### ISSUE TITLE
Get odex smali (with optimized opcode) from oat/odex

### ISSUE THREAD

**Issue by zinian** [liudongmiao/Brevent#1]
把 services 转成 smali
安卓5.0-5.1应该可以省略一些步骤

Get odex smali (with optimized opcode) from oat/odex
```
  java -jar oat2dex.jar smali services.odex
```
https://github.com/testwhat/SmaliEx

**Comment by liudongmiao** [comment]
通过对比，里面有一些 vtable, field 之类。
反正在我本机的时候，都没法使用 smali 回 classes.dex 。
如果你确认这样的代码 smali 回去以后可以执行，请告诉我。

**Comment by zinian** [comment]
@liudongmiao 我的也不能 smali 回 classes.dex 。
