### ISSUE TITLE
Magisk模块：Android 7.1.1（NPF10C） 的 Nexus 5X（Bullhead）

### ISSUE THREAD

**Issue by oyrx** [liudongmiao/Brevent#1]
https://github.com/oyrx/Brevent-Patch-Module-For-Android-7.1.1-Nexus-5X-NPF10C

**Comment by aviraxp** [comment]
……………………发这里来干什么………………还有上传的时候建议注意authorship

**Comment by oyrx** [comment]
别人好找一点
