### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by amdth** [liudongmiao/Brevent#101]
独立开发者的作品，不可能也不打算满足每一个人的需求，谢谢理解！（冰箱作者语）
希望柳大先满足自己的使用需求，勿忘初心！不要去迎合那些小白！感觉近来黑域出尽了风头，相应的小学生也多了很多，他们遇到问题都不看评论，直接提问开新帖，根本不考虑开发者，太自私了；也有很多强迫症者要求立即强杀，一段时间后强杀，root用户重启不失效等等，在我看来都是没有一个好的使用习惯，老大可以按照自己的使用逻辑来给他们定义使用方法！
老大若有时间和精力可以开发捐赠版，但是建议收费高一点！
希望老大坚持开发黑域，我也会继续捐赠以表支持！有了黑域感觉安卓比iOS省心了

**Comment by amdth** [comment]
另外建议老大在GIthub里面回复，门槛高一点，小白少一点

**Comment by liudongmiao** [comment]
我也希望只到github啊，play啊提建议。但是，不太现实。所以，有空我也去酷安看下。

收费与否，意义不大，毕竟再怎么捐赠，真的用户很少。接下来，会考虑 root 版，不使用目前网络监听技术，必须要捐赠才能使用，不愿意捐赠的，自己下源码编译就好。

**Comment by amdth** [comment]
那adb版应该会继续开发吧！不想root，只想安心使用手机

2017年2月21日 上午10:03 於 "Liu DongMiao" <notifications@github.com> 寫道：

**Comment by liudongmiao** [comment]
肯定会的，我不会root，哈哈～

**Comment by wudimenghuan** [comment]
@amdth 有想法是应该说出来的，而不是什么建议都不提，而且liudongmiao也欢迎大家提建议啊
关于收费的问题。。。阻止运行出来的时候都没收费，如果你想让作者收费，那竞争对手就高兴了，阻止了黑域的流行。
root用户重启不失效是一个好事啊，这和使用习惯有什么关系，我坐车的时候不小心死机重启了，然后没有电脑启动黑域，就只能看着手机发热又死机，重启发热又死机。。。不断循环（本人装了大概300个应用，国产全家桶毒瘤APP基本都在）

**Comment by liudongmiao** [comment]
感谢建议～
