### ISSUE TITLE
cannot listen port...

### ISSUE THREAD

**Issue by manhong2112** [liudongmiao/Brevent#102]
Mi5 32GB, Android 7.1, Omni Rom
gemini:/ $ /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
[brevent.txt](https://github.com/liudongmiao/Brevent/files/788106/brevent.txt)

**Comment by manhong2112** [comment]
詭異的是, 我再執行一次後, 又成功了...

**Comment by liudongmiao** [comment]
你这个显示了内存不够，找下rom提供者。之前也遇到过。

**Comment by manhong2112** [comment]
謎的是 3GB ram也會out of memory?....嘛算了我換個rom...

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
