### ISSUE TITLE
一直停留在进程获取状态中

### ISSUE THREAD

**Issue by PHizing** [liudongmiao/Brevent#103]
已经用adb执行并阻止了几个程序，但过一会再进app就有个进程获取状态的图标一直转，没办法看到程序列表了。
系统是氢3.0，黑域是0.7。

**Comment by PHizing** [comment]
系统没有Root

**Comment by liudongmiao** [comment]
使用日志报告工具看看，有可能已经异常。另外，使用最新版的 adb

**Comment by PHizing** [comment]
OnePlus3T:/ $ logcat -b main -d -s BreventLoader BreventServer
02-22 19:36:31.567  8299  8308 D BreventServer: checking
02-22 19:38:10.577  8299  8308 D BreventServer: checking
02-22 19:39:42.884  8299  8308 D BreventServer: checking
02-22 19:39:51.011  8299  8308 D BreventServer: checking
02-22 19:41:08.529  8299  8308 D BreventServer: checking
02-22 19:41:11.531  8299  8308 D BreventServer: checking
02-22 19:42:57.808  8299  8308 D BreventServer: checking
02-22 19:43:30.153  8299  8308 I BreventServer: reset home tid to 1771
02-22 19:43:33.169  8299  8308 D BreventServer: checking

**Comment by PHizing** [comment]
用的是最新的adb 1.0.36，谷歌下载的。

**Comment by muziling** [comment]
我也是，要等很久，后台类似这种信息有上百条
`
02-23 14:06:39.122 W/pool-4-thread-1(29963): type=1400 audit(0.0:62069): avc: denied { ioctl } for path="socket:[467719]" dev="sockfs" ino=467719 ioctlcmd=891d scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=udp_socket permissive=0`

**Comment by PHizing** [comment]
我这里等很久都没用

**Comment by liudongmiao** [comment]
看下最新的 0.7.1 吧

**Comment by PHizing** [comment]
OnePlus3T:/ $ logcat -b main -d -s BreventLoader BreventServer                     
02-28 15:30:40.674 21488 21488 D BreventLoader: lib: /data/user_de/0/com.android   
.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so     
02-28 15:30:40.682 21488 21497 D BreventServer: Brevent Server 0.7.7 started       
02-28 15:30:40.686 21488 21497 D BreventServer: brevent user: 0                    
02-28 15:30:40.687 21488 21497 D BreventServer: brevent data directory: /data/us   
er_de/0/com.android.shell                                                          
02-28 15:30:40.776 21488 21497 I BreventServer: load /data/user_de/0/com.android   
.shell/me.piebridge.brevent.list, size: 35                                         
02-28 15:30:40.776 21488 21497 D BreventServer: loaded brevent list                
02-28 15:30:40.776 21488 21497 D BreventServer: loaded brevent conf                
02-28 15:30:40.784 21488 21497 D BreventServer: checking                           
02-28 15:30:41.097 21488 21497 I BreventServer: power_screen_state, tag: 2728, e   
vent: 7                                                                            
02-28 15:30:41.098 21488 21497 I BreventServer: notification_cancel_all, tag: 27   
52, event: 6                                                                       
02-28 15:30:41.101 21488 21497 I BreventServer: am_new_intent, tag: 30003, event   
: 2                                                                                
02-28 15:30:41.102 21488 21497 I BreventServer: am_pause_activity, tag: 30013, e   
vent: 3                                                                            
02-28 15:30:41.102 21488 21497 I BreventServer: am_proc_start, tag: 30014, event   
: 4                                                                                
02-28 15:30:41.104 21488 21497 I BreventServer: am_switch_user, tag: 30041, even   
t: 5                                                                               
02-28 15:30:41.105 21488 21497 I BreventServer: am_focused_activity, tag: 30043,   
 event: 1                                                                          
02-28 15:31:00.842 21488 21497 D BreventServer: checking                           
02-28 15:31:27.269 21488 21497 D BreventServer: checking                           
02-28 15:32:36.809 21488 21497 D BreventServer: checking                           
02-28 15:32:39.510 21488 21497 D BreventServer: checking

**Comment by PHizing** [comment]
02-28 15:33:40.075 22157 22157 D BreventLoader: lib: /data/user_de/0/com.android
.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
02-28 15:33:40.083 22157 22166 D BreventServer: Brevent Server 0.7.7 started
02-28 15:33:40.085 22157 22166 D BreventServer: brevent user: 0
02-28 15:33:40.086 22157 22166 D BreventServer: brevent data directory: /data/us
er_de/0/com.android.shell
02-28 15:33:40.142 22157 22166 I BreventServer: load /data/user_de/0/com.android
.shell/me.piebridge.brevent.list, size: 35
02-28 15:33:40.142 22157 22166 D BreventServer: loaded brevent list
02-28 15:33:40.142 22157 22166 D BreventServer: loaded brevent conf
02-28 15:33:40.150 22157 22166 D BreventServer: checking
02-28 15:33:40.643 22157 22166 I BreventServer: power_screen_state, tag: 2728, e
vent: 7
02-28 15:33:40.644 22157 22166 I BreventServer: notification_cancel_all, tag: 27
52, event: 6
02-28 15:33:40.646 22157 22166 I BreventServer: am_new_intent, tag: 30003, event
: 2
02-28 15:33:40.647 22157 22166 I BreventServer: am_pause_activity, tag: 30013, e
vent: 3
02-28 15:33:40.647 22157 22166 I BreventServer: am_proc_start, tag: 30014, event
: 4
02-28 15:33:40.648 22157 22166 I BreventServer: am_switch_user, tag: 30041, even
t: 5
02-28 15:33:40.649 22157 22166 I BreventServer: am_focused_activity, tag: 30043,
 event: 1
02-28 15:34:53.287 22157 22166 D BreventServer: checking
02-28 15:35:06.665 22271 22271 D BreventLoader: lib: /data/user_de/0/com.android
.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
02-28 15:35:06.673 22271 22280 D BreventServer: Brevent Server 0.7.7 started

**Comment by PHizing** [comment]
02-28 15:35:06.675 22271 22280 D BreventServer: brevent user: 0
02-28 15:35:06.677 22271 22280 D BreventServer: brevent data directory: /data/us
er_de/0/com.android.shell
02-28 15:35:06.706 22271 22280 I BreventServer: load /data/user_de/0/com.android
.shell/me.piebridge.brevent.list, size: 35
02-28 15:35:06.706 22271 22280 D BreventServer: loaded brevent list
02-28 15:35:06.707 22271 22280 D BreventServer: loaded brevent conf
02-28 15:35:06.712 22271 22280 D BreventServer: checking
02-28 15:35:07.156 22271 22280 I BreventServer: power_screen_state, tag: 2728, e
vent: 7
02-28 15:35:07.157 22271 22280 I BreventServer: notification_cancel_all, tag: 27
52, event: 6
02-28 15:35:07.159 22271 22280 I BreventServer: am_new_intent, tag: 30003, event
: 2
02-28 15:35:07.160 22271 22280 I BreventServer: am_pause_activity, tag: 30013, e
vent: 3
02-28 15:35:07.160 22271 22280 I BreventServer: am_proc_start, tag: 30014, event
: 4
02-28 15:35:07.161 22271 22280 I BreventServer: am_switch_user, tag: 30041, even
t: 5
02-28 15:35:07.161 22271 22280 I BreventServer: am_focused_activity, tag: 30043,
 event: 1
02-28 15:35:09.165 22271 22280 D BreventServer: checking

**Comment by PHizing** [comment]
无可奈何的感觉。
老是刚装就正常，后面就看不到程序列表了。换到0.7.7也是如此。

**Comment by liudongmiao** [comment]
日志看起来没有什么异常。你看下你的 rom 有没有禁止别的应用获取安装的应用列表之类。

**Comment by PHizing** [comment]
这就奇怪了。我这原生的氢3.0，没改过啥。刚装的时候是正常的。

**Comment by liudongmiao** [comment]
十天内没有继续反馈，关闭。

**Comment by muziling** [comment]
我用的是rescurrection remix的ROM，也是一样。不知道老外的ROM有做了什么改动，但dirty unicorm之类的应该都有这个问题。

**Comment by liudongmiao** [comment]
最新版还是这样的问题么？

**Comment by muziling** [comment]
对，就是用最新版的，查了下应用是连这个端口，但这个端口没有东西在监听
shamu:/ # netstat -anp|grep 59526
tcp6       0      1 ::1:42703               ::1:59526               SYN_SENT    29089/me.piebridge.brevent

**Comment by liudongmiao** [comment]
你得看日志啊，应用详情里都有，包括 crash 和 BreventServer 日志

[如何反馈]
有问题建议带上详细日志，前往 github: https://github.com/liudongmiao/Brevent/issues
1. 崩溃日志(电脑命令行)：adb -d logcat -d -b crash
2. 黑域服务日志(电脑命令行)：adb -d logcat -d -s BreventServer BreventLoader
2.1 如果想开启黑域服务调试日志，请在电脑命令行中执行: adb -d setprop log.tag.BreventServer DEBUG 然后获取黑域服务日志
2.2 如果要关闭黑域服务调试日志，请在电脑命令行中执行: adb -d setprop log.tag.BreventServer \"\" (注意这个反斜杠)

**Comment by muziling** [comment]
没有crash 的log，DEBUG开起来的日志：

> 03-15 16:59:48.680 31523 31523 I BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/
com.android.shell/brevent/libloader.so
03-15 16:59:48.734 31523 31535 I BreventServer: Brevent Server 0.8.7 started
03-15 16:59:48.751 31523 31535 I BreventServer: brevent user: 0
03-15 16:59:48.754 31523 31535 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-15 16:59:48.949 31523 31535 I BreventServer: loading brevent list
03-15 16:59:48.949 31523 31535 I BreventServer: loading brevent conf
03-15 16:59:49.097 31523 31535 D BreventServer: power_screen_state, tag: 2728, event: 7
03-15 16:59:49.099 31523 31535 D BreventServer: notification_cancel_all, tag: 2752, event: 6
03-15 16:59:49.108 31523 31535 D BreventServer: am_new_intent, tag: 30003, event: 2
03-15 16:59:49.110 31523 31535 D BreventServer: am_pause_activity, tag: 30013, event: 3
03-15 16:59:49.111 31523 31535 D BreventServer: am_proc_start, tag: 30014, event: 4
03-15 16:59:49.114 31523 31535 D BreventServer: am_switch_user, tag: 30041, event: 5
03-15 16:59:49.115 31523 31535 D BreventServer: am_focused_activity, tag: 30043, event: 1
03-15 16:59:49.219 31523 31535 D BreventServer: sent first status
03-15 16:59:53.549 31523 31535 D BreventServer: check and brevent
03-15 16:59:53.608 31523 31535 D BreventServer: widgets: {}
03-15 16:59:53.608 31523 31535 D BreventServer: running: {me.piebridge.prevent=29224, com.tencent.mm=25686, ru.kingbird.
doggame=19356, tk.schspa.preventpatch=27391, muziling.forum=29970, com.topjohnwu.magisk=27486, com.mixplorer=28677, com.
coolapk.market=28150, com.android.settings=27531, net.jejer.hipda.ng=29970, com.hobbyone.HashDroid=17801, com.yandex.bro
wser=28237, dev.ukanth.ufirewall.donate=29391}
03-15 16:59:53.608 31523 31535 D BreventServer: top: {}
03-15 16:59:53.609 31523 31535 D BreventServer: home: {com.teslacoilsw.launcher, com.android.systemui}
03-15 16:59:53.609 31523 31535 D BreventServer: current: null
03-15 16:59:53.609 31523 31535 D BreventServer: recent: {com.teslacoilsw.launcher, com.hexin.plat.android, me.piebridge.
prevent, com.tencent.mm, ru.kingbird.doggame, tk.schspa.preventpatch, rikka.appops, com.topjohnwu.magisk, com.mixplorer,
 com.coolapk.market, com.candykk.android.dialer, com.android.settings, com.yandex.browser, com.android.systemui, dev.uka
nth.ufirewall.donate, com.deified.robot.auotorobot}
03-15 16:59:53.727 31523 31535 D BreventServer: com.mixplorer.addon.archive depended by {com.mixplorer}
03-15 16:59:53.727 31523 31535 D BreventServer: com.android.webview depended by {com.google.android.gms}
03-15 16:59:53.727 31523 31535 D BreventServer: com.google.android.gms depended by {com.teslacoilsw.launcher, com.androi
d.vending, ru.kingbird.doggame, com.google.android.apps.youtube.kids, com.yandex.browser}
03-15 16:59:53.729 31523 31535 D BreventServer: back: {}
03-15 16:59:53.729 31523 31535 D BreventServer: service: {}
03-15 16:59:53.729 31523 31535 D BreventServer: blocking: {}
03-15 16:59:53.729 31523 31535 D BreventServer: noRecent: {}
03-15 16:59:53.729 31523 31535 D BreventServer: unsafe: {}
03-15 16:59:53.729 31523 31535 D BreventServer: final blocking: {}
03-15 16:59:53.729 31523 31535 D BreventServer: notifications: {com.tencent.mm=null}
03-15 16:59:53.729 31523 31535 D BreventServer: foreground service: {}
03-15 17:00:31.258 31523 31535 E BreventServer: Don't receive answer from universe

**Comment by liudongmiao** [comment]
> Don't receive answer from universe

你看下，有没有禁用系统的日志，主要是事件日志，开发者选项里看下。

你可以这样尝试下:
```
adb logcat -d -b events
```

**Comment by muziling** [comment]
这个命令能输出一大堆日志，开发者选项里没找到对应项

> 03-15 17:34:06.338  1500  1869 I sysui_action: [323,com.android.development/.Development]
03-15 17:34:06.338  1500  1869 I sysui_action: [324,false]
03-15 17:34:06.338  1500  1869 I sysui_action: [325,754]
03-15 17:34:06.346  4909  4909 I sysui_view_visibility: [39,0]
03-15 17:34:06.347  4909  4909 I am_on_paused_called: [0,com.android.settings.Settings$DevelopmentSettingsActivity,handl
ePauseActivity]
03-15 17:34:06.382  1500  2702 I am_proc_start: [0,6459,1000,com.android.development,activity,com.android.development/.D
evelopment]
03-15 17:34:06.427  1500  1521 I sysui_action: [321,142]
03-15 17:34:06.427  1500  1511 I am_proc_bound: [0,6459,com.android.development]
03-15 17:34:06.433  1500  1511 I am_restart_activity: [0,70520757,195,com.android.development/.Development]
03-15 17:34:06.443  1500  1521 I sysui_action: [320,1]
03-15 17:34:06.443  1500  1521 I sysui_action: [319,158]
03-15 17:34:06.468  1500  1513 I am_pss  : [4909,1000,com.android.settings,85164032,74989568,0]
03-15 17:34:06.502  1500  1513 I am_pss  : [5626,1000,org.cyanogenmod.cmparts,4865024,3817472,0]
03-15 17:34:06.633  6459  6459 I am_on_resume_called: [0,com.android.development.Development,LAUNCH_ACTIVITY]
03-15 17:34:07.046  1500  1521 I sysui_action: [322,761]
03-15 17:34:07.046  1500  1521 I am_activity_launch_time: [0,70520757,com.android.development/.Development,683,683]
03-15 17:34:07.065  1500  1512 I am_stop_activity: [0,37332016,com.android.settings/.Settings$DevelopmentSettingsActivit
y]
03-15 17:34:07.077  4909  4909 I am_on_stop_called: [0,com.android.settings.Settings$DevelopmentSettingsActivity,handleS
topActivity]
03-15 17:34:07.095   946   946 I sf_frame_dur: [com.android.settings/com.android.settings.Settings$DevelopmentSettingsAc
tivity,295,10,2,0,2,5,1]
03-15 17:34:07.118  1500  1513 I am_pss  : [5047,10119,com.tencent.mm,73631744,67588096,0]
03-15 17:34:07.140  1500  1513 I am_pss  : [4798,10119,com.tencent.mm:push,16241664,11776000,0]
03-15 17:34:07.159  1500  1513 I am_pss  : [5491,10097,tk.schspa.preventpatch,7160832,6275072,0]
03-15 17:34:07.183  1500  1513 I am_pss  : [2720,10112,com.deified.robot.auotorobot,14240768,12566528,0]
03-15 17:34:07.205  1500  1513 I am_pss  : [4638,10122,com.chinatelecom.mihao,35226624,33333248,0]
03-15 17:34:07.229  1500  1513 I am_pss  : [5062,10104,com.netease.cloudmusic:play,15048704,10678272,0]
03-15 17:34:07.254  1500  1513 I am_pss  : [5015,10104,com.netease.cloudmusic:pushservice,8931328,7286784,0]
03-15 17:34:07.280  1500  1513 I am_pss  : [5547,10049,com.android.vending,14304256,12587008,0]
03-15 17:34:07.302  1500  1513 I am_pss  : [5475,10093,com.baidu.input_huawei,25834496,24166400,0]
03-15 17:34:07.322  1500  1513 I am_pss  : [5438,10078,org.cyanogenmod.profiles,3078144,2420736,0]
03-15 17:34:07.340  1500  1513 I am_pss  : [4733,10133,com.mobiledirection.proximitysensorreset,4940800,4186112,0]
03-15 17:34:07.357  1500  1513 I am_pss  : [4543,1000,com.qualcomm.telephony,2624512,1966080,0]
03-15 17:34:07.375  1500  1513 I am_pss  : [3776,10063,com.audlabs.viperfx,4400128,3715072,0]

**Comment by liudongmiao** [comment]
那就开启黑域服务的 VERBOSE 日志吧：`adb -d setprop log.tag.BreventServer VERBOSE`

**Comment by liudongmiao** [comment]
然后给黑域服务的日志：`adb -d logcat -d -s BreventServer`

**Comment by muziling** [comment]
> C:\Users\Administrator>adb -d logcat -d -s BreventServer
--------- beginning of system
--------- beginning of crash
--------- beginning of main
03-16 09:05:19.158   517   527 I BreventServer: Brevent Server 0.8.7 started
03-16 09:05:19.176   517   527 I BreventServer: brevent user: 0
03-16 09:05:19.178   517   527 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-16 09:05:19.404   517   527 I BreventServer: loading brevent list
03-16 09:05:19.404   517   527 I BreventServer: loading brevent conf
03-16 09:05:19.572   517   527 D BreventServer: power_screen_state, tag: 2728, event: 7
03-16 09:05:19.574   517   527 D BreventServer: notification_cancel_all, tag: 2752, event: 6
03-16 09:05:19.581   517   527 D BreventServer: am_new_intent, tag: 30003, event: 2
03-16 09:05:19.583   517   527 D BreventServer: am_pause_activity, tag: 30013, event: 3
03-16 09:05:19.584   517   527 D BreventServer: am_proc_start, tag: 30014, event: 4
03-16 09:05:19.587   517   527 D BreventServer: am_switch_user, tag: 30041, event: 5
03-16 09:05:19.587   517   527 D BreventServer: am_focused_activity, tag: 30043, event: 1
03-16 09:05:19.607   517   527 V BreventServer: get running activities
03-16 09:05:19.640   517   527 V BreventServer: get running processes
03-16 09:05:19.679   517   527 D BreventServer: sent first status
03-16 09:05:19.680   517   528 D BreventServer: received feelgood
03-16 09:05:43.345   517   528 V BreventServer: power_screen_state: {offOrOn=1, touchCycles=0, totalTouchDownTime=0, becauseOfUser=0}
03-16 09:05:46.408   517   527 D BreventServer: check and brevent
03-16 09:05:46.409   517   527 V BreventServer: get running activities
03-16 09:05:46.424   517   527 D BreventServer: widgets: {}
03-16 09:05:46.425   517   527 D BreventServer: running: {com.android.vending=11131, com.tencent.mm=54317, com.android.dialer=56656, com.mixplorer=15568, com.android.settings=1253, net.jejer.hipda.ng=56534}
03-16 09:05:46.425   517   527 D BreventServer: top: {net.jejer.hipda.ng}
03-16 09:05:46.425   517   527 D BreventServer: home: {com.teslacoilsw.launcher, com.android.systemui}
03-16 09:05:46.425   517   527 D BreventServer: current: null
03-16 09:05:46.425   517   527 D BreventServer: recent: {com.teslacoilsw.launcher, com.tencent.mm, com.google.android.deskclock, org.xdty.callerinfo, com.textra, net.jejer.hipda.ng, com.android.systemui, com.deified.robot.auotorobot}
03-16 09:05:46.454   517   527 V BreventServer: get running processes
03-16 09:05:46.573   517   527 D BreventServer: com.mixplorer.addon.archive depended by {com.mixplorer}
03-16 09:05:46.573   517   527 D BreventServer: com.google.android.gms depended by {com.teslacoilsw.launcher, com.android.vending, com.google.android.apps.youtube.kids, com.textra}
03-16 09:05:46.576   517   527 D BreventServer: back: {}
03-16 09:05:46.576   517   527 D BreventServer: service: {}
03-16 09:05:46.576   517   527 D BreventServer: blocking: {}
03-16 09:05:46.576   517   527 D BreventServer: noRecent: {}
03-16 09:05:46.576   517   527 D BreventServer: unsafe: {}
03-16 09:05:46.576   517   527 D BreventServer: final blocking: {}
03-16 09:05:46.576   517   527 D BreventServer: notifications: {com.tencent.mm=null}
03-16 09:05:46.576   517   527 D BreventServer: foreground service: {}
03-16 09:05:50.654   517   528 V BreventServer: am_new_intent: {action=android.intent.action.MAIN, mimeType=NULL, taskId=194, uri=NULL, user=0, flags=270532608, token=188766682, componentName=com.teslacoilsw.launcher/.NovaLauncher}
03-16 09:05:50.657   517   528 V BreventServer: am_focused_activity: {reason=bringingFoundTaskToFront, user=0, componentName=com.teslacoilsw.launcher/.NovaLauncher}
03-16 09:05:50.657   517   527 V BreventServer: tid: 2018, homeTid: 2018, mHomeTid: 0, possibleHomeTid: 2018
03-16 09:05:50.658   517   528 V BreventServer: am_pause_activity: {user=0, token=260852669, componentName=net.jejer.hipda.ng/.MainActivity-Original}
03-16 09:05:53.175   517   528 V BreventServer: am_focused_activity: {reason=startedActivity, user=0, componentName=me.piebridge.brevent/.ui.BreventActivity}
03-16 09:05:53.178   517   528 V BreventServer: am_pause_activity: {user=0, token=208423185, componentName=com.teslacoilsw.launcher/.NovaLauncher}
03-16 09:05:53.376   517   528 V BreventServer: am_proc_start: {component=me.piebridge.brevent/.ui.BreventActivity, pid=577, uid=10099, type=activity, user=0, processName=me.piebridge.brevent}
03-16 09:05:53.740   517   527 D BreventServer: check and brevent
03-16 09:05:53.741   517   527 V BreventServer: get running activities
03-16 09:05:53.773   517   527 D BreventServer: widgets: {}
03-16 09:05:53.773   517   527 D BreventServer: running: {com.android.vending=11131, com.tencent.mm=54317, me.piebridge.brevent=56663, com.android.dialer=56663, com.mixplorer=15568, com.android.settings=1253, net.jejer.hipda.ng=56660}
03-16 09:05:53.774   517   527 D BreventServer: top: {me.piebridge.brevent}
03-16 09:05:53.774   517   527 D BreventServer: home: {com.teslacoilsw.launcher, com.android.systemui}
03-16 09:05:53.774   517   527 D BreventServer: current: me.piebridge.brevent
03-16 09:05:53.774   517   527 D BreventServer: recent: {com.teslacoilsw.launcher, com.tencent.mm, me.piebridge.brevent, com.google.android.deskclock, org.xdty.callerinfo, com.textra, net.jejer.hipda.ng, com.android.systemui, com.deified.robot.auotorobot}
03-16 09:05:53.806   517   527 V BreventServer: get running processes
03-16 09:05:53.879   517   527 D BreventServer: com.mixplorer.addon.archive depended by {com.mixplorer}
03-16 09:05:53.880   517   527 D BreventServer: com.google.android.gms depended by {com.teslacoilsw.launcher, com.android.vending, com.google.android.apps.youtube.kids, com.textra}
03-16 09:05:53.882   517   527 D BreventServer: back: {}
03-16 09:05:53.882   517   527 D BreventServer: service: {}
03-16 09:05:53.882   517   527 D BreventServer: blocking: {}
03-16 09:05:53.883   517   527 D BreventServer: noRecent: {}
03-16 09:05:53.883   517   527 D BreventServer: unsafe: {}
03-16 09:05:53.883   517   527 D BreventServer: final blocking: {}
03-16 09:05:53.883   517   527 D BreventServer: notifications: {com.tencent.mm=null}
03-16 09:05:53.883   517   527 D BreventServer: foreground service: {}

**Comment by liudongmiao** [comment]
没有看到有什么具体的错误，下个版本将会修复更新时可能的 "Don't receive answer from universe"

**Comment by liudongmiao** [comment]
十天未汇报，关闭。

**Comment by muziling** [comment]
看了jni的代码，会使用 
export CLASSPATH=/data/app/me.piebridge.brevent-1/base.apk
app_process /system/bin --nice-name=brevent_server me.piebridge.brevent.server.BreventServer
两条命令来启进程，启动黑域的时候是不是也同时会启这个进程，
如果是的话，我查了，我的机器没有同时启起来。

不知道是否和下面的这个有关系
https://github.com/miracle2k/android-autostarts/issues/13

**Comment by liudongmiao** [comment]
那就发日志。

1. 不要试图 root 运行，有些能，有些不能，我不支持
2. 不要试图以非 shell 帐号运行，它们基本没有权限

最新测试版： https://piebridge.me/br/next/

**Comment by muziling** [comment]
不知道是不是IPV6的问题，还是说是因为非shell用户连接不了shell启的监听端口，::1是哪个用户监听，只能哪个用户连接？

`tcp        0      0 ::1:59526               :::*                    LISTEN      4526/brevent_server
tcp        0      1 ::1:47531               ::1:59526               SYN_SENT    -
shamu:/ $ ps|grep bre
shell     4509  1     3732   460   sigsuspend a8cde85c S brevent_daemon
shell     4526  4509  1436528 43272 SyS_epoll_ b393b514 S brevent_server
u0_a140   6091  318   1233748 57680 SyS_epoll_ 00000000 S me.piebridge.brevent
`

**Comment by liudongmiao** [comment]
与 ipv6 无关

**Comment by muziling** [comment]
我感觉就是监听的IP地址有问题，其它应用都是监听:::，只有brevent是监听::1

> :/data/data # netstat -anp|grep LISTEN
tcp        0      0 ::1:59526               :::*                    LISTEN      5088/brevent_server
tcp        0      0 :::51688                :::*                    LISTEN      2251/com.unionpay:pu
tcp        0      0 :::61323                :::*                    LISTEN      4096/com.netease.clo

**Comment by liudongmiao** [comment]
为了安全，我故意只监听本地网络，是对用户安全的考虑。

你可以带上日志，看日志中有没有发送广播的日志，以及你没有其它类似软件，阻断 shell 发出广播到黑域。

不要使用任何方式破解黑域。如有需要，电脑上安装  teamviewer，帐号密码发我邮箱： br@piebridge.me
