### ISSUE TITLE
初始配置时总是请求运行so

### ISSUE THREAD

**Issue by marcher233** [liudongmiao/Brevent#105]
使用Play最新版本Brevent时，如果在初始配置正确运行了.so之后（输出successful），不立刻对某个应用进行一次“黑域”操作，那么关闭Brenvent一段时间（或从最近任务划掉）并再次启动时仍然会提示需要再次连接电脑运行.so。希望能改善。

测试设备：Pixel (Android 7.1.1, Patch level: Feb. 2017)
测试版本：Brevent 0.7 (Play Store)

**Comment by liudongmiao** [comment]
请使用最新的  adb 版本看下。
我也是 pixel 

#74 #94

**Comment by liudongmiao** [comment]
windows: http://dl.google.com/android/repository/platform-tools_r25.0.3-windows.zip
mac: http://dl.google.com/android/repository/platform-tools_r25.0.3-macosx.zip
linux: http://dl.google.com/android/repository/platform-tools_r25.0.3-linux.zip

**Comment by marcher233** [comment]
谢谢您！经测试，重装Brevent后使用最新版本的adb，一切正常！
https://dl.google.com/android/repository/platform-tools-latest-windows.zip

**Comment by liudongmiao** [comment]
我认真看了下。

在 1.0.32 里，执行完命令，直接退出了，然后会把 brevent_server 给杀掉。解决办法，分两次进行。

在 1.0.36 里，一次执行完命令，不会退出。所以这种是可以的。
