### ISSUE TITLE
Status bar 时间突然停止更新

### ISSUE THREAD

**Issue by lancelotly** [liudongmiao/Brevent#106]
使用一段时间后，状态栏的时间都会停止更新，只能打开 System UI Tuner 让时间显示秒，然后才不停变化。查看 System UI 在 Framework Apps 里，并不能被黑。求解。
（同 Pixel）

**Comment by liudongmiao** [comment]
你再想想，有没有阻止其它软件，特别是框架应用里是否存在被block。

如果出现，基本无法恢复，建议重启手机。

有一次我也遇到，是之前不当阻止框架软件导致。

**Comment by lancelotly** [comment]
框架应用里的都有感叹号，没有阻止任何一个。系统应用里阻止了 Play store, maps, camera, download, download manager, drive, photos，没啦，其他都没有阻止。

**Comment by liudongmiao** [comment]
你需要显示所有应用，再看一遍。默认好多应用都不显示的。

**Comment by lancelotly** [comment]
三个选项卡全开了，真显示了所有应用，我再等等看看～感觉是 download manager 的祸…没黑它之前时钟一直走，后来就不行了

**Comment by marcher233** [comment]
建议不要随便黑框架类应用，“绿色守护”在前几个版本中如果开启类似“浅层休眠”的功能便会影响系统时钟显示。

**Comment by liudongmiao** [comment]
你清空了之后，重启再看效果。

框架类，本来就是不能阻止的。当然，目前有核心破解的，下个版本，我应该会使用反核心破解技术，准确识别是否为框架应用。
