### ISSUE TITLE
Donation 里没有对 M 适配申请权限

### ISSUE THREAD

**Issue by aviraxp** [liudongmiao/Brevent#108]
这样微信捐赠就显示不出来，本来想给你 commit 一下的，但是不知道你想怎么处理。

**Comment by aviraxp** [comment]
https://github.com/liudongmiao/Brevent/blob/master/donation/src/main/java/me/piebridge/donation/DonateActivity.java#L193

**Comment by liudongmiao** [comment]
https://github.com/liudongmiao/Brevent/blob/master/donation/src/main/java/me/piebridge/donation/DonateActivity.java#L338

这里，优先级调一下就好。

当然，我实际来的是两个方法，mayHasPermission 和 hasPermission.

不想 M 里有，很简单，不想多要一个权限，而微信捐赠体验并不好。

我已经修复，代码没有 push

**Comment by liudongmiao** [comment]
这个是一个捐赠的公共类，会用到其它项目。所以，并不在这里申请权限。
