### ISSUE TITLE
玩坏了短信……

### ISSUE THREAD

**Issue by aegishe** [liudongmiao/Brevent#109]
大概流程是这样——
1）早先黑域可以阻止系统应用甚至框架，我就把短信呀gmail之类的顺手阻止了
2）然后似乎黑域更新过一次，当时似乎有看到一些我原先阻止的系统应用状态是启动，但阻止的图标还在
若干天后……
3）更新了最新的黑域，还没具体发现
4）然后昨天突然意识到好几天没收到短信，从银行、支付宝到格瓦拉，但在打开messenger应用的时候可以收到，退出后就无法收到新的了。同时把短信应用切换到环聊，一切正常。
顺带发现gmail也是如此，没新邮件通知。然后我还忘记其他有什么重要应用被我阻止过，然后现在黑域里面显示那些应用都是没阻止状态，但其实系统底层是已经阻止了吧？

**Comment by aegishe** [comment]
用过adb shell appops set com.google.android.apps.messaging RUN_IN_BACKGROUND allow和default，好像没用

**Comment by liudongmiao** [comment]
就直接把所有的应用，全部设为 allow

1. 进入手机
```
cmd> adb -d shell
```

2. 执行以下命令
```
cmd appops query-op RUN_IN_BACKGROUND | while read line; do echo $line; cmd appops set $line RUN_IN_BACKGROUND allow; done
```

3. 如果还异常，给应用的单独设定看下。
```
cmd appops get com.google.android.apps.messaging 
```
特别注意下 XXX_SMS 之类的权限。

**Comment by aegishe** [comment]
结果如下
c:\adb>adb -d shell
line; cmd appops set $line RUN_IN_BACKGROUND allow; done                      <
com.android.nfc
com.google.android.contacts
com.google.android.packageinstaller
com.google.android.partnersetup
com.android.dreams.basic
com.google.android.apps.docs
com.google.android.syncadapters.contacts
com.google.android.apps.photos
com.google.android.gm
com.android.printspooler
com.farproc.wifi.analyzer
com.google.android.youtube
com.google.android.apps.docs.editors.docs
com.google.android.apps.docs.editors.sheets
com.neuralprisma
com.shazam.android
com.zhan_dui.evermemo
com.eg.android.AlipayGphone
com.coolapk.market
com.gotokeep.keep
com.lonelycatgames.Xplore
com.tumblr
com.google.android.ext.services
com.valvesoftware.android.steam.community
com.innologica.inoreader
com.baidu.BaiduMap
com.dropbox.android
com.evernote
com.sony.playmemories.mobile
com.hazuu.tumblersave
org.zwanoo.android.speedtest
com.zhuishushenqi.stejke6
com.sdu.didi.psnger
com.niksoftware.snapseed
com.app.pornhub
com.dianping.v1
bullhead:/ $ cmd appops get com.google.android.apps.messaging
VIBRATE: allow; time=+9d19h56m13s810ms ago; duration=+392ms
READ_CONTACTS: allow; time=+14m54s132ms ago
WRITE_CONTACTS: allow; time=+11h43m24s853ms ago
POST_NOTIFICATION: allow; time=+49m26s459ms ago
CALL_PHONE: allow; time=+172d2h36m18s953ms ago
READ_SMS: allow; time=+49m26s967ms ago
WRITE_SMS: allow; time=+49m23s103ms ago
RECEIVE_SMS: allow; time=+49m16s231ms ago
RECEIVE_MMS: allow; time=+6d21h43m6s448ms ago
SEND_SMS: allow; time=+11h38m37s858ms ago
READ_ICC_SMS: allow; time=+13h0m51s392ms ago
READ_CLIPBOARD: allow; time=+14d13h37m7s543ms ago
WRITE_CLIPBOARD: allow; time=+46d21h47m22s147ms ago
TAKE_AUDIO_FOCUS: allow; time=+13h44m19s120ms ago
WAKE_LOCK: allow; time=+9m44s677ms ago; duration=+304ms
OP_READ_PHONE_STATE: allow; time=+14m54s147ms ago
READ_EXTERNAL_STORAGE: allow; time=+14m56s368ms ago
WRITE_EXTERNAL_STORAGE: allow; time=+14m56s368ms ago
RUN_IN_BACKGROUND: allow; time=+9m44s761ms ago
bullhead:/ $

**Comment by liudongmiao** [comment]
你再试下可否接收短信

**Comment by aegishe** [comment]
测试了下短信和邮件，看起来 正常了，其他这些allow了就应该也没问题了吧

**Comment by liudongmiao** [comment]
默认应该都是 allow

**Comment by aegishe** [comment]
那就可以装回黑域了吧

**Comment by liudongmiao** [comment]
装吧。其实也可以不用卸载的。我只是用这种极端方式，告诉你，和黑域不太相关。

**Comment by aegishe** [comment]
嗯，就是之前黑域的时候我阻止了，然后（新版）就没法改回来，于是就收不到短信了是吧
