### ISSUE TITLE
please run with 'su shell /data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so'

### ISSUE THREAD

**Issue by wudimenghuan** [liudongmiao/Brevent#111]
please run with 'su shell /data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so'

adb -d shell /data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so

希望提供ROOT版，这个打命令就没好使过，ROOT可以开机不用管，不是所有时间都有电脑打命令

一加3 7.1 魔趣

**Comment by wudimenghuan** [comment]
提供zip版刷机包也行，就是弄个脚本，把app放到priv里面
现在我是这样刷的
魔趣
opengapps
(原来6.0这里刷xposed)
supersu

**Comment by GongJianwei** [comment]
#95

**Comment by liudongmiao** [comment]
priv模式不能休眠，所以不会提供。

**Comment by wudimenghuan** [comment]
关于ROOT是否危险的问题，我认为不危险，因为有SuperSU，只有授权的应用才能使用ROOT权限
那可否像绿色守护一样，只需给黑域ROOT权限就可以使用？现在这样打补丁每次开机都需要连接电脑，不太方便

**Comment by wudimenghuan** [comment]
最新版本一直不能启动，运行adb命令后手机无反应

**Comment by wudimenghuan** [comment]
adb unroot可解决
