### ISSUE TITLE
关于 App Standby 无法阻止应用高占用 CPU 的讨论

### ISSUE THREAD

**Issue by 7nights** [liudongmiao/Brevent#112]
由于对 App Standby 具体不是很了解，查看官方的文档也还是无法解答我的问题（按照我的理解进入standby 的 app 不应该能这样占用 cpu），所以在这里提出讨论一下？

现在有个应用本身具有 bug，会长时间的消耗 CPU，通过 adb top 能够查看到（com.mzba.happy.laugh），而且当出现这个 bug 的时候还会导致 system_server 这个进程持续高 CPU 消耗：

![image](https://cloud.githubusercontent.com/assets/3193621/23208270/568eeb0a-f92f-11e6-9924-5d76aa6c8381.png)

这会导致 CPU 频率一直锁定在比较高的阶段，掉电很快。之前一直用 greenify 熄屏后强制 force stop.

在 brevent 里可以看到该应用(Smooth)已经处于 App Standby 状态:

![image](https://cloud.githubusercontent.com/assets/3193621/23208372/b49a992e-f92f-11e6-9069-58f314166f69.png)

即便这个应用作者最后修复了这个问题（其实我很早以前就反映过了，不过作者一直没有修复），别的应用会不会也有可能出现这样的 Bug? 由于对 Android 不是很了解，所以很疑惑的是 Brevent 已经显示应用 standby 了，为什么它还能占用 CPU 呢？

**Comment by liudongmiao** [comment]
standby 主要是系统的一种手段。很奇怪的是，这个应用还是 cached process。

根据官方文档，standby还可以接受gcm等消息，可能会被唤醒进行处理。

你可以使用 dumpsys activity processes 看下完整的进程，有可能是 android 本身 bug。

目前在识别最近列表还和系统返回的不同，下一版，只要从最近列表划掉了，就执行强杀操作。当然，这只是默认，也会放出选项，全部休眠还是全部停止。

**Comment by zzzdtz** [comment]
也许可以考虑捐赠版加个时间判断，晚上11点以后，休眠的应用除了能触发GCM通知的，全部强杀。毕竟有些小白要看晚上的待机耗电。。。，这样可以刷一波跟绿色的对比

**Comment by liudongmiao** [comment]
哈哈，我直接来个模式，只强杀不休眠就好吧。然后注上，性能测试，请使用强杀…

**Comment by liudongmiao** [comment]
接下来的版本，休眠最多只会 3 个小时，作为对比，7.0 中的最近列表是 6 个小时: https://android.googlesource.com/platform/frameworks/base/+/master/packages/SystemUI/src/com/android/systemui/recents/model/RecentsTaskLoadPlan.java#56

在跟系统的代码中，搞定了最近列表的问题。这样应该是安全的。

**Comment by zzzdtz** [comment]
这样也合理，我是clone了你77 78那个版本的，然后注释了强行停止，改为全部休眠，晚上的时候才杀，这样打开常用的应用很快，电量也不怎么掉，我改了HOST，使用GCM,关屏了3秒内自动休眠

**Comment by liudongmiao** [comment]
请注意，不要在任何地方以黑域的名义发布你改动过后的版本。

但是，你可以在描述里，加上黑域非官方修改字样。

此外，还要注意恶意唤醒的情况。当然，我一般是下个版本出来的时候，放出上个版本的源码。

**Comment by liudongmiao** [comment]
最好的情况，是你就自己使用，不要发布它。

**Comment by zzzdtz** [comment]
只自己在用，不会发布

**Comment by kcschan** [comment]
处于standby的应用似乎还是可以获得wakelock

**Comment by liudongmiao** [comment]
十天内没有继续反馈，关闭。
