### ISSUE TITLE
cannot listen port 错误

### ISSUE THREAD

**Issue by m0b0x** [liudongmiao/Brevent#113]
看了下  /data/user/0/com.android.shell/brevent/libloader.so  已经有了。
多谢。

--------------
```
--- crash start ---
02-23 08:49:28.774 26276 26276 E AndroidRuntime: FATAL EXCEPTION: main
02-23 08:49:28.774 26276 26276 E AndroidRuntime: Process: me.piebridge.brevent, PID: 26276
02-23 08:49:28.774 26276 26276 E AndroidRuntime: java.lang.RuntimeException: Unable to stop activity {me.piebridge.brevent/me.piebridge.brevent.ui.BreventActivity}: java.lang.IllegalArgumentException: Receiver not registered: me.piebridge.brevent.ui.o@4c5827b
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.app.ActivityThread.handleSleeping(ActivityThread.java:3624)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.app.ActivityThread.-wrap19(ActivityThread.java)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1519)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.app.ActivityThreadHook.handleMain(ActivityThreadHook.java:27)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
02-23 08:49:28.774 26276 26276 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Receiver not registered: me.piebridge.brevent.ui.o@4c5827b
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:780)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1195)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at me.piebridge.brevent.ui.BreventActivity.onStop(BreventActivity.java:228)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1278)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.app.Activity.performStop(Activity.java:6395)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        at android.app.ActivityThread.handleSleeping(ActivityThread.java:3621)
02-23 08:49:28.774 26276 26276 E AndroidRuntime:        ... 9 more
02-23 09:03:24.709  4484  4579 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-23 09:03:24.709  4484  4579 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-23 09:03:24.709  4484  4579 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        ... 1 more
02-23 09:03:24.709  4484  4579 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Bad magic number for Bundle: 0x27
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1628)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.java:3056)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at me.piebridge.brevent.server.d.a(HideApi.java:81)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:745)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:707)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:134)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:841)
02-23 09:03:24.709  4484  4579 E AndroidRuntime:        ... 3 more
02-23 09:03:24.719  4484  4579 E AndroidRuntime: Error reporting crash
02-23 09:03:24.719  4484  4579 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-23 09:03:24.719  4484  4579 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-23 09:03:24.719  4484  4579 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
02-23 09:03:24.719  4484  4579 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
02-23 09:03:24.719  4484  4579 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java)
02-23 09:03:24.719  4484  4579 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-23 09:03:24.719  4484  4579 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
02-23 09:03:24.512  4484  4484 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-23 09:03:24.584  4484  4579 D BreventServer: Brevent Server 0.7 started
02-23 09:03:24.594  4484  4579 D BreventServer: brevent user: 0, uid: 2000
02-23 09:03:24.595  4484  4579 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-23 09:03:24.627  4484  4579 D BreventServer: loaded brevent list
02-23 09:03:24.627  4484  4579 D BreventServer: loaded brevent conf
02-23 09:03:24.709  4484  4579 D BreventLoader: Can't run brevent server
02-23 09:03:24.709  4484  4579 D BreventLoader: java.lang.reflect.InvocationTargetException
02-23 09:03:24.709  4484  4579 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-23 09:03:24.709  4484  4579 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-23 09:03:24.709  4484  4579 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-23 09:03:24.709  4484  4579 D BreventLoader: Caused by: java.lang.IllegalStateException: Bad magic number for Bundle: 0x27
02-23 09:03:24.709  4484  4579 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1628)
02-23 09:03:24.709  4484  4579 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1573)
02-23 09:03:24.709  4484  4579 D BreventLoader:         at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.java:3056)
02-23 09:03:24.709  4484  4579 D BreventLoader:         at me.piebridge.brevent.server.d.a(HideApi.java:81)
02-23 09:03:24.709  4484  4579 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:745)
02-23 09:03:24.709  4484  4579 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:707)
02-23 09:03:24.709  4484  4579 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:134)
02-23 09:03:24.709  4484  4579 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:841)
02-23 09:03:24.709  4484  4579 D BreventLoader:         ... 3 more
02-23 09:03:24.709  4484  4484 D BreventLoader: Brevent Server quit in 30 seconds, quit
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
```

**Comment by m0b0x** [comment]
取消magisk root之后，执行报错如下：

checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
02-24 08:18:03.980  7562  7594 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-24 08:18:03.980  7562  7594 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:62)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-24 08:18:03.980  7562  7594 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        ... 1 more
02-24 08:18:03.980  7562  7594 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException:  is not a constant in android.text.Layout$Alignment
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at java.lang.Enum.valueOf(Enum.java:200)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.text.Layout$Alignment.valueOf(Layout.java:2017)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpan.java:33)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java:711)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java:689)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.readFromParcel(ActivityManager.java:938)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java:963)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java:955)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java:954)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.os.Parcel.createTypedArrayList(Parcel.java:2007)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at android.app.ActivityManagerProxy.getRecentTasks(ActivityManagerNative.java:3292)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at me.piebridge.brevent.server.f.a(HideApiOverrideM.java:22)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:347)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:242)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:140)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:874)
02-24 08:18:03.980  7562  7594 E AndroidRuntime:        ... 3 more
02-24 08:18:03.984  7562  7594 E AndroidRuntime: Error reporting crash
02-24 08:18:03.984  7562  7594 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-24 08:18:03.984  7562  7594 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-24 08:18:03.984  7562  7594 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
02-24 08:18:03.984  7562  7594 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
02-24 08:18:03.984  7562  7594 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java)
02-24 08:18:03.984  7562  7594 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-24 08:18:03.984  7562  7594 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
02-24 08:18:03.840  7562  7562 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-24 08:18:03.908  7562  7594 D BreventServer: Brevent Server 0.7.1 started
02-24 08:18:03.912  7562  7594 D BreventServer: brevent user: 0
02-24 08:18:03.913  7562  7594 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-24 08:18:03.938  7562  7594 D BreventServer: loaded brevent list
02-24 08:18:03.938  7562  7594 D BreventServer: loaded brevent conf
02-24 08:18:03.951  7562  7594 D BreventServer: checking
02-24 08:18:03.980  7562  7594 D BreventLoader: Can't run brevent server
02-24 08:18:03.980  7562  7594 D BreventLoader: java.lang.reflect.InvocationTargetException
02-24 08:18:03.980  7562  7594 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-24 08:18:03.980  7562  7594 D BreventLoader: Caused by: java.lang.IllegalArgumentException:  is not a constant in android.text.Layout$Alignment
02-24 08:18:03.980  7562  7594 D BreventLoader:         at java.lang.Enum.valueOf(Enum.java:200)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.text.Layout$Alignment.valueOf(Layout.java:2017)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpan.java:33)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.text.TextUtils$1.createFromParcel(TextUtils.java:711)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.text.TextUtils$1.createFromParcel(TextUtils.java:689)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.readFromParcel(ActivityManager.java:938)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java:963)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java:955)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java:954)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.os.Parcel.createTypedArrayList(Parcel.java:2007)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at android.app.ActivityManagerProxy.getRecentTasks(ActivityManagerNative.java:3292)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at me.piebridge.brevent.server.f.a(HideApiOverrideM.java:22)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:347)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:242)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:140)
02-24 08:18:03.980  7562  7594 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:874)
02-24 08:18:03.980  7562  7594 D BreventLoader:         ... 3 more
02-24 08:18:03.980  7562  7562 D BreventLoader: Brevent Server quit in 30 seconds, quit
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
系统底层错误，无法获取最近列表。暂无思路。

如果第三方 ROM，可以请 ROM 提供者看看。

**Comment by m0b0x** [comment]
是第三方patchrom miui8，好的， 多谢。

**Comment by liudongmiao** [comment]
十天内没有继续反馈，关闭。
