### ISSUE TITLE
Cannot listen to port. upgraded from 0.4 to 0.7 - Nexus 6P 7.1.1

### ISSUE THREAD

**Issue by alexyzhou** [liudongmiao/Brevent#118]
checking...brevent_server started, pid: 6084
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
02-23 22:42:13.178  8098  8098 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
02-23 22:42:13.178  8098  8098 F DEBUG   :     x0   0000000000000000  x1   000000555a204402  x2   0000000000000007  x3   0000000000000004
02-23 22:42:13.178  8098  8098 F DEBUG   :     x4   000000000000004b  x5   8080800000000000  x6   0000007fe8e8ffd8  x7   fefeff3133fefefe
02-23 22:42:13.178  8098  8098 F DEBUG   :     x8   000000555a204402  x9   00000070fa00c708  x10  000000000000004b  x11  0101010101010101
02-23 22:42:13.178  8098  8098 F DEBUG   :     x12  00000070fa00c6e8  x13  000000000ccccccc  x14  000000008000002f  x15  00000070fa7811e8
02-23 22:42:13.179  8098  8098 F DEBUG   :     x16  000000555a21d778  x17  00000070fa6f641c  x18  0000000000000000  x19  ffffffffffffffff
02-23 22:42:13.179  8098  8098 F DEBUG   :     x20  00000070fa02a1f0  x21  00000070fa036400  x22  000000555a200df5  x23  ffffffffffffffff
02-23 22:42:13.179  8098  8098 F DEBUG   :     x24  00000070fa032010  x25  000000555a21f760  x26  000000555a204402  x27  000000555a20440b
02-23 22:42:13.179  8098  8098 F DEBUG   :     x28  0000000000000000  x29  0000007fe8e90060  x30  000000555a1e8d4c
02-23 22:42:13.179  8098  8098 F DEBUG   :     sp   0000007fe8e8ffc0  pc   00000070fa6f6504  pstate 0000000000000000
02-23 22:42:13.182  8098  8098 F DEBUG   : 
02-23 22:42:13.182  8098  8098 F DEBUG   : backtrace:
02-23 22:42:13.183  8098  8098 F DEBUG   :     #00 pc 000000000001b504  /system/lib64/libc.so (strncmp+232)
02-23 22:42:13.183  8098  8098 F DEBUG   :     #01 pc 0000000000020d48  /system/bin/toybox
02-23 22:42:13.183  8098  8098 F DEBUG   :     #02 pc 000000000000c58c  /system/bin/toybox
02-23 22:42:13.183  8098  8098 F DEBUG   :     #03 pc 000000000000c678  /system/bin/toybox
02-23 22:42:13.183  8098  8098 F DEBUG   :     #04 pc 000000000000c5e4  /system/bin/toybox
02-23 22:42:13.183  8098  8098 F DEBUG   :     #05 pc 0000000000020340  /system/bin/toybox
02-23 22:42:13.183  8098  8098 F DEBUG   :     #06 pc 000000000001190c  /system/bin/toybox
02-23 22:42:13.183  8098  8098 F DEBUG   :     #07 pc 00000000000114b8  /system/bin/toybox
02-23 22:42:13.183  8098  8098 F DEBUG   :     #08 pc 00000000000119a4  /system/bin/toybox
02-23 22:42:13.183  8098  8098 F DEBUG   :     #09 pc 000000000001a594  /system/lib64/libc.so (__libc_init+88)
02-23 22:42:13.183  8098  8098 F DEBUG   :     #10 pc 000000000000b6f8  /system/bin/toybox
02-23 22:42:17.115  8210  8210 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 8210 (netstat)
02-23 22:42:17.171  8215  8215 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-23 22:42:17.171  8215  8215 F DEBUG   : Build fingerprint: 'google/angler/angler:7.1.1/N4F26J/3549317:user/release-keys'
02-23 22:42:17.171  8215  8215 F DEBUG   : Revision: '0'
02-23 22:42:17.171  8215  8215 F DEBUG   : ABI: 'arm64'
02-23 22:42:17.171  8215  8215 F DEBUG   : pid: 8210, tid: 8210, name: netstat  >>> netstat <<<
02-23 22:42:17.171  8215  8215 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
02-23 22:42:17.171  8215  8215 F DEBUG   :     x0   0000000000000000  x1   0000005567ba4402  x2   0000000000000007  x3   0000000000000004
02-23 22:42:17.171  8215  8215 F DEBUG   :     x4   000000000000004b  x5   0000000000000000  x6   0000007fc0d4ff78  x7   fefefefefefefefe
02-23 22:42:17.171  8215  8215 F DEBUG   :     x8   0000005567ba4402  x9   0000007bdea0c708  x10  000000000000004b  x11  0101010101010101
02-23 22:42:17.171  8215  8215 F DEBUG   :     x12  0000007bdea0c6e8  x13  000000000ccccccc  x14  000000008000002f  x15  0000007bdf15f1e8
02-23 22:42:17.171  8215  8215 F DEBUG   :     x16  0000005567bbd778  x17  0000007bdf0d441c  x18  0000000000000000  x19  ffffffffffffffff
02-23 22:42:17.171  8215  8215 F DEBUG   :     x20  0000007bdea2a1f0  x21  0000007bdea36400  x22  0000005567ba0df5  x23  ffffffffffffffff
02-23 22:42:17.171  8215  8215 F DEBUG   :     x24  0000007bdea32010  x25  0000005567bbf760  x26  0000005567ba4402  x27  0000005567ba440b
02-23 22:42:17.172  8215  8215 F DEBUG   :     x28  0000000000000000  x29  0000007fc0d50000  x30  0000005567b88d4c
02-23 22:42:17.172  8215  8215 F DEBUG   :     sp   0000007fc0d4ff60  pc   0000007bdf0d4504  pstate 0000000000000000
02-23 22:42:17.175  8215  8215 F DEBUG   : 
02-23 22:42:17.175  8215  8215 F DEBUG   : backtrace:
02-23 22:42:17.176  8215  8215 F DEBUG   :     #00 pc 000000000001b504  /system/lib64/libc.so (strncmp+232)
02-23 22:42:17.176  8215  8215 F DEBUG   :     #01 pc 0000000000020d48  /system/bin/toybox
02-23 22:42:17.176  8215  8215 F DEBUG   :     #02 pc 000000000000c58c  /system/bin/toybox
02-23 22:42:17.176  8215  8215 F DEBUG   :     #03 pc 000000000000c678  /system/bin/toybox
02-23 22:42:17.176  8215  8215 F DEBUG   :     #04 pc 000000000000c5e4  /system/bin/toybox
02-23 22:42:17.176  8215  8215 F DEBUG   :     #05 pc 0000000000020340  /system/bin/toybox
02-23 22:42:17.176  8215  8215 F DEBUG   :     #06 pc 000000000001190c  /system/bin/toybox
02-23 22:42:17.176  8215  8215 F DEBUG   :     #07 pc 00000000000114b8  /system/bin/toybox
02-23 22:42:17.176  8215  8215 F DEBUG   :     #08 pc 00000000000119a4  /system/bin/toybox
02-23 22:42:17.176  8215  8215 F DEBUG   :     #09 pc 000000000001a594  /system/lib64/libc.so (__libc_init+88)
02-23 22:42:17.176  8215  8215 F DEBUG   :     #10 pc 000000000000b6f8  /system/bin/toybox
02-23 22:42:20.473  8224  8224 F libc    : Fatal signal 7 (SIGBUS), code 2, fault addr 0xebb07000 in tid 8224 (main)
02-23 22:42:20.536  8254  8254 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-23 22:42:20.536  8254  8254 F DEBUG   : Build fingerprint: 'google/angler/angler:7.1.1/N4F26J/3549317:user/release-keys'
02-23 22:42:20.536  8254  8254 F DEBUG   : Revision: '0'
02-23 22:42:20.536  8254  8254 F DEBUG   : ABI: 'arm'
02-23 22:42:20.536  8254  8254 F DEBUG   : pid: 8224, tid: 8224, name: main  >>> /system/bin/dex2oat <<<
02-23 22:42:20.536  8254  8254 F DEBUG   : signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0xebb07000
02-23 22:42:20.536  8254  8254 F DEBUG   :     r0 eb014000  r1 00000000  r2 000000ac  r3 00567000
02-23 22:42:20.536  8254  8254 F DEBUG   :     r4 00000000  r5 00000019  r6 eb5a0000  r7 00000041
02-23 22:42:20.536  8254  8254 F DEBUG   :     r8 ef7bb008  r9 0056d000  sl eb581000  fp ef69d010
02-23 22:42:20.536  8254  8254 F DEBUG   :     ip eb014000  sp ffb1f6c0  lr 000000b1  pc efc86c20  cpsr 800f0030
02-23 22:42:20.538  8254  8254 F DEBUG   : 
02-23 22:42:20.538  8254  8254 F DEBUG   : backtrace:
02-23 22:42:20.538  8254  8254 F DEBUG   :     #00 pc 00019c20  /data/app/com.bankcomm.Bankcomm-1/lib/arm/libDexHelper.so
02-23 22:42:20.538  8254  8254 F DEBUG   :     #01 pc 00019d03  /data/app/com.bankcomm.Bankcomm-1/lib/arm/libDexHelper.so
02-23 22:42:20.538  8254  8254 F DEBUG   :     #02 pc 00006d45  /system/lib/libc.so (offset 0x1a000)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
02-23 22:42:22.886  8319  8365 E AndroidRuntime: Process: com.teslacoilsw.launcher:wallpaper_chooser, PID: 8319
02-23 22:42:22.886  8319  8365 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.photos.contentprovider.MediaContentProvider from ProcessRecord{1163729 8319:com.teslacoilsw.launcher:wallpaper_chooser/u0a140} (pid=8319, uid=10140) that is not exported from uid 10078
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1684)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1637)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4199)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:5476)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2239)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1517)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1131)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:984)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:704)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at o.interface$mK.mK(SourceFile)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at o.interface$mK.eN(SourceFile)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at o.interface$eN.eN(SourceFile)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at com.android.launcher3.WallpaperCropActivity$3.eN(SourceFile)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at com.android.launcher3.WallpaperCropActivity$3.doInBackground(SourceFile)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-23 22:42:22.886  8319  8365 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: FATAL EXCEPTION: main
02-23 22:45:00.511 10285 10285 E AndroidRuntime: Process: org.videolan.vlc, PID: 10285
02-23 22:45:00.511 10285 10285 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.EditText android.support.design.widget.TextInputLayout.getEditText()' on a null object reference
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at org.videolan.vlc.gui.network.MRLPanelFragment.onSaveInstanceState(MRLPanelFragment.java:92)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2109)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1767)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1835)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:125)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:523)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at org.videolan.vlc.gui.MainActivity.onSaveInstanceState(MainActivity.java:425)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.app.Activity.performSaveInstanceState(Activity.java:1414)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1300)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4541)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3856)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3915)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.app.ActivityThread.-wrap25(ActivityThread.java)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1511)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at Android.MODEL(Nexus 6P)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at Android.VERSION(7.1.1)
02-23 22:45:00.511 10285 10285 E AndroidRuntime: 	at Android.FINGERPRINT(google/angler/angler:7.1.1/N4F26J/3549317:user/release-keys)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: FATAL EXCEPTION: BG
02-24 00:00:10.336 13317 13395 E AndroidRuntime: Process: com.google.android.wearable.app:background, PID: 13317
02-24 00:00:10.336 13317 13395 E AndroidRuntime: java.lang.RuntimeException: Unchecked exception running task: StartCalendarRunnable@2c0e1a0
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at com.google.android.clockwork.common.concurrent.InstrumentedTask.maybePropagateException(PG:116)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at com.google.android.clockwork.common.concurrent.InstrumentedTask.done(PG:2098)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at com.google.android.clockwork.common.concurrent.InstrumentedTask.run(PG:71)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at com.google.android.clockwork.common.concurrent.PooledThreadPoolExecutor$Worker.run(PG:455)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at com.google.android.clockwork.common.concurrent.CwPriorityRunnable.run(PG:36)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.isEmpty()' on a null object reference
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at com.google.android.clockwork.calendar.WearableCalendarSyncer.syncEvents(PG:127)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at com.google.android.clockwork.calendar.RootCalendarSyncer.syncEvents(PG:52)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at com.google.android.clockwork.calendar.CalendarSyncSchedulerImpl$StartCalendarRunnable.run(PG:122)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-24 00:00:10.336 13317 13395 E AndroidRuntime: 	... 6 more
02-24 11:48:46.969 32708 32709 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe8 in tid 32709 (Binder:32708_1)
02-24 11:51:20.596  1875  1884 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-1
02-24 11:51:20.596  1875  1884 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:62)
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
02-24 11:51:20.596  1875  1884 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	... 1 more
02-24 11:51:20.596  1875  1884 E AndroidRuntime: Caused by: java.net.BindException: Address already in use
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	at java.net.PlainSocketImpl.socketBind(Native Method)
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:368)
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	at java.net.ServerSocket.bind(ServerSocket.java:377)
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:882)
02-24 11:51:20.596  1875  1884 E AndroidRuntime: 	... 3 more
02-24 11:51:20.619  1875  1884 E AndroidRuntime: Error reporting crash
02-24 11:51:20.619  1875  1884 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-24 11:51:20.619  1875  1884 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
02-24 11:51:20.619  1875  1884 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
02-24 11:51:20.619  1875  1884 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5133)
02-24 11:51:20.619  1875  1884 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
02-24 11:51:20.619  1875  1884 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-24 11:51:20.619  1875  1884 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
02-24 11:56:53.366  6084  6084 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 6084 (main)
02-24 11:56:53.449  6095  6095 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-24 11:56:53.451  6095  6095 F DEBUG   : Build fingerprint: 'google/angler/angler:7.1.1/N4F26J/3549317:user/release-keys'
02-24 11:56:53.451  6095  6095 F DEBUG   : Revision: '0'
02-24 11:56:53.451  6095  6095 F DEBUG   : ABI: 'arm'
02-24 11:56:53.451  6095  6095 F DEBUG   : pid: 6084, tid: 6084, name: main  >>> brevent_server <<<
02-24 11:56:53.452  6095  6095 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-24 11:56:53.463  6095  6095 F DEBUG   : Abort message: 'art/runtime/thread.cc:1657] No pending exception expected: java.lang.ClassNotFoundException: Didn't find class "me.piebridge.brevent.loader.Brevent" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]'
02-24 11:56:53.463  6095  6095 F DEBUG   :     r0 00000000  r1 000017c4  r2 00000006  r3 00000008
02-24 11:56:53.463  6095  6095 F DEBUG   :     r4 f2d5458c  r5 00000006  r6 f2d54534  r7 0000010c
02-24 11:56:53.463  6095  6095 F DEBUG   :     r8 00000000  r9 0000000a  sl 00000214  fp f0085400
02-24 11:56:53.464  6095  6095 F DEBUG   :     ip 00000000  sp ffabf9b8  lr f25ea557  pc f25ecdb4  cpsr 200f0010
02-24 11:56:53.480  6095  6095 F DEBUG   : 
02-24 11:56:53.480  6095  6095 F DEBUG   : backtrace:
02-24 11:56:53.480  6095  6095 F DEBUG   :     #00 pc 00049db4  /system/lib/libc.so (tgkill+12)
02-24 11:56:53.480  6095  6095 F DEBUG   :     #01 pc 00047553  /system/lib/libc.so (pthread_kill+34)
02-24 11:56:53.480  6095  6095 F DEBUG   :     #02 pc 0001d8a5  /system/lib/libc.so (raise+10)
02-24 11:56:53.480  6095  6095 F DEBUG   :     #03 pc 000193f1  /system/lib/libc.so (__libc_android_abort+34)
02-24 11:56:53.480  6095  6095 F DEBUG   :     #04 pc 00017034  /system/lib/libc.so (abort+4)
02-24 11:56:53.480  6095  6095 F DEBUG   :     #05 pc 0031a5f1  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+328)
02-24 11:56:53.480  6095  6095 F DEBUG   :     #06 pc 000b5205  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1132)
02-24 11:56:53.480  6095  6095 F DEBUG   :     #07 pc 00333c47  /system/lib/libart.so (_ZNK3art6Thread24AssertNoPendingExceptionEv+602)
02-24 11:56:53.480  6095  6095 F DEBUG   :     #08 pc 000e5119  /system/lib/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+28)
02-24 11:56:53.480  6095  6095 F DEBUG   :     #09 pc 00260fc3  /system/lib/libart.so (_ZN3art3JNI9FindClassEP7_JNIEnvPKc+1878)
02-24 11:56:53.481  6095  6095 F DEBUG   :     #10 pc 00002703  /system/lib/libnativehelper.so (jniRegisterNativeMethods+30)
02-24 11:56:53.481  6095  6095 F DEBUG   :     #11 pc 00066921  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime8startRegEP7_JNIEnv+108)
02-24 11:56:53.481  6095  6095 F DEBUG   :     #12 pc 00067c67  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+298)
02-24 11:56:53.481  6095  6095 F DEBUG   :     #13 pc 00001947  /system/bin/app_process32
02-24 11:56:53.481  6095  6095 F DEBUG   :     #14 pc 00016c4d  /system/lib/libc.so (__libc_init+48)
02-24 11:56:53.481  6095  6095 F DEBUG   :     #15 pc 00001564  /system/bin/app_process32
--- crash end ---
--- brevent start ---
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
please install the latest 0.7.1, then following instruction.

**Comment by alexyzhou** [comment]
我用的就是0.7.1，是把0.4删了重新装的0.7.1

**Comment by alexyzhou** [comment]
问题已经解决，重启再进入0.7.1就好了。谢谢！已捐赠:D
