### ISSUE TITLE
三星系统更新到7.0之后，没有合并odex，编译补丁失败

### ISSUE THREAD

**Issue by honggegeda** [liudongmiao/Brevent#12]
有几位热心兄弟和自己尝试尝试编译补丁，但是都失败了，据说因为service.jar文件太长，无法反编译，我是小白，靠工具也无法编译
留下了整个farmework文件夹，求解决
http://pan.baidu.com/share/link?shareid=3699762165&uk=3745298705

**Comment by liudongmiao** [comment]
建议你只传解包的文件，按照 https://github.com/liudongmiao/Brevent/blob/master/aosp/README.md#怎样打补丁 这个文档来。

100M+的文件，不是每个人都愿意下载。

**Comment by aviraxp** [comment]
```
Exception in thread "main" org.jf.util.ExceptionWithContext: Unsigned short ve out of range: 65537
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java6)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.ja338)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1039)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.j:818)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:245)
        at org.jf.smali.Smali.assemble(Smali.java:130)
        at org.jf.smali.AssembleCommand.run(AssembleCommand.java:96)
        at org.jf.smali.Main.main(Main.java:99)
```
方法数超出了限制（65535）个，怎么就正好多两个…………原来 java 方法数是没有超出限制的，但是转为 smali 需要增加一些虚拟方法，这样就增大了方法数。

我不知道怎么解决，这样的话能不能放进两个 dex？

**Comment by liudongmiao** [comment]
放进两个 dex 的话，会出现可能找不到，毕竟我没法测试，可能要用到一些其它的特殊机制。

你先帮忙去掉两个方法：

https://github.com/liudongmiao/Brevent/blob/master/services/core/java/com/android/server/am/PreventRunningUtils.java#L70

https://github.com/liudongmiao/Brevent/blob/master/services/core/java/com/android/server/am/PreventRunning.java#L180

暂时不要提交，因为给 aosp 的版本里用到了这两个文件。

手动的话，在解压 apk 后，删除两个方法：
- `PreventRunningUtils.smali` 中的 `.method public static returnFalse(Z)Z`
- `PreventRunning.smali` 中的 `.method public isActiviated()Z`

如果还说多了方法，我再想想删除哪些。

总共加了 8 个方法(为了方便hook ams 中的8个方法)，以及三个 dummy 类。

以后我可能会简化整个操作流程，甚至在 4.4 - 6.0 也采取不用补丁的方法；从某种意义上讲，`不让唤醒`与`唤醒之后立即杀`的效果可能差不多，但后者会柔和一些。

**Comment by aviraxp** [comment]
悲报：还是多一个方法

**Comment by zinian** [comment]
@aviraxp  我是把 PreventRunning 的那三个 smali  扔到 classes2.dex  了

**Comment by liudongmiao** [comment]
@zinian 可以运行？

@aviraxp 把 `ActivityManagerService.smali` 里的 `bindService` 删除，然后，把 `bindService$Pr` 删除， 同时，把 `PreventRunningUtils` 中的 `hookBindService` 删除；如果还多，对 `startService` 与 `startService$Pr` 也同样处理，找方法时，找的 `bindService` 与 `startService` 一定要和带 `$Pr` 的签名保持一致。

**Comment by zinian** [comment]
@liudongmiao 酷安 测试两个三星的可以，他们的本身就有 classes2.dex

**Comment by aviraxp** [comment]
非常奇怪：删除之后总方法数反而增加了。

**Comment by liudongmiao** [comment]
等我晚上回去看看吧。

**Comment by zinian** [comment]
@honggegeda  来测试下。https://share.weiyun.com/5b090ff1847054a77773eec33552a198
可能要重启一两次。

**Comment by honggegeda** [comment]
不敢删除啊，已经替换了，不知道删除哪个有俩odex，一个事Samsung－services.odex，这个文件2m，在arm64里面，还有一个是services.odex，这个文件62m@zinian

**Comment by aviraxp** [comment]
当然是大的那个

**Comment by zinian** [comment]
@honggegeda  补丁我已经做了，需要你测试下啊，上面的链接

**Comment by honggegeda** [comment]
好了，已经成功上车，谢谢上面的帮助，可以留下简单的方法，下次系统更新了自己来试试@zinian，@aviraxp

**Comment by liudongmiao** [comment]
@honggegeda @aviraxp 不是大的那个，而是叫 `services.odex` 的那个，只是建议删除，不删除的话，应该也可以使用。

**Comment by aviraxp** [comment]
啊，我知道。。。只是为了简化说明。。

**Comment by honggegeda** [comment]
明白了，三星这玩意儿补丁不好打啊，有什么简易方法可以打吗😀😀🤔@aviraxp，@liudongmiao

**Comment by liudongmiao** [comment]
@honggegeda 没什么简化版本，现在只是编译而已。想想阻止运行时代的补丁，打起来那叫一个复杂。现在已经简化很多了。

接下来，我会考虑普通模式，建立在一个理念上，`阻止唤醒`与`唤醒后立马杀掉`效果差不多。但明显，我需要时间，以及时间，最好有人协助我写代码就好。

**Comment by honggegeda** [comment]
好吧，没有简便的方法岂不是以后我还得麻烦你了，实在是很不好意思啊😕😕😕

**Comment by liudongmiao** [comment]
@honggegeda 你这个是官方原始的文件，还是第三方的 ROM ?

**Comment by honggegeda** [comment]
@

**Comment by honggegeda** [comment]
@zinian   @aviraxp，重刷了新的系统，求新补丁这次合并了odex文件，http://pan.baidu.com/share/link?shareid=3311273600&uk=3745298705，services.jar文件已上传
