### ISSUE TITLE
从0.4更新到0.7.1后无法启动黑域服务

### ISSUE THREAD

**Issue by DreamistW** [liudongmiao/Brevent#120]
机型是FRD-AL00，ROM是EMUI 5.0+Android 7.0
（重启手机后可以启动黑域服务）
日志如下：

HWFRD:/ $ /data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so
/data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so
checking...brevent_server started, pid: 21481
checking for stable...quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
02-23 12:41:22.202  9621  9621 F libc    : "/data/user/0/com.autonavi.minimap/lib/libappwatcher-1.0.1.so": error: only position independent executables (PIE) are supported.
02-23 12:41:22.202  9621  9621 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 9621 (libappwatcher-1)
02-23 12:41:22.305  9623  9623 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-23 12:41:22.305  9623  9623 F DEBUG   : Build fingerprint: 'honor/FRD-AL00/HWFRD:7.0/HUAWEIFRD-AL00/C00B650:user/release-keys'
02-23 12:41:22.305  9623  9623 F DEBUG   : Revision: '0'
02-23 12:41:22.305  9623  9623 F DEBUG   : ABI: 'arm'
02-23 12:41:22.306  9623  9623 F DEBUG   : pid: 9621, tid: 9621, name: libappwatcher-1  >>> /data/user/0/com.autonavi.minimap/lib/libappwatcher-1.0.1.so <<<
02-23 12:41:22.306  9623  9623 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-23 12:41:22.306  9623  9623 F DEBUG   :     r0 00000000  r1 00002595  r2 00000006  r3 00000008
02-23 12:41:22.306  9623  9623 F DEBUG   :     r4 e780658c  r5 00000006  r6 e7806534  r7 0000010c
02-23 12:41:22.306  9623  9623 F DEBUG   :     r8 e779a010  r9 00000000  sl 00000000  fp ffd3db34
02-23 12:41:22.306  9623  9623 F DEBUG   :     ip 00000000  sp ffd3c890  lr e77e61ef  pc e77e6c0c  cpsr 600f0010
02-23 12:41:22.311  9623  9623 F DEBUG   :
02-23 12:41:22.311  9623  9623 F DEBUG   : backtrace:
02-23 12:41:22.311  9623  9623 F DEBUG   :     #00 pc 00045c0c  /system/bin/linker (__dl_tgkill+12)
02-23 12:41:22.311  9623  9623 F DEBUG   :     #01 pc 000451eb  /system/bin/linker (__dl_pthread_kill+34)
02-23 12:41:22.311  9623  9623 F DEBUG   :     #02 pc 0003d4ef  /system/bin/linker (__dl_raise+10)
02-23 12:41:22.311  9623  9623 F DEBUG   :     #03 pc 0003bfab  /system/bin/linker (__dl___libc_android_abort+34)
02-23 12:41:22.311  9623  9623 F DEBUG   :     #04 pc 0003ad84  /system/bin/linker (__dl_abort+4)
02-23 12:41:22.311  9623  9623 F DEBUG   :     #05 pc 0003cff3  /system/bin/linker (__dl___libc_fatal+22)
02-23 12:41:22.311  9623  9623 F DEBUG   :     #06 pc 000093ef  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2254)
02-23 12:41:22.311  9623  9623 F DEBUG   :     #07 pc 00008a8b  /system/bin/linker (__dl___linker_init+358)
02-23 12:41:22.311  9623  9623 F DEBUG   :     #08 pc 000027b0  /system/bin/linker (_start+4)
02-24 13:05:03.177 21481 21490 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-1
02-24 13:05:03.177 21481 21490 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:62)
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:776)
02-24 13:05:03.177 21481 21490 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        ... 1 more
02-24 13:05:03.177 21481 21490 E AndroidRuntime: Caused by: java.net.BindException: Address already in use
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        at java.net.PlainSocketImpl.socketBind(Native Method)
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:368)
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        at java.net.ServerSocket.bind(ServerSocket.java:380)
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:882)
02-24 13:05:03.177 21481 21490 E AndroidRuntime:        ... 3 more
02-24 13:05:03.194 21481 21490 E AndroidRuntime: Error reporting crash
02-24 13:05:03.194 21481 21490 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-24 13:05:03.194 21481 21490 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-24 13:05:03.194 21481 21490 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:617)
02-24 13:05:03.194 21481 21490 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5115)
02-24 13:05:03.194 21481 21490 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
02-24 13:05:03.194 21481 21490 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-24 13:05:03.194 21481 21490 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
02-24 13:05:02.502 21481 21490 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 78
02-24 13:05:03.147 21481 21490 I BreventServer: power_screen_state, tag: 2728, event: 7
02-24 13:05:03.149 21481 21490 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-24 13:05:03.153 21481 21490 I BreventServer: am_new_intent, tag: 30003, event: 2
02-24 13:05:03.154 21481 21490 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-24 13:05:03.155 21481 21490 I BreventServer: am_proc_start, tag: 30014, event: 4
02-24 13:05:03.156 21481 21490 I BreventServer: am_switch_user, tag: 30041, event: 5
02-24 13:05:03.157 21481 21490 I BreventServer: am_focused_activity, tag: 30043, event: 1
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
不支持从 0.4 到 0.7.1 的升级。

对于 0.4，只监听了一个端口；0.5 以上，才有了程序的名字。所以，在 0.7.1 之前，都是使用端口来看是否有启动黑域服务；到了 0.7.1，由于中间已经发布过 N 多版本，为简单，直接使用程序名字判断是否启用。

解决办法：
a. 从 0.4 升到 0.7，然后升 0.7.1
b. 重启手机，再使用 0.7.1
c. 手动找到那个进程，再处理。但比较麻烦，我就不说了
