### ISSUE TITLE
0.71程序在前台运行也会进休眠

### ISSUE THREAD

**Issue by eYoungNoir** [liudongmiao/Brevent#121]
系统版本6.0.1，黑域版本0.71
从0.7升级为0.71后，部分已设为阻止的程序在前台运行时也会进入休眠断开在线状态，移出阻止列表就正常，0.7的黑域没有这现象

**Comment by liudongmiao** [comment]
正常的 Android 即使是在休眠，只要你进入，也会退出休眠状态。

请根据这个页面，看下应用是否支持休眠：https://developer.android.google.cn/training/monitoring-device-state/doze-standby.html

下个版本里，将会允许强行停止。

此外，你也可以这样测试：强行停止它，打开它，看是否正常。

**Comment by liudongmiao** [comment]
还可以这样测试，插上电源，查看是否正常。

当然，我也会考虑在下个版本中，当打开以后，显式退出休眠。

**Comment by eYoungNoir** [comment]
刚用一个游戏试验了下，不停操作的情况下出现“正在连接...”，黑域显示游戏进入休眠，插电和不插电都出现相同的情况。问题出在我正在进行操作的程序被黑域进行了休眠，与是否通知提示无关。

**Comment by liudongmiao** [comment]
0.7.2/0.7.3 对于这类情况优化过，请下载看看是否有解决，谢谢。

**Comment by eYoungNoir** [comment]
0.7.2和0.7.3都试了，仍旧有这情况，酷安和Welike等不少app也有这状况，表现为正在浏览的状态忽然刷不出缩略图

**Comment by eYoungNoir** [comment]
0.7.4已解决该问题，给力 O(∩_∩)O
