### ISSUE TITLE
如果可以不必每次开机都连接电脑那黑域就完美了

### ISSUE THREAD

**Issue by wudimenghuan** [liudongmiao/Brevent#126]
如果这样，在外面没电脑时，就可以不用担心不小心重启了
绿色守护也可以丢掉了（它不能休眠）

**Comment by wudimenghuan** [comment]
我觉得可以尝试申请ROOT权限，在每次开机时，调用某种类似adb的东西让自己的进程启动。
这样对于root的用户，就可以不用每次开机连接电脑了。
没有root的用户还是使用adb命令运行。

**Comment by liudongmiao** [comment]
下个版本会支持的。

**Comment by wudimenghuan** [comment]
真佩服你的休眠，这是怎么做到的？绿色守护就不能这么完美的休眠，它的浅度睡眠会很费电

**Comment by liudongmiao** [comment]
可以去看代码哈～目前是开源的。虽然没有上传最新的代码，但不影响阅读核心代码。
