### ISSUE TITLE
在三星S7E的内测版7.0中重启手机后需要重新adb一次 - 异常处理卸载应用问题

### ISSUE THREAD

**Issue by BadGuyX** [liudongmiao/Brevent#127]
如题

**Comment by liudongmiao** [comment]
普通版，无解，因为黑域服务需要的权限，无法被长期授予，但是能基本保证，只要不重启手机，即使升级黑域也不用重新启动黑域服务。

下个版本极有可能会加入 root 模式的自启动，但是对于普通用户，我的建议是，不要重启手机。

**Comment by liCN** [comment]
感谢作者
我也觉得adb模式比较烦，虽然我极少重启手机

**Comment by BadGuyX** [comment]
有个可能打脸作者的情况：今天中午升级0.7.3后，过了大概1小时后打开黑域，它又叫我重新adb一次  0.0

**Comment by liudongmiao** [comment]
嗯，请带上日志。目前黑域服务非常稳定（因为我也一直使用），包括升级不会出现异常退出，也不受 AMS （Android的ebtl）控制。所以，一旦异常退出，需要详细的日志。

**Comment by liudongmiao** [comment]
这也是我不愿意开发 root 版的原因，因为 root 了以后，会有多种方法干掉一个进程。

**Comment by BadGuyX** [comment]
那个。。日志保存在哪里的？该怎么找出来?  0.0

**Comment by liudongmiao** [comment]
再次执行那个脚本，没有提示的。如果没有，就重启一下吧，会有提示的。

**Comment by BadGuyX** [comment]
刚刚更新之后又要adb一次，以下就是第二次输入APP提示的adb语句后cmd中弹出的两句adb语句之一的“adb logcat -b main -d -s BreventLoader BreventServer”（另一条的结果在下面），其结果如下：

02-27 19:42:04.387 18681 18681 D BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
02-27 19:42:04.396 18681 18690 D BreventServer: Brevent Server 0.7.5 started
02-27 19:42:04.400 18681 18690 D BreventServer: brevent user: 0
02-27 19:42:04.403 18681 18690 D BreventServer: brevent data directory: /data/user_de/0/com.android.shell
02-27 19:42:04.651 18681 18690 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 14
02-27 19:42:04.651 18681 18690 D BreventServer: loaded brevent list
02-27 19:42:04.652 18681 18690 D BreventServer: loaded brevent conf
02-27 19:42:04.668 18681 18690 D BreventServer: checking
02-27 19:42:05.022 18681 18690 I BreventServer: power_screen_state, tag: 2728, event: 7
02-27 19:42:05.023 18681 18690 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-27 19:42:05.027 18681 18690 I BreventServer: am_new_intent, tag: 30003, event: 2
02-27 19:42:05.028 18681 18690 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-27 19:42:05.028 18681 18690 I BreventServer: am_proc_start, tag: 30014, event: 4
02-27 19:42:05.030 18681 18690 I BreventServer: am_switch_user, tag: 30041, event: 5
02-27 19:42:05.031 18681 18690 I BreventServer: am_focused_activity, tag: 30043, event: 1
02-27 19:42:07.223 18681 18711 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags], events: [0, 34031054, 826, com.teslacoilsw.launcher/.NovaLauncher, android.intent.action.MAIN, NULL, NULL, 272629760, com.jamworks.easyhome]
02-27 19:42:09.227 18681 18690 D BreventServer: checking
02-27 19:42:25.609 19004 19004 D BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
02-27 19:42:25.627 19004 19016 D BreventServer: Brevent Server 0.7.5 started
02-27 19:42:25.630 19004 19016 D BreventServer: brevent user: 0
02-27 19:42:25.632 19004 19016 D BreventServer: brevent data directory: /data/user_de/0/com.android.shell
02-27 19:42:25.849 19004 19016 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 14
02-27 19:42:25.849 19004 19016 D BreventServer: loaded brevent list
02-27 19:42:25.850 19004 19016 D BreventServer: loaded brevent conf
02-27 19:42:25.877 19004 19016 D BreventServer: checking
02-27 19:42:26.460 19004 19016 I BreventServer: power_screen_state, tag: 2728, event: 7
02-27 19:42:26.461 19004 19016 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-27 19:42:26.465 19004 19016 I BreventServer: am_new_intent, tag: 30003, event: 2
02-27 19:42:26.466 19004 19016 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-27 19:42:26.467 19004 19016 I BreventServer: am_proc_start, tag: 30014, event: 4
02-27 19:42:26.469 19004 19016 I BreventServer: am_switch_user, tag: 30041, event: 5
02-27 19:42:26.469 19004 19016 I BreventServer: am_focused_activity, tag: 30043, event: 1

下面是另一条语句“adb logcat -b crash -d”的结果：

02-26 13:03:56.227 31785 31785 F libc    : "/data/data/com.motie.motiereader/lib/libtpnsWatchdog.so": error: only position independent executables (PIE) are supported.
02-26 13:03:56.227 31785 31785 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 31785 (libtpnsWatchdog)
02-26 13:03:56.305 31787 31787 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-26 13:03:56.305 31787 31787 F DEBUG   : Build fingerprint: 'samsung/hero2qltezc/hero2qltechn:7.0/NRD90M/G9350ZCU2ZQA1:user/release-keys'
02-26 13:03:56.305 31787 31787 F DEBUG   : Revision: '15'
02-26 13:03:56.305 31787 31787 F DEBUG   : ABI: 'arm'
02-26 13:03:56.305 31787 31787 F DEBUG   : pid: 31785, tid: 31785, name: libtpnsWatchdog  >>> /data/data/com.motie.motiereader/lib/libtpnsWatchdog.so <<<
02-26 13:03:56.305 31787 31787 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-26 13:03:56.306 31787 31787 F DEBUG   :     r0 00000000  r1 00007c29  r2 00000006  r3 00000008
02-26 13:03:56.306 31787 31787 F DEBUG   :     r4 f2cbf58c  r5 00000006  r6 f2cbf534  r7 0000010c
02-26 13:03:56.306 31787 31787 F DEBUG   :     r8 f2c5b000  r9 00000000  sl f2c4e010  fp ffb00388
02-26 13:03:56.306 31787 31787 F DEBUG   :     ip 00000000  sp ffb00308  lr f2c9ff8f  pc f2ca0a1c  cpsr 200f0010
02-26 13:03:56.311 31787 31787 F DEBUG   :
02-26 13:03:56.311 31787 31787 F DEBUG   : backtrace:
02-26 13:03:56.311 31787 31787 F DEBUG   :     #00 pc 00045a1c  /system/bin/linker (__dl_tgkill+12)
02-26 13:03:56.311 31787 31787 F DEBUG   :     #01 pc 00044f8b  /system/bin/linker (__dl_pthread_kill+34)
02-26 13:03:56.311 31787 31787 F DEBUG   :     #02 pc 0003d21f  /system/bin/linker (__dl_raise+10)
02-26 13:03:56.311 31787 31787 F DEBUG   :     #03 pc 0003bcab  /system/bin/linker (__dl___libc_android_abort+34)
02-26 13:03:56.311 31787 31787 F DEBUG   :     #04 pc 0003ac0c  /system/bin/linker (__dl_abort+4)
02-26 13:03:56.311 31787 31787 F DEBUG   :     #05 pc 0003ccfb  /system/bin/linker (__dl___libc_fatal+22)
02-26 13:03:56.311 31787 31787 F DEBUG   :     #06 pc 000094a1  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2392)
02-26 13:03:56.311 31787 31787 F DEBUG   :     #07 pc 00008ab3  /system/bin/linker (__dl___linker_init+358)
02-26 13:03:56.311 31787 31787 F DEBUG   :     #08 pc 000027d0  /system/bin/linker (_start+4)
02-26 13:04:02.583 31830 31830 F libc    : "/data/data/com.motie.motiereader/lib/libtpnsWatchdog.so": error: only position independent executables (PIE) are supported.
02-26 13:04:02.583 31830 31830 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 31830 (libtpnsWatchdog)
02-26 13:04:06.403 32477 32477 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-26 13:04:06.403 32477 32477 F DEBUG   : Build fingerprint: 'samsung/hero2qltezc/hero2qltechn:7.0/NRD90M/G9350ZCU2ZQA1:user/release-keys'
02-26 13:04:06.403 32477 32477 F DEBUG   : Revision: '15'
02-26 13:04:06.403 32477 32477 F DEBUG   : ABI: 'arm'
02-26 13:04:06.403 32477 32477 F DEBUG   : pid: 31830, tid: 31830, name: libtpnsWatchdog  >>> /data/data/com.motie.motiereader/lib/libtpnsWatchdog.so <<<
02-26 13:04:06.403 32477 32477 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-26 13:04:06.403 32477 32477 F DEBUG   :     r0 00000000  r1 00007c56  r2 00000006  r3 00000008
02-26 13:04:06.403 32477 32477 F DEBUG   :     r4 f76ca58c  r5 00000006  r6 f76ca534  r7 0000010c
02-26 13:04:06.403 32477 32477 F DEBUG   :     r8 f7666000  r9 00000000  sl f7659010  fp ff8846a8
02-26 13:04:06.403 32477 32477 F DEBUG   :     ip 00000000  sp ff884628  lr f76aaf8f  pc f76aba1c  cpsr 200f0010
02-26 13:04:06.409 32477 32477 F DEBUG   :
02-26 13:04:06.409 32477 32477 F DEBUG   : backtrace:
02-26 13:04:06.409 32477 32477 F DEBUG   :     #00 pc 00045a1c  /system/bin/linker (__dl_tgkill+12)
02-26 13:04:06.409 32477 32477 F DEBUG   :     #01 pc 00044f8b  /system/bin/linker (__dl_pthread_kill+34)
02-26 13:04:06.409 32477 32477 F DEBUG   :     #02 pc 0003d21f  /system/bin/linker (__dl_raise+10)
02-26 13:04:06.410 32477 32477 F DEBUG   :     #03 pc 0003bcab  /system/bin/linker (__dl___libc_android_abort+34)
02-26 13:04:06.410 32477 32477 F DEBUG   :     #04 pc 0003ac0c  /system/bin/linker (__dl_abort+4)
02-26 13:04:06.410 32477 32477 F DEBUG   :     #05 pc 0003ccfb  /system/bin/linker (__dl___libc_fatal+22)
02-26 13:04:06.410 32477 32477 F DEBUG   :     #06 pc 000094a1  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2392)
02-26 13:04:06.410 32477 32477 F DEBUG   :     #07 pc 00008ab3  /system/bin/linker (__dl___linker_init+358)
02-26 13:04:06.410 32477 32477 F DEBUG   :     #08 pc 000027d0  /system/bin/linker (_start+4)
02-26 15:50:10.979 14682 14682 F libc    : "/data/data/com.zhaopin.social/files/gdaemon_20151105": error: only position independent executables (PIE) are supported.
02-26 15:50:10.979 14682 14682 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 14682 (gdaemon_2015110)
02-26 15:50:11.044 14688 14688 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-26 15:50:11.052 14688 14688 F DEBUG   : Build fingerprint: 'samsung/hero2qltezc/hero2qltechn:7.0/NRD90M/G9350ZCU2ZQA1:user/release-keys'
02-26 15:50:11.052 14688 14688 F DEBUG   : Revision: '15'
02-26 15:50:11.052 14688 14688 F DEBUG   : ABI: 'arm'
02-26 15:50:11.052 14688 14688 F DEBUG   : pid: 14682, tid: 14682, name: gdaemon_2015110  >>> /data/data/com.zhaopin.social/files/gdaemon_20151105 <<<
02-26 15:50:11.052 14688 14688 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-26 15:50:11.052 14688 14688 F DEBUG   :     r0 00000000  r1 0000395a  r2 00000006  r3 00000008
02-26 15:50:11.052 14688 14688 F DEBUG   :     r4 f60ce58c  r5 00000006  r6 f60ce534  r7 0000010c
02-26 15:50:11.052 14688 14688 F DEBUG   :     r8 f606a000  r9 00000000  sl f605d010  fp ffc3bd08
02-26 15:50:11.052 14688 14688 F DEBUG   :     ip 00000000  sp ffc3bc88  lr f60aef8f  pc f60afa1c  cpsr 200f0010
02-26 15:50:11.057 14688 14688 F DEBUG   :
02-26 15:50:11.057 14688 14688 F DEBUG   : backtrace:
02-26 15:50:11.058 14688 14688 F DEBUG   :     #00 pc 00045a1c  /system/bin/linker (__dl_tgkill+12)
02-26 15:50:11.058 14688 14688 F DEBUG   :     #01 pc 00044f8b  /system/bin/linker (__dl_pthread_kill+34)
02-26 15:50:11.058 14688 14688 F DEBUG   :     #02 pc 0003d21f  /system/bin/linker (__dl_raise+10)
02-26 15:50:11.058 14688 14688 F DEBUG   :     #03 pc 0003bcab  /system/bin/linker (__dl___libc_android_abort+34)
02-26 15:50:11.058 14688 14688 F DEBUG   :     #04 pc 0003ac0c  /system/bin/linker (__dl_abort+4)
02-26 15:50:11.058 14688 14688 F DEBUG   :     #05 pc 0003ccfb  /system/bin/linker (__dl___libc_fatal+22)
02-26 15:50:11.058 14688 14688 F DEBUG   :     #06 pc 000094a1  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2392)
02-26 15:50:11.058 14688 14688 F DEBUG   :     #07 pc 00008ab3  /system/bin/linker (__dl___linker_init+358)
02-26 15:50:11.058 14688 14688 F DEBUG   :     #08 pc 000027d0  /system/bin/linker (_start+4)
02-26 18:29:36.808  6760  6760 F libc    : "/data/data/com.zhaopin.social/files/gdaemon_20151105": error: only position independent executables (PIE) are supported.
02-26 18:29:36.808  6760  6760 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 6760 (gdaemon_2015110)
02-26 18:29:36.873  6762  6762 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-26 18:29:36.875  6762  6762 F DEBUG   : Build fingerprint: 'samsung/hero2qltezc/hero2qltechn:7.0/NRD90M/G9350ZCU2ZQA1:user/release-keys'
02-26 18:29:36.875  6762  6762 F DEBUG   : Revision: '15'
02-26 18:29:36.875  6762  6762 F DEBUG   : ABI: 'arm'
02-26 18:29:36.876  6762  6762 F DEBUG   : pid: 6760, tid: 6760, name: gdaemon_2015110  >>> /data/data/com.zhaopin.social/files/gdaemon_20151105 <<<
02-26 18:29:36.876  6762  6762 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-26 18:29:36.877  6762  6762 F DEBUG   :     r0 00000000  r1 00001a68  r2 00000006  r3 00000008
02-26 18:29:36.877  6762  6762 F DEBUG   :     r4 eec7058c  r5 00000006  r6 eec70534  r7 0000010c
02-26 18:29:36.877  6762  6762 F DEBUG   :     r8 eec0c000  r9 00000000  sl eebff010  fp ff972b38
02-26 18:29:36.877  6762  6762 F DEBUG   :     ip 00000000  sp ff972ab8  lr eec50f8f  pc eec51a1c  cpsr 200f0010
02-26 18:29:36.893  6762  6762 F DEBUG   :
02-26 18:29:36.893  6762  6762 F DEBUG   : backtrace:
02-26 18:29:36.893  6762  6762 F DEBUG   :     #00 pc 00045a1c  /system/bin/linker (__dl_tgkill+12)
02-26 18:29:36.893  6762  6762 F DEBUG   :     #01 pc 00044f8b  /system/bin/linker (__dl_pthread_kill+34)
02-26 18:29:36.893  6762  6762 F DEBUG   :     #02 pc 0003d21f  /system/bin/linker (__dl_raise+10)
02-26 18:29:36.893  6762  6762 F DEBUG   :     #03 pc 0003bcab  /system/bin/linker (__dl___libc_android_abort+34)
02-26 18:29:36.893  6762  6762 F DEBUG   :     #04 pc 0003ac0c  /system/bin/linker (__dl_abort+4)
02-26 18:29:36.893  6762  6762 F DEBUG   :     #05 pc 0003ccfb  /system/bin/linker (__dl___libc_fatal+22)
02-26 18:29:36.893  6762  6762 F DEBUG   :     #06 pc 000094a1  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2392)
02-26 18:29:36.893  6762  6762 F DEBUG   :     #07 pc 00008ab3  /system/bin/linker (__dl___linker_init+358)
02-26 18:29:36.893  6762  6762 F DEBUG   :     #08 pc 000027d0  /system/bin/linker (_start+4)
02-27 11:38:37.476 22695 22695 F libc    : "/data/data/com.zhaopin.social/files/gdaemon_20151105": error: only position independent executables (PIE) are supported.
02-27 11:38:37.477 22695 22695 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 22695 (gdaemon_2015110)
02-27 11:38:37.559 22698 22698 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-27 11:38:37.560 22698 22698 F DEBUG   : Build fingerprint: 'samsung/hero2qltezc/hero2qltechn:7.0/NRD90M/G9350ZCU2ZQA1:user/release-keys'
02-27 11:38:37.561 22698 22698 F DEBUG   : Revision: '15'
02-27 11:38:37.561 22698 22698 F DEBUG   : ABI: 'arm'
02-27 11:38:37.562 22698 22698 F DEBUG   : pid: 22695, tid: 22695, name: gdaemon_2015110  >>> /data/data/com.zhaopin.social/files/gdaemon_20151105 <<<
02-27 11:38:37.562 22698 22698 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-27 11:38:37.562 22698 22698 F DEBUG   :     r0 00000000  r1 000058a7  r2 00000006  r3 00000008
02-27 11:38:37.562 22698 22698 F DEBUG   :     r4 f544058c  r5 00000006  r6 f5440534  r7 0000010c
02-27 11:38:37.562 22698 22698 F DEBUG   :     r8 f53dc000  r9 00000000  sl f53cf010  fp fff96a78
02-27 11:38:37.563 22698 22698 F DEBUG   :     ip 00000000  sp fff969f8  lr f5420f8f  pc f5421a1c  cpsr 200f0010
02-27 11:38:37.588 22698 22698 F DEBUG   :
02-27 11:38:37.588 22698 22698 F DEBUG   : backtrace:
02-27 11:38:37.589 22698 22698 F DEBUG   :     #00 pc 00045a1c  /system/bin/linker (__dl_tgkill+12)
02-27 11:38:37.589 22698 22698 F DEBUG   :     #01 pc 00044f8b  /system/bin/linker (__dl_pthread_kill+34)
02-27 11:38:37.589 22698 22698 F DEBUG   :     #02 pc 0003d21f  /system/bin/linker (__dl_raise+10)
02-27 11:38:37.589 22698 22698 F DEBUG   :     #03 pc 0003bcab  /system/bin/linker (__dl___libc_android_abort+34)
02-27 11:38:37.589 22698 22698 F DEBUG   :     #04 pc 0003ac0c  /system/bin/linker (__dl_abort+4)
02-27 11:38:37.589 22698 22698 F DEBUG   :     #05 pc 0003ccfb  /system/bin/linker (__dl___libc_fatal+22)
02-27 11:38:37.589 22698 22698 F DEBUG   :     #06 pc 000094a1  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2392)
02-27 11:38:37.589 22698 22698 F DEBUG   :     #07 pc 00008ab3  /system/bin/linker (__dl___linker_init+358)
02-27 11:38:37.589 22698 22698 F DEBUG   :     #08 pc 000027d0  /system/bin/linker (_start+4)
02-27 17:27:37.124 10824 10841 E AndroidRuntime: !@*** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-1
02-27 17:27:37.124 10824 10841 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:62)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
02-27 17:27:37.124 10824 10841 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        ... 1 more
02-27 17:27:37.124 10824 10841 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unknown package: tursky.jan.nauc.sa.html5
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1697)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1646)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:5435)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at me.piebridge.brevent.server.d.a(HideApi.java:161)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:651)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:318)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.handleMessage(BreventServer.java:213)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:888)
02-27 17:27:37.124 10824 10841 E AndroidRuntime:        ... 3 more

**Comment by liudongmiao** [comment]
这也太巧了，在处理过程中，你卸载了某个应用。

**Comment by BadGuyX** [comment]
0.0

**Comment by liudongmiao** [comment]
十天内没有继续反馈，关闭。
