### ISSUE TITLE
HTC 10安卓N系统（开发者版2.28.6固件）打补丁时提示IntentResolver多打一处补丁

### ISSUE THREAD

**Issue by chr0247** [liudongmiao/Brevent#13]
在打补丁时，显示：为IntentResolver打了3处补丁，应该打2处。最终输出的services.jar和原版没任何改变。

**Comment by liudongmiao** [comment]
贴这个文件。路径我就不贴了，在子目录找 `IntentResolver.smali` 。

**Comment by chr0247** [comment]
辛苦你了

**Comment by chr0247** [comment]
昨天邮件回复的附件，不知道有没有收到，我再上传网盘一份吧
http://pan.baidu.com/s/1dEHbEMH

**Comment by chr0247** [comment]
通过分析在6.0.1上patch前后的文件，手动修改7.0的相关文件，已经实现了正常运行。不过还是建议作者完善下脚本，能实现自动patch。本人以及群内朋友略捐赠，感谢作者的辛苦付出。

**Comment by chr0247** [comment]
多打的一处补丁在方法.method public queryIntent(Landroid/content/Intent;Ljava/lang/String;ZI)Ljava/util/List;下的一个调用invoke-virtual/range {p1 .. p1}, Landroid/content/Intent;->isExcludingStopped()Z

**Comment by liudongmiao** [comment]
最近真的相当忙，网盘在公司又没法访问。主要是看这个的依赖。

你测试下，如果确实这处打上也能运行的话，告诉我，我直接想个办法让它不出错就好。

之前类似的做法见些：https://github.com/liudongmiao/Brevent/commit/b141c89cbdd9347eb47dc612c2e24348f885b549  (处理htc)

**Comment by liudongmiao** [comment]
这种方式将不再支持，抱歉。
