### ISSUE TITLE
0.7.4休眠问题

### ISSUE THREAD

**Issue by eYoungNoir** [liudongmiao/Brevent#135]
升级0.7.4后，插电状态下，前台app在back到后台之后不会进入休眠状态，闲置多久都不会，只能手动划掉结束运行，但是偶尔后台自动唤醒的却会在休眠中，工作正常。不插电状态正常。之前版本也能正常休眠。

**Comment by liudongmiao** [comment]
插电状态不会休眠的，这是 Android 底层设计，在休眠里，我也来了括号说明这种情况。

此外，在 0.7.1 中会息屏后休眠前台运行的 app，但是这样反而更不好处理，因为还得开屏以后，不再限制。反而让整个流程变得复杂，所以回归简单，永不处理前台应用。
