### ISSUE TITLE
0.8 功能点

### ISSUE THREAD

**Issue by liudongmiao** [liudongmiao/Brevent#136]
- [ ] 卸载或变更设定时，退出机制
   - [x] 卸载时，删除配置文件
   - [ ] 卸载时，恢复 appops
   - [ ] 设置中取消 appops 时，恢复 appops
      - [ ] 启用 appops 应该是一个设置，而不是默认 #129 #133 

- [ ] 支持 root 模式
   - [ ] 自启，需要 su
      - [ ] 必要时，提供 rom 补丁
   - [ ] ~正在使用的 vpn 判定~
   - [ ] 付费模式与验证 (这种模式我不受益，但开发调试要花好久)

- [ ] 支持只休眠，以及只强行停止模式（目前是休眠+强行停止）
  1. 使用服务开启过的唤醒，一律强行停止 （动态延后 30s 或 立即处理）
  2. 用户打开过的应用
      1. 休眠：一律都休眠
      2. 强行停止：一律都强行停止
      3. 休眠然后强行停止：休眠，如果不在最近列表中（系统+3小时限制），就强行停止

- [ ] 重要应用的识别
   - [ ] gms 等使用规则 （系统的 persistent 进程, system_server 等）
   - [ ] 允许某些框架应用

- [ ] 前端
   - [ ] 是否把动词黑域，是否直接换成“处理”
   - [ ] 大量提示语的更新
   - [ ] 界面中，icon 及时间的提示语

**Comment by PhotonQuantum** [comment]
希望能针对一些未适配standby的应用直接强制停止 不知道这能不能识别？

**Comment by liudongmiao** [comment]
@PhotonQuantum 可能比较难。一个可以处理的模式，是看它的 targetSdk，但可能用处不大。我后期会考虑一下。

但是，从另外一方面讲，其实用户不大。在休眠之后，程序是不可感知的；而在主动打开(focus)后，黑域会显式针对这个应用退出休眠。所以，对于应用本身而言，意义有限。当然，如果说，就在这一个瞬间，应用就受很大影响，这和没有适配网络差不多。

此外，休眠在你没有打开它的时候，最多只会持续 3 小时，系统(android 7)是 6 小时。

**Comment by PhotonQuantum** [comment]
嗯 还有一个问题就是 有些应用被休眠之后还会读秒 比如QQ和冰箱 那这样的应用处于什么状态呢？

**Comment by liudongmiao** [comment]
@PhotonQuantum 后台应用，表示你没退出（按HOME或者切换应用，或者某些流氓）。首屏及设置的下面都有提及。

**Comment by neoFelhz** [comment]
1.2 希望卸载后不要清除 AppOps，这样下次安装时可以继续用原来的配置。

**Comment by PhotonQuantum** [comment]
诶那如何干掉这些流氓呢 我的确是back退出的 已经进了休眠列表 然而还是磕了药一样读秒

**Comment by liudongmiao** [comment]
@neoFelhz 为了安全，会清空设置，否则问题更严重。

@PhotonQuantum 不用管它。你要么从最近列表划掉，要么等它休眠直到3小时，要么等下一个版本，选择只强行停止。我本来有选项，对于这种不遵守 BACK 的，直接强行停止，但觉得不好，没开放。

**Comment by PhotonQuantum** [comment]
直接停止感觉就有点过了。。希望还是有选项区分这些不遵守back的程序能够直接干掉

**Comment by simonsmh** [comment]
最好能和其他的优秀的appops软件配合，而并非一定要选择黒域的设置

**Comment by 849506054** [comment]
自主选择是否处理通知

**Comment by 849506054** [comment]
某些本来自己阻止了通知的应用，黑域之后会打开通知

**Comment by liudongmiao** [comment]
@Aroamer-L-K 真心怀疑你有没安装。apoops后台应用，不是一个选项么，自己去开启不就行了？

**Comment by liudongmiao** [comment]
@849506054 你没看到功能点里说了，这是一个问题，会修么？

**Comment by 849506054** [comment]
好吧，并没有理解到你说的appops就是指的通知这个问题

**Comment by Aroamer-L-K** [comment]
@liudongmiao 作者您好，首先很感谢您能够回复，并给予回答，但是很显然我尽量保证能使配置一样，环境一样，新版同样开了原生后台限制，动态延后和立即处理也都试了，这样的情况下还是耗电，更加严格的对比请原谅难以做到了，您怀疑我没有装，如果我没有使用上的明显感觉我又何必向您反馈感觉像无理取闹一般自讨无趣，难道还需要桌面截图向您证实我在使用您的软件吗？况且新版耗电不止我一人有感觉只是不如我这样明显。不管怎样，我能力不够且也没有做过相关工作，很感谢并敬佩您做的工作，为广大安卓用户带来很优秀的应用，祝您做的更好。耗电的事儿，或许是我个例，我自行解决。谢谢。

**Comment by liudongmiao** [comment]
@Aroamer-L-K 你是在比 0.4 与最新版，我就说了，0.4 的 appops 目前是可选的，至于你想要的强行停止，目前也是可以的（全部从最近列表划掉而已）。然后你又说晚上待机，说电量啥的，我真不敢认同，要测试，我自己也测了，同时，也不止一个网友说了，晚上待机关数据情况下，基本不耗电；我自己测试，不关网络与数据，也就 2% 左右。目前，黑域服务信息也能显示出自己的电量，至于系统及系统软件的电量，我真心无法处理，如果使用不当，只会加大系统与系统软件耗电量。

然后，你又说 0.7.1 与 0.7.4 的区别，这两版本之间几乎没有改动，然后你说差别这么大。就你这种感觉，我根本没法信服，只能怀疑你是否使用了。

关于 0.4，请忘记它，谢谢，它是我的耻辱。

**Comment by Aroamer-L-K** [comment]
@liudongmiao 感谢您回复，关于耗电问题我自行抉择吧，我会使用最合适的一版，达到最少耗电。祝您一切顺利，越做越好。

**Comment by hubeixulu** [comment]
作者大神，在休眠列表里面的应用都是已经休眠不耗电的吧，我看了下休眠列表里面的应用也有几个状态，比如后台服务，缓存，还有进程还有很多读秒的等，这些我统统都不用关心吧，只要在休眠列表里面就好了吧

**Comment by liudongmiao** [comment]
不用关心休眠的状态。你要问我，是否严格不耗电，我会说，会耗电。但是，这是一个再次打开快速、可能收到消息(如GCM)及耗电之间的一个平衡。你看到了，上面提到了，下版会给两个极端，只休眠或者只强杀。

**Comment by 1liang** [comment]
作者大人，为什么我后台超过3小时问没有自动杀掉？

**Comment by liudongmiao** [comment]
提供日志 (`logcat -b main -d -s BreventLoader BreventServer`)，以及 `dumpsys activity recents` 结果。

**Comment by 849506054** [comment]
关于通知这块，再提个问题。
未加入黑域处理的应用通知也被处理，重启后也不会自动还原
某些本来我没加入黑域处理的应用，自己屏蔽了通知的应用，只要打开过就会自动恢复通知权限

等等这种情况，造成很多不便利

**Comment by liudongmiao** [comment]
@849506054 感谢反馈，在刚发的 0.7.6 中修复了，谢谢。

**Comment by lethe07** [comment]
在最新版，黑域掉的应用通知级别为0，打开应用后通知等级还是0，请问这是问题还是说就是这样的设置啊…

**Comment by lethe07** [comment]
大神…在酷安问到怎么回事了…上一条抱歉了…不能删除请见谅。重启导致通知级别为0会优化吗…

**Comment by SPRING-Z** [comment]
还是希望支持root模式的

**Comment by SPRING-Z** [comment]
省事，方便，毕竟黑域的用户大部分手机应该都是root过的

**Comment by t123yh** [comment]
请问接下来的版本会有源码吗？非常希望研究学习您的修改。

**Comment by liudongmiao** [comment]
为了安全，及相关保护，目前只在下一个版本发布时，才开放上一个版本源码。

0.7 系列的，请看这里：https://github.com/liudongmiao/Brevent/tree/0.7

**Comment by liudongmiao** [comment]
0.8 改动比较多，但总体思路不变。

**Comment by zhouzhuang** [comment]
希望Root模式可以开机自启，不需要每次开机都进入App点一下。

**Comment by liudongmiao** [comment]
@zhouzhuang 已经开放。开机自启功能，去设置中开启“允许ROOT运行”即可。

**Comment by hubeixulu** [comment]
大神，有几个应用长时间都没有休眠，请问是什么原因造成的呢，还是说时间没到啊
![screenshot_20170306-165012](https://cloud.githubusercontent.com/assets/20060019/23602856/79a1fda0-028d-11e7-96d3-aadfe2d74191.png)

**Comment by liudongmiao** [comment]
@hubeixulu 休眠需要你系统支持。

**Comment by hubeixulu** [comment]
@liudongmiao 但是有部分应用是可以休眠的，休眠列表里面有14个应用，我看了下百度贴吧到了30分钟开始才休眠，我理解的是30分钟干掉程序
![screenshot_20170306-171208](https://cloud.githubusercontent.com/assets/20060019/23605044/25da9dfe-0296-11e7-97eb-ecefe1e9f911.png)

**Comment by liudongmiao** [comment]
请参照向导第一屏

**Comment by hubeixulu** [comment]
大神，有问题反馈一下，版本是0.8.4，ADB方式，一加3T 7.1.1
一加3T有自带的应用加密功能，我把两个应用加密了，同时应用也放在黑域阻止列表了，现在只要打开应用就会闪退（应该是被黑域干掉了），解除黑域阻止列表就没事了。0.8.4之前的版本是没有这个问题的，还有部分应用分享的时候会被干掉，只是部分应用

**Comment by liudongmiao** [comment]
1. 不要选择 appops 之类，之前有支持，当你打开时，会自动解除
2. 不要选择立即处理模式，兼容性得不到保证

此外，换个新的 github issue
