### ISSUE TITLE
长时间运行后后台服务似乎停止

### ISSUE THREAD

**Issue by PhotonQuantum** [liudongmiao/Brevent#137]
似乎在手机在长时间闲置之后黑域后台服务就会莫名消失 因为后台已经被我重启所以暂时没有抓到logcat 如果下次重现我会再附上

**Comment by liudongmiao** [comment]
我这边完全没有。理论上， 黑域服务不受 Android 系统限制。但不排除有第三方应用，主动排查并杀的可能。

**Comment by liudongmiao** [comment]
我这边偶尔也出现，问题难以定位。

**Comment by PhotonQuantum** [comment]
啊这就麻烦了 因为根本不知道什么时候会挂 本来还以为这个问题是偶发的 我这重现也不容易 因为只出现了2次 log也没

**Comment by liudongmiao** [comment]
接下来，我会改变目前工作模式。
