### ISSUE TITLE
0.7.4中美团强杀不掉

### ISSUE THREAD

**Issue by amdth** [liudongmiao/Brevent#138]
有几个问题 
1 adb命令执行成功后是不是有“checking.... ok"的标志？
2 从最近列表中划掉美团，在黑域中查看美团的状态，确实是stopped的状态；而关闭屏幕，然后打开之后看到美团的状态是standy，好像没法强杀

**Comment by liudongmiao** [comment]
1. 现在提示语好像变了，反正没说让你带上日志汇报的，都属于正常

2. 强杀嘛，不用那么在意。有时，真的，最近列表展示的与 api 返回的不一致。我下个版本会提供不休眠，只强杀策略。再这么弄下去，反而投入与产出不成比例，调试相当困难，模拟器上又没法完全测试。但是，即使是目前的休眠，也不会超过某个时间点。

3. 作为美团前员工，我非常建议卸载美团这种流氓应用。

**Comment by liudongmiao** [comment]
感谢反馈，我将在 0.7.5 中修复这个问题。

**Comment by amdth** [comment]
修复问题后，耗电量也有所改善，1% 8h

**Comment by liudongmiao** [comment]
十天内没有继续反馈，关闭。
