### ISSUE TITLE
Nexus 6p 拿起设备无法唤醒屏幕通知或时钟

### ISSUE THREAD

**Issue by Bob021** [liudongmiao/Brevent#139]
更新新版本的黑域，发现拿起设备唤醒屏幕功能不起作用，设置了已开启move。

**Comment by liudongmiao** [comment]
请不要阻止重要应用，以及，参照酷安公告去除原生后台限制。

**Comment by Bob021** [comment]
柳大，之前刷过7.1.2系统，黑域不能使用，后来完全线刷的7.1.1系统，直接使用Play版最新黑域。这之间没有阻止过系统应用，也没有使用0.4版黑域，现在突然发现关屏下设备无法唤醒屏幕。
您的Pixel 手机可以双击唤醒屏幕吗？

**Comment by liudongmiao** [comment]
不知道双击唤醒屏幕什么意思，但我的是拿起来就亮了。

**Comment by Bob021** [comment]
我之前也是拿起来亮屏，现在lift to check却不行了，不知道什么原因。
Double tap to check
On Pixel phones, you can check your notifications by double tapping your screen.
Lift to check
You can check your notifications by picking up your phone.

**Comment by liudongmiao** [comment]
我刚看了下，这两个都正常工作。

**Comment by Bob021** [comment]
收到，那是我手机问题，我再看看，谢谢柳大帮忙确认。
