### ISSUE TITLE
0.7.4版本无法将浙江移动营业厅添加到黑域列表

### ISSUE THREAD

**Issue by TAXUEZJU** [liudongmiao/Brevent#141]
如题，不知因为什么原因，可以在黑域里选中该应用，但是选择黑域后右边没有标记，也不会被处理，是不是识别成了VPN了……

**Comment by liudongmiao** [comment]
花了 20M 流量下载，无法重现。

**Comment by TAXUEZJU** [comment]
并不知道是什么原因，今天更新了0.7.5之后正常了，原先只保留了录屏的视频，没有日志之类的，估计也没什么帮助
