### ISSUE TITLE
三星S6应用从不休眠

### ISSUE THREAD

**Issue by Julymycin** [liudongmiao/Brevent#142]
如题…看酷安评论好像三星都这样，不知道能解决吗？

**Comment by zzzdtz** [comment]
三星6.0的系统关闭了潜睡，等7.0吧

**Comment by zzzdtz** [comment]
动手能力强的话，执行下 dumpsys deviceidle enabled 开启

**Comment by Julymycin** [comment]
怎么执行，adb吗？并没有root呢。

**Comment by zzzdtz** [comment]
adb -d shell   dumpsys deviceidle enable 我刚多打了个D，抱歉

**Comment by Julymycin** [comment]
好的 我回去试试 谢谢！

**Comment by Julymycin** [comment]
依旧不休眠。不过好像本身就是doze就是开启的。
  mEnabled=true
  m3rdWhitelistEnable=false
  mForceIdle=false
  mScreenOn=false
  mCharging=false
  mSigMotionActive=false
  mSensing=false mNotMoving=false
  mLocating=false mHaveGps=true mLocated=false
  mState=INACTIVE
  mInactiveTimeout=+30m0s0ms
  mNextAlarmTime=+29m55s927ms

我unlug然后关屏幕之后，使用三步step可以由active进入idle
shell@zerofltechn:/ $ dumpsys deviceidle step
Stepped to: IDLE_PENDING
shell@zerofltechn:/ $ dumpsys deviceidle step
Stepped to: SENSING
shell@zerofltechn:/ $ dumpsys deviceidle step
Stepped to: LOCATING

**Comment by Julymycin** [comment]
我觉得似乎是standby的问题？
shell@zerofltechn:/ $ am set-inactive com.tencent.mm **true**
shell@zerofltechn:/ $  am get-inactive com.tencent.mm
Idle=**false**

**Comment by liudongmiao** [comment]
1. 如果加入了电池优化白名单，是不会休眠的。0.8.2 界面上选择以后，会显示，并且不许加入。0.8.3 起，将只会提示，可以加入
2. 充电时，不会休眠。

**Comment by Julymycin** [comment]
1.我测试了微信，酷市场，chrome，微信加入了三星智能管理器的自启名单，后两者没有加入。电池优化白名单除了系统默认的如Samsung push service之类的，没有别的了。
  shell@zerofltechn:/ $ am set-inactive com.coolapk.market **true**
  shell@zerofltechn:/ $ am get-inactive com.coolapk.market
  Idle=**false**
2.没有在充电，adb测试的时候，也执行了dumpsys battery unplug。

**Comment by liudongmiao** [comment]
多执行几次，以及不要让它在前台

**Comment by Julymycin** [comment]
还是不行。
感觉应该是三星ROM的问题吧。不管我执行多少次：
**am set-inactive com.coolapk.market true**
得到的都是：
**am get-inactive com.coolapk.market
Idle=false**
而且不管我是强行停止酷市场还是用空调购把它冻结了，都是这样的结果。

**Comment by liudongmiao** [comment]
看来可能就是系统不允许休眠...你可以更换黑域模式为“只强行停止，不休眠”。

**Comment by zzzdtz** [comment]
三星6.0确实不支持休眠，7.0可以。
