### ISSUE TITLE
miui 8.2升级新版黑域，adb失败 - uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS

### ISSUE THREAD

**Issue by rookiedong521** [liudongmiao/Brevent#146]
C:\Users\D>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
02-28 17:02:25.078 18834 18849 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-28 17:02:25.078 18834 18849 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:62)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-28 17:02:25.078 18834 18849 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        ... 1 more
02-28 17:02:25.078 18834 18849 E AndroidRuntime: Caused by: java.lang.SecurityException: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at com.android.internal.app.IAppOpsService$Stub$Proxy.setMode(IAppOpsService.java:607)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at me.piebridge.brevent.server.d.a(HideApi.java:180)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at me.piebridge.brevent.server.d.b(HideApi.java:200)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:322)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:743)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:140)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:879)
02-28 17:02:25.078 18834 18849 E AndroidRuntime:        ... 3 more
02-28 17:02:25.085 18834 18849 E AndroidRuntime: Error reporting crash
02-28 17:02:25.085 18834 18849 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-28 17:02:25.085 18834 18849 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-28 17:02:25.085 18834 18849 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
02-28 17:02:25.085 18834 18849 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4449)
02-28 17:02:25.085 18834 18849 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:145)
02-28 17:02:25.085 18834 18849 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-28 17:02:25.085 18834 18849 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-28 17:19:19.024 23119 23132 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-28 17:19:19.024 23119 23132 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:62)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-28 17:19:19.024 23119 23132 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        ... 1 more
02-28 17:19:19.024 23119 23132 E AndroidRuntime: Caused by: java.lang.SecurityException: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at com.android.internal.app.IAppOpsService$Stub$Proxy.setMode(IAppOpsService.java:607)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at me.piebridge.brevent.server.d.a(HideApi.java:180)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at me.piebridge.brevent.server.d.b(HideApi.java:200)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:322)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:743)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:140)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:879)
02-28 17:19:19.024 23119 23132 E AndroidRuntime:        ... 3 more
02-28 17:19:19.028 23119 23132 E AndroidRuntime: Error reporting crash
02-28 17:19:19.028 23119 23132 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-28 17:19:19.028 23119 23132 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-28 17:19:19.028 23119 23132 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
02-28 17:19:19.028 23119 23132 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4449)
02-28 17:19:19.028 23119 23132 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:145)
02-28 17:19:19.028 23119 23132 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-28 17:19:19.028 23119 23132 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-28 17:27:32.581 25186 25199 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-10
02-28 17:27:32.581 25186 25199 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:62)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-28 17:27:32.581 25186 25199 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        ... 1 more
02-28 17:27:32.581 25186 25199 E AndroidRuntime: Caused by: java.lang.SecurityException: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at com.android.internal.app.IAppOpsService$Stub$Proxy.setMode(IAppOpsService.java:607)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at me.piebridge.brevent.server.d.a(HideApi.java:180)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at me.piebridge.brevent.server.d.b(HideApi.java:200)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:322)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:743)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:140)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:879)
02-28 17:27:32.581 25186 25199 E AndroidRuntime:        ... 3 more
02-28 17:27:32.585 25186 25199 E AndroidRuntime: Error reporting crash
02-28 17:27:32.585 25186 25199 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-28 17:27:32.585 25186 25199 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-28 17:27:32.585 25186 25199 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
02-28 17:27:32.585 25186 25199 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4449)
02-28 17:27:32.585 25186 25199 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:145)
02-28 17:27:32.585 25186 25199 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-28 17:27:32.585 25186 25199 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-28 17:39:42.199 27714 27727 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-28 17:39:42.199 27714 27727 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:62)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-28 17:39:42.199 27714 27727 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        ... 1 more
02-28 17:39:42.199 27714 27727 E AndroidRuntime: Caused by: java.lang.SecurityException: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at com.android.internal.app.IAppOpsService$Stub$Proxy.setMode(IAppOpsService.java:607)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at me.piebridge.brevent.server.d.a(HideApi.java:180)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at me.piebridge.brevent.server.d.b(HideApi.java:200)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:322)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:743)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:140)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:879)
02-28 17:39:42.199 27714 27727 E AndroidRuntime:        ... 3 more
02-28 17:39:42.201 27714 27727 E AndroidRuntime: Error reporting crash
02-28 17:39:42.201 27714 27727 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-28 17:39:42.201 27714 27727 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-28 17:39:42.201 27714 27727 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
02-28 17:39:42.201 27714 27727 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4449)
02-28 17:39:42.201 27714 27727 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:145)
02-28 17:39:42.201 27714 27727 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-28 17:39:42.201 27714 27727 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
02-28 17:02:24.761 18834 18834 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-28 17:02:24.802 18834 18849 D BreventServer: Brevent Server 0.7.7 started
02-28 17:02:24.804 18834 18849 D BreventServer: brevent user: 0
02-28 17:02:24.805 18834 18849 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-28 17:02:24.859 18834 18849 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 111
02-28 17:02:24.859 18834 18849 D BreventServer: loaded brevent list
02-28 17:02:24.860 18834 18849 D BreventServer: loaded brevent conf
02-28 17:02:24.867 18834 18849 D BreventServer: checking
02-28 17:02:25.077 18834 18849 D BreventLoader: Can't run brevent server
02-28 17:02:25.077 18834 18849 D BreventLoader: java.lang.reflect.InvocationTargetException
02-28 17:02:25.077 18834 18849 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-28 17:02:25.077 18834 18849 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-28 17:02:25.077 18834 18849 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-28 17:02:25.077 18834 18849 D BreventLoader: Caused by: java.lang.SecurityException: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
02-28 17:02:25.077 18834 18849 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1620)
02-28 17:02:25.077 18834 18849 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1573)
02-28 17:02:25.077 18834 18849 D BreventLoader:         at com.android.internal.app.IAppOpsService$Stub$Proxy.setMode(IAppOpsService.java:607)
02-28 17:02:25.077 18834 18849 D BreventLoader:         at me.piebridge.brevent.server.d.a(HideApi.java:180)
02-28 17:02:25.077 18834 18849 D BreventLoader:         at me.piebridge.brevent.server.d.b(HideApi.java:200)
02-28 17:02:25.077 18834 18849 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:322)
02-28 17:02:25.077 18834 18849 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:743)
02-28 17:02:25.077 18834 18849 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:140)
02-28 17:02:25.077 18834 18849 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:879)
02-28 17:02:25.077 18834 18849 D BreventLoader:         ... 3 more
02-28 17:02:25.078 18834 18834 D BreventLoader: Brevent Server quit in 30 seconds, quit
02-28 17:19:18.798 23119 23119 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-28 17:19:18.837 23119 23132 D BreventServer: Brevent Server 0.7.7 started
02-28 17:19:18.842 23119 23132 D BreventServer: brevent user: 0
02-28 17:19:18.844 23119 23132 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-28 17:19:18.916 23119 23132 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 111
02-28 17:19:18.916 23119 23132 D BreventServer: loaded brevent list
02-28 17:19:18.917 23119 23132 D BreventServer: loaded brevent conf
02-28 17:19:18.922 23119 23132 D BreventServer: checking
02-28 17:19:19.024 23119 23132 D BreventLoader: Can't run brevent server
02-28 17:19:19.024 23119 23132 D BreventLoader: java.lang.reflect.InvocationTargetException
02-28 17:19:19.024 23119 23132 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-28 17:19:19.024 23119 23132 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-28 17:19:19.024 23119 23132 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-28 17:19:19.024 23119 23132 D BreventLoader: Caused by: java.lang.SecurityException: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
02-28 17:19:19.024 23119 23132 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1620)
02-28 17:19:19.024 23119 23132 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1573)
02-28 17:19:19.024 23119 23132 D BreventLoader:         at com.android.internal.app.IAppOpsService$Stub$Proxy.setMode(IAppOpsService.java:607)
02-28 17:19:19.024 23119 23132 D BreventLoader:         at me.piebridge.brevent.server.d.a(HideApi.java:180)
02-28 17:19:19.024 23119 23132 D BreventLoader:         at me.piebridge.brevent.server.d.b(HideApi.java:200)
02-28 17:19:19.024 23119 23132 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:322)
02-28 17:19:19.024 23119 23132 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:743)
02-28 17:19:19.024 23119 23132 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:140)
02-28 17:19:19.024 23119 23132 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:879)
02-28 17:19:19.024 23119 23132 D BreventLoader:         ... 3 more
02-28 17:19:19.024 23119 23119 D BreventLoader: Brevent Server quit in 30 seconds, quit
02-28 17:27:32.101 25186 25186 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-28 17:27:32.172 25186 25199 D BreventServer: Brevent Server 0.7.7 started
02-28 17:27:32.177 25186 25199 D BreventServer: brevent user: 0
02-28 17:27:32.178 25186 25199 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-28 17:27:32.262 25186 25199 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 111
02-28 17:27:32.262 25186 25199 D BreventServer: loaded brevent list
02-28 17:27:32.264 25186 25199 D BreventServer: loaded brevent conf
02-28 17:27:32.275 25186 25199 D BreventServer: checking
02-28 17:27:32.580 25186 25199 D BreventLoader: Can't run brevent server
02-28 17:27:32.580 25186 25199 D BreventLoader: java.lang.reflect.InvocationTargetException
02-28 17:27:32.580 25186 25199 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-28 17:27:32.580 25186 25199 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-28 17:27:32.580 25186 25199 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-28 17:27:32.580 25186 25199 D BreventLoader: Caused by: java.lang.SecurityException: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
02-28 17:27:32.580 25186 25199 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1620)
02-28 17:27:32.580 25186 25199 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1573)
02-28 17:27:32.580 25186 25199 D BreventLoader:         at com.android.internal.app.IAppOpsService$Stub$Proxy.setMode(IAppOpsService.java:607)
02-28 17:27:32.580 25186 25199 D BreventLoader:         at me.piebridge.brevent.server.d.a(HideApi.java:180)
02-28 17:27:32.580 25186 25199 D BreventLoader:         at me.piebridge.brevent.server.d.b(HideApi.java:200)
02-28 17:27:32.580 25186 25199 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:322)
02-28 17:27:32.580 25186 25199 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:743)
02-28 17:27:32.580 25186 25199 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:140)
02-28 17:27:32.580 25186 25199 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:879)
02-28 17:27:32.580 25186 25199 D BreventLoader:         ... 3 more
02-28 17:27:32.580 25186 25186 D BreventLoader: Brevent Server quit in 30 seconds, quit
02-28 17:39:41.752 27714 27714 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-28 17:39:41.805 27714 27727 D BreventServer: Brevent Server 0.7.7 started
02-28 17:39:41.808 27714 27727 D BreventServer: brevent user: 0
02-28 17:39:41.809 27714 27727 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-28 17:39:41.894 27714 27727 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 111
02-28 17:39:41.895 27714 27727 D BreventServer: loaded brevent list
02-28 17:39:41.897 27714 27727 D BreventServer: loaded brevent conf
02-28 17:39:41.909 27714 27727 D BreventServer: checking
02-28 17:39:42.198 27714 27727 D BreventLoader: Can't run brevent server
02-28 17:39:42.198 27714 27727 D BreventLoader: java.lang.reflect.InvocationTargetException
02-28 17:39:42.198 27714 27727 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-28 17:39:42.198 27714 27727 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-28 17:39:42.198 27714 27727 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-28 17:39:42.198 27714 27727 D BreventLoader: Caused by: java.lang.SecurityException: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
02-28 17:39:42.198 27714 27727 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1620)
02-28 17:39:42.198 27714 27727 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1573)
02-28 17:39:42.198 27714 27727 D BreventLoader:         at com.android.internal.app.IAppOpsService$Stub$Proxy.setMode(IAppOpsService.java:607)
02-28 17:39:42.198 27714 27727 D BreventLoader:         at me.piebridge.brevent.server.d.a(HideApi.java:180)
02-28 17:39:42.198 27714 27727 D BreventLoader:         at me.piebridge.brevent.server.d.b(HideApi.java:200)
02-28 17:39:42.198 27714 27727 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:322)
02-28 17:39:42.198 27714 27727 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:743)
02-28 17:39:42.198 27714 27727 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:140)
02-28 17:39:42.198 27714 27727 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:879)
02-28 17:39:42.198 27714 27727 D BreventLoader:         ... 3 more
02-28 17:39:42.198 27714 27714 D BreventLoader: Brevent Server quit in 30 seconds, quit
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

C:\Users\D>

**Comment by rookiedong521** [comment]
重新安装0.6.1使用 正常

**Comment by liudongmiao** [comment]
没有 UPDATE_APP_OPS_STATS 这个权限，早先是可选的，后来变成了必选。

**Comment by rookiedong521** [comment]
大神，有没有解决方案？

**Comment by liudongmiao** [comment]
等着吧，下个版本，将忽视这个异常。

**Comment by rookiedong521** [comment]
好的，多谢哈

**Comment by liudongmiao** [comment]
@rookiedong521 0.8.1 还出现这个异常么？

**Comment by liudongmiao** [comment]
已经去掉appops功能。
