### ISSUE TITLE
重新解锁屏幕后，网络不能使用。

### ISSUE THREAD

**Issue by Julymycin** [liudongmiao/Brevent#147]
不知道是不是黑域的原因，关屏一段时间后解锁，网络就不能使用了，而且也不是暂时不能使用那种，而是需要开关wifi之后才能重新使用。

**Comment by liudongmiao** [comment]
你把黑域想得太厉害了 。。。

**Comment by Lex-Clan** [comment]
这个真不是黑域的锅，明显是7.0电池优化搞的鬼，得在优化里把微信和网络连接加白名单才会避免断网
