### ISSUE TITLE
黑域在钉钉运行状态显示出现问题，显示未运行，其实是运行中的。

### ISSUE THREAD

**Issue by XGHeaven** [liudongmiao/Brevent#148]
版本: v0.7.7

1. 将钉钉加入到 block 列表
2. 查看钉钉状态，黑域显示 (not running)，应用的 force stop 无法点击，也就是未运行。
3. 打开钉钉
4. 切换到黑域，看到钉钉处于 (running) 状态
4. 切换回钉钉，然后按后退回到启动器，在最近任务中删除钉钉卡片。
5. 打开黑域，看到钉钉的状态变成 (not running)，但是进入 app info，可以看到 force stop 是可以点击的状态。也就是说黑域显示未运行，实际上是在运行中。

我尝试了其他的程序，比如说美团，支付宝，闲鱼，飞猪等阿里系的软件都没有问题，都可以正常 force stop，并且显示 (not running)

**Comment by liudongmiao** [comment]
不要使用系统的是否可以 force stop 来判断是否在运行。简而言之，相信黑域。

如果你真的不相信，可以使用以下更直接的方式：

- `ps`
- `dumpsys activity processes`
- 系统中的正在运行服务

如果还是不相信黑域，请直接卸载吧。

**Comment by liudongmiao** [comment]
在接下来的版本里，会有“允许GCM”的选项。这个选项里，即使强行停止，也会把停止状态调为 false，以便接收 GCM 消息。

**Comment by XGHeaven** [comment]
OK
