### ISSUE TITLE
cm14.1 打补丁时出错了

### ISSUE THREAD

**Issue by luanzun** [liudongmiao/Brevent#15]
在进行打补丁的时候提示错误
`python patch.py -a apk -s services`

`Traceback (most recent call last):`
`  File "patch.py", line 315, in <module>`
`    main()`
`  File "patch.py", line 308, in main`
`    IntentResolver(options.dir_services).run()`
`  File "patch.py", line 67, in run`
`    os.rename(path, path + ".orig")`
`WindowsError: [Error 183]`

**Comment by luanzun** [comment]
已解决，之前用的是python2.7，重新用3.5就好了。不知道啥情况。

**Comment by liudongmiao** [comment]
这个 python 兼容 2.7 与 3.5 的，我也不知道啥情况。
