### ISSUE TITLE
MIUI系统神隐模式冲突

### ISSUE THREAD

**Issue by mzfqy** [liudongmiao/Brevent#151]
开启系统神隐模式可以正常显示已经休眠，不开启显示正在运行，实际应该已经休眠了，开启神隐模式没有勾选的软件也会被休眠

**Comment by idongyou** [comment]
if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer
请带上日志

**Comment by liudongmiao** [comment]
问题是，这是系统的行为，与黑域无关啊。
