### ISSUE TITLE
请问黑域 app standby 生效与否，是否与这条 rom 中的提交有关

### ISSUE THREAD

**Issue by aviraxp** [liudongmiao/Brevent#152]
https://github.com/LineageOS/android_frameworks_base/commit/0326bb5e41219cf502727c3aa44ebf2daa19a5b3

刚刚突然想到这个，没有仔细看源码，但是从直觉上来看，可能有关。

**Comment by simonsmh** [comment]
doze与standby无关
Inference: https://developer.android.com/training/monitoring-device-state/doze-standby.html?hl=zh-cn#understand_doze

**Comment by aviraxp** [comment]
问题是，commit改了AppIdle

**Comment by aviraxp** [comment]
看了一会源码，应该无关。
