### ISSUE TITLE
黑域0.8.1  卸载软件后导致系统无响应

### ISSUE THREAD

**Issue by multiwebview** [liudongmiao/Brevent#157]
手机：三星s7edge
黑域0.8.1版本卸载软件后会导致系统无响应3~10s 然后恢复，但是需要ADB重新运行一遍，测试几次复现概率100%

**Comment by liudongmiao** [comment]
有电脑么？我能上去远程调试么？

发邮件至 br@piebridge.me

**Comment by liudongmiao** [comment]
谢谢，我本地已经重现，下个版本修复
