### ISSUE TITLE
希望能增加一些默认不阻止的应用

### ISSUE THREAD

**Issue by ZeppLu** [liudongmiao/Brevent#16]
这些是我目前觉得有必要默认允许的

| App name  | Package name  | Why  |
|---|---|---|
|  Media Storage | com.android.providers.media  |  required by MTP (vital!) |
|  Clock | com.android.deskclock  |  required by alarms |
|  Download Manager | com.android.providers.downloads  | download files in background  |

**Comment by liudongmiao** [comment]
默认这些都是系统应用吧，你默认应该看不到吧？

而且，这些即使阻止了，也有很大的权限，可以被唤醒。

**Comment by ZeppLu** [comment]
轻度强迫症，喜欢搜索 `-s` 然后全选。。

亲测是不会被唤醒的，在看到酷安上的一条评论前，我一直不知道原来 MTP 失败是因为阻止了 Media Storage，一直在蛋疼地用 adb 传文件。。取消阻止后立马就没事了，闹钟跟下载的问题也是这样，可见 ~~阻止运行~~ 黑域比系统应用更厉害一点。

**Comment by liudongmiao** [comment]
理论上，这些应该和系统同一签名。否则就是 ROM 惹的祸。

默认也没有处理，所以你的这个要求，抱歉，不能处理。

目前加的白名单只以下几个：
- 输入法 与 当前短信应用
- xposed框架
- supersu
- 自己

具体实现可以看这个定义：https://github.com/liudongmiao/Brevent/blob/master/src/me/piebridge/prevent/common/PackageUtils.java#L34

以及这个方法：
https://github.com/liudongmiao/Brevent/blob/master/src/me/piebridge/prevent/common/PackageUtils.java#L125

**Comment by ZeppLu** [comment]
这就有点奇怪了，闹钟和下载管理器的问题我没太注意，但 MTP 的问题，不管用的是摩托原生、cm 还是其它 cm based 的 rom，都会存在。

话说，`IMPORT_PACKAGES` 里面没有 superuser 没问题么，[phh's superuser](https://github.com/phhusson/Superuser) 还是挺多人用的

**Comment by aviraxp** [comment]
phh 阻止了也不影响。

**Comment by ZeppLu** [comment]
哦嚯？能解释一下吗

**Comment by liudongmiao** [comment]
接下来版本，默认看不到绝大部分应用。不处理。
