### ISSUE TITLE
后台应用时间到了，不会立刻处理后台，非得重新进去黑域，才能够杀死后台

### ISSUE THREAD

**Issue by wozuida521** [liudongmiao/Brevent#160]

**Comment by liudongmiao** [comment]
这个是由事件控制的，一般来说，回到桌面过3秒，黑屏立即，打开应用60秒，打开黑域立即。

如果出现进入黑域才执行，请与我联系。

这样设定，是为了更安全，以免误杀与错杀。

**Comment by wozuida521** [comment]
谢谢dalao耐心回答，今天刚刷lineage，没有再出现这种问题了，装了黑域，感觉如有神助，耗电变慢了很多，真心感谢dalao开发了如此之棒的作品。

2017年3月5日星期日，Liu DongMiao <notifications@github.com> 写道：

**Comment by liudongmiao** [comment]
如果喜欢，请随(duo)意(duo)捐赠。尽量通过play商店，支付宝与微信等，无法自动获取捐赠记录。
