### ISSUE TITLE
电脑adb指令cannot listen port

### ISSUE THREAD

**Issue by FoobarRogers** [liudongmiao/Brevent#163]
--- crash start ---
>>> logcat -b crash -t '03-05 14:08:59.000' -d
03-05 14:08:59.599 20153 20153 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-05 14:08:59.599 20153 20153 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-05 14:08:59.599 20153 20153 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-05 14:08:59.599 20153 20153 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-05 14:08:59.599 20153 20153 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-05 14:08:59.599 20153 20153 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-05 14:08:59.599 20153 20153 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-05 14:08:59.599 20153 20153 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-05 14:08:59.599 20153 20153 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:264)
03-05 14:08:59.600 20153 20153 E AndroidRuntime: Error reporting crash
03-05 14:08:59.600 20153 20153 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3063)
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3062)
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:87)
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-05 14:08:59.600 20153 20153 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-05 14:08:59.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
1. 不要 root 模式与普通模式混用

2. 手动删除 `/data/user_de/0/com.android.shell/` 下的其它文件，再试。

**Comment by liudongmiao** [comment]
十天未反馈，关闭
