### ISSUE TITLE
显示电池未优化的系统应用不能黑域化。

### ISSUE THREAD

**Issue by renjie45** [liudongmiao/Brevent#164]
Miui最新开发版，已经root,黑域是0.82版。系统和框架服务不好黑域化。

**Comment by liudongmiao** [comment]
下个版本起，将显示。

你也可以尝鲜下：https://piebridge.me/br-v0.8.2+6.apk

**Comment by sxml** [comment]
创建捷径:QuickShortcutMaker 可以开启 电池未优化隐藏选项 但 重启手机 就恢复
感觉黑域 阻止不了 miui自带应用 唤起无关应用都会后台运行 没有冰箱镇得住

**Comment by liudongmiao** [comment]
@sxml 黑域不事先阻断，只事后处理。
冰箱下，东西对于系统就是不存在的。

你或许可以尝试下阻止运行，这个是事先阻断。
