### ISSUE TITLE
GCM 在加入黑域之后还是无法接受通知 v0.8.3

### ISSUE THREAD

**Issue by XGHeaven** [liudongmiao/Brevent#165]
在更新之后，通过更新日志我发现移除了 开启 gcm 需要贡献的这个限制。 👍 

然后我开启允许 gcm 之后，并将 twitter, telegram,whatsapp 加入到黑域中。在应用关闭之后，发现依旧无法接受通知。

请问这是什么原因？

**Comment by liudongmiao** [comment]
1. 请不要混用其它工具。在开启允许 GCM 之后，如果应用之前已经强行停止，请至少打开一次。如果黑域内显示没有运行，请点击该应用详情，确保出现的强行停止按钮可以点击（但不要点击哈，点击了就收不到了）。
2. 我本人不保证这些应用一定能收到 GCM 消息。你可以下载我的一个测试应用：https://piebridge.me/fcm.apk 打开一次，退出；再打开一次，确认屏幕上有内容。我将会不定时推送消息。你可以酷安私信，或者发邮件让我开始推送。

**Comment by sxml** [comment]
奇怪了 8.3 我没谷歌没框架 不黑域微信 不缩定后台 划掉微信 关屏10几分钟还能收到信息 
升级8.4 亮着屏幕也收不到信息 杀得死死 必须打开微信才可以

**Comment by XGHeaven** [comment]
谢谢作者，我能接受到您的测试应用的通知，也能接收到 telegram 的通知，但是有些应用还是无法通知。如果作者有时间的话可以测试一下 twitter 的 gcm 通知，我按照您的方式测试了好多次都不可以。

**Comment by liudongmiao** [comment]
我只能说，目前这个功能是 work 的。但是，具体是否能真正 work，就看应用是不是真的实现了 GCM 推送。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
