### ISSUE TITLE
* failed to start daemon *

### ISSUE THREAD

**Issue by kyonkoo** [liudongmiao/Brevent#167]
小白一枚，不好意思打扰一下作者
XPERIA X COMPACT 7.1 未root
黑域版本号0.83

adb版本1.0.32
在cmd里执行了以下的命令
adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so
提示
* daemon not running. starting it now on port 5037 *
CreateProcess failure, error 2
* failed to start daemon *
error: cannot connect to daemon

之前0.79版本的时候使用正常，更新到0.83版本以后需要重新执行adb命令的时候就出错了，请问一下有没有什么解决方案...

拜谢

**Comment by liudongmiao** [comment]
这个看起来是电脑相关问题啊。

https://developer.android.google.cn/studio/releases/platform-tools.html

你从这里下载最新的 platform-tools 看下。

**Comment by kyonkoo** [comment]
确实解决了，看来是adb版本的问题，非常感谢
