### ISSUE TITLE
更新 0.8.3 后CMD中执行命令后多出提示信息

### ISSUE THREAD

**Issue by kscvx063** [liudongmiao/Brevent#168]
晚上更新的0.8.3，然后数据线链接手机执行命令，与往日不太一样的是多了一些提示，但是黑域软件主界面是出来了，不太清楚有无影响，粘到这里来，请开发着参考。。

我的手机信息;
Nexus 5X
Android 7.1.1 
Build Number N4F26O

手机已使用 SuperSU Root

下面是CMD中的信息：
C:\Development\Android_SDK>.\adb.exe -d shell /data/app/me.piebridge.brevent-2/lib/arm64/libbootstrap.so
checking...brevent_server started, pid: 29813
checking for stable....quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-05 23:16:52.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-05 23:16:52.000' -d -s BreventLoader BreventServer
03-05 23:16:52.887 29813 29813 I BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
03-05 23:16:52.893 29813 29822 I BreventServer: Brevent Server 0.8.3 started
03-05 23:16:52.920 29813 29822 I BreventServer: brevent user: 0
03-05 23:16:52.922 29813 29822 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-05 23:16:53.006 29813 29822 I BreventServer: loading brevent list
03-05 23:16:53.007 29813 29822 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 35
03-05 23:16:53.007 29813 29822 I BreventServer: loading brevent conf
03-05 23:16:53.009 29813 29822 E BreventServer: Can't load configuration from /data/user_de/0/com.android.shell/me.piebridge.brevent.conf
03-05 23:16:53.009 29813 29822 E BreventServer: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/me.piebridge.brevent.conf (Permission denied)
03-05 23:16:53.009 29813 29822 E BreventServer:         at java.io.FileInputStream.open(Native Method)
03-05 23:16:53.009 29813 29822 E BreventServer:         at java.io.FileInputStream.<init>(FileInputStream.java:146)
03-05 23:16:53.009 29813 29822 E BreventServer:         at java.io.FileReader.<init>(FileReader.java:72)
03-05 23:16:53.009 29813 29822 E BreventServer:         at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:170)
03-05 23:16:53.009 29813 29822 E BreventServer:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:147)
03-05 23:16:53.009 29813 29822 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1079)
03-05 23:16:53.009 29813 29822 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
03-05 23:16:53.009 29813 29822 E BreventServer:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
03-05 23:16:53.009 29813 29822 E BreventServer:         at java.lang.Thread.run(Thread.java:761)
03-05 23:16:53.062 29813 29822 D BreventServer: check and brevent
03-05 23:16:56.180 29813 29822 E BreventServer: Don't receive answer from universe
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
不要混用 root 模式与 adb 模式。

你可以删除 /data/user_de/0/com.android.shell/ 下的文件，然后再执行。
理论上，这个目录 shell 帐号(就是adb之后的帐号)有权限。

**Comment by kscvx063** [comment]
开发者您好：

抱歉这么晚才回复您，
我按照您说的，删除了/data/user_de/0/com.android.shell/ 下的文件，然后打算再执行脚本，但是此时发现黑域软件可以正常的打开，我不太确认需不需要再执行脚本，所以，我把手机重启了一次，系统启动后，使用数据线链接电脑，CMD中输入命令，有了下面的提示，这个应该是有点问题的吧？
此时我发现黑域可以打开，但是配置貌似全丢失了。。

下面是CMD命令行中提示消息，请开发者参考：
C:\Development\Android_SDK>.\adb.exe -d shell /data/app/me.piebridge.brevent-2/lib/arm64/libbootstrap.so
checking...brevent_server started, pid: 11403
checking for stable....quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-06 16:13:40.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-06 16:13:40.000' -d -s BreventLoader BreventServer
03-06 16:13:41.341 11403 11403 I BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
03-06 16:13:41.422 11403 11413 I BreventServer: Brevent Server 0.8.3 started
03-06 16:13:41.436 11403 11413 I BreventServer: brevent user: 0
03-06 16:13:41.438 11403 11413 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-06 16:13:41.505 11403 11413 I BreventServer: loading brevent list
03-06 16:13:41.506 11403 11413 I BreventServer: loading brevent conf
03-06 16:13:41.535 11403 11413 D BreventServer: check and brevent
03-06 16:13:44.667 11403 11413 E BreventServer: Don't receive answer from universe
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

C:\Development\Android_SDK>

**Comment by kscvx063** [comment]
抱歉，再补充一些，
我发现黑域软件是打开的了，但是在黑域里不能设置程序阻止，即选中APP，选择阻止，无效果；
退出黑域再打开又回归到提示需要开启USB调试执行脚本的用户界面。
再次执行脚本后，CMD中仍有上条反馈的提示，黑域又打开了，还是不能设置阻止。

我现在在怀疑是我最开始的时候，删除那些文件的时候不该重启吗？
是不是破坏了什么导致的，还是些别的原因？

**Comment by liudongmiao** [comment]
这个是另一个问题了。

试试这个版本：https://piebridge.me/br-v0.8.3+1-dirty.apk

我将在今晚发布一个 0.8.4 解决这个问题。

**Comment by liudongmiao** [comment]
> 03-06 16:13:44.667 11403 11413 E BreventServer: Don't receive answer from universe

**Comment by kscvx063** [comment]
Very Good！！
安装您给的“br-v0.8.3+1-dirty.apk”就没有问题了，LOG显示OK，然后黑域中也可以设置阻止；
看来这是个已经问题，您已经发现并且解决啦，期待新版本发布，感谢开发者！！

LOG附上吧，看就看，不看也罢：
C:\Development\Android_SDK>.\adb.exe -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so
checking...brevent_server started, pid: 21506
checking for stable...........ok

if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

**Comment by liudongmiao** [comment]
这也是有人带上日志给我，我修改的一个版本。
