### ISSUE TITLE
黑域0.8版本之后出现的问题

### ISSUE THREAD

**Issue by Puzzleliu** [liudongmiao/Brevent#169]
在0.77版本之前可用，但是升级了0.8版本之后不论root模式还是adb模式都无法正常使用。

手机三星s6 ，系统6.0，newux

1、root模式下（已play捐赠），每次back后再进入黑域会重新出现“请启动黑域服务”的启动页，并且应用无法黑域。

2、清理数据重新安装黑域后使用adb模式，cmd会出现报错

c:\adb>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so
checking...brevent_server started, pid: 16109
checking for stable.....quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log belo
w
--- crash start ---
>>> logcat -b crash -t '03-06 14:43:53.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-06 14:43:53.000' -d -s BreventLoader BreventServer
Unable to open log device 'main'
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/
issues with log above

并且使用了酷安@茶_day的博客的方法也无法成功。

**Comment by liudongmiao** [comment]
无法开启日志。请问问你的 ROM 提供者，是不是关闭了日志。

> Unable to open log device 'crash'
> Unable to open log device 'main'

**Comment by Puzzleliu** [comment]
那请问root模式无法使用也是因为这个原因吗？

**Comment by liudongmiao** [comment]
这个异常，将会导致不论 root 模式，还是 adb 模式，都无法使用。

**Comment by Puzzleliu** [comment]
好的，谢谢解答！

**Comment by liudongmiao** [comment]
在 0.8 之前的版本，没有判断日志是否可用，会导致一些其它的问题。
所以，0.8 加入了，必须要收到日志，才认为系统正常工作。

**Comment by Puzzleliu** [comment]
那我只能再重刷其他rom或者暂时放弃黑域了。

**Comment by liudongmiao** [comment]
你去开发者选项中看看。没有日志，是无法处理的。

**Comment by Puzzleliu** [comment]
rom的开发者选项没有开启日志的选项，而且我也不太清楚哪个才是。询问了开发者也还没有回答。我应该需要重刷其他rom试验一下。

**Comment by liudongmiao** [comment]
十天没反馈，关闭
