### ISSUE TITLE
强迫症设置中的「休眠应用」可以阻止 wake lock 吗？

### ISSUE THREAD

**Issue by Nullizer** [liudongmiao/Brevent#17]
据我所知，app standby不处理wake lock唤醒，这个有用吗？

**Comment by liudongmiao** [comment]
只是为了提供一个选项而已，选择权交给用户的。

如果处理了，可能会对应用造成问题，比如从休眠中恢复问题；所以直接不特殊处理。

**Comment by Nullizer** [comment]
那么也就是说「休眠应用」的省电效果是逊于默认的停止运行的？

**Comment by Nullizer** [comment]
我实在是想保留应用的内存上下文，但又不想减弱省电效果。

那么第二个问题：黑域对doze机制有任何增强吗？进入doze后应该可以忽略大部分wake lock吧。

用其它工具增强doze，比如naptime和greenify，会不会与黑域冲突，比如影响5分钟后「强行停止后台程序」等功能的正常发挥？

**Comment by liudongmiao** [comment]
不处理任何 doze 机制。

不知道，没测试过。就我本人，基本只使用停止，启动那点速度，能接受。

**Comment by Nullizer** [comment]
是吗，我倒是觉得不太能接受ˊ_>ˋ

- 有的应用启动有固定时长的splash

- 杀掉进程释放内存对大RAM手机是一种浪费，不符合Android的内存使用机制
