### ISSUE TITLE
锤子M1L，从未见过应用进入休眠

### ISSUE THREAD

**Issue by yckula** [liudongmiao/Brevent#170]
--- crash start ---
>>> logcat -b crash -t '03-06 14:48:03.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-06 14:48:03.000' -d -s BreventLoader BreventServer
03-06 14:48:03.738 12022 12022 I BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
03-06 14:48:03.776 12022 12035 I BreventServer: Brevent Server 0.8.3 started
03-06 14:48:03.782 12022 12035 I BreventServer: brevent user: 0
03-06 14:48:03.783 12022 12035 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-06 14:48:03.836 12022 12035 I BreventServer: loading brevent list
03-06 14:48:03.836 12022 12035 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 52
03-06 14:48:03.837 12022 12035 I BreventServer: loading brevent conf
03-06 14:48:03.853 12022 12035 D BreventServer: check and brevent
03-06 14:48:07.047 12022 12035 E BreventServer: Don't receive answer from universe
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by yckula** [comment]
这个是adb的运行，运行完后能进入黑域，但是应用好像不会进入休眠

**Comment by liudongmiao** [comment]
> E BreventServer: Don't receive answer from universe
试下这个版本吧：https://piebridge.me/br-v0.8.3+1-dirty.apk

**Comment by yckula** [comment]
已经升级为0.8.5，还是未见选中黑域的应用进入休眠，后台划掉应用再进入黑域会发现应用不在正在运行的tab里面了，但还是不会休眠，什么设置都试过了，锤子m1l一定要root才能用么

**Comment by yckula** [comment]
shell@colombo:/ $ logcat -d -b crash
shell@colombo:/ $ logcat -d -s BreventServer BreventLoader
--------- beginning of system
--------- beginning of main
03-13 22:13:35.776  8558  8570 D BreventServer: check and brevent
03-13 22:13:35.832  8558  8570 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-13 22:13:35.849  8558  8571 D BreventServer: received feelgood
03-13 22:13:36.668  8558  8570 D BreventServer: check and brevent
03-13 22:13:36.727  8558  8570 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-13 22:13:39.053  8558  8570 D BreventServer: Can't setStopped for com.android.vending(ignore)
03-13 22:13:39.054  8558  8570 D BreventServer: check and brevent
03-13 22:13:39.098  8558  8570 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-13 22:13:39.103  8558  8570 D BreventServer: Can't setStopped for com.android.vending(ignore)
03-13 22:13:39.303  8558  8570 D BreventServer: Can't setStopped for com.android.vending(ignore)
03-13 22:14:10.734  8558  8570 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-13 22:14:10.763  8558  8570 D BreventServer: check and brevent
03-13 22:14:10.898  8558  8570 D BreventServer: Force stop com.android.providers.downloads(noRecent)
03-13 22:14:10.902  8558  8570 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-13 22:14:20.607  8558  8570 D BreventServer: Can't setStopped for com.android.vending(ignore)
03-13 22:14:20.611  8558  8570 D BreventServer: check and brevent
03-13 22:14:35.508  8558  8570 D BreventServer: check and brevent
03-13 22:14:35.618  8558  8570 D BreventServer: Force stop com.android.email(service)
03-13 22:15:10.382  8558  8570 D BreventServer: check and brevent
03-13 22:15:10.447  8558  8570 I BreventServer: reset home tid to 1402
03-13 22:15:13.178  8558  8570 D BreventServer: check and brevent
03-13 22:15:13.261  8558  8570 D BreventServer: check and brevent
03-13 22:15:13.330  8558  8571 D BreventServer: received feelgood
03-13 22:18:28.598  8558  8570 D BreventServer: check and brevent
03-13 22:18:43.164  8558  8570 D BreventServer: check and brevent
03-13 22:18:43.274  8558  8570 D BreventServer: Force stop com.android.providers.downloads(noRecent)
03-13 22:18:43.291  8558  8570 D BreventServer: Force stop com.iflytek.inputmethod.smartisan(noRecent)
03-13 22:18:46.232  8558  8570 D BreventServer: check and brevent
03-13 22:18:46.301  8558  8571 D BreventServer: received feelgood

**Comment by yckula** [comment]
这个是我刚运行了浏览器后提取的报告

**Comment by yckula** [comment]
刚才升级了0.8.6， 又重新试了下， 设置为动态延后，只强行停止，不休眠。 服务运行良好。下面是日志
shell@colombo:/ $ logcat -d -s BreventServer BreventLoader
--------- beginning of system
--------- beginning of main
03-13 22:37:00.743  8558  1851 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-13 22:37:00.807  8558  1851 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-13 22:37:00.917  8558  1851 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-13 22:37:02.253  8558  1851 D BreventServer: check and brevent
03-13 22:37:02.382  8558  1851 D BreventServer: Force stop com.android.providers.downloads(forceStop)
03-13 22:37:03.726  8558  1851 D BreventServer: Can't setStopped for com.smartisanos.notes(ignore)
03-13 22:37:03.752  8558  1851 D BreventServer: Can't setStopped for com.smartisanos.notes(ignore)
03-13 22:37:05.327  8558  1851 D BreventServer: Can't setStopped for com.coolapk.market(ignore)
03-13 22:37:05.380  8558  1851 D BreventServer: Can't setStopped for com.coolapk.market(ignore)
03-13 22:37:08.824  8558  1851 D BreventServer: check and brevent
03-13 22:37:09.036  8558  1851 D BreventServer: Force stop com.quark.browser(forceStop)
03-13 22:37:09.112  8558  1851 D BreventServer: Force stop com.smartisanos.notes(forceStop)
03-13 22:37:09.307  8558  1851 D BreventServer: Force stop com.coolapk.market(forceStop)

好像成功杀了应用，个人很好奇为什么没办法休眠，希望大神解答

**Comment by liudongmiao** [comment]
休眠需要 ROM 支持。

**Comment by liudongmiao** [comment]
锤子科技并不支持待机，后续版本已经不再显示待机选项。
