### ISSUE TITLE
强迫症选项“只休眠”的问题

### ISSUE THREAD

**Issue by NianSan** [liudongmiao/Brevent#171]
不知道能不能反馈强迫症选项的问题
1、就算开启只休眠设置，从最近任务列表中划掉，就会被强行停止，只有在APP开启了前台服务的情况下才会“只休眠”，比如正在播放的音乐软件
2、还有一种情况，比如支付宝被拉起支付，完成支付后退出会被强行停止而不是休眠

**Comment by liudongmiao** [comment]
是的，请参照下向导第一屏。

这个所有的怎样黑域，都只针对你主动打开的应用。如果被恶意唤醒，是会被杀的。
如果从最近列表划掉，除前台服务外，系统确实会杀掉这些服务。

**Comment by NianSan** [comment]
那增加只休眠这个设置有什么意义呢，不是和“back休眠，划掉强行停止”没多少区别了

**Comment by liudongmiao** [comment]
系统行为，我也没办法啊。

它的意义，本来就不强。只是有些强迫症要，所以我才给。

比如说，系统杀掉了它，我肯定不能唤醒它，让它休眠吧？
比如说，被恶意唤醒，我也不能休眠而不强行停止吧？

**Comment by NianSan** [comment]
明白了，作者如果有需要测试的问题可以来找我，虽然懂的不是很多，但是最近比较有时间，也比较好学
