### ISSUE TITLE
root方式无法开启黑域服务

### ISSUE THREAD

**Issue by OnMyWaiting** [liudongmiao/Brevent#174]
F:\刷机\工具包>adb logcat -b crash -d

03-06 21:18:24.799  3596  3847 E AndroidRuntime: FATAL EXCEPTION: AsyncHandler

03-06 21:18:24.799  3596  3847 E AndroidRuntime: Process: com.android.deskclock, PID: 3596

03-06 21:18:24.799  3596  3847 E AndroidRuntime: android.database.sqlite.SQLiteException: Can't downgrade database from version 11 to 8

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at com.android.deskclock.provider.ClockProvider.query(SourceFile:151)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.content.ContentProvider.query(ContentProvider.java:1020)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.content.ContentProvider$Transport.query(ContentProvider.java:239)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:534)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:475)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at axy.a(SourceFile:228)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at com.android.deskclock.alarms.AlarmStateManager.b(SourceFile:798)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at anl.run(SourceFile:95)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)

03-06 21:18:24.799  3596  3847 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)

03-06 21:18:40.143  4912  4950 E AndroidRuntime: FATAL EXCEPTION: app-indexing

03-06 21:18:40.143  4912  4950 E AndroidRuntime: Process: com.android.deskclock, PID: 4912

03-06 21:18:40.143  4912  4950 E AndroidRuntime: android.database.sqlite.SQLiteException: Can't downgrade database from version 11 to 8

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at com.android.deskclock.provider.ClockProvider.query(SourceFile:151)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.content.ContentProvider.query(ContentProvider.java:1020)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.content.ContentProvider$Transport.query(ContentProvider.java:239)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:534)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:475)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at com.android.deskclock.provider.Alarm.a(SourceFile:225)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at axi.a(SourceFile:1051)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at axl.run(SourceFile:106)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)

03-06 21:18:40.143  4912  4950 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by liudongmiao** [comment]
这里并没有相关日志。请使用命令行，运行 su，再运行黑域提示的指令 (去掉前面的 adb -d shell )

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
