### ISSUE TITLE
三星S7 G9300 7.0 QB8通过ADB方式开启失败

### ISSUE THREAD

**Issue by bigback** [liudongmiao/Brevent#175]
SeLinux为Enforce，已ROOT，安卓7.0。
以下为日志:

checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-07 00:45:20.000' -d
03-07 00:45:20.771 10433 10433 E AndroidRuntime: !@*** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-07 00:45:20.771 10433 10433 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-07 00:45:20.771 10433 10433 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-07 00:45:20.771 10433 10433 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-07 00:45:20.771 10433 10433 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-07 00:45:20.771 10433 10433 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-07 00:45:20.771 10433 10433 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-07 00:45:20.771 10433 10433 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-07 00:45:20.771 10433 10433 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)
03-07 00:45:20.785 10433 10433 E AndroidRuntime: Error reporting crash
03-07 00:45:20.785 10433 10433 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:628)
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:66)
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3460)
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3459)
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:97)
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:130)
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-07 00:45:20.785 10433 10433 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-07 00:45:20.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
没有权限，请不要混用 root 模式与 adb 模式。如有需要，可以直接删除 `/data/user_de/0/com.android.shell/` 下的所有文件，再使用。

**Comment by liudongmiao** [comment]
十天未反馈，且新版应该解决了这个问题，关闭。
