### ISSUE TITLE
无故重启黑域提示

### ISSUE THREAD

**Issue by amdth** [liudongmiao/Brevent#176]
laoda，有时在黑域界面按back键退出，但是按了好几次都显示同一个界面，并没有退出，然后提示让重新启动黑域，不过好的是重启黑域也没有重新执行adb命令
这是使用logcat -b main -d -s BreventLoader BreventServer命令提取的日志
03-07 07:54:29.009  8204 10310 D BreventServer: check and brevent
03-07 07:54:29.165  8204 10311 D BreventServer: received feelgood
03-07 07:54:37.523  8204 10310 D BreventServer: check and brevent
03-07 07:54:46.072  8204 10310 D BreventServer: check and brevent
03-07 07:54:46.238  8204 10311 D BreventServer: received feelgood
03-07 07:54:54.627  8204 10310 D BreventServer: check and brevent
03-07 07:55:09.847  8204 10310 D BreventServer: check and brevent
03-07 07:55:10.009  8204 10311 D BreventServer: received feelgood
03-07 07:55:14.039  8204 10310 D BreventServer: check and brevent
03-07 07:56:06.717  8204 10310 I BreventServer: reset home tid to 5339
03-07 07:56:09.624  8204 10310 D BreventServer: check and brevent
03-07 07:56:09.793  8204 10311 D BreventServer: received feelgood
03-07 07:56:17.557  8204 10310 D BreventServer: check and brevent
03-07 07:56:22.997  8204 10310 D BreventServer: check and brevent
03-07 07:56:23.162  8204 10311 D BreventServer: received feelgood
03-07 07:56:27.202  8204 10310 D BreventServer: check and brevent
03-07 07:56:27.367  8204 10311 D BreventServer: received feelgood
03-07 07:56:50.524  8204 10310 D BreventServer: check and brevent
03-07 07:56:50.725  8204 10311 D BreventServer: received feelgood
03-07 07:56:54.443  8204 10310 D BreventServer: check and brevent
03-07 07:56:57.914  8204 10310 D BreventServer: check and brevent
03-07 07:56:58.077  8204 10311 D BreventServer: received feelgood
03-07 07:57:15.419  8204 10310 D BreventServer: check and brevent
03-07 07:57:40.481  8204 10310 D BreventServer: check and brevent
03-07 07:57:43.242  8204 10310 D BreventServer: check and brevent
03-07 07:57:43.394  8204 10311 D BreventServer: received feelgood
03-07 07:57:49.802  8204 10310 D BreventServer: check and brevent
03-07 07:57:49.934  8204 10310 D BreventServer: Force stop com.coolapk.market(service)
03-07 07:58:27.983  8204 10310 D BreventServer: check and brevent
03-07 07:58:28.144  8204 10311 D BreventServer: received feelgood
03-07 07:58:34.877  8204 10310 D BreventServer: check and brevent
03-07 07:58:35.059  8204 10311 D BreventServer: received feelgood
03-07 07:58:36.095  8204 10310 D BreventServer: check and brevent
03-07 07:58:36.271  8204 10311 D BreventServer: received feelgood
03-07 07:58:37.288  8204 10310 D BreventServer: check and brevent
03-07 07:58:37.464  8204 10311 D BreventServer: received feelgood
03-07 07:58:38.419  8204 10310 D BreventServer: check and brevent
03-07 07:58:38.578  8204 10311 D BreventServer: received feelgood
03-07 07:58:41.633  8204 10310 D BreventServer: check and brevent
03-07 07:59:44.894  8204 10310 I BreventServer: reset home tid to 5339
03-07 07:59:47.905  8204 10310 D BreventServer: check and brevent

**Comment by amdth** [comment]
laoda没回是因为日志错了吗？
现在所有的日志都在这里了
F5121:/ $ logcat -b crash -d
03-05 09:14:53.843 13325 14203 E AndroidRuntime: FATAL EXCEPTION: Thread-144
03-05 09:14:53.843 13325 14203 E AndroidRuntime: Process: com.cici.tiexin, PID: 13325
03-05 09:14:53.843 13325 14203 E AndroidRuntime: java.lang.NegativeArraySizeException: -471
03-05 09:14:53.843 13325 14203 E AndroidRuntime: 	at com.org.wal.libs.network.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:316)
03-05 09:14:53.843 13325 14203 E AndroidRuntime: 	at com.org.wal.libs.network.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:117)
03-05 09:14:53.843 13325 14203 E AndroidRuntime: 	at com.org.wal.libs.network.volley.CacheDispatcher.run(CacheDispatcher.java:101)
03-05 23:18:17.478 24413 27150 E AndroidRuntime: FATAL EXCEPTION: Brevent
03-05 23:18:17.478 24413 27150 E AndroidRuntime: Process: me.piebridge.brevent, PID: 24413
03-05 23:18:17.478 24413 27150 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendEmptyMessage(int)' on a null object reference
03-05 23:18:17.478 24413 27150 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:657)
03-05 23:18:17.478 24413 27150 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:600)
03-05 23:18:17.478 24413 27150 E AndroidRuntime: 	at me.piebridge.brevent.ui.a.handleMessage(AppsActivityHandler.java:58)
03-05 23:18:17.478 24413 27150 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-05 23:18:17.478 24413 27150 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
03-05 23:18:17.478 24413 27150 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-06 23:14:33.113 13443 15941 E AndroidRuntime: FATAL EXCEPTION: Brevent
03-06 23:14:33.113 13443 15941 E AndroidRuntime: Process: me.piebridge.brevent, PID: 13443
03-06 23:14:33.113 13443 15941 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendEmptyMessage(int)' on a null object reference
03-06 23:14:33.113 13443 15941 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:657)
03-06 23:14:33.113 13443 15941 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:600)
03-06 23:14:33.113 13443 15941 E AndroidRuntime: 	at me.piebridge.brevent.ui.a.handleMessage(AppsActivityHandler.java:58)
03-06 23:14:33.113 13443 15941 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-06 23:14:33.113 13443 15941 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
03-06 23:14:33.113 13443 15941 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-07 07:58:38.617  9869 15678 E AndroidRuntime: FATAL EXCEPTION: Brevent
03-07 07:58:38.617  9869 15678 E AndroidRuntime: Process: me.piebridge.brevent, PID: 9869
03-07 07:58:38.617  9869 15678 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendEmptyMessage(int)' on a null object reference
03-07 07:58:38.617  9869 15678 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:657)
03-07 07:58:38.617  9869 15678 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:600)
03-07 07:58:38.617  9869 15678 E AndroidRuntime: 	at me.piebridge.brevent.ui.a.handleMessage(AppsActivityHandler.java:58)
03-07 07:58:38.617  9869 15678 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-07 07:58:38.617  9869 15678 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
03-07 07:58:38.617  9869 15678 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
F5121:/ $  logcat -b main -d -s BreventLoader BreventServer
03-07 13:05:13.654  8204 10310 D BreventServer: check and brevent
03-07 13:05:18.861  8204 10310 D BreventServer: check and brevent
03-07 13:05:46.483  8204 10310 D BreventServer: check and brevent
03-07 13:05:47.496  8204 10310 D BreventServer: check and brevent
03-07 13:05:47.628  8204 10311 D BreventServer: received feelgood
03-07 13:05:54.243  8204 10310 D BreventServer: check and brevent
03-07 13:05:54.389  8204 10311 D BreventServer: received feelgood
03-07 13:06:32.944  8204 10310 D BreventServer: check and brevent
03-07 13:07:33.105  8204 10310 D BreventServer: check and brevent
03-07 13:07:53.669  8204 10310 D BreventServer: check and brevent
03-07 13:08:14.893  8204 10310 D BreventServer: check and brevent
03-07 13:08:17.640  8204 10310 I BreventServer: reset home tid to 5339
03-07 13:08:20.652  8204 10310 D BreventServer: check and brevent
03-07 13:08:22.103  8204 10310 D BreventServer: check and brevent
03-07 13:08:22.242  8204 10311 D BreventServer: received feelgood
03-07 13:08:27.416  8204 10310 D BreventServer: check and brevent
03-07 13:08:43.086  8204 10310 D BreventServer: check and brevent
03-07 13:08:55.939  8204 10310 D BreventServer: check and brevent
03-07 13:08:57.843  8204 10310 D BreventServer: check and brevent
03-07 13:09:58.056  8204 10310 D BreventServer: check and brevent
03-07 13:10:58.271  8204 10310 D BreventServer: check and brevent
03-07 13:11:20.202  8204 10310 D BreventServer: check and brevent
03-07 13:11:31.397  8204 10310 D BreventServer: check and brevent
F5121:/ $

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
