### ISSUE TITLE
我的cm13不支持doze休眠，那么黑域对我的手机还有用处吗

### ISSUE THREAD

**Issue by wozuida521** [liudongmiao/Brevent#177]
lineages不好用，刷回了cm13,发现没有doze这个机制，黑域无法休眠应用。

**Comment by liudongmiao** [comment]
如果可以 root，我建议使用其它软件代替。

如果不能休眠，你可以选择只强行停止，不休眠，能动态强行停止。

**Comment by wozuida521** [comment]
不想用其他的软件了，这个已经很好了，我按照你的方法去设置下，试试效果

**Comment by liudongmiao** [comment]
十天未反馈，关闭
