### ISSUE TITLE
华为EMUI4.0.1不能监听端口 0.8.5

### ISSUE THREAD

**Issue by leyan22** [liudongmiao/Brevent#179]
C:\platform-tools>adb -d shell /data/app/me.piebridge.brevent-2/lib/arm64/libboo
tstrap.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log belo
w
--- crash start ---
>>> logcat -b crash -t '03-07 13:33:14.000' -d
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-07 13:33:14.000' -d -s BreventLoader BreventServer
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/
issues with log above

**Comment by liudongmiao** [comment]
没有权限，获取日志。

黑域高度依赖日志事件，所以，无法处理。

**Comment by leyan22** [comment]
哎，没办法获取日志，那就没办法用了

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
