### ISSUE TITLE
有没有升级的 README，我尝试升级黑域 apk，结果提示我要重启，而且重启后还是这个样子

### ISSUE THREAD

**Issue by XGHeaven** [liudongmiao/Brevent#18]
* 设备：小米5
* 系统：suda cm14.1

我是使用的小米5 suda 版本的 cm14.1，自带了黑域补丁，但是是基于3.1.1版本的。我想升级到3.1.2版本，于是在酷安上下载安装了3.1.2版本的黑域。刚开始提示我需要重启以激活版本，重启后还是这个提示我需要重启。那么具体如何更新黑域呢？

我查看了内部版本，虽然手机上安装的是3.1.2，但是实际在使用的补丁却是3.1.1，如图：
![image](https://cloud.githubusercontent.com/assets/9291212/21071324/da49a58a-bed7-11e6-944e-805525f08321.png)
我猜测是需要重新打补丁，然后尝试按照教程来，结果发现了有如下的问题：
1. 在我的 `/system/framework` 上并没有 `services.jar` 这个文件，相反却有 `service.jar` 这个文件，我就强行用 `service.jar` 代替 `services.jar` 文件
2. 下一步，解包，然后在 patch 的过程中出现了一个 bug。这个其实是 python 的 bug。就是在 macos 10.12 上，调用 `locale.getdefaultlocale()` 后会提示 `ValueError: unknown locale: UTF-8`， [issue](https://bugs.python.org/issue18378)已经提出来过了，而且提出了好几年了。希望作者可以修改一下。我只能强行 `lang='zh-CN' encoding='utf-8'`。
3. 运行 patch，结果告诉我没有任何需要打得补丁。我在想是不是我之前打过了，所以不需要。可是那怎么升级呢？？

**Comment by aviraxp** [comment]
https://github.com/SudaMod/android_frameworks_base/commit/d1130a2cdbca94a89aab4c00afd0b8d8587e981b

请尝试手动将新版apk转移到这个位置。

**Comment by XGHeaven** [comment]
@aviraxp 请问对应的是手机那个位置？是 `/system/app` 下么？
我看他的 commit 是将 prevent 从内部移除了么？

**Comment by aviraxp** [comment]
"/system/app/ForceStop/ForceStop.apk"

**Comment by XGHeaven** [comment]
哦，谢谢

Wang Han <notifications@github.com>于2016年12月10日周六 15:24写道：

**Comment by liudongmiao** [comment]
关于第2个，请给你自己的 console 设定 locale，比如 utf-8.

你可以在终端中选定 UTF-8，然后选中启动时设定；或者直接在 `~/.bash_profile` 中设定。

**Comment by liudongmiao** [comment]
我很好奇，你的 locale 居然不是 utf-8 ...?

**Comment by XGHeaven** [comment]
@liudongmiao 似乎是 python 的 bug
