### ISSUE TITLE
EMUI终于把日志弄出来了

### ISSUE THREAD

**Issue by leyan22** [liudongmiao/Brevent#180]
C:\platform-tools>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libboo
tstrap.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log belo
w
--- crash start ---
>>> logcat -b crash -t '03-07 14:56:18.000' -d
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
03-07 14:56:19.287 10131 10131 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM P
ROCESS: main
03-07 14:56:19.287 10131 10131 E AndroidRuntime: java.io.FileNotFoundException:
/data/user/0/com.android.shell/brevent/libreader.so: open failed: EACCES (Permis
sion denied)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at libcore.io.IoBridge.o
pen(IoBridge.java:459)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at java.io.FileOutputStr
eam.<init>(FileOutputStream.java:87)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at java.io.FileOutputStr
eam.<init>(FileOutputStream.java:72)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at me.piebridge.brevent.
loader.Brevent.a(Brevent.java:95)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at me.piebridge.brevent.
loader.Brevent.main(Brevent.java:123)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit.nativeFinishInit(Native Method)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit.main(RuntimeInit.java:251)
03-07 14:56:19.287 10131 10131 E AndroidRuntime: Caused by: android.system.Errno
Exception: open failed: EACCES (Permission denied)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at libcore.io.Posix.open
(Native Method)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at libcore.io.BlockGuard
Os.open(BlockGuardOs.java:186)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at libcore.io.IoBridge.o
pen(IoBridge.java:445)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        ... 6 more
03-07 14:56:19.287 10131 10131 E AndroidRuntime: Error reporting crash
03-07 14:56:19.287 10131 10131 E AndroidRuntime: java.lang.RuntimeException: Bad
 file descriptor
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at android.os.BinderProx
y.transactNative(Native Method)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at android.os.BinderProx
y.transact(Binder.java:505)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at android.os.ServiceMan
agerProxy.getService(ServiceManagerNative.java:123)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at android.os.ServiceMan
ager.getService(ServiceManager.java:55)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at android.app.ActivityM
anagerNative$1.create(ActivityManagerNative.java:2607)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at android.app.ActivityM
anagerNative$1.create(ActivityManagerNative.java:2605)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at android.util.Singleto
n.get(Singleton.java:34)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at android.app.ActivityM
anagerNative.getDefault(ActivityManagerNative.java:84)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at java.lang.ThreadGroup
.uncaughtException(ThreadGroup.java:693)
03-07 14:56:19.287 10131 10131 E AndroidRuntime:        at java.lang.ThreadGroup
.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-07 14:56:18.000' -d -s BreventLoader BreventServer
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/
issues with log above

**Comment by kenviliang** [comment]
你可以尝试一下，在你的adb shell那里输入：
su -c setenforce 0
su -c /data/app/`pm path me.piebridge.brevent|cut -f 4 -d '/'`/lib/arm/libbootstrap.so
好像能解决问题，只是还要一个问题，设备每次重启后，又失效了

**Comment by kenviliang** [comment]
我也有这个问题

**Comment by liudongmiao** [comment]
1. 你开机自动 setenforce
2. 黑域中，开始”允许root运行“，就可以自动启动了。

**Comment by yEs1do** [comment]
这里:
su -c /data/app/`pm path me.piebridge.brevent|cut -f 4 -d '/'`/lib/arm/libbootstrap.so
pm前面有没有`这个符号？
我在酷安上看到有，不知道该怎么填

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
