### ISSUE TITLE
pixel xl配置suhide后无法监听端口

### ISSUE THREAD

**Issue by memphisyu** [liudongmiao/Brevent#181]
pixel xl使用xda的patch配置完suhide后，在suhide gui里没有勾选brevent，也没有勾选任何uid系统app和框架，只勾选了pokemon go。使用brevent的root模式后，主界面没有任何显示。
使用adb配置，出现如下报错信息。还请帮忙查看一下。
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-07 14:53:46.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-07 14:53:46.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by memphisyu** [comment]
patch是替换了system/system/lib/libandroid_runtiome.so，以及system/system/lib64/libandroid_runtiome.so两个文件。
使用了root switch软件进行root屏蔽，不过开启brevent时，没有开启root switch功能。
另外，我在root switch里强制保持SELINUX为Permissive ，请问是否这个会影响brevent正常运行？
是否需要切换SELINUX到enforcing么？

**Comment by memphisyu** [comment]
找到一个变通的临时解决方法。
将05suhide script文件从 /su/su.d/ 暂时移出，重启.
重启后运行需要获取root授权的app，然后grant root 授权。此时将brevent以root模式运行，可以正常获取app列表，正常运行。
重新将05suhide script文件 移回 /su/su.d目录，chmod 0700后，重启。
重启之后，brevent再以root模式运行，会一直停留在Retrieving processes status,please wait的界面。
从后台关掉brevent重新打开，重新尝试以root模式运行，依然停留在Retrieving processes status,please wait的界面。
以adb模式运行，依然出现上述一开始的报错信息。
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-07 15:47:31.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-07 15:47:31.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above.

这个方式只能治标不治本，还希望能够有一个共存的方式。
初步判断是因为suhide或者SELINUX引起的问题。

**Comment by aviraxp** [comment]
我没记错的话，suhide 重写了 app_process。很不幸，Chainfire 从来不开源他的修改。

05suhide 这个脚本主要就是将重写了的 app_process bind mount 到原来的位置，然后更改 SELinux 上下文。剩下的就不得而知。

**Comment by memphisyu** [comment]
那看起来估计暂时也是无解了。
看来还是直接果断重新刷最新的NOF27B Mar. update好了，其实发现配置完suhide之后用处也不大，光是一个pokemon也没有必要专门牺牲brevent.

**Comment by liudongmiao** [comment]
我不使用 root，暂时也不提供 root 后的任何支持。因为 root 之后，太多东西不可控了。

**Comment by memphisyu** [comment]
确实，鱼和熊掌不能兼得。
