### ISSUE TITLE
0.9 功能

### ISSUE THREAD

**Issue by liudongmiao** [liudongmiao/Brevent#182]
- [x] ~即使黑域vpn，不强行停止已经连接上的vpn~，改用优先通知实现
 可能直接在 0.8 的某个修复版本中引入
- [ ] 界面加入搜索功能，会显示全部，包括当前不显示的应用
- [x] ~支持只休眠不强行停止列表，同时使用这个功能去掉目前的微信硬编码~，改用优先通知实现
- [ ] 界面上，加入底部 icon 点击意义
- [ ] 报告问题带上相关日志

**Comment by amdth** [comment]
laoda，在#176中的问题算是bug吗？
