### ISSUE TITLE
google play最新版无法自动黑域高德地图（至少）

### ISSUE THREAD

**Issue by HaroldYu** [liudongmiao/Brevent#184]
一加一 rr 7.1最新版 adb方式运行黑域
退出高德地图后，通知栏依然显示高德地图正在运行，但打开黑域后，通知消失

**Comment by liudongmiao** [comment]
1. 默认模式下，黑域选用优先休眠，然后强行停止策略

2. 你离开之后，会让它进入休眠，然后再强行停止。一般来说，你从最近列表划掉它，或者过 3 小时没打开，就会处理。(作为对比，系统的最近列表只显示 6 小时内的应用)

3. 这也和何时黑域相关。当你退出某个应用之后，默认是 60s 后处理，回到桌面是 3s，息屏或者打开黑域立即。你可以回到桌面，数1，2，3，应该也能看到通知消失（3秒后开始策略）。

**Comment by HaroldYu** [comment]
谢谢！

**Comment by HaroldYu** [comment]
感谢作者开发这么好的软件

2017年3月8日 09:18于 Liu DongMiao <notifications@github.com>写道：

  1.  默认模式下，黑域选用优先休眠，然后强行停止策略

  2.  你离开之后，会让它进入休眠，然后再强行停止。一般来说，你从最近列表划掉它，或者过 3 小时没打开，就会处理。(作为对比，系统的最近列表只显示 6 小时内的应用)

  3.  这也和何时黑域相关。当你退出某个应用之后，默认是 60s 后处理，回到桌面是 3s，息屏或者打开黑域立即。你可以回到桌面，数1，2，3，应该也能看到通知消失（3秒后开始策略）。

**Comment by liudongmiao** [comment]
我又认真看了下，更像是一个 bug。
从模式与策略来看，确实不应该杀掉高德地图。

**Comment by HaroldYu** [comment]
没懂什么是不应该杀掉高德……能麻烦作者大大解释一下吗…

2017年3月8日 09:52于 Liu DongMiao <notifications@github.com>写道：

我又认真看了下，更像是一个 bug。
从模式与策略来看，确实不应该杀掉高德地图。

**Comment by liudongmiao** [comment]
整个流程是这样子的：

1. 用户打开高德
2. 高德在前台时，启动服务类 (这时标记为服务，可能的恶意唤醒)
3. 退出高德，回到桌面，开始检查。这时，高德没有运行(已经退出了，不会显示时间)，有开启过服务，然后就被杀了。

在高德的这个过程中，并没有出现恶意唤醒。也就是说，它在自己的界面里，打开自己的服务，应该被允许。退出以后，执行休眠而不是强行停止操作。

另外一个类似高德但不同的例子：
1. 打开 UC
2. 用户按 Back 退出 UC，UC自杀式退出 (System.exit之类)
3. 系统重新启动服务，此时界面不是 UC，标记为恶意唤醒
4. 下次清理，杀掉

一个常见的恶意唤醒示例：
1. 打开高德
2. 唤醒支付宝、淘宝 （服务类）
3. 支付宝与淘宝没有打开过，杀掉 (目前是下次清理，接下来会改为30秒)

一个常见的善意唤醒示例：
1. 打开黑域
2. 进入设置，点击 Play 捐赠
3. play捐赠过程中，主动打开了界面，整个过程不会被杀

**Comment by HaroldYu** [comment]
明白了，谢谢大大

2017年3月8日 11:34于 Liu DongMiao <notifications@github.com>写道：

整个流程是这样子的：

  1.  用户打开高德
  2.  高德在前台时，启动服务类 (这时标记为服务，可能的恶意唤醒)
  3.  退出高德，回到桌面，开始检查。这时，高德没有运行(已经退出了，不会显示时间)，有开启过服务，然后就被杀了。

在高德的这个过程中，并没有出现恶意唤醒。也就是说，它在自己的界面里，打开自己的服务，应该被允许。退出以后，执行休眠而不是强行停止操作。

另外一个类似高德但不同的例子：

  1.  打开 UC
  2.  用户按 Back 退出 UC，UC自杀式退出 (System.exit之类)
  3.  系统重新启动服务，此时界面不是 UC，标记为恶意唤醒
  4.  下次清理，杀掉

一个常见的恶意唤醒示例：

  1.  打开高德
  2.  唤醒支付宝、淘宝 （服务类）
  3.  支付宝与淘宝没有打开过，杀掉 (目前是下次清理，接下来会改为30秒)

一个常见的善意唤醒示例：

  1.  打开黑域
  2.  进入设置，点击 Play 捐赠
  3.  play捐赠过程中，主动打开了界面，整个过程不会被杀

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
