### ISSUE TITLE
"是否黑域后台应用" 的疑惑 求解答 谢谢

### ISSUE THREAD

**Issue by is0ra** [liudongmiao/Brevent#185]
"是否黑域后台应用"设置的多久时间(例如5分钟)后执行休眠停止操作似乎只在5分钟后点开黑域app那一刻才起效 黑域app处在前台或者home键后台则貌似后台应用没有被成功休眠停止 是应用实际已被成功休眠的状态没有实时刷新过来 还是后台应用真的没有被干掉 求柳大回复解惑 打扰您了

**Comment by is0ra** [comment]
大概同#184的问题

**Comment by liudongmiao** [comment]
你可以试试。但是，这存在测不准。
1. 目前打开黑域，就会执行一次清理。
2. 自动清理和事件相关，你那几个事件，打开某个应用，回到主屏幕(也是打开某个应用)，某个应用被唤醒，关屏亮屏，都会。你可以使用日志 "logcat -b main -s BreventServer" 查看。目前，每次黑域服务执行（参考怎样黑域）时，都会输出 "check and brevent" 日志

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
