### ISSUE TITLE
关于三星S7 7.0微信无法休眠的问题

### ISSUE THREAD

**Issue by Pason2C** [liudongmiao/Brevent#186]
三星S7/S7 Edge，微信“无法休眠，电池未优化”，原因是微信在deviceidle whitelist，但是在“优化电池用量”中，微信的灰色不可调对象。
通过USB调试执行命令：adb shell dumpsys deviceidle whitelist -com.tencent.mm
“优化电池用量”处，微信变为可调对象。黑域也能正常休眠微信。
但是，在重启后，又无法正常休眠，请问，如何才能将com.tencent.mm从白名单中永久性去除

**Comment by zzzdtz** [comment]
大哥，三星S7 微信在系统电池优化白名单里，得先想办法删掉。。。才能休眠

**Comment by StevenQD** [comment]
咱们的S7E 7.0确实被三星弄的操蛋，强制把微信 QQ等列入doze排除名单

**Comment by zzzdtz** [comment]
只能先不重启了，用楼主的那个命令可以暂时删除微信的名单，下次启动的时候，还会读取那个写死的文件，微信就又不能休眠了

**Comment by StevenQD** [comment]
com.tencent.mm
com.sds.mysinglesquare
com.tencent.mobileqq
com.kakao.talk

**Comment by zzzdtz** [comment]
三星不知道为啥这么干，我HTC的手机，不能优化的只有短信。。。。其他都可以优化

**Comment by liudongmiao** [comment]
很正常。下个版本里，我打算把短信也加入可优化名单，但是需要测试是否能收到短信。
甚至输入法也可以加入，当然，需要获取当前正在使用的输入法。

**Comment by liudongmiao** [comment]
@StevenQD 我不会特意去处理。
我加个那个描述，只是一个提示，它无法休眠。
免得有人疑问，不是说应该休眠的么，为什么不能休眠...?

**Comment by liudongmiao** [comment]
三星其实也是为用户着想。然后他们要一直等用户投诉，怎么微信收不到消息了...?

**Comment by Pason2C** [comment]
目前来看：只能ROOT后修改/data/system/deviceidle.xml来永久修改。
免ROOT只能重启后执行adb shell dumpsys deviceidle whitelist -xxxxxxxx来暂时去除名单。

@ECHO ON
adb devices
adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so
@ECHO OFF
Echo 按任意键继续优化微信及QQ电池使用，不优化请直接关闭窗口。
Pause
adb -d shell dumpsys deviceidle whitelist -com.tencent.mm
adb -d shell dumpsys deviceidle whitelist -com.tencent.mobileqq
Pause
Exit

**Comment by liudongmiao** [comment]
@Pason2C 不建议写死路径，会出问题的。

**Comment by zzzdtz** [comment]
@Pason2C  三星最新的7.0版本，我这边无法连接GCM服务了，以前可以ROOT的HTC，可以修改HOST收到GCM，现在三星休眠了也不行了

**Comment by Pason2C** [comment]
@liudongmiao 可以帮忙修改一下吗？Linux命令不太熟悉
@zzzdtz 不清楚，我使用Shadowsocks可以收到GCM

**Comment by StevenQD** [comment]
@liudongmiao 当初三星一开始并没有把微信 QQ写死的，是可自由开关是否加入doze。后来写死我估计也能理解为什么这么做，但是对于我们这些小众人群肯定不满意的。
目前最糟糕的就是，如果我们曲线用ADB方式去把微信临时性的加入到doze优化里头，是可以黑域休眠掉。
但是另一面来说，没办法使用微信GMC优化了，因为按照您说的设置，微信必须关掉doze优化的。如果是微信是关掉doze优化，那就没办法黑域并休眠，会一直运行。

**Comment by zzzdtz** [comment]
@StevenQD  经测试，大陆区域新增了一个GCM的服务器IP  64.233.187.188  64.233.189.188 66.249.89.104 容易超时，部分地区还是原来的那个188所以正常收信。。。 经测试去除后如果GCM服务连接成功，可以一直收信

**Comment by StevenQD** [comment]
测试只有188可以ping通，其余两个均不可以
正在 Ping 64.233.189.188 具有 32 字节的数据:
来自 64.233.189.188 的回复: 字节=32 时间=74ms TTL=41
来自 64.233.189.188 的回复: 字节=32 时间=74ms TTL=41
来自 64.233.189.188 的回复: 字节=32 时间=72ms TTL=41
来自 64.233.189.188 的回复: 字节=32 时间=75ms TTL=41

**Comment by zzzdtz** [comment]
@StevenQD  你有没有发现三星S7的GCM，在一定时间以后，会自动变成未连接

**Comment by liudongmiao** [comment]
无论在我本机，还是美国的 VPS 上，alt2-mtalk.google.com 都返回 173.194.*.188

http://www.jiankongbao.com/labs/ping?host=alt2-mtalk.google.com

一般来说，谷歌的 dns 解析，最后一们都是一样的。

**Comment by StevenQD** [comment]
@zzzdtz -_-#! 我用不成GCM，所以没用它。我一般都休眠微信，我不需要它时时刻刻的留在后台。

**Comment by liudongmiao** [comment]
@zzzdtz 如果休眠了，还有网络，还叫什么休眠...

**Comment by zzzdtz** [comment]
@StevenQD  我已经换过一块主板了，别ROOT了，高通版的ROOT后地图是反的。。比较坑，不像猎户座那样完美

**Comment by zzzdtz** [comment]
@StevenQD  还是HTC的系统相对符合谷歌的系统设计。

**Comment by Pason2C** [comment]
@liudongmiao GCM所使用的推送服务器可以通过*#*#426#*#*查看，我这边看出64.233.188.188:5228，内地可以Ping通

**Comment by liudongmiao** [comment]
mtalk.google.com 每个地方解析都不太一样的

**Comment by zzzdtz** [comment]
你们有在4G状态下，关屏5分钟，GCM自己断掉的情况吗，而且 network event while disconnected / throttling 05 ,而且不会自己重连，除非连上WIFI 造成网络变动，我记得以前HTC的谷歌服务好像没这种情况，你们有吗，如果没有就是三星的GCM问题了

**Comment by Pason2C** [comment]
@zzzdtz 你好，经测试：在4G状态下使用环聊，关闭8分钟后，使用另一账号发送消息，环聊能正常接收GCM推送的消息。
![日志截图](https://ooo.0o0.ooo/2017/03/09/58c0d090d7f13.png)

**Comment by liudongmiao** [comment]
@Pason2C 不要记 426，记 GCM 就好，也就是 `*#*#GCM#*#*`，GCM 就是 426

**Comment by Pason2C** [comment]
@liudongmiao 原来是这样，谢谢拉。不过三星把这个指令禁用了，要查看得安装PNF Root来曲线调用。
PS：可以帮我更改一下批处理动态检测libbootstrap.so的路径吗？[:纠结:]

**Comment by wt670280793** [comment]
三星S7 7.0太坑了，没法玩了，微信没法优化，没法休眠，没法GCM推送，ADB改了之后好像休眠一段时间会被杀，只能不黑域了微信，太伤心。柳大帮帮这个三星弱机吧
