### ISSUE TITLE
小米4原生安卓7.1黑域启用失败

### ISSUE THREAD

**Issue by shuiniubuchicao** [liudongmiao/Brevent#187]
不会获取日志，所以就截图了，多谢dalao
![image](https://cloud.githubusercontent.com/assets/26263880/23685772/e40a603e-03e0-11e7-844a-c5d387006289.png)

**Comment by zzzdtz** [comment]
你重启后再用命令试试。。。

**Comment by shuiniubuchicao** [comment]
多谢 已成功解决 就是要手机打开黑域的同时再进行调试 。

**Comment by Pason2C** [comment]
日志获取方式：
崩溃日志：adb logcat -d -b crash

黑域服务日志：adb logcat -d -s BreventServer BreventLoader

**Comment by liudongmiao** [comment]
简单点来说，不要使用 root 运行。如果以root运行的话，请去设置中开启”允许 ROOT 运行“。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
