### ISSUE TITLE
Nexus 6p   打开支付宝，会唤醒chrome.

### ISSUE THREAD

**Issue by Bob021** [liudongmiao/Brevent#188]
柳大，打开支付宝，会唤醒chrome.支付宝和chrome 均黑域。但是当支付宝强行退出或者休眠后，chrome不会退出。反复测试，均是这种状况，这是正常状况吗？谢谢！

**Comment by liudongmiao** [comment]
chrome，浏览器作为一个组件，会被很多应用依赖。如果你访问一下日志，就会看到。

> BreventServer: won't block com.android.chrome due do dependency by {com.google.android.googlequicksearchbox, com.zhihu.android, com.eg.android.AlipayGphone}

比如这条日志是说，不会阻止 chrome，因为以下几个应用依赖它：Google 应用, 知乎, 支付宝
一旦强行停止 chrome，其它几个也会被杀掉，这时，估计你要骂我了....

**Comment by Bob021** [comment]
理解了，谢谢柳大解惑。谢谢。

**Comment by kcschan** [comment]
对于搭载GMS的Android 7+而言，Chrome同时承担了WebView的责任。
而上述应用肯定都用到了WebView。

关于WebView：
从Android 6.0开始，WebView从系统的一个部件变为一个单独的Android WebView应用(实际上是Chromium)，这个时候称之为Chromium WebView

从Android 7.0开始，WebView的角色转移到了Chrome。
5x/6p升级到Android 7.0+后，原先的Android WebView会被自动禁用。
