### ISSUE TITLE
可不可以不杀掉状态栏通知，或者至少给一个选项

### ISSUE THREAD

**Issue by Nodlay** [liudongmiao/Brevent#189]
在深夜收到微信 ，outlook但是通知被杀了第二天早上可能会错过一些消息。
其次，有些应用收到通知只有通知声音，连状态栏通知都没有。

**Comment by liudongmiao** [comment]
系统设置中，一旦强行停止，就会清除通知。在阻止运行时代，通过改动系统，从而保留通知。

在下个版本中，将加入”只休眠不强行停止“清单，这些应用被唤醒后，不会强杀，只会休眠，这种情况下，会保留通知。

**Comment by liudongmiao** [comment]
你看这种设定可以么？

**Comment by vikiyi0** [comment]
嗯，我觉得可以的，说实话早上打开手机刚好听到3声通知却没有通知真莫名其妙，还准备抽时间查看耗电记录揪出耗电元凶呢，知道刚才听到hangout特有的提示音却没有hangout的通知😂

**Comment by Nodlay** [comment]
可以，谢谢。
希望不停止耗的电不多。
如果可以做到的话，建议收到了消息的应用只休眠不停止。

**Comment by StevenQD** [comment]
只休眠不强杀清单非常NICE

**Comment by liudongmiao** [comment]
关于消息，我有另外一个想法，个人觉得比这个只休眠不停止要好。
那就是，对于开启了优先通知的应用，只有要通知，不会强行停止。

试想，邮件类应用，如果放到只休眠不强行停止里，不好，因为它就没有退出机制。
所以，如果有消息，在消息未阅读情况下，都不会强杀掉，执行休眠机制。

相反，只休眠不强行停止，其实，主要是给微信这种非标准 GCM 准备的，当然，某些情况下，可能也会用到，但总体来说，用户有限。加入了这个功能，界面操作将会变得复杂：

现在只有不黑域与黑域，如果加了这个，就会有三种，不处理，黑域，黑域(只休眠不强行停止，叫灰域好了)，对于新用户来说，作用有限。

@Nodlay @vikiyi0 @StevenQD 如果你们能想到只休眠不强行停止的场景，请告诉我。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
