### ISSUE TITLE
非root版能不能实现

### ISSUE THREAD

**Issue by LornBin** [liudongmiao/Brevent#19]
liu大，非root版本能不能够在5.0以上使用？

**Comment by zinian** [comment]
本身不需要root啊，但是写系统文件需要root权限或者recovery啊

**Comment by liudongmiao** [comment]
非root非补丁版本还在开发之中，现在极忙，暂停一切开发。

本身不需要 root，6.0下改 bootloader 其实非常容易，目前估计除了 pixel，改 bootloader 都非常容易。

**Comment by liudongmiao** [comment]
非补丁非xposed版本依赖以下几个事情：

- 能否强行停止其它应用
- 能否阻断唤醒 (3.2引入了广播，可以阻断广播唤醒；但是其它唤醒在7.0才引入)
- 能否有权限获取当前正在运行应用列表
- 能否有途径获取当前 activity 状态，是 destroy，还是 pause
- 以上这些途径能否以某种安全的方式，只允许黑域使用

目前有一个版本的实现，通过补丁模式，或者前xposed模式。

**Comment by liudongmiao** [comment]
有可能会支持到 5.0，看情况。但不一定支持。6.0肯定会支持的。
