### ISSUE TITLE
黑域打开提示请重启黑域服务，但是查服务记录感觉是正在运行

### ISSUE THREAD

**Issue by huaxianyan** [liudongmiao/Brevent#190]
1|shell@angler:/ $ logcat -d -s BreventServer BreventLoader
--------- beginning of crash
--------- beginning of system
--------- beginning of main
03-08 12:41:26.405 13519 13551 D BreventServer: received feelgood
03-08 12:41:31.019 13519 13550 D BreventServer: check and brevent
03-08 12:41:31.214 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 12:41:31.216 13519 13550 D BreventServer: Can't setStopped for com.ushaqi.zhuishushenqi(ignore)
03-08 12:41:31.218 13519 13550 D BreventServer: Can't setStopped for com.alibaba.android.rimet(ignore)
03-08 12:43:29.054 13519 13550 D BreventServer: check and brevent
03-08 12:43:29.277 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 12:43:29.279 13519 13550 D BreventServer: Can't setStopped for com.ushaqi.zhuishushenqi(ignore)
03-08 12:43:29.576 13519 13550 D BreventServer: Force stop me.ele(service)
03-08 12:43:29.578 13519 13550 D BreventServer: Can't setStopped for com.alibaba.android.rimet(ignore)

因为ROOT版不稳定，我把之前的卸载了重新安装，使用ADB方法使用

ADB命令都是成功了，第一次成功进入，设置了一些程序。然后重启之后用ADB也成功，但是主界面会一直卡着正在读取进程，然后最后提示请重启服务

**Comment by liudongmiao** [comment]
那就重新启动看一下吧。

此外，开启详细的日志模式：setprop log.tag.BreventServer VERBOSE

**Comment by huaxianyan** [comment]
shell@angler:/ $ logcat -d -s BreventServer BreventLoader
--------- beginning of crash
--------- beginning of system
--------- beginning of main
03-08 13:29:18.060 13519 13550 D BreventServer: check and brevent
03-08 13:29:18.236 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 13:29:18.237 13519 13550 D BreventServer: Can't setStopped for com.droid4you.application.wallet(ignore)
03-08 13:31:23.801 13519 13550 D BreventServer: check and brevent
03-08 13:31:23.977 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 13:31:23.979 13519 13550 D BreventServer: Can't setStopped for com.droid4you.application.wallet(ignore)
03-08 13:33:07.985 13519 13550 D BreventServer: check and brevent
03-08 13:33:08.432 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 13:33:08.436 13519 13550 D BreventServer: Can't setStopped for com.droid4you.application.wallet(ignore)
03-08 13:35:22.279 13519 13550 D BreventServer: check and brevent
03-08 13:35:22.487 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 13:35:22.488 13519 13550 D BreventServer: Can't setStopped for com.droid4you.application.wallet(ignore)
03-08 13:37:08.428 13519 13550 D BreventServer: check and brevent
03-08 13:37:08.612 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 13:37:08.613 13519 13550 D BreventServer: Can't setStopped for com.droid4you.application.wallet(ignore)
03-08 13:38:45.931 13519 13550 D BreventServer: check and brevent
03-08 13:38:46.139 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 13:38:46.141 13519 13550 D BreventServer: Can't setStopped for com.droid4you.application.wallet(ignore)
03-08 13:39:15.699 13519 13550 D BreventServer: check and brevent
03-08 13:39:15.874 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 13:39:15.876 13519 13550 D BreventServer: Can't setStopped for com.droid4you.application.wallet(ignore)
03-08 13:39:23.537 13519 13550 D BreventServer: check and brevent
03-08 13:39:23.728 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 13:39:25.300 13519 13551 V BreventServer: am_proc_start: {component=com.qualcomm.qcrilmsgtunnel/.QcrilMsgTunnelService, pid=8202, uid=1001, type=service, user=0, processName=com.qualcomm.qcrilmsgtunnel}
03-08 13:39:34.130 13519 13551 V BreventServer: am_proc_start: {component=com.qualcomm.cabl/.CABLService, pid=8239, uid=1000, type=service, user=0, processName=com.qualcomm.display}
03-08 13:39:44.105 13519 13551 V BreventServer: am_proc_start: {component=com.dianping.v1/com.huawei.android.pushagent.PushService, pid=8277, uid=10088, type=service, user=0, processName=com.dianping.v1:pushservice}
03-08 13:39:45.156 13519 13551 V BreventServer: am_proc_start: {component=com.dianping.v1/com.dianping.base.push.pushservice.dp.DPPushService, pid=8329, uid=10088, type=service, user=0, processName=com.dianping.v1:dppushservice}
03-08 13:39:54.103 13519 13551 V BreventServer: am_proc_start: {component=com.google.android.apps.translate/.copydrop.CopyDropService, pid=8407, uid=10180, type=service, user=0, processName=com.google.android.apps.translate:copydrop}
03-08 13:39:54.960 13519 13551 V BreventServer: am_proc_start: {component=com.google.android.apps.translate/com.google.android.libraries.translate.core.MultiprocessProfile, pid=8443, uid=10180, type=content provider, user=0, processName=com.google.android.apps.translate}
03-08 13:40:04.127 13519 13551 V BreventServer: am_proc_start: {component=com.nhnent.SKQUEST/com.neezen.atom.AtomService, pid=8809, uid=10161, type=service, user=0, processName=com.nhnent.SKQUEST}
03-08 13:40:14.125 13519 13551 V BreventServer: am_proc_start: {component=cmb.pb/com.feinno.teatalkavsdk.service.KeepExist, pid=8848, uid=10123, type=service, user=0, processName=cmb.pb:CMCoreService}
03-08 13:40:20.205 13519 13551 V BreventServer: am_proc_start: {component=com.alibaba.android.rimet/com.huawei.android.pushagent.PushBootReceiver, pid=8889, uid=10144, type=broadcast, user=0, processName=com.alibaba.android.rimet}
03-08 13:40:23.736 13519 13550 D BreventServer: check and brevent
03-08 13:40:23.742 13519 13550 V BreventServer: get running activities
03-08 13:40:23.778 13519 13550 D BreventServer: running: {me.ele=2781, me.piebridge.brevent=3243}
03-08 13:40:23.778 13519 13550 D BreventServer: top: {}
03-08 13:40:23.778 13519 13550 D BreventServer: home: {com.actionlauncher.playstore}
03-08 13:40:23.778 13519 13550 D BreventServer: current: com.actionlauncher.playstore
03-08 13:40:23.779 13519 13550 D BreventServer: recent: {com.tencent.mobileqqi, com.speedsoftware.rootexplorer, me.ele, com.android.vending, in.zhaoj.shadowsocksr, me.piebridge.brevent, com.actionlauncher.playstore, com.android.settings, com.droid4you.application.wallet}
03-08 13:40:23.779 13519 13550 V BreventServer: get running processes
03-08 13:40:23.878 13519 13550 D BreventServer: inactive for com.tencent.mobileqqi: 0, timeout: 1800
03-08 13:40:23.879 13519 13550 D BreventServer: inactive for me.ele: 1306, timeout: 1800
03-08 13:40:23.879 13519 13550 D BreventServer: inactive for com.alibaba.android.rimet: 0, timeout: 1800
03-08 13:40:23.927 13519 13550 D BreventServer: com.google.android.webview depended by {com.google.android.googlequicksearchbox, me.ele, org.mariotaku.twidere, com.taobao.idlefish, com.alibaba.android.rimet}
03-08 13:40:23.935 13519 13550 D BreventServer: com.google.android.gms depended by {in.zhaoj.shadowsocksr, com.android.chrome}
03-08 13:40:23.936 13519 13550 D BreventServer: back: {}
03-08 13:40:23.936 13519 13550 D BreventServer: service: {}
03-08 13:40:23.936 13519 13550 D BreventServer: blocking: {com.tencent.mobileqqi, com.alibaba.android.rimet}
03-08 13:40:23.936 13519 13550 D BreventServer: noRecent: {com.alibaba.android.rimet}
03-08 13:40:23.936 13519 13550 D BreventServer: unsafe: {}
03-08 13:40:23.936 13519 13550 D BreventServer: final blocking: {com.tencent.mobileqqi, com.alibaba.android.rimet}
03-08 13:40:23.937 13519 13550 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 13:40:23.937 13519 13550 E BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
这个是重启前的，然后我重启了一下，继续运行了一下黑域，并查看了2次日志，如下：
130|shell@angler:/ $ logcat -d -s BreventServer BreventLoader
--------- beginning of system
--------- beginning of crash
--------- beginning of main
03-08 13:44:59.390  7363  7363 I BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
03-08 13:44:59.442  7363  7378 I BreventServer: Brevent Server 0.8.5 started
03-08 13:44:59.468  7363  7378 I BreventServer: brevent user: 0
03-08 13:44:59.470  7363  7378 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-08 13:44:59.549  7363  7378 I BreventServer: loading brevent list
03-08 13:44:59.551  7363  7378 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 11
03-08 13:44:59.551  7363  7378 I BreventServer: loading brevent conf
03-08 13:44:59.571  7363  7378 D BreventServer: check and brevent
03-08 13:45:14.746  7363  7381 D BreventServer: received feelgood
03-08 13:45:18.585  7363  7378 D BreventServer: check and brevent
03-08 13:45:18.811  7363  7378 D BreventServer: Force stop me.ele(service)
03-08 13:45:19.306  7363  7378 D BreventServer: check and brevent
03-08 13:45:34.383  7363  7381 D BreventServer: received feelgood
shell@angler:/ $ setprop log.tag.BreventServer VERBOSE
shell@angler:/ $ logcat -d -s BreventServer BreventLoader
--------- beginning of system
--------- beginning of crash
--------- beginning of main
03-08 13:44:59.390  7363  7363 I BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
03-08 13:44:59.442  7363  7378 I BreventServer: Brevent Server 0.8.5 started
03-08 13:44:59.468  7363  7378 I BreventServer: brevent user: 0
03-08 13:44:59.470  7363  7378 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-08 13:44:59.549  7363  7378 I BreventServer: loading brevent list
03-08 13:44:59.551  7363  7378 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 11
03-08 13:44:59.551  7363  7378 I BreventServer: loading brevent conf
03-08 13:44:59.571  7363  7378 D BreventServer: check and brevent
03-08 13:45:14.746  7363  7381 D BreventServer: received feelgood
03-08 13:45:18.585  7363  7378 D BreventServer: check and brevent
03-08 13:45:18.811  7363  7378 D BreventServer: Force stop me.ele(service)
03-08 13:45:19.306  7363  7378 D BreventServer: check and brevent
03-08 13:45:34.383  7363  7381 D BreventServer: received feelgood
03-08 13:46:08.104  7363  7378 D BreventServer: check and brevent
03-08 13:46:08.289  7363  7378 D BreventServer: Can't setStopped for com.tencent.mobileqqi(ignore)
03-08 13:46:08.391  7363  7378 D BreventServer: Force stop com.alibaba.android.rimet(service)
03-08 13:46:08.603  7363  7378 D BreventServer: Force stop com.eg.android.AlipayGphone(service)
03-08 13:46:14.832  7363  7381 V BreventServer: am_proc_start: {component=com.cmbchina.ccd.pluto.cmbActivity/com.igexin.sdk.PushService, pid=9331, uid=10120, type=service, user=0, processName=com.cmbchina.ccd.pluto.cmbActivity:pushservice}
03-08 13:46:15.215  7363  7381 V BreventServer: am_proc_start: {component=com.quinny898.app.customquicksettings/.receivers.CQSReceiver, pid=9353, uid=10148, type=broadcast, user=0, processName=com.quinny898.app.customquicksettings}
主界面还是显示的是启动黑域服务。我觉得我需要尝试重新安装APP了，但是不能确定问题在哪里。

**Comment by liudongmiao** [comment]
你看看，是不是使用了其它什么工具断了黑域的网络权限...

**Comment by huaxianyan** [comment]
重新安装之后就没问题了…

安装黑域之前已经去掉了所有类似绿守、阻止运行、禁止唤醒之类的工具，类似的工具也没有了

**Comment by huaxianyan** [comment]
好吧，今天重启之后又出现了……感觉好像要继续回去用root版了

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
