### ISSUE TITLE
Root模式 卡在获取进程

### ISSUE THREAD

**Issue by david082321** [liudongmiao/Brevent#191]
三星6.0.1

看了以下的日志，我建立了 /data/user/0/com.samsung.android.voc/brevent 文件夹，给予全部权限，并重新开启黑域，但是仍然一样。

以下是supersu日志：
INTERACTIVE
@/data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so
exit
checking...8brevent_server started, pid: 22337
checking for stable.........quited

fplease report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
/>>> logcat -b crash -t '03-08 14:27:04.000' -d
"Unable to open log device 'crash'
(--- crash end ---
--- brevent start ---
M>>> logcat -b main -t '03-08 14:27:04.000' -d -s BreventLoader BreventServer
x03-08 14:24:59.402 21187 21187 W BreventLoader: Can't make sure directory: /data/user/0/com.samsung.android.voc/brevent
x03-08 14:25:09.142 21375 21375 W BreventLoader: Can't make sure directory: /data/user/0/com.samsung.android.voc/brevent
z--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by david082321** [comment]
原始superSu日志截图
https://s.amsu.ng/3YmrcN91hoBN

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
