### ISSUE TITLE
7.1.2系统运行一成功后，就出现正在读取列表……

### ISSUE THREAD

**Issue by surezheng** [liudongmiao/Brevent#194]
7.1.2系统运行一成功后，就出现正在读取列表……然后就再也没办法运行
软件删除重装后就没办法通过adb启动服务了
黑域0.8.5
angler:/ $ logcat -b crash -d  
03-08 23:30:48.529  9556  9556 F libc    : "/data/user/0/com.kingpoint.gmcchh/files/com.cmcc.aoe.keepalive": error: only position independent executables (PIE) are supported.
03-08 23:30:48.529  9556  9556 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 9556 (com.cmcc.aoe.ke)
03-08 23:30:48.603  9558  9558 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-08 23:30:48.603  9558  9558 F DEBUG   : Build fingerprint: 'google/angler/angler:7.1.2/NPG05F/3729850:user/release-keys'
03-08 23:30:48.603  9558  9558 F DEBUG   : Revision: '0'
03-08 23:30:48.603  9558  9558 F DEBUG   : ABI: 'arm'
03-08 23:30:48.604  9558  9558 F DEBUG   : pid: 9556, tid: 9556, name: com.cmcc.aoe.ke  >>> /data/user/0/com.kingpoint.gmcchh/files/com.cmcc.aoe.keepalive <<<
03-08 23:30:48.604  9558  9558 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
03-08 23:30:48.604  9558  9558 F DEBUG   :     r0 00000000  r1 00002554  r2 00000006  r3 00000008
03-08 23:30:48.604  9558  9558 F DEBUG   :     r4 f42a958c  r5 00000006  r6 f42a9534  r7 0000010c
03-08 23:30:48.604  9558  9558 F DEBUG   :     r8 f4244000  r9 ffc4cd74  sl 00000000  fp f4238010
03-08 23:30:48.604  9558  9558 F DEBUG   :     ip 00000000  sp ffc4ba68  lr f428939f  pc f4289db8  cpsr 20000010
03-08 23:30:48.611  9558  9558 F DEBUG   : 
03-08 23:30:48.611  9558  9558 F DEBUG   : backtrace:
03-08 23:30:48.612  9558  9558 F DEBUG   :     #00 pc 00045db8  /system/bin/linker (__dl_tgkill+12)
03-08 23:30:48.613  9558  9558 F DEBUG   :     #01 pc 0004539b  /system/bin/linker (__dl_pthread_kill+34)
03-08 23:30:48.613  9558  9558 F DEBUG   :     #02 pc 0003d73f  /system/bin/linker (__dl_raise+10)
03-08 23:30:48.613  9558  9558 F DEBUG   :     #03 pc 0003c1fb  /system/bin/linker (__dl___libc_android_abort+34)
03-08 23:30:48.613  9558  9558 F DEBUG   :     #04 pc 0003afd8  /system/bin/linker (__dl_abort+4)
03-08 23:30:48.613  9558  9558 F DEBUG   :     #05 pc 0003d23b  /system/bin/linker (__dl___libc_fatal+22)
03-08 23:30:48.613  9558  9558 F DEBUG   :     #06 pc 00009871  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2416)
03-08 23:30:48.613  9558  9558 F DEBUG   :     #07 pc 00008e6b  /system/bin/linker (__dl___linker_init+358)
03-08 23:30:48.613  9558  9558 F DEBUG   :     #08 pc 00002788  /system/bin/linker (_start+4)
03-08 23:38:50.575 12790 13611 E AndroidRuntime: FATAL EXCEPTION: IntentService[BreventIntentService]
03-08 23:38:50.575 12790 13611 E AndroidRuntime: Process: me.piebridge.brevent, PID: 12790
03-08 23:38:50.575 12790 13611 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
03-08 23:38:50.575 12790 13611 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventIntentService.a(BreventIntentService.java:34)
03-08 23:38:50.575 12790 13611 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventIntentService.onHandleIntent(BreventIntentService.java:23)
03-08 23:38:50.575 12790 13611 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
03-08 23:38:50.575 12790 13611 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-08 23:38:50.575 12790 13611 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-08 23:38:50.575 12790 13611 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by surezheng** [comment]
下行还能正常使用，晚上大概用了两个多小时，突然就不能使用了。上面是用adb查看的日志

**Comment by surezheng** [comment]
初步知道问题所在，昨晚黑域自动升级了，升级后就不能使用，删除升级后的版本，断网安装旧版本，adb启动后关闭自动更新，重新联网，正常

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
