### ISSUE TITLE
root模式开启失败

### ISSUE THREAD

**Issue by Snailluo** [liudongmiao/Brevent#199]
使用终端模拟器调用libbootstrap.so后报错，日志如下

a/app/`pm path me.piebridge.brevent|cut -f 4 -d '/'`/lib/*/libbootstrap.so <
checking...brevent_server started, pid: 3238
checking for stable....quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-10 16:12:49.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-10 16:12:49.000' -d -s BreventLoader BreventServer
03-10 16:12:50.281  3238  3238 I BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
03-10 16:12:50.308  3238  3256 I BreventServer: Brevent Server 0.8.5 started
03-10 16:12:50.312  3238  3256 I BreventServer: brevent user: 0
03-10 16:12:50.313  3238  3256 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-10 16:12:50.356  3238  3256 I BreventServer: loading brevent list
03-10 16:12:50.356  3238  3256 I BreventServer: loading brevent conf
03-10 16:12:50.384  3238  3256 D BreventServer: check and brevent
03-10 16:12:50.661  3238  3257 D BreventServer: received feelgood
03-10 16:12:53.363  3238  3256 E BreventServer: Can't be run as root, please open Brevent
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
1|OnePlus3T:/ $

**Comment by liudongmiao** [comment]
> Can't be run as root, please open Brevent
说得很清楚了吧....从黑域内开启吧。

**Comment by Snailluo** [comment]
哈哈，尴尬，字太多了没看，谢谢哈

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
