### ISSUE TITLE
请问没有root的一加3手机,怎么push services.jar到手机?

### ISSUE THREAD

**Issue by sosmygirl** [liudongmiao/Brevent#2]
1. pull 出来的services.jar 大小205字节 ，看了一下设备里的大小为也为205字节，这有问题吗？
2. 我用第三方工具把 services.odex boot.oat 合成 services.jar，怎么把这个services.jar push回手机啊？
3. 怎么删除设备中的services.odex啊？

  **手机没有root，已解锁bootloader**

**Comment by aviraxp** [comment]
1. 一加做了dexpreopt，请把整个framework目录导出。
2. 现在对你来说比较方便的办法应该是在第三方rec里替换。

**Comment by sosmygirl** [comment]
好像只有这样了，谁有其他的方法请提供一下谢谢。比如把services.jar 压缩成update.zip等等，可以吗

**Comment by aviraxp** [comment]
压成update.zip也得在第三方rec装………………
如果你会编辑boot.img，也可以直接在bootloader刷入

**Comment by sosmygirl** [comment]
谢谢以解决非root安装
