### ISSUE TITLE
黑域偶尔不起作用，带日志

### ISSUE THREAD

**Issue by GyeaDone** [liudongmiao/Brevent#200]
android版本：6.0.1
黑域白名单：微信，搜索lite，网易邮箱，讯飞输入法，Pure天气，clipboard plus
黑域设置：动态延后；  休眠，然后强行停止；  15分钟后黑域后台应用
==================================================
场景
最近应用保留着微信，黑域，然后锁屏，解锁之后进入黑域界面，发现嘀嘀打车，大麦，智联，淘宝（基本都是这几个出现频率比较高，偶尔有其他）等几个应用被唤醒，且位于"正在运行"的子项当中，并伴随着一些推送消息在状态栏。

当我在黑域“正在运行”的列表上看见被唤醒的应用，我切到系统设置里面查看正在运行的服务，并看到了在黑域中被唤醒的应用的确是在运行的，之后我再切回黑域，跟着被唤醒的应用就被黑域掉了。

我自己再明确一下，我的最近应用列表只有微信和黑域是锁着，并且没有任何后台应用，为什么解锁（包括但不限于解锁这个场景，有时候其他场景都会有）后会有其他应用被唤醒？

因为自己比较在意黑域失效这个问题，所以我都会经常打开黑域查看，发现上述的情况一天大概有3-4次，我确认自己没有启动任何应用，他偏偏就被唤醒了，发现被唤醒后，从黑域切换到任何的activity之后再切换回来黑域，被唤醒的应用就被黑域了(这个我试了很多次，发现是这样没错)

我自己也查看了日志，但是感觉日志都是比较正常，没看出什么异常信息，下面的日志是中午发生的一个情况，解锁后突然发现B站推送了一条消息，我立马打开黑玉界面，发现B站正在运行，当时我并没有将B站后台或者休眠，发现被唤醒后，从黑域切换到任何的桌面之后再切换回来黑域，B站就被黑域了，场景基本和我上述的一样，请问一下这是什么问题？

D:\platform-tools>adb shell logcat -b main -d -s BreventLoader BreventServer
03-10 13:38:53.317 29622 29650 D BreventServer: check and brevent
03-10 13:38:53.489 29622 29650 D BreventServer: Force stop com.zhiyong.japanese.word(noRecent)
03-10 13:38:53.577 29622 29650 D BreventServer: Force stop com.sdu.didi.psnger(noRecent)
03-10 13:38:53.624 29622 29650 D BreventServer: Force stop com.zhaopin.social(noRecent)
03-10 13:38:53.749 29622 29650 D BreventServer: Force stop cn.damai(noRecent)
03-10 13:38:53.818 29622 29650 D BreventServer: Force stop com.taobao.taobao(noRecent)
03-10 13:38:53.915 29622 29650 D BreventServer: Force stop com.eg.android.AlipayGphone(noRecent)
03-10 13:38:54.021 29622 29653 D BreventServer: received feelgood
03-10 13:42:15.632 29622 29650 D BreventServer: check and brevent
03-10 13:42:15.783 29622 29650 D BreventServer: Force stop tv.danmaku.bili(noRecent)
03-10 13:42:15.866 29622 29653 D BreventServer: received feelgood

**Comment by liudongmiao** [comment]
之前，服务类唤醒，为了保证正常的唤醒，如支付等，帐号同步等，一律是最长30秒。
但是，一进入黑域，就会全部清理。

在即将发布的 0.8.6 里，引入优先通知概念，对于没有优先通知的，3 秒后杀，有优先通知的，保证一定会运行到 30 秒之后。

你可以尝试这个版本：https://piebridge.me/br-v0.8.5+7.apk

说明一下，黑域采取后杀，所以无法阻止事前唤醒，但是，唤醒后一定会被处理。

**Comment by GyeaDone** [comment]
好的，对于30秒我自己得试验一下，感谢开发者解答。

**Comment by GyeaDone** [comment]
开发者你好，我换了你提供的版本，没有设置优先通知，场景还是跟之前的一样，就在刚才突发了一些情况，就是多个应用同时被唤醒了(并不知道什么原因唤醒的，后台应用只有微信跟taptap)，一堆通知推送过来，差点没被吓死，因为你之前所说的30秒内必定会被黑域掉，于是我就对着手机等了1分多钟，但还是没有被黑域掉，郁闷啊

**Comment by liudongmiao** [comment]
那一连串的 force stop ，没有干掉？

**Comment by GyeaDone** [comment]
当我发现有推送消息后，我并没有进去黑域查看，因为我知道打开界面后被唤醒的应用会被黑域掉，所以我打开了设置，查看当前正在运行的应用和服务，发现了有多个应用被唤醒正在运行当中，就是日志上的那几个，因为开发者你在之前回复的时候说过，黑域是采取后杀的方式，被唤醒后30s内，黑域一定会杀掉被唤醒的应用，所以我在正在运行的应用和服务的界面等了1分多钟，发现并没有杀掉，当然当我进入黑域的时候，被唤醒的应用就被杀掉了，上面那一串的force stop就是进去黑域日志

**Comment by liudongmiao** [comment]
那看看这个版本吧：https://piebridge.me/br-v0.8.5+12.apk

**Comment by GyeaDone** [comment]
还是不可以，被唤醒之后就无法杀掉了，难道是我手机系统不支持吗，另外请问一下开发这能在酷安那里私信你吗，我想带上手机正在运行的服务界面的截图发送给你，和截图时的日志作比较，不知道这样可行不？

**Comment by liudongmiao** [comment]
如果含有私人信息，发邮件。

另外，有一个详细调试模式。

1. `setprop log.tag.BreventServer VERBOSE` 设置日志级别是 verbose
2. 使用上述方法取日志。现在能看到所有事件及调试日志，每一步的过程都有

比如，开启了什么服务，什么时候开始检测，为什么处理之类 。
截图对我来说，基本没啥意义。如果有必要，就约定时间，比如晚上几点啥的，我 teamviewer 远程上去。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
