### ISSUE TITLE
ADB开启失败

### ISSUE THREAD

**Issue by NiGuang1027** [liudongmiao/Brevent#201]
checking...brevent_server started, pid: 27851
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-11 10:44:34.000' -d
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-11 10:44:34.000' -d -s BreventLoader BreventServer
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
03-11 10:44:34.896 27851 27851 I BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
03-11 10:44:34.931 27851 27862 I BreventServer: Brevent Server 0.8.5-12-g6c589c3 started
03-11 10:44:34.965 27851 27862 I BreventServer: brevent user: 0
03-11 10:44:34.969 27851 27862 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-11 10:44:35.122 27851 27862 I BreventServer: loading brevent list
03-11 10:44:35.122 27851 27862 I BreventServer: loading brevent conf
03-11 10:44:35.315 27851 27862 W BreventLoader: Can't run brevent server
03-11 10:44:35.315 27851 27862 W BreventLoader: java.lang.reflect.InvocationTargetException
03-11 10:44:35.315 27851 27862 W BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at java.lang.Thread.run(Thread.java:833)
03-11 10:44:35.315 27851 27862 W BreventLoader: Caused by: java.lang.IllegalArgumentException:  is not a constant in android.text.Layout$Alignment
03-11 10:44:35.315 27851 27862 W BreventLoader:         at java.lang.Enum.valueOf(Enum.java:200)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.text.Layout$Alignment.valueOf(Layout.java:2025)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpan.java:33)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.text.TextUtils$1.createFromParcel(TextUtils.java:711)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.text.TextUtils$1.createFromParcel(TextUtils.java:684)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.readFromParcel(ActivityManager.java:938)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java:963)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java:804)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java:955)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java:953)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.os.Parcel.createTypedArrayList(Parcel.java:1989)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at android.app.ActivityManagerProxy.getRecentTasks(ActivityManagerNative.java:3292)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at me.piebridge.brevent.server.f.a(HideApiOverrideM.java:22)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:571)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:334)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1000)
03-11 10:44:35.315 27851 27862 W BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1150)
03-11 10:44:35.315 27851 27862 W BreventLoader:         ... 3 more
03-11 10:44:35.315 27851 27851 E BreventLoader: Brevent Server quit in 30 seconds, quit
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
