### ISSUE TITLE
音乐类应用不正常暂停

### ISSUE THREAD

**Issue by wangshuy** [liudongmiao/Brevent#202]
网易云和googleplay应用会在摁home或多任务键或返回键离开应用时不正常暂停播放。之前没有这个问题，大概是在安装黑域之后发现的，没对任何应用黑域,root方式。Android m gpe原生系统，htc m8

**Comment by liudongmiao** [comment]
怎么开了，又送了呢？

**Comment by wangshuy** [comment]
因为我发现是我使用的一款动态壁纸的问题造成了这个异常，😂就是最近限免的那个tree of love，那个开发者已经确定了🙈

2017年3月11日 下午1:29，"Liu DongMiao" <notifications@github.com>写道：
