### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by SubDragonzj** [liudongmiao/Brevent#203]
subdragonzj@zx50:~$ adb devices 
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached 
5e985f81	device
subdragonzj@zx50:~$ adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-12 15:13:45.000' -d
03-12 15:13:46.845 16683 16683 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-12 15:13:46.845 16683 16683 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-12 15:13:46.845 16683 16683 E AndroidRuntime: 	at java.io.FileOutputStream.open(Native Method)
03-12 15:13:46.845 16683 16683 E AndroidRuntime: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-12 15:13:46.845 16683 16683 E AndroidRuntime: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-12 15:13:46.845 16683 16683 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-12 15:13:46.845 16683 16683 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-12 15:13:46.845 16683 16683 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-12 15:13:46.845 16683 16683 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: Error reporting crash
03-12 15:13:46.846 16683 16683 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:55)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3049)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3048)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:86)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-12 15:13:46.846 16683 16683 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-12 15:13:45.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
没有权限。请手动删除  `/data/user_de/0/com.android.shell/` 下的文件，然后再尝试。

**Comment by SubDragonzj** [comment]
ok.

**Comment by qllq1993** [comment]
data文件夹下没有user_de/0/com.android.shell/啊

**Comment by SubDragonzj** [comment]
我以root模式运行了0 0

**Comment by qllq1993** [comment]
但是adb模式这个问题解决了吗

**Comment by SubDragonzj** [comment]
没试..

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
