### ISSUE TITLE
没有连接的设备

### ISSUE THREAD

**Issue by luoyeyunyun** [liudongmiao/Brevent#204]
D:\platform-tools>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
error: no devices found

D:\platform-tools>adb devices
List of devices attached

手机的USB调试也开了，1.打开黑域 2.连电脑，3执行这两句命令 不行。交换了顺序也不行
偶尔 显示如下：

D:\platform-tools>adb devices
List of devices attached
adb server version (31) doesn't match this client (36); killing...
* daemon started successfully *

**Comment by luoyeyunyun** [comment]
手机是lg v20港版

**Comment by liudongmiao** [comment]
如果没法找到设备，那基本没有办法。

**Comment by luoyeyunyun** [comment]
是说有些手机不支持么

**Comment by Pason2C** [comment]
@luoyeyunyun @liudongmiao 这个问题应该是adb端口被占用了，导致adb调试工具无法使用该端口所导致了，查看一下是否后台装有各种手机助手，有的话，从任务管理器中结束该进程后再试试

**Comment by luoyeyunyun** [comment]
@Pason2C 这是我开adb之前的

TCP    127.0.0.1:1645         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:1645         127.0.0.1:5701         ESTABLISHED
  TCP    127.0.0.1:5701         127.0.0.1:1645         ESTABLISHED
  TCP    127.0.0.1:8128         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:10650        127.0.0.1:5357         TIME_WAIT
  TCP    127.0.0.1:10651        127.0.0.1:5357         TIME_WAIT
  TCP    127.0.0.1:27015        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:28317        0.0.0.0:0              LISTENING

这是开之后的，感觉应该不是端口问题  电脑上的各种手机助手也都退了
 TCP    127.0.0.1:1584         127.0.0.1:1583         ESTABLISHED
  TCP    127.0.0.1:1645         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:1645         127.0.0.1:5701         ESTABLISHED
  TCP    127.0.0.1:5037         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:5037         127.0.0.1:10392        TIME_WAIT
  TCP    127.0.0.1:5701         127.0.0.1:1645         ESTABLISHED

**Comment by Pason2C** [comment]
ADB和Fastboot for Windows：[platform-tools-latest-windows.zip](https://dl.google.com/android/repository/platform-tools-latest-windows.zip)

    关于如何查看占用端口的进程
    netstat -aon|findstr 5037
    ::查看占用5037端口的进程PID
    tasklist /fi "PID eq 5555"
    ::通过PID查看所属进程，5555为进程PID
    taskkill /pid 5555 /f
    ::终止PID为5555的进程

**Comment by liudongmiao** [comment]
感谢 @Pason2C 学了两招，tasklist 与 taskkill

**Comment by luoyeyunyun** [comment]
@Pason2C   3ks,晚上我再试试。

**Comment by luoyeyunyun** [comment]
@Pason2C  谢谢，还是不行，我已经放弃了。而且我每天都要换电池，做不到每次换完电池都搞一次。

**Comment by Pason2C** [comment]
@luoyeyunyun 很抱歉没有帮到你。

**Comment by luoyeyunyun** [comment]
@Pason2C  还是谢谢，以后root了会再来用的！

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
