### ISSUE TITLE
保持通知并且后台运行/休眠的程序到6小时后仍被强行停止

### ISSUE THREAD

**Issue by ZGNCZMY** [liudongmiao/Brevent#205]
[崩溃日志.txt](https://github.com/liudongmiao/Brevent/files/836852/default.txt)
[服务日志.txt](https://github.com/liudongmiao/Brevent/files/836853/default.txt)

Android7.1.1 oneplus

**Comment by liudongmiao** [comment]
如果没有通知，也会停止的。

**Comment by liudongmiao** [comment]
如果你要一直运行，就只有一个办法，不要加入黑域。

**Comment by liaobin** [comment]
用绿守吧,能保持休眠

**Comment by liudongmiao** [comment]
@ZGNCZMY 我再确认下。总体原则是，没有消息内容(需要你主动进入)，或者没有打开过的，都会强行停止。

应该是这样子的：
1. 有通知 及 在后台运行的，只会休眠不停止。
比如同步或者GCM来了消息，不会停止；比如打开了微信，没有退出，不会停止。

2. 没有通知，或者 不在后台运行的，会过段时间强行停止。
比如同步唤醒了服务，但是没有通知，过段时间就会停止。

@liaobin 你在这，就是污辱我智商。如果绿守当时能支持我的 2.3，也不会有阻止运行啥事；如果普通版的绿守很给力，也不会有黑域啥事。至于它的其它版本，不屑于提供多个功能不一样的模式。

**Comment by liaobin** [comment]
他是针对某个app,需要长期休眠,所以我建议他对这个app用绿守,有什么不对么? @liudongmiao

**Comment by liudongmiao** [comment]
@liaobin 

1. 我说了，黑域没问题
2. 我说了，普通版的绿守做不到

**Comment by liudongmiao** [comment]
@liaobin 确切的说，普通版的绿守根本就没休眠。

一个应用，能够把强行停止叫休眠，然后接着把休眠(app standby)叫浅度休眠，我佩服得无以复加。

**Comment by liaobin** [comment]
嗯,我指的是app standby

**Comment by liudongmiao** [comment]
新版没修复，下个版本才修复。可以在这里下载：https://piebridge.me/br/next/

**Comment by liudongmiao** [comment]
@ZGNCZMY 请帮忙确认下这个问题有没有修复。

同时，请发邮件给我，我好赠送一个特别贡献优惠码给您，可永久使用黑域所有功能（仅限 Play 版）。

**Comment by ZGNCZMY** [comment]
@liudongmiao今晚我试试.手机正在充电

**Comment by ZGNCZMY** [comment]
@liudongmiao 我不知道你的邮箱

**Comment by liudongmiao** [comment]
成功使用之后，点击反馈，你就能看到。

**Comment by liudongmiao** [comment]
新版已经发布，0.8.7 集成了这个功能。
