### ISSUE TITLE
BUG：Android 7.1 OnePlus3T ROOT模式，开启失败

### ISSUE THREAD

**Issue by mapleshadow** [liudongmiao/Brevent#206]
给了ROOT权限，但没有任何反映，用adb shell模式开启成功。

**Comment by liudongmiao** [comment]
你得给 ROOT 模式的日志。
据部分网友反馈，禁用 selinux 就可以使用。

我目前无法复现，模拟器，备机的 lineage，ROOT 都没有问题。

**Comment by mapleshadow** [comment]
谢谢回复。首先，应用很棒！！！顶了！
照你这么说，不用看日志了，我估计就是selinux的问题了。。。如果说禁用的模式来实现ROOT启用，我认为并不是一个好的可取方式。如果实在没有别的方法解决，我出个主意：
请参考以及搜索一下Magisk，当前版本是11.1支持android 7.1，这货是个神器！！！可以搞定一切不能搞定的深层系统问题，特别是系统级API，最大的优势就是ROOT和BOOT解锁即可。。。。

**Comment by liudongmiao** [comment]
我不用 ROOT，也不解锁，这就是 黑域 的优势。
而我，也不愿意开发多个功能不一的模式。

ROOT 只是能实现开机自启，能自启就自启，不能就手动，不影响所有功能。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
