### ISSUE TITLE
cannot listen port

### ISSUE THREAD

**Issue by Freedomzasf** [liudongmiao/Brevent#207]
C:\Users\freedomzas>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-13 19:04:42.000' -d
03-13 19:04:43.141 22365 22365 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-13 19:04:43.141 22365 22365 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
03-13 19:04:43.141 22365 22365 E AndroidRuntime: Error reporting crash
03-13 19:04:43.141 22365 22365 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3033)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3032)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:92)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-13 19:04:43.141 22365 22365 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-13 19:04:42.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by Freedomzasf** [comment]
我看过了com.android.shell里面，是没有文件的

**Comment by Freedomzasf** [comment]
我看过了类似的报告，但是com.android.shell里面是没有文件的

**Comment by liudongmiao** [comment]
> java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)

你看下，是否有权限。

你可以先输入 `adb -d shell id -Z`，给下这个的结果。

**Comment by Freedomzasf** [comment]
C:\Users\freedomzas>adb -d shell id -Z
context=u:r:shell:s0

**Comment by Freedomzasf** [comment]
C:\Users\freedomzas>adb -d shell id -Z
context=u:r:shell:s0

**Comment by liudongmiao** [comment]
没有理由没有权限啊。我需要更多信息。谢谢。

1. 电脑执行 `adb -d shell`，进入手机
2. 运行 `id`，给我结果
3. 运行 `ls -l /data/user_de/0/com.android.shell/`，给我结果

**Comment by Freedomzasf** [comment]
C:\Users\freedomzas>adb -d shell
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
idE6553:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1026(drmrpc),1028(sdcard_r),2993(trimarea),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc) context=u:r:shell:s0
E6553:/ $ ls -l /data/user_de/0/com.android.shell/
total 32
drwx------ 2 root root 4096 2017-03-06 15:07 brevent
drwx------ 2 root root 4096 2017-03-13 19:15 cache
-rw------- 1 root root  203 2017-03-13 19:15 me.piebridge.brevent.conf
-rw------- 1 root root  374 2017-03-13 10:05 me.piebridge.brevent.list

**Comment by liudongmiao** [comment]
看到了没，你使用 root 模式运行过。

切换到 root，删除里面的文件，然后再 adb 吧。
或者使用 root 模式，但是，root 模式可能要禁用 selinux。

你可以清空黑域数据，再进入，认真阅读第二屏。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
