### ISSUE TITLE
讨论 SELinux 问题

### ISSUE THREAD

**Issue by aviraxp** [liudongmiao/Brevent#208]
这样方便一些。

写了两个 sepolicy 之后，原来的 denial 没了，又在这里扔出异常：

https://github.com/liudongmiao/Brevent/blob/0.7/loader/src/main/java/me/piebridge/brevent/loader/Brevent.java#L86

同时查看，无法在相应文件夹成功复制文件。尝试更改文件夹权限和 SELinux 上下文，不成功。同时不知道是我这个 rom 还是什么问题，审计日志记录的信息很少。

还有什么可以尝试的吗？

**Comment by liudongmiao** [comment]
什么  ROM ？

这个文件的话，倒不是必须的。下个版本，我使用其它的机制来加载，就不用复制文件了。
但是，估计你不能复制文件的话，能在这个目录写文件么？

**Comment by liudongmiao** [comment]
你是一加几？我考虑入下这个设备了，从后来看，确实一加的设备也比较多。

**Comment by aviraxp** [comment]
一加2官方6.0，你要是买的话，建议你买新的3或者3T。

我手动改权限是可以自己创建文件的，我是说黑域不能创建文件。你可以尝试调用 root 权限来复制。

**Comment by liudongmiao** [comment]
你直接借给我用用呗，就测试几天，好了再还你....

如果要使用 root，涉及到创建进程，开销会大得多。

**Comment by aviraxp** [comment]
不是我不想借，我就这一台手机，最近实习还要用的。。。

**Comment by liudongmiao** [comment]
居然只有一台机器...还这么折腾....

**Comment by bigbighill** [comment]
柳大能否写个针对黑域的SELinux规则。
不太想 setenforce 0。

**Comment by liudongmiao** [comment]
目前和 @aviraxp 联调之后，发现并不真正属于 selinux 问题。
他的版本已经修复，体现在 v0.8.7+10 中，你可以从这里下载：https://piebridge.me/br/next/

**Comment by bigbighill** [comment]
解决了,setenforce 1后可以获取到进程列表了，
我是 小米5splus Android 6.0.1 miui8.2
miui的神隐模式是否和这款软件差不多，神隐模式有4种控制方法，1、miui智能省电 2、无限制 3、限制后台功能 4、禁止后台运行 ，在黑域中黑域微信，微信必须在神隐模式中设置为第三种才有效。
而且有些软件神隐模式设置为4 后，一后台就杀掉也不会自启。 黑域是否和神隐模式有功能重合的地方？或者说是相互配合才行？
从酷安下载的版s本用选 google play 捐赠后，如果下次从 直接从google play下载能否识别已捐赠？

**Comment by liudongmiao** [comment]
1. miui 问题无法解答

2. 只要没有通过其它渠道阻断 play 商店或者破解，都能有效识别

**Comment by bigbighill** [comment]
我是root模式下使用的，重启黑域无法自动启动，必须手动。

**Comment by aviraxp** [comment]
我这里用测试版是可以自启的

**Comment by bigbighill** [comment]
清空数据，删除 com.android.shell中的数据，配置好了，重新启动系统，黑域还是不能自启，且手动启动后还提示要启动黑域服务
