### ISSUE TITLE
服气了

### ISSUE THREAD

**Issue by chm512512** [liudongmiao/Brevent#209]
卸载不会删掉shell文件夹，用过root之后，即使取消，以后还是会永远继续使用root模式。并且卸载重装依然使用root模式开启。个人感觉不如不要算了。
http://img02.sogoucdn.com/app/a/100520146/7431de1f4a19c097df10e4cd4d367afe
http://img03.sogoucdn.com/app/a/100520146/8354e8f9f74f8d2ea46c474825438190
http://img01.sogoucdn.com/app/a/100520146/43ad356b1cd5a89bdf74cbfd7de7c23a
http://img04.sogoucdn.com/app/a/100520146/b8bfaed31705cc3c1a0b3453efccbe5a

**Comment by chm512512** [comment]
重装了系统，新版目前可用。

**Comment by liudongmiao** [comment]
不建议使用 root 模式。root 可能要禁用 selinux，我还没找到好的方法保证可用。

就我自己的话，虚拟机( 不支持selinux)与lineage(selinux为enforce)都可以。
