### ISSUE TITLE
应用停止之后,任务列表还显示应用缓存

### ISSUE THREAD

**Issue by hhuimie** [liudongmiao/Brevent#21]
魅族mx3,flyme 5.1.9.0A
以前用阻止运行的时候,应用停止的同时,任务列表就没这个应用了.
现在还有,不知道是不是bug

**Comment by aviraxp** [comment]
这个功能被去掉了。

**Comment by liudongmiao** [comment]
这个功能是 阻止运行 2.3 引入的。

但是，黑域基于 阻止运行 2.2，以及针对改动日志修复 bug，所以并没有引进这个功能。

**Comment by hhuimie** [comment]
那有没有计划加入呢

**Comment by hhuimie** [comment]
@liudongmiao 还有个小问题.我用阻止运行2.3.2时,修改force_stop_timeout无效~~然后才迫不得已打了补丁用黑域...

**Comment by liudongmiao** [comment]
暂时没有计划加入，重心将放在 adb 版，不再需要打补丁，也不需要 Xposed.

手动改，需要重启，请通过管理界面改。

我本人不维护，也没有权限维护阻止运行。
