### ISSUE TITLE
一加3T 7.0系统 直接就command not found了……

### ISSUE THREAD

**Issue by rogersung** [liudongmiao/Brevent#210]
一切没问题，然后连接电脑之后提示libbootstrap.so through adb shell，我也照做了，但是就是不行……刚开始以为是win的问题，然后mac下面也试了一下，发现也是一样

**Comment by chm512512** [comment]
字里行间看出有钱

**Comment by rogersung** [comment]
@chm512512 不是啊，用一加的当然没钱了，而且我的只是2014early的MBA而已T T

**Comment by liudongmiao** [comment]
提示语啥？

**Comment by rogersung** [comment]
@liudongmiao 我吧log做成zip
[logs-v0.4.zip](https://github.com/liudongmiao/Brevent/files/841319/logs-v0.4.zip)
了，我把附件发过来您看一下

**Comment by liudongmiao** [comment]
你这个日志就是空的

**Comment by rogersung** [comment]
好惆怅。。。我也没打开看TAT，就直接发过来了，主要是下了adb，然后执行命令（adb shell下）居然no command

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
