### ISSUE TITLE
一加3t7.1.1打开卡

### ISSUE THREAD

**Issue by lebronbian** [liudongmiao/Brevent#211]
一加3t，7.1.1当按返回键退出黑域时，再次打开黑域会有卡顿的现象,动画很卡，而按home键退出时再次开启黑域则没有卡顿，同样是7.1.1的小米4则没有卡顿。

**Comment by liudongmiao** [comment]
呃，呃，呃。无法理解一加的系统。

**Comment by lebronbian** [comment]
谢谢回复，一加系统感觉就像一个残废，不过希望作者修复是最好的。动画看着实在不爽

**Comment by TakcC** [comment]
3T，7.1.1的氢并没有遇到这个问题呢。

**Comment by TakcC** [comment]
不过看其他issue，好像一加系统的问题真不少。。。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
