### ISSUE TITLE
一加3，氢，7.1.1，崩溃了。。

### ISSUE THREAD

**Issue by breezewang-0101** [liudongmiao/Brevent#212]
--- crash start ---
>>> logcat -b crash -t '03-14 01:19:52.000' -d
03-14 01:19:53.285 12046 12046 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-14 01:19:53.285 12046 12046 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-14 01:19:53.285 12046 12046 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-14 01:19:53.285 12046 12046 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-14 01:19:53.285 12046 12046 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-14 01:19:53.285 12046 12046 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-14 01:19:53.285 12046 12046 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-14 01:19:53.285 12046 12046 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-14 01:19:53.285 12046 12046 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java)
03-14 01:19:53.286 12046 12046 E AndroidRuntime: Error reporting crash
03-14 01:19:53.286 12046 12046 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java)
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java)
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java)
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java)
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java)
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java)
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java)
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java)
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-14 01:19:53.286 12046 12046 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-14 01:19:52.000' -d -s BreventLoader BreventServer
--- brevent end ---

**Comment by liudongmiao** [comment]
> java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)

无法理解一加的系统。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
