### ISSUE TITLE
黑域0.86是否因为更改了文件地址导致更新后黑域失败？

### ISSUE THREAD

**Issue by editevy** [liudongmiao/Brevent#213]
1、更新0.86后跟之前更新一个版本一样，更新完淘宝能唤醒美团 支付宝，而且划掉淘宝还在后台。重启，重新输入adb解决
2、是否adb输入的那个地址由-1变-2导致上述问题呢
3、是否最近的版本划掉后要6-10秒才能在黑域里面看到app被处理？划掉淘宝立刻进去，淘宝停止几时，等一会再进黑域才看到淘宝干掉

**Comment by liudongmiao** [comment]
1. 估计没有正确识别日志更新？

2. 理论上不可能，这个只是一个入口，启动后不受限

3. 之前版本在你进入黑域时，执行一次清理。现在的版本，完全依赖事件。进入黑域不处理。
总的来说，类似这样：
1). 划掉
2). 回到桌面，3 秒后执行清理过程
3). 进入黑域，发现没有，退出回到桌面，如果之前的没有执行，取消，过 3 秒后再执行
4). 如果你真的不断来回。。。会导致一直不清理
你要测试的话，回到桌面，数1，2，3，再进入黑域看看。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
