### ISSUE TITLE
一加3T， RR unofficial 11\03版本， 错误日志

### ISSUE THREAD

**Issue by evanxyj** [liudongmiao/Brevent#214]
>>> logcat -b crash -t '03-14 09:45:14.000' -d
03-14 09:45:14.348 15567 15567 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-14 09:45:14.348 15567 15567 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:264)
03-14 09:45:14.348 15567 15567 E AndroidRuntime: Error reporting crash
03-14 09:45:14.348 15567 15567 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3063)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3062)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:87)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-14 09:45:14.348 15567 15567 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-14 09:45:14.000' -d -s BreventLoader BreventServer
--- brevent end ---

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
