### ISSUE TITLE
S7edge 使用黑域几天后发现 按多任务 home按键会有1～2秒延迟

### ISSUE THREAD

**Issue by Neillll** [liudongmiao/Brevent#215]
机型港版S7edge 原版系统6.0.1 未root。 刚用黑域一开始还很正常，用越久逐渐的按多任务和home键延迟就会越来越长，现在点击后要等1～2秒才会有反应。 以前不会有这种情况。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
