### ISSUE TITLE
gcm not working

### ISSUE THREAD

**Issue by chotchot** [liudongmiao/Brevent#216]
allow gcm not working

**Comment by Pason2C** [comment]
Hi, This feature requires a donation of at least two dollars before it can be used.

**Comment by chotchot** [comment]
already donate it, but still not working

**Comment by chm512512** [comment]
where ary you from?(⁎⚈᷀᷁ᴗ⚈᷀᷁⁎)

**Comment by Pason2C** [comment]
@chotchot You need to set the notification of the application to "priority"

**Comment by liudongmiao** [comment]
@chotchot 

1. please turn on "keep notifications" and "allow GCM"
2. please set priority for apps, you can click, choose "Notifications", then select "Override Do Not Disturb" or similar options.
3. And, some apps claims to support GCM, but not actually GCM.

@Pason2C Thanks. But please don't use Chinese screenshots for English users.

**Comment by Pason2C** [comment]
@liudongmiao Sorry, has been updated

**Comment by chotchot** [comment]
@liudongmiao it maybe just me, wechat gcm not working for me, but i can confirm whatsapp working fine with gcm allow

**Comment by liudongmiao** [comment]
@chotchot Wechat don't work well with GCM.

You may try like this:

1. open Wechat
2. press Back or Home, which will put Wechat into background
3. never, never, force-stop Wechat, nor clear it from Recent tasks.
Current v0.8.6, will force-stop Wechat after 3 hours, it will be fixed in next version.
You can get it here: piebridge.me/br/next/

**Comment by chotchot** [comment]
ohh now i get it soo it will not working under brevent mode,

**Comment by liudongmiao** [comment]
@chotchot For wechat, please try the next version, and open it, then don't swipe it from recent list.

**Comment by chotchot** [comment]
already try your method install next brevent apk, butt wechat still no good
only whatsapp work properly

**Comment by liudongmiao** [comment]
I cannot promise wechat will work, but at least it may work.

because, wechat just don't support GCM.

**Comment by chotchot** [comment]
at least whatsapp still suport gcm,it still can save my batery rather two
messangin app hongingnt my battery btw keep your hardwork,loving your app,:)
