### ISSUE TITLE
cannot listen port 

### ISSUE THREAD

**Issue by hingbong** [liudongmiao/Brevent#217]
PS C:\Users\Hingbong> adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so
>>
checking...brevent_server started, pid: 31963
checking for stable....quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-14 11:27:16.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-14 11:27:16.000' -d -s BreventLoader BreventServer
03-14 11:27:16.829 31963 31963 I BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/
com.android.shell/brevent/libloader.so
03-14 11:27:16.851 31963 31972 I BreventServer: Brevent Server 0.8.6 started
03-14 11:27:16.857 31963 31972 I BreventServer: brevent user: 0
03-14 11:27:16.859 31963 31972 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-14 11:27:16.915 31963 31972 I BreventServer: loading brevent list
03-14 11:27:16.916 31963 31972 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size:
9
03-14 11:27:16.916 31963 31972 I BreventServer: loading brevent conf
03-14 11:27:17.101 31963 31972 D BreventServer: sent first status
03-14 11:27:17.101 31963 31973 D BreventServer: received feelgood
03-14 11:27:20.020 31963 31972 E BreventServer: Can't be run as root, please open Brevent
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by Pason2C** [comment]
BreventServer: Can't be run as root, please open Brevent
Root模式吗？建议使用非ROOT开启

**Comment by chm512512** [comment]
😂是不是用了root 发现一直获取进程然后又想试试adb发现没用。恭喜你，GG了

**Comment by liudongmiao** [comment]
@chm512512 目前不支持第三方脚本以 ROOT 方式开启。

为什么不支持？

1. 不安全，我不允许任何未经授权的 ROOT
2. 某种意义上讲，这是一个付费功能，必须要付费才能开启

如何正确使用 ROOT 方式开启？

1. 启动界面，点击 7 次返回，然后选择“以ROOT开启”
2. 如果是Play版，请进设置，累计捐赠3刀，开启“以ROOT开启”；非Play版，不用管，但是建议捐赠。

**Comment by liudongmiao** [comment]
@Pason2C 请发个邮件给我，我给个特别贡献的优惠码，谢谢。
