### ISSUE TITLE
 report bug

### ISSUE THREAD

**Issue by miaojie78559028** [liudongmiao/Brevent#218]
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log belo
w
--- crash start ---
>>> logcat -b crash -t '03-14 11:35:27.000' -d
03-14 11:35:27.593  7590  7590 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM P
ROCESS: main
03-14 11:35:27.593  7590  7590 E AndroidRuntime: java.io.FileNotFoundException:
/data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-14 11:35:27.593  7590  7590 E AndroidRuntime:        at java.io.FileOutputStr
eam.open(Native Method)
03-14 11:35:27.593  7590  7590 E AndroidRuntime:        at java.io.FileOutputStr
eam.<init>(FileOutputStream.java:221)
03-14 11:35:27.593  7590  7590 E AndroidRuntime:        at java.io.FileOutputStr
eam.<init>(FileOutputStream.java:169)
03-14 11:35:27.593  7590  7590 E AndroidRuntime:        at me.piebridge.brevent.
loader.Brevent.a(Brevent.java:95)
03-14 11:35:27.593  7590  7590 E AndroidRuntime:        at me.piebridge.brevent.
loader.Brevent.main(Brevent.java:123)
03-14 11:35:27.593  7590  7590 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit.nativeFinishInit(Native Method)
03-14 11:35:27.593  7590  7590 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit.main(RuntimeInit.java:276)
03-14 11:35:27.594  7590  7590 E AndroidRuntime: Error reporting crash
03-14 11:35:27.594  7590  7590 E AndroidRuntime: java.lang.RuntimeException: Bad
 file descriptor
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at android.os.BinderProx
y.transactNative(Native Method)
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at android.os.BinderProx
y.transact(Binder.java:651)
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at android.os.ServiceMan
agerProxy.getService(ServiceManagerNative.java:123)
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at android.os.ServiceMan
ager.getService(ServiceManager.java:55)
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at android.app.ActivityM
anagerNative$1.create(ActivityManagerNative.java:3208)
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at android.app.ActivityM
anagerNative$1.create(ActivityManagerNative.java:3207)
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at android.util.Singleto
n.get(Singleton.java:34)
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at android.app.ActivityM
anagerNative.getDefault(ActivityManagerNative.java:90)
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:111)
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at java.lang.ThreadGroup
.uncaughtException(ThreadGroup.java:1068)
03-14 11:35:27.594  7590  7590 E AndroidRuntime:        at java.lang.ThreadGroup
.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-14 11:35:27.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/
issues with log above

**Comment by Pason2C** [comment]
look at here : https://github.com/liudongmiao/Brevent/issues/175

**Comment by miaojie78559028** [comment]
可是更新0.8.6后没有root模式开启黑域了

**Comment by Pason2C** [comment]
@miaojie78559028 点击 **后退键** 7次开启root模式。如果不需要ROOT模式，删除`data/user_de/0/com.android.shell/`下的文件

**Comment by miaojie78559028** [comment]
ok，非常感谢
