### ISSUE TITLE
和通讯录无法黑域

### ISSUE THREAD

**Issue by windong** [liudongmiao/Brevent#219]
选中和通讯录后，点击黑域那个按钮没反应，后面还是没有任何图标

**Comment by Pason2C** [comment]
最好带上日志哈，不然开发者无法处理。
    崩溃日志：logcat -d -b crash
    黑域服务日志：logcat -d -s BreventServer BreventLoader

**Comment by windong** [comment]
没描述清楚，更新一下描述

**Comment by Pason2C** [comment]
@windong 你好，如图：在后台5分钟后和通讯录可以正常休眠。后台时间可以黑域设置中“是否黑域后台应用”中设置，如果未休眠，可以检查此处是否设置为“永不”。[如果是从最近任务列表“划掉”或“Back”退出应用，则会强制停止应用]
![2.jpg](https://ooo.0o0.ooo/2017/03/14/58c78261bb7c4.jpg)
![3.jpg](https://ooo.0o0.ooo/2017/03/14/58c782613a5a0.jpg)
如果以上操作还未解决你的问题，建议上传黑域的服务日志，等待开发者回答。

**Comment by windong** [comment]
OnePlus2:/ $ logcat -d -s BreventServer BreventLoader
--------- beginning of main
OnePlus2:/ $
呃，为什么只有这些

**Comment by liudongmiao** [comment]
应该已经在最新的测试版中修复。

https://piebridge.me/br/next/
