### ISSUE TITLE
三星s7edge，系统更新7.0，已odex化，个人打补丁失败

### ISSUE THREAD

**Issue by honggegeda** [liudongmiao/Brevent#22]
services.jar文件已经上传http://pan.baidu.com/share/link?shareid=3311273600&uk=3745298705

**Comment by aviraxp** [comment]
参照https://github.com/liudongmiao/Brevent/pull/10

**Comment by honggegeda** [comment]
@aviraxp。  可以说完全看不懂吗，只会用一键生成工具，其他的都不会，完全不知道里面说的啥🤕🤕🤕
