### ISSUE TITLE
无法开启Root

### ISSUE THREAD

**Issue by Small-Ku** [liudongmiao/Brevent#220]
按下「使用Root開啓」按钮后，显示一会「正在取得處理程序狀態，請稍候. . .」会重回「請開啓黑域服務」的界面
Logcat: http://pastebin.com/rfrRF799

**Comment by chm512512** [comment]
哇喔，港台用户耶。
我翻墙看看连接先～

**Comment by liudongmiao** [comment]
> 03-14 12:13:09.467 W/Thread-1(16742): type=1400 audit(0.0:147): avc: denied { use } for path="/data/user_de/0/com.android.shell/dumpsys716031923log" dev="dm-0" ino=410226 scontext=u:r:system_server:s0 tcontext=u:r:su:s0 tclass=fd permissive=0

@Small-Ku 建议使用普通模式，或者禁用 selinux。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
