### ISSUE TITLE
百度外卖黑域之后立即自启动 + linux下无法获取相关日志 + 不稳定机型反馈

### ISSUE THREAD

**Issue by tgr989** [liudongmiao/Brevent#222]
Brevent 0.8.6 ; Android 6.0.1 ; Ubuntu 16.04

1.百度外卖4.5.0黑域之后立即自启动

2.linux下无法获取相关日志
user@user:~$ logcat -d -b crash
未找到 'logcat' 命令，您要输入的是否是：
 命令 'lolcat' 来自于包 'lolcat' (universe)
logcat：未找到命令
user@user:~$ logcat -d -s BreventServer BreventLoader
未找到 'logcat' 命令，您要输入的是否是：
 命令 'lolcat' 来自于包 'lolcat' (universe)
logcat：未找到命令

3.lenovo P8 plus不稳定，多次命令行才能成功，成功后也容易失效.
因为第二个问题的原因,无法获取相关日志.

**Comment by liudongmiao** [comment]
logcat 等，均是 adb shell 之后的指令。如果不在 adb shell 里，请使用 adb -d shell logcat ...

**Comment by tgr989** [comment]
Brevent 0.8.6 ; Android 6.0.1 ; Ubuntu 16.04

1.百度外卖4.5.0黑域之后立即自启动
adb -d logcat d -b crash
[crash.txt](https://github.com/liudongmiao/Brevent/files/840534/crash.txt)

adb -d logcat -d -s BreventServer BreventLoader
[Brevent.txt](https://github.com/liudongmiao/Brevent/files/840535/Brevent.txt)

2.lenovo P8 pluslenovo P8 plus不稳定现象不能复现，当时是0.8.5版本，现在是0.8.6了，以后有问题再反馈吧。

**Comment by liudongmiao** [comment]
从 Brevent.txt 里，你也看到了，一直不断的在强行停止它，但是它不断运行。

1. 请确定是否开启了优先通知，如果有，关掉它；你也可以去掉黑域设置中的“保持通知”看看
2. 你大约需要 ActivityManagerService 的日志了

对于这种问题，黑域无法处理。因为，如果一个程序杀了又启，只能继续杀。
说明，有某种系统层级的东西，不断的启动它。你除了卸载它，别无他法。

**Comment by tgr989** [comment]
谢谢解答，没开优先通知，开了保持通知。我已经卸载了百度外卖，保持通知是必须功能，哈哈。

**Comment by tgr989** [comment]
ActivityManagerService 日志有必要获取吗，如果要应该怎么获取。

**Comment by liudongmiao** [comment]
你可以自己尝试看一下。大约是 

`adb logcat -b system ActivityManager`

这个会打出一些应用被唤醒，特别是 component，但是，也不一定能定位到具体的来源。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
