### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Uomiio** [liudongmiao/Brevent#224]
--- crash start ---
>>> logcat -b crash -t '03-14 15:36:52.000' -d
03-14 15:36:53.561 24156 24156 E AndroidRuntime: !@*** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-14 15:36:53.561 24156 24156 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-14 15:36:53.561 24156 24156 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-14 15:36:53.561 24156 24156 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-14 15:36:53.561 24156 24156 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-14 15:36:53.561 24156 24156 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-14 15:36:53.561 24156 24156 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-14 15:36:53.561 24156 24156 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-14 15:36:53.561 24156 24156 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)
03-14 15:36:53.577 24156 24156 E AndroidRuntime: Error reporting crash
03-14 15:36:53.577 24156 24156 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:628)
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:66)
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3477)
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3476)
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:97)
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:130)
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-14 15:36:53.577 24156 24156 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-14 15:36:52.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

Device: Samsung S6 edge international （SM-G925F) @android 7.0 UX

**Comment by liudongmiao** [comment]
> java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)

Don't run as root, or disable selinux.

**Comment by Uomiio** [comment]
--- crash start ---
>>> logcat -b crash -t '03-14 20:35:57.000' -d
03-14 20:35:58.494  9587  9587 E AndroidRuntime: !@*** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-14 20:35:58.494  9587  9587 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-14 20:35:58.494  9587  9587 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-14 20:35:58.494  9587  9587 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-14 20:35:58.494  9587  9587 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-14 20:35:58.494  9587  9587 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-14 20:35:58.494  9587  9587 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-14 20:35:58.494  9587  9587 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-14 20:35:58.494  9587  9587 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)
03-14 20:35:58.509  9587  9587 E AndroidRuntime: Error reporting crash
03-14 20:35:58.509  9587  9587 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:628)
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:66)
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3477)
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3476)
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:97)
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:130)
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-14 20:35:58.509  9587  9587 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-14 20:35:57.000' -d -s BreventLoader BreventServer
--- brevent end ---


Set the selinux to permissive mode and it seems to be no difference. I'm not running from root mode

**Comment by liudongmiao** [comment]
1. run `adb shell` to device's shell

2.0 if you want to use su, run `su` in device's shell

2. run `id` in device's shell

3. run 'ls -l /data/user_de/0/com.android.shell/` in device's shell

**Comment by Uomiio** [comment]
zenlte:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc) context=u:r:shell:s0
zenlte:/ $ ls -l /data/user_de/0/com.android.shell/
total 24
drwxr-xr-x 2 root  root  4096 2017-03-12 04:15 brevent
drwxrwx--x 2 shell shell 4096 2017-03-13 17:27 cache
drwxrwx--x 2 shell shell 4096 2017-03-12 02:58 code_cache
-rw-r--r-- 1 root  root     0 2017-03-14 11:19 dumpsys1074074783log
-rw-r--r-- 1 root  root     0 2017-03-12 10:17 dumpsys1230807513appwidget
-rw-r--r-- 1 root  root     0 2017-03-14 11:19 dumpsys1250239038log
-rw-r--r-- 1 root  root     0 2017-03-14 11:21 dumpsys1404908705log
-rw-r--r-- 1 root  root     0 2017-03-14 11:19 dumpsys1415246285appwidget
-rw-r--r-- 1 root  root     0 2017-03-12 10:17 dumpsys1496424077appwidget
-rw-r--r-- 1 root  root     0 2017-03-14 11:19 dumpsys1514076597appwidget
-rw-r--r-- 1 root  root     0 2017-03-14 11:19 dumpsys278734450log
-rw-r--r-- 1 root  root     0 2017-03-14 11:21 dumpsys293350151appwidget
-rw-r--r-- 1 root  root     0 2017-03-14 11:19 dumpsys388010338appwidget
-rw-r--r-- 1 root  root     0 2017-03-14 11:19 dumpsys531783695log
-rw-r--r-- 1 root  root     0 2017-03-14 11:19 dumpsys643961694log
-rw-r--r-- 1 root  root     0 2017-03-14 11:19 dumpsys746256310log
-rw-r--r-- 1 root  root     0 2017-03-14 11:21 dumpsys869904948log


Got these lines. Is 'drwxr-xr-x 2 root  root  4096 2017-03-12 04:15 brevent' created by the patch smh?

**Comment by liudongmiao** [comment]
You have used root mode, then just swith to root account, delete all the files belong to root.

Then run as adb.

**Comment by Uomiio** [comment]
Thanks! Finally got it. Is it possible to start the service every time I restart the phone without using the adb command? I heard that root mode can do only few things.

**Comment by liudongmiao** [comment]
@Uomiio Yes, there is ROOT mode, which can skip debugging mode, and auto start.

1. click Back 7 times when you see "Please Start Brevent server"
2. click "Run as ROOT", if it works well, then navigate to Settings, donate a total of 3 USD

ROOT mode is unsafe, and unnecessary, and you may need to disable SELinux. (For myself, works well on Lineage's OS and it's su)

**Comment by liudongmiao** [comment]
@Uomiio Please note, if you choose root mode, then you cannot returns normal mode. However, you can uninstall Brevent in root mode, then, you can returns to adb/shell mode.

**Comment by Uomiio** [comment]
Great. I will try both ways and figure out which one fits me best.
