### ISSUE TITLE
软件捐赠过，为什么GCM 推送功能打不开了 ？谷歌市场下载的捐赠的！

### ISSUE THREAD

**Issue by cokeLi1983** [liudongmiao/Brevent#225]
软件捐赠过，为什么GCM 推送功能打不开了 ？谷歌市场下载的捐赠的！
![screenshot_20170314-122525](https://cloud.githubusercontent.com/assets/26404395/23893620/2065b31e-08da-11e7-9b38-0878767bb4cf.png)
![screenshot_20170314-135813](https://cloud.githubusercontent.com/assets/26404395/23893619/204a8184-08da-11e7-99f6-1fae03dde380.png)

**Comment by aviraxp** [comment]
这个，貌似需要额外1刀。

**Comment by cokeLi1983** [comment]
你的意思是我需要再捐赠一刀？

**Comment by cokeLi1983** [comment]
@aviraxp 你的意思是我需要再捐赠一刀？

**Comment by cokeLi1983** [comment]
@aviraxp 更新最新版本后再打不开的！之前没问题的！

**Comment by aviraxp** [comment]
你急啥。。。再捐赠1刀就开了

**Comment by cokeLi1983** [comment]
@aviraxp 这样玩不厚道吧再捐一到，呵呵，虽然我捐的不多！

**Comment by liudongmiao** [comment]
@cokeLi1983 确实提示语有些不太友好。晚上更新一下。

1. 为什么必须要“保持通知”？如果不保持通知，消息就没了。这个选项，下个版本，改成建议捐赠，但不强制。

2. 为什么必须要“允许 GCM”？
确切的说，这个应该叫“允许用户应用 GCM”。对于系统应用和框架应用，GMS 能轻易通过广播唤醒它们。而对于用户应用，必须要单开。但同时，某些流氓，明明不支持 GCM，却要声明。也就是说，一旦开了这个选项，他们除了能接受 GCM 广播外，还能被其它广播唤醒。所以必须要单开一个设置。这个设置，下个版本起，改成需要捐赠 2 美元，强制。你绕过的办法是，把这些应用放到系统里。

3. 至于是否厚道。
我已经提供了 APK 下载，只要是非 Play 安装的，使用没有任何限制。如果你要说，这也是不厚道的话，我也认了。

**Comment by liudongmiao** [comment]
@cokeLi1983 不过，既然你提到了不厚道，我还是下个版本，Play 版本里的保持通知也强制捐赠吧。

早先，真的是所有功能不设限制的。但是，有个人发邮件给我，说捐赠了和不捐赠没有区别，太寒心了。我听了太寒心，于是又加上限制。

**Comment by liudongmiao** [comment]
虽然，对 @aviraxp 这样的，捐赠过好多，但是 Play 版本可能还是要捐赠，确实不厚道...

@aviraxp 发个邮件给我吧，鉴于你在 github 上对于本项目的贡献，我给你一个特别贡献优惠码。

**Comment by cokeLi1983** [comment]
@刘东   不意思，我并没有恶意。我只是不明白这个什么情况，所以来这里问下！这是我第一次捐赠软件作者！让我遇到这样的问题，可能说话有点偏激了，我在这里说声不好意思！

**Comment by liudongmiao** [comment]
@cokeLi1983 我也很偏激。下个版本里，保持优先通知确实是会改成建议但不强制，其它的才强制，同时注明非Play版自由使用。

**Comment by cokeLi1983** [comment]
@liudongmiao 我来这里寻求解决问题不是来吵架的！

**Comment by AkazaDorian** [comment]
我补了一刀还是开不了 GCM。。。

**Comment by liudongmiao** [comment]
已经更新描述，请更新至 0.8.7
