### ISSUE TITLE
Copy 到剪贴板的字符串与 UI 的提示不符

### ISSUE THREAD

**Issue by lsmgeb89** [liudongmiao/Brevent#227]
小问题，实际 copy 的还是 me.piebridge.brevent-1。
但应该 copy 的是 me.piebridge.brevent-2。
麻烦更新下。

**Comment by liudongmiao** [comment]
我使用的是同一个字符串...会不会被其它的复制代替了？

**Comment by lsmgeb89** [comment]
重启看了下，确实是误报。
