### ISSUE TITLE
升级0.8.7后无法adb授权，也无法root模式运行

### ISSUE THREAD

**Issue by TAXUEZJU** [liudongmiao/Brevent#230]
原先0.8.6时root模式运行，升级后需要重新授权，运行adb报错，在系统内手动执行那个脚本也报错，下面附上log文件
`
taxue@TAXUE:~/Downloads> adb -d shell
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
bacon:/ $ /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-15 08:06:48.000' -d
03-15 08:06:50.355  8884  8884 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-15 08:06:50.355  8884  8884 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-15 08:06:50.355  8884  8884 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-15 08:06:50.355  8884  8884 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-15 08:06:50.355  8884  8884 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-15 08:06:50.355  8884  8884 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-15 08:06:50.355  8884  8884 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-15 08:06:50.355  8884  8884 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-15 08:06:50.355  8884  8884 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:264)
03-15 08:06:50.357  8884  8884 E AndroidRuntime: Error reporting crash
03-15 08:06:50.357  8884  8884 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3049)
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3048)
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:86)
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-15 08:06:50.357  8884  8884 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-15 08:06:48.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
`

**Comment by liudongmiao** [comment]
使用 root 模式以后，你回不到 adb 模式。

如果要继续使用 root 模式，清空黑域数据，阅读向导第二屏。

如果要退回到 adb 模式，以 root 身份进入 `/data/user_de/0/com.android.shell`，删除这个文件下所有文件。

**Comment by TAXUEZJU** [comment]
感谢，升级后没有详细阅读说明，已正常
