### ISSUE TITLE
提交一个问题

### ISSUE THREAD

**Issue by bensona1** [liudongmiao/Brevent#231]
我发现最近几个版本直接升级后虽然看似黑域仍能正常工作，能正常进入读取应用列表。 

但是实际上各功能已经无法正常运作。打开过的毒瘤软件一直在运行不会被强停（我设置的只强停，不休眠），本来黑域掉的应用旁边所在的计时也没有了。最近列表划掉也不能停止软件在后台的运行。

但此时连接电脑重新ADB后，一切恢复正常。

作者能否测试并修复一下这个问题呢？谢谢！

设备是7.1.1 Nexus 6P。

**Comment by Bob021** [comment]
是，最近也是此问题，我都要重新ADB，或者卸载直接安装最新版，不通过更新的方式。
你的酷市场正常吗？划掉后可以退出吗？

2017-03-15 9:25 GMT+08:00 bensona1 <notifications@github.com>:

**Comment by bensona1** [comment]
对的  就是这样  我直接用的网页版 并没有安装酷安的APP  如果直接覆盖升级黑域   黑域的各项功能都会失效（就看界面你会感觉一切正常）  划掉也无法退出   依然在后台运行

**Comment by Bob021** [comment]
兄弟，你安装下酷市场试试看，有没有最近列表划掉无法退出的问题，即使有时退出，你再进入黑域查看是否有运行，帮忙复试下，看此问题能否复现。如果你那边是好的，那就是我自个的问题。

**Comment by liudongmiao** [comment]
@Bob021 就我本地的话，没有。如果有，我早就修了。

你可以这样看看，划掉之后，回到桌面，等个3秒，再进黑域。
因为现在进入黑域已经不主动清理了，完全依赖事件机制自动处理。

**Comment by Bob021** [comment]
@liudongmiao 测试过，划掉之后，回到桌面，等个3秒，再进黑域，酷市场仍在运行。查看系统运行里酷市场也是在运行。

**Comment by liudongmiao** [comment]
@Bob021 开启详细调试模式吧。

1. 电脑命令行中执行以开启调试：adb -d shell setprop log.tag.BreventServer VERBOSE

2. 重新你这个过程，然后电脑命令行中执行以获取日志：adb -d logcat -d -s BreventServer

如果没有收到相应事件，黑域无法处理。

**Comment by bensona1** [comment]
作者  那我提交的问题怎么说呢？

**Comment by liudongmiao** [comment]
@bensona1 提交日志，上面有说怎么提取，参照一下就好。

**Comment by Bob021** [comment]
[调试日志.txt](https://github.com/liudongmiao/Brevent/files/843266/default.txt)
@liudongmiao 你看看是这样的调试日志吗？
谢谢！

**Comment by liudongmiao** [comment]
@Bob021 你的问题，就在 #228 这里说好了，不要交叉。

**Comment by bensona1** [comment]
那等下次覆盖安装的时候   我提取下日志  然后发上来吧

**Comment by GongJianwei** [comment]
请看 #74

**Comment by bensona1** [comment]
[调试日志.txt](https://github.com/liudongmiao/Brevent/files/872311/default.txt)
直接0.9.2升级到0.9.3+14的调试日志  这样是正常的吗  升级需要adb命令的问题应该解决了吧  为什么有时候感觉黑域了的应用会长时间逗留后台

**Comment by liudongmiao** [comment]
最新的测试版，开启 立即清理，应该能解决你的疑惑。
https://piebridge.me/br/next/

**Comment by bensona1** [comment]
谢谢作者回复。已经测试了测试版  开启了打开黑域界面后立即清理  但是并没有生效  我导出了日志记录给您参考，麻烦看下是什么原因  辛苦啦
[日志文件.txt](https://github.com/liudongmiao/Brevent/files/878828/default.txt)
