### ISSUE TITLE
GCM保持通知开启后无法唤醒

### ISSUE THREAD

**Issue by sunshineynwa** [liudongmiao/Brevent#232]
play版已经捐赠开启gcm保持通知，同时也将应用(比如whatsapp和microsoft teams)设置为优先打扰，然而发现将app在最近列表划去后，别人发消息无法主动收到通知，需要再次打开后才能看到，不知道这是否正常，烦请解答，谢谢！

**Comment by sunshineynwa** [comment]
机型三星s7e，安卓7.0，有谷歌框架

**Comment by liudongmiao** [comment]
这是微信限制。

目前你要微信可以收到的话，不要把它从最近列表划掉。其它的应用，whatsapp 你可以自由划掉它。

**Comment by sunshineynwa** [comment]
谢谢回复，但是现在的问题是微信没有问题，反而是teams和whatsapp在划掉之后就无法收到消息的推送，app显示不在运行

**Comment by liudongmiao** [comment]
你得开 优先通知，同时，设置里选择 保持通知，允许 GCM 推送。

**Comment by sunshineynwa** [comment]
谢谢回复。全部都是开启的，但是还是划去后无法唤醒。刚升级了0.87版，明天让同事帮忙再测试一下通知情况。现在同时安装了豌豆荚的通知清理，不知道是不是会有影响(app选择不清理)，明天如果还有问题，卸载清理后会再试一下。

**Comment by zzzdtz** [comment]
@sunshineynwa  同S7，三星S7 7.0的谷歌框架，FCM是被内核给镇压（严格）了，心跳的时候超过5分钟，断掉FCM连接后，要1个小时才会恢复连接（除非关闭网络重新打开，识别到网络变动才能自动连接），其他机型比如HTC 比如亲儿子，是能在心跳停止后，马上重连的，所以想三星S7 GCM收信，基本上不现实。已经放弃

**Comment by myliyifei** [comment]
只有国行的三星才有这个问题吧

**Comment by zzzdtz** [comment]
港行没测，不知道，国行的GCM应该是为了省电才这么搞的。。。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
