### ISSUE TITLE
大佬，刚才自动失效了

### ISSUE THREAD

**Issue by XiaoyuJiao** [liudongmiao/Brevent#233]
没重启过了一会儿需要重新adb，还有我不会提取日志😂😂😂

**Comment by XiaoyuJiao** [comment]
0.8.7play版

**Comment by Pason2C** [comment]
adb -d logcat -d -b crash
    #查看崩溃日志
    adb -d logcat -d -s BreventServer BreventLoader
    #查看黑域服务日志

**Comment by XiaoyuJiao** [comment]
谢谢柳大，下次退出时马上抓取😀😀😀

2017年3月15日 下午7:50，"Pason" <notifications@github.com>写道：

**Comment by Pason2C** [comment]
我不是柳大。。。

**Comment by XiaoyuJiao** [comment]
😱😱😱

2017年3月15日 下午7:55，"Pason" <notifications@github.com>写道：

**Comment by GongJianwei** [comment]
请看 #74

**Comment by XiaoyuJiao** [comment]
谢谢😂
