### ISSUE TITLE
没有人觉得每次重启都要连电脑一次非常不方便？

### ISSUE THREAD

**Issue by Sternengeang** [liudongmiao/Brevent#234]
存有adb的电脑就在手边还好说，重启这种事情谁也说不准什么时候会发生，万一在外边一不小心重启了黑域不就炸了？
不知道为什么你们都不在意这个问题，非root手机就不说了，新版本居然连root手机也要电脑授权，在无法脱离电脑使用之前黑域作为非常不安定的因素，绝对无法作为一个靠谱的系统优化工具使用。

**Comment by liudongmiao** [comment]
1. 如果你的手机经常重启，请不要使用黑域，这不面向这样的用户。
2. 如果你 ROOT 了，请认真参阅第二屏。同时，Play 版强制捐赠。

你告诉我不 ROOT 情况下哪个可以达到黑域的效果，我保证只使用它，不再开发。

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
