### ISSUE TITLE
NEXUS 6P安装3月15日安全补丁之后无法启用

### ISSUE THREAD

**Issue by Fortis428** [liudongmiao/Brevent#236]
安装官方OTA 3月5日安全补丁之后，黑域就无法启用了。
adb执行之后显示成功，但是读取一段时间程序之后显示"请重启黑域服务"并伴随屏幕闪动。
使用老版本0.8.6 及0.8.5依旧不行。
有截图。请问该如何解决啊。
![1](https://cloud.githubusercontent.com/assets/19601896/23980072/609035e0-0a38-11e7-98ac-df0c4eddbf6d.jpg)
![2](https://cloud.githubusercontent.com/assets/19601896/23980069/606e0e34-0a38-11e7-8286-915d7f925bb6.jpg)
![3](https://cloud.githubusercontent.com/assets/19601896/23980071/607970f8-0a38-11e7-9db3-525fa34a7fe1.jpg)
日志是这样调试吗？
![4](https://cloud.githubusercontent.com/assets/19601896/23980659/0c4f2cc6-0a3c-11e7-885c-312817afa774.jpg)

-===============
莫名其妙的好了，我的手机有毒。

**Comment by liudongmiao** [comment]
从日志看，一切正常。。。。

**Comment by Fortis428** [comment]
@liudongmiao 有什么建议的解决方案吗。前天还是可以的，昨天安装更新之后突然就无法执行了。

**Comment by lebronbian** [comment]
求字体

**Comment by Bob021** [comment]
可能需要重新刷一下系统或者清除数据试试。

**Comment by Fortis428** [comment]
@Bob021 并未root。只能格机重置了么。惨

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
