### ISSUE TITLE
android 7.1.1 一加2启动不成功

### ISSUE THREAD

**Issue by wahmaths** [liudongmiao/Brevent#237]
好像是文件找不到的错误。明明给了权限，还报错？
求教
--- crash start ---
>>> logcat -b crash -t '03-16 14:53:21.000' -d
E/AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
E/AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
E/AndroidRuntime:       at java.io.FileOutputStream.open(Native Method)
E/AndroidRuntime:       at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
E/AndroidRuntime:       at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
E/AndroidRuntime:       at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
E/AndroidRuntime:       at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
E/AndroidRuntime:       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E/AndroidRuntime:       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:269)
E/AndroidRuntime: Error reporting crash
E/AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
E/AndroidRuntime:       at android.os.BinderProxy.transactNative(Native Method)
E/AndroidRuntime:       at android.os.BinderProxy.transact(Binder.java:615)
E/AndroidRuntime:       at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
E/AndroidRuntime:       at android.os.ServiceManager.getService(ServiceManager.java:55)
E/AndroidRuntime:       at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3072)
E/AndroidRuntime:       at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3071)
E/AndroidRuntime:       at android.util.Singleton.get(Singleton.java:34)
E/AndroidRuntime:       at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:87)
E/AndroidRuntime:       at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:98)
E/AndroidRuntime:       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E/AndroidRuntime:       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---

**Comment by Pason2C** [comment]
尝试一下将SELinux状态设置为permissive
 [SELinux Mode Changer](http://www.coolapk.com/apk/com.mrbimc.selinux)

**Comment by liudongmiao** [comment]
十天未反馈，关闭。

这个在新版都有新的提示。就是以 root 运行了，然后以 shell 运行。
