### ISSUE TITLE
8.6开始无法浅度休眠

### ISSUE THREAD

**Issue by chenbuhtig** [liudongmiao/Brevent#238]
8.5是这样的
![443608_1489609789_075 png s](https://cloud.githubusercontent.com/assets/26458044/23992427/dc85c432-0a77-11e7-9177-740546e8f8da.jpg)

8.6和8.7开始是这样的
![14dd1abba9218a11c34f303496496699](https://cloud.githubusercontent.com/assets/26458044/23992473/0e331034-0a78-11e7-9fb2-218b7a4e0e02.jpg)

日志是这个吗？
![default](https://cloud.githubusercontent.com/assets/26458044/23992483/1863d7f0-0a78-11e7-94c3-d84d0fa84489.PNG)

系统是官方的lineageos没谷歌套件

**Comment by liudongmiao** [comment]
lineageos 就是没有gms的话，不能待机。
