### ISSUE TITLE
按照应用的提示做的，似乎出现了问题

### ISSUE THREAD

**Issue by hashiqice** [liudongmiao/Brevent#239]
--- crash start ---
>>> logcat -b crash -t '03-17 08:46:08.000' -d
03-17 08:46:09.986  2941  2941 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-17 08:46:09.986  2941  2941 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-17 08:46:09.986  2941  2941 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-17 08:46:09.986  2941  2941 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-17 08:46:09.986  2941  2941 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-17 08:46:09.986  2941  2941 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-17 08:46:09.986  2941  2941 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-17 08:46:09.986  2941  2941 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-17 08:46:09.986  2941  2941 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:268)
03-17 08:46:09.993  2941  2941 E AndroidRuntime: Error reporting crash
03-17 08:46:09.993  2941  2941 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3063)
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3062)
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:87)
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:98)
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-17 08:46:09.993  2941  2941 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-17 08:46:08.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

希望能够得到帮助

**Comment by liudongmiao** [comment]
请给两个结果

```
adb -d shell id
```

```
adb -d shell ls -l /data/user_de/0/com.android.shell
```
