### ISSUE TITLE
有人参考appops和您的黑域，做了一个无需root的

### ISSUE THREAD

**Issue by one360** [liudongmiao/Brevent#24]
以下都是搬运：

我做了个免Root的应用管理应用，实现的功能有：
1，权限管理（对于一些敏感权限，提供假数值）
2，应用免后台（Android 7.0及以上可用）
以上两者基于Android的调试方法 appops实现。
3，屏幕关闭后应用自动休眠（绿色守护中的“浅度休眠”）
4，屏幕关闭后应用强制退出。
后两个基于adb 的am指令实现。
所以这是一个利用adb调试命令来实现免Root地应用管理软件。
使用方法如下：
应用打开前，手机要打开开发者选项，连接上电脑 在终端输入 adb tcpip 5555 回车。就可以正常使用这个工具了。注意：
1 手机的开发者选项不可关闭。
2 手机重启后，需要再次直行 adb tcpip 5555命令。
3 弹出“允许USB调试”的对话框时，需要勾选一律同意且确定（否则需要清除应用数据重新打开，只有一次授权机会）
应用支持Android 6.0及以上。UI是Clone appops的，实现逻辑上重写了，关于“黑域”算是个思想上的参考
apk地址
https://drive.google.com/open?id=0Bz8hObq51pTzaE1OQlNqS0pFLXM

**Comment by garywzh** [comment]
一直开着网络调试比较有风险，每个应用可能去申请连接 adb

**Comment by liudongmiao** [comment]
很好。如果早知道的话，我就不写了。

**Comment by liudongmiao** [comment]
再多说一点，如果只是使用的话，不建议任何人尝试。

adb shell具有很高的权限，如果只是开了，凭用户自己去授权或者不授权，是种非常危险的行为。
所以，除了黑域的基本工作之外，我一直在想一件事：

怎么开一个口子，并且，只许自己使用？

无论是阻止运行，还是黑域，我都在这方面处理非常谨慎。

**Comment by one360** [comment]
这个作者说了，参考了你的思想，用这个模拟的adb，https://github.com/tananaev/adblib。你考虑的很周到，知乎也看到过类似的安全考虑，我这几天也只是在备用机上使用这个app，就是担心这点。希望新版的黑域能解决好安全问题，如果你的上架了，那一定使用你的，毕竟您的阻止运行太经典了。希望能早日上架play商店。谢谢！

**Comment by liudongmiao** [comment]
本地其实已经差不多完成了，有些功能还在调试与自测中。

另外，就是想着既然有人说界面长得和阻止运行相似，所以我也在想要不要花点时间重写个UI...

我花了很大的精力在如何开一个口子只允许自己使用...这里一度block了我很久很久很久。

**Comment by one360** [comment]
期待，可以先放出来，公测更容易发现问题。UI相似，原理不同，如果有人拿这个说事，那这个人也够无知的。

**Comment by sino1641** [comment]
@one360 
更关心权限管理实现的原理？
是类似XPrivacy么？

**Comment by one360** [comment]
@sino1641 利用adb起个shell进程吧，XPrivacy是依靠框架吧
