### ISSUE TITLE
部分软件存在闪退情况，并且是未黑域过的软件

### ISSUE THREAD

**Issue by HandsomeYellow** [liudongmiao/Brevent#242]
谷歌官方的Messages和酷友开发的搜索lite比较常用，我都没进行黑域
但是，这两个使用时候均出现了闪退，点进去出现一会主界面就闪退了，闪退多次后才能正常使用
重启后没有启用黑域，软件使用正常，应该确认是黑域的问题了

主要是我这两个软件都没进行黑域，而且黑域策略没有做任何更改，就是使用默认的

软件版本是0.8.7，最新的

**Comment by liudongmiao** [comment]
1. 卸载黑域

2. 不要使用任何 appops 策略

3. 如果你认为是黑域，就得拿出黑域日志啊
