### ISSUE TITLE
开机一会后黑域无反应

### ISSUE THREAD

**Issue by aocboe** [liudongmiao/Brevent#243]
Root模式下，开机久了之后软件会没反应（具体表现为无法黑域软件，无法不再黑域软件，软件的休眠与强制停止也有问题），必须重启（强制停止黑域再打开无用）才能恢复正常
Slim 7.1.1（based on aosp）与非官方CM 13均有此问题（机型：OnePlus One）
授权软件为Magisk SU，SELinux状态为许可

**Comment by liudongmiao** [comment]
本人不对 root 模式提供任何支援，特别是没有日志的情况下。
