### ISSUE TITLE
[BUG]自动黑域会黑域输入法程序

### ISSUE THREAD

**Issue by moonheart** [liudongmiao/Brevent#244]
步骤：
1. 新系统
2. 安装并启用黑域，保持默认设置
3. 通过钛备份还原谷歌拼音输入法
4. 在文字输入界面点击，弹出输入法键盘，但3s后自动关闭
5. 在黑域中查看，发现输入法处于黑域状态，且未运行

**Comment by liudongmiao** [comment]
并不属于 BUG，你不要黑域它就是。

下个版本里，将不会处理正在使用的输入法。

**Comment by moonheart** [comment]
好的，等待修复

**Comment by liudongmiao** [comment]
由于获取方法有误，所以启用了输入法之后，还是进入一回黑域吧。
