### ISSUE TITLE
 Can't be run as root, please open Brevent

### ISSUE THREAD

**Issue by yeniugo** [liudongmiao/Brevent#245]
--- crash start ---
******* logcat -b crash -t '03-18 09:22:58.000' -d
03-18 09:23:00.449  4821  4821 F libc    : page record for 0x7f7e1ea050 was not found (block_size=64)
03-18 09:23:00.500  4822  4822 F libc    : page record for 0x7fa54c8050 was not found (block_size=64)
--- crash end ---
--- brevent start ---
******* logcat -b main -t '03-18 09:22:58.000' -d -s BreventLoader BreventServer
03-18 09:22:59.275  4791  4791 I BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
03-18 09:22:59.319  4791  4801 I BreventServer: Brevent Server 0.8.7 started
03-18 09:22:59.334  4791  4801 I BreventServer: brevent user: 0
03-18 09:22:59.336  4791  4801 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-18 09:22:59.402  4791  4801 I BreventServer: loading brevent list
03-18 09:22:59.403  4791  4801 I BreventServer: loading brevent conf
03-18 09:22:59.567  4791  4801 D BreventServer: sent first status
03-18 09:22:59.568  4791  4805 D BreventServer: received feelgood
03-18 09:23:02.487  4791  4801 E BreventServer: Can't be run as root, please open Brevent

**Comment by liudongmiao** [comment]
I think the message is very clear.

In short, please don't run from third-party tools, just in Brevent.
If you want to use root in Brevent, read the guide carefully.

If you have donate, please navigate to settings, then enable run as root.
If you don't see it, please read guide carefully, special "Security".
