### ISSUE TITLE
从其他应用打开的被黑域应用，会在打开系统分享界面数秒后被强行停止

### ISSUE THREAD

**Issue by EdiTurn** [liudongmiao/Brevent#248]
Android 7.1.1，Nexus 6P，黑域 0.8.7 root

复现方式：在 A 应用中点击链接打开被黑域的 B 应用，然后在 B 应用中使用分享功能打开系统的分享界面，数秒后 B 应用会被强行停止。

> 03-19 00:30:02.075 980-3965/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=http://www.bilibili.com/... cmp=com.bilibili.app.blue/tv.danmaku.bili.ui.IntentHandlerActivity (has extras)} from uid 10180 on display 0
03-19 00:30:02.133 980-6920/? I/ActivityManager: Start proc 20144:com.bilibili.app.blue/u0a198 for activity com.bilibili.app.blue/tv.danmaku.bili.ui.IntentHandlerActivity
03-19 00:30:02.263 980-6920/? I/ActivityManager: Start proc 20161:com.bilibili.app.blue:download/u0a198 for content provider com.bilibili.app.blue/com.bilibili.lib.lua.LuaProvider
03-19 00:30:02.334 20161-20161/? D/ActivityThread: Loading provider com.bilibili.app.blue.provider.lua: com.bilibili.lib.lua.LuaProvider
03-19 00:30:02.487 980-4796/? I/ActivityManager: START u0 {cmp=com.bilibili.app.blue/tv.danmaku.bili.MainActivity} from uid 10198 on display 0
03-19 00:30:02.497 980-4796/? I/ActivityManager: START u0 {cmp=com.bilibili.app.blue/tv.danmaku.bili.ui.video.VideoDetailsActivity (has extras)} from uid 10198 on display 0
03-19 00:30:02.882 980-1022/? I/ActivityManager: Displayed com.bilibili.app.blue/tv.danmaku.bili.ui.video.VideoDetailsActivity: +366ms (total +2m2s40ms)
03-19 00:30:02.933 980-1022/? I/WindowManager: Screen frozen for +417ms due to Window{7f84774 u0 Starting com.bilibili.app.blue}
03-19 00:30:03.365 20161-20172/? D/J4A: J4ALoader: OK: 'com.bilibili.lua.BLReportWrapper' loaded
03-19 00:30:03.366 20161-20172/? D/J4A: J4ALoader: OK: 'com.bilibili.lua.BLSi7Wrapper' loaded
03-19 00:30:03.366 20161-20172/? D/J4A: J4ALoader: OK: 'com.bilibili.lua.BLHttpWrapper' loaded
03-19 00:30:03.551 980-4761/? I/ActivityManager: Start proc 20248:com.bilibili.app.blue:stats/u0a198 for service com.bilibili.app.blue/com.bilibili.lib.infoeyes.InfoEyesRemoteService
03-19 00:30:12.418 980-12807/? I/ActivityManager: Force stopping com.bilibili.app.blue appid=10198 user=0: from pid 8831
03-19 00:30:12.419 980-12807/? I/ActivityManager: Killing 20144:com.bilibili.app.blue/u0a198 (adj 100): stop com.bilibili.app.blue
03-19 00:30:12.421 980-12807/? W/ActivityManager: Force removing ActivityRecord{a65e7e6 u0 com.bilibili.app.blue/tv.danmaku.bili.ui.video.VideoDetailsActivity t10436}: app died, no saved state
03-19 00:30:12.458 980-12807/? I/ActivityManager: Start proc 20437:com.bilibili.app.blue/u0a198 for activity com.bilibili.app.blue/tv.danmaku.bili.MainActivity
03-19 00:30:12.458 980-12807/? I/ActivityManager: Killing 20161:com.bilibili.app.blue:download/u0a198 (adj 0): stop com.bilibili.app.blue
03-19 00:30:12.459 980-12807/? W/ActivityManager: Scheduling restart of crashed service com.bilibili.app.blue/tv.danmaku.bili.services.videodownload.VideoDownloadService in 1000ms
03-19 00:30:12.459 980-12807/? I/ActivityManager: Killing 20248:com.bilibili.app.blue:stats/u0a198 (adj 500): stop com.bilibili.app.blue
03-19 00:30:12.459 980-12807/? W/ActivityManager: Scheduling restart of crashed service com.bilibili.app.blue/com.bilibili.lib.infoeyes.InfoEyesRemoteService in 10999ms
03-19 00:30:12.461 980-12807/? I/ActivityManager:   Force finishing activity ActivityRecord{62efb4b u0 com.bilibili.app.blue/tv.danmaku.bili.MainActivity t10436}
03-19 00:30:12.510 980-12807/? I/ActivityManager:   Force stopping service ServiceRecord{dfb6735 u0 com.bilibili.app.blue/tv.danmaku.bili.services.videodownload.VideoDownloadService}
03-19 00:30:12.512 8831-8880/? D/BreventServer: Force stop com.bilibili.app.blue(noRecent)
03-19 00:30:13.259 980-4858/? I/ActivityManager: Start proc 20472:com.bilibili.app.blue:download/u0a198 for content provider com.bilibili.app.blue/com.bilibili.lib.lua.LuaProvider
03-19 00:30:13.401 20472-20472/? D/ActivityThread: Loading provider com.bilibili.app.blue.provider.lua: com.bilibili.lib.lua.LuaProvider
03-19 00:30:17.664 980-1012/? I/ActivityManager: Force stopping com.bilibili.app.blue appid=10198 user=0: from pid 8831
03-19 00:30:17.664 980-1012/? I/ActivityManager: Killing 20437:com.bilibili.app.blue/u0a198 (adj 900): stop com.bilibili.app.blue
03-19 00:30:17.668 980-1012/? I/ActivityManager: Killing 20472:com.bilibili.app.blue:download/u0a198 (adj 900): stop com.bilibili.app.blue
03-19 00:30:17.675 8831-8880/? D/BreventServer: Force stop com.bilibili.app.blue(noRecent)

**Comment by liudongmiao** [comment]
重启，重新执行看看。

然后带上黑域服务的调试日志，商店详情里有获取方法。
