### ISSUE TITLE
偶尔发生打开被黑域的应用会直接闪退，再打开则正常的问题

### ISSUE THREAD

**Issue by EdiTurn** [liudongmiao/Brevent#249]
Android 7.1.1，Nexus 6P，黑域 0.8.7 root

> 03-19 00:17:41.524 980-6914/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.eg.android.AlipayGphone/.AlipayLogin bnds=[287,627][514,906] (has extras)} from uid 10093 on display 0
03-19 00:17:41.536 607-765/? D/audio_hw_primary: enable_snd_device: snd_device(2: speaker)
03-19 00:17:41.541 607-765/? D/audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback speaker
03-19 00:17:41.557 980-1012/? I/ActivityManager: Start proc 18389:com.eg.android.AlipayGphone/u0a178 for activity com.eg.android.AlipayGphone/.AlipayLogin
03-19 00:17:41.635 18389-18389/? I/art: Starting a blocking GC AddRemoveAppImageSpace
03-19 00:17:41.647 4990-16059/? I/PBSessionCacheImpl: Deleted sessionId[21947741939751176] from persistence.
03-19 00:17:41.664 4990-4990/? W/SearchService: Abort, client detached.
03-19 00:17:41.758 18389-18389/? I/jni: libcrashsdk.so loaded
03-19 00:17:41.764 18389-18389/? I/Logging: LoggerFactoryBinder.nativeInit invoked
03-19 00:17:41.859 18389-18389/? D/ApplicationLoaders: ignored Vulkan layer search path /data/app/com.android.chrome-1/lib/arm:/data/app/com.android.chrome-1/base.apk!/lib/armeabi-v7a for namespace 0xe89db090
03-19 00:17:41.937 18389-18389/? I/WebViewFactory: Loading com.android.chrome version 56.0.2924.87 (code 292408752)
03-19 00:17:41.955 980-980/? V/NotificationService: pkg=com.internet.speed.meter canInterrupt=false intercept=true
03-19 00:17:42.014 980-1013/? I/ActivityManager: Force stopping com.eg.android.AlipayGphone appid=10178 user=0: from pid 8831
03-19 00:17:42.015 980-1013/? I/ActivityManager: Killing 18389:com.eg.android.AlipayGphone/u0a178 (adj 0): stop com.eg.android.AlipayGphone
03-19 00:17:42.015 980-1013/? D/ActivityManager: cleanUpApplicationRecord -- 18389
03-19 00:17:42.029 980-1013/? I/ActivityManager: Start proc 18420:com.eg.android.AlipayGphone/u0a178 for activity com.eg.android.AlipayGphone/.AlipayLogin
03-19 00:17:42.029 980-1013/? I/ActivityManager:   Force finishing activity ActivityRecord{cc70f46 u0 com.eg.android.AlipayGphone/.AlipayLogin t10435}
03-19 00:17:42.042 8831-8880/? D/BreventServer: Force stop com.eg.android.AlipayGphone(noRecent)

**Comment by liudongmiao** [comment]
如果应用实现不够好，或者说通过服务方式启动的界面，有可能发生。

此外，需要黑域服务的日志，只有这个日志，不够啊。
