### ISSUE TITLE
Nexus9 反编译 失败 Could not find classpath entry /system/framework/core.jar

### ISSUE THREAD

**Issue by zhucemax** [liudongmiao/Brevent#25]
我的Nexus9 是原生的7.1.1系统 在反编译的时候使用 命令java -Xms1g -jar baksmali-2.2b4.jar x -d C:\Users\用户名\framework\arm C:\Users\用户名\framework\services.jar -o services 指令，报错Could not find classpath entry /system/framework/core.jar。是不是应该使用 java -Xms1g -jar baksmali-2.2b4.jar d <services.jar路径,1M以上> -o services 这个命令？这个可以得到一个 services 文件夹。

**Comment by aviraxp** [comment]
请把整个/framework目录导出。

**Comment by zhucemax** [comment]
看错了，我的没有odex与dex 不用执行C:\Users\用户名\framework\arm C:\Users\用户名\framework\services.jar -o services 指令，只需要使用 java -Xms1g -jar baksmali-2.2b4.jar d <services.jar路径,1M以上> -o services 这个命令，现在可以打完补丁了，谢谢！
