### ISSUE TITLE
无网就提示root?

### ISSUE THREAD

**Issue by sxml** [liudongmiao/Brevent#250]
一断网 就提示需要root 难道root是连网的? 
还有能不能白名单 没谷歌框架 使用GcmForMojo 小米推送信息

**Comment by sxml** [comment]
GcmForMojo 黑域  锁屏推送信息就不提示

**Comment by liudongmiao** [comment]
1. 黑域需要访问本地(localhost)，看你对网络的定义
2. 不加入即白名单。
3. 要显示通知，请开启“保持通知”。

**Comment by sxml** [comment]
定时省电模式 自动半夜关闭网络 那黑域也就不工作了?

**Comment by liudongmiao** [comment]
再看看吧，和网络肯定是无关的。我本地，飞行模式也可以使用的。
