### ISSUE TITLE
MIUI下报错

### ISSUE THREAD

**Issue by wu1yi2fan** [liudongmiao/Brevent#251]
用adb开启时报错
--- crash start ---
>>> logcat -b crash -t '03-19 10:11:01.000' -d
03-19 10:11:02.837 17218 17218 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-19 10:11:02.837 17218 17218 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/com.android.shell/brevent/libreader.so: open failed: EACCES (Permission denied)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        at libcore.io.IoBridge.open(IoBridge.java:452)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:331)
03-19 10:11:02.837 17218 17218 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        at libcore.io.Posix.open(Native Method)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        at libcore.io.IoBridge.open(IoBridge.java:438)
03-19 10:11:02.837 17218 17218 E AndroidRuntime:        ... 6 more
03-19 10:11:02.850 17218 17218 E AndroidRuntime: Error reporting crash
03-19 10:11:02.850 17218 17218 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-19 10:11:02.850 17218 17218 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-19 10:11:02.850 17218 17218 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:506)
03-19 10:11:02.850 17218 17218 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-19 10:11:02.850 17218 17218 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
03-19 10:11:02.850 17218 17218 E AndroidRuntime:        at miui.mqsas.sdk.MQSEventManagerDelegate.getMQSService(MQSEventManagerDelegate.java:85)
03-19 10:11:02.850 17218 17218 E AndroidRuntime:        at miui.mqsas.sdk.MQSEventManagerDelegate.reportJavaExceptionEvent(MQSEventManagerDelegate.java:36)
03-19 10:11:02.850 17218 17218 E AndroidRuntime:        at com.android.internal.os.RuntimeInitInjector.onJE(RuntimeInitInjector.java:58)
03-19 10:11:02.850 17218 17218 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:149)
03-19 10:11:02.850 17218 17218 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
03-19 10:11:02.850 17218 17218 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-19 10:11:01.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
http://piebridge.me/br/next/ 使用这个版本吧。

另外，建议去删除  /data/user/0/com.android.shell/ 这个目录下所有文件
