### ISSUE TITLE
Sony Z3C ADB 命令报错

### ISSUE THREAD

**Issue by taklele** [liudongmiao/Brevent#253]
--- crash start ---
>>> logcat -b crash -t '03-19 22:06:40.000' -d
03-19 22:06:41.011 11440 11440 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM P
ROCESS: main
03-19 22:06:41.011 11440 11440 E AndroidRuntime: java.io.FileNotFoundException:
/data/user/0/com.sonymobile.enterprise.installation/brevent/libreader.so: open f
ailed: EACCES (Permission denied)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        at libcore.io.IoBridge.o
pen(IoBridge.java:452)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        at java.io.FileOutputStr
eam.<init>(FileOutputStream.java:87)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        at java.io.FileOutputStr
eam.<init>(FileOutputStream.java:72)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        at me.piebridge.brevent.
loader.Brevent.a(Brevent.java:95)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        at me.piebridge.brevent.
loader.Brevent.main(Brevent.java:123)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit.nativeFinishInit(Native Method)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit.main(RuntimeInit.java)
03-19 22:06:41.011 11440 11440 E AndroidRuntime: Caused by: android.system.Errno
Exception: open failed: EACCES (Permission denied)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        at libcore.io.Posix.open
(Native Method)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        at libcore.io.BlockGuard
Os.open(BlockGuardOs.java:186)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        at libcore.io.IoBridge.o
pen(IoBridge.java:438)
03-19 22:06:41.011 11440 11440 E AndroidRuntime:        ... 6 more
03-19 22:06:41.012 11440 11440 E AndroidRuntime: Error reporting crash
03-19 22:06:41.012 11440 11440 E AndroidRuntime: java.lang.RuntimeException: Bad
 file descriptor
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at android.os.BinderProx
y.transactNative(Native Method)
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at android.os.BinderProx
y.transact(Binder.java)
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at android.os.ServiceMan
agerProxy.getService(ServiceManagerNative.java)
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at android.os.ServiceMan
ager.getService(ServiceManager.java)
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at android.app.ActivityM
anagerNative$1.create(ActivityManagerNative.java)
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at android.app.ActivityM
anagerNative$1.create(ActivityManagerNative.java)
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at android.util.Singleto
n.get(Singleton.java)
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at android.app.ActivityM
anagerNative.getDefault(ActivityManagerNative.java)
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java)
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at java.lang.ThreadGroup
.uncaughtException(ThreadGroup.java:693)
03-19 22:06:41.012 11440 11440 E AndroidRuntime:        at java.lang.ThreadGroup
.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-19 22:06:40.000' -d -s BreventLoader BreventServer
--- brevent end ---

**Comment by Pason2C** [comment]
善用搜索：跟issue https://github.com/liudongmiao/Brevent/issues/235 一样的问题。
你应该是之前使用过Root模式，删除 `/data/user/0/com.android.shell/ `下的文件后重启再试。

**Comment by taklele** [comment]
楼上说的那个问题我看了，发生的场景几乎一样。
但是那个文件夹下没有任何文件。
我删除那个文件夹，然后删除黑域，重启手机。再重新安装，还是无效...

**Comment by Pason2C** [comment]
那等开发者看看是什么问题吧。

**Comment by liudongmiao** [comment]
无效也要有无效的日志，日志一样还是咋的？
不要使用任何方式试图以 root 方式调用黑域服务。
否则文件一旦生成，你一样会遇到这样的事情。

你可以卸载，删除那个文件，尝试目前的测试版：https://piebridge.me/br/next/

**Comment by taklele** [comment]
我是有多闲，复制别人的问题过来问....
测试版安装通过。
