### ISSUE TITLE
0.8.7-19开启失败

### ISSUE THREAD

**Issue by mzfqy** [liudongmiao/Brevent#255]
adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbrevent.so

**Comment by mzfqy** [comment]
>>> logcat -b crash -t '03-19 23:45:45.000' -d
03-19 23:45:46.246  6162  6162 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-19 23:45:46.246  6162  6162 E AndroidRuntime: java.lang.NoSuchFieldError: No field QS_TILES of type Ljava/lang/String; in class Landroid/provider/Settings$Secure; or its superclasses (declaration of 'android.provider.Settings$Secure' appears in /system/framework/framework.jar)
03-19 23:45:46.246  6162  6162 E AndroidRuntime:        at me.piebridge.brevent.a.c.<clinit>(HideApiOverrideN.java:17)
03-19 23:45:46.246  6162  6162 E AndroidRuntime:        at me.piebridge.brevent.server.d.<clinit>(HideApi.java:57)
03-19 23:45:46.246  6162  6162 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:180)
03-19 23:45:46.246  6162  6162 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.z(BreventServer.java:1420)
03-19 23:45:46.246  6162  6162 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1482)
03-19 23:45:46.246  6162  6162 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-19 23:45:46.246  6162  6162 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:342)
03-19 23:45:46.248  6162  6162 E AndroidRuntime: Error reporting crash
03-19 23:45:46.248  6162  6162 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-19 23:45:46.248  6162  6162 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-19 23:45:46.248  6162  6162 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:618)
03-19 23:45:46.248  6162  6162 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-19 23:45:46.248  6162  6162 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
03-19 23:45:46.248  6162  6162 E AndroidRuntime:        at miui.mqsas.sdk.MQSEventManagerDelegate.getMQSService(MQSEventManagerDelegate.java:85)
03-19 23:45:46.248  6162  6162 E AndroidRuntime:        at miui.mqsas.sdk.MQSEventManagerDelegate.reportJavaExceptionEvent(MQSEventManagerDelegate.java:36)
03-19 23:45:46.248  6162  6162 E AndroidRuntime:        at com.android.internal.os.RuntimeInitInjector.onJE(RuntimeInitInjector.java:58)
03-19 23:45:46.248  6162  6162 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:149)
03-19 23:45:46.248  6162  6162 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-19 23:45:46.248  6162  6162 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-19 23:45:45.000' -d -s BreventLoader BreventServer
03-19 23:45:45.852  6149  6149 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
03-19 23:45:45.884  6149  6149 D BreventLoader: libreader: /data/app/me.piebridge.brevent-1/lib/arm64/libreader.so
03-19 23:45:46.239  6162  6162 I BreventServer: Brevent Server 0.8.7-19-gbc5405e started
03-19 23:45:46.258  6149  6149 E BreventLoader: worker 6162 exited on signal 9
03-19 23:45:46.258  6149  6149 D BreventLoader: signal arrived, update: 0
03-19 23:45:46.259  6148  6148 D BreventLoader: worker 6149 exited with status 0
--- brevent end ---

**Comment by shinzi0427** [comment]
同样
--- crash start ---
>>> logcat -b crash -t '03-19 23:48:48.000' -d
03-19 23:48:51.407 13295 13295 E AndroidRuntime: !@*** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-19 23:48:51.407 13295 13295 E AndroidRuntime: java.lang.NoSuchFieldError: No field QS_TILES of type Ljava/lang/String; in class Landroid/provider/Settings$Secure; or its superclasses (declaration of 'android.provider.Settings$Secure' appears in /system/framework/framework.jar:classes2.dex)
03-19 23:48:51.407 13295 13295 E AndroidRuntime:        at me.piebridge.brevent.a.c.<clinit>(HideApiOverrideN.java:17)
03-19 23:48:51.407 13295 13295 E AndroidRuntime:        at me.piebridge.brevent.server.d.<clinit>(HideApi.java:57)
03-19 23:48:51.407 13295 13295 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:180)
03-19 23:48:51.407 13295 13295 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.z(BreventServer.java:1420)
03-19 23:48:51.407 13295 13295 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1482)
03-19 23:48:51.407 13295 13295 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-19 23:48:51.407 13295 13295 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)
03-19 23:48:51.461 13295 13295 E AndroidRuntime: Error reporting crash
03-19 23:48:51.461 13295 13295 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:628)
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:66)
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3460)
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3459)
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:97)
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:130)
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-19 23:48:51.461 13295 13295 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-19 23:48:48.000' -d -s BreventLoader BreventServer
03-19 23:48:50.346 13280 13280 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
03-19 23:48:50.481 13280 13280 D BreventLoader: libreader: /data/app/me.piebridge.brevent-1/lib/arm64/libreader.so
03-19 23:48:51.390 13295 13295 I BreventServer: Brevent Server 0.8.7-19-gbc5405e started
03-19 23:48:51.494 13280 13280 E BreventLoader: worker 13295 exited on signal 9
03-19 23:48:51.494 13280 13280 D BreventLoader: signal arrived, update: 0
03-19 23:48:51.496 13278 13278 D BreventLoader: worker 13280 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by aviraxp** [comment]
又是个hidden api的锅么。。。

**Comment by liudongmiao** [comment]
告诉我说是 api 24，但是没有 qs_tiles ....
