### ISSUE TITLE
br0.8.7+21 一加7.1.1报错 - 没有 Tiles

### ISSUE THREAD

**Issue by kuwanone** [liudongmiao/Brevent#256]
C:\Users\lst>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbrevent.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-20 09:36:28.000' -d
03-20 09:36:29.276  5140  5140 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-20 09:36:29.276  5140  5140 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
03-20 09:36:29.276  5140  5140 E AndroidRuntime:        at me.piebridge.brevent.protocol.b.a(TileUtils.java:23)
03-20 09:36:29.276  5140  5140 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.f(BreventServer.java:436)
03-20 09:36:29.276  5140  5140 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.j(BreventServer.java:729)
03-20 09:36:29.276  5140  5140 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:207)
03-20 09:36:29.276  5140  5140 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.z(BreventServer.java:1424)
03-20 09:36:29.276  5140  5140 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1486)
03-20 09:36:29.276  5140  5140 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-20 09:36:29.276  5140  5140 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:276)
03-20 09:36:29.277  5140  5140 E AndroidRuntime: Error reporting crash
03-20 09:36:29.277  5140  5140 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-20 09:36:29.277  5140  5140 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-20 09:36:29.277  5140  5140 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:651)
03-20 09:36:29.277  5140  5140 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5341)
03-20 09:36:29.277  5140  5140 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:111)
03-20 09:36:29.277  5140  5140 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-20 09:36:29.277  5140  5140 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-20 09:36:28.000' -d -s BreventLoader BreventServer
03-20 09:36:28.755  5121  5121 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
03-20 09:36:28.783  5121  5121 D BreventLoader: libreader: /data/app/me.piebridge.brevent-1/lib/arm64/libreader.so
03-20 09:36:29.180  5140  5140 I BreventServer: Brevent Server 0.8.7-21-g6d57e2f started
03-20 09:36:29.189  5140  5140 I BreventServer: brevent user: 0, uid: 2000
03-20 09:36:29.190  5140  5140 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-20 09:36:29.218  5140  5140 I BreventServer: loading brevent list
03-20 09:36:29.221  5140  5140 I BreventServer: loading brevent conf
03-20 09:36:29.285  5121  5121 E BreventLoader: worker 5140 exited on signal 9
03-20 09:36:29.285  5121  5121 D BreventLoader: signal arrived, update: 0
03-20 09:36:29.286  5119  5119 D BreventLoader: worker 5121 exited with status 0
--- brevent end ---

0.8.7版本没问题

**Comment by liudongmiao** [comment]
作为一个 7.1 的系统，没有任何快捷设置，是不可思议的，晚上再说。
