### ISSUE TITLE
br0.8.7+21  （ root模式） 手机重启后如果立即解锁则黑域能够自启，如果等几分钟解锁，则不能够自启

### ISSUE THREAD

**Issue by bigbighill** [liudongmiao/Brevent#258]
br0.8.7+21    手机重启后如果立即解锁则黑域能够自启，如果等几分钟解锁，则不能够自启。有时黑域进程莫名挂了。
好奇怪，看了崩溃日志和黑域的服务日志也没有问题。
这个日志是重启后的立即解锁后能够自启，但过了一段时间后黑域进程挂了的完整日志。
完整日志这里不好上传，只好传网盘了。
小米5SP MIUI 8.2 andorid 6.0.1  已root supersu2.79
http://pan.baidu.com/s/1eS5Qiqe

**Comment by bigbighill** [comment]
这是重启系统后没有立即解锁，黑域没有能够自启，看andorid完整日志好像是启动，但后来被kill了，手动启动黑域后能正常使用。
崩溃日志：
`03-20 12:36:48.495 12829 12866 E AndroidRuntime: FATAL EXCEPTION: GoogleLocationService

03-20 12:36:48.495 12829 12866 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 12829

03-20 12:36:48.495 12829 12866 E AndroidRuntime: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.

03-20 12:36:48.495 12829 12866 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)

03-20 12:36:48.495 12829 12866 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)

03-20 12:36:48.495 12829 12866 E AndroidRuntime: 	at android.location.ILocationManager$Stub$Proxy.addGpsStatusListener(ILocationManager.java:741)

03-20 12:36:48.495 12829 12866 E AndroidRuntime: 	at android.location.LocationManager.addGpsStatusListener(LocationManager.java:1540)

03-20 12:36:48.495 12829 12866 E AndroidRuntime: 	at alrf.a(:com.google.android.gms:1035)

03-20 12:36:48.495 12829 12866 E AndroidRuntime: 	at alnq.b(:com.google.android.gms:5346)

03-20 12:36:48.495 12829 12866 E AndroidRuntime: 	at alnq.handleMessage(:com.google.android.gms:265)

03-20 12:36:48.495 12829 12866 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

03-20 12:36:48.495 12829 12866 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

03-20 12:36:48.495 12829 12866 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)

03-20 12:41:49.473 24220 24254 E AndroidRuntime: FATAL EXCEPTION: GoogleLocationService

03-20 12:41:49.473 24220 24254 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 24220

03-20 12:41:49.473 24220 24254 E AndroidRuntime: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.

03-20 12:41:49.473 24220 24254 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)

03-20 12:41:49.473 24220 24254 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)

03-20 12:41:49.473 24220 24254 E AndroidRuntime: 	at android.location.ILocationManager$Stub$Proxy.addGpsStatusListener(ILocationManager.java:741)

03-20 12:41:49.473 24220 24254 E AndroidRuntime: 	at android.location.LocationManager.addGpsStatusListener(LocationManager.java:1540)

03-20 12:41:49.473 24220 24254 E AndroidRuntime: 	at alrf.a(:com.google.android.gms:1035)

03-20 12:41:49.473 24220 24254 E AndroidRuntime: 	at alnq.b(:com.google.android.gms:5346)

03-20 12:41:49.473 24220 24254 E AndroidRuntime: 	at alnq.handleMessage(:com.google.android.gms:265)

03-20 12:41:49.473 24220 24254 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

03-20 12:41:49.473 24220 24254 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

03-20 12:41:49.473 24220 24254 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)

`
服务日志：
`--------- beginning of system

--------- beginning of main

03-20 12:33:57.446  6148  6148 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk

03-20 12:33:57.484  6148  6148 D BreventLoader: libreader: /data/app/me.piebridge.brevent-2/lib/arm64/libreader.so

03-20 12:33:57.784  6190  6190 I BreventServer: Brevent Server 0.8.7-21-g6d57e2f started

03-20 12:33:57.793  6190  6190 I BreventServer: brevent user: 0, uid: 0

03-20 12:33:57.794  6190  6190 I BreventServer: brevent data directory: /data/user/0/com.android.shell

03-20 12:33:57.925  6190  6190 I BreventServer: loading brevent list

03-20 12:33:57.932  6190  6190 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 26

03-20 12:33:57.932  6190  6190 I BreventServer: loading brevent conf

03-20 12:33:58.136  6190  6190 D BreventServer: check and brevent

03-20 12:33:58.317  6190  6190 D BreventServer: Force stop com.xiaomi.market(forceStop)

03-20 12:34:10.610  6190  6190 D BreventServer: sent first status

03-20 12:36:15.676  6190  6190 D BreventServer: check and brevent

03-20 12:36:15.817  6190  6190 D BreventServer: Force stop org.uguess.android.sysinfo.pro(forceStop)

--------- beginning of crash

03-20 12:37:10.519  6190  6201 D BreventServer: received feelgood

03-20 12:37:46.268  6190  6190 D BreventServer: check and brevent

03-20 12:38:40.024  6190  6190 D BreventServer: check and brevent

03-20 12:38:47.928  6190  6201 D BreventServer: received feelgood

03-20 12:38:49.326  6190  6190 D BreventServer: check and brevent

03-20 12:38:49.446  6190  6190 D BreventServer: Force stop org.uguess.android.sysinfo.pro(forceStop)

03-20 12:38:54.864  6190  6190 D BreventServer: check and brevent

03-20 12:39:55.329  6190  6190 D BreventServer: check and brevent

03-20 12:40:39.800  6190  6201 D BreventServer: received feelgood

03-20 12:40:41.806  6190  6190 D BreventServer: check and brevent

03-20 12:40:42.005  6190  6190 D BreventServer: Force stop org.uguess.android.sysinfo.pro(forceStop)

03-20 12:40:49.281  6190  6190 D BreventServer: check and brevent

03-20 12:41:11.136  6190  6201 D BreventServer: received feelgood

03-20 12:41:12.178  6190  6190 D BreventServer: check and brevent

03-20 12:41:19.067  6190  6190 D BreventServer: check and brevent

03-20 12:42:17.869  6190  6190 D BreventServer: check and brevent

`
完整日志：

http://pan.baidu.com/s/1slW8d6t

**Comment by liudongmiao** [comment]
这里没有相关信息，复制时去掉里面的空行吧，看起来痛苦。

**Comment by bigbighill** [comment]
可参考上面两个回贴里面的完整日志
