### ISSUE TITLE
br-v0.8.7+19包括到21adb命令激活失败

### ISSUE THREAD

**Issue by freedomchaos** [liudongmiao/Brevent#260]
锤子m1l，6.0系统，之前8.7的都能用，新的测试版adb激活不了，显示/system/bin/sh: adb -d shell /data/app/me.piebridge.brevent-2/lib/arm64/libbootstrap.so: not found，无法启用黑域

**Comment by wwqq777** [comment]
写错了，最后是libbrevent.so,你没看到not found吗

**Comment by liudongmiao** [comment]
就几个字母，还提供了复制，不会处理么？

**Comment by shadowwider** [comment]
这话说的太重了吧。没有进手机文件查看的人肯定不会知道正确的文件名是什么的。既然软件提供了复制当然会认为复制出来的不会错了。

**Comment by freedomchaos** [comment]
之前都是复制在电脑的记事本上，每次来粘贴就行，这次改了代码，好像也没提示，要是错都在我，也无话可说。

**Comment by liudongmiao** [comment]
@freedomchaos 现在这个版本，你可以复制到某个地方，然后执行。
比如 cp ... /data/local/tmp/brevent
然后，每次可以直接 adb shell /data/local/tmp/brevent

如果有更改，我会在发版说明中提到。
