### ISSUE TITLE
执行adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so报错

### ISSUE THREAD

**Issue by zhengyinxi** [liudongmiao/Brevent#261]
$ adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so
/system/bin/sh: syntax error: '(' unexpected

手机为sony xz， android 版本7.0,手机没有root过

**Comment by liudongmiao** [comment]
这个指令不是手机上执行的，而是电脑上执行的。

**Comment by kcschan** [comment]
手机上运行可能也可以
开一个terminal直接运行引号里的内容
“/data/app/me.piebridge.brevent-1/lib/arm64/libbootstrap.so”

**Comment by liudongmiao** [comment]
手机上不会有权限的，参照向导第二屏。你有权限另说。

**Comment by zhengyinxi** [comment]
是在pc上打开adb执行的

**Comment by Pason2C** [comment]
@kcschan 手机运行的前提是要有su权限。

**Comment by Yangli93** [comment]
@zhengyinxi 现在命令改了。
`adb -d shell /data/app/me.piebridge.brevent-2/lib/arm64/libbrevent.so`
