### ISSUE TITLE
S7E 7.0开启服务之后过一会儿再打开提示要ADB重新启动服务

### ISSUE THREAD

**Issue by wwqq777** [liudongmiao/Brevent#262]
日志如下：
--------- beginning of system
--------- beginning of main
03-20 16:26:50.957 13397 13397 I BreventServer: Brevent Server 0.8.7-21-g6d57e2f started
03-20 16:26:50.966 13397 13397 I BreventServer: brevent user: 0, uid: 2000
03-20 16:26:50.968 13397 13397 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-20 16:26:51.600 13397 13397 I BreventServer: loading brevent list
03-20 16:26:51.602 13397 13397 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 43
03-20 16:26:51.602 13397 13397 I BreventServer: loading brevent conf
03-20 16:26:51.755 13397 13397 D BreventServer: No field QS_TILES of type Ljava/lang/String; in class Landroid/provider/Settings$Secure; or its superclasses (declaration of 'android.provider.Settings$Secure' appears in /system/framework/framework.jar:classes2.dex)
03-20 16:26:51.766 13397 13397 D BreventServer: notification_cancel_all, tag: 2752, event: 6
03-20 16:26:51.768 13397 13397 D BreventServer: notification_panel_revealed, tag: 27500, event: 8
03-20 16:26:51.768 13397 13397 D BreventServer: notification_panel_hidden, tag: 27501, event: 9
03-20 16:26:51.768 13397 13397 D BreventServer: am_new_intent, tag: 30003, event: 2
03-20 16:26:51.769 13397 13397 D BreventServer: am_pause_activity, tag: 30013, event: 3
03-20 16:26:51.769 13397 13397 D BreventServer: am_proc_start, tag: 30014, event: 4
03-20 16:26:51.771 13397 13397 D BreventServer: am_switch_user, tag: 30041, event: 5
03-20 16:26:51.771 13397 13397 D BreventServer: am_focused_activity, tag: 30043, event: 1
03-20 16:26:51.775 13397 13397 D BreventServer: screen_toggled, tag: 70000, event: 7
03-20 16:26:51.866 13397 13397 D BreventServer: check and brevent
03-20 16:26:51.897 13397 13397 D BreventServer: widgets: {}
03-20 16:26:51.897 13397 13397 D BreventServer: running: {me.piebridge.brevent=12082, com.tencent.mobileqq=11651}
03-20 16:26:51.897 13397 13397 D BreventServer: recent: {me.piebridge.brevent, com.tencent.mobileqq, com.sec.android.app.launcher, com.android.systemui, com.samsung.android.sm_cn}
03-20 16:26:51.953 13397 13397 D BreventServer: No field QS_TILES of type Ljava/lang/String; in class Landroid/provider/Settings$Secure; or its superclasses (declaration of 'android.provider.Settings$Secure' appears in /system/framework/framework.jar:classes2.dex)
03-20 16:26:52.219 13397 13397 D BreventServer: com.samsung.android.app.taskedge depended by {com.samsung.android.app.cocktailbarservice}
03-20 16:26:52.219 13397 13397 D BreventServer: com.google.android.webview depended by {com.taobao.taobao}
03-20 16:26:52.219 13397 13397 D BreventServer: com.sec.android.app.quicktool depended by {com.samsung.android.app.cocktailbarservice}
03-20 16:26:52.219 13397 13397 D BreventServer: com.samsung.android.widgetapp.briefing depended by {com.samsung.android.app.cocktailbarservice}
03-20 16:26:52.219 13397 13397 D BreventServer: com.samsung.android.app.appsedge depended by {com.samsung.android.app.cocktailbarservice}
03-20 16:26:52.221 13397 13397 D BreventServer: back: {}
03-20 16:26:52.221 13397 13397 D BreventServer: service: {}
03-20 16:26:52.221 13397 13397 D BreventServer: blocking: {}
03-20 16:26:52.251 13397 13397 D BreventServer: vpn: null
03-20 16:26:52.252 13397 13397 D BreventServer: top: {me.piebridge.brevent}
03-20 16:26:52.252 13397 13397 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
03-20 16:26:52.252 13397 13397 D BreventServer: current: null
03-20 16:26:52.252 13397 13397 D BreventServer: unsafe: {}
03-20 16:26:52.252 13397 13397 D BreventServer: important: {com.orekie.search, com.microsoft.cortana/com.microsoft.bing.dss.SplashActivity, com.samsung.android.messaging, com.sec.android.inputmethod, com.sec.android.app.clockpackage, com.google.android.webview}
03-20 16:26:52.252 13397 13397 D BreventServer: trustAgents: {com.google.android.gms}
03-20 16:26:52.252 13397 13397 D BreventServer: final blocking: {}
03-20 16:26:52.252 13397 13397 D BreventServer: notifications: {}
03-20 16:26:52.252 13397 13397 D BreventServer: noRecent: {}
03-20 16:26:52.252 13397 13397 D BreventServer: foreground service: {}
03-20 16:26:52.566 13397 13397 D BreventServer: sent first status
03-20 16:28:31.423 13397 13397 E BreventServer: Don't receive answer from universe

**Comment by Pason2C** [comment]
根据Issue https://github.com/liudongmiao/Brevent/issues/74 ，可以尝试使用最新版adb工具。
下载地址：https://developer.android.com/studio/releases/platform-tools.html#download

**Comment by liudongmiao** [comment]
@wwqq777 你这个应该已经修了，等晚上发布，同 #255 
@Pason2C 这并不是同一个问题

**Comment by Pason2C** [comment]
@liudongmiao OK。看来今晚要发布0.9版本拉~

**Comment by wwqq777** [comment]
@liudongmiao 用了最新的0.9依然后有brevent服务挂掉的情况，日志如下：
C:\Users\wangq>adb -d logcat -d -s BreventServer BreventLoader
--------- beginning of system
--------- beginning of main
03-23 13:17:50.627  1250  1250 I BreventServer: Brevent Server 0.9 started
03-23 13:17:50.648  1250  1250 E BreventServer: version unmatched, running: 0.9, installed: 0.9-repack
03-23 13:17:50.654  1250  1250 I BreventServer: brevent user: 0, uid: 2000
03-23 13:17:50.659  1250  1250 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-23 13:17:51.340  1250  1250 I BreventServer: loading brevent list
03-23 13:17:51.347  1250  1250 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 42
03-23 13:17:51.347  1250  1250 I BreventServer: loading brevent conf
03-23 13:17:51.605  1250  1250 D BreventServer: No field QS_TILES of type Ljava/lang/String; in class Landroid/provider/Settings$Secure; or its superclasses (declaration of 'android.provider.Settings$Secure' appears in /system/framework/framework.jar:classes2.dex)
03-23 13:17:51.619  1250  1250 D BreventServer: notification_cancel_all, tag: 2752, event: 6
03-23 13:17:51.621  1250  1250 D BreventServer: notification_panel_revealed, tag: 27500, event: 8
03-23 13:17:51.621  1250  1250 D BreventServer: notification_panel_hidden, tag: 27501, event: 9
03-23 13:17:51.622  1250  1250 D BreventServer: am_new_intent, tag: 30003, event: 2
03-23 13:17:51.622  1250  1250 D BreventServer: am_pause_activity, tag: 30013, event: 3
03-23 13:17:51.623  1250  1250 D BreventServer: am_proc_start, tag: 30014, event: 4
03-23 13:17:51.624  1250  1250 D BreventServer: am_switch_user, tag: 30041, event: 5
03-23 13:17:51.624  1250  1250 D BreventServer: am_focused_activity, tag: 30043, event: 1
03-23 13:17:51.627  1250  1250 D BreventServer: screen_toggled, tag: 70000, event: 7
03-23 13:17:51.637  1250  1250 D BreventServer: check and brevent
03-23 13:17:51.713  1250  1250 D BreventServer: No field QS_TILES of type Ljava/lang/String; in class Landroid/provider/Settings$Secure; or its superclasses (declaration of 'android.provider.Settings$Secure' appears in /system/framework/framework.jar:classes2.dex)
03-23 13:17:51.821  1250  1250 D BreventServer: widgets: {}
03-23 13:17:51.821  1250  1250 D BreventServer: running: {com.weico.international=72332, com.tencent.mm=72709, me.piebridge.brevent=72602, com.baidu.tieba=70642, com.tencent.mobileqq=72597, com.sec.android.app.sbrowser=72184, com.jingdong.app.mall=72709, com.taobao.idlefish=72275, fm.jihua.kecheng=72709, com.taobao.taobao=72709, com.eg.android.AlipayGphone=72600}
03-23 13:17:51.821  1250  1250 D BreventServer: recent: {com.weico.international, com.sec.android.app.samsungapps, com.tencent.mm, me.piebridge.brevent, com.sec.android.gallery3d, com.ruanmei.ithome, com.baidu.tieba, com.tencent.mobileqq, com.sec.android.app.myfiles, com.sec.android.app.launcher, com.sec.android.app.sbrowser, com.sec.android.app.popupcalculator, com.jingdong.app.mall, com.taobao.idlefish, com.android.systemui, fm.jihua.kecheng, com.taobao.taobao, com.sec.android.app.camera, tv.danmaku.bili, com.eg.android.AlipayGphone}
03-23 13:17:51.913  1250  1250 D BreventServer: inactive for com.ruanmei.ithome: 0, timeout: 1800
03-23 13:17:51.913  1250  1250 D BreventServer: inactive for com.baidu.tieba: 2067, timeout: 1800
03-23 13:17:51.913  1250  1250 D BreventServer: inactive for com.taobao.idlefish: 434, timeout: 1800
03-23 13:17:51.914  1250  1250 D BreventServer: inactive for tv.danmaku.bili: 0, timeout: 1800
03-23 13:17:52.087  1250  1250 D BreventServer: com.samsung.android.app.taskedge depended by {com.samsung.android.app.cocktailbarservice}
03-23 13:17:52.087  1250  1250 D BreventServer: com.google.android.webview depended by {com.ruanmei.ithome, com.baidu.tieba, com.taobao.idlefish, com.taobao.taobao, com.eg.android.AlipayGphone}
03-23 13:17:52.087  1250  1250 D BreventServer: com.sec.android.app.quicktool depended by {com.samsung.android.app.cocktailbarservice}
03-23 13:17:52.087  1250  1250 D BreventServer: com.samsung.android.widgetapp.briefing depended by {com.samsung.android.app.cocktailbarservice}
03-23 13:17:52.087  1250  1250 D BreventServer: com.samsung.android.app.appsedge depended by {com.samsung.android.app.cocktailbarservice}
03-23 13:17:52.097  1250  1250 D BreventServer: back: {}
03-23 13:17:52.097  1250  1250 D BreventServer: service: {}
03-23 13:17:52.097  1250  1250 D BreventServer: blocking: {com.ruanmei.ithome, com.baidu.tieba, tv.danmaku.bili}
03-23 13:17:52.131  1250  1250 D BreventServer: vpn: null
03-23 13:17:52.131  1250  1250 D BreventServer: top: {me.piebridge.brevent}
03-23 13:17:52.131  1250  1250 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
03-23 13:17:52.131  1250  1250 D BreventServer: current: null
03-23 13:17:52.131  1250  1250 D BreventServer: unsafe: {}
03-23 13:17:52.131  1250  1250 D BreventServer: important: {com.orekie.search, com.microsoft.cortana/com.microsoft.bing.dss.SplashActivity, com.samsung.android.messaging, com.ospolice.packagedisablerpro, com.sec.android.inputmethod, com.sec.android.app.clockpackage, com.google.android.webview}
03-23 13:17:52.131  1250  1250 D BreventServer: trustAgents: {com.google.android.gms}
03-23 13:17:52.131  1250  1250 D BreventServer: final blocking: {com.ruanmei.ithome, com.baidu.tieba, tv.danmaku.bili}
03-23 13:17:52.131  1250  1250 D BreventServer: notifications: {}
03-23 13:17:52.131  1250  1250 D BreventServer: noRecent: {}
03-23 13:17:52.131  1250  1250 D BreventServer: foreground service: {}
03-23 13:17:52.132  1250  1250 D BreventServer: gcm: {}
03-23 13:17:52.358  1250  1250 D BreventServer: check and brevent, took 721ms
03-23 13:17:52.507  1250  1250 D BreventServer: sent first status
03-23 13:18:55.278  1250  1250 D BreventServer: checking feelgood
03-23 13:19:06.956  1250  1250 D BreventServer: checking feelgood
03-23 13:19:41.868  1250  1250 D BreventServer: checking feelgood
03-23 13:19:55.388  1250  1250 D BreventServer: checking feelgood
03-23 13:20:23.784  1250  1250 D BreventServer: checking feelgood
03-23 13:20:42.893  1250  1250 D BreventServer: checking feelgood
03-23 13:21:24.932  1250  1250 E BreventServer: Don't receive answer from universe//看起来一到这里就被杀

**Comment by liudongmiao** [comment]
@wwqq777 那时。理论上，要收到自己发出的事件。
如果事件收不到任何事件，黑域就会自己退出。

请检查你的系统上，是否关闭了系统日志，主要是事件日志。

`adb logcat -d -b events` 可查看事件日志

**Comment by wwqq777** [comment]
@liudongmiao 开启服务后把“开发者选项”关了貌似就不会被杀了，不知道是哪儿的问题
