### ISSUE TITLE
迷之无限获取进程，应该是一个具有偶发性的不知道能是能重复出现的bug

### ISSUE THREAD

**Issue by BadGuyX** [liudongmiao/Brevent#263]
刚刚打开黑域app被提示要adb一次，照做，结果adb之后黑域那个获取进程和提示adb操作两个画面不断重复交替出现，可惜那时我慌了神没录下来。。
这时我就想着都很多天没关过机，干脆就重启一波，顺便上来GitHub反馈一波问题，以下是日志（还有还有就是“adb logcat -b crash -d”这句话不知道为什么输入之后没反应，再交代一下，我的手机是三星s7e，官推的7.0）：

c:\adb>adb logcat -b main -d -s BreventLoader BreventServer
03-20 21:16:39.468 14181 14181 I BreventLoader: lib: /data/user/0/com.samsung.android.voc/brevent, loader: /data/user/0/com.samsung.android.voc/brevent/libloader.so
03-20 21:16:39.703 14181 14349 I BreventServer: Brevent Server 0.8.7 started
03-20 21:16:39.739 14181 14349 I BreventServer: brevent user: 0
03-20 21:16:39.741 14181 14349 I BreventServer: brevent data directory: /data/user/0/com.samsung.android.voc
03-20 21:16:40.635 14181 14349 I BreventServer: loading brevent list
03-20 21:16:40.642 14181 14349 I BreventServer: load /data/user/0/com.samsung.android.voc/me.piebridge.brevent.list, size: 11
03-20 21:16:40.642 14181 14349 I BreventServer: loading brevent conf
03-20 21:16:47.313 14181 14349 D BreventServer: sent first status
03-20 21:16:47.398 14181 14402 D BreventServer: received feelgood
03-20 21:16:48.164 14181 14402 D BreventServer: received feelgood
03-20 21:17:02.612 14181 14402 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags], events: [0, 162122614, 1679, com.teslacoilsw.launcher/.NovaLauncher, android.intent.action.MAIN, NULL, NULL, 272629760, com.jamworks.easyhome]
03-20 21:17:06.040 14181 14349 D BreventServer: check and brevent
03-20 21:17:12.142 14181 14349 D BreventServer: check and brevent
03-20 21:17:16.040 14181 14349 D BreventServer: check and brevent
03-20 21:18:55.970 14181 14349 D BreventServer: check and brevent
03-20 21:18:58.862 14181 14402 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags], events: [0, 17286276, 1689, eu.chainfire.perfmon/.LaunchActivity, android.intent.action.MAIN, NULL, NULL, 283115520, com.teslacoilsw.launcher]
03-20 21:19:00.193 14181 14402 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags], events: [0, 172427571, 1689, eu.chainfire.perfmon/.LaunchActivity, android.intent.action.MAIN, NULL, NULL, 283115520, com.teslacoilsw.launcher]
03-20 21:19:06.292 14181 14349 D BreventServer: check and brevent
03-20 21:19:10.824 14181 14349 D BreventServer: check and brevent
03-20 21:19:11.898 14181 14349 I BreventServer: remove package com.google.android.apps.forscience.whistlepunk
03-20 21:19:30.846 14181 14349 D BreventServer: check and brevent
03-20 21:20:32.737 14181 14349 D BreventServer: check and brevent
03-20 21:20:41.082 14181 14402 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags], events: [0, 208559553, 1679, com.teslacoilsw.launcher/.NovaLauncher, android.intent.action.MAIN, NULL, NULL, 272629760, com.jamworks.easyhome]
03-20 21:20:42.783 14181 14349 I BreventServer: remove package eu.chainfire.perfmon
03-20 21:20:43.365 14181 14402 D BreventServer: received feelgood
03-20 21:20:44.260 14181 14349 D BreventServer: check and brevent

**Comment by liudongmiao** [comment]
试试最新测试版：https://piebridge.me/br/next/
