### ISSUE TITLE
8.7 B26 黑域进程经常被杀

### ISSUE THREAD

**Issue by bigbighill** [liudongmiao/Brevent#265]
已经在安全中心给了自启权限，神隐模式也给了最大权限黑域进程经常被杀。
查看了日志：
03-21 15:29:00.022 I/ActivityManager(1614) :	Killing 9294:me.piebridge.brevent/u0a190 (adj 4): empty #17
03-21 16:51:15.868 I/ActivityManager(1614) :	Killing 17806:me.piebridge.brevent/u0a190 (adj 4): empty #17
03-21 17:40:26.179 I/ActivityManager(1614) :	Killing 8387:me.piebridge.brevent/u0a190 (adj 4): empty #17
03-21 18:22:12.036 I/ActivityManager(1614) :	Killing 13147:me.piebridge.brevent/u0a190 (adj 4): stop me.piebridge.brevent

http://pan.baidu.com/s/1o8HLm10

**Comment by liudongmiao** [comment]
这个无所谓的，只是一个界面，界面没有无关系。

真正起作用的是 brevent_daemon 与 brevent_server，这两个进程，ActivityManager 不会也不能杀掉它。

**Comment by bigbighill** [comment]
原来如此，刚刚在终端用top看了下 brevent_daemon bervent_server 还在
