### ISSUE TITLE
0.8.7-29 影响ambient display

### ISSUE THREAD

**Issue by tickeyding** [liudongmiao/Brevent#268]
一加3T，OxygenOs 4.1.0 (7.1.1)，安装0.8.7-29后ambient display不定期出现bug，即息屏状态下有推送或信息进来会直接点亮彩屏，而且内容呈现透明化，难以看清，而不是amoled屏的黑白效果。记得之前0.8.7的某一个测试版也出现此问题。

**Comment by liudongmiao** [comment]
目前没有稳定日志，暂时不处理。
如果你能稳定重现，请带上日志提交反馈。

由于也无法稳定重现，所以去掉了针对这个问题的可能优化方案。

**Comment by tickeyding** [comment]
Sorry，已经确认不是黑域的锅。是OxygenOS 4.1.0的bug
