### ISSUE TITLE
安卓5.1 X86框架Adb执行提示错误

### ISSUE THREAD

**Issue by Kotori-0912** [liudongmiao/Brevent#270]
WARNING: linker: /data/app/me.piebridge.brevent-1/lib/x86/libbrevent.so: unused DT entry: type 0x6ffffffe arg 0x944
WARNING: linker: /data/app/me.piebridge.brevent-1/lib/x86/libbrevent.so: unused DT entry: type 0x6fffffff arg 0x1
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-22 14:45:46.000' -d
E/AndroidRuntime( 4109): *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
E/AndroidRuntime( 4109): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/me.piebridge.brevent-1/lib/x86/libreader.so" is 32-bit instead of 64-bit
E/AndroidRuntime( 4109):        at java.lang.Runtime.load(Runtime.java:331)
E/AndroidRuntime( 4109):        at java.lang.System.load(System.java:981)
E/AndroidRuntime( 4109):        at me.piebridge.LogReader.<clinit>(LogReader.java:14)
E/AndroidRuntime( 4109):        at me.piebridge.LogReader.readEvents(Native Method)
E/AndroidRuntime( 4109):        at me.piebridge.brevent.server.a.run(BreventEvent.java:49)
E/AndroidRuntime( 4109):        at java.lang.Thread.run(Thread.java:818)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-22 14:45:46.000' -d -s BreventLoader BreventServer
D/BreventLoader( 4093): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader( 4093): libreader: /data/app/me.piebridge.brevent-1/lib/x86/libreader.so
I/BreventServer( 4109): Brevent Server 0.9 started
I/BreventServer( 4109): brevent user: 0, uid: 2000
I/BreventServer( 4109): brevent data directory: /data/data/com.android.shell
I/BreventServer( 4109): loading brevent list
I/BreventServer( 4109): loading brevent conf
D/BreventServer( 4109): check and brevent
E/BreventLoader( 4093): worker 4109 exited on signal 9
D/BreventLoader( 4093): signal arrived, update: 0
D/BreventLoader( 4091): worker 4093 exited with status 0

**Comment by aviraxp** [comment]
所以说，把x86-64支持加回来吧。。。

**Comment by liudongmiao** [comment]
@Kotori-0912 你确定不是在虚拟上运行？

@aviraxp 确切的说，这是支持你那个惹的祸。本来我写死路径，运行得好好的，结果你那个非不认，我就用 app_process，如果 64 位的话，默认就是 64 位。

**Comment by liudongmiao** [comment]
@Kotori-0912 还有一个办法

1. `ln -sf /system/bin/app_process32 /data/local/tmp/app_process`
2. `PATH=/data/local/tmp:$PATH /path/to/libbrevent.so`

**Comment by Kotori-0912** [comment]
@liudongmiao 并不是虚拟机，我的平板电脑是使用X86框架的，而且内核也是奇怪的X86-64

**Comment by liudongmiao** [comment]
@Kotori-0912 你按我上面提到的处理下，能执行不？

**Comment by Kotori-0912** [comment]
@liudongmiao PATH那一段执行不了,ln链接没问题

**Comment by liudongmiao** [comment]
哦，那就先

export PATH=/data/local/tmp:$PATH

然后执行

/path/to/libbrevent.so

**Comment by Kotori-0912** [comment]
@liudongmiao  export PATH提示成功，但是执行/path/to/libbrevent.so提示Not Found和之前PATH=/data/local/tmp:$PATH /path/to/libbrevent.so执行后一样是提示NotFound

**Comment by liudongmiao** [comment]
你 not found 肯定不是这个问题了，是路径不对
