### ISSUE TITLE
一加3T h2os open 3 based on Android 7.1.1

### ISSUE THREAD

**Issue by iVeego** [liudongmiao/Brevent#272]
使用supersu 的systemless的方式root.
0.9版本的黑域，打开了允许root方式运行。
重启手机之后，黑域服务不会自动运行，需要手动打开一下app，点击一下使用root方式可以正常开启。

**Comment by liudongmiao** [comment]
不对 root 方式提供任何形式的支持。

你可以自查下： (adb logcat -s BreventUI)
1. 日志中，是否有启动的记录，如果没有，请看下是否有其它应用阻断它启动
2. 日志中，是否有启动但失败的记录

**Comment by iVeego** [comment]
多谢！

**Comment by iVeego** [comment]
C:\Android>adb logcat -s BreventUI
--------- beginning of system
--------- beginning of crash
--------- beginning of main
03-22 18:16:22.555  8430  8446 D BreventUI: request status
03-22 18:16:22.557  8430  8446 E BreventUI: cannot connect to ip6-localhost/::1:59526
03-22 18:16:25.560  8430  8446 D BreventUI: retry request status
03-22 18:16:25.564  8430  8446 E BreventUI: cannot connect to ip6-localhost/::1:59526
03-22 18:16:28.566  8430  8446 D BreventUI: retry request status
03-22 18:16:28.570  8430  8446 E BreventUI: cannot connect to ip6-localhost/::1:59526
03-22 18:16:30.419  8430  8457 D BreventUI: onHandleIntent, action: me.piebridge.brevent.intent.action.BREVENT, started: false
03-22 18:16:30.420  8430  8457 D BreventUI: startBrevent: /data/app/me.piebridge.brevent-1/lib/arm64/libbrevent.so
03-22 18:16:31.573  8430  8446 D BreventUI: retry request status
03-22 18:16:31.575  8430  8446 E BreventUI: cannot connect to ip6-localhost/::1:59526
03-22 18:16:32.705  8430  8446 D BreventUI: received response
03-22 18:16:32.724  8430  8446 D BreventUI: important: {com.camel.corp.universalcopy=10, com.xinshuru.inputmethod=0, com.teslacoilsw.launcher=11, com.oneplus.deskclock=1, net.dinglisch.android.taskerm=11, com.lastpass.lpandroid=10, com.android.mms=2, se.dirac.acs=4, com.oneplus=4, =7, com.zncm.dminter.mmhelper=11, com.google.android.webview=8, com.google.android.gms=11, com.android.systemui=4}
03-22 18:16:32.727  8430  8446 D BreventUI: favorite: {com.oasisfeng.greenify=13, com.teslacoilsw.launcher=13, com.android.providers.downloads=13, org.kman.AquaMail=13, com.ttxapps.onesyncv2=13, in.zhaoj.shadowsocksr=13, net.dinglisch.android.taskerm=13, com.nll.acr=13, com.tencent.mm=13, com.sdu.didi.psnger=13, com.lastpass.lpandroid=13, com.teslacoilsw.launcher.prime=13, rikka.smscodehelper=13, com.google.android.syncadapters.calendar=13, com.asksven.betterbatterystats=13, com.nll.acr.license=13, org.kman.AquaMail.UnlockerMarket=13, eu.chainfire.supersu.pro=13, com.suyashsrijan.forcedoze=13, com.cygery.toggledata.xda=13, com.alibaba.android.rimet=13, com.pushbullet.android=13, eu.chainfire.supersu=13, com.vibhinna.cpuspyfree=13}
03-22 18:16:32.758  8430  8446 D BreventUI: gcm: {com.ifttt.ifttt, com.teslacoilsw.launcher, org.kman.AquaMail, com.ttxapps.onesyncv2, com.android.vending, com.nll.acr, com.tencent.mm, com.lastpass.lpandroid, com.oasisfeng.island, com.google.android.gms, com.google.android.gsf, rikka.appops, com.google.android.apps.photos, com.google.android.calendar, com.pushbullet.android}
03-22 18:16:40.772  8430  8446 D BreventUI: important: {com.camel.corp.universalcopy=10, com.xinshuru.inputmethod=0, com.teslacoilsw.launcher=11, com.oneplus.deskclock=1, net.dinglisch.android.taskerm=11, com.lastpass.lpandroid=10, com.android.mms=2, se.dirac.acs=4, com.oneplus=4, =7, com.zncm.dminter.mmhelper=11, com.google.android.webview=8, com.google.android.gms=11, com.android.systemui=4}
03-22 18:16:40.774  8430  8446 D BreventUI: favorite: {com.oasisfeng.greenify=13, com.teslacoilsw.launcher=13, com.android.providers.downloads=13, org.kman.AquaMail=13, com.ttxapps.onesyncv2=13, in.zhaoj.shadowsocksr=13, net.dinglisch.android.taskerm=13, com.nll.acr=13, com.tencent.mm=13, com.sdu.didi.psnger=13, com.lastpass.lpandroid=13, com.teslacoilsw.launcher.prime=13, rikka.smscodehelper=13, com.google.android.syncadapters.calendar=13, com.asksven.betterbatterystats=13, com.nll.acr.license=13, org.kman.AquaMail.UnlockerMarket=13, eu.chainfire.supersu.pro=13, com.suyashsrijan.forcedoze=13, com.cygery.toggledata.xda=13, com.alibaba.android.rimet=13, com.pushbullet.android=13, eu.chainfire.supersu=13, com.vibhinna.cpuspyfree=13}
03-22 18:16:40.809  8430  8446 D BreventUI: gcm: {com.ifttt.ifttt, com.teslacoilsw.launcher, org.kman.AquaMail, com.ttxapps.onesyncv2, com.android.vending, com.nll.acr, com.tencent.mm, com.lastpass.lpandroid, com.oasisfeng.island, com.google.android.gms, com.google.android.gsf, rikka.appops, com.google.android.apps.photos, com.google.android.calendar, com.pushbullet.android}
03-22 18:16:41.891  8430  8457 D BreventUI: checking...brevent_server started, pid: 8481
03-22 18:16:41.892  8430  8457 D BreventUI: checking for stable...........ok
03-22 18:16:41.892  8430  8457 D BreventUI:
03-22 18:16:41.892  8430  8457 D BreventUI: if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
03-22 18:16:41.892  8430  8457 D BreventUI: for crash log: logcat -b crash -d
03-22 18:16:41.892  8430  8457 D BreventUI: for brevent log: logcat -b main -d -s BreventLoader BreventServer

**Comment by iVeego** [comment]
如果有时间的话，麻烦看下。多多感谢。

**Comment by liudongmiao** [comment]
要更早之前的数据。

我本人不对 root 模式的自启进行任何形式的保证。

**Comment by iVeego** [comment]
搞定了！我忘了一件事情，H2OS有自己的自启动管理，我忘记给黑域自启动权限了。现在已经OK。非常感谢。
