### ISSUE TITLE
Crash on Nexus5x running Android O.

### ISSUE THREAD

**Issue by OzzyThorne** [liudongmiao/Brevent#274]
D:\Documents\infotech\bullhead\adb\platform-tools>adb -d shell
e.piebridge.brevent-ZswL8u8Y37QTtOTMW2D3jQ==/lib/arm64/libbrevent.so      <
checking....brevent_server started, pid: 15317
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-22 17:39:37.000' -d
03-22 17:39:39.363 15317 15317 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-22 17:39:39.363 15317 15317 E AndroidRuntime: java.lang.NoSuchFieldError: No field RECENT_IGNORE_HOME_STACK_TASKS of type I in class Landroid/app/ActivityManager; or its superclasses (declaration of 'android.app.ActivityManager' appears in /system/framework/framework.jar)
03-22 17:39:39.363 15317 15317 E AndroidRuntime:        at me.piebridge.brevent.a.a.b(HideApiOverride.java:91)
03-22 17:39:39.363 15317 15317 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<clinit>(BreventServer.java:162)
03-22 17:39:39.363 15317 15317 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-22 17:39:39.363 15317 15317 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
03-22 17:39:39.364 15317 15317 E AndroidRuntime: Error reporting crash
03-22 17:39:39.364 15317 15317 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:692)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:56)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:3926)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:3924)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at android.app.ActivityManager.getService(ActivityManager.java:3919)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:115)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
03-22 17:39:39.364 15317 15317 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-22 17:39:37.000' -d -s BreventLoader BreventServer
03-22 17:39:38.847 15261 15261 D BreventLoader: loader path: /data/app/me.piebridge.brevent-ZswL8u8Y37QTtOTMW2D3jQ==/base.apk
03-22 17:39:38.915 15261 15261 D BreventLoader: libreader: /data/app/me.piebridge.brevent-ZswL8u8Y37QTtOTMW2D3jQ==/lib/arm64/libreader.so
03-22 17:39:39.378 15261 15261 E BreventLoader: worker 15317 exited on signal 9
03-22 17:39:39.378 15261 15261 D BreventLoader: signal arrived, update: 0
03-22 17:39:39.379 15260 15260 D BreventLoader: worker 15261 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by aviraxp** [comment]
估计在O放出源码之前，都不可能支持。

**Comment by liudongmiao** [comment]
可以的，反编译看下就好。。。

**Comment by aviraxp** [comment]
关键是怕O的api还有进一步的调整。

**Comment by liudongmiao** [comment]
这个还好，重要的基本不会变。就像这个，是个可选的 flags

**Comment by liudongmiao** [comment]
@aviraxp 确实有重要的 api 变更。

1. settings 之前是个 jar (app_process ....)，现在是个 shell command (cmd settings ...)
这个已经解决

2. 没有了优先通知这一项，基本意味着我得来个配置文件，允许通知

3. 没有 5.1 - 7.1 一直支持的 `am_focused_activity`
这个也可以绕过，但比较麻烦，一旦绕过，就可以支持 5.0 了

**Comment by liudongmiao** [comment]
已经支持，绕过了 settings，绕过了 优先通知，绕过了 am_focused_activity
