### ISSUE TITLE
Nexus 5X 安卓O开发者预览版无法开启

### ISSUE THREAD

**Issue by windxiaoli** [liudongmiao/Brevent#279]
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-23 07:23:04.000' -d
03-23 07:23:06.727 24059 24059 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-23 07:23:06.727 24059 24059 E AndroidRuntime: java.lang.NoSuchFieldError: No field RECENT_IGNORE_HOME_STACK_TASKS of type I in class Landroid/app/ActivityManager; or its superclasses (declaration of 'android.app.ActivityManager' appears in /system/framework/framework.jar)
03-23 07:23:06.727 24059 24059 E AndroidRuntime:        at me.piebridge.brevent.a.a.b(HideApiOverride.java:91)
03-23 07:23:06.727 24059 24059 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<clinit>(BreventServer.java:162)
03-23 07:23:06.727 24059 24059 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-23 07:23:06.727 24059 24059 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
03-23 07:23:06.728 24059 24059 E AndroidRuntime: Error reporting crash
03-23 07:23:06.728 24059 24059 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:692)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:56)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:3926)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:3924)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at android.app.ActivityManager.getService(ActivityManager.java:3919)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:115)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
03-23 07:23:06.728 24059 24059 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-23 07:23:04.000' -d -s BreventLoader BreventServer
03-23 07:23:05.824 24034 24034 D BreventLoader: loader path: /data/app/me.piebridge.brevent-gqmvIdGLIIK5NUY_24hXhg==/base.apk
03-23 07:23:05.869 24034 24034 D BreventLoader: libreader: /data/app/me.piebridge.brevent-gqmvIdGLIIK5NUY_24hXhg==/lib/arm64/libreader.so
03-23 07:23:06.748 24034 24034 E BreventLoader: worker 24059 exited on signal 9
03-23 07:23:06.748 24034 24034 D BreventLoader: signal arrived, update: 0
03-23 07:23:06.749 24033 24033 D BreventLoader: worker 24034 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
这个字段改名了，叫 `RECENT_IGNORE_HOME_AND_RECENTS_STACK_TASKS`，值和原来的一样。

**Comment by liudongmiao** [comment]
#274

**Comment by liudongmiao** [comment]
已经支持。
