### ISSUE TITLE
cannot listen port

### ISSUE THREAD

**Issue by scodec121310** [liudongmiao/Brevent#281]
C:\Program Files (x86)\WugFresh Development\Nexus Root Toolkit\data>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbrevent.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-23 13:17:28.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-23 13:17:28.000' -d -s BreventLoader BreventServer
03-23 13:17:29.671 12847 12847 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
03-23 13:17:29.707 12847 12847 D BreventLoader: libreader: /data/app/me.piebridge.brevent-1/lib/arm64/libreader.so
03-23 13:17:30.466 12860 12860 I BreventServer: Brevent Server 0.9 started
03-23 13:17:30.479 12860 12860 I BreventServer: brevent user: 0, uid: 2000
03-23 13:17:30.481 12860 12860 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-23 13:17:30.613 12860 12860 I BreventServer: loading brevent list
03-23 13:17:30.615 12860 12860 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 6
03-23 13:17:30.616 12860 12860 I BreventServer: loading brevent conf
03-23 13:17:30.616 12860 12860 E BreventServer: Did you run as root, then run as shell?
03-23 13:17:30.647 12847 12847 E BreventLoader: worker 12860 exited with status 1
03-23 13:17:30.647 12847 12847 D BreventLoader: signal arrived, update: 0
03-23 13:17:30.652 12845 12845 D BreventLoader: worker 12847 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by scodec121310** [comment]
1.delete all file in  /data/user_de/0/com.android.shell/ 
2.run script again

**Comment by liudongmiao** [comment]
Yes, I think the message is very clear:
> Did you run as root, then run as shell?
