### ISSUE TITLE
无法开启黑域，之前成功过，这次重启之后发现问下，谢谢

### ISSUE THREAD

**Issue by lslovemomo** [liudongmiao/Brevent#282]
E:\adb\platform-tools>adb -d shell /data/app/me.piebridge.brevent-2/lib/arm64/li
bbrevent.so
/system/bin/sh: /data/app/me.piebridge.brevent-2/lib/arm64/libbrevent.so: not fo
und

**Comment by liudongmiao** [comment]
not found，就是你敲错了
