### ISSUE TITLE
TTS服务能不能不强杀

### ISSUE THREAD

**Issue by wuchjun** [liudongmiao/Brevent#283]
TTS加入黑域列表后经常被强杀导致语音播放断断续续和停止，只选择只休眠不强行停止也会强杀，希望在唤醒时不要强杀，没有调用的时候再休眠就好

**Comment by liudongmiao** [comment]
不要加入黑域吧

**Comment by uhy** [comment]
TTS 又没有自启特性，加了黑域有什么用？
