### ISSUE TITLE
adb命令无法开启权限

### ISSUE THREAD

**Issue by HorizonChan** [liudongmiao/Brevent#285]
你好，我无法用adb命令开启黑域权限，设备为诺基亚N1，系统为5.1.1，x86版本。bug report附在下面。
>>> logcat -b main -t '03-23 19:17:02.000' -d -s BreventLoader BreventServer
D/BreventLoader(16085): worker 26915 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): worker 26913 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(26938): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(26938): libreader: /data/app/me.piebridge.brevent-1/lib/x86/libreader.so
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
I/BreventServer(26955): Brevent Server 0.9 started
I/BreventServer(26955): brevent user: 0, uid: 2000
I/BreventServer(26955): brevent data directory: /data/data/com.android.shell
I/BreventServer(26955): loading brevent list
I/BreventServer(26955): loading brevent conf
D/BreventServer(26955): check and brevent
E/BreventLoader(26938): worker 26955 exited on signal 9
D/BreventLoader(26938): signal arrived, update: 0
D/BreventLoader(26936): worker 26938 exited with status 0
D/BreventLoader(29336): worker 26981 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): worker 26983 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): worker 27046 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): worker 27048 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): worker 27098 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): worker 27097 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): worker 27146 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): worker 27148 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): worker 27193 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): worker 27198 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): worker 27242 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): worker 27248 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): worker 27294 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): worker 27299 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): worker 27344 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): worker 27349 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): worker 27394 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): worker 27399 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): worker 27449 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): worker 27448 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): worker 27494 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(29336): worker 27499 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): worker 27550 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): worker 27551 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): worker 27601 exited with status 0
D/BreventLoader(29336): signal arrived, update: 1
D/BreventLoader(16085): worker 27600 exited with status 0
D/BreventLoader(16085): signal arrived, update: 1
D/BreventLoader(16085): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(29336): loader path: /data/app/me.piebridge.brevent-1/base.apk
--- brevent end ---

**Comment by liudongmiao** [comment]
@HorizonChan 电脑上装个 teamviewer，然后邮件我帐号与密码 (br@piebridge.me)

**Comment by HorizonChan** [comment]
你好，在昨天的版本更新后，此问题已经解决。感谢。

**Comment by liudongmiao** [comment]
好的~
