### ISSUE TITLE
sonyZ5（E6683）成功开启黑域之后连wifi没有网络，日志在这里不知道对不对

### ISSUE THREAD

**Issue by yovewoo** [liudongmiao/Brevent#288]
03-24 14:41:28.721 14900 14900 I BreventLoader: lib: /data/user/0/com.sonymobile
.enterprise.installation/brevent, loader: /data/user/0/com.sonymobile.enterprise
.installation/brevent/libloader.so
03-24 14:41:28.800 14900 14915 I BreventServer: Brevent Server 0.8.7 started
03-24 14:41:28.816 14900 14915 I BreventServer: brevent user: 0
03-24 14:41:28.818 14900 14915 I BreventServer: brevent data directory: /data/us
er/0/com.sonymobile.enterprise.installation
03-24 14:41:28.918 14900 14915 I BreventServer: loading brevent list
03-24 14:41:28.923 14900 14915 I BreventServer: load /data/user/0/com.sonymobile
.enterprise.installation/me.piebridge.brevent.list, size: 41
03-24 14:41:28.923 14900 14915 I BreventServer: loading brevent conf
03-24 14:41:29.327 14900 14915 D BreventServer: sent first status
03-24 14:41:29.332 14900 14916 D BreventServer: received feelgood
03-24 14:41:43.101 14900 14915 D BreventServer: check and brevent
03-24 14:41:43.492 14900 14915 D BreventServer: Force stop com.youku.phone(noRec
ent)
03-24 14:41:43.532 14900 14915 D BreventServer: Force stop com.xiachufang(noRece
nt)
03-24 14:41:43.600 14900 14915 D BreventServer: Force stop net.luoo.LuooFM(noRec
ent)
03-24 14:41:43.697 14900 14915 D BreventServer: Force stop com.myzaker.ZAKER_Pho
ne(foreground service no notification)
03-24 14:41:43.728 14900 14915 D BreventServer: Force stop com.snda.wifilocating
(noRecent)
03-24 14:41:43.787 14900 14915 D BreventServer: Force stop com.ricebook.highgard
en(noRecent)
03-24 14:41:43.852 14900 14915 D BreventServer: Force stop com.microsoft.cortana
(noRecent)
03-24 14:41:43.964 14900 14915 D BreventServer: Force stop com.sina.weibo(noRece
nt)
03-24 14:41:44.057 14900 14915 D BreventServer: Force stop com.taobao.taobao(for
eground service no notification)
03-24 14:41:44.177 14900 14915 D BreventServer: Force stop com.eg.android.Alipay
Gphone(foreground service no notification)
03-24 14:42:04.943 14900 14915 D BreventServer: check and brevent
03-24 14:42:10.116 14900 14916 D BreventServer: received feelgood
03-24 14:42:22.305 14900 14915 D BreventServer: check and brevent
03-24 14:42:28.027 14900 14915 D BreventServer: check and brevent
03-24 14:42:33.602 14900 14915 D BreventServer: check and brevent
03-24 14:42:38.736 14900 14915 D BreventServer: check and brevent
03-24 14:43:10.198 14900 14916 D BreventServer: received feelgood
03-24 14:43:17.501 14900 14915 D BreventServer: Can't setStopped for com.fihtdc.
note(ignore)
03-24 14:43:17.505 14900 14915 D BreventServer: Can't setStopped for com.iflytek
.recinbox(ignore)
03-24 14:43:21.243 14900 14915 D BreventServer: Can't setStopped for cn.ibuka.ma
nga.ui(ignore)
03-24 14:43:35.579 14900 14916 D BreventServer: received feelgood
03-24 14:43:40.795 14900 14915 D BreventServer: check and brevent
03-24 14:43:43.369 14900 14916 D BreventServer: received feelgood
03-24 14:43:50.935 14900 14915 D BreventServer: check and brevent
03-24 14:43:54.019 14900 14916 D BreventServer: received feelgood
03-24 14:43:59.270 14900 14915 D BreventServer: check and brevent
03-24 14:44:08.184 14900 14916 D BreventServer: received feelgood
03-24 14:44:18.876 14900 14915 D BreventServer: check and brevent
03-24 14:44:24.276 14900 14915 I BreventServer: reset home tid to 3602
03-24 14:44:25.201 14900 14915 D BreventServer: Can't setStopped for com.myzaker
.ZAKER_Phone(ignore)
03-24 14:44:25.214 14900 14915 D BreventServer: Can't setStopped for com.myzaker
.ZAKER_Phone(ignore)
03-24 14:44:27.066 14900 14915 D BreventServer: check and brevent
03-24 14:44:29.152 14900 14915 D BreventServer: Can't setStopped for com.myzaker
.ZAKER_Phone(ignore)
03-24 14:44:29.484 14900 14915 D BreventServer: Can't setStopped for com.myzaker
.ZAKER_Phone(ignore)
03-24 14:44:32.364 14900 14915 D BreventServer: check and brevent
03-24 14:44:32.700 14900 14915 D BreventServer: Force stop com.eg.android.Alipay
Gphone(service)
03-24 14:44:38.770 14900 14915 D BreventServer: Can't setStopped for com.myzaker
.ZAKER_Phone(ignore)
03-24 14:44:39.051 14900 14915 D BreventServer: check and brevent
03-24 14:44:39.315 14900 14915 D BreventServer: Force stop com.ricebook.highgard
en(service)
03-24 14:44:39.418 14900 14915 D BreventServer: Force stop com.eg.android.Alipay
Gphone(service)
03-24 14:44:55.755 14900 14915 D BreventServer: Can't setStopped for com.myzaker
.ZAKER_Phone(ignore)
03-24 14:44:57.844 14900 14915 D BreventServer: Can't setStopped for com.myzaker
.ZAKER_Phone(ignore)
03-24 14:44:59.078 14900 14915 D BreventServer: Can't setStopped for com.myzaker
.ZAKER_Phone(ignore)
03-24 14:45:02.892 14900 14916 D BreventServer: received feelgood
03-24 14:45:09.958 14900 14915 D BreventServer: check and brevent
03-24 14:45:14.573 14900 14915 D BreventServer: check and brevent
03-24 14:45:37.671 14900 14915 D BreventServer: Can't setStopped for com.myzaker
.ZAKER_Phone(ignore)
03-24 14:45:38.817 14900 14915 D BreventServer: Can't setStopped for com.myzaker
.ZAKER_Phone(ignore)
03-24 14:46:34.806 14900 14915 D BreventServer: check and brevent
03-24 14:48:02.344 14900 14916 D BreventServer: received feelgood
03-24 14:48:15.947 14900 14915 D BreventServer: Can't setStopped for com.sevente
enmiles.sketch(ignore)
03-24 14:48:23.047 14900 14915 D BreventServer: check and brevent
03-24 14:48:23.272 14900 14915 D BreventServer: Force stop com.alibaba.android.r
imet(service)

**Comment by yovewoo** [comment]
可以连上wifi，图标带感叹号，没有网络。

**Comment by liudongmiao** [comment]
你带叹号，真的与我无关啊。

https://www.noisyfox.cn/android-captive-portal.html

**Comment by yovewoo** [comment]
额......可是我重启之后不运行黑域就没有问题啊，而且不是感叹号的关系，主要是上不了网

**Comment by yovewoo** [comment]
虽然不知道为什么，但是照着上面就弄好了，谢谢大佬~
