### ISSUE TITLE
三星s7 root模式开启黑域，导致短信自动闪退

### ISSUE THREAD

**Issue by benworushi** [liudongmiao/Brevent#289]
三星s7  7.0系统，root模式开启
短信相关并没被加入黑域，闪退情景：
1：开短信，然后随意点击某条短信，直接闪退
2：开短信，然后随意点开某条短信，点击短信输入，直接闪退
    
[保持通知关闭.txt](https://github.com/liudongmiao/Brevent/files/867292/default.txt)
[保持通知开启 .txt](https://github.com/liudongmiao/Brevent/files/867291/default.txt)

**Comment by benworushi** [comment]
刚刚试了下，不仅仅短信，联系人，电话都自动闪退。。

**Comment by chm512512** [comment]
play版的？

**Comment by chm512512** [comment]
@benworushi play的？！捐赠没？！第二个里面写的没有开root。你又说开了。要不你换个酷安版再试试？！短信好像是禁用了什么服务，全部都不黑域也闪退吗？！
热心人回复～

**Comment by liudongmiao** [comment]
>  Force stop com.android.providers.userdictionary(noRecent)

没事不要黑域这个。你没事，黑域系统应用干啥。
开启黑域后，卸载它，然后重新安装。

**Comment by benworushi** [comment]
@liudongmiao 我都试过，把黑域数据全清，就只是root开启，所有应用和系统应用都没加入黑域，短信一样就会闪退。我冻结的系统程序是按着之前用的阻止运行来的，不会出问题的。后来判断了下可能是升级到了7.0后，第三方rom问题。我重刷了另外一个rom，现在可以正常用了。你的阻止运行我可以说是第一批使用的用户，当时还给你反馈过bug的，可能你不记得了。

**Comment by benworushi** [comment]
@chm512512  酷安和play版都试了，作者的应用我都捐赠过。2个日志都是开启root的，只是一个开了保留通知选项，一个没开。当然现在问题解决了，谢谢你的热心回复。

**Comment by liudongmiao** [comment]
怎么解决的？

**Comment by chm512512** [comment]
@liudongmiao  上面说了换了ROM…哈哈哈

**Comment by benworushi** [comment]
@liudongmiao 换了rom，没办法了，不想用什么绿色守护，现在用着完美，跟阻止运行一个样了！！👍
