### ISSUE TITLE
8.6开始出现异常

### ISSUE THREAD

**Issue by chenbuhtig** [liudongmiao/Brevent#290]
8.6开始黑域推出键不能浅度休眠
9.0开始黑域不能强行停止（具体版本不知道保持8.5一段时间了，强行停止是划掉之后在黑域里看应用已经停止了返回桌面再次打开黑域应用又出现了）
手机是乐视max2刷的LineageOS下载地址是https://download.lineageos.org/x2

是不是这个命令？adb -d logcat -d -s BreventServer BreventLoader

C:\platform-tools>adb -d logcat -d -s BreventServer BreventLoader
--------- beginning of system
--------- beginning of main
03-24 17:38:50.059  4526  4537 D BreventServer: check and brevent
03-24 17:38:50.102  4526  4537 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-24 17:38:50.120  4526  4537 D BreventServer: Force stop org.cyanogenmod.theme.chooser2(noRecent)
03-24 17:38:50.121  4526  4537 D BreventServer: Can't setStopped for com.tencent.mm(ignore)
03-24 17:38:50.136  4526  4537 D BreventServer: Force stop org.cyanogenmod.profiles(noRecent)
03-24 17:38:50.170  4526  4537 D BreventServer: Force stop com.android.cellbroadcastreceiver(noRecent)
03-24 17:38:50.205  4526  4537 D BreventServer: Force stop com.sina.weibo(noRecent)
03-24 17:38:50.252  4526  4538 D BreventServer: received feelgood
03-24 18:03:08.748  4526  4537 D BreventServer: check and brevent
03-24 18:03:08.813  4526  4537 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-24 18:03:08.825  4526  4537 D BreventServer: Force stop org.cyanogenmod.theme.chooser2(noRecent)
03-24 18:03:08.827  4526  4537 D BreventServer: Can't setStopped for com.tencent.mm(ignore)
03-24 18:03:08.861  4526  4537 D BreventServer: Force stop com.android.cellbroadcastreceiver(noRecent)
03-24 18:03:08.865  4526  4537 D BreventServer: Can't setStopped for com.zhihu.android(ignore)
03-24 18:03:08.924  4526  4538 D BreventServer: received feelgood
03-24 18:07:36.462  4526  4537 D BreventServer: check and brevent
03-24 18:07:36.543  4526  4537 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-24 18:07:36.556  4526  4537 D BreventServer: Force stop com.android.providers.media(noRecent)
03-24 18:07:36.570  4526  4537 D BreventServer: Force stop org.cyanogenmod.theme.chooser2(noRecent)
03-24 18:07:36.586  4526  4537 D BreventServer: Force stop com.android.providers.downloads(noRecent)
03-24 18:07:36.678  4526  4537 D BreventServer: Force stop com.lbe.parallel(noRecent)
03-24 18:07:36.696  4526  4537 D BreventServer: Force stop com.android.cellbroadcastreceiver(noRecent)
03-24 18:07:36.697  4526  4537 D BreventServer: Can't setStopped for com.zhihu.android(ignore)
03-24 18:07:36.752  4526  4538 D BreventServer: received feelgood
03-24 18:10:28.679  4526  4537 D BreventServer: check and brevent
03-24 18:10:28.744  4526  4537 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-24 18:10:28.758  4526  4537 D BreventServer: Force stop org.cyanogenmod.theme.chooser2(noRecent)
03-24 18:10:28.774  4526  4537 D BreventServer: Force stop com.android.defcontainer(noRecent)
03-24 18:10:28.790  4526  4537 D BreventServer: Force stop org.cyanogenmod.profiles(noRecent)
03-24 18:10:28.824  4526  4537 D BreventServer: Force stop com.android.cellbroadcastreceiver(noRecent)
03-24 18:10:28.842  4526  4537 D BreventServer: Force stop org.cyanogenmod.themes.provider(noRecent)
03-24 18:10:28.857  4526  4537 D BreventServer: Force stop com.android.gallery3d(noRecent)
03-24 18:10:28.879  4526  4537 D BreventServer: Force stop com.svox.pico(noRecent)
03-24 18:10:28.880  4526  4537 D BreventServer: Can't setStopped for com.zhihu.android(ignore)
03-24 18:10:28.893  4526  4537 D BreventServer: Force stop com.android.email(noRecent)
03-24 18:10:28.912  4526  4537 D BreventServer: Force stop com.android.providers.userdictionary(noRecent)
03-24 18:10:28.931  4526  4537 D BreventServer: Force stop com.android.exchange(noRecent)
03-24 18:10:28.933  4526  4537 D BreventServer: Force stop com.android.providers.contacts(noRecent)
03-24 18:10:28.981  4526  4538 D BreventServer: received feelgood
03-24 18:10:29.009  8745  8745 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-24 18:10:29.009  8745  8745 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-24 18:11:43.354  4526  4537 D BreventServer: check and brevent
03-24 18:11:43.449  4526  4537 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-24 18:11:43.476  4526  4537 D BreventServer: Force stop org.cyanogenmod.theme.chooser2(noRecent)
03-24 18:11:43.502  4526  4537 D BreventServer: Force stop com.android.packageinstaller(noRecent)
03-24 18:11:43.505  4526  4537 D BreventServer: Can't setStopped for com.zhihu.android(ignore)
03-24 18:11:43.592  4526  4538 D BreventServer: received feelgood
03-24 18:11:56.017  4526  4537 D BreventServer: check and brevent
03-24 18:11:56.116  4526  4537 D BreventServer: Can't setStopped for com.quark.browser(ignore)
03-24 18:11:56.135  4526  4537 D BreventServer: Force stop org.cyanogenmod.theme.chooser2(noRecent)
03-24 18:11:56.136  4526  4537 D BreventServer: Can't setStopped for com.zhihu.android(ignore)
03-24 18:11:56.238  4526  4538 D BreventServer: received feelgood
03-24 18:12:55.562  4526  4537 D BreventServer: check and brevent
03-24 18:12:55.694  4526  4537 D BreventServer: Force stop org.cyanogenmod.theme.chooser2(noRecent)
03-24 18:12:55.702  4526  4537 D BreventServer: Can't setStopped for com.tencent.mm(ignore)
03-24 18:12:55.703  4526  4537 D BreventServer: Can't setStopped for com.zhihu.android(ignore)
03-24 18:12:55.801  4526  4538 D BreventServer: received feelgood
03-24 18:13:58.609  9277  9277 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
03-24 18:13:59.067  9289  9289 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-24 18:13:59.067  9289  9289 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-24 18:13:59.070  9289  9289 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
03-24 18:13:59.083  9289  9289 I BreventServer: Brevent Server 0.9.1 started
03-24 18:13:59.085  9289  9289 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-24 18:13:59.085  9289  9289 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-24 18:13:59.096  9289  9289 I BreventServer: brevent user: 0, uid: 2000
03-24 18:13:59.097  9289  9289 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-24 18:13:59.138  9289  9289 I BreventServer: loading brevent list
03-24 18:13:59.150  9289  9289 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 93
03-24 18:13:59.150  9289  9289 I BreventServer: loading brevent conf
03-24 18:13:59.291  9289  9289 D BreventServer: check and brevent
03-24 18:13:59.547  9289  9289 D BreventServer: Force stop com.android.providers.media(noRecent)
03-24 18:13:59.568  9289  9289 D BreventServer: Force stop org.cyanogenmod.theme.chooser2(noRecent)
03-24 18:13:59.588  9289  9289 D BreventServer: Force stop com.android.providers.downloads(noRecent)
03-24 18:13:59.880  9289  9289 D BreventServer: Force stop com.tencent.mm(foreground service no notification)
03-24 18:13:59.887  9289  9289 D BreventServer: Can't setStopped for com.zhihu.android(ignore)
03-24 18:13:59.938  9289  9289 D BreventServer: check and brevent, took 647ms
03-24 18:13:59.959  9289  9289 D BreventServer: sent first status
03-24 18:14:01.893  9289  9289 D BreventServer: checking feelgood
03-24 18:14:01.894  9289  9297 D BreventServer: received feelgood
03-24 18:14:12.415  9289  9289 D BreventServer: checking feelgood
03-24 18:14:12.417  9289  9297 D BreventServer: received feelgood
03-24 18:14:15.729  9289  9289 D BreventServer: checking feelgood
03-24 18:14:15.729  9289  9297 D BreventServer: received feelgood

C:\platform-tools>

**Comment by liudongmiao** [comment]
> 03-24 18:10:28.893 4526 4537 D BreventServer: Force stop com.android.email(noRecent)
> 03-24 18:10:28.912 4526 4537 D BreventServer: Force stop com.android.providers.userdictionary(noRecent)
> 03-24 18:10:28.931 4526 4537 D BreventServer: Force stop com.android.exchange(noRecent)
> 03-24 18:10:28.933 4526 4537 D BreventServer: Force stop com.android.providers.contacts(noRecent)

没事，别黑域重要系统应用。我都默认不显示，你硬要处理，我也没办法。
保持黑域启用之后，卸载黑域，重新安装吧。

**Comment by chenbuhtig** [comment]
说的不是重要的系统应用阿，说的就是普通的自己安装的应用，现在我已经把重要的应用取消了
再看下日志

C:\platform-tools>adb -d logcat -d -s BreventServer BreventLoader
--------- beginning of system
--------- beginning of main
03-25 18:37:31.087  7312  7312 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
03-25 18:37:31.539  7322  7322 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-25 18:37:31.539  7322  7322 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-25 18:37:31.542  7322  7322 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
03-25 18:37:31.554  7322  7322 I BreventServer: Brevent Server 0.9.1 started
03-25 18:37:31.555  7322  7322 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-25 18:37:31.556  7322  7322 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-25 18:37:31.564  7322  7322 I BreventServer: brevent user: 0, uid: 2000
03-25 18:37:31.565  7322  7322 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-25 18:37:31.599  7322  7322 I BreventServer: loading brevent list
03-25 18:37:31.608  7322  7322 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 22
03-25 18:37:31.608  7322  7322 I BreventServer: loading brevent conf
03-25 18:37:31.789  7322  7322 D BreventServer: check and brevent
03-25 18:37:32.078  7322  7322 D BreventServer: Force stop com.quark.browser(noRecent)
03-25 18:37:32.143  7322  7322 D BreventServer: Force stop com.xunlei.vip.swjsq(sticky notification)
03-25 18:37:32.271  7322  7322 D BreventServer: Force stop com.coolapk.market(noRecent)
03-25 18:37:32.413  7322  7322 D BreventServer: Force stop com.sina.weibo(noRecent)
03-25 18:37:32.461  7322  7322 D BreventServer: check and brevent, took 672ms
03-25 18:37:32.507  7322  7322 D BreventServer: sent first status
03-25 18:37:39.681  7322  7322 D BreventServer: checking feelgood
03-25 18:37:39.682  7322  7330 D BreventServer: received feelgood
03-25 18:37:42.118  7322  7322 D BreventServer: checking feelgood
03-25 18:37:42.118  7322  7330 D BreventServer: received feelgood
03-25 18:37:43.867  7322  7322 D BreventServer: checking feelgood
03-25 18:37:43.870  7322  7330 D BreventServer: received feelgood
03-25 18:37:53.475  7322  7322 D BreventServer: checking feelgood
03-25 18:37:53.475  7322  7330 D BreventServer: received feelgood
03-25 18:38:05.611  7322  7322 D BreventServer: checking feelgood
03-25 18:38:05.612  7322  7330 D BreventServer: received feelgood
03-25 18:38:13.430  7322  7322 D BreventServer: checking feelgood
03-25 18:38:13.432  7322  7330 D BreventServer: received feelgood
03-25 18:38:16.098  7322  7322 D BreventServer: checking feelgood
03-25 18:38:16.098  7322  7330 D BreventServer: received feelgood
03-25 18:38:22.386  7322  7322 D BreventServer: checking feelgood
03-25 18:38:22.386  7322  7330 D BreventServer: received feelgood
03-25 18:40:00.111  7322  7322 D BreventServer: checking feelgood
03-25 18:40:00.111  7322  7330 D BreventServer: received feelgood
03-25 18:42:01.248  7322  7322 D BreventServer: checking feelgood
03-25 18:42:01.249  7322  7330 D BreventServer: received feelgood
03-25 18:42:21.106  7322  7322 D BreventServer: checking feelgood
03-25 18:42:21.108  7322  7330 D BreventServer: received feelgood
03-25 18:42:23.394  7322  7322 D BreventServer: checking feelgood
03-25 18:42:23.394  7322  7330 D BreventServer: received feelgood
03-25 18:42:32.420  7322  7322 D BreventServer: check and brevent
03-25 18:42:32.890  7322  7322 D BreventServer: Force stop com.tencent.mm(foreground service no notification)
03-25 18:42:32.893  7322  7322 D BreventServer: Can't setStopped for com.zhihu.android(ignore)
03-25 18:42:32.895  7322  7322 D BreventServer: Can't setStopped for com.coolapk.market(ignore)
03-25 18:42:32.938  7322  7322 D BreventServer: check and brevent, took 518ms
03-25 18:42:48.857  7322  7322 D BreventServer: checking feelgood
03-25 18:42:48.857  7322  7330 D BreventServer: received feelgood
03-25 18:42:50.916  7322  7322 D BreventServer: checking feelgood
03-25 18:42:50.917  7322  7330 D BreventServer: received feelgood








第二组

03-25 18:37:31.087  7312  7312 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
03-25 18:37:31.539  7322  7322 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-25 18:37:31.539  7322  7322 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-25 18:37:31.542  7322  7322 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
03-25 18:37:31.554  7322  7322 I BreventServer: Brevent Server 0.9.1 started
03-25 18:37:31.555  7322  7322 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-25 18:37:31.556  7322  7322 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-25 18:37:31.564  7322  7322 I BreventServer: brevent user: 0, uid: 2000
03-25 18:37:31.565  7322  7322 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-25 18:37:31.599  7322  7322 I BreventServer: loading brevent list
03-25 18:37:31.608  7322  7322 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 22
03-25 18:37:31.608  7322  7322 I BreventServer: loading brevent conf
03-25 18:37:31.789  7322  7322 D BreventServer: check and brevent
03-25 18:37:32.078  7322  7322 D BreventServer: Force stop com.quark.browser(noRecent)
03-25 18:37:32.143  7322  7322 D BreventServer: Force stop com.xunlei.vip.swjsq(sticky notification)
03-25 18:37:32.271  7322  7322 D BreventServer: Force stop com.coolapk.market(noRecent)
03-25 18:37:32.413  7322  7322 D BreventServer: Force stop com.sina.weibo(noRecent)
03-25 18:37:32.461  7322  7322 D BreventServer: check and brevent, took 672ms
03-25 18:37:32.507  7322  7322 D BreventServer: sent first status
03-25 18:37:39.681  7322  7322 D BreventServer: checking feelgood
03-25 18:37:39.682  7322  7330 D BreventServer: received feelgood
03-25 18:37:42.118  7322  7322 D BreventServer: checking feelgood
03-25 18:37:42.118  7322  7330 D BreventServer: received feelgood
03-25 18:37:43.867  7322  7322 D BreventServer: checking feelgood
03-25 18:37:43.870  7322  7330 D BreventServer: received feelgood
03-25 18:37:53.475  7322  7322 D BreventServer: checking feelgood
03-25 18:37:53.475  7322  7330 D BreventServer: received feelgood
03-25 18:38:05.611  7322  7322 D BreventServer: checking feelgood
03-25 18:38:05.612  7322  7330 D BreventServer: received feelgood
03-25 18:38:13.430  7322  7322 D BreventServer: checking feelgood
03-25 18:38:13.432  7322  7330 D BreventServer: received feelgood
03-25 18:38:16.098  7322  7322 D BreventServer: checking feelgood
03-25 18:38:16.098  7322  7330 D BreventServer: received feelgood
03-25 18:38:22.386  7322  7322 D BreventServer: checking feelgood
03-25 18:38:22.386  7322  7330 D BreventServer: received feelgood
03-25 18:40:00.111  7322  7322 D BreventServer: checking feelgood
03-25 18:40:00.111  7322  7330 D BreventServer: received feelgood
03-25 18:42:01.248  7322  7322 D BreventServer: checking feelgood
03-25 18:42:01.249  7322  7330 D BreventServer: received feelgood
03-25 18:42:21.106  7322  7322 D BreventServer: checking feelgood
03-25 18:42:21.108  7322  7330 D BreventServer: received feelgood
03-25 18:42:23.394  7322  7322 D BreventServer: checking feelgood
03-25 18:42:23.394  7322  7330 D BreventServer: received feelgood
03-25 18:42:32.420  7322  7322 D BreventServer: check and brevent
03-25 18:42:32.890  7322  7322 D BreventServer: Force stop com.tencent.mm(foreground service no notification)
03-25 18:42:32.893  7322  7322 D BreventServer: Can't setStopped for com.zhihu.android(ignore)
03-25 18:42:32.895  7322  7322 D BreventServer: Can't setStopped for com.coolapk.market(ignore)
03-25 18:42:32.938  7322  7322 D BreventServer: check and brevent, took 518ms
03-25 18:42:48.857  7322  7322 D BreventServer: checking feelgood
03-25 18:42:48.857  7322  7330 D BreventServer: received feelgood
03-25 18:42:50.916  7322  7322 D BreventServer: checking feelgood
03-25 18:42:50.917  7322  7330 D BreventServer: received feelgood
03-25 18:45:02.083  7322  7322 D BreventServer: checking feelgood
03-25 18:45:02.084  7322  7330 D BreventServer: received feelgood
03-25 18:45:04.319  7322  7322 D BreventServer: checking feelgood
03-25 18:45:04.320  7322  7330 D BreventServer: received feelgood
03-25 18:45:07.588  7322  7322 D BreventServer: checking feelgood
03-25 18:45:07.589  7322  7330 D BreventServer: received feelgood
03-25 18:45:11.073  7322  7322 D BreventServer: checking feelgood
03-25 18:45:11.074  7322  7330 D BreventServer: received feelgood

**Comment by liudongmiao** [comment]
看起来无异常啊～
