### ISSUE TITLE
点击手机实体最近任务按钮后桌面闪退并重启锁屏。。

### ISSUE THREAD

**Issue by cxgreat2014** [liudongmiao/Brevent#291]
谷歌市场下载的最新版黑域，开启adb后使用的root模式，root管理程序为kingroot。。
以及。。要贴log吗？手机上直接root使用的不知道怎么做。。
具体现象为，点击最近任务按钮，然后界面就黑掉，之后出现主页，再立马跳到锁屏界面。。
以上。。
手机奇酷手机青春版，8681-m02,安卓5.1

**Comment by chm512512** [comment]
@cxgreat2014 首先作者说了不要混用，其次play版的root要捐赠，再然后提供日志是基本，最后好好看向导。

**Comment by cxgreat2014** [comment]
@chm512512 谢谢您的回复，我不知道在哪能找到log以及怎么贴出来（我对安卓开发的知识储备仅限于安装Android Studio），因此。。。很抱歉我想贴也没法贴。。。我在向导里也没有找到相关的资料。另外，play版的root我下的不要捐赠。。。难道我上的是假play？最后。。。我在被这个BUG烦得不得了之后，把黑域丢到冷藏室里disable了，然后重启，再过了段时间再去打开黑域。。。。神奇的BUG就不见了。。我也是很无奈啊。。。

**Comment by liudongmiao** [comment]
参照商店详情来日志吧

**Comment by liudongmiao** [comment]
在商店详情，你执行adb启动服务时都有说日志怎么取…你居然告诉我不知道？

**Comment by cxgreat2014** [comment]
@chm512512 啊？抱歉。。我直接点的下载。。。没看应用详情。。

**Comment by cxgreat2014** [comment]
@chm512512 现在BUG已经不能复现了。。。去执行命令看日志还有意义吗？

**Comment by cxgreat2014** [comment]
@liudongmiao 谢谢您的关注 :heart:  :+1:  或许只能等待别人在遇到这问题或者我这问题再次复现时才能报告了
