### ISSUE TITLE
Nokia N1 lease:A5CNB19  Android 5.1.1

### ISSUE THREAD

**Issue by Bingo-Dragon** [liudongmiao/Brevent#293]
D:\Android\sdk\platform-tools>adb devices
List of devices attached
L25141CNN1K3    device

D:\Android\sdk\platform-tools>adb -d shell /data/app/me.piebridge.brevent-1/lib/x86/libbrevent.so
WARNING: linker: /data/app/me.piebridge.brevent-1/lib/x86/libbrevent.so: unused DT entry: type 0x6ffffffe arg 0x928
WARNING: linker: /data/app/me.piebridge.brevent-1/lib/x86/libbrevent.so: unused DT entry: type 0x6fffffff arg 0x1
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-24 23:00:27.000' -d
E/AndroidRuntime(19102): *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
E/AndroidRuntime(19102): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/me.piebridge.brevent-1/lib/x86/libreader.so" is 32-bit instead of 64-bit
E/AndroidRuntime(19102):        at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/AndroidRuntime(19102):        at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime(19102):        at me.piebridge.LogReader.<clinit>(LogReader.java:10)
E/AndroidRuntime(19102):        at me.piebridge.LogReader.readEvents(Native Method)
E/AndroidRuntime(19102):        at me.piebridge.brevent.server.a.run(BreventEvent.java:47)
E/AndroidRuntime(19102):        at java.lang.Thread.run(Thread.java:818)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-24 23:00:27.000' -d -s BreventLoader BreventServer
D/BreventLoader(19084): loader path: /data/app/me.piebridge.brevent-1/base.apk
W/BreventServer(19102): Can't find Settings.Secure.DIALER_DEFAULT_APPLICATION
W/BreventServer(19102): Can't find Settings.Secure.ASSISTANT
W/BreventServer(19102): Can't find ActivityManager.PROCESS_STATE_BOUND_FOREGROUND_SERVICE
W/BreventServer(19102): Can't find ActivityManager.PROCESS_STATE_FOREGROUND_SERVICE
W/BreventServer(19102): Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
W/BreventServer(19102): Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
I/BreventServer(19102): classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
I/BreventServer(19102): Brevent Server 0.9.1 started
W/BreventServer(19102): Can't find Settings.Secure.DIALER_DEFAULT_APPLICATION
W/BreventServer(19102): Can't find Settings.Secure.ASSISTANT
W/BreventServer(19102): Can't find ActivityManager.PROCESS_STATE_BOUND_FOREGROUND_SERVICE
W/BreventServer(19102): Can't find ActivityManager.PROCESS_STATE_FOREGROUND_SERVICE
W/BreventServer(19102): Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
W/BreventServer(19102): Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
I/BreventServer(19102): brevent user: 0, uid: 2000
I/BreventServer(19102): brevent data directory: /data/data/com.android.shell
I/BreventServer(19102): loading brevent list
I/BreventServer(19102): loading brevent conf
D/BreventServer(19102): check and brevent
E/BreventLoader(19084): worker 19102 exited on signal 9
D/BreventLoader(19084): signal arrived, update: 0
D/BreventLoader(19082): worker 19084 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
已经支持 x86_64 机器
