### ISSUE TITLE
大厂启动失败——vivo X6S

### ISSUE THREAD

**Issue by JasonAustinal** [liudongmiao/Brevent#294]
WARNING: linker: /data/app/me.piebridge.brevent-2/lib/arm/libbrevent.so: unused DT entry: type 0x6ffffffe arg 0xa64
WARNING: linker: /data/app/me.piebridge.brevent-2/lib/arm/libbrevent.so: unused DT entry: type 0x6fffffff arg 0x1
checking...brevent_server started, pid: 12802
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-25 00:05:55.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-25 00:05:55.000' -d -s BreventLoader BreventServer
D/BreventLoader(12785): loader path: /data/app/me.piebridge.brevent-2/base.apk
W/BreventServer(12802): Can't find Settings.Secure.DIALER_DEFAULT_APPLICATION
W/BreventServer(12802): Can't find Settings.Secure.ASSISTANT
W/BreventServer(12802): Can't find ActivityManager.PROCESS_STATE_BOUND_FOREGROUND_SERVICE
W/BreventServer(12802): Can't find ActivityManager.PROCESS_STATE_FOREGROUND_SERVICE
W/BreventServer(12802): Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
W/BreventServer(12802): Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
I/BreventServer(12802): classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
I/BreventServer(12802): Brevent Server 0.9.1 started
W/BreventServer(12802): Can't find Settings.Secure.DIALER_DEFAULT_APPLICATION
W/BreventServer(12802): Can't find Settings.Secure.ASSISTANT
W/BreventServer(12802): Can't find ActivityManager.PROCESS_STATE_BOUND_FOREGROUND_SERVICE
W/BreventServer(12802): Can't find ActivityManager.PROCESS_STATE_FOREGROUND_SERVICE
W/BreventServer(12802): Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
W/BreventServer(12802): Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
I/BreventServer(12802): brevent user: 0, uid: 2000
I/BreventServer(12802): brevent data directory: /data/data/com.android.shell
I/BreventServer(12802): loading brevent list
I/BreventServer(12802): loading brevent conf
D/BreventServer(12802): check and brevent
E/BreventLoader(12785): worker 12802 exited on signal 9
D/BreventLoader(12785): signal arrived, update: 0
D/BreventLoader(12783): worker 12785 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
最新的测试版  https://piebridge.me/br/next 看了么？
现在是什么情况？

**Comment by GongJianwei** [comment]
这个问题和 #350 一样

**Comment by liudongmiao** [comment]
我很佩服 @GongJianwei 这个日志没有说任何信息，你就能断定和别的一样。牛。

**Comment by GongJianwei** [comment]
那抱歉啦，是我的错 😂 @liudongmiao

**Comment by liudongmiao** [comment]
十天没有继续反馈，关闭。
