### ISSUE TITLE
非odex优化版本，services.jar却小于1M，流程无法继续

### ISSUE THREAD

**Issue by john41nt** [liudongmiao/Brevent#3]
SONY Xperia Z3 Tablet Compact（SGP621），Android 6.0.1，services.jar大小为206字节，整个目录没有services.odex文件，补丁流程无法继续，求问对应方法。
[services.zip](https://github.com/liudongmiao/Brevent/files/561082/services.zip)

**Comment by liudongmiao** [comment]
我没有说在这个目录下吧，请找找子目录。

**Comment by john41nt** [comment]
已经使用Everything搜索过，整个硬盘里并没有services.odex文件。

**Comment by aviraxp** [comment]
理论上应该在/system/framework/oat/arm/下。

**Comment by liudongmiao** [comment]
@john41nt 你需要从手机里找，或者把整个 framework 目录从手机里导出来，就在子目录下。
手机里的 `/system/framework` 一共也只有少数几个子目录，并不难找。

**Comment by john41nt** [comment]
找到了，在framwork/oat/arm/下，之前这个目录并没有被成功导出。感谢回复。
