### ISSUE TITLE
0.9.2黑域处理延迟

### ISSUE THREAD

**Issue by chenguangtu** [liudongmiao/Brevent#300]
更新0.9.2之后，back退出应用，不再像之前几秒没就黑域了，现在差不多要等1分钟

**Comment by liudongmiao** [comment]
某些应用，当你按 Back 时，不执行正常的的 Back 操作...还记得之前版本的这段话么？

现在，这些应用不处理。等他们超时。

如果你说的其它，那就是，黑域时机，现在就是动态控制，回到桌面，数1，2，3，看是否还清理了。

**Comment by chenguangtu** [comment]
希望默认处理这些应用，国内流氓应用没几个是正常back的

**Comment by liudongmiao** [comment]
自己划掉就好。而且，又不是不处理。

为了你主动打开过的极少数流氓应用，你偏要使用一种复杂比较的使用模式，来让开发者支持，结论，不处理。

**Comment by chenguangtu** [comment]
那这样系统超时只能设置成一分钟了……

**Comment by liudongmiao** [comment]
自己划掉不就好了...

这样的应用，我也没遇到几个，就是少数极端情况。为了他们，写大段代码不值当。

**Comment by chenguangtu** [comment]
不说其他，可以试试酷安

**Comment by liudongmiao** [comment]
要么卸，要么从最近列表划掉。又不是不处理，只是要等到后台应用超时而已。我说得很清楚了。

酷安 (7.5)，并没有不正常 Back。自己想好了，再来找我，不要浪费我的时间。

你，可能只会考虑你自己的需求；而我，作为开发者，要综合考虑性能，有所取舍。
为了少数几个应用，而写大量复杂逻辑，还要考虑各个平台兼容性，只是为了一个极少数的强迫症，不值当。

遇到不正常 Back，要么：
1. 卸载它，不打开它
2. 从最近列表划掉它
    你明明知道它会这样，选择 Back 和 选择最近列表划掉，会那么麻烦？
3. 要求它的开发者，不要使用这种方式
4. 找其它开发者或者找我，付费开发类似功能
5. 任何时候，我都想对黑域用户说，“喜欢就用，不用就卸”
