### ISSUE TITLE
0.9以后的版本，系统异常唤醒导致耗电

### ISSUE THREAD

**Issue by 849506054** [liudongmiao/Brevent#302]
两次测试都是充满电开始测的，使用时间大概为半天
首先上图，图一是0.87版本，PowerManagerService.WakeLocks唤醒时间正常
![screenshot_20170325-215434](https://cloud.githubusercontent.com/assets/25845909/24328006/23cc6a80-1211-11e7-8462-c88bc47ebedb.png)
图二是0.92版本，PowerManagerService.WakeLocks唤醒时间近半小时之久
![screenshot_20170326-103440](https://cloud.githubusercontent.com/assets/25845909/24328005/23cad06c-1211-11e7-955c-cb58e73f7233.png)
使用习惯都是相同的，系统是6.0.1

之前没开调试日志，等下传，随时可以teamviewer

**Comment by 849506054** [comment]
0.9、0.91也测试过，情况一样

**Comment by chenguangtu** [comment]
我的也是这样，一加3  7.1

**Comment by 849506054** [comment]
尴尬的是从新充满电测试到现在好像又正常了，再观察看看

**Comment by liudongmiao** [comment]
@849506054 目前确实有个小问题，我没有修复。

那就是，关屏后，要减低触发 check and brevent 的频率，这里可以优化下。

**Comment by 849506054** [comment]
@liudongmiao 好的，已知问题就好
希望下个版本修复😁

**Comment by liudongmiao** [comment]
这个不算啥啦，对电量影响甚微，只是我追求极致才提一下而已。

**Comment by 849506054** [comment]
@liudongmiao 事实上增加了多少耗电我也没仔细测，只是发现有这个问题而已😂

**Comment by chenguangtu** [comment]
唤醒多了二十多分钟，是不是意味着cpu起码在最低频率运行了二十多分钟？

**Comment by 849506054** [comment]
@chenguangtu 没有特意去对比，不知道是不是最低频率唤醒的

**Comment by liudongmiao** [comment]
请检查下最新的0.9.4 或者 最新测试版 https://piebridge.me/br/next/

**Comment by liudongmiao** [comment]
暂时关闭，就我本人来说，已经大大改善不必要的检查 (check and brevent)。

**Comment by 849506054** [comment]
@liudongmiao 好的，已经下载了最新测试版
