### ISSUE TITLE
ADB 指令無法啟用黑域

### ISSUE THREAD

**Issue by Whatthe8078** [liudongmiao/Brevent#303]
手機：Samsung GALAXY Note2 (N7100)
Android 版本：6.0.1 with MIUI 8 (6.11.9)
日誌內容：
> --- crash start ---
> >>> logcat -b crash -t '03-26 11:26:45.000' -d
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime: java.lang.reflect.InvocationTargetException
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1369)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException:  is not a constant in android.text.Layout$Alignment
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at java.lang.Enum.valueOf(Enum.java:200)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.text.Layout$Alignment.valueOf(Layout.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpan.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.readFromParcel(ActivityManager.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.os.Parcel.createTypedArrayList(Parcel.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at android.app.ActivityManagerProxy.getRecentTasks(ActivityManagerNative.java)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at me.piebridge.brevent.a.b.a(HideApiOverrideM.java:22)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:767)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.f(BreventServer.java:449)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1350)
> 03-26 11:26:48.630 21989 21989 E AndroidRuntime:        ... 4 more
> 03-26 11:26:48.631 21989 21989 E AndroidRuntime: Error reporting crash
> 03-26 11:26:48.631 21989 21989 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
> 03-26 11:26:48.631 21989 21989 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
> 03-26 11:26:48.631 21989 21989 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java)
> 03-26 11:26:48.631 21989 21989 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java)
> 03-26 11:26:48.631 21989 21989 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java)
> 03-26 11:26:48.631 21989 21989 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
> 03-26 11:26:48.631 21989 21989 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
> --- crash end ---
> --- brevent start ---
> >>> logcat -b main -t '03-26 11:26:45.000' -d -s BreventLoader BreventServer
> 03-26 11:26:47.369 21972 21972 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
> 03-26 11:26:48.330 21989 21989 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
> 03-26 11:26:48.330 21989 21989 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
> 03-26 11:26:48.337 21989 21989 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
> 03-26 11:26:48.351 21989 21989 I BreventServer: Brevent Server 0.9.2 started
> 03-26 11:26:48.358 21989 21989 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
> 03-26 11:26:48.358 21989 21989 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
> 03-26 11:26:48.367 21989 21989 W BreventServer: version unmatched, running: 0.9.2, installed: ivy(0.9.2)
> 03-26 11:26:48.368 21989 21989 I BreventServer: brevent user: 0, uid: 0
> 03-26 11:26:48.369 21989 21989 I BreventServer: brevent data directory: /data/user/0/com.android.shell
> 03-26 11:26:48.453 21989 21989 I BreventServer: loading brevent list
> 03-26 11:26:48.455 21989 21989 I BreventServer: loading brevent conf
> 03-26 11:26:48.497 21989 21989 D BreventServer: check and brevent
> 03-26 11:26:48.638 21972 21972 E BreventLoader: worker 21989 exited on signal 9
> 03-26 11:26:48.638 21972 21972 D BreventLoader: signal arrived, update: 0
> 03-26 11:26:48.639 21963 21963 D BreventLoader: worker 21972 exited with status 0
> --- brevent end ---
> cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
您的机器上，无法获取最近任务列表，这是一个非常重要的数据，作为是否恶意唤醒一个非常重要的数据。

我再想想要不要跳过这个数据。

由于不是官方的 ROM，我可能不会支持它。因为没有这个数据，非常影响体验。
