### ISSUE TITLE
一加三7.1黑域0.92版本，黑域服务调试日志

### ISSUE THREAD

**Issue by linqi0816** [liudongmiao/Brevent#304]
日志如下
03-26 11:32:54.710 29842 29842 D BreventServer: check and brevent
03-26 11:33:02.063 29842 29842 D BreventServer: ignore com.google.android.google
quicksearchbox, wait for the service check
03-26 11:33:02.063 29842 29842 D BreventServer: check and brevent, took 7352ms
03-26 11:34:05.572 29842 29842 D BreventServer: check and brevent
03-26 11:34:12.868 29842 29842 D BreventServer: ignore com.google.android.google
quicksearchbox, wait for the service check
03-26 11:34:12.868 29842 29842 D BreventServer: check and brevent, took 7296ms
03-26 11:36:51.463 29842 29842 D BreventServer: checking feelgood
03-26 11:36:51.466 29842 29855 D BreventServer: received feelgood
03-26 11:37:01.436 29842 29842 D BreventServer: checking feelgood
03-26 11:37:01.437 29842 29855 D BreventServer: received feelgood
03-26 11:37:18.400 29842 29842 D BreventServer: check and brevent
03-26 11:37:25.745 29842 29842 D BreventServer: ignore com.google.android.google
quicksearchbox, wait for the service check
03-26 11:37:25.746 29842 29842 D BreventServer: check and brevent, took 7345ms
03-26 11:37:41.171 29842 29842 D BreventServer: check and brevent
03-26 11:37:48.415 29842 29842 D BreventServer: ignore com.google.android.google
quicksearchbox, wait for the service check
03-26 11:37:48.415 29842 29842 D BreventServer: check and brevent, took 7244ms
03-26 11:40:21.779 29842 29842 D BreventServer: check and brevent
03-26 11:40:21.785 29842 29842 D BreventServer: before dump notifications, took
5ms
03-26 11:40:28.905 29842 29842 D BreventServer: after dump notifications, took 7
125ms
03-26 11:40:28.925 29842 29842 D BreventServer: after dump widgets, took 7145ms
03-26 11:40:28.925 29842 29842 D BreventServer: before dumpActivities, took 7145
ms
03-26 11:40:28.962 29842 29842 D BreventServer: after dumpActivities, took 7182m
s
03-26 11:40:28.962 29842 29842 D BreventServer: before getRecentPackages, took 7
182ms
03-26 11:40:28.964 29842 29842 D BreventServer: after getRecentPackages, took 71
84ms
03-26 11:40:28.964 29842 29842 D BreventServer: widgets: {com.oneplus.security,
cn.ledongli.ldl, small.word, com.xtuone.android.syllabus, com.netease.cloudmusic
, com.motorola.commandcenter3}
03-26 11:40:28.964 29842 29842 D BreventServer: running: {com.quark.browser=1323
97, com.oneplus.deskclock=115660, hanjie.app.pureweather=129236, com.tencent.mm=
131437, me.piebridge.brevent=132263, com.tencent.mobileqq=131481, com.coolapk.ma
rket=132398}
03-26 11:40:28.964 29842 29842 D BreventServer: recent: {com.quark.browser, com.
teslacoilsw.launcher, hanjie.app.pureweather, com.tencent.mm, me.piebridge.breve
nt, com.tencent.mobileqq, com.coolapk.market, com.android.systemui}
03-26 11:40:28.964 29842 29842 D BreventServer: before getRunningProcesses, took
 7184ms
03-26 11:40:29.017 29842 29842 D BreventServer: after getRunningProcesses, took
7237ms
03-26 11:40:29.017 29842 29842 D BreventServer: inactive for com.quark.browser:
68, timeout: 600
03-26 11:40:29.017 29842 29842 D BreventServer: inactive for com.google.android.
googlequicksearchbox: 0, timeout: 600
03-26 11:40:29.017 29842 29842 D BreventServer: inactive for com.coolapk.market:
 67, timeout: 600
03-26 11:40:29.017 29842 29842 D BreventServer: before dumpProcesses, took 7237m
s
03-26 11:40:29.078 29842 29842 D BreventServer: after dumpProcesses, took 7298ms

03-26 11:40:29.078 29842 29842 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gms, com.coolapk.market}
03-26 11:40:29.078 29842 29842 D BreventServer: com.google.android.gms depended
by {com.oasisfeng.greenify, com.flyperinc.cornerfly}
03-26 11:40:29.078 29842 29842 D BreventServer: before isCharging, took 7298ms
03-26 11:40:29.078 29842 29842 D BreventServer: after isCharging, took 7298ms
03-26 11:40:29.079 29842 29842 D BreventServer: service: {}
03-26 11:40:29.079 29842 29842 D BreventServer: blocking: {com.google.android.go
oglequicksearchbox}
03-26 11:40:29.079 29842 29842 D BreventServer: before getVpn, took 7299ms
03-26 11:40:29.082 29842 29842 D BreventServer: after getVpn, took 7302ms
03-26 11:40:29.082 29842 29842 D BreventServer: vpn: null
03-26 11:40:29.082 29842 29842 D BreventServer: top: {com.coolapk.market}
03-26 11:40:29.082 29842 29842 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
03-26 11:40:29.082 29842 29842 D BreventServer: current: com.coolapk.market
03-26 11:40:29.082 29842 29842 D BreventServer: unsafe: {}
03-26 11:40:29.082 29842 29842 D BreventServer: final blocking: {com.google.andr
oid.googlequicksearchbox}
03-26 11:40:29.082 29842 29842 D BreventServer: notifications: {com.lbe.security
=[98, 98], hanjie.app.pureweather=[98], cn.ledongli.ldl=[98], com.tencent.mobile
qq=[17], me.bylife.oneplusnetspeed=[98], cn.mixiaoxiao.myappscreenmask=[10]}
03-26 11:40:29.082 29842 29842 D BreventServer: noRecent: {com.google.android.go
oglequicksearchbox}
03-26 11:40:29.082 29842 29842 D BreventServer: foreground service: {}
03-26 11:40:29.083 29842 29842 D BreventServer: before blocking, took 7303ms, si
ze: 1
03-26 11:40:29.083 29842 29842 D BreventServer: ignore com.google.android.google
quicksearchbox, wait for the service check
03-26 11:40:29.083 29842 29842 D BreventServer: after blocking, took 7303ms
03-26 11:40:29.083 29842 29842 D BreventServer: check and brevent, took 7303ms
03-26 11:40:56.493 29842 29842 D BreventServer: checking feelgood
03-26 11:40:56.499 29842 29855 D BreventServer: received feelgood
03-26 11:41:09.626 29842 29842 D BreventServer: checking feelgood
03-26 11:41:09.627 29842 29855 D BreventServer: received feelgood
03-26 11:41:21.796 29842 29842 D BreventServer: check and brevent
03-26 11:41:21.801 29842 29842 D BreventServer: before dump notifications, took
5ms
03-26 11:41:28.987 29842 29842 D BreventServer: after dump notifications, took 7
191ms
03-26 11:41:29.003 29842 29842 D BreventServer: after dump widgets, took 7207ms
03-26 11:41:29.003 29842 29842 D BreventServer: before dumpActivities, took 7207
ms
03-26 11:41:29.018 29842 29842 D BreventServer: after dumpActivities, took 7222m
s
03-26 11:41:29.018 29842 29842 D BreventServer: before getRecentPackages, took 7
222ms
03-26 11:41:29.037 29842 29842 D BreventServer: after getRecentPackages, took 72
41ms
03-26 11:41:29.037 29842 29842 D BreventServer: widgets: {com.oneplus.security,
cn.ledongli.ldl, small.word, com.xtuone.android.syllabus, com.netease.cloudmusic
, com.motorola.commandcenter3}
03-26 11:41:29.037 29842 29842 D BreventServer: running: {com.quark.browser=1323
98, com.oneplus.deskclock=115661, com.lbe.security=132520, hanjie.app.pureweathe
r=129237, com.tencent.mm=131438, me.piebridge.brevent=132522, com.tencent.mobile
qq=131482, com.coolapk.market=132491}
03-26 11:41:29.037 29842 29842 D BreventServer: recent: {com.quark.browser, com.
teslacoilsw.launcher, com.lbe.security, hanjie.app.pureweather, com.tencent.mm,
me.piebridge.brevent, com.tencent.mobileqq, com.coolapk.market, com.android.syst
emui}
03-26 11:41:29.037 29842 29842 D BreventServer: before getRunningProcesses, took
 7241ms
03-26 11:41:29.115 29842 29842 D BreventServer: after getRunningProcesses, took
7318ms
03-26 11:41:29.115 29842 29842 D BreventServer: inactive for com.quark.browser:
127, timeout: 600
03-26 11:41:29.115 29842 29842 D BreventServer: inactive for com.google.android.
googlequicksearchbox: 0, timeout: 600
03-26 11:41:29.115 29842 29842 D BreventServer: inactive for com.coolapk.market:
 34, timeout: 600
03-26 11:41:29.115 29842 29842 D BreventServer: before dumpProcesses, took 7319m
s
03-26 11:41:29.163 29842 29842 D BreventServer: after dumpProcesses, took 7367ms

03-26 11:41:29.163 29842 29842 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gms, com.coolapk.market}
03-26 11:41:29.164 29842 29842 D BreventServer: com.google.android.gms depended
by {com.oasisfeng.greenify, com.flyperinc.cornerfly}
03-26 11:41:29.164 29842 29842 D BreventServer: before isCharging, took 7368ms
03-26 11:41:29.164 29842 29842 D BreventServer: after isCharging, took 7368ms
03-26 11:41:29.164 29842 29842 D BreventServer: service: {}
03-26 11:41:29.164 29842 29842 D BreventServer: blocking: {com.google.android.go
oglequicksearchbox}
03-26 11:41:29.164 29842 29842 D BreventServer: before getVpn, took 7368ms
03-26 11:41:29.165 29842 29842 D BreventServer: after getVpn, took 7369ms
03-26 11:41:29.165 29842 29842 D BreventServer: vpn: null
03-26 11:41:29.165 29842 29842 D BreventServer: top: {me.piebridge.brevent}
03-26 11:41:29.165 29842 29842 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
03-26 11:41:29.165 29842 29842 D BreventServer: current: com.lbe.security
03-26 11:41:29.165 29842 29842 D BreventServer: unsafe: {}
03-26 11:41:29.165 29842 29842 D BreventServer: final blocking: {com.google.andr
oid.googlequicksearchbox}
03-26 11:41:29.165 29842 29842 D BreventServer: notifications: {com.lbe.security
=[98, 98], hanjie.app.pureweather=[98], cn.ledongli.ldl=[98], com.tencent.mobile
qq=[17], me.bylife.oneplusnetspeed=[98], cn.mixiaoxiao.myappscreenmask=[10]}
03-26 11:41:29.165 29842 29842 D BreventServer: noRecent: {com.google.android.go
oglequicksearchbox}
03-26 11:41:29.165 29842 29842 D BreventServer: foreground service: {}
03-26 11:41:29.165 29842 29842 D BreventServer: gcm: {}
03-26 11:41:29.165 29842 29842 D BreventServer: before blocking, took 7369ms, si
ze: 1
03-26 11:41:29.165 29842 29842 D BreventServer: ignore com.google.android.google
quicksearchbox, wait for the service check
03-26 11:41:29.165 29842 29842 D BreventServer: after blocking, took 7369ms
03-26 11:41:29.165 29842 29842 D BreventServer: check and brevent, took 7369ms
03-26 11:41:29.199 29842 29842 D BreventServer: checking feelgood
03-26 11:41:29.205 29842 29855 D BreventServer: received feelgood
03-26 11:42:29.177 29842 29842 D BreventServer: check and brevent
03-26 11:42:29.186 29842 29842 D BreventServer: before dump notifications, took
9ms
03-26 11:42:36.284 29842 29842 D BreventServer: after dump notifications, took 7
107ms
03-26 11:42:36.303 29842 29842 D BreventServer: after dump widgets, took 7126ms
03-26 11:42:36.303 29842 29842 D BreventServer: before dumpActivities, took 7126
ms
03-26 11:42:36.329 29842 29842 D BreventServer: after dumpActivities, took 7152m
s
03-26 11:42:36.329 29842 29842 D BreventServer: before getRecentPackages, took 7
152ms
03-26 11:42:36.331 29842 29842 D BreventServer: after getRecentPackages, took 71
54ms
03-26 11:42:36.332 29842 29842 D BreventServer: widgets: {com.oneplus.security,
cn.ledongli.ldl, small.word, com.xtuone.android.syllabus, com.netease.cloudmusic
, com.motorola.commandcenter3}
03-26 11:42:36.332 29842 29842 D BreventServer: running: {com.quark.browser=1325
47, com.oneplus.deskclock=115661, com.lbe.security=132592, hanjie.app.pureweathe
r=129236, com.tencent.mm=131437, me.piebridge.brevent=132545, com.tencent.mobile
qq=131482, com.coolapk.market=132491}
03-26 11:42:36.332 29842 29842 D BreventServer: recent: {com.quark.browser, com.
teslacoilsw.launcher, com.lbe.security, hanjie.app.pureweather, com.tencent.mm,
me.piebridge.brevent, com.tencent.mobileqq, com.coolapk.market, com.android.syst
emui}
03-26 11:42:36.332 29842 29842 D BreventServer: before getRunningProcesses, took
 7155ms
03-26 11:42:36.470 29842 29842 D BreventServer: after getRunningProcesses, took
7293ms
03-26 11:42:36.470 29842 29842 D BreventServer: inactive for com.quark.browser:
45, timeout: 600
03-26 11:42:36.470 29842 29842 D BreventServer: inactive for com.google.android.
googlequicksearchbox: 0, timeout: 600
03-26 11:42:36.470 29842 29842 D BreventServer: inactive for com.coolapk.market:
 101, timeout: 600
03-26 11:42:36.470 29842 29842 D BreventServer: before dumpProcesses, took 7293m
s
03-26 11:42:36.538 29842 29842 D BreventServer: after dumpProcesses, took 7361ms

03-26 11:42:36.538 29842 29842 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gms, com.coolapk.market}
03-26 11:42:36.538 29842 29842 D BreventServer: com.google.android.gms depended
by {com.oasisfeng.greenify, com.flyperinc.cornerfly}
03-26 11:42:36.538 29842 29842 D BreventServer: before isCharging, took 7361ms
03-26 11:42:36.538 29842 29842 D BreventServer: after isCharging, took 7361ms
03-26 11:42:36.538 29842 29842 D BreventServer: service: {}
03-26 11:42:36.539 29842 29842 D BreventServer: blocking: {com.google.android.go
oglequicksearchbox}
03-26 11:42:36.539 29842 29842 D BreventServer: before getVpn, took 7362ms
03-26 11:42:36.540 29842 29842 D BreventServer: after getVpn, took 7363ms
03-26 11:42:36.540 29842 29842 D BreventServer: vpn: null
03-26 11:42:36.540 29842 29842 D BreventServer: top: {com.quark.browser}
03-26 11:42:36.540 29842 29842 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
03-26 11:42:36.540 29842 29842 D BreventServer: current: com.quark.browser
03-26 11:42:36.540 29842 29842 D BreventServer: unsafe: {}
03-26 11:42:36.540 29842 29842 D BreventServer: final blocking: {com.google.andr
oid.googlequicksearchbox}
03-26 11:42:36.540 29842 29842 D BreventServer: notifications: {com.lbe.security
=[98, 98], hanjie.app.pureweather=[98], cn.ledongli.ldl=[98], com.tencent.mobile
qq=[17], me.bylife.oneplusnetspeed=[98], cn.mixiaoxiao.myappscreenmask=[10]}
03-26 11:42:36.540 29842 29842 D BreventServer: noRecent: {com.google.android.go
oglequicksearchbox}
03-26 11:42:36.540 29842 29842 D BreventServer: foreground service: {}
03-26 11:42:36.540 29842 29842 D BreventServer: gcm: {}
03-26 11:42:36.540 29842 29842 D BreventServer: before blocking, took 7363ms, si
ze: 1
03-26 11:42:36.540 29842 29842 D BreventServer: ignore com.google.android.google
quicksearchbox, wait for the service check
03-26 11:42:36.540 29842 29842 D BreventServer: after blocking, took 7363ms
03-26 11:42:36.540 29842 29842 D BreventServer: check and brevent, took 7363ms

前几天反馈0.9版本卡顿的时候，大大你说我能不能帮忙调试，很抱歉当时在准备考试，今天闲下来想了下可能是我当时会错了意。不知道大大指的调试是？

**Comment by liudongmiao** [comment]
> 03-26 11:42:29.186 29842 29842 D BreventServer: before dump notifications, took 9ms
> 03-26 11:42:36.331 29842 29842 D BreventServer: after getRecentPackages, took 7154ms

嗯，差不多就是这个。
你的机器上，获取通知信息非常慢。
慢到不可以接受。

由于通知慢，导致后续处理非常慢。你看通知花了 7154ms，后面总共也就 7363ms。
接下来，我会针对这样的机器，不检查通知，虽然有些功能没法使用，但比不使用好。

你也通过 dumpsys notifications 看看，一共花了多久。

另外，请发个邮件给我。

**Comment by linqi0816** [comment]
@liudongmiao 请问大大，邮件内容是？

**Comment by liudongmiao** [comment]
最新的测试版  0.9.4+3 及以上，可以允许关掉“检查通知”。
如果发现慢，请去设置中开启。

下载地址：https://piebridge.me/br/next/
