### ISSUE TITLE
老大有搞一个永久adb或者Android上无root操作吗？

### ISSUE THREAD

**Issue by LornBin** [liudongmiao/Brevent#305]
想给爸妈搞一个黑域，还有女朋友不过他们都没有root，重启就没辙了又没有root。老大是否有打算弄个永久adb，类似绿色那种？

**Comment by liudongmiao** [comment]
没有 ROOT 的话，不可能。

1. 如果真的可以，太可怕。试想某天你在外充电，突然出现调试警告，自己不小心点了…然后恶意应用使用这种手段，拥有了超高权限，你还去不掉，要恢复出厂设置。

2. 为什么 XX 应用，如XX，XXXX可以不用重新执行？我这么说，要是他们真的如此强大，也就没黑域啥事了吧。

**Comment by yc1234** [comment]
不root要什么安卓啊，你帮他们root了不就行了

**Comment by liudongmiao** [comment]
root 更不安全，除非你写一个自己的 root，只许自己指定的应用使用，其它的应用一律拒绝，并且家人还没法更改。
