### ISSUE TITLE
可以搞一个「处方」一样的阻止方案

### ISSUE THREAD

**Issue by wbsdty331** [liudongmiao/Brevent#306]
和绿色守护类似，采用 `XML` 或 `Json` 编写，用户可以自己编写处方，也可以导入处方对应用进行阻止。

我也希望 Brevent 能为 Android 应用生态带来带更好的风貌，
请作者考虑一下，谢谢！

**Comment by liudongmiao** [comment]
认真阅读，我的理念：http://www.jianshu.com/p/aa3395d04b6d

你的这个想法，不是给生态带来更好的风貌，而是更恶劣。

你自己就可以处理，自己搜索 intent firewall 就好。
