### ISSUE TITLE
一加3安卓6.0.1&0.9.2 root模式循环问题

### ISSUE THREAD

**Issue by digiw** [liudongmiao/Brevent#309]
这样一个操作情况，在xposed框架安装了阻止运行的情况下，开启黑域092的root模式很快能获取进程没问题；如果在框架禁用阻止运行并重启，重启后打开黑域092版点击root模式，则循环在root获取提示页，此时输入adb指令也无法获取日志，返回空白提示符：
G:\adb tools>adb -d shell setprop log.tag.BreventServer DEBUG

G:\adb tools>adb -d logcat -d -b main -s BreventServer BreventLoader

G:\adb tools>adb -d logcat -d -b main -s BreventServer BreventLoader

G:\adb tools>adb -d shell setprop log.tag.BreventServer DEBUG

G:\adb tools>adb -d logcat -d -b crash

G:\adb tools>adb -d logcat -d -b crash
- waiting for device -

G:\adb tools>adb -d logcat -d -b crash

G:\adb tools>adb -d logcat -d -b crash

G:\adb tools>adb -d logcat -d -b crash

G:\adb tools>adb -d logcat -d -b main -s BreventServer BreventLoader

G:\adb tools>adb -d shell setprop log.tag.BreventServer DEBUG
；

接着cmd窗口内输入启动黑域的命令，会执行成功，
G:\adb tools>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbrevent.so
checking..........brevent_server started, pid: 27271
checking for stable...........ok

if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

手机上显示再次获取进程，但还是会失败，循环在root获取窗口；但adb指令可以获取日志，日志如下：

G:\adb tools>adb -d logcat -d -b crash
03-26 22:46:14.935 21383 21383 F libc    : Fatal signal 13 (SIGPIPE), code 0 in tid 21383 (ping)
03-26 22:46:16.164   652   652 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-26 22:46:16.797   652   652 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus3/OnePlus3:6.0.1/MMB29M/386990:user/release-keys'
03-26 22:46:16.797   652   652 F DEBUG   : Revision: '0'
03-26 22:46:16.798   652   652 F DEBUG   : ABI: 'arm64'
03-26 22:46:16.798   652   652 F DEBUG   : pid: 21383, tid: 21383, name: ping  >>> ping <<<
03-26 22:46:16.798   652   652 F DEBUG   : signal 13 (SIGPIPE), code 0 (SI_USER), fault addr --------
03-26 22:46:16.804   652   652 F DEBUG   :     x0   ffffffffffffffe0  x1   0000007fb77a7000  x2   000000000000003c  x3   0000000000000055
03-26 22:46:16.804   652   652 F DEBUG   :     x4   0000007fb7820000  x5   0000007fb7821011  x6   0000007fb7820000  x7   0000007fb7821010
03-26 22:46:16.804   652   652 F DEBUG   :     x8   0000000000000040  x9   0000007fb7820000  x10  0000007fb7821012  x11  0000000000000000
03-26 22:46:16.804   652   652 F DEBUG   :     x12  0000007fb7820000  x13  0000007fb75ff090  x14  0000000000000000  x15  0000007fb7820000
03-26 22:46:16.805   652   652 F DEBUG   :     x16  0000007fb75ff158  x17  0000000000000000  x18  000000000000004c  x19  0000007fb7820000
03-26 22:46:16.805   652   652 F DEBUG   :     x20  0000007fb7820000  x21  0000007fb7821050  x22  0000007fb794c44c  x23  0000000000000000
03-26 22:46:16.805   652   652 F DEBUG   :     x24  0000007fb79bc610  x25  0000000000000000  x26  000000000000003b  x27  00000055711c80f0
03-26 22:46:16.805   652   652 F DEBUG   :     x28  0000000000000040  x29  0000007fd2f5c5f0  x30  0000007fb780f5d8
03-26 22:46:16.805   652   652 F DEBUG   :     sp   0000007fd2f5c5f0  pc   0000007fb794c454  pstate 0000000020000000
03-26 22:46:16.811   652   652 F DEBUG   :
03-26 22:46:16.811   652   652 F DEBUG   : backtrace:
03-26 22:46:16.811   652   652 F DEBUG   :     #00 pc 0000000000069454  /system/lib64/libc.so (write+8)
03-26 22:46:16.811   652   652 F DEBUG   :     #01 pc 00000000000035d4  /system/vendor/lib64/libcneconn.so (write+124)
03-26 22:46:16.811   652   652 F DEBUG   :     #02 pc 0000000000001364  /system/vendor/lib64/libNimsWrap.so (write+44)
03-26 22:46:16.811   652   652 F DEBUG   :     #03 pc 00000000000733a8  /system/lib64/libc.so (__swrite+76)
03-26 22:46:16.811   652   652 F DEBUG   :     #04 pc 0000000000055260  /system/lib64/libc.so (__sflush+104)
03-26 22:46:16.811   652   652 F DEBUG   :     #05 pc 000000000005531c  /system/lib64/libc.so (fflush+108)
03-26 22:46:16.811   652   652 F DEBUG   :     #06 pc 0000000000004a78  /system/bin/ping
03-26 22:46:16.812   652   652 F DEBUG   :     #07 pc 0000000000008494  /system/bin/ping
03-26 22:46:16.812   652   652 F DEBUG   :     #08 pc 0000000000002ee8  /system/bin/ping (main+2544)
03-26 22:46:16.812   652   652 F DEBUG   :     #09 pc 000000000001bd18  /system/lib64/libc.so (__libc_init+100)
03-26 22:46:16.812   652   652 F DEBUG   :     #10 pc 000000000000350c  /system/bin/ping
03-26 22:46:17.384   652   652 F DEBUG   :
03-26 22:46:17.384   652   652 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_02

G:\adb tools>adb -d logcat -d -b main -s BreventServer BreventLoader
03-26 22:52:28.974 27271 27271 D BreventServer: checking feelgood
03-26 22:52:28.975 27271 27271 D BreventServer: check and brevent
03-26 22:52:29.005 27271 27271 D BreventServer: before dump notifications, took 30ms
03-26 22:52:29.153 27271 27345 D BreventServer: received feelgood
03-26 22:52:29.436 27271 27271 D BreventServer: after dump notifications, took 461ms
03-26 22:52:29.851 27271 27271 D BreventServer: after dump widgets, took 876ms
03-26 22:52:29.852 27271 27271 D BreventServer: before dumpActivities, took 877ms
03-26 22:52:29.867 27271 27271 D BreventServer: after dumpActivities, took 892ms
03-26 22:52:29.867 27271 27271 D BreventServer: before getRecentPackages, took 892ms
03-26 22:52:29.871 27271 27271 D BreventServer: after getRecentPackages, took 896ms
03-26 22:52:29.871 27271 27271 D BreventServer: widgets: {com.orekie.search}
03-26 22:52:29.871 27271 27271 D BreventServer: running: {com.coolapk.searchbox=141, me.piebridge.brevent=666}
03-26 22:52:29.871 27271 27271 D BreventServer: recent: {com.teslacoilsw.launcher, cn.xm.xmvideoplayer, de.robv.android.xposed.installer, com.tencent.mm, me.piebridge.brevent, bin.mt.plus, com.dianping.movieheaven, com.chaozhuo.filemanager, com.coolapk.market, com.general.video, com.jc.rebootmanager}
03-26 22:52:29.871 27271 27271 D BreventServer: before getRunningProcesses, took 896ms
03-26 22:52:30.092 27271 27271 D BreventServer: after getRunningProcesses, took 1117ms
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.smi.wcloud: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.sankuai.meituan: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.tencent.androidqqmail: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.smzdm.client.android: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.ushaqi.zhuishushenqi: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.avatar.kungfufinance: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.dianping.v1: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.tradehero.th: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.mmmono.mono: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.yty.minerva: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.mingzhihuatong.muochi: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.android.vending: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.sdu.didi.psnger: 0, timeout: 0
03-26 22:52:30.092 27271 27271 D BreventServer: inactive for com.umetrip.android.msky.app: 0, timeout: 0
03-26 22:52:30.093 27271 27271 D BreventServer: inactive for com.xunlei.downloadprovider: 0, timeout: 0
03-26 22:52:30.093 27271 27271 D BreventServer: inactive for com.hengtiansoft.zhaike: 0, timeout: 0
03-26 22:52:30.093 27271 27271 D BreventServer: inactive for com.ttyongche: 0, timeout: 0
03-26 22:52:30.093 27271 27271 D BreventServer: inactive for video.vue.android: 0, timeout: 0
03-26 22:52:30.093 27271 27271 D BreventServer: inactive for com.environmentpollution.activity: 0, timeout: 0
03-26 22:52:30.093 27271 27271 D BreventServer: inactive for com.thestore.main: 0, timeout: 0
03-26 22:52:30.093 27271 27271 D BreventServer: inactive for cn.wiz.note: 0, timeout: 0
03-26 22:52:30.093 27271 27271 D BreventServer: inactive for net.luoo.LuooFM: 0, timeout: 0
03-26 22:52:30.093 27271 27271 D BreventServer: inactive for com.mirroon.spoon: 0, timeout: 0
03-26 22:52:30.093 27271 27271 D BreventServer: inactive for com.didapinche.booking: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.gbanker.gbankerandroid: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.myzaker.ZAKER_Phone: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.ricebook.highgarden: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.kaola: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.qzone: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.mobike.mobikeapp: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.theinitium.news: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.dailyyoga.cn: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.jingdong.app.mall: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for ctrip.android.view: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.starbucks.cn: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.kekeclient_: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.ymall.presentshop: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.taobao.taobao: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.wallstreetcn.news: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.cmbchina.ccd.pluto.cmbActivity: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.dp.android.elong: 0, timeout: 0
03-26 22:52:30.097 27271 27271 D BreventServer: inactive for com.eg.android.AlipayGphone: 0, timeout: 0
03-26 22:52:30.098 27271 27271 D BreventServer: inactive for com.beevle.xz.renxing.gdong: 0, timeout: 0
03-26 22:52:30.098 27271 27271 D BreventServer: before dumpProcesses, took 1123ms
03-26 22:52:30.300 27271 27271 D BreventServer: after dumpProcesses, took 1325ms
03-26 22:52:30.300 27271 27271 D BreventServer: com.google.android.webview depended by {com.smzdm.client.android, com.xunlei.downloadprovider, com.myzaker.ZAKER_Phone, com.ricebook.highgarden, com.iflytek.inputmethod, com.taobao.taobao, com.wallstreetcn.news, com.eg.android.AlipayGphone}
03-26 22:52:30.300 27271 27271 D BreventServer: com.google.android.gms depended by {com.android.vending, com.google.android.apps.walletnfcrel, com.starbucks.cn}
03-26 22:52:30.300 27271 27271 D BreventServer: before isCharging, took 1325ms
03-26 22:52:30.300 27271 27271 D BreventServer: after isCharging, took 1325ms
03-26 22:52:30.301 27271 27271 D BreventServer: service: {com.smzdm.client.android, com.ushaqi.zhuishushenqi, com.avatar.kungfufinance, com.tradehero.th, com.mmmono.mono, com.mingzhihuatong.muochi, com.umetrip.android.msky.app, com.xunlei.downloadprovider, com.hengtiansoft.zhaike, com.ttyongche, com.thestore.main, net.luoo.LuooFM, com.mirroon.spoon, com.didapinche.booking, com.gbanker.gbankerandroid, com.myzaker.ZAKER_Phone, com.ricebook.highgarden, com.qzone, com.mobike.mobikeapp, com.jingdong.app.mall, com.starbucks.cn, com.ymall.presentshop, com.taobao.taobao, com.cmbchina.ccd.pluto.cmbActivity, com.dp.android.elong, com.eg.android.AlipayGphone, com.beevle.xz.renxing.gdong}
03-26 22:52:30.301 27271 27271 D BreventServer: blocking: {com.smi.wcloud, com.sankuai.meituan, com.tencent.androidqqmail, com.smzdm.client.android, com.ushaqi.zhuishushenqi, com.avatar.kungfufinance, com.dianping.v1, com.tradehero.th, com.mmmono.mono, com.yty.minerva, com.mingzhihuatong.muochi, com.android.vending, com.sdu.didi.psnger, com.umetrip.android.msky.app, com.xunlei.downloadprovider, com.hengtiansoft.zhaike, com.ttyongche, video.vue.android, com.environmentpollution.activity, com.thestore.main, cn.wiz.note, net.luoo.LuooFM, com.mirroon.spoon, com.didapinche.booking, com.gbanker.gbankerandroid, com.myzaker.ZAKER_Phone, com.ricebook.highgarden, com.kaola, com.qzone, com.mobike.mobikeapp, com.theinitium.news, com.dailyyoga.cn, com.jingdong.app.mall, ctrip.android.view, com.starbucks.cn, com.kekeclient_, com.ymall.presentshop, com.taobao.taobao, com.wallstreetcn.news, com.cmbchina.ccd.pluto.cmbActivity, com.dp.android.elong, com.eg.android.AlipayGphone, com.beevle.xz.renxing.gdong}
03-26 22:52:30.301 27271 27271 D BreventServer: before getVpn, took 1326ms
03-26 22:52:30.318 27271 27271 D BreventServer: after getVpn, took 1343ms
03-26 22:52:30.318 27271 27271 D BreventServer: vpn: null
03-26 22:52:30.318 27271 27271 D BreventServer: top: {me.piebridge.brevent}
03-26 22:52:30.318 27271 27271 D BreventServer: home: {com.teslacoilsw.launcher}
03-26 22:52:30.318 27271 27271 D BreventServer: current: me.piebridge.brevent
03-26 22:52:30.318 27271 27271 D BreventServer: unsafe: {}
03-26 22:52:30.319 27271 27271 D BreventServer: final blocking: {com.smi.wcloud, com.sankuai.meituan, com.tencent.androidqqmail, com.smzdm.client.android, com.ushaqi.zhuishushenqi, com.avatar.kungfufinance, com.dianping.v1, com.tradehero.th, com.mmmono.mono, com.yty.minerva, com.mingzhihuatong.muochi, com.android.vending, com.sdu.didi.psnger, com.umetrip.android.msky.app, com.xunlei.downloadprovider, com.hengtiansoft.zhaike, com.ttyongche, video.vue.android, com.environmentpollution.activity, com.thestore.main, cn.wiz.note, net.luoo.LuooFM, com.mirroon.spoon, com.didapinche.booking, com.gbanker.gbankerandroid, com.myzaker.ZAKER_Phone, com.ricebook.highgarden, com.kaola, com.qzone, com.mobike.mobikeapp, com.theinitium.news, com.dailyyoga.cn, com.jingdong.app.mall, ctrip.android.view, com.starbucks.cn, com.kekeclient_, com.ymall.presentshop, com.taobao.taobao, com.wallstreetcn.news, com.cmbchina.ccd.pluto.cmbActivity, com.dp.android.elong, com.eg.android.AlipayGphone, com.beevle.xz.renxing.gdong}
03-26 22:52:30.319 27271 27271 D BreventServer: notifications: {}
03-26 22:52:30.319 27271 27271 D BreventServer: noRecent: {com.smi.wcloud, com.sankuai.meituan, com.tencent.androidqqmail, com.smzdm.client.android, com.ushaqi.zhuishushenqi, com.avatar.kungfufinance, com.dianping.v1, com.tradehero.th, com.mmmono.mono, com.yty.minerva, com.mingzhihuatong.muochi, com.android.vending, com.sdu.didi.psnger, com.umetrip.android.msky.app, com.xunlei.downloadprovider, com.hengtiansoft.zhaike, com.ttyongche, video.vue.android, com.environmentpollution.activity, com.thestore.main, cn.wiz.note, net.luoo.LuooFM, com.mirroon.spoon, com.didapinche.booking, com.gbanker.gbankerandroid, com.myzaker.ZAKER_Phone, com.ricebook.highgarden, com.kaola, com.qzone, com.mobike.mobikeapp, com.theinitium.news, com.dailyyoga.cn, com.jingdong.app.mall, ctrip.android.view, com.starbucks.cn, com.kekeclient_, com.ymall.presentshop, com.taobao.taobao, com.wallstreetcn.news, com.cmbchina.ccd.pluto.cmbActivity, com.dp.android.elong, com.eg.android.AlipayGphone, com.beevle.xz.renxing.gdong}
03-26 22:52:30.319 27271 27271 D BreventServer: foreground service: {com.tencent.androidqqmail, com.umetrip.android.msky.app, com.myzaker.ZAKER_Phone, com.qzone, com.taobao.taobao, com.wallstreetcn.news, com.eg.android.AlipayGphone}
03-26 22:52:30.319 27271 27271 D BreventServer: before blocking, took 1344ms, size: 43
03-26 22:52:30.343 27271 27271 D BreventServer: Force stop com.smi.wcloud(forceStop)
03-26 22:52:30.383 27271 27271 D BreventServer: Force stop com.sankuai.meituan(forceStop)
03-26 22:52:30.396 27271 27271 D BreventServer: Force stop com.tencent.androidqqmail(foreground service no notification)
03-26 22:52:30.535 27271 27271 D BreventServer: Force stop com.smzdm.client.android(service)
03-26 22:52:30.744 27271 27271 D BreventServer: Force stop com.ushaqi.zhuishushenqi(service)
03-26 22:52:30.767 27271 27271 D BreventServer: Force stop com.avatar.kungfufinance(service)
03-26 22:52:30.767 27271 27271 D BreventServer: ignore com.dianping.v1, wait for the service check
03-26 22:52:30.994 27271 27271 D BreventServer: Force stop com.tradehero.th(service)
03-26 22:52:32.271 27271 27271 D BreventServer: Force stop com.xunlei.downloadprovider(service)
03-26 22:52:32.291 27271 27271 D BreventServer: Force stop com.hengtiansoft.zhaike(service)
03-26 22:52:32.338 27271 27271 D BreventServer: Force stop com.ttyongche(service)
03-26 22:52:32.354 27271 27271 D BreventServer: Force stop video.vue.android(forceStop)
03-26 22:52:32.354 27271 27271 D BreventServer: ignore com.environmentpollution.activity, wait for the service check
03-26 22:52:32.706 27271 27271 D BreventServer: Force stop cn.wiz.note(forceStop)
03-26 22:52:33.105 27271 27271 D BreventServer: Force stop com.didapinche.booking(service)
03-26 22:52:33.371 27271 27271 D BreventServer: Force stop com.gbanker.gbankerandroid(service)
03-26 22:52:33.652 27271 27271 D BreventServer: Force stop com.myzaker.ZAKER_Phone(foreground service no notification)
03-26 22:52:33.828 27271 27271 D BreventServer: Force stop com.ricebook.highgarden(service)
03-26 22:52:33.923 27271 27271 D BreventServer: Force stop com.kaola(forceStop)
03-26 22:52:34.339 27271 27271 D BreventServer: Force stop com.qzone(foreground service no notification)
03-26 22:52:34.354 27271 27271 D BreventServer: Force stop com.mobike.mobikeapp(service)
03-26 22:52:34.354 27271 27271 D BreventServer: ignore com.theinitium.news, wait for the service check
03-26 22:52:34.592 27271 27271 D BreventServer: Force stop com.dailyyoga.cn(forceStop)
03-26 22:52:34.614 27271 27271 D BreventServer: Force stop com.jingdong.app.mall(service)
03-26 22:52:34.645 27271 27271 D BreventServer: Force stop ctrip.android.view(forceStop)
03-26 22:52:34.677 27271 27271 D BreventServer: Force stop com.starbucks.cn(service)
03-26 22:52:34.677 27271 27271 D BreventServer: ignore com.kekeclient_, wait for the service check
03-26 22:52:34.736 27271 27271 D BreventServer: Force stop com.ymall.presentshop(service)
03-26 22:52:34.844 27271 27271 D BreventServer: Force stop com.taobao.taobao(foreground service no notification)
03-26 22:52:34.879 27271 27271 D BreventServer: Force stop com.wallstreetcn.news(foreground service no notification)
03-26 22:52:34.900 27271 27271 D BreventServer: Force stop com.cmbchina.ccd.pluto.cmbActivity(service)

由于我安装了将近500个app的量，启动时是否这些app会先于黑域自启动导致系统已经卡出翔，所以会干扰黑域的正常root获取呢？
希望能支持到柳兄，酷安id：stoneh，需要的时候请@我，感谢你的辛勤付出！

**Comment by liudongmiao** [comment]
日志看起来无异常。请安装最新测试版，有问题再反馈，谢谢。

https://piebridge.me/br/next/
