### ISSUE TITLE
CM14.1 patch IntentResolver 失败

### ISSUE THREAD

**Issue by XGHeaven** [liudongmiao/Brevent#31]
系统：CM14.1 安卓7.1.1
设备：小米5

执行 patch 之后，提示我
为 IntentResolver 打了 0 处补丁，应该打 2 处。

[IntentResolver.smali.zip](https://github.com/liudongmiao/Brevent/files/698116/IntentResolver.smali.zip)

**Comment by liudongmiao** [comment]
已经打过补丁了，所以尽量找个原版的。

**Comment by XGHeaven** [comment]
意思就是我直接安装黑域就好了是么？
