### ISSUE TITLE
0.9.2/4耗电异常

### ISSUE THREAD

**Issue by heganyuliang** [liudongmiao/Brevent#312]
待机一晚，没有断网没有刻意清后台，掉了10%多的电 ，看详细耗电情况在不停地唤醒，应该是0.92新出现的情况。日志如下（但是都是最近几分钟的感觉没有用……）：
>03-27 10:07:49.592  5551  5551 D BreventServer: check and brevent
03-27 10:07:50.723  5551  5551 D BreventServer: network name:tun0 (tun0)
03-27 10:07:50.724  5551  5551 D BreventServer: check and brevent, took 1131ms
03-27 10:08:10.288  5551  5551 D BreventServer: check and brevent
03-27 10:08:10.443  5551  5551 D BreventServer: network name:tun0 (tun0)
03-27 10:08:10.449  5551  5551 D BreventServer: check and brevent, took 161ms
03-27 10:09:10.453  5551  5551 D BreventServer: check and brevent
03-27 10:09:10.703  5551  5551 D BreventServer: network name:tun0 (tun0)
03-27 10:09:10.713  5551  5551 D BreventServer: check and brevent, took 259ms
03-27 10:09:12.945  5551  5551 D BreventServer: checking feelgood
03-27 10:09:12.951  5551  5560 D BreventServer: received feelgood
03-27 10:09:24.669  5551  5551 D BreventServer: checking feelgood
03-27 10:09:24.672  5551  5560 D BreventServer: received feelgood
03-27 10:09:28.362  5551  5551 D BreventServer: check and brevent
03-27 10:09:28.515  5551  5551 D BreventServer: network name:tun0 (tun0)
03-27 10:09:28.518  5551  5551 D BreventServer: check and brevent, took 156ms
03-27 10:09:38.166  5551  5551 D BreventServer: checking feelgood
03-27 10:09:38.170  5551  5560 D BreventServer: received feelgood
03-27 10:09:38.841  5551  5551 D BreventServer: check and brevent
03-27 10:09:38.953  5551  5551 D BreventServer: network name:tun0 (tun0)
03-27 10:09:38.956  5551  5551 D BreventServer: check and brevent, took 114ms
03-27 10:09:46.688  5551  5551 D BreventServer: checking feelgood
03-27 10:09:46.694  5551  5560 D BreventServer: received feelgood
03-27 10:10:38.964  5551  5551 D BreventServer: check and brevent
03-27 10:10:39.247  5551  5551 D BreventServer: network name:tun0 (tun0)
03-27 10:10:39.260  5551  5551 D BreventServer: check and brevent, took 296ms
03-27 10:10:51.976  5551  5551 D BreventServer: check and brevent
03-27 10:10:51.990  5551  5551 D BreventServer: before dump notifications, took 14ms
03-27 10:10:52.077  5551  5551 D BreventServer: after dump notifications, took 101ms
03-27 10:10:52.084  5551  5551 D BreventServer: after dump widgets, took 108ms
03-27 10:10:52.084  5551  5551 D BreventServer: before dumpActivities, took 108ms
03-27 10:10:52.091  5551  5551 D BreventServer: after dumpActivities, took 114ms
03-27 10:10:52.091  5551  5551 D BreventServer: before getRecentPackages, took 115ms
03-27 10:10:52.093  5551  5551 D BreventServer: after getRecentPackages, took 117ms
03-27 10:10:52.094  5551  5551 D BreventServer: widgets: {com.google.android.googlequicksearchbox, com.oneplus.security, com.ruby.timetable, com.google.android.calendar, small.word, org.zooper.zwpro, com.netease.cloudmusic}
03-27 10:10:52.094  5551  5551 D BreventServer: running: {com.oneplus.deskclock=27889, com.tencent.mm=38357, me.piebridge.brevent=38541, com.xio.cardnews=38222, com.netease.cloudmusic=38467}
03-27 10:10:52.094  5551  5551 D BreventServer: recent: {com.github.shadowsocks, com.hupu.games, com.android.vending, com.tencent.mm, me.piebridge.brevent, rikka.appops, com.coolapk.market, com.android.systemui, com.xio.cardnews, net.oneplus.launcher, com.netease.cloudmusic}
03-27 10:10:52.094  5551  5551 D BreventServer: before getRunningProcesses, took 118ms
03-27 10:10:52.114  5551  5551 D BreventServer: after getRunningProcesses, took 138ms
03-27 10:10:52.114  5551  5551 D BreventServer: inactive for rikka.appops: 0, timeout: 3600
03-27 10:10:52.114  5551  5551 D BreventServer: inactive for com.coolapk.market: 0, timeout: 3600
03-27 10:10:52.114  5551  5551 D BreventServer: inactive for com.xio.cardnews: 321, timeout: 3600
03-27 10:10:52.114  5551  5551 D BreventServer: inactive for com.netease.cloudmusic: 76, timeout: 3600
03-27 10:10:52.114  5551  5551 D BreventServer: before dumpProcesses, took 138ms
03-27 10:10:52.162  5551  5551 D BreventServer: after dumpProcesses, took 186ms
03-27 10:10:52.162  5551  5551 D BreventServer: com.android.chrome depended by {com.google.android.googlequicksearchbox}
03-27 10:10:52.162  5551  5551 D BreventServer: com.google.android.gms depended by {com.github.shadowsocks, com.android.vending, com.google.android.gm, com.android.chrome, rikka.appops}
03-27 10:10:52.162  5551  5551 D BreventServer: before isCharging, took 186ms
03-27 10:10:52.162  5551  5551 D BreventServer: after isCharging, took 186ms
03-27 10:10:52.162  5551  5551 D BreventServer: service: {}
03-27 10:10:52.162  5551  5551 D BreventServer: blocking: {rikka.appops, com.coolapk.market}
03-27 10:10:52.162  5551  5551 D BreventServer: before getVpn, took 186ms
03-27 10:10:52.163  5551  5551 D BreventServer: network name:tun0 (tun0)
03-27 10:10:52.165  5551  5551 D BreventServer: after getVpn, took 189ms
03-27 10:10:52.165  5551  5551 D BreventServer: vpn: com.github.shadowsocks
03-27 10:10:52.165  5551  5551 D BreventServer: top: {me.piebridge.brevent}
03-27 10:10:52.165  5551  5551 D BreventServer: home: {com.android.systemui, net.oneplus.launcher}
03-27 10:10:52.166  5551  5551 D BreventServer: current: net.oneplus.launcher
03-27 10:10:52.166  5551  5551 D BreventServer: unsafe: {}
03-27 10:10:52.166  5551  5551 D BreventServer: final blocking: {rikka.appops, com.coolapk.market}
03-27 10:10:52.166  5551  5551 D BreventServer: notifications: {com.github.shadowsocks=[98]}
03-27 10:10:52.166  5551  5551 D BreventServer: noRecent: {}
03-27 10:10:52.166  5551  5551 D BreventServer: foreground service: {}
03-27 10:10:52.166  5551  5551 D BreventServer: gcm: {org.wordpress.android, org.telegram.messenger, com.google.android.apps.cultural, com.journey.app, cc.forestapp, rikka.searchbyimage, net.ia.iawriter, com.ajnsnewmedia.kitchenstories, rikka.appops, uk.co.economist, com.airbnb.android, net.skyscanner.android.main, com.ideashower.readitlater.pro}
03-27 10:10:52.166  5551  5551 D BreventServer: before blocking, took 190ms, size: 2
03-27 10:10:52.169  5551  5551 D BreventServer: after blocking, took 193ms
03-27 10:10:52.169  5551  5551 D BreventServer: check and brevent, took 193ms

**Comment by chenguangtu** [comment]
check and brevent太频繁了？

**Comment by liudongmiao** [comment]
事件触发的。

你可以看下测试版本，优化了黑屏后的情况。
但在我机器上，即使没有优化，也不会这么频繁。

下载地址：https://piebridge.me/br/next/

后续版本，优化成了，每次检查，必须隔 2 秒以上。
这个版本，优化成了，息屏情况下，精准检查。

关于耗电，你可以点开黑域，选择黑域服服务信息，查看相应的电脑。

**Comment by liudongmiao** [comment]
另外，再给日志时，先关掉调试。

```
adb -d shell setprop log.tag.BreventServer \"\"
```

**Comment by heganyuliang** [comment]
明白了。
但是前几个版本都没有这样，我感觉是不是0.9.2控制不如之前的有力？今天晚上再试试测试版。

**Comment by heganyuliang** [comment]
0.9.4测了两天，前天晚上开飞行模式掉电2%，昨天晚上没开掉电百分之十几……日志如下
>03-29 11:57:27.617  6200  6200 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
03-29 11:57:28.072  6211  6211 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]]
03-29 11:57:28.080  6211  6211 I BreventServer: Brevent Server 0.9.4 started
03-29 11:57:28.090  6211  6211 I BreventServer: brevent user: 0, uid: 2000
03-29 11:57:28.092  6211  6211 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-29 11:57:28.211  6211  6211 I BreventServer: loading brevent list
03-29 11:57:28.220  6211  6211 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 140
03-29 11:57:28.220  6211  6211 I BreventServer: loading brevent conf
03-29 11:57:28.272  6211  6211 D BreventServer: check and brevent
03-29 11:57:28.549  6211  6211 D BreventServer: Force stop org.telegram.messenger(priority service)
03-29 11:57:28.581  6211  6211 D BreventServer: Force stop com.netease.cloudmusic(noRecent)
03-29 11:57:28.624  6211  6211 D BreventServer: check and brevent, took 351ms
03-29 11:57:28.659  6211  6211 D BreventServer: sent first status

**Comment by liudongmiao** [comment]
怎么，黑域自动启动了呢？

会不会，昨晚其实是没有黑域作用的？
