### ISSUE TITLE
0.9 黑域显示不在运行的软件，打开软件信息页却还可以“强行停止”是为何

### ISSUE THREAD

**Issue by diskonline** [liudongmiao/Brevent#316]
三星Note5 安卓6 黑域0.9
华为荣耀6 安卓5.1.1 黑域0.9

曾经发现，一些在黑域中已经“没有运行”的app，如果打开绿色守护，却发现它们还在“待手动休眠”。如果实际从“设置”中打开这些app的详细信息，会发现“强行停止”按钮确实是可按的——这是不是表示这些软件其实还在运行？

荣耀6如果进入系统-应用程序-正在运行（Note5没有这个界面），会发现上述app确实没有出现在列表中，但是到“全部应用程序”中找到它们的详细信息页，“强行停止”按钮却也是可以按的，略诡异。

**Comment by aviraxp** [comment]
这两个没啥关系。那个强行停止与否的按钮状态是可以随意设置的。主要是为了能够接收 GCM。

**Comment by liudongmiao** [comment]
正在运行：正在运行的服务及进程 不要包含 未启用的启用之已启用
已经待机：正在运行的服务及进程 以及同时 未启用的应用之未启用
没有运行：不解释
如果你的系统不支持待机，就没有未启用的应用什么事

- 可以强行停止不代表在运行
   如好多应用，你打开后，重启，如果不自启，它们不会运行，但是可以强行停止
- 不能强行停止也不代表没有运行
   如系统好多内置的应用，你不能强行停止，但实际是运行的

不谦虚的说，我自认黑域和系统一样正确，如果不认同，建议直接卸载黑域。
不客气的说，你需要提升自己的知识水平，认真看下向导第四屏。

绿色守护的休眠，你去问冯老师去，不要问我。Android 哪里有休眠？
