### ISSUE TITLE
7.1  0.94版本黑域服务调试日志

### ISSUE THREAD

**Issue by linqi0816** [liudongmiao/Brevent#320]
已关闭允许FCM推送
日志如下
.tencent.mobileqq=3586, com.coolapk.market=3204}
03-27 22:35:23.957  7812  7812 D BreventServer: inactive for com.google.android.
googlequicksearchbox: 0, timeout: 600
03-27 22:35:23.957  7812  7812 D BreventServer: inactive for com.coolapk.market:
 396, timeout: 600
03-27 22:35:23.957  7812  7812 D BreventServer: check later(background) for com.
coolapk.market: 204
03-27 22:35:24.026  7812  7812 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gms}
03-27 22:35:24.026  7812  7812 D BreventServer: com.google.android.gms depended
by {in.zhaoj.shadowsocksr, com.flyperinc.cornerfly}
03-27 22:35:24.026  7812  7812 D BreventServer: service: {com.google.android.goo
glequicksearchbox}
03-27 22:35:24.026  7812  7812 D BreventServer: blocking: {com.google.android.go
oglequicksearchbox}
03-27 22:35:24.026  7812  7812 D BreventServer: top: {com.tencent.mobileqq}
03-27 22:35:24.026  7812  7812 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
03-27 22:35:24.026  7812  7812 D BreventServer: current: com.tencent.mobileqq
03-27 22:35:24.026  7812  7812 D BreventServer: unsafe: {}
03-27 22:35:24.026  7812  7812 D BreventServer: final blocking: {com.google.andr
oid.googlequicksearchbox}
03-27 22:35:24.026  7812  7812 D BreventServer: notifications: {in.zhaoj.shadows
ocksr=[98], hanjie.app.pureweather=[98], cn.ledongli.ldl=[98], cn.mixiaoxiao.mya
ppscreenmask=[10]}
03-27 22:35:24.026  7812  7812 D BreventServer: noRecent: {com.google.android.go
oglequicksearchbox}
03-27 22:35:24.026  7812  7812 D BreventServer: foreground service: {}
03-27 22:35:24.026  7812  7812 D BreventServer: sticky notification: {}
03-27 22:35:24.032  7812  7812 D BreventServer: Force stop com.google.android.go
oglequicksearchbox(service)
03-27 22:35:24.032  7812  7812 D BreventServer: check and brevent, took 6965ms
03-27 22:35:27.962  7812  7812 D BreventServer: check and brevent
03-27 22:35:34.186  7812  7812 D BreventServer: widgets: {com.oneplus.security,
cn.ledongli.ldl, small.word, com.xtuone.android.syllabus, com.netease.cloudmusic
, com.motorola.commandcenter3}
03-27 22:35:34.186  7812  7812 D BreventServer: running: {com.quark.browser=1501
, in.zhaoj.shadowsocksr=1057, com.tencent.mm=795, me.piebridge.brevent=1516, com
.tencent.mobileqq=1520, com.coolapk.market=1138}
03-27 22:35:34.186  7812  7812 D BreventServer: recent: {com.quark.browser=3556,
 in.zhaoj.shadowsocksr=3112, com.tencent.mm=2851, me.piebridge.brevent=3571, com
.tencent.mobileqq=3575, com.coolapk.market=3193}
03-27 22:35:34.211  7812  7812 D BreventServer: inactive for com.google.android.
googlequicksearchbox: 0, timeout: 600
03-27 22:35:34.211  7812  7812 D BreventServer: inactive for com.coolapk.market:
 406, timeout: 600
03-27 22:35:34.211  7812  7812 D BreventServer: check later(background) for com.
coolapk.market: 194
03-27 22:35:34.276  7812  7812 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gms}
03-27 22:35:34.276  7812  7812 D BreventServer: com.google.android.gms depended
by {in.zhaoj.shadowsocksr, com.flyperinc.cornerfly}
03-27 22:35:34.277  7812  7812 D BreventServer: service: {com.google.android.goo
glequicksearchbox}
03-27 22:35:34.277  7812  7812 D BreventServer: blocking: {com.google.android.go
oglequicksearchbox}
03-27 22:35:34.277  7812  7812 D BreventServer: top: {com.tencent.mobileqq}
03-27 22:35:34.277  7812  7812 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
03-27 22:35:34.277  7812  7812 D BreventServer: current: com.tencent.mobileqq
03-27 22:35:34.277  7812  7812 D BreventServer: unsafe: {}
03-27 22:35:34.277  7812  7812 D BreventServer: final blocking: {com.google.andr
oid.googlequicksearchbox}
03-27 22:35:34.277  7812  7812 D BreventServer: notifications: {in.zhaoj.shadows
ocksr=[98], hanjie.app.pureweather=[98], cn.ledongli.ldl=[98], cn.mixiaoxiao.mya
ppscreenmask=[10]}
03-27 22:35:34.277  7812  7812 D BreventServer: noRecent: {com.google.android.go
oglequicksearchbox}
03-27 22:35:34.277  7812  7812 D BreventServer: foreground service: {}
03-27 22:35:34.277  7812  7812 D BreventServer: sticky notification: {}
03-27 22:35:34.285  7812  7812 D BreventServer: Force stop com.google.android.go
oglequicksearchbox(service)
03-27 22:35:34.286  7812  7812 D BreventServer: check and brevent, took 6323ms
03-27 22:35:37.408  7812  7812 D BreventServer: check and brevent
03-27 22:35:43.416  7812  7812 D BreventServer: widgets: {com.oneplus.security,
cn.ledongli.ldl, small.word, com.xtuone.android.syllabus, com.netease.cloudmusic
, com.motorola.commandcenter3}
03-27 22:35:43.416  7812  7812 D BreventServer: running: {com.quark.browser=1501
, in.zhaoj.shadowsocksr=1057, com.tencent.mm=795, me.piebridge.brevent=1516, com
.tencent.mobileqq=1520, com.coolapk.market=1138}
03-27 22:35:43.416  7812  7812 D BreventServer: recent: {com.quark.browser=3547,
 in.zhaoj.shadowsocksr=3103, com.tencent.mm=2842, me.piebridge.brevent=3562, com
.tencent.mobileqq=3566, com.coolapk.market=3184}
03-27 22:35:43.518  7812  7812 D BreventServer: inactive for com.google.android.
googlequicksearchbox: 0, timeout: 600
03-27 22:35:43.518  7812  7812 D BreventServer: inactive for com.android.chrome:
 0, timeout: 600
03-27 22:35:43.518  7812  7812 D BreventServer: inactive for com.google.android.
apps.photos: 0, timeout: 600
03-27 22:35:43.518  7812  7812 D BreventServer: inactive for com.coolapk.market:
 415, timeout: 600
03-27 22:35:43.518  7812  7812 D BreventServer: check later(background) for com.
coolapk.market: 185
03-27 22:35:43.635  7812  7812 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gms}
03-27 22:35:43.635  7812  7812 D BreventServer: com.google.android.gms depended
by {in.zhaoj.shadowsocksr, com.flyperinc.cornerfly}
03-27 22:35:43.635  7812  7812 D BreventServer: service: {com.google.android.goo
glequicksearchbox}
03-27 22:35:43.635  7812  7812 D BreventServer: blocking: {com.google.android.go
oglequicksearchbox, com.android.chrome, com.google.android.apps.photos}
03-27 22:35:43.635  7812  7812 D BreventServer: top: {com.tencent.mobileqq}
03-27 22:35:43.635  7812  7812 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
03-27 22:35:43.635  7812  7812 D BreventServer: current: com.tencent.mobileqq
03-27 22:35:43.635  7812  7812 D BreventServer: unsafe: {}
03-27 22:35:43.635  7812  7812 D BreventServer: final blocking: {com.google.andr
oid.googlequicksearchbox, com.android.chrome, com.google.android.apps.photos}
03-27 22:35:43.635  7812  7812 D BreventServer: notifications: {in.zhaoj.shadows
ocksr=[98], hanjie.app.pureweather=[98], cn.ledongli.ldl=[98], cn.mixiaoxiao.mya
ppscreenmask=[10]}
03-27 22:35:43.635  7812  7812 D BreventServer: noRecent: {com.google.android.go
oglequicksearchbox, com.android.chrome, com.google.android.apps.photos}
03-27 22:35:43.635  7812  7812 D BreventServer: foreground service: {}
03-27 22:35:43.635  7812  7812 D BreventServer: sticky notification: {}
03-27 22:35:43.646  7812  7812 D BreventServer: Force stop com.google.android.go
oglequicksearchbox(service)
03-27 22:35:43.664  7812  7812 D BreventServer: Force stop com.android.chrome(fo
rceStop)
03-27 22:35:43.676  7812  7812 D BreventServer: Force stop com.google.android.ap
ps.photos(forceStop)
03-27 22:35:43.677  7812  7812 D BreventServer: check and brevent, took 6267ms
03-27 22:35:46.786  7812  7812 D BreventServer: check and brevent
03-27 22:35:52.500  7812  7812 D BreventServer: widgets: {com.oneplus.security,
cn.ledongli.ldl, small.word, com.xtuone.android.syllabus, com.netease.cloudmusic
, com.motorola.commandcenter3}
03-27 22:35:52.500  7812  7812 D BreventServer: running: {com.quark.browser=1501
, in.zhaoj.shadowsocksr=1057, com.tencent.mm=795, me.piebridge.brevent=1516, com
.tencent.mobileqq=1520, com.coolapk.market=1138}
03-27 22:35:52.500  7812  7812 D BreventServer: recent: {com.quark.browser=3538,
 in.zhaoj.shadowsocksr=3094, com.tencent.mm=2833, me.piebridge.brevent=3553, com
.tencent.mobileqq=3557, com.coolapk.market=3175}
03-27 22:35:52.543  7812  7812 D BreventServer: inactive for com.google.android.
googlequicksearchbox: 0, timeout: 600
03-27 22:35:52.543  7812  7812 D BreventServer: inactive for com.android.chrome:
 0, timeout: 600
03-27 22:35:52.543  7812  7812 D BreventServer: inactive for com.google.android.
apps.photos: 0, timeout: 600
03-27 22:35:52.543  7812  7812 D BreventServer: inactive for com.coolapk.market:
 424, timeout: 600
03-27 22:35:52.543  7812  7812 D BreventServer: check later(background) for com.
coolapk.market: 176
03-27 22:35:52.593  7812  7812 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gms}
03-27 22:35:52.593  7812  7812 D BreventServer: com.google.android.gms depended
by {in.zhaoj.shadowsocksr, com.flyperinc.cornerfly}
03-27 22:35:52.593  7812  7812 D BreventServer: service: {com.google.android.goo
glequicksearchbox}
03-27 22:35:52.593  7812  7812 D BreventServer: blocking: {com.google.android.go
oglequicksearchbox, com.android.chrome, com.google.android.apps.photos}
03-27 22:35:52.593  7812  7812 D BreventServer: top: {com.tencent.mobileqq}
03-27 22:35:52.593  7812  7812 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
03-27 22:35:52.593  7812  7812 D BreventServer: current: com.tencent.mobileqq
03-27 22:35:52.593  7812  7812 D BreventServer: unsafe: {}
03-27 22:35:52.593  7812  7812 D BreventServer: final blocking: {com.google.andr
oid.googlequicksearchbox, com.android.chrome, com.google.android.apps.photos}
03-27 22:35:52.593  7812  7812 D BreventServer: notifications: {in.zhaoj.shadows
ocksr=[98], hanjie.app.pureweather=[98], cn.ledongli.ldl=[98], cn.mixiaoxiao.mya
ppscreenmask=[10]}
03-27 22:35:52.593  7812  7812 D BreventServer: noRecent: {com.google.android.go
oglequicksearchbox, com.android.chrome, com.google.android.apps.photos}
03-27 22:35:52.593  7812  7812 D BreventServer: foreground service: {}
03-27 22:35:52.593  7812  7812 D BreventServer: sticky notification: {}
03-27 22:35:52.601  7812  7812 D BreventServer: Force stop com.google.android.go
oglequicksearchbox(service)
03-27 22:35:52.608  7812  7812 D BreventServer: Force stop com.android.chrome(fo
rceStop)
03-27 22:35:52.620  7812  7812 D BreventServer: Force stop com.google.android.ap
ps.photos(forceStop)
03-27 22:35:52.620  7812  7812 D BreventServer: check and brevent, took 5830ms
03-27 22:35:58.038  7812  7812 D BreventServer: check and brevent
03-27 22:36:03.822  7812  7812 D BreventServer: widgets: {com.oneplus.security,
cn.ledongli.ldl, small.word, com.xtuone.android.syllabus, com.netease.cloudmusic
, com.motorola.commandcenter3}
03-27 22:36:03.822  7812  7812 D BreventServer: running: {com.quark.browser=1502
, in.zhaoj.shadowsocksr=1057, com.tencent.mm=796, me.piebridge.brevent=1516, com
.tencent.mobileqq=1567, com.coolapk.market=1138}
03-27 22:36:03.822  7812  7812 D BreventServer: recent: {com.quark.browser=3527,
 in.zhaoj.shadowsocksr=3083, com.tencent.mm=2822, me.piebridge.brevent=3542, com
.tencent.mobileqq=3593, com.coolapk.market=3164}
03-27 22:36:03.846  7812  7812 D BreventServer: inactive for com.google.android.
googlequicksearchbox: 0, timeout: 600
03-27 22:36:03.846  7812  7812 D BreventServer: inactive for com.coolapk.market:
 436, timeout: 600
03-27 22:36:03.846  7812  7812 D BreventServer: check later(background) for com.
coolapk.market: 164
03-27 22:36:03.888  7812  7812 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gms}
03-27 22:36:03.888  7812  7812 D BreventServer: com.google.android.gms depended
by {in.zhaoj.shadowsocksr, com.flyperinc.cornerfly}
03-27 22:36:03.888  7812  7812 D BreventServer: service: {com.google.android.goo
glequicksearchbox}
03-27 22:36:03.888  7812  7812 D BreventServer: blocking: {com.google.android.go
oglequicksearchbox}
03-27 22:36:03.888  7812  7812 D BreventServer: top: {com.tencent.mobileqq}
03-27 22:36:03.888  7812  7812 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
03-27 22:36:03.888  7812  7812 D BreventServer: current: com.tencent.mobileqq
03-27 22:36:03.888  7812  7812 D BreventServer: unsafe: {}
03-27 22:36:03.888  7812  7812 D BreventServer: final blocking: {com.google.andr
oid.googlequicksearchbox}
03-27 22:36:03.888  7812  7812 D BreventServer: notifications: {in.zhaoj.shadows
ocksr=[98], hanjie.app.pureweather=[98], cn.ledongli.ldl=[98], cn.mixiaoxiao.mya
ppscreenmask=[10]}
03-27 22:36:03.888  7812  7812 D BreventServer: noRecent: {com.google.android.go
oglequicksearchbox}
03-27 22:36:03.888  7812  7812 D BreventServer: foreground service: {}
03-27 22:36:03.889  7812  7812 D BreventServer: sticky notification: {}
03-27 22:36:03.894  7812  7812 D BreventServer: Force stop com.google.android.go
oglequicksearchbox(service)
03-27 22:36:03.895  7812  7812 D BreventServer: check and brevent, took 5856ms
03-27 22:36:07.026  7812  7812 D BreventServer: check and brevent
03-27 22:36:14.795  7812  7812 D BreventServer: widgets: {com.oneplus.security,
cn.ledongli.ldl, small.word, com.xtuone.android.syllabus, com.netease.cloudmusic
, com.motorola.commandcenter3}
03-27 22:36:14.795  7812  7812 D BreventServer: running: {com.quark.browser=1502
, in.zhaoj.shadowsocksr=1057, com.tencent.mm=796, me.piebridge.brevent=1516, com
.tencent.mobileqq=1567, com.coolapk.market=1138}
03-27 22:36:14.795  7812  7812 D BreventServer: recent: {com.quark.browser=3516,
 in.zhaoj.shadowsocksr=3072, com.tencent.mm=2811, me.piebridge.brevent=3531, com
.tencent.mobileqq=3582, com.coolapk.market=3153}
03-27 22:36:14.824  7812  7812 D BreventServer: inactive for com.google.android.
googlequicksearchbox: 0, timeout: 600
03-27 22:36:14.824  7812  7812 D BreventServer: inactive for com.coolapk.market:
 447, timeout: 600
03-27 22:36:14.824  7812  7812 D BreventServer: check later(background) for com.
coolapk.market: 153
03-27 22:36:14.888  7812  7812 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gms}
03-27 22:36:14.888  7812  7812 D BreventServer: com.google.android.gms depended
by {in.zhaoj.shadowsocksr, com.flyperinc.cornerfly}
03-27 22:36:14.889  7812  7812 D BreventServer: service: {com.google.android.goo
glequicksearchbox}
03-27 22:36:14.889  7812  7812 D BreventServer: blocking: {com.google.android.go
oglequicksearchbox}
03-27 22:36:14.889  7812  7812 D BreventServer: top: {com.tencent.mobileqq}
03-27 22:36:14.889  7812  7812 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
03-27 22:36:14.889  7812  7812 D BreventServer: current: com.tencent.mobileqq
03-27 22:36:14.889  7812  7812 D BreventServer: unsafe: {}
03-27 22:36:14.889  7812  7812 D BreventServer: final blocking: {com.google.andr
oid.googlequicksearchbox}
03-27 22:36:14.889  7812  7812 D BreventServer: notifications: {in.zhaoj.shadows
ocksr=[98], hanjie.app.pureweather=[98], cn.ledongli.ldl=[98], cn.mixiaoxiao.mya
ppscreenmask=[10]}
03-27 22:36:14.889  7812  7812 D BreventServer: noRecent: {com.google.android.go
oglequicksearchbox}
03-27 22:36:14.889  7812  7812 D BreventServer: foreground service: {}
03-27 22:36:14.889  7812  7812 D BreventServer: sticky notification: {}
03-27 22:36:14.895  7812  7812 D BreventServer: Force stop com.google.android.go
oglequicksearchbox(service)
03-27 22:36:14.895  7812  7812 D BreventServer: check and brevent, took 7869ms
03-27 22:36:18.055  7812  7812 D BreventServer: check and brevent
03-27 22:36:25.052  7812  7812 D BreventServer: widgets: {com.oneplus.security,
cn.ledongli.ldl, small.word, com.xtuone.android.syllabus, com.netease.cloudmusic
, com.motorola.commandcenter3}
03-27 22:36:25.052  7812  7812 D BreventServer: running: {com.quark.browser=1501
, in.zhaoj.shadowsocksr=1057, com.tencent.mm=795, me.piebridge.brevent=1516, com
.tencent.mobileqq=1567, com.coolapk.market=1138}
03-27 22:36:25.052  7812  7812 D BreventServer: recent: {com.quark.browser=3505,
 in.zhaoj.shadowsocksr=3061, com.tencent.mm=2800, me.piebridge.brevent=3520, com
.tencent.mobileqq=3571, com.coolapk.market=3142}
03-27 22:36:25.107  7812  7812 D BreventServer: inactive for com.google.android.
googlequicksearchbox: 0, timeout: 600
03-27 22:36:25.107  7812  7812 D BreventServer: inactive for com.coolapk.market:
 457, timeout: 600
03-27 22:36:25.107  7812  7812 D BreventServer: check later(background) for com.
coolapk.market: 143
03-27 22:36:25.107  7812  7812 D BreventServer: inactive for com.google.android.
talk: 0, timeout: 600
03-27 22:36:25.181  7812  7812 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gms}
03-27 22:36:25.181  7812  7812 D BreventServer: com.google.android.gms depended
by {in.zhaoj.shadowsocksr, com.flyperinc.cornerfly}
03-27 22:36:25.181  7812  7812 D BreventServer: service: {com.google.android.goo
glequicksearchbox}
03-27 22:36:25.181  7812  7812 D BreventServer: blocking: {com.google.android.go
oglequicksearchbox, com.google.android.talk}
03-27 22:36:25.181  7812  7812 D BreventServer: top: {com.tencent.mobileqq}
03-27 22:36:25.181  7812  7812 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
03-27 22:36:25.181  7812  7812 D BreventServer: current: com.tencent.mobileqq
03-27 22:36:25.181  7812  7812 D BreventServer: unsafe: {}
03-27 22:36:25.181  7812  7812 D BreventServer: final blocking: {com.google.andr
oid.googlequicksearchbox, com.google.android.talk}
03-27 22:36:25.181  7812  7812 D BreventServer: notifications: {in.zhaoj.shadows
ocksr=[98], hanjie.app.pureweather=[98], cn.ledongli.ldl=[98], cn.mixiaoxiao.mya
ppscreenmask=[10]}
03-27 22:36:25.181  7812  7812 D BreventServer: noRecent: {com.google.android.go
oglequicksearchbox, com.google.android.talk}
03-27 22:36:25.181  7812  7812 D BreventServer: foreground service: {}
03-27 22:36:25.181  7812  7812 D BreventServer: sticky notification: {}
03-27 22:36:25.187  7812  7812 D BreventServer: Force stop com.google.android.go
oglequicksearchbox(service)
03-27 22:36:25.210  7812  7812 D BreventServer: Force stop com.google.android.ta
lk(forceStop)
03-27 22:36:25.210  7812  7812 D BreventServer: check and brevent, took 7153ms
03-27 22:36:28.388  7812  7812 D BreventServer: check and brevent
OnePlus3:/ $
还是要7000+ms，我觉得可能是一加的系统问题。。。。

**Comment by liudongmiao** [comment]
是的。直接 `time dumsys notification` 看看吧，不用管过程，只看结果花了多少秒就好。

**Comment by linqi0816** [comment]
@liudongmiao 大大，我用time dumsys notification看了下，在我对除用户软件外的系统软件电池不优化之后，测试三次基本在5s

**Comment by liudongmiao** [comment]
这个太慢。也就是说，只能不支持你的系统。

接下来我会发个版本，可以直接设置里勾选，不检查通知。

**Comment by linqi0816** [comment]
@liudongmiao 大大，我有个疑问，黑域不检查通知的话和检查通知的版本在效用上有什么区别吗

**Comment by liudongmiao** [comment]
#黑域# 约法三章
1. 没有黑域，活
2. 加入黑域，罪
3. 恶意唤醒，死

加入黑域罪，三章
1. 前台服务没通知（7.0之前漏洞利用者），死
1. 顽固通知：没有后台，死；不许同步，死(0.9.3及以后)；其他不处理
2. 带有通知：允许同步，不会死（但可能会待机）
3. 其他情况：退出应用或后台应用超时，待机；待机超时，死

恶意唤醒认定：打开服务，但是没有打开界面

也就是说，无法检查通知的话，一些场景无法使用:
1. 前台服务将无法运行，比如音乐类，下载类，你只能选择不处理
2. 允许同步呀，fcm 呀，基本是摆设，因为会被当成没有通知

还是很影响判断的。

目前从反馈来看，仅有小部分有这样的问题，所以下版本，倾向于去掉特殊处理。

**Comment by linqi0816** [comment]
感谢大大的解答
