### ISSUE TITLE
when adb shell open brevent service warning cannot listen port

### ISSUE THREAD

**Issue by JessyTang** [liudongmiao/Brevent#321]
When I input adb shell script it warning below. But I have use normally in 0.9.1 before.

here is the warning information!

 ./adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-27 22:41:34.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-27 22:41:34.000' -d -s BreventLoader BreventServer
03-27 22:41:35.584  4953  4953 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
03-27 22:41:36.430  4972  4972 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]]
03-27 22:41:36.431  4972  4972 I BreventServer: Brevent Server 0.9.4 started
03-27 22:41:36.442  4972  4972 I BreventServer: brevent user: 0, uid: 2000
03-27 22:41:36.443  4972  4972 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-27 22:41:36.505  4972  4972 I BreventServer: loading brevent list
03-27 22:41:36.508  4972  4972 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 72
03-27 22:41:36.509  4972  4972 I BreventServer: loading brevent conf
03-27 22:41:36.509  4972  4972 E BreventServer: Did you run as root, then run as shell?
03-27 22:41:36.526  4953  4953 E BreventLoader: worker 4972 exited with status 1
03-27 22:41:36.526  4953  4953 D BreventLoader: signal arrived, update: 0
03-27 22:41:36.527  4951  4951 D BreventLoader: worker 4953 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> Did you run as root, then run as shell?

You should have ROOTed, please delete files under `/data/user_de/0/com.android.shell`.

Or read guide - permissions, learn how to use ROOT mode.
