### ISSUE TITLE
094更新以后，新安装的app无法选择是否黑域以及允许同步

### ISSUE THREAD

**Issue by Loticyang** [liudongmiao/Brevent#322]
表现是，更新094之前就安装的app可以自由勾选是否黑域，以及允许同步，但是新安装的app则默认处于黑域状态，我无法使之取消黑域，也无法允许同步（尝试点击但是没有效果）。

系统7.0

E:\htc10lifestyle\黑域ADB>adb -d logcat -d -b main -s BreventServer BreventLoader
03-28 09:23:25.925  8669  8669 D BreventServer: check and brevent
03-28 09:23:26.136  8669  8669 D BreventServer: check again in 1577s
03-28 09:23:26.252  8669  8669 I BreventServer: remove package sogou.mobile.explorer
03-28 09:23:26.254  8669  8669 D BreventServer: check and brevent, took 328ms
03-28 09:23:33.541  8669  8669 D BreventServer: check and brevent
03-28 09:23:33.739  8669  8669 D BreventServer: check again in 1797s
03-28 09:23:33.819  8669  8669 I BreventServer: remove package sogou.mobile.explorer
03-28 09:23:33.820  8669  8669 D BreventServer: check and brevent, took 278ms

上面我用搜狗浏览器试了下，日志好像不完整

再尝试安装网易新闻看看
E:\htc10lifestyle\黑域ADB>adb -d logcat -d -b main -s BreventServer BreventLoader
03-28 09:29:33.493  8669  8669 D BreventServer: checking feelgood
03-28 09:29:33.504  8669  8679 D BreventServer: received feelgood
03-28 09:29:35.926  8669  8669 D BreventServer: checking feelgood
03-28 09:29:35.928  8669  8679 D BreventServer: received feelgood
03-28 09:29:40.819  8669  8669 D BreventServer: check and brevent
03-28 09:29:41.057  8669  8669 D BreventServer: widgets: {com.htc.launcher, fm.jihua.kecheng}
03-28 09:29:41.057  8669  8669 D BreventServer: running: {com.quark.browser=5881, com.htc.launcher=5831, com.tencent.mm=4793, com.htc.contacts=1942, me.piebridge.brevent=6330, com.tencent.mobileqq=6157, com.netease.newsreader.activity=6327, com.coolapk.market=6310, com.sina.weibo=2732}
03-28 09:29:41.058  8669  8669 D BreventServer: recent: {com.quark.browser=3145, com.tudou.android=1859, com.tencent.mm=2057, me.piebridge.brevent=3594, com.tencent.mobileqq=3421, com.netease.newsreader.activity=3591, com.coolapk.market=3574, com.android.settings=2332, tv.acfundanmaku.video=249, com.htc.filemanager=224, com.htcmarket=1966, com.netease.cloudmusic=1503, tv.danmaku.bili=1468}
03-28 09:29:41.080  8669  8669 D BreventServer: inactive for com.tencent.androidqqmail: 0, timeout: 1800
03-28 09:29:41.080  8669  8669 D BreventServer: inactive for com.tencent.mobileqq: 178, timeout: 1800
03-28 09:29:41.080  8669  8669 D BreventServer: check later(background) for com.tencent.mobileqq: 1622
03-28 09:29:41.080  8669  8669 D BreventServer: inactive for com.coolapk.market: 25, timeout: 1800
03-28 09:29:41.080  8669  8669 D BreventServer: check later(background) for com.coolapk.market: 1775
03-28 09:29:41.080  8669  8669 D BreventServer: inactive for com.htc.android.mail: 0, timeout: 1800
03-28 09:29:41.145  8669  8669 D BreventServer: com.prassein.sit.htc depended by {com.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
03-28 09:29:41.145  8669  8669 D BreventServer: com.google.android.webview depended by {com.netease.newsreader.activity, com.sina.weibo, com.baidu.tiebar}
03-28 09:29:41.145  8669  8669 D BreventServer: com.google.android.gms depended by {com.github.shadowsocks}
03-28 09:29:41.145  8669  8669 D BreventServer: service: {com.tencent.androidqqmail}
03-28 09:29:41.145  8669  8669 D BreventServer: blocking: {com.tencent.androidqqmail, com.htc.android.mail}
03-28 09:29:41.145  8669  8669 D BreventServer: top: {me.piebridge.brevent}
03-28 09:29:41.145  8669  8669 D BreventServer: home: {com.htc.launcher, com.android.systemui}
03-28 09:29:41.145  8669  8669 D BreventServer: current: com.htc.launcher
03-28 09:29:41.145  8669  8669 D BreventServer: unsafe: {}
03-28 09:29:41.145  8669  8669 D BreventServer: final blocking: {com.tencent.androidqqmail, com.htc.android.mail}
03-28 09:29:41.145  8669  8669 D BreventServer: notifications: {com.android.providers.media=[98], com.tencent.mobileqq=[34], com.coolapk.market=[16, 16]}
03-28 09:29:41.145  8669  8669 D BreventServer: noRecent: {com.tencent.androidqqmail, com.htc.android.mail}
03-28 09:29:41.145  8669  8669 D BreventServer: foreground service: {com.tencent.mobileqq}
03-28 09:29:41.146  8669  8669 D BreventServer: gcm: {}
03-28 09:29:41.146  8669  8669 D BreventServer: sticky notification: {com.tencent.mobileqq}
03-28 09:29:41.151  8669  8669 D BreventServer: Force stop com.tencent.androidqqmail(service)
03-28 09:29:41.158  8669  8669 D BreventServer: Force stop com.htc.android.mail(forceStop)
03-28 09:29:41.158  8669  8669 D BreventServer: check again in 1622s
03-28 09:29:41.240  8669  8669 I BreventServer: add package com.netease.newsreader.activity
03-28 09:29:41.292  8669  8669 I BreventServer: remove package sogou.mobile.explorer
03-28 09:29:41.294  8669  8669 D BreventServer: check and brevent, took 474ms
03-28 09:29:51.162  8669  8669 D BreventServer: checking feelgood
03-28 09:29:51.162  8669  8679 D BreventServer: received feelgood
03-28 09:29:52.176  8669  8669 D BreventServer: checking feelgood
03-28 09:29:52.176  8669  8679 D BreventServer: received feelgood
03-28 09:29:54.303  8669  8669 D BreventServer: check and brevent
03-28 09:29:54.448  8669  8669 D BreventServer: widgets: {com.htc.launcher, fm.jihua.kecheng}
03-28 09:29:54.448  8669  8669 D BreventServer: running: {com.quark.browser=5881, com.htc.launcher=5831, com.tencent.mm=4793, com.htc.contacts=1942, me.piebridge.brevent=6346, com.tencent.mobileqq=6157, com.netease.newsreader.activity=6327, com.coolapk.market=6310, com.sina.weibo=2731}
03-28 09:29:54.449  8669  8669 D BreventServer: recent: {com.quark.browser=3132, com.tudou.android=1846, com.tencent.mm=2044, me.piebridge.brevent=3598, com.tencent.mobileqq=3408, com.netease.newsreader.activity=3578, com.coolapk.market=3561, com.android.settings=2319, tv.acfundanmaku.video=236, com.htc.filemanager=211, com.htcmarket=1953, com.netease.cloudmusic=1490, tv.danmaku.bili=1455}
03-28 09:29:54.465  8669  8669 D BreventServer: inactive for com.tencent.mobileqq: 191, timeout: 1800
03-28 09:29:54.465  8669  8669 D BreventServer: check later(background) for com.tencent.mobileqq: 1609
03-28 09:29:54.465  8669  8669 D BreventServer: inactive for com.netease.newsreader.activity: 21, timeout: 1800
03-28 09:29:54.465  8669  8669 D BreventServer: check later(background) for com.netease.newsreader.activity: 1779
03-28 09:29:54.465  8669  8669 D BreventServer: inactive for com.coolapk.market: 38, timeout: 1800
03-28 09:29:54.466  8669  8669 D BreventServer: check later(background) for com.coolapk.market: 1762
03-28 09:29:54.522  8669  8669 D BreventServer: com.prassein.sit.htc depended by {com.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
03-28 09:29:54.522  8669  8669 D BreventServer: com.google.android.webview depended by {com.netease.newsreader.activity, com.sina.weibo, com.baidu.tiebar}
03-28 09:29:54.523  8669  8669 D BreventServer: com.google.android.gms depended by {com.github.shadowsocks}
03-28 09:29:54.523  8669  8669 D BreventServer: service: {}
03-28 09:29:54.523  8669  8669 D BreventServer: blocking: {}
03-28 09:29:54.523  8669  8669 D BreventServer: top: {me.piebridge.brevent}
03-28 09:29:54.523  8669  8669 D BreventServer: home: {com.htc.launcher, com.android.systemui}
03-28 09:29:54.523  8669  8669 D BreventServer: current: com.htc.launcher
03-28 09:29:54.523  8669  8669 D BreventServer: unsafe: {}
03-28 09:29:54.523  8669  8669 D BreventServer: final blocking: {}
03-28 09:29:54.523  8669  8669 D BreventServer: notifications: {com.android.providers.media=[98], com.tencent.mobileqq=[34], com.coolapk.market=[16, 16]}
03-28 09:29:54.523  8669  8669 D BreventServer: noRecent: {}
03-28 09:29:54.523  8669  8669 D BreventServer: foreground service: {com.tencent.mobileqq}
03-28 09:29:54.523  8669  8669 D BreventServer: sticky notification: {com.tencent.mobileqq}
03-28 09:29:54.523  8669  8669 D BreventServer: check again in 1609s
03-28 09:29:54.586  8669  8669 I BreventServer: add package com.netease.newsreader.activity
03-28 09:29:54.588  8669  8669 I BreventServer: remove package sogou.mobile.explorer
03-28 09:29:54.590  8669  8669 D BreventServer: check and brevent, took 286ms

**Comment by liudongmiao** [comment]
设置中可自由修改的。黑域，三点菜单，设置，自动更新。

**Comment by Loticyang** [comment]
我取消勾选“自动更新”以后，新安装的app默认不再黑域，我也无法通过勾选使之处于黑域的状态

**Comment by liudongmiao** [comment]
什么叫无法通过勾选？

1. 点击图标，能选择么？
2. 选择以后，能加入黑域么？
   如果选择已经黑域的，再点击加入黑域时，不会有任何行为。

**Comment by Loticyang** [comment]
我取消勾选“自动更新”以后，新安装的app默认不再黑域

点击图标，能选择上，但是，不能加入黑域

（柳大，我用黑域也有一段时间。是知道已经黑域的app再选黑域，不会有任何行为）

现在的情况是

如果我勾选“自动更新”，我再去安装app A，这个A默认处于黑域（这里正常），但是，我选中这个app，点击右上角的圆圈（即不再黑域），并不能达到“退出黑域”效果，app A 仍然处于黑域状态，并且，我再点击这个A，点击“允许同步”，点完也不会有任何变化。


如果我取消勾选“自动更新”，我再去安装app B, 那么这个B默认处于不黑域的状态（这里也正常），但是，我选中这个app，点击右上角的“圆圈叉”（即进入黑域），并不能达到“进入黑域”的效果。这个B我将会一直不能黑域它。

这个问题只针对我在更新094以后的新安装的app，在此之前安装的所有app全部正常，可以随意选中黑域或者退出黑域。

**Comment by liudongmiao** [comment]
发个邮件给我，黑域内反馈有邮箱。

**Comment by liudongmiao** [comment]
你机器上的描述，更像黑域服务已经退出，是 普通模式 还是 ROOT 模式？

**Comment by Loticyang** [comment]
普通模式，未root。实际上，黑域对“已经黑域的app”还是能正常工作的。邮件名为“新安装app无法黑域”，带几张截图。

**Comment by liudongmiao** [comment]
没有找到这样的邮件，请确认标题～或者正文说是你

**Comment by liudongmiao** [comment]
看你的机器，好像是 htc 的...  
htc 的机器，本来就有各种各样的问题...

能用则用，不能用则不用。
比如，它不能设置停止状态，导致 fcm 无法使用
比如，它无法检测到安装/卸载状态，目前是一个临时方案
比如，更多，等着你发现

**Comment by Loticyang** [comment]
标题是我忘记打。

的确，htc的rom的确问题很多，以前就有发现。

原以为sense现在做的很类似原生了，却还是有这么多不一样的地方

**Comment by liudongmiao** [comment]
下个版本起，我决定去掉去 htc 的兼容，哦，主要是以下行为：
- 安装或卸载应用没有事件
- 支持待机但无法设置停止状态，这个问题还小点

我估计你的问题，和第一个相关。

**Comment by Loticyang** [comment]
那就是以后不支持htc了？

很遗憾。

的确，htc和sony一样，在国内都属于小众的机器，但正因如此，很多机型网上并没有root相关教程，所以很多用户深受不能root管不住后台的苦恼，见到黑域非常惊喜，是因为黑域是第一个在不root的情况下做的这么好的省电类应用。

哎，也许我下一步应该试试root吧

**Comment by liudongmiao** [comment]
不是，是它有些基本的功能无法完备。上面我有说那两点。

**Comment by liudongmiao** [comment]
最新的测试版已经优化这个问题：https://piebridge.me/br/next/

但是，由于 htc 没有相应的事件，我也不知道该什么时候去更新应用列表。
所以，只有当你更新黑域清单时，出现了异常的应用，才会去检查。
虽然一定影响体验，但是总比不能黑域/不能取消黑域好。
