### ISSUE TITLE
一加3T执行adb shell time dumpsys notification日志

### ISSUE THREAD

**Issue by niexingithub** [liudongmiao/Brevent#323]
我使用的是一加3T，已ROOT，ROM是官方的氢OS公测第三版，Android7.1.1
  Group summaries:
    0m00.08s real     0m00.00s user     0m00.02s system

多执行了几次，结果如下：
  Group summaries:
    0m00.03s real     0m00.00s user     0m00.01s system

  Group summaries:
    0m00.03s real     0m00.01s user     0m00.00s system

  Group summaries:
    0m00.03s real     0m00.01s user     0m00.00s system

  Group summaries:
    0m00.04s real     0m00.00s user     0m00.01s system

如有其他问题，可发邮件383655168@qq.com或在酷安上@聶鑫

**Comment by liudongmiao** [comment]
你手机上，有解锁或者查看通知时卡顿情况么？另外，可以直接给 BreventServer 的日志，会说是否禁用了通知。

**Comment by niexingithub** [comment]
我有使用过程中并没有觉得卡顿。
我手机里安装了110多个软件。
没有加入黑域的软件有：
黑域，钛备份，输入法，微信，支付宝，中华万年历，EAS，Play商店，QQ，Skype，SuperSU。
别的我都加入了黑域。
你说的日志，是让我运行下面哪个命令呀？
2. 黑域服务日志(电脑命令行)：adb -d logcat -d -b main -s BreventServer BreventLoader
2.1 如果想开启黑域服务调试日志，请在电脑命令行中执行: adb -d shell setprop log.tag.BreventServer DEBUG 然后获取黑域服务日志

**Comment by niexingithub** [comment]
打开命令后再运行adb shell time dumpsys notification吗？

**Comment by liudongmiao** [comment]
不卡顿就行了～
