### ISSUE TITLE
关于一些手机获取通知时间过长的一些处理建议

### ISSUE THREAD

**Issue by chenguangtu** [liudongmiao/Brevent#325]
既然程序上能够知道过去一次通知需要的时间，这样的话能不能做到根据这个时间动态调整黑域后台获取通知的间隔，比如一台手机需要5秒以上才能获取的，那么起码半分钟或者一分钟才刷新一次

**Comment by liudongmiao** [comment]
影响体验。本来就是事件驱动，会有更多的人问怎么怎么不生效。

以及，目前是事件机制，只有一个线程，如果这里 block 了，所有的消息都会堆积，并且几乎是放内存里的。

下个版本，我决定开启硬限制，一旦发现，立即退出，表明不支持这样的系统。

**Comment by liudongmiao** [comment]
最新的 0.9.4+3 及以上，有一个选项，检查通知，默认关闭。

开启之后，对于允许同步应用，一律当成有通知；不允许同步应用，一律当成没有通知。

**Comment by chenguangtu** [comment]
开启“检查通知”的选项，对于允许同步应用，一律当成有通知；不允许同步应用，一律当成没有通知。这样的话，手机卡顿应该打开这个开关吗？

**Comment by liudongmiao** [comment]
这个开关就是给手机卡顿专设的。

如果你手机卡顿，请去下载体验：https://piebridge.me/br/next
更建议找厂商修这个问题
