### ISSUE TITLE
一加3T 0.8.5 未root启动黑域出现cannot listen port

### ISSUE THREAD

**Issue by musicyy** [liudongmiao/Brevent#326]
--- crash start ---
>>> logcat -b crash -t '03-28 12:32:40.000' -d
03-28 12:32:41.066 10955 10955 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-28 12:32:41.066 10955 10955 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-28 12:32:41.066 10955 10955 E AndroidRuntime: 	at java.io.FileOutputStream.open(Native Method)
03-28 12:32:41.066 10955 10955 E AndroidRuntime: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-28 12:32:41.066 10955 10955 E AndroidRuntime: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-28 12:32:41.066 10955 10955 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-28 12:32:41.066 10955 10955 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-28 12:32:41.066 10955 10955 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-28 12:32:41.066 10955 10955 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:276)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: Error reporting crash
03-28 12:32:41.067 10955 10955 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:651)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:55)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3293)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3292)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:93)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:111)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-28 12:32:41.067 10955 10955 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-28 12:32:40.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
不对旧版提供任何支持。

你这个问题，大约是你使用 root 运行过。然后现在想以 adb 运行。

**Comment by musicyy** [comment]
OK 定位很准确，已解决。
