### ISSUE TITLE
moto xt1570，黑域0.94，执行ADB出错。

### ISSUE THREAD

**Issue by timelord11th** [liudongmiao/Brevent#327]
C:\Windows\system32>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm64/libbrevent.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-28 13:03:21.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-28 13:03:21.000' -d -s BreventLoader BreventServer
03-28 13:03:22.357  1182  1182 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
03-28 13:03:22.792  1206  1206 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-28 13:03:22.792  1206  1206 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-28 13:03:22.797  1206  1206 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
03-28 13:03:22.806  1206  1206 I BreventServer: Brevent Server 0.9.4 started
03-28 13:03:22.815  1206  1206 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-28 13:03:22.816  1206  1206 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-28 13:03:22.823  1206  1206 I BreventServer: brevent user: 0, uid: 2000
03-28 13:03:22.825  1206  1206 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-28 13:03:22.922  1206  1206 I BreventServer: loading brevent list
03-28 13:03:22.931  1206  1206 E BreventServer: Did you run as root, then run as shell?
03-28 13:03:22.969  1182  1182 E BreventLoader: worker 1206 exited with status 1
03-28 13:03:22.969  1182  1182 D BreventLoader: signal arrived, update: 0
03-28 13:03:22.971  1180  1180 D BreventLoader: worker 1182 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> 03-28 13:03:22.931 1206 1206 E BreventServer: Did you run as root, then run as shell?

你之前以 root 方式运行过，然后现在以 adb 模式运行。

**Comment by timelord11th** [comment]
0.83时曾用过root模式，后来卸载装了0.94

**Comment by liudongmiao** [comment]
使用 root 帐号，去删除 /data/user/0/com.android.shell 下的文件。

**Comment by timelord11th** [comment]
谢谢，已解决。
