### ISSUE TITLE
除了Owner之外，其他用户无法正常使用Brevent

### ISSUE THREAD

**Issue by Losses** [liudongmiao/Brevent#329]
在高版本Android的其他用户当中安装并启动本程序将无法正常加载进程列表、疯狂弹出设置引导（显示adb命令的那个对话框）。
这个有解么……

**Comment by liudongmiao** [comment]
不支持其它用户，只支持机主。

这种高级功能，参见我的说法：http://www.jianshu.com/p/aa3395d04b6d

这是一个重要的收费模式，我还没想好要不要支持。一般用户，真的用不着这个。

**Comment by Losses** [comment]
额，用来隔离软件防止其获得自己的隐私信息，单独开用户是一个不错的方法。

如果支持这个功能的话我会付费的w

**Comment by liudongmiao** [comment]
你都单开了一个用户，不如多开几个用户。在那里，它谁也找不到，谁也唤不醒。

这样的需求太少，我自己目前也不使用，以后再说了。

**Comment by Losses** [comment]
切换到主用户之后其他用户的进程是不唤醒的嘛？受教了 =3=~

**Comment by liudongmiao** [comment]
基本上无法唤醒。但不排除某些应用有了权限以后，可以访问另外一个用户的资源。

**Comment by Losses** [comment]
没……我切换到Owner之后，子用户的QQ响了Owner上会有声音……
好可怕……

**Comment by liudongmiao** [comment]
那给个日志，你要开 VERBOSE 级别了。

我考虑以后支持这种情况。

但是，估计是一个必须要捐赠的功能了。

**Comment by liudongmiao** [comment]
就目前来说，没有任何计划做这个功能。虽然，之前想在 1.2 中实现这个。
