### ISSUE TITLE
选中操作

### ISSUE THREAD

**Issue by imbear** [liudongmiao/Brevent#332]
常见应用中，点单是选中条目，长按不放才弹出菜单
现在黑域是单点就弹出菜单，操作起来有些不方便

黑域0.9.4

**Comment by liudongmiao** [comment]
先更正一点：点击选中条目这是不正确的，某些应用会这样，可能只是它没有上下文菜单。
其它的应用，如 Play Store, Gmail, Inbox，绝大部分情况下，点击都不是选择。

最早，长按是选择（当然，选择了以后有菜单），具体参见 Play Store，Gmail，Inbox 等应用。
后来，觉得增加点击图标表示选择的比较好，具体参见 Gmail, Inbox 等应用，于是给出提示。
在这种情况下，点击图标与长按都可以选择。

接下来，由于引入了“允许同步”的概念，需要更加快捷的告知用户如果处理允许同步。
我发现，说点击时，用户可能会点到图标那里去，所以恢复长按弹出上下文菜单的做法。
长按弹出上下文菜单，这也是 Android 默认行为。具体参考这次改动: fdff3c5390614212ac95225599025b80009d1c97
目前来说，你的困惑只有一点，单点非图标外的，到底是想干啥。

对于 Gmail 与 非选择模式下的 单点非图标，都是打开邮件。
而为了用户体验一致性，个人觉得，使用 Gmail 这种统一设定，比较好。
不同模式点击同一个地方，出现不一样的体验，更加不确定性。
所以，我选择像 Gmail 一样，点击非图标外，统一体验。参考 3d8e8323c2cc6f70df76ae15d1193637e5e45557
同时没有选择时，给出明显提示。参考 be4928d0a8ad05b2b4240a90ef7f4a9c1a6a2e4b

那么，点击非图标外，到底是干啥。
对于 Gmail 与 Inbox，点击是打开邮件（反正不是选择），进行具体操作。
而对于黑域来说，并没有具体操作，如果说有的话，设置“允许同步”可能性更大一些。
所以，就全部把事件弄成上下文菜单。

点击事件，可以参考这个文件的改动记录。
https://github.com/liudongmiao/Brevent/commits/master/brevent/src/main/java/me/piebridge/brevent/ui/AppsItemAdapter.java

BTW，我虽然是开发者，更是用户。
黑域的很多设定，都来源于自己的实际操作，如 Back / Home, 最近任务列表, 以及最近引入的通知。

**Comment by imbear** [comment]
原来是点击图标选中条目！虽然也用Gmail，不过真没在意

谢谢了～～

**Comment by imbear** [comment]
原来是点击图标选中条目！虽然也用Gmail，不过真没在意

谢谢了～～

**Comment by liudongmiao** [comment]
看来是早期用户～最近的话，就会出这个提示了：
> 黑域服务已成功启动。请点击图标，选择一些应用，然后黑域它们

现在的话，只有这一个方式可以选中条目吧。
呃，你不会以为，每次都要弹出菜单，然后点一次选择吧...

**Comment by liudongmiao** [comment]
经你这么一说，有个 BUG，使用上下文菜单选择的时候，一次只能选择一个...

**Comment by liudongmiao** [comment]
下个版本里，我将去掉上下文菜单中的选择功能

**Comment by imbear** [comment]
“一次只能选择一个……”

是的，我最初也是因为这样操作太过麻烦才来提这个的

**Comment by liudongmiao** [comment]
因为我确实没这么用过。

要是我自己使用，发现只能这样选择，然后一次还只能一次，早骂自己笨蛋，早改了。

接下来，我有逐步去掉自己不用的功能，但是会保留一些兼容性的方案，如 htc 的，一加的，强迫症的。

**Comment by liudongmiao** [comment]
上下文菜单中已经把选择改为了“选择/取消选择”，点击意义和图标一样。
请前往下载测试 https://piebridge.me/br/next/

请给我发邮件，我好赠送你一个Play版的特别贡献优惠。

**Comment by imbear** [comment]
谢谢～～

2017年3月30日 07:35，"Liu DongMiao" <notifications@github.com>写道：
