### ISSUE TITLE
0.9.4输入命令后报错

### ISSUE THREAD

**Issue by sz2git** [liudongmiao/Brevent#335]
一加3 氧OS 4.0.3 Android7.0
之前用过补丁版的，现在是装的是play版，但是没法启用

checking...brevent_server started, pid: 16418
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-29 15:02:46.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-29 15:02:46.000' -d -s BreventLoader BreventServer
03-29 15:02:47.665 16407 16407 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
03-29 15:02:48.031 16418 16418 W BreventServer: Can't find Settings.Secure.QS_TILES
03-29 15:02:48.036 16418 16418 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]]
03-29 15:02:48.037 16418 16418 I BreventServer: Brevent Server 0.9.4 started
03-29 15:02:48.043 16418 16418 W BreventServer: Can't find Settings.Secure.QS_TILES
03-29 15:02:48.045 16418 16418 I BreventServer: brevent user: 0, uid: 2000
03-29 15:02:48.046 16418 16418 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-29 15:02:48.224 16418 16418 I BreventServer: loading brevent list
03-29 15:02:48.228 16418 16418 E BreventServer: Did you run as root, then run as shell?
03-29 15:02:48.254 16407 16407 E BreventLoader: worker 16418 exited with status 1
03-29 15:02:48.254 16407 16407 D BreventLoader: signal arrived, update: 0
03-29 15:02:48.255 16405 16405 D BreventLoader: worker 16407 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> 03-29 15:02:48.228 16418 16418 E BreventServer: Did you run as root, then run as shell?

你之前以 ROOT 运行过，然后现在想以 shell 运行。

解决方法：
1. 继续使用 ROOT 运行
2. 使用 ROOT 帐号，删除 /data/user_de/0/com.android.shell 下的内容
