### ISSUE TITLE
突然加载列表卡机，网络不能使用

### ISSUE THREAD

**Issue by Bob021** [liudongmiao/Brevent#337]
[崩溃日志.txt](https://github.com/liudongmiao/Brevent/files/878531/default.txt)
[服务日志.txt](https://github.com/liudongmiao/Brevent/files/878533/default.txt)
![screenshot_20170329-161742](https://cloud.githubusercontent.com/assets/26019873/24448512/0a360344-143a-11e7-8f0e-519aaefd227e.png)

**Comment by liudongmiao** [comment]
这种情况确实有。先划掉它，接着用吧。

**Comment by Bob021** [comment]
好的，频率不多，第一次出现。

**Comment by liudongmiao** [comment]
看下最新测试版吧：https://piebridge.me/br/next/

我本地使用这个版本以后，没有再重现过了。

**Comment by Bob021** [comment]
测试2天，问题没有复现，谢谢柳大 。
