### ISSUE TITLE
一加三7.1 黑域版本0.94＋3 time dumpsys notification

### ISSUE THREAD

**Issue by linqi0816** [liudongmiao/Brevent#338]

**Comment by linqi0816** [comment]
Group summaries:
  0m03.98s real     0m00.00s user     0m00.02s system

Group summaries:
  0m03.85s real     0m00.03s user     0m00.01s system
虽然测试两次显示有延迟，但实际使用关闭获取通知之后没有出现卡顿。万分感谢作者大大的辛勤付出

**Comment by liudongmiao** [comment]
哎，这也是没有办法的事，还是找厂商修这个问题吧。
