### ISSUE TITLE
一加三7.1 黑域0.94＋3版本time dumpsys notification

### ISSUE THREAD

**Issue by linqi0816** [liudongmiao/Brevent#340]
Group summaries:
  0m03.98s real     0m00.00s user     0m00.02s system

Group summaries:
  0m03.85s real     0m00.03s user     0m00.01s system
虽然测试有延迟，但在关闭了获取通知之后正常使用不卡顿。

**Comment by liudongmiao** [comment]
好的。

但是，你也要明白，这是 ROM 关系，并非黑域问题。
当然，黑域也没有更好方式支持这种情况。

当然，如果是我自己用的话，我大概会新个应用，给予通知权限，然后黑域服务与之交互。
但也不够 smart 。。。为了通知，还得使用另外一个应用，不如见到允许同步应用，一律当成有通知。
