### ISSUE TITLE
后续#231问题

### ISSUE THREAD

**Issue by bensona1** [liudongmiao/Brevent#341]
谢谢作者回复。已经测试了测试版 开启了打开黑域界面后立即清理 但是并没有生效 我导出了日志记录给您参考，麻烦看下是什么原因 辛苦啦
[日志文件.txt](https://github.com/liudongmiao/Brevent/files/879177/default.txt)

**Comment by liudongmiao** [comment]
日志太多，反而无法看到问题。

请重新获取日志，只需要给黑域的就行，商店详情里有获取方法。
同时，重新描述问题～。

关于处理机制，请参看：http://coolapk.com/feed/2954866
