### ISSUE TITLE
黑 域 0.9.4 应用 计时 失效

### ISSUE THREAD

**Issue by lethe07** [liudongmiao/Brevent#342]
之前反馈被关闭了，说是不正常back的第三个变种，强停应用和启动器就好。
可是这个问题出现期间只打开黑域，没打开过别的，甚至问题应用也是home返回，之后黑域计时不正确，划掉黑域之后再进黑域又是重新给问题应用计时。

**Comment by liudongmiao** [comment]
1. 强行停止问题应用
2. 强行停止主屏幕应用

黑域使用系统 API 来判断离开时长，这个时间，是系统给的。

**Comment by lethe07** [comment]
问题应用之前版本没有过这种问题，而且这问题不是每次都出现。
强停启动器，换启动器问题也存在。

**Comment by liudongmiao** [comment]
那是两个步骤，不是选择。

1. 为什么不再处理非正常 Back？不再多说，简单点就是，处理不好

2. 你可以怎么做？不要使用 Back，杀了它。

3. 为什么以前支持，现在不支持？以前我错了。

**Comment by lethe07** [comment]
开发者你好
在使用中，退出应用我都是按的home，没有选择back，也出现了这个问题。
如果这是非正常Bcak，以前得处理非正常back就很好啊？可能有些情况下处理不好，那可以把这个加到隐藏或者需要捐增开启里面吗？
谢谢开发者的耐心

**Comment by liudongmiao** [comment]
支持困难，效果有限。

**Comment by lethe07** [comment]
请求加在捐赠功能……和之前差不多也好😅😅😅😅

**Comment by amdth** [comment]
你这应该是强迫症吧，反正过几分钟就停止了，要不然就手动划掉！

**Comment by lethe07** [comment]
问题是计时不准确！等于黑域不会自动处理后台！全靠手动

**Comment by liudongmiao** [comment]
又不是我的问题，怼他去。

黑域只是根据系统读数据。

**Comment by lethe07** [comment]
开发者好
我没有说是您的问题，看上面您得回复我知道这是因为非正常back导致的，看您回复以前是支持处理非正常back这种情况的，可能您对处理方式不满意所以在新版本上取消了这功能。
只是盼望能加回这个功能，哪怕是捐赠也好。
我没有埋怨您是您造成了这个问题。
如果造成了困扰或者影响到开发者了，非常抱歉。
希望黑域更加完善，感谢开发者的黑域。

**Comment by amdth** [comment]
@lethe07 
1 非正常back并不会影响手机的性能，强迫症而已！也就是在laoda看来以前支持此选项是错误的。
2 “home返回，之后黑域计时不正确，划掉黑域之后再进黑域又是重新给问题应用计时。”laoda针对的是这段话，根据系统读数据，并没有问题。

**Comment by lethe07** [comment]
明白了
我理解不不影响性能，甚至以前我都是直接划掉应用，不会交给黑域处理。
现在交给黑域反而导致不会自动处理后台了就反馈下。
谢谢

**Comment by liudongmiao** [comment]
接下来，我会尝试使用新的机制来处理这个非正常 Back。

但是，如果你的情况，不是由 Back 造成（我不相信这一点），就没有办法了。
所有的时间，都是由 `dumpsys activity activities` 中的 inactive for 字段而来。

**Comment by lethe07** [comment]
我没有不相信哒……期待接下来的新机制处理

**Comment by ffxk** [comment]
希望一切都好
