### ISSUE TITLE
无法启动黑域 Command not found

### ISSUE THREAD

**Issue by EircL** [liudongmiao/Brevent#344]
用的是MAC OS 按照步骤下载了platform 也根据指示进去了adb 但是在运行那行命令的时候显示command not found.

**Comment by liudongmiao** [comment]
参见这个文档里，里面有截图  https://piebridge.me/br/br.pdf

重点时，直接把 adb 拖到终端里，同时，去掉重复的 adb

**Comment by EircL** [comment]
开心 感谢开发者 进去了 主要是复制那一行命令的时候没有写前面的一段/user/apple 的信息 还是谢谢你 这么快给回复 有机会的话会给捐赠！

**Comment by liudongmiao** [comment]
你帮忙看看，向导 - ADB 那里，改成什么可以更好一些呢。这样可以让更多人上手～

**Comment by EircL** [comment]
首先有一个问题 将adb拖进去的时候 要自行加上devices 这一个词 其次那一行命令行复制进去的时候 前面记得要打上 那段/user/你的用户名/platform所在的文件夹 直接复制是不行的

**Comment by liudongmiao** [comment]
呃，我以为我说的，拖进去以后，带了 adb，变成了 /path/to/adb ，然后提示了去掉重复的 adb。。

我以为就是这个样子

1. 拖进去，/user/你的用户名/platform所在的文件夹/adb
2. 复制去掉重复的 adb，变成 /user/你的用户名/platform所在的文件夹/adb -d shell ....

你看看，怎么才能描述清楚这个事情呢？

**Comment by EircL** [comment]
我觉得首先要告诉他们 如果手机连接好的话 黑域的那个向导会有显示（已连接）我就是一开始连接不上出问题 其次告诉他们拖进去之后要打 adb devices 并且显示 attached decvices list等字样 最后在复制那行命令行的时候 记得变成/user/你的用户名/platform所在的文件夹/adb -d shell ....

**Comment by EircL** [comment]
“拖进去，/user/你的用户名/platform所在的文件夹/adb”这部分应改成 /platfrom所在的文件夹/adb devices. 不然虽然会出现一大段命令 但是无法进行下一步

**Comment by GongJianwei** [comment]
我提供一个想法
Windows: 按下“开始”+ R 组合键，输入“cmd”并回车，在弹出的窗口中输入“cd”并按下空格键，再将“platfrom-tools”文件夹拖入窗口中

**Comment by liudongmiao** [comment]
@GongJianwei 他是 Mac，Windows 下的不有什么问题，请参考向导 - ADB。
