### ISSUE TITLE
更新后会不杀部分软件

### ISSUE THREAD

**Issue by Hidarihitomi** [liudongmiao/Brevent#347]
每次更新好像都会杀不了adm和酷安的进程，有划掉后台 root模式
顺带问一下…为什么要去掉开机自启了…很不理解呀，跟脚本冲突…手机执行的话有root的呀，为什么不用黑域本身功能了…

**Comment by liudongmiao** [comment]
带日志。没日志我什么也解决不了。

原因在那边说了。这里再贴一下。

1. 代价多。多一个权限，多一个广播，多一个服务。

2. 此模式与第三方脚本不兼容。开启以后，互相会掐架。

3. 本着对用户负责的态度，所有操作需要自己确认，所以，不提供自启。什么，再加一个可选项？参见第一条。以及第五条。

4. 为什么之前有现在没有？之前我错了。目前体验不好。也有捐赠用户说有的能启动，有的太慢。

5. 做好这个功能很难，比如最好启动时加状态栏，告知你正在启动；启动完成后告诉你已经成功。相比已有功能，去掉更好。
