### ISSUE TITLE
一些悬浮式软件被Kill

### ISSUE THREAD

**Issue by mr4side** [liudongmiao/Brevent#348]
如Perfmon、悬浮窗口式的计算器、翻译软件，还有薄暮微光等软件，必须取消这些软件的黑域才正常运行

**Comment by liudongmiao** [comment]
你开启允许同步吧，只要有通知，就可以运行。

因为这种需要允许出现在其他应用上，默认不需要你确认。另外一个，可能就是 freeform 型的。

**Comment by mr4side** [comment]
明白
