### ISSUE TITLE
开机重新启动卡界面

### ISSUE THREAD

**Issue by huahua2017** [liudongmiao/Brevent#349]
开发者你好，我现在用的你的0.9.4最新测试版本，已开启root启动。但是每次开机重启点击黑域的时候，第一屏出现点击root启动时，屏幕出现一个灰色方框然后就卡着不动了。用第一个测试版没出现这种情况。麻烦你有时间看一下，谢谢。

**Comment by liudongmiao** [comment]
看最新测试版  0.9.4+16

我估计你使用的第三方 su 程序。
