### ISSUE TITLE
无法通过adb和root模式启动黑域

### ISSUE THREAD

**Issue by daleysh** [liudongmiao/Brevent#350]
我的手机是oppo r7t 5.1，进入黑域两秒后，又会弹出窗口需要再次激活。root模式也是这种情况。

C:\Users\daley\Downloads\Compressed\platform-tools-latest-windows\platform-tools>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so
WARNING: linker: /data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so: unused DT entry: type 0x6ffffffe arg 0xa64
WARNING: linker: /data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so: unused DT entry: type 0x6fffffff arg 0x1
checking...brevent_server started, pid: 7151
checking for stable........quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-02 13:45:50.000' -d
E/AndroidRuntime( 7151): *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
E/AndroidRuntime( 7151): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/me.piebridge.brevent-1/lib/arm/libreader.so" is 32-bit instead of 64-bit
E/AndroidRuntime( 7151):        at java.lang.Runtime.loadLibrary(Runtime.java:372)
E/AndroidRuntime( 7151):        at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 7151):        at me.piebridge.LogReader.<clinit>(LogReader.java:10)
E/AndroidRuntime( 7151):        at me.piebridge.LogReader.readEvents(Native Method)
E/AndroidRuntime( 7151):        at me.piebridge.brevent.server.a.run(BreventEvent.java:47)
E/AndroidRuntime( 7151):        at java.lang.Thread.run(Thread.java:818)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-02 13:45:50.000' -d -s BreventLoader BreventServer
D/BreventLoader( 7133): loader path: /data/app/me.piebridge.brevent-1/base.apk
W/BreventServer( 7151): Can't find Settings.Secure.DIALER_DEFAULT_APPLICATION
W/BreventServer( 7151): Can't find Settings.Secure.ASSISTANT
W/BreventServer( 7151): Can't find ActivityManager.PROCESS_STATE_BOUND_FOREGROUND_SERVICE
W/BreventServer( 7151): Can't find ActivityManager.PROCESS_STATE_FOREGROUND_SERVICE
W/BreventServer( 7151): Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
W/BreventServer( 7151): Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
I/BreventServer( 7151): classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
I/BreventServer( 7151): Brevent Server 0.9.4 started
W/BreventServer( 7151): Can't find Settings.Secure.DIALER_DEFAULT_APPLICATION
W/BreventServer( 7151): Can't find Settings.Secure.ASSISTANT
W/BreventServer( 7151): Can't find ActivityManager.PROCESS_STATE_BOUND_FOREGROUND_SERVICE
W/BreventServer( 7151): Can't find ActivityManager.PROCESS_STATE_FOREGROUND_SERVICE
W/BreventServer( 7151): Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
W/BreventServer( 7151): Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
I/BreventServer( 7151): brevent user: 0, uid: 2000
I/BreventServer( 7151): brevent data directory: /data/data/com.android.shell
I/BreventServer( 7151): loading brevent list
I/BreventServer( 7151): loading brevent conf
D/BreventServer( 7151): check and brevent
W/BreventServer( 7151): Can't parse stack:   Stack #1(isFloating:false):
W/BreventServer( 7151): Can't parse stack:   Stack #0(isFloating:false):
D/BreventServer( 7151): check and brevent, took 173ms
W/BreventServer( 7151): Can't parse stack:   Stack #1(isFloating:false):
W/BreventServer( 7151): Can't parse stack:   Stack #0(isFloating:false):
D/BreventServer( 7151): sent first status
E/BreventLoader( 7133): worker 7151 exited on signal 9
D/BreventLoader( 7133): signal arrived, update: 0
D/BreventLoader( 7132): worker 7133 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by aviraxp** [comment]
这个问题让我想到了这个https://github.com/rovo89/XposedTools/issues/15，不知道有没有关系。

**Comment by daleysh** [comment]
我改成arm64试试

**Comment by liudongmiao** [comment]
你系统是一个 64 位的 app_process，然后系统只提取了 arm 的机器。

骂你的 ROM 厂商去吧。

**Comment by daleysh** [comment]
那我还是去用补丁版吧，不骂了，反正暑假就换机了，此生不在入大厂。

**Comment by GongJianwei** [comment]
把你的命令改成 ```adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so``` 尝试一下

**Comment by daleysh** [comment]
认命了，开发者说了是rom有问题。

**Comment by liudongmiao** [comment]
要么是你的 ROM 问题，要么是你装了 Xposed。

首先，要确认的是，你安装的真提原厂的版本，没有自己处理？

首先，我自己是直接调用 app_process，这个在 64 位机器上会链接到 app_process64，32 位机器上就是 app_process。

其次，你的报错信息："/data/app/me.piebridge.brevent-1/lib/arm/libreader.so" is 32-bit instead of 64-bit

而事实上，我有提供 64 位的版本，但是你的系统依然只解析出了 32 位的版本，那就是你的 ROM 问题了。

**Comment by daleysh** [comment]
是原厂的rom，没有装xposed,应该是大厂的rom有问题。

**Comment by liudongmiao** [comment]
你电脑上装下 teamviewer，然后把帐号密码发我邮箱，我登录上去看看。

**Comment by daleysh** [comment]
嗯

**Comment by daleysh** [comment]
柳大，你邮箱账号是？

**Comment by liudongmiao** [comment]
brevent @ piebridge.me

**Comment by daleysh** [comment]
发了

**Comment by daleysh** [comment]
谢谢了柳大，可以正常使用了，我去play支持一下。

**Comment by aviraxp** [comment]
其实我很好奇，怎么处理的？

**Comment by daleysh** [comment]
这个.......需要问柳大了。我看不懂。

**Comment by liudongmiao** [comment]
@aviraxp 你看看能看懂不，哈哈

**Comment by aviraxp** [comment]
懂了。。。。没有64的时候软连接可能的32位app_process然后暴露到PATH
