### ISSUE TITLE
一直显示正在获取进程状态，偶尔也会突然好一下，几个版本都试过了，依旧不行

### ISSUE THREAD

**Issue by zzlpp** [liudongmiao/Brevent#351]
C:\Windows\system32>adb -d logcat -d -b main -s BreventServer BreventLoader
04-02 19:11:24.288  5633  5633 D BreventServer: check and brevent
04-02 19:11:24.289  5633  5633 D BreventServer: before dump notifications, took 1ms
04-02 19:11:24.325  5633  5633 D BreventServer: after dump notifications, took 37ms
04-02 19:11:24.329  5633  5633 D BreventServer: after dump widgets, took 40ms
04-02 19:11:24.329  5633  5633 D BreventServer: before dumpActivities, took 41ms
04-02 19:11:24.331  5633  5633 D BreventServer: after dumpActivities, took 43ms
04-02 19:11:24.331  5633  5633 D BreventServer: before getRecentPackages, took 43ms
04-02 19:11:24.332  5633  5633 D BreventServer: after getRecentPackages, took 43ms
04-02 19:11:24.332  5633  5633 D BreventServer: widgets: {hanjie.app.pureweather, com.meizu.notes, com.xtuone.android.syllabus}
04-02 19:11:24.332  5633  5633 D BreventServer: running: {me.piebridge.brevent=3424, com.android.settings=3423}
04-02 19:11:24.332  5633  5633 D BreventServer: recent: {me.piebridge.brevent, com.yulong.android.launcher3, com.android.settings}
04-02 19:11:24.332  5633  5633 D BreventServer: before getRunningProcesses, took 44ms
04-02 19:11:24.348  5633  5633 D BreventServer: after getRunningProcesses, took 60ms
04-02 19:11:24.348  5633  5633 D BreventServer: before dumpProcesses, took 60ms
04-02 19:11:24.358  5633  5633 D BreventServer: after dumpProcesses, took 69ms
04-02 19:11:24.358  5633  5633 D BreventServer: com.android.webview depended by {com.yulong.android.launcher3}
04-02 19:11:24.358  5633  5633 D BreventServer: before isCharging, took 70ms
04-02 19:11:24.358  5633  5633 D BreventServer: after isCharging, took 70ms
04-02 19:11:24.359  5633  5633 D BreventServer: back: {}
04-02 19:11:24.359  5633  5633 D BreventServer: service: {}
04-02 19:11:24.359  5633  5633 D BreventServer: blocking: {}
04-02 19:11:24.359  5633  5633 D BreventServer: before getVpn, took 71ms
04-02 19:11:24.375  5633  5633 D BreventServer: after getVpn, took 87ms
04-02 19:11:24.375  5633  5633 D BreventServer: vpn: null
04-02 19:11:24.375  5633  5633 D BreventServer: top: {me.piebridge.brevent}
04-02 19:11:24.375  5633  5633 D BreventServer: home: {com.yulong.android.launcher3}
04-02 19:11:24.375  5633  5633 D BreventServer: current: me.piebridge.brevent
04-02 19:11:24.375  5633  5633 D BreventServer: unsafe: {}
04-02 19:11:24.375  5633  5633 D BreventServer: final blocking: {}
04-02 19:11:24.375  5633  5633 D BreventServer: notifications: {com.android.systemui={flags: 62, show: true, priority: false}}
04-02 19:11:24.375  5633  5633 D BreventServer: noRecent: {}
04-02 19:11:24.375  5633  5633 D BreventServer: foreground service: {}
04-02 19:11:24.375  5633  5633 D BreventServer: before blocking, took 87ms, size: 0
04-02 19:11:24.375  5633  5633 D BreventServer: after blocking, took 87ms
04-02 19:11:24.375  5633  5633 D BreventServer: check and brevent, took 87ms

**Comment by zzlpp** [comment]
附带崩溃日志，有点长，放在文件里了
[新建文本文档.txt](https://github.com/liudongmiao/Brevent/files/888324/default.txt)

**Comment by liudongmiao** [comment]
先关掉，有问题还重开。

你这个日志没有相应信息。
