### ISSUE TITLE
checking............cannot listen port

### ISSUE THREAD

**Issue by qiurigao** [liudongmiao/Brevent#352]
C:\adb>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-02 19:48:02.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-02 19:48:02.000' -d -s BreventLoader BreventServer
04-02 19:46:47.817 25056 25056 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
04-02 19:46:47.817 25056 25056 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
04-02 19:48:04.687 25303 25303 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-02 19:48:05.637 25367 25367 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
04-02 19:48:05.637 25367 25367 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
04-02 19:48:05.637 25367 25367 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
04-02 19:48:05.657 25367 25367 I BreventServer: Brevent Server 0.9.4 started
04-02 19:48:05.657 25367 25367 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
04-02 19:48:05.657 25367 25367 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
04-02 19:48:05.667 25367 25367 I BreventServer: brevent user: 0, uid: 2000
04-02 19:48:05.667 25367 25367 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-02 19:48:05.857 25367 25367 I BreventServer: loading brevent list
04-02 19:48:05.857 25367 25367 I BreventServer: loading brevent conf
04-02 19:48:05.897 25367 25367 D BreventServer: check and brevent
04-02 19:48:06.177 25303 25303 E BreventLoader: worker 25367 exited on signal 9
04-02 19:48:06.177 25303 25303 D BreventLoader: signal arrived, update: 0
04-02 19:48:06.177 25301 25301 D BreventLoader: worker 25303 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
由于你的系统没有 crash 日志，所以，你需要自己手动提取 crash 信息。

就是直接获取所有日志，然后从中找出黑域相关的。

你不要直接给我整个日志，我会疯掉的。
