### ISSUE TITLE
br-v0.9.4+22用adb或root都不能进入黑域

### ISSUE THREAD

**Issue by smdx** [liudongmiao/Brevent#354]
三星 6.0.1已root
使用root进入时一直反复的在获取程序列表以及使用root进入选项界面

下面是adb
================
F:\Phone\adb>adb -d shell
shell@zerofltechn:/ $ sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
checking...brevent_server started, pid: 16450
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-03 20:12:42.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-03 20:12:42.000' -d -s BreventLoader BreventServer
04-03 20:11:39.340 15803 15803 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-03 20:11:39.780 15816 15816 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-03 20:11:39.790 15816 15816 I BreventServer: Brevent Server 0.9.4-22-g42aad11 started
04-03 20:11:39.790 15816 15816 I BreventServer: brevent user: 0, uid: 0
04-03 20:11:39.790 15816 15816 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 20:11:39.890 15816 15816 I BreventServer: loading brevent list
04-03 20:11:39.890 15816 15816 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 64
04-03 20:11:39.890 15816 15816 I BreventServer: loading brevent conf
04-03 20:11:39.930 15816 15816 D BreventServer: check and brevent
04-03 20:11:39.940 15816 15825 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 177258748, 5966, com.teslacoilsw.notifier/.BlankActivity, NULL, NULL, NULL, 276824064, com.teslacoilsw.notifier, 0]
04-03 20:11:39.950 15803 15803 E BreventLoader: worker 15816 exited with status 1
04-03 20:11:39.950 15803 15803 D BreventLoader: signal arrived, update: 0
04-03 20:11:39.950 15802 15802 D BreventLoader: worker 15803 exited with status 0
04-03 20:11:47.290 15841 15841 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-03 20:11:47.880 15851 15851 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-03 20:11:47.890 15851 15851 I BreventServer: Brevent Server 0.9.4-22-g42aad11 started
04-03 20:11:47.900 15851 15851 I BreventServer: brevent user: 0, uid: 0
04-03 20:11:47.900 15851 15851 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 20:11:48.260 15851 15851 I BreventServer: loading brevent list
04-03 20:11:48.270 15851 15851 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 64
04-03 20:11:48.270 15851 15851 I BreventServer: loading brevent conf
04-03 20:11:48.340 15851 15851 D BreventServer: check and brevent
04-03 20:11:48.360 15851 15859 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 177258748, 5966, com.teslacoilsw.notifier/.BlankActivity, NULL, NULL, NULL, 276824064, com.teslacoilsw.notifier, 0]
04-03 20:11:48.370 15841 15841 E BreventLoader: worker 15851 exited with status 1
04-03 20:11:48.370 15841 15841 D BreventLoader: signal arrived, update: 0
04-03 20:11:48.370 15839 15839 D BreventLoader: worker 15841 exited with status 0
04-03 20:12:42.880 16440 16440 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-03 20:12:43.390 16450 16450 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-03 20:12:43.400 16450 16450 I BreventServer: Brevent Server 0.9.4-22-g42aad11 started
04-03 20:12:43.410 16450 16450 I BreventServer: brevent user: 0, uid: 2000
04-03 20:12:43.410 16450 16450 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 20:12:43.710 16450 16450 I BreventServer: loading brevent list
04-03 20:12:43.720 16450 16450 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 64
04-03 20:12:43.720 16450 16450 I BreventServer: loading brevent conf
04-03 20:12:43.770 16450 16450 D BreventServer: check and brevent
04-03 20:12:43.780 16450 16458 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 177258748, 5966, com.teslacoilsw.notifier/.BlankActivity, NULL, NULL, NULL, 276824064, com.teslacoilsw.notifier, 0]
04-03 20:12:43.790 16440 16440 E BreventLoader: worker 16450 exited with status 1
04-03 20:12:43.790 16440 16440 D BreventLoader: signal arrived, update: 0
04-03 20:12:43.790 16430 16430 D BreventLoader: worker 16440 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
1|shell@zerofltechn:/ $

**Comment by liudongmiao** [comment]
装个 teamviewer，然后邮件告诉我帐号与密码，我上去看看。

**Comment by liudongmiao** [comment]
电脑上装个 teamviewer，然后邮件告诉我帐号与密码，我上去看看。

**Comment by smdx** [comment]
稍等，刚刚在看电影。我下载了放邮件你

**Comment by smdx** [comment]
哎。。请问你邮箱地址是？

**Comment by smdx** [comment]
v0.9.4+23 用root开启可以进程序列表了。

**Comment by liudongmiao** [comment]
> 04-03 20:12:43.780 16450 16458 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 177258748, 5966, com.teslacoilsw.notifier/.BlankActivity, NULL, NULL, NULL, 276824064, com.teslacoilsw.notifier, 0]

看看最新的测试版。

#359 #360

**Comment by smdx** [comment]
root正常，然后取消允许root运行后重启手机测试adb。运行完brevent.sh脚本后黑域正常使用。

adb
F:\Phone\adb>adb -d shell
shell@zerofltechn:/ $ sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
checking....brevent_server started, pid: 13371
checking for stable...........ok

if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer
shell@zerofltechn:/ $ logcat -b crash -d
Unable to open log device 'crash'
1|shell@zerofltechn:/ $  logcat -b main -d -s BreventLoader BreventServer
04-04 08:24:02.781 13361 13361 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-04 08:24:03.291 13371 13371 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-04 08:24:03.291 13371 13371 I BreventServer: Brevent Server 0.9.5-1-g4f54550 started
04-04 08:24:03.301 13371 13371 I BreventServer: brevent user: 0, uid: 2000
04-04 08:24:03.301 13371 13371 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-04 08:24:03.451 13371 13371 I BreventServer: loading brevent list
04-04 08:24:03.461 13371 13371 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 64
04-04 08:24:03.461 13371 13371 I BreventServer: loading brevent conf
04-04 08:24:03.491 13371 13371 D BreventServer: check and brevent
04-04 08:24:03.631 13371 13371 D BreventServer: Force stop com.sds.android.ttpod(noRecent)
04-04 08:24:03.631 13371 13371 D BreventServer: check and brevent, took 141ms
04-04 08:24:03.631 13371 13371 D BreventServer: check and brevent
04-04 08:24:03.761 13371 13371 D BreventServer: check and brevent, took 110ms
04-04 08:24:03.791 13371 13371 D BreventServer: sent first status
04-04 08:24:06.801 13371 13371 D BreventServer: check and brevent
04-04 08:24:07.051 13371 13371 D BreventServer: Force stop com.icbc(service)
04-04 08:24:07.051 13371 13371 D BreventServer: check again in 3600s
04-04 08:24:07.051 13371 13371 D BreventServer: check and brevent, took 249ms
04-04 08:24:36.621 13371 13371 D BreventServer: check and brevent
04-04 08:24:36.841 13371 13371 D BreventServer: check again in 3600s
04-04 08:24:36.841 13371 13371 D BreventServer: check and brevent, took 221ms
shell@zerofltechn:/ $
