### ISSUE TITLE
0.9.5 root模式不能用

### ISSUE THREAD

**Issue by david082321** [liudongmiao/Brevent#355]
三星，6.0.1，有捐赠了
# 附SuperSu日志

INTERACTIVE
/data/app/me.piebridge.brevent-2/lib/arm64/libbrevent.so
exit
checking....brevent_server started, pid: 5905
checking for stable...quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>>logcat -b crash -t '04-03 22:34:45.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-03 22:34:45.000' -d -s BreventLoader BreventServer
04-03 22:34:49.281 5905 5905 I BreventServer: loading brevent list
04-03 22:34:49.281 5905 5905 I BreventServer: loading brevent conf
04-03 22:34:49.341 5905 5905 D BreventServer: check and brevent
04-03 22:34:49.361 5905 5954 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 150743637, 34, com.android.systemui/.recents.SeparatedRecentsActivity, NULL, NULL, NULL, 281018368, com.android.systemui, 0]
04-03 22:34:49.391 5852 5852 E BreventLoader: worker 5905 exited with status 1
04-03 22:34:49.391 5852 5852 D BreventLoader: signal arrived, update: 0
04-03 22:34:49.391 5851 5851 D BreventLoader: worker 5852 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by david082321** [comment]
还需要我提供什么样的信息吗？

**Comment by david082321** [comment]
装回历史版本0.9.4又能使用root模式了

**Comment by david082321** [comment]
以下截图，就是一直循环这两张
[https://www.dropbox.com/s/j253xqpoeot3n30/Screenshot_20170403-230815.png?dl=0](url)
[https://www.dropbox.com/s/7wrfr57cgy8amls/Screenshot_20170403-230751.png?dl=0](url)

**Comment by iVeego** [comment]
我也有同样的问题。0.94是OK的，0.95失效。log如下。操作顺序是：开机，手动点击黑域，使用Root开启。

C:\Android>adb logcat -s BreventUI
- waiting for device -
--------- beginning of system
--------- beginning of main
04-03 23:44:54.738  7247  7263 D BreventUI: request status
04-03 23:44:54.740  7247  7263 E BreventUI: cannot connect to ip6-localhost/::1:59526
04-03 23:44:57.743  7247  7263 D BreventUI: retry request status
04-03 23:44:57.744  7247  7263 E BreventUI: cannot connect to ip6-localhost/::1:59526
04-03 23:45:00.748  7247  7263 D BreventUI: retry request status
04-03 23:45:00.749  7247  7263 E BreventUI: cannot connect to ip6-localhost/::1:59526
04-03 23:45:00.850  7247  7275 D BreventUI: startBrevent: /data/app/me.piebridge.brevent-2/lib/arm64/libbrevent.so
04-03 23:45:02.671  7247  7263 D BreventUI: received response
04-03 23:45:12.189  7247  7275 D BreventUI: checking...brevent_server started, pid: 7297
04-03 23:45:12.189  7247  7275 D BreventUI: checking for stable...........ok
04-03 23:45:12.189  7247  7275 D BreventUI:
04-03 23:45:12.189  7247  7275 D BreventUI: if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
04-03 23:45:12.189  7247  7275 D BreventUI: for crash log: logcat -b crash -d
04-03 23:45:12.189  7247  7275 D BreventUI: for brevent log: logcat -b main -d -s BreventLoader BreventServer

**Comment by liudongmiao** [comment]
看下这个测试版吧：https://piebridge.me/br/next/

> 04-03 22:34:49.361 5905 5954 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 150743637, 34, com.android.systemui/.recents.SeparatedRecentsActivity, NULL, NULL, NULL, 281018368, com.android.systemui, 0]

三星的某个事件，在字段中声明只有 9 个，返回了 10 个。
当然实际上正常的里面比这个都少。

主要是在支持非正常“返回”时引入。测试版忽略这种异常。

**Comment by liudongmiao** [comment]
#359 #360 #354

**Comment by liudongmiao** [comment]
#354, #355, #356, #359, #360
