### ISSUE TITLE
0.9.5 log 反馈

### ISSUE THREAD

**Issue by czb1994** [liudongmiao/Brevent#356]
我都数据线都是只能充电的，说多了都是泪，网络adb结果

checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-03 23:29:06.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-03 23:29:06.000' -d -s BreventLoader BreventServer
04-03 23:19:05.091  3947  3947 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-03 23:19:06.151  3973  3973 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
04-03 23:19:06.171  3973  3973 I BreventServer: Brevent Server 0.9.5 started
04-03 23:19:06.181  3973  3973 I BreventServer: brevent user: 0, uid: 2000
04-03 23:19:06.181  3973  3973 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 23:19:06.551  3973  3973 I BreventServer: loading brevent list
04-03 23:19:06.551  3973  3973 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 6
04-03 23:19:06.551  3973  3973 I BreventServer: loading brevent conf
04-03 23:19:06.591  3973  3973 D BreventServer: check and brevent
04-03 23:19:06.601  3973  4044 E BreventServer: names: [user, pid, uid, processName, type, component], events: [0, 1253, 218192027, 5010, com.samsung.android.intelligenceservice2, content provider, com.samsung.android.intelligenceservice2/com.samsung.android.intelligenceservice.useranalysis.PlaceProvider]
04-03 23:19:06.621  3947  3947 E BreventLoader: worker 3973 exited with status 1
04-03 23:19:06.621  3947  3947 D BreventLoader: signal arrived, update: 0
04-03 23:19:06.621  3912  3912 D BreventLoader: worker 3947 exited with status 0
04-03 23:19:14.891  4294  4294 D BreventLoader: loader path: 10383
04-03 23:19:14.891  4294  4294 E BreventLoader: can't find loader: 10383
04-03 23:19:14.901  4292  4292 E BreventLoader: worker 4294 exited with status 255
04-03 23:19:27.521  4626  4626 D BreventLoader: loader path: 10383
04-03 23:19:27.521  4626  4626 E BreventLoader: can't find loader: 10383
04-03 23:19:27.521  4624  4624 E BreventLoader: worker 4626 exited with status 255
04-03 23:21:37.501  7020  7020 D BreventLoader: loader path: 10383
04-03 23:21:37.501  7020  7020 E BreventLoader: can't find loader: 10383
04-03 23:21:37.501  7019  7019 E BreventLoader: worker 7020 exited with status 255
04-03 23:22:28.711  8168  8168 D BreventLoader: loader path: 10383
04-03 23:22:28.711  8168  8168 E BreventLoader: can't find loader: 10383
04-03 23:22:28.721  8167  8167 E BreventLoader: worker 8168 exited with status 255
04-03 23:22:40.141  8479  8479 D BreventLoader: loader path: 10383
04-03 23:22:40.141  8479  8479 E BreventLoader: can't find loader: 10383
04-03 23:22:40.141  8473  8473 E BreventLoader: worker 8479 exited with status 255
04-03 23:22:58.511  8908  8908 D BreventLoader: loader path: 10383
04-03 23:22:58.511  8908  8908 E BreventLoader: can't find loader: 10383
04-03 23:22:58.521  8907  8907 E BreventLoader: worker 8908 exited with status 255
04-03 23:26:33.455 13846 13846 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-03 23:26:34.525 13889 13889 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
04-03 23:26:34.535 13889 13889 I BreventServer: Brevent Server 0.9.5 started
04-03 23:26:34.545 13889 13889 I BreventServer: brevent user: 0, uid: 2000
04-03 23:26:34.545 13889 13889 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 23:26:34.845 13889 13889 I BreventServer: loading brevent list
04-03 23:26:34.845 13889 13889 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 6
04-03 23:26:34.845 13889 13889 I BreventServer: loading brevent conf
04-03 23:26:34.885 13889 13889 D BreventServer: check and brevent
04-03 23:26:34.885 13889 13918 E BreventServer: names: [user, pid, uid, processName, type, component], events: [0, 17234, 91221676, 1000, com.trustonic.tuiservice, service, com.trustonic.tuiservice/.TuiService]
04-03 23:26:34.905 13846 13846 E BreventLoader: worker 13889 exited with status 1
04-03 23:26:34.905 13846 13846 D BreventLoader: signal arrived, update: 0
04-03 23:26:34.905 13821 13821 D BreventLoader: worker 13846 exited with status 0
04-03 23:26:48.155 14178 14178 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-03 23:26:49.225 14207 14207 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
04-03 23:26:49.235 14207 14207 I BreventServer: Brevent Server 0.9.5 started
04-03 23:26:49.245 14207 14207 I BreventServer: brevent user: 0, uid: 2000
04-03 23:26:49.245 14207 14207 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 23:26:49.585 14207 14207 I BreventServer: loading brevent list
04-03 23:26:49.585 14207 14207 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 6
04-03 23:26:49.585 14207 14207 I BreventServer: loading brevent conf
04-03 23:26:49.625 14207 14207 D BreventServer: check and brevent
04-03 23:26:49.635 14207 14276 E BreventServer: names: [user, pid, uid, processName, type, component], events: [0, 17702, 32429888, 1000, com.trustonic.tuiservice, service, com.trustonic.tuiservice/.TuiService]
04-03 23:26:49.655 14178 14178 E BreventLoader: worker 14207 exited with status 1
04-03 23:26:49.655 14178 14178 D BreventLoader: signal arrived, update: 0
04-03 23:26:49.655 14155 14155 D BreventLoader: worker 14178 exited with status 0
04-03 23:26:59.905 14510 14510 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-03 23:27:00.945 14531 14531 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
04-03 23:27:00.955 14531 14531 I BreventServer: Brevent Server 0.9.5 started
04-03 23:27:00.965 14531 14531 I BreventServer: brevent user: 0, uid: 2000
04-03 23:27:00.965 14531 14531 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 23:27:01.285 14531 14531 I BreventServer: loading brevent list
04-03 23:27:01.285 14531 14531 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 6
04-03 23:27:01.285 14531 14531 I BreventServer: loading brevent conf
04-03 23:27:01.325 14531 14531 D BreventServer: check and brevent
04-03 23:27:01.325 14531 14583 E BreventServer: names: [user, pid, uid, processName, type, component], events: [0, 18051, 177514998, 1000, com.trustonic.tuiservice, service, com.trustonic.tuiservice/.TuiService]
04-03 23:27:01.345 14510 14510 E BreventLoader: worker 14531 exited with status 1
04-03 23:27:01.345 14510 14510 D BreventLoader: signal arrived, update: 0
04-03 23:27:01.345 14471 14471 D BreventLoader: worker 14510 exited with status 0
04-03 23:27:27.625 15028 15028 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-03 23:27:28.685 15040 15040 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
04-03 23:27:28.705 15040 15040 I BreventServer: Brevent Server 0.9.5 started
04-03 23:27:28.715 15040 15040 I BreventServer: brevent user: 0, uid: 2000
04-03 23:27:28.715 15040 15040 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 23:27:28.985 15040 15040 I BreventServer: loading brevent list
04-03 23:27:28.985 15040 15040 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 6
04-03 23:27:28.985 15040 15040 I BreventServer: loading brevent conf
04-03 23:27:29.035 15040 15040 D BreventServer: check and brevent
04-03 23:27:29.045 15040 15060 E BreventServer: names: [user, pid, uid, processName, type, component], events: [0, 18738, 171758910, 1000, com.trustonic.tuiservice, service, com.trustonic.tuiservice/.TuiService]
04-03 23:27:29.065 15028 15028 E BreventLoader: worker 15040 exited with status 1
04-03 23:27:29.065 15028 15028 D BreventLoader: signal arrived, update: 0
04-03 23:27:29.065 15011 15011 D BreventLoader: worker 15028 exited with status 0
04-03 23:27:56.055 15575 15575 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-03 23:27:57.095 15620 15620 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
04-03 23:27:57.105 15620 15620 I BreventServer: Brevent Server 0.9.5 started
04-03 23:27:57.115 15620 15620 I BreventServer: brevent user: 0, uid: 2000
04-03 23:27:57.115 15620 15620 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 23:27:57.445 15620 15620 I BreventServer: loading brevent list
04-03 23:27:57.445 15620 15620 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 6
04-03 23:27:57.445 15620 15620 I BreventServer: loading brevent conf
04-03 23:27:57.485 15620 15620 D BreventServer: check and brevent
04-03 23:27:57.495 15620 15659 E BreventServer: names: [user, pid, uid, processName, type, component], events: [0, 19336, 242811094, 1000, com.trustonic.tuiservice, service, com.trustonic.tuiservice/.TuiService]
04-03 23:27:57.515 15575 15575 E BreventLoader: worker 15620 exited with status 1
04-03 23:27:57.515 15575 15575 D BreventLoader: signal arrived, update: 0
04-03 23:27:57.515 15557 15557 D BreventLoader: worker 15575 exited with status 0
04-03 23:28:26.085 16110 16110 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-03 23:28:27.135 16124 16124 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
04-03 23:28:27.155 16124 16124 I BreventServer: Brevent Server 0.9.5 started
04-03 23:28:27.165 16124 16124 I BreventServer: brevent user: 0, uid: 2000
04-03 23:28:27.165 16124 16124 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 23:28:27.535 16124 16124 I BreventServer: loading brevent list
04-03 23:28:27.535 16124 16124 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 6
04-03 23:28:27.535 16124 16124 I BreventServer: loading brevent conf
04-03 23:28:27.595 16124 16124 D BreventServer: check and brevent
04-03 23:28:27.615 16124 16140 E BreventServer: names: [user, pid, uid, processName, type, component], events: [0, 20054, 193505440, 1000, com.trustonic.tuiservice, service, com.trustonic.tuiservice/.TuiService]
04-03 23:28:27.635 16110 16110 E BreventLoader: worker 16124 exited with status 1
04-03 23:28:27.635 16110 16110 D BreventLoader: signal arrived, update: 0
04-03 23:28:27.635 16075 16075 D BreventLoader: worker 16110 exited with status 0
04-03 23:29:07.255 16822 16822 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-03 23:29:08.415 16852 16852 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
04-03 23:29:08.435 16852 16852 I BreventServer: Brevent Server 0.9.5 started
04-03 23:29:08.445 16852 16852 I BreventServer: brevent user: 0, uid: 2000
04-03 23:29:08.445 16852 16852 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 23:29:08.785 16852 16852 I BreventServer: loading brevent list
04-03 23:29:08.785 16852 16852 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 6
04-03 23:29:08.785 16852 16852 I BreventServer: loading brevent conf
04-03 23:29:08.825 16852 16852 D BreventServer: check and brevent
04-03 23:29:08.835 16852 16904 E BreventServer: names: [user, pid, uid, processName, type, component], events: [0, 21433, 70315071, 1000, com.trustonic.tuiservice, service, com.trustonic.tuiservice/.TuiService]
04-03 23:29:08.855 16822 16822 E BreventLoader: worker 16852 exited with status 1
04-03 23:29:08.855 16822 16822 D BreventLoader: signal arrived, update: 0
04-03 23:29:08.855 16806 16806 D BreventLoader: worker 16822 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> 04-03 23:29:08.835 16852 16904 E BreventServer: names: [user, pid, uid, processName, type, component], events: [0, 21433, 70315071, 1000, com.trustonic.tuiservice, service, com.trustonic.tuiservice/.TuiService]

#354 #355  #356 #359 #360

**Comment by liudongmiao** [comment]
请使用最新测试版，然后看看能否正常使用。

**Comment by liudongmiao** [comment]
#354, #355, #356, #359, #360
