### ISSUE TITLE
在执行最后一步出现错误 0.9.5(1)版，三星s6 台版

### ISSUE THREAD

**Issue by soswxl** [liudongmiao/Brevent#359]
E:\手机\platform-tools>adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
checking...brevent_server started, pid: 25036
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-04 00:12:36.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-04 00:12:36.000' -d -s BreventLoader BreventServer
04-03 23:58:05.571 19350 19350 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-03 23:58:06.201 19365 19365 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-03 23:58:06.211 19365 19365 I BreventServer: Brevent Server 0.9.5 started
04-03 23:58:06.221 19365 19365 I BreventServer: brevent user: 0, uid: 2000
04-03 23:58:06.221 19365 19365 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 23:58:06.551 19365 19365 I BreventServer: loading brevent list
04-03 23:58:06.551 19365 19365 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 71
04-03 23:58:06.551 19365 19365 I BreventServer: loading brevent conf
04-03 23:58:06.581 19365 19365 D BreventServer: check and brevent
04-03 23:58:06.591 19365 19394 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 225637440, 1, com.sec.android.app.launcher/.activities.LauncherActivity, android.intent.action.MAIN, NULL, NULL, 283115520, com.android.systemui, 0]
04-03 23:58:06.601 19350 19350 E BreventLoader: worker 19365 exited with status 1
04-03 23:58:06.601 19350 19350 D BreventLoader: signal arrived, update: 0
04-03 23:58:06.601 19338 19338 D BreventLoader: worker 19350 exited with status 0
04-03 23:59:33.151 20351 20351 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-03 23:59:33.691 20362 20362 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-03 23:59:33.691 20362 20362 I BreventServer: Brevent Server 0.9.5 started
04-03 23:59:33.701 20362 20362 I BreventServer: brevent user: 0, uid: 2000
04-03 23:59:33.701 20362 20362 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-03 23:59:33.851 20362 20362 I BreventServer: loading brevent list
04-03 23:59:33.851 20362 20362 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 71
04-03 23:59:33.851 20362 20362 I BreventServer: loading brevent conf
04-03 23:59:33.891 20362 20362 D BreventServer: check and brevent
04-03 23:59:33.891 20362 20375 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 16174627, 3, com.android.systemui/.recents.SeparatedRecentsActivity, NULL, NULL, NULL, 281018368, com.android.systemui, 0]
04-03 23:59:33.901 20351 20351 E BreventLoader: worker 20362 exited with status 1
04-03 23:59:33.901 20351 20351 D BreventLoader: signal arrived, update: 0
04-03 23:59:33.901 20337 20337 D BreventLoader: worker 20351 exited with status 0
04-04 00:00:18.031 21018 21018 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-04 00:00:18.551 21038 21038 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-04 00:00:18.561 21038 21038 I BreventServer: Brevent Server 0.9.5 started
04-04 00:00:18.571 21038 21038 I BreventServer: brevent user: 0, uid: 2000
04-04 00:00:18.571 21038 21038 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-04 00:00:18.691 21038 21038 I BreventServer: loading brevent list
04-04 00:00:18.701 21038 21038 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 71
04-04 00:00:18.701 21038 21038 I BreventServer: loading brevent conf
04-04 00:00:18.731 21038 21038 D BreventServer: check and brevent
04-04 00:00:18.731 21038 21064 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 150640623, 3, com.android.systemui/.recents.SeparatedRecentsActivity, NULL, NULL, NULL, 281018368, com.android.systemui, 0]
04-04 00:00:18.741 21018 21018 E BreventLoader: worker 21038 exited with status 1
04-04 00:00:18.741 21018 21018 D BreventLoader: signal arrived, update: 0
04-04 00:00:18.751 21003 21003 D BreventLoader: worker 21018 exited with status 0
04-04 00:12:11.111 24535 24535 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-04 00:12:11.671 24567 24567 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-04 00:12:11.681 24567 24567 I BreventServer: Brevent Server 0.9.5 started
04-04 00:12:11.691 24567 24567 I BreventServer: brevent user: 0, uid: 2000
04-04 00:12:11.691 24567 24567 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-04 00:12:11.881 24567 24567 I BreventServer: loading brevent list
04-04 00:12:11.891 24567 24567 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 71
04-04 00:12:11.891 24567 24567 I BreventServer: loading brevent conf
04-04 00:12:11.911 24567 24567 D BreventServer: check and brevent
04-04 00:12:11.911 24567 24594 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 195359132, 3, com.android.systemui/.recents.SeparatedRecentsActivity, NULL, NULL, NULL, 281018368, com.android.systemui, 0]
04-04 00:12:11.931 24535 24535 E BreventLoader: worker 24567 exited with status 1
04-04 00:12:11.931 24535 24535 D BreventLoader: signal arrived, update: 0
04-04 00:12:11.931 24519 24519 D BreventLoader: worker 24535 exited with status 0
04-04 00:12:29.681 24909 24909 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-04 00:12:30.181 24921 24921 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-04 00:12:30.181 24921 24921 I BreventServer: Brevent Server 0.9.5 started
04-04 00:12:30.191 24921 24921 I BreventServer: brevent user: 0, uid: 2000
04-04 00:12:30.191 24921 24921 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-04 00:12:30.501 24921 24921 I BreventServer: loading brevent list
04-04 00:12:30.511 24921 24921 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 71
04-04 00:12:30.511 24921 24921 I BreventServer: loading brevent conf
04-04 00:12:30.551 24921 24921 D BreventServer: check and brevent
04-04 00:12:30.561 24921 24933 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 195359132, 3, com.android.systemui/.recents.SeparatedRecentsActivity, NULL, NULL, NULL, 281018368, com.android.systemui, 0]
04-04 00:12:30.581 24909 24909 E BreventLoader: worker 24921 exited with status 1
04-04 00:12:30.581 24909 24909 D BreventLoader: signal arrived, update: 0
04-04 00:12:30.581 24898 24898 D BreventLoader: worker 24909 exited with status 0
04-04 00:12:36.511 25026 25026 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-04 00:12:37.001 25036 25036 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-04 00:12:37.011 25036 25036 I BreventServer: Brevent Server 0.9.5 started
04-04 00:12:37.021 25036 25036 I BreventServer: brevent user: 0, uid: 2000
04-04 00:12:37.021 25036 25036 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-04 00:12:37.181 25036 25036 I BreventServer: loading brevent list
04-04 00:12:37.181 25036 25036 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 71
04-04 00:12:37.181 25036 25036 I BreventServer: loading brevent conf
04-04 00:12:37.211 25036 25036 D BreventServer: check and brevent
04-04 00:12:37.211 25036 25046 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 195359132, 3, com.android.systemui/.recents.SeparatedRecentsActivity, NULL, NULL, NULL, 281018368, com.android.systemui, 0]
04-04 00:12:37.231 25026 25026 E BreventLoader: worker 25036 exited with status 1
04-04 00:12:37.231 25026 25026 D BreventLoader: signal arrived, update: 0
04-04 00:12:37.231 25015 25015 D BreventLoader: worker 25026 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> 04-04 00:12:30.561 24921 24933 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 195359132, 3, com.android.systemui/.recents.SeparatedRecentsActivity, NULL, NULL, NULL, 281018368, com.android.systemui, 0]

已经修了，请使用最新测试版，然后看看有没有问题。

https://piebridge.me/br/next/

**Comment by liudongmiao** [comment]
#354, #355, #356, #359, #360
