### ISSUE TITLE
[0.9.5]从最近列表将黑域划掉后需要重新ADB开启

### ISSUE THREAD

**Issue by Pason2C** [liudongmiao/Brevent#360]
手机型号：Samsung S7 Edge ( Android 7.0 )
0.9.5之前的版本，将黑域从最近列表划掉后不需要重新开启。
已经清除数据、卸载、重启、重装后尝试，一样的结果。附上服务日志。

服务日志

    04-04 02:19:05.189 10554 10554 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
    04-04 02:19:06.050 10565 10565 W BreventServer: Can't find Settings.Secure.QS_TILES
    04-04 02:19:06.057 10565 10565 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]]
    04-04 02:19:06.058 10565 10565 I BreventServer: Brevent Server 0.9.5 started
    04-04 02:19:06.065 10565 10565 W BreventServer: Can't find Settings.Secure.QS_TILES
    04-04 02:19:06.080 10565 10565 I BreventServer: brevent user: 0, uid: 2000
    04-04 02:19:06.083 10565 10565 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
    04-04 02:19:06.953 10565 10565 I BreventServer: loading brevent list
    04-04 02:19:06.958 10565 10565 I BreventServer: loading brevent conf
    04-04 02:19:07.073 10565 10565 D BreventServer: check and brevent
    04-04 02:19:07.771 10565 10565 D BreventServer: check and brevent, took 696ms
    04-04 02:19:08.037 10565 10565 D BreventServer: sent first status
    04-04 02:19:08.065 10287 10515 W BreventServer: Can't find Settings.Secure.QS_TILES
    04-04 02:19:16.125 10565 10574 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags], events: [0, 246189530, 2447, com.sec.android.app.launcher/.activities.LauncherActivity, android.intent.action.MAIN, NULL, NULL, 283115520, com.android.systemui]
    04-04 02:19:16.172 10554 10554 E BreventLoader: worker 10565 exited with status 1
    04-04 02:19:16.172 10554 10554 D BreventLoader: signal arrived, update: 0
    04-04 02:19:16.175 10546 10546 D BreventLoader: worker 10554 exited with status 0

调试服务日志

	04-04 02:21:31.655 11277 11277 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
	04-04 02:21:32.389 11291 11291 W BreventServer: Can't find Settings.Secure.QS_TILES
	04-04 02:21:32.395 11291 11291 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]]
	04-04 02:21:32.396 11291 11291 I BreventServer: Brevent Server 0.9.5 started
	04-04 02:21:32.403 11291 11291 W BreventServer: Can't find Settings.Secure.QS_TILES
	04-04 02:21:32.407 11291 11291 I BreventServer: brevent user: 0, uid: 2000
	04-04 02:21:32.408 11291 11291 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
	04-04 02:21:34.553 11291 11291 I BreventServer: loading brevent list
	04-04 02:21:34.554 11291 11291 I BreventServer: loading brevent conf
	04-04 02:21:34.641 11291 11291 D BreventServer: notification_cancel_all, tag: 2752, event: 4
	04-04 02:21:34.646 11291 11291 D BreventServer: notification_panel_revealed, tag: 27500, event: 6
	04-04 02:21:34.648 11291 11291 D BreventServer: notification_panel_hidden, tag: 27501, event: 7
	04-04 02:21:34.650 11291 11291 D BreventServer: am_new_intent, tag: 30003, event: 8
	04-04 02:21:34.651 11291 11291 D BreventServer: am_resume_activity, tag: 30007, event: 2
	04-04 02:21:34.652 11291 11291 D BreventServer: am_pause_activity, tag: 30013, event: 9
	04-04 02:21:34.652 11291 11291 D BreventServer: am_proc_start, tag: 30014, event: 1
	04-04 02:21:34.654 11291 11291 D BreventServer: am_switch_user, tag: 30041, event: 3
	04-04 02:21:34.661 11291 11291 D BreventServer: screen_toggled, tag: 70000, event: 5
	04-04 02:21:34.681 11291 11291 D BreventServer: check and brevent
	04-04 02:21:34.836 11291 11291 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, com.sec.android.daemonapp, com.samsung.android.app.memo}
	04-04 02:21:34.836 11291 11291 D BreventServer: running: {com.android.vending=134, me.piebridge.brevent=282}
	04-04 02:21:34.836 11291 11291 D BreventServer: recent: {com.github.shadowsocks=3379, com.android.vending=3437, com.tencent.mm=562, me.piebridge.brevent=3585, com.android.settings=3281}
	04-04 02:21:35.090 11291 11291 D BreventServer: com.google.android.gms depended by {com.github.shadowsocks, com.android.vending}
	04-04 02:21:35.090 11291 11291 D BreventServer: service: {}
	04-04 02:21:35.090 11291 11291 D BreventServer: back(no action): {}
	04-04 02:21:35.090 11291 11291 D BreventServer: blocking: {}
	04-04 02:21:35.090 11291 11291 D BreventServer: top: {me.piebridge.brevent}
	04-04 02:21:35.090 11291 11291 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
	04-04 02:21:35.090 11291 11291 D BreventServer: current: null
	04-04 02:21:35.090 11291 11291 D BreventServer: unsafe: {}
	04-04 02:21:35.090 11291 11291 D BreventServer: final blocking: {}
	04-04 02:21:35.090 11291 11291 D BreventServer: notifications: {com.github.shadowsocks=[98], android=[98]}
	04-04 02:21:35.090 11291 11291 D BreventServer: noRecent: {}
	04-04 02:21:35.091 11291 11291 D BreventServer: foreground service: {}
	04-04 02:21:35.091 11291 11291 D BreventServer: sticky notification: {}
	04-04 02:21:35.091 11291 11291 D BreventServer: check and brevent, took 407ms
	04-04 02:21:35.273 11291 11291 D BreventServer: sent first status
	04-04 02:21:35.305 10743 10758 W BreventServer: Can't find Settings.Secure.QS_TILES
	04-04 02:22:15.491 11291 11291 D BreventServer: pause activity, tid: 3031, packageName: me.piebridge.brevent
	04-04 02:22:15.545 11291 11291 D BreventServer: resume activity, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher, paused: me.piebridge.brevent, pressed home: false
	04-04 02:22:16.814 11291 11291 D BreventServer: pause activity, tid: 6984, packageName: com.sec.android.app.launcher
	04-04 02:22:17.074 11291 11291 D BreventServer: checking feelgood
	04-04 02:22:17.077 11291 11301 D BreventServer: received feelgood
	04-04 02:22:18.547 11291 11291 D BreventServer: check and brevent
	04-04 02:22:18.738 11291 11291 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, com.sec.android.daemonapp, com.samsung.android.app.memo}
	04-04 02:22:18.738 11291 11291 D BreventServer: running: {com.android.vending=134, me.piebridge.brevent=340}
	04-04 02:22:18.738 11291 11291 D BreventServer: recent: {com.github.shadowsocks=3335, com.android.vending=3393, com.tencent.mm=518, me.piebridge.brevent=3598, com.android.settings=3237}
	04-04 02:22:18.932 11291 11291 D BreventServer: com.google.android.gms depended by {com.github.shadowsocks, com.android.vending}
	04-04 02:22:18.932 11291 11291 D BreventServer: service: {}
	04-04 02:22:18.932 11291 11291 D BreventServer: back(no action): {}
	04-04 02:22:18.932 11291 11291 D BreventServer: blocking: {}
	04-04 02:22:18.932 11291 11291 D BreventServer: top: {me.piebridge.brevent}
	04-04 02:22:18.933 11291 11291 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
	04-04 02:22:18.933 11291 11291 D BreventServer: current: com.sec.android.app.launcher
	04-04 02:22:18.933 11291 11291 D BreventServer: unsafe: {}
	04-04 02:22:18.933 11291 11291 D BreventServer: final blocking: {}
	04-04 02:22:18.933 11291 11291 D BreventServer: notifications: {com.github.shadowsocks=[98], android=[98]}
	04-04 02:22:18.933 11291 11291 D BreventServer: noRecent: {}
	04-04 02:22:18.933 11291 11291 D BreventServer: foreground service: {}
	04-04 02:22:18.933 11291 11291 D BreventServer: sticky notification: {}
	04-04 02:22:18.933 11291 11291 D BreventServer: check and brevent, took 380ms
	04-04 02:23:19.064 11291 11291 D BreventServer: pause activity, tid: 1838, packageName: me.piebridge.brevent
	04-04 02:23:21.392 11291 11291 D BreventServer: check and brevent
	04-04 02:23:21.603 11291 11291 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, com.sec.android.daemonapp, com.samsung.android.app.memo}
	04-04 02:23:21.604 11291 11291 D BreventServer: running: {com.android.vending=135, me.piebridge.brevent=402}
	04-04 02:23:21.604 11291 11291 D BreventServer: recent: {com.github.shadowsocks=3272, com.android.vending=3330, com.tencent.mm=455, me.piebridge.brevent=3598, com.android.settings=3174}
	04-04 02:23:21.928 11291 11291 D BreventServer: com.google.android.gms depended by {com.github.shadowsocks, com.android.vending}
	04-04 02:23:21.928 11291 11291 D BreventServer: service: {}
	04-04 02:23:21.928 11291 11291 D BreventServer: back(no action): {}
	04-04 02:23:21.928 11291 11291 D BreventServer: blocking: {}
	04-04 02:23:21.929 11291 11291 D BreventServer: top: {me.piebridge.brevent}
	04-04 02:23:21.929 11291 11291 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
	04-04 02:23:21.929 11291 11291 D BreventServer: current: com.sec.android.app.launcher
	04-04 02:23:21.929 11291 11291 D BreventServer: unsafe: {}
	04-04 02:23:21.929 11291 11291 D BreventServer: final blocking: {}
	04-04 02:23:21.929 11291 11291 D BreventServer: notifications: {com.github.shadowsocks=[98], android=[98]}
	04-04 02:23:21.929 11291 11291 D BreventServer: noRecent: {}
	04-04 02:23:21.929 11291 11291 D BreventServer: foreground service: {}
	04-04 02:23:21.929 11291 11291 D BreventServer: sticky notification: {}
	04-04 02:23:21.929 11291 11291 D BreventServer: check again in 3600s
	04-04 02:23:21.930 11291 11291 D BreventServer: check and brevent, took 532ms
	04-04 02:23:26.296 11291 11291 D BreventServer: checking feelgood
	04-04 02:23:26.298 11291 11291 D BreventServer: resume activity, packageName: me.piebridge.brevent, launcher: com.sec.android.app.launcher, paused: me.piebridge.brevent, pressed home: false
	04-04 02:23:26.307 11291 11301 D BreventServer: received feelgood
	04-04 02:23:27.218 11291 11291 D BreventServer: pause activity, tid: 4722, packageName: me.piebridge.brevent
	04-04 02:23:27.285 11291 11291 D BreventServer: resume activity, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher, paused: me.piebridge.brevent, pressed home: false
	04-04 02:23:28.421 11291 11291 D BreventServer: pause activity, tid: 4707, packageName: com.sec.android.app.launcher
	04-04 02:23:28.623 11291 11291 D BreventServer: checking feelgood
	04-04 02:23:28.624 11291 11301 D BreventServer: received feelgood
	04-04 02:23:29.745 11291 11291 D BreventServer: pause activity, tid: 4760, packageName: me.piebridge.brevent
	04-04 02:23:29.780 11291 11291 D BreventServer: resume activity, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher, paused: me.piebridge.brevent, pressed home: false
	04-04 02:23:30.177 11291 11301 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags], events: [0, 248026687, 2451, com.android.systemui/.recents.RecentsActivity, NULL, NULL, NULL, 281034752, com.android.systemui]
	04-04 02:23:30.244 11277 11277 E BreventLoader: worker 11291 exited with status 1
	04-04 02:23:30.245 11277 11277 D BreventLoader: signal arrived, update: 0

**Comment by liudongmiao** [comment]
三星的机器？试试最新的测试版吧。

**Comment by liudongmiao** [comment]
#359

**Comment by liudongmiao** [comment]
#354, #355, #356, #359, #360

**Comment by Pason2C** [comment]
@liudongmiao 更新至0.9.6后已解决。
另外，这个是特意改成这个样式的吗？
![1491275556(1).png](https://ooo.0o0.ooo/2017/04/04/58e30f9cd32c7.png)

**Comment by liudongmiao** [comment]
据部分用户反映，是三星三启了什么缩放。

我使用的是原生控件，就一个 SwitchPreference，没有特意处理。

**Comment by Pason2C** [comment]
之前的版本印象中不是这样，0.9.5因为上述Bug所有没有进设置项看不清楚。
不过，也不影响使用就是了。
OK。关闭。
