### ISSUE TITLE
输入命令手机黑域没反应

### ISSUE THREAD

**Issue by xysf123** [liudongmiao/Brevent#361]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>adb devices
List of devices attached
adb server version (31) doesn't match this client (39); killing...
* daemon started successfully *
91f44f52        device

C:\Users\Administrator>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/lib
brevent.so
WARNING: linker: /data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so: unused
DT entry: type 0x6ffffffe arg 0xa64
WARNING: linker: /data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so: unused
DT entry: type 0x6fffffff arg 0x1
checking...brevent_server started, pid: 5613
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log belo
w
--- crash start ---
>>> logcat -b crash -t '04-04 08:07:28.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-04 08:07:28.000' -d -s BreventLoader BreventServer
D/BreventLoader( 5592): loader path: /data/app/me.piebridge.brevent-1/base.apk
W/BreventServer( 5613): Can't find Settings.Secure.DIALER_DEFAULT_APPLICATION
W/BreventServer( 5613): Can't find Settings.Secure.ASSISTANT
W/BreventServer( 5613): Can't find ActivityManager.PROCESS_STATE_BOUND_FOREGROUN
D_SERVICE
W/BreventServer( 5613): Can't find ActivityManager.PROCESS_STATE_FOREGROUND_SERV
ICE
W/BreventServer( 5613): Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TO
P_TASK
W/BreventServer( 5613): Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TA
SKS
I/BreventServer( 5613): classloader: dalvik.system.PathClassLoader[DexPathList[[
zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[
/vendor/lib64, /system/lib64]]]
I/BreventServer( 5613): Brevent Server 0.9.4 started
W/BreventServer( 5613): Can't find Settings.Secure.DIALER_DEFAULT_APPLICATION
W/BreventServer( 5613): Can't find Settings.Secure.ASSISTANT
W/BreventServer( 5613): Can't find ActivityManager.PROCESS_STATE_BOUND_FOREGROUN
D_SERVICE
W/BreventServer( 5613): Can't find ActivityManager.PROCESS_STATE_FOREGROUND_SERV
ICE
W/BreventServer( 5613): Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TO
P_TASK
W/BreventServer( 5613): Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TA
SKS
I/BreventServer( 5613): brevent user: 0, uid: 2000
I/BreventServer( 5613): brevent data directory: /data/data/com.android.shell
I/BreventServer( 5613): loading brevent list
I/BreventServer( 5613): loading brevent conf
D/BreventServer( 5613): check and brevent
E/BreventLoader( 5592): worker 5613 exited on signal 9
D/BreventLoader( 5592): signal arrived, update: 0
D/BreventLoader( 5590): worker 5592 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/
issues with log above

C:\Users\Administrator>

**Comment by liudongmiao** [comment]
我不对旧版提供任何支持。

请使用最新的 0.9.5 或者最新的测试版，然后再看。
