### ISSUE TITLE
升级最新版还是没反应

### ISSUE THREAD

**Issue by xysf123** [liudongmiao/Brevent#362]
C:\Users\Administrator>adb devices
List of devices attached
91f44f52        device

C:\Users\Administrator>adb -d shell sh /storage/emulated/0/Android/data/me.piebr
idge.brevent/brevent.sh
sh: /storage/emulated/0/Android/data/me.piebridge.brevent/brevent.sh: No such fi
le or directory

**Comment by liudongmiao** [comment]
打开黑域，然后按屏幕提示，不要直接使用。

默认没有这个文件，只要当你要启用时才有。
