### ISSUE TITLE
版本：0.9.5 ；机器：三星note5；adb方法进不去了，好像需要什么权限求解答，谢谢

### ISSUE THREAD

**Issue by ROCKHEARTWINE** [liudongmiao/Brevent#363]
F:\platform-tools-latest-windows\platform-tools>adb devices
List of devices attached
0815f8196c311602        device

F:\platform-tools-latest-windows\platform-tools>adb -d shell sh
shell@nobleltechn:/ $ /sdcard/Android/data/me.piebridge.brevent/brevent.sh
/sdcard/Android/data/me.piebridge.brevent/brevent.sh
sh: /sdcard/Android/data/me.piebridge.brevent/brevent.sh: can't execute: Permission denied
126|shell@nobleltechn:/ $

**Comment by smdx** [comment]
你先输入adb -d shell然后输入su  /sdcard/Android/data/me.piebridge.brevent/brevent.sh试试

**Comment by ROCKHEARTWINE** [comment]
F:\platform-tools-latest-windows\platform-tools>adb -d shell
shell@nobleltechn:/ $ su/sdcard/Android/data/me.piebridge.brevent/brevent.sh
/system/bin/sh: su/sdcard/Android/data/me.piebridge.brevent/brevent.sh: not found
127|shell@nobleltechn:/ $

**Comment by ROCKHEARTWINE** [comment]
不行哎，命令行有个sdcard，这个机器没有外置SD卡是不是这个原因呢？

**Comment by ROCKHEARTWINE** [comment]
F:\platform-tools-latest-windows\platform-tools>adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
checking...

.brevent_server started, pid: 13387
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-04 10:16:07.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-04 10:16:07.000' -d -s BreventLoader BreventServer
04-04 10:16:08.795 13377 13377 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-04 10:16:09.605 13387 13387 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-04 10:16:09.605 13387 13387 I BreventServer: Brevent Server 0.9.5 started
04-04 10:16:09.615 13387 13387 I BreventServer: brevent user: 0, uid: 2000
04-04 10:16:09.615 13387 13387 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-04 10:16:10.235 13387 13387 I BreventServer: loading brevent list
04-04 10:16:10.245 13387 13387 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 35
04-04 10:16:10.245 13387 13387 I BreventServer: loading brevent conf
04-04 10:16:10.315 13387 13387 D BreventServer: check and brevent
04-04 10:16:10.385 13387 13409 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 246518005, 4948, com.sec.android.app.launcher/.activities.LauncherActivity, android.intent.action.MAIN, NULL, NULL, 283115520, android, 0]
04-04 10:16:10.405 13377 13377 E BreventLoader: worker 13387 exited with status 1
04-04 10:16:10.405 13377 13377 D BreventLoader: signal arrived, update: 0
04-04 10:16:10.405 13366 13366 D BreventLoader: worker 13377 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
你这个在 0.9.6 里修了，装最新的 0.9.6 去。
