### ISSUE TITLE
非正常返回bug

### ISSUE THREAD

**Issue by Hidarihitomi** [liudongmiao/Brevent#364]
QQ没有黑域，但是开了非正常返回开关的话过段时间QQ就被杀了，关掉后测试正常

**Comment by liudongmiao** [comment]
黑域只处理黑域内应用。
请带上日志，日志里黑域杀时，会有记录。

否则，不是黑域处理的。

**Comment by Hidarihitomi** [comment]
多次确认，非黑域原因，抱歉…
