### ISSUE TITLE
关于启动后很长时间才能获得app进程列表的反馈

### ISSUE THREAD

**Issue by digiw** [liudongmiao/Brevent#365]
柳兄，你说起的最好不要重启，由于总会遇到重启的情况，
所以我尝试就当全新安装黑域（不管root那些事），如果将你的sh脚本放到sdcard指定目录下，连接电脑用adb指令执行启动，电脑端反馈启动黑域服务正常；
但是此时打开黑域显示的是”复制指令“启动黑域服务的界面，不能获取到进程；
此时电脑上查看黑域的日志，发现貌似是它正忙着杀后台（我500多个app后台热闹），
手机屏幕的黑域界面上是一直处于跳闪“复制指令”的提示框窗口状态，大约需要18分钟左右最后能在黑域里获取到后台进程，
注：由于先前装过框架的阻止运行，接此设置好了黑域的阻止app列表，
但如果是完全新装黑域，未配置过阻止列表，这么多app开机后卡死手机，黑域想要获得进程列表并首次配置，会不会很不乐观？
当时的电脑端日志如下：
G:\adb tools>adb devices
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached
b8b05e30 device

G:\adb tools>adb -d shell sh /sdcard/android/data/me.piebridge.brevent/brevent.sh
checking...brevent_server started, pid: 28713
checking for stable...........ok

if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

G:\adb tools>logcat -b main -d -s breventloader breventserver
DNS 服务器对区域没有权威。

G:\adb tools>adb -d logcat -d -b main -s BreventServer BreventLoader
04-03 23:10:31.058 28713 28713 D BreventServer: checking feelgood
04-03 23:10:31.067 28713 28736 D BreventServer: received feelgood
04-03 23:10:31.070 28713 28713 D BreventServer: Force stop com.xunlei.downloadprovider(killed)
04-03 23:10:31.152 28713 28713 D BreventServer: Force stop com.ymall.presentshop(killed)
04-03 23:10:31.256 28713 28713 D BreventServer: Force stop com.starbucks.cn(killed 2)
04-03 23:10:31.373 28713 28713 D BreventServer: Force stop com.yit.v1(killed)
04-03 23:10:31.409 28713 28713 D BreventServer: Force stop com.ymall.presentshop(killed 2)
04-03 23:10:32.637 28713 28713 D BreventServer: check and brevent
04-03 23:10:33.231 28713 28713 D BreventServer: Force stop com.dream.ipm(forceStop)
04-03 23:10:33.284 28713 28713 D BreventServer: Force stop com.mmmono.mono(service)
04-03 23:10:33.305 28713 28713 D BreventServer: Force stop com.yty.minerva(service)
04-03 23:10:33.336 28713 28713 D BreventServer: Force stop com.umetrip.android.msky.app(foreground service no notification)
04-03 23:10:33.408 28713 28713 D BreventServer: Force stop com.xunlei.downloadprovider(service)
04-03 23:10:33.526 28713 28713 D BreventServer: Force stop com.hengtiansoft.zhaike(service)
04-03 23:10:33.594 28713 28713 D BreventServer: Force stop com.environmentpollution.activity(service)
04-03 23:10:33.642 28713 28713 D BreventServer: Force stop net.luoo.LuooFM(service)
04-03 23:10:33.762 28713 28713 D BreventServer: Force stop com.gbanker.gbankerandroid(service)
04-03 23:10:33.890 28713 28713 D BreventServer: Force stop com.myzaker.ZAKER_Phone(service)
04-03 23:10:33.960 28713 28713 D BreventServer: Force stop com.xueqiu.android(forceStop)
04-03 23:10:33.999 28713 28713 D BreventServer: Force stop com.theinitium.news(service)
04-03 23:10:34.115 28713 28713 D BreventServer: Force stop com.dailyyoga.cn(forceStop)
04-03 23:10:34.139 28713 28713 D BreventServer: Force stop com.yit.v1(service)
04-03 23:10:34.178 28713 28713 D BreventServer: Force stop com.starbucks.cn(service)
04-03 23:10:34.295 28713 28713 D BreventServer: Force stop com.ymall.presentshop(service)
04-03 23:10:34.317 28713 28713 D BreventServer: Force stop com.beevle.xz.renxing.gdong(service)
04-03 23:10:34.329 28713 28713 D BreventServer: check again in 3600s
04-03 23:10:34.329 28713 28713 D BreventServer: check and brevent, took 1691ms

G:\adb tools>adb -d logcat -d -b main -s BreventServer BreventLoader
04-03 23:11:25.230 28713 28713 D BreventServer: checking feelgood
04-03 23:11:25.231 28713 28713 W BreventServer: avoid killing com.starbucks.cn
04-03 23:11:25.231 28713 28713 W BreventServer: avoid killing com.yit.v1
04-03 23:11:25.232 28713 28713 W BreventServer: avoid killing com.myzaker.ZAKER_Phone
04-03 23:11:25.232 28713 28736 D BreventServer: received feelgood
04-03 23:11:26.876 28713 28713 D BreventServer: check and brevent
04-03 23:11:27.601 28713 28713 D BreventServer: Force stop com.nextcloud.client(forceStop)
04-03 23:11:27.666 28713 28713 D BreventServer: Force stop com.smi.wcloud(service)
04-03 23:11:27.882 28713 28713 D BreventServer: Force stop com.tencent.androidqqmail(forceStop)
04-03 23:11:28.073 28713 28713 D BreventServer: Force stop com.mmmono.mono(forceStop)
04-03 23:11:28.120 28713 28713 D BreventServer: Force stop com.mingzhihuatong.muochi(forceStop)
04-03 23:11:28.157 28713 28713 D BreventServer: Force stop com.umetrip.android.msky.app(foreground service no notification)
04-03 23:11:28.246 28713 28713 D BreventServer: Force stop com.budejie.www(service)
04-03 23:11:28.434 28713 28713 D BreventServer: Force stop com.hengtiansoft.zhaike(service)
04-03 23:11:28.483 28713 28713 D BreventServer: Force stop com.mfw.roadbook(forceStop)
04-03 23:11:28.585 28713 28713 D BreventServer: Force stop com.ttyongche(forceStop)
04-03 23:11:28.818 28713 28713 D BreventServer: Force stop com.mirroon.spoon(service)
04-03 23:11:28.853 28713 28713 D BreventServer: Force stop com.myzaker.ZAKER_Phone(service)
04-03 23:11:29.091 28713 28713 D BreventServer: Force stop com.autohome.usedcar(forceStop)
04-03 23:11:29.194 28713 28713 D BreventServer: Force stop com.gewara(service)
04-03 23:11:29.272 28713 28713 D BreventServer: Force stop com.mobike.mobikeapp(forceStop)
04-03 23:11:29.293 28713 28713 D BreventServer: Force stop com.linkedin.android(forceStop)
04-03 23:11:29.401 28713 28713 D BreventServer: Force stop com.yit.v1(service)
04-03 23:11:29.433 28713 28713 D BreventServer: Force stop com.sjtu.chenzhongpu.cloudbooks(forceStop)
04-03 23:11:29.584 28713 28713 D BreventServer: Force stop com.starbucks.cn(service)
04-03 23:11:29.834 28713 28713 D BreventServer: Force stop com.kekeclient_(service)
04-03 23:11:29.887 28713 28713 D BreventServer: Force stop com.dp.android.elong(forceStop)
04-03 23:11:29.903 28713 28713 D BreventServer: check again in 3600s
04-03 23:11:29.903 28713 28713 D BreventServer: check and brevent, took 3025ms

G:\adb tools>adb -d logcat -d -b main -s BreventServer BreventLoader
04-03 23:11:47.932 28713 28713 D BreventServer: check and brevent
04-03 23:12:04.179 28713 28713 D BreventServer: checking feelgood
04-03 23:12:04.180 28713 28713 W BreventServer: avoid killing com.starbucks.cn
04-03 23:12:04.180 28713 28713 W BreventServer: avoid killing com.yit.v1
04-03 23:12:04.180 28713 28713 W BreventServer: avoid killing com.myzaker.ZAKER_Phone
04-03 23:12:04.181 28713 28736 D BreventServer: received feelgood
04-03 23:12:04.212 28713 28713 D BreventServer: Force stop com.eg.android.AlipayGphone(killed)
04-03 23:12:04.222 28713 28713 W BreventServer: avoid killing com.ymall.presentshop
04-03 23:12:04.277 28713 28713 D BreventServer: Force stop com.environmentpollution.activity(killed)
04-03 23:12:04.296 28713 28713 W BreventServer: avoid killing com.myzaker.ZAKER_Phone
04-03 23:12:05.968 28713 28713 D BreventServer: check and brevent
04-03 23:12:06.357 28713 28713 D BreventServer: Force stop com.mmmono.mono(service)
04-03 23:12:06.380 28713 28713 D BreventServer: Force stop com.umetrip.android.msky.app(foreground service no notification)
04-03 23:12:06.457 28713 28713 D BreventServer: Force stop com.xunlei.downloadprovider(service)
04-03 23:12:06.552 28713 28713 D BreventServer: Force stop com.hengtiansoft.zhaike(service)
04-03 23:12:06.644 28713 28713 D BreventServer: Force stop com.environmentpollution.activity(service)
04-03 23:12:06.686 28713 28713 D BreventServer: Force stop com.myzaker.ZAKER_Phone(service)
04-03 23:12:06.744 28713 28713 D BreventServer: Force stop com.sankuai.movie(forceStop)
04-03 23:12:06.779 28713 28713 D BreventServer: Force stop com.jingdong.app.mall(forceStop)
04-03 23:12:06.847 28713 28713 D BreventServer: Force stop com.yit.v1(service)
04-03 23:12:06.869 28713 28713 D BreventServer: Force stop com.starbucks.cn(service)
04-03 23:12:06.983 28713 28713 D BreventServer: Force stop com.kekeclient_(service)
04-03 23:12:07.097 28713 28713 D BreventServer: Force stop com.ymall.presentshop(service)
04-03 23:12:07.137 28713 28713 D BreventServer: Force stop com.eg.android.AlipayGphone(service)
04-03 23:12:07.155 28713 28713 D BreventServer: check again in 3600s
04-03 23:12:07.156 28713 28713 D BreventServer: check and brevent, took 1187ms

**Comment by liudongmiao** [comment]
参见设置中，保持通知底下的说明，不要检查通知。

我估计你机器上获取通知耗时太长，从而 block 整个过程。
