### ISSUE TITLE
正在获取进程状态，请稍候...

### ISSUE THREAD

**Issue by Flammulinavelutipes** [liudongmiao/Brevent#367]
Nexus6，原生7.1.1+MagiskSU，已授予ROOT权限，Play版已捐赠
点击ROOT开启，显示正在获取进程状态，请稍候...然后又会回到之前界面，永远无法进入黑域

**Comment by liudongmiao** [comment]
日志，日志，日志。

没有日志，我永远不知道发生了什么。

**Comment by Flammulinavelutipes** [comment]
04-04 18:10:41.781  6147  6171 D BreventUI: checking....brevent_server started, pid: 7105
04-04 18:10:41.781  6147  6171 D BreventUI: checking for stable..quited
04-04 18:10:41.781  6147  6171 D BreventUI:
04-04 18:10:41.781  6147  6171 D BreventUI: please report bug to https://github.com/liudongmiao/Brevent/issues with log below
04-04 18:10:41.781  6147  6171 D BreventUI: --- crash start ---
04-04 18:10:41.781  6147  6171 D BreventUI: >>> logcat -b crash -t '04-04 18:10:39.000' -d
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime: java.lang.reflect.InvocationTargetException
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime:    at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1519)
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime:    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime:    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime: Caused by: me.piebridge.brevent.server.d$a: Can't dump activities
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime:    at me.piebridge.brevent.server.d.d(HideApi.java:327)
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime:    at me.piebridge.brevent.server.BreventServer.o(BreventServer.java:1346)
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime:    at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:465)
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime:    at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1497)
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime:    ... 4 more
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.662  7105  7105 E AndroidRuntime: Error reporting crash
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.662  7105  7105 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.662  7105  7105 E AndroidRuntime:    at android.os.BinderProxy.transactNative(Native Method)
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.662  7105  7105 E AndroidRuntime:    at android.os.BinderProxy.transact(Binder.java:615)
04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.662  7105  7105 E AndroidRuntime:    at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5133)
04-04 18:10:41.782  6147  6171 D BreventUI: 04-04 18:10:41.662  7105  7105 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
04-04 18:10:41.782  6147  6171 D BreventUI: 04-04 18:10:41.662  7105  7105 E AndroidRuntime:    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
04-04 18:10:41.782  6147  6171 D BreventUI: 04-04 18:10:41.662  7105  7105 E AndroidRuntime:    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
04-04 18:10:41.782  6147  6171 D BreventUI: --- crash end ---

**Comment by liudongmiao** [comment]
> 04-04 18:10:41.781  6147  6171 D BreventUI: 04-04 18:10:41.661  7105  7105 E AndroidRuntime: Caused by: me.piebridge.brevent.server.d$a: Can't dump activities

1. 装这个最新测试版： https://piebridge.me/br/next/

2. 重启，然后再看。

**Comment by Flammulinavelutipes** [comment]
+6版、+8版都试过了，还是不行

**Comment by jieyujing** [comment]
我也遇到同样的问题
