### ISSUE TITLE
sh脚本的路径不对...

### ISSUE THREAD

**Issue by woaihsw** [liudongmiao/Brevent#369]
魅族，5.1.1

app提示我的脚本在/storage/emulated/0/Android/data/me.piebridge.brevent/brevent.sh

实际脚本位置在/storage/emulated/legacy/Android/data/me.piebridge.brevent/brevent.sh

刚开始提示我No such file or directory，后来shell进去才找到正确的路径...

**Comment by liudongmiao** [comment]
一般来说，你使用 /sdcard/Android/data/me.piebridge.brevent/brevent.sh 就好。
但是，如果你机器上特殊处理，我也没有办法啊。

绝大部分机器上都没有问题，以后我再想办法。

**Comment by liudongmiao** [comment]
`/sdcard/Android/data/me.piebridge.brevent/brevent.sh` 这个地址可以么？

**Comment by woaihsw** [comment]
这个路径是ok的

**Comment by liudongmiao** [comment]
你看下这个测试版： https://piebridge.me/br/next/

**Comment by woaihsw** [comment]
输出路径依然不对...

**Comment by liudongmiao** [comment]
你执行下这个，然后给下我结果吧：

```
adb -d shell ls -l /storage/emulated/
```

**Comment by woaihsw** [comment]
legacy -> /mnt/shell/emulated/0


2017-04-04 21:14 GMT+08:00 Liu DongMiao <notifications@github.com>:

**Comment by liudongmiao** [comment]
这个我认真看了下，真的没法处理。

> E/BreventUI(32414): cannot read link for /storage/emulated/0
E/BreventUI(32414): android.system.ErrnoException: readlink failed: EINVAL (Invalid argument)

> E/BreventUI(32414): cannot read link for /storage/emulated/legacy
E/BreventUI(32414): android.system.ErrnoException: readlink failed: EINVAL (Invalid argument)

而且，在我这边的魅族 5.1 上，/storage/emulated/0 与 /storage/emulated/legacy 都指向 /mnt/shell/emulated/0，但是 API 无法返回他们是同一个。

**Comment by liudongmiao** [comment]
而直接写死，不是我风格。
