### ISSUE TITLE
黑域root版，手机京东按back键杀不掉

### ISSUE THREAD

**Issue by liushuai0929** [liudongmiao/Brevent#37]
Android: zh_CN_#Hans-7.0
黑域: 0.4
OnePlus/OnePlus3/OnePlus3:7.0/NRD90M/12060155:user/release-keys
手机京东按back杀不掉，从最近任务列表划掉可以杀掉。帮酷友反馈的。

**Comment by liushuai0929** [comment]
12306也是这些

**Comment by wudimenghuan** [comment]
这个是正常的吧？有的app就是这么设计的啊，比如微信

**Comment by liushuai0929** [comment]
关键是这些软件被加到阻止列表里面了，黑域对他们没作用

**Comment by liudongmiao** [comment]
会处理的。

**Comment by liudongmiao** [comment]
http://piebridge.me/br/ 这里的版本应该已经处理了，请帮忙看看。

**Comment by liudongmiao** [comment]
请使用最新 beta 版测试：piebridge.me/br/

如果还有这个问题，请重开这个问题，谢谢。
