### ISSUE TITLE
安卓6.0 启动失败

### ISSUE THREAD

**Issue by lelemka0** [liudongmiao/Brevent#371]
--- crash start ---
>>> logcat -b crash -t '04-04 22:51:50.000' -d
open /proc/kmsg failed: Permission denied
04-04 22:51:53.809 21337 21337 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-04 22:51:53.809 21337 21337 E AndroidRuntime: java.lang.reflect.InvocationTargetException
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.
java:1519)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native M
ethod)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251
)
04-04 22:51:53.809 21337 21337 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException:  is not a constant in an
droid.text.Layout$Alignment
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at java.lang.Enum.valueOf(Enum.java:200)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.text.Layout$Alignment.valueOf(Layout.java:2017)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpa
n.java:33)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java:711)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java:684)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.readFromParcel(Act
ivityManager.java:944)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityMan
ager.java:969)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityMan
ager.java:810)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel
(ActivityManager.java:961)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel
(ActivityManager.java:959)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.os.Parcel.createTypedArrayList(Parcel.java:2007)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at android.app.ActivityManagerProxy.getRecentTasks(ActivityManag
erNative.java:3332)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at me.piebridge.brevent.a.b.a(HideApiOverrideM.java:22)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.g(BreventServer.jav
a:815)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.e(BreventServer.jav
a:470)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.startBreventServer(
BreventServer.java:1497)
04-04 22:51:53.809 21337 21337 E AndroidRuntime:        ... 4 more
04-04 22:51:53.814 21337 21337 E AndroidRuntime: Error reporting crash
04-04 22:51:53.814 21337 21337 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-04 22:51:53.814 21337 21337 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
04-04 22:51:53.814 21337 21337 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:532)
04-04 22:51:53.814 21337 21337 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(Activ
ityManagerNative.java:4466)
04-04 22:51:53.814 21337 21337 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtE
xception(RuntimeInit.java:90)
04-04 22:51:53.814 21337 21337 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
04-04 22:51:53.814 21337 21337 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-04 22:51:50.000' -d -s BreventLoader BreventServer
open /proc/kmsg failed: Permission denied
04-04 22:51:51.201 21327 21327 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-04 22:51:51.797 21337 21337 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/
app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-04 22:51:51.817 21337 21337 I BreventServer: Brevent Server 0.9.6 started
04-04 22:51:51.835 21337 21337 I BreventServer: brevent user: 0, uid: 2000
04-04 22:51:51.837 21337 21337 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-04 22:51:52.604 21337 21337 I BreventServer: loading brevent list
04-04 22:51:52.606 21337 21337 I BreventServer: loading brevent conf
04-04 22:51:52.646 21337 21337 D BreventServer: check and brevent
04-04 22:51:53.839 21327 21327 E BreventLoader: worker 21337 exited on signal 9
04-04 22:51:53.839 21327 21327 D BreventLoader: signal arrived, update: 0
04-04 22:51:53.840 21316 21316 D BreventLoader: worker 21327 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by Flammulinavelutipes** [comment]
6.0用阻止运行不是美滋滋？

**Comment by liudongmiao** [comment]
> 04-04 22:51:53.809 21337 21337 E AndroidRuntime: at android.app.ActivityManagerProxy.getRecentTasks(ActivityManag
erNative.java:3332)

没有办法获取最近列表，装个正常的 ROM 吧。
