### ISSUE TITLE
三星c7执行运行命令失败

### ISSUE THREAD

**Issue by a1121611810** [liudongmiao/Brevent#373]
D:\Lld\Downloads\platform-tools-latest-windows\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
04-04 22:49:49.215 10523 10523 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-04 22:49:49.785 10533 10533 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-04 22:49:49.795 10533 10533 I BreventServer: Brevent Server 0.9.5 started
04-04 22:49:49.805 10533 10533 I BreventServer: brevent user: 0, uid: 2000
04-04 22:49:49.805 10533 10533 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-04 22:49:50.155 10533 10533 I BreventServer: loading brevent list
04-04 22:49:50.155 10533 10533 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 51
04-04 22:49:50.155 10533 10533 I BreventServer: loading brevent conf
04-04 22:49:50.185 10533 10533 D BreventServer: check and brevent
04-04 22:49:50.205 10533 10541 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 151580885, 2189, com.tencent.androidqqmail/moai.daemon.DaemonActivity, NULL, NULL, NULL, 276824064, com.tencent.androidqqmail, 0]
04-04 22:49:50.215 10523 10523 E BreventLoader: worker 10533 exited with status 1
04-04 22:49:50.215 10523 10523 D BreventLoader: signal arrived, update: 0
04-04 22:49:50.215 10512 10512 D BreventLoader: worker 10523 exited with status 0
04-04 22:58:44.545 11295 11295 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-04 22:58:45.135 11305 11305 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-04 22:58:45.145 11305 11305 I BreventServer: Brevent Server 0.9.5 started
04-04 22:58:45.145 11305 11305 I BreventServer: brevent user: 0, uid: 2000
04-04 22:58:45.145 11305 11305 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-04 22:58:45.615 11305 11305 I BreventServer: loading brevent list
04-04 22:58:45.615 11305 11305 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 51
04-04 22:58:45.615 11305 11305 I BreventServer: loading brevent conf
04-04 22:58:45.655 11305 11305 D BreventServer: check and brevent
04-04 22:58:45.675 11305 11313 E BreventServer: names: [user, token, taskId, componentName, action, mimeType, uri, flags, launchedFromPackage], events: [0, 151580885, 2189, com.tencent.androidqqmail/moai.daemon.DaemonActivity, NULL, NULL, NULL, 276824064, com.tencent.androidqqmail, 0]
04-04 22:58:45.695 11295 11295 E BreventLoader: worker 11305 exited with status 1
04-04 22:58:45.695 11295 11295 D BreventLoader: signal arrived, update: 0
04-04 22:58:45.695 11284 11284 D BreventLoader: worker 11295 exited with status 0

D:\Lld\Downloads\platform-tools-latest-windows\platform-tools>

![Uploading 微信图片_20170404230134.jpg…]()

**Comment by liudongmiao** [comment]
装最新的 0.9.6 或更高版本。
