### ISSUE TITLE
黒域导致一些Google应用闪退

### ISSUE THREAD

**Issue by EnmaFamiliar** [liudongmiao/Brevent#374]
将Google一些自带的如play商店，Google日历，Google相册这些黒域后打开应用会闪退

**Comment by EnmaFamiliar** [comment]
04-05 08:36:11.794 20262 20262 D BreventServer: check and brevent
04-05 08:36:11.967 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:36:11.974 20262 20262 D BreventServer: check and brevent, took 176ms
04-05 08:36:18.147 20262 20262 D BreventServer: checking feelgood
04-05 08:36:18.147 20262 20277 D BreventServer: received feelgood
04-05 08:37:10.112 20262 20262 D BreventServer: checking feelgood
04-05 08:37:10.117 20262 20277 D BreventServer: received feelgood
04-05 08:37:10.869 20262 20262 I BreventServer: real home tid: 18825
04-05 08:37:13.871 20262 20262 D BreventServer: check and brevent
04-05 08:37:13.962 20262 20262 D BreventServer: check and brevent, took 90ms
04-05 08:38:48.760 20262 20262 D BreventServer: check and brevent
04-05 08:38:48.841 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:38:48.846 20262 20262 D BreventServer: check and brevent, took 84ms
04-05 08:38:51.927 20262 20262 D BreventServer: check and brevent
04-05 08:38:51.992 20262 20262 D BreventServer: check and brevent, took 64ms
04-05 08:38:57.370 20262 20262 D BreventServer: checking feelgood
04-05 08:38:57.370 20262 20277 D BreventServer: received feelgood
04-05 08:38:59.066 20262 20262 D BreventServer: check and brevent
04-05 08:38:59.125 20262 20262 D BreventServer: check and brevent, took 58ms
04-05 08:39:12.288 20262 20262 D BreventServer: check and brevent
04-05 08:39:12.397 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:39:12.405 20262 20262 D BreventServer: Force stop com.android.vending(service)
04-05 08:39:12.408 20262 20262 D BreventServer: check and brevent, took 117ms
04-05 08:39:22.119 20262 20262 D BreventServer: checking feelgood
04-05 08:39:22.121 20262 20277 D BreventServer: received feelgood
04-05 08:39:29.962 20262 20262 I BreventServer: real home tid: 18825
04-05 08:39:35.610 20262 20262 D BreventServer: check and brevent
04-05 08:39:35.777 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:39:35.779 20262 20262 D BreventServer: check and brevent, took 168ms
04-05 08:39:55.517 20262 20262 D BreventServer: check and brevent
04-05 08:39:55.698 20262 20262 D BreventServer: Force stop com.android.providers.calendar(noRecent)
04-05 08:39:55.705 20262 20262 D BreventServer: check and brevent, took 185ms
04-05 08:40:02.078 20262 20262 D BreventServer: check and brevent
04-05 08:40:02.215 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:40:02.221 20262 20262 D BreventServer: Force stop com.android.vending(noRecent)
04-05 08:40:02.222 20262 20262 D BreventServer: check and brevent, took 143ms
04-05 08:40:08.494 20262 20262 D BreventServer: check and brevent
04-05 08:40:08.621 20262 20262 D BreventServer: check and brevent, took 126ms
04-05 08:40:32.302 20262 20262 D BreventServer: check and brevent
04-05 08:40:32.432 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:40:32.448 20262 20262 D BreventServer: Force stop com.estrongs.android.pop(service)
04-05 08:40:32.455 20262 20262 D BreventServer: check and brevent, took 152ms
04-05 08:40:48.632 20262 20262 D BreventServer: checking feelgood
04-05 08:40:48.632 20262 20277 D BreventServer: received feelgood
04-05 08:41:00.197 20262 20262 D BreventServer: check and brevent
04-05 08:41:00.328 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:41:00.337 20262 20262 D BreventServer: Force stop com.android.vending(service)
04-05 08:41:00.349 20262 20262 D BreventServer: Force stop com.google.android.talk(noRecent)
04-05 08:41:00.351 20262 20262 D BreventServer: check and brevent, took 153ms
04-05 08:41:01.763 20262 20262 D BreventServer: checking feelgood
04-05 08:41:01.767 20262 20277 D BreventServer: received feelgood
04-05 08:41:23.754 20262 20262 I BreventServer: real home tid: 941
04-05 08:41:26.754 20262 20262 D BreventServer: check and brevent
04-05 08:41:26.896 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:41:26.911 20262 20262 D BreventServer: check and brevent, took 156ms
04-05 08:42:31.057 20262 20262 D BreventServer: checking feelgood
04-05 08:42:31.059 20262 20277 D BreventServer: received feelgood
04-05 08:42:33.615 20262 20262 D BreventServer: check and brevent
04-05 08:42:33.812 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:42:33.814 20262 20262 D BreventServer: check and brevent, took 198ms
04-05 08:42:40.348 20262 20262 D BreventServer: check and brevent
04-05 08:42:40.472 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:42:40.474 20262 20262 D BreventServer: check and brevent, took 126ms
04-05 08:42:42.465 20262 20262 D BreventServer: checking feelgood
04-05 08:42:42.466 20262 20277 D BreventServer: received feelgood
04-05 08:42:43.170 20262 20262 I BreventServer: real home tid: 2810
04-05 08:42:46.172 20262 20262 D BreventServer: check and brevent
04-05 08:42:46.293 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:42:46.295 20262 20262 D BreventServer: check and brevent, took 122ms
04-05 08:42:49.334 20262 20262 D BreventServer: check and brevent
04-05 08:42:49.452 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:42:49.454 20262 20262 D BreventServer: check and brevent, took 119ms
04-05 08:43:03.173 20262 20262 D BreventServer: check and brevent
04-05 08:43:03.338 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:43:03.342 20262 20262 D BreventServer: check and brevent, took 167ms
04-05 08:43:07.576 20262 20262 D BreventServer: checking feelgood
04-05 08:43:07.576 20262 20277 D BreventServer: received feelgood
04-05 08:43:13.653 20262 20262 D BreventServer: check and brevent
04-05 08:43:13.805 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:43:13.809 20262 20262 D BreventServer: check and brevent, took 154ms
04-05 08:43:44.742 20262 20262 D BreventServer: check and brevent
04-05 08:43:44.886 20262 20262 D BreventServer: Force stop com.google.android.gm(service)
04-05 08:43:44.897 20262 20262 D BreventServer: Force stop com.google.android.partnersetup(noRecent)
04-05 08:43:44.906 20262 20262 D BreventServer: Force stop com.android.providers.blockednumber(noRecent)
04-05 08:43:44.911 20262 20262 D BreventServer: Force stop com.android.providers.contacts(noRecent)
04-05 08:43:44.915 20262 20262 D BreventServer: check and brevent, took 172ms
04-05 08:47:48.402 20262 20262 D BreventServer: checking feelgood
04-05 08:47:48.403 20262 20277 D BreventServer: received feelgood
04-05 08:47:50.547 20262 20262 I BreventServer: real home tid: 2810
04-05 08:47:53.549 20262 20262 D BreventServer: check and brevent
04-05 08:47:53.689 20262 20262 D BreventServer: Force stop com.google.android.talk(noRecent)
04-05 08:47:53.709 20262 20262 D BreventServer: Force stop com.android.providers.blockednumber(noRecent)
04-05 08:47:53.719 20262 20262 D BreventServer: Force stop com.android.providers.contacts(noRecent)
04-05 08:47:53.727 20262 20262 D BreventServer: check and brevent, took 176ms
04-05 08:47:56.727 20262 20262 D BreventServer: check and brevent
04-05 08:47:56.834 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:47:56.846 20262 20262 D BreventServer: check and brevent, took 118ms
04-05 08:50:14.211 20262 20262 D BreventServer: check and brevent
04-05 08:50:14.384 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:50:14.389 20262 20262 D BreventServer: check and brevent, took 177ms
04-05 08:50:22.901 20262 20262 D BreventServer: check and brevent
04-05 08:50:23.047 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:50:23.052 20262 20262 D BreventServer: check and brevent, took 148ms
04-05 08:51:05.052 20262 20262 D BreventServer: check and brevent
04-05 08:51:05.539 20262 20262 D BreventServer: check again in 3425s
04-05 08:51:05.539 20262 20262 D BreventServer: check and brevent, took 486ms
04-05 08:51:27.734 20262 20262 D BreventServer: check and brevent
04-05 08:51:27.844 20262 20262 D BreventServer: Force stop com.google.android.talk(noRecent)
04-05 08:51:27.845 20262 20262 D BreventServer: check again in 600s
04-05 08:51:27.845 20262 20262 D BreventServer: check and brevent, took 110ms
04-05 08:52:50.106 20262 20262 D BreventServer: check and brevent
04-05 08:52:50.266 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:52:50.278 20262 20262 D BreventServer: Force stop com.google.android.apps.photos(noRecent)
04-05 08:52:50.285 20262 20262 D BreventServer: Force stop com.android.providers.blockednumber(noRecent)
04-05 08:52:50.289 20262 20262 D BreventServer: Force stop com.android.providers.contacts(noRecent)
04-05 08:52:50.292 20262 20262 D BreventServer: check again in 597s
04-05 08:52:50.292 20262 20262 D BreventServer: check and brevent, took 184ms
04-05 08:54:30.209 20262 20262 D BreventServer: check and brevent
04-05 08:54:30.326 20262 20262 D BreventServer: Force stop com.android.printspooler(service)
04-05 08:54:30.335 20262 20262 D BreventServer: check again in 597s
04-05 08:54:30.335 20262 20262 D BreventServer: check and brevent, took 125ms
04-05 08:54:45.942 20262 20262 D BreventServer: check and brevent
04-05 08:54:46.099 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:54:46.112 20262 20262 D BreventServer: Force stop com.android.printspooler(service)
04-05 08:54:46.114 20262 20262 D BreventServer: check again in 3596s
04-05 08:54:46.114 20262 20262 D BreventServer: check and brevent, took 171ms
04-05 08:55:20.000 20262 20262 D BreventServer: check and brevent
04-05 08:55:20.108 20262 20262 D BreventServer: Force stop com.android.printspooler(service)
04-05 08:55:20.114 20262 20262 D BreventServer: check again in 600s
04-05 08:55:20.114 20262 20262 D BreventServer: check and brevent, took 113ms
04-05 08:55:43.318 20262 20262 D BreventServer: checking feelgood
04-05 08:55:43.318 20262 20277 D BreventServer: received feelgood
04-05 08:55:45.045 20262 20262 D BreventServer: check and brevent
04-05 08:55:45.168 20262 20262 D BreventServer: Force stop com.android.providers.media(noRecent)
04-05 08:55:45.182 20262 20262 D BreventServer: check again in 3537s
04-05 08:55:45.182 20262 20262 D BreventServer: check and brevent, took 136ms
04-05 08:56:18.058 20262 20262 D BreventServer: check and brevent
04-05 08:56:18.229 20262 20262 D BreventServer: check again in 3504s
04-05 08:56:18.229 20262 20262 D BreventServer: check and brevent, took 168ms
04-05 08:56:23.756 20262 20262 D BreventServer: checking feelgood
04-05 08:56:23.761 20262 20277 D BreventServer: received feelgood
04-05 08:56:25.612 20262 20262 I BreventServer: real home tid: 941
04-05 08:56:28.613 20262 20262 D BreventServer: check and brevent
04-05 08:56:28.783 20262 20262 D BreventServer: Force stop com.google.android.talk(noRecent)
04-05 08:56:28.784 20262 20262 D BreventServer: check again in 3494s
04-05 08:56:28.784 20262 20262 D BreventServer: check and brevent, took 168ms

----机型：Nexus 5x，Android 7.1.2-4月正式版，已root----

**Comment by liudongmiao** [comment]
谁鼓励你去黑域那些默认不显示的应用?

**Comment by liudongmiao** [comment]
此外，最新测试版把这部分应用强制为重要，不会再杀已经发现的 Android 进程。
你可以前去体验： https://piebridge.me/br/next/

**Comment by liudongmiao** [comment]
但是，即使是这个最新测试版，依然不能解决你黑域了“日历存储”，然后要打开“谷歌日历”问题。

你的主要原因不在于黑域这些你可见的应用，可是黑域那些 `com.android.providers.*` 的应用，具体的话，自己看日志。

**Comment by EnmaFamiliar** [comment]
嗯，主要以前在老的7.0上是用着你原来阻止运行补丁版黑域这些一直都没事，现在更新到新的系统和黑域后就遇到这个google应用闪退问题了

**Comment by liudongmiao** [comment]
1. 之前处理逻辑不如现在高效简单。
2. 之前为系统应用特别优化，有些尽力阻挡，阻不住就不处理，避免误杀。

现在的话，更多交给用户，然后认真识别重要应用。

**Comment by liudongmiao** [comment]
此外，还有，黑域是事后处理，而阻止运行是事前处理。

所以，有些应用没有它时，可以启动；但是有了它，又要杀掉它，就会崩溃。

**Comment by heiyuheiyu** [comment]
我的做法是 用re删除 系统自带的 play商店，Google日历，Google相册，然后再从play商店 ，如上三个应用。play商店 是更新后删除 system app下自带的。 只保留  data/app 里的。
这样 黑域这三个 没有任何影响。而且 这三个 出现在了 黑域 “用户应用” 列表里

**Comment by chm512512** [comment]
牛逼啊 你师全选黑域吧，什么都黑了，媒体储存都黑。我黑商店怎么就没闪退了
