### ISSUE TITLE
新版 v0.9.6+9  问题反馈 （不知道 是不是偶然）

### ISSUE THREAD

**Issue by heiyuheiyu** [liudongmiao/Brevent#375]
昨晚后来试了您的测试版 v0.9.6+9.  发现您把uc 设定为 “辅助应用” 。无法选择 加入可黑域的app名单中。同时也就无法到时间后，进行待机 或者 超时后进行强杀的处理。
这些都没什么， 因为是测试版，您对uc的这种设置 可能是出于某种考虑。 
但发现了一个问题。 从后台列表划去 uc后 uc被强杀，从黑域“正在运行”的列表里也消失了。
过了几分钟后 又被唤醒，出现在正在运行列表，并一直保持在“正在运行”里。（期间我并没有打开过 uc，系统后台列表里也没） 我觉得出现这种唤醒 是不是 跟 uc设定为  “辅助应用”  有关？ 下面是我进行的日志采集
补充一句  我抓下面两个日志的时候 uc 正是被唤醒后 保持在黑域正在运行列表里的，不是我打开的。
*****************************************************************************
F:\platform-tools>adb -d shell setprop log.tag.BreventServer DEBUG
* daemon not running. starting it now on port 5037 *
* daemon started successfully *

F:\platform-tools>adb -d shell setprop log.tag.BreventServer DEBUG

F:\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
04-05 08:36:50.476 25811 25811 D BreventServer: check and brevent
04-05 08:36:50.671 25811 25811 D BreventServer: check again in 189s
04-05 08:36:50.671 25811 25811 D BreventServer: check and brevent, took 193ms
04-05 08:37:57.355 25811 25811 D BreventServer: check and brevent
04-05 08:37:57.708 25811 25811 D BreventServer: check again in 122s
04-05 08:37:57.708 25811 25811 D BreventServer: check and brevent, took 350ms
04-05 08:43:31.792 25811 25811 D BreventServer: check and brevent
04-05 08:43:32.159 25811 25811 D BreventServer: Force stop me.piebridge.brevent(noRecent)
04-05 08:43:32.161 25811 25811 D BreventServer: check again in 3600s
04-05 08:43:32.161 25811 25811 D BreventServer: check and brevent, took 365ms
04-05 08:59:00.740 25811 25811 D BreventServer: check and brevent
04-05 08:59:00.866 25811 25811 D BreventServer: Force stop org.zooper.zwpro(noRecent)
04-05 08:59:00.867 25811 25811 D BreventServer: check again in 298s
04-05 08:59:00.867 25811 25811 D BreventServer: check and brevent, took 125ms
04-05 09:09:15.180 25811 25811 D BreventServer: check and brevent
04-05 09:09:15.288 25811 25811 D BreventServer: check again in 299s
04-05 09:09:15.288 25811 25811 D BreventServer: check and brevent, took 107ms
04-05 09:09:15.312 25811 25811 D BreventServer: checking feelgood
04-05 09:09:15.314 25811 25820 D BreventServer: received feelgood
04-05 09:09:20.983 25811 25811 D BreventServer: check and brevent
04-05 09:09:21.113 25811 25811 D BreventServer: check again in 293s
04-05 09:09:21.113 25811 25811 D BreventServer: check and brevent, took 129ms
04-05 09:09:21.152 25811 25811 D BreventServer: checking feelgood
04-05 09:09:21.155 25811 25820 D BreventServer: received feelgood
04-05 09:10:23.499 25811 25811 D BreventServer: check and brevent
04-05 09:10:23.820 25811 25811 D BreventServer: check again in 230s
04-05 09:10:23.820 25811 25811 D BreventServer: check and brevent, took 318ms
04-05 09:12:42.988 25811 25811 D BreventServer: check and brevent
04-05 09:12:43.188 25811 25811 D BreventServer: check again in 91s
04-05 09:12:43.188 25811 25811 D BreventServer: check and brevent, took 180ms
04-05 09:12:43.213 25811 25811 D BreventServer: checking feelgood
04-05 09:12:43.217 25811 25820 D BreventServer: received feelgood
04-05 09:12:48.077 25811 25811 I BreventServer: real home tid: 1824
04-05 09:12:51.082 25811 25811 D BreventServer: check and brevent
04-05 09:12:51.352 25811 25811 D BreventServer: check again in 83s
04-05 09:12:51.353 25811 25811 D BreventServer: check and brevent, took 268ms
04-05 09:13:50.706 25811 25811 D BreventServer: check and brevent
04-05 09:13:51.022 25811 25811 D BreventServer: check again in 23s
04-05 09:13:51.022 25811 25811 D BreventServer: check and brevent, took 313ms
04-05 09:14:11.773 25811 25811 D BreventServer: check and brevent
04-05 09:14:11.963 25811 25811 D BreventServer: check again in 2s
04-05 09:14:11.963 25811 25811 D BreventServer: check and brevent, took 189ms
04-05 09:14:12.022 25811 25811 D BreventServer: checking feelgood
04-05 09:14:12.024 25811 25820 D BreventServer: received feelgood
04-05 09:14:13.969 25811 25811 D BreventServer: check and brevent
04-05 09:14:14.243 25811 25811 D BreventServer: check again in 0s
04-05 09:14:14.243 25811 25811 D BreventServer: check and brevent, took 270ms
04-05 09:14:16.246 25811 25811 D BreventServer: check and brevent
04-05 09:14:16.599 25811 25811 D BreventServer: check again in 296s
04-05 09:14:16.599 25811 25811 D BreventServer: check and brevent, took 351ms
04-05 09:15:17.785 25811 25811 D BreventServer: check and brevent
04-05 09:15:18.135 25811 25811 D BreventServer: check again in 298s
04-05 09:15:18.135 25811 25811 D BreventServer: check and brevent, took 348ms
04-05 09:15:39.950 25811 25811 D BreventServer: check and brevent
04-05 09:15:40.214 25811 25811 D BreventServer: check again in 300s
04-05 09:15:40.214 25811 25811 D BreventServer: check and brevent, took 234ms
04-05 09:15:40.243 25811 25811 D BreventServer: checking feelgood
04-05 09:15:40.245 25811 25820 D BreventServer: received feelgood
04-05 09:16:51.697 25811 25811 D BreventServer: check and brevent
04-05 09:16:52.037 25811 25811 D BreventServer: check again in 298s
04-05 09:16:52.037 25811 25811 D BreventServer: check and brevent, took 339ms
04-05 09:19:39.912 25811 25811 D BreventServer: check and brevent
04-05 09:19:40.031 25811 25811 D BreventServer: Force stop org.zooper.zwpro(noRecent)
04-05 09:19:40.033 25811 25811 D BreventServer: check again in 274s
04-05 09:19:40.033 25811 25811 D BreventServer: check and brevent, took 120ms
04-05 09:19:40.059 25811 25811 D BreventServer: checking feelgood
04-05 09:19:40.073 25811 25820 D BreventServer: received feelgood
04-05 09:20:43.399 25811 25811 D BreventServer: check and brevent
04-05 09:20:43.725 25811 25811 D BreventServer: check again in 210s
04-05 09:20:43.725 25811 25811 D BreventServer: check and brevent, took 323ms
04-05 09:23:01.219 25811 25811 D BreventServer: check and brevent
04-05 09:23:01.477 25811 25811 D BreventServer: check again in 72s
04-05 09:23:01.477 25811 25811 D BreventServer: check and brevent, took 231ms
04-05 09:23:01.497 25811 25811 D BreventServer: checking feelgood
04-05 09:23:01.503 25811 25820 D BreventServer: received feelgood
04-05 09:23:23.519 25811 25811 I BreventServer: real home tid: 1824
04-05 09:23:26.522 25811 25811 D BreventServer: check and brevent
04-05 09:23:26.687 25811 25811 D BreventServer: check again in 47s
04-05 09:23:26.687 25811 25811 D BreventServer: check and brevent, took 161ms
04-05 09:23:35.900 25811 25811 D BreventServer: check and brevent
04-05 09:23:35.987 25811 25811 D BreventServer: check again in 38s
04-05 09:23:35.987 25811 25811 D BreventServer: check and brevent, took 87ms
04-05 09:23:36.003 25811 25811 D BreventServer: checking feelgood
04-05 09:23:36.003 25811 25820 D BreventServer: received feelgood
04-05 09:24:13.990 25811 25811 D BreventServer: check and brevent
04-05 09:24:14.139 25811 25811 D BreventServer: widgets: {com.oneplus.security, com.google.android.calendar, org.zooper.zwpro}
04-05 09:24:14.139 25811 25811 D BreventServer: running: {com.tencent.mm=39275, me.piebridge.brevent=40137, com.android.incallui=36082, com.google.android.packageinstaller=2744, com.android.settings=40136, com.iflytek.inputmethod.google=40175}
04-05 09:24:14.140 25811 25811 D BreventServer: recent: {me.piebridge.brevent=861, com.android.settings=861}
04-05 09:24:14.181 25811 25811 D BreventServer: inactive for com.tencent.mm: 900, timeout: 300
04-05 09:24:14.181 25811 25811 D BreventServer: inactive for me.piebridge.brevent: 38, timeout: 300
04-05 09:24:14.181 25811 25811 D BreventServer: check later(background) for me.piebridge.brevent: 262
04-05 09:24:14.269 25811 25811 D BreventServer: com.google.android.webview depended by {com.google.android.gms}
04-05 09:24:14.269 25811 25811 D BreventServer: com.google.android.gms depended by {net.oneplus.push}
04-05 09:24:14.270 25811 25811 D BreventServer: service: {}
04-05 09:24:14.270 25811 25811 D BreventServer: back: {}
04-05 09:24:14.270 25811 25811 D BreventServer: blocking: {com.tencent.mm}
04-05 09:24:14.270 25811 25811 D BreventServer: top: {me.piebridge.brevent}
04-05 09:24:14.270 25811 25811 D BreventServer: home: {com.android.systemui, net.oneplus.launcher}
04-05 09:24:14.270 25811 25811 D BreventServer: current: me.piebridge.brevent
04-05 09:24:14.270 25811 25811 D BreventServer: unsafe: {}
04-05 09:24:14.271 25811 25811 D BreventServer: final blocking: {com.tencent.mm}
04-05 09:24:14.271 25811 25811 D BreventServer: notifications: {}
04-05 09:24:14.271 25811 25811 D BreventServer: noRecent: {com.tencent.mm}
04-05 09:24:14.271 25811 25811 D BreventServer: foreground service: {}
04-05 09:24:14.272 25811 25811 D BreventServer: sticky notification: {}
04-05 09:24:14.292 25811 25811 D BreventServer: Force stop com.tencent.mm(noRecent)
04-05 09:24:14.297 25811 25811 D BreventServer: check again in 262s
04-05 09:24:14.297 25811 25811 D BreventServer: check and brevent, took 300ms
04-05 09:24:36.067 25811 25811 D BreventServer: pause activity, tid: 1466, packageName: me.piebridge.brevent
04-05 09:24:38.399 25811 25811 D BreventServer: check and brevent
04-05 09:24:38.556 25811 25811 D BreventServer: widgets: {com.oneplus.security, com.google.android.calendar, org.zooper.zwpro}
04-05 09:24:38.556 25811 25811 D BreventServer: running: {me.piebridge.brevent=40197, com.android.incallui=36081, com.google.android.packageinstaller=2743, com.android.settings=40136, com.iflytek.inputmethod.google=40199}
04-05 09:24:38.557 25811 25811 D BreventServer: recent: {me.piebridge.brevent=898, com.android.settings=837}
04-05 09:24:38.626 25811 25811 D BreventServer: inactive for me.piebridge.brevent: 3, timeout: 300
04-05 09:24:38.627 25811 25811 D BreventServer: check later(background) for me.piebridge.brevent: 297
04-05 09:24:38.719 25811 25811 D BreventServer: com.google.android.webview depended by {com.google.android.gms}
04-05 09:24:38.719 25811 25811 D BreventServer: com.google.android.gms depended by {net.oneplus.push}
04-05 09:24:38.719 25811 25811 D BreventServer: service: {}
04-05 09:24:38.719 25811 25811 D BreventServer: back: {}
04-05 09:24:38.719 25811 25811 D BreventServer: blocking: {}
04-05 09:24:38.719 25811 25811 D BreventServer: top: {me.piebridge.brevent}
04-05 09:24:38.719 25811 25811 D BreventServer: home: {com.android.systemui, net.oneplus.launcher}
04-05 09:24:38.719 25811 25811 D BreventServer: current: me.piebridge.brevent
04-05 09:24:38.719 25811 25811 D BreventServer: unsafe: {}
04-05 09:24:38.719 25811 25811 D BreventServer: final blocking: {}
04-05 09:24:38.719 25811 25811 D BreventServer: notifications: {}
04-05 09:24:38.719 25811 25811 D BreventServer: noRecent: {}
04-05 09:24:38.719 25811 25811 D BreventServer: foreground service: {}
04-05 09:24:38.719 25811 25811 D BreventServer: sticky notification: {}
04-05 09:24:38.719 25811 25811 D BreventServer: check again in 297s
04-05 09:24:38.719 25811 25811 D BreventServer: check and brevent, took 317ms

**Comment by heiyuheiyu** [comment]
上个日志 我不知道 对不对  我又抓了一个  你看一下 
*****************************************************
F:\platform-tools>adb -d shell setprop log.tag.BreventServer DEBUG

F:\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
04-05 08:36:50.476 25811 25811 D BreventServer: check and brevent
04-05 08:36:50.671 25811 25811 D BreventServer: check again in 189s
04-05 08:36:50.671 25811 25811 D BreventServer: check and brevent, took 193ms
04-05 08:37:57.355 25811 25811 D BreventServer: check and brevent
04-05 08:37:57.708 25811 25811 D BreventServer: check again in 122s
04-05 08:37:57.708 25811 25811 D BreventServer: check and brevent, took 350ms
04-05 08:43:31.792 25811 25811 D BreventServer: check and brevent
04-05 08:43:32.159 25811 25811 D BreventServer: Force stop me.piebridge.brevent(noRecent)
04-05 08:43:32.161 25811 25811 D BreventServer: check again in 3600s
04-05 08:43:32.161 25811 25811 D BreventServer: check and brevent, took 365ms
04-05 08:59:00.740 25811 25811 D BreventServer: check and brevent
04-05 08:59:00.866 25811 25811 D BreventServer: Force stop org.zooper.zwpro(noRecent)
04-05 08:59:00.867 25811 25811 D BreventServer: check again in 298s
04-05 08:59:00.867 25811 25811 D BreventServer: check and brevent, took 125ms
04-05 09:09:15.180 25811 25811 D BreventServer: check and brevent
04-05 09:09:15.288 25811 25811 D BreventServer: check again in 299s
04-05 09:09:15.288 25811 25811 D BreventServer: check and brevent, took 107ms
04-05 09:09:15.312 25811 25811 D BreventServer: checking feelgood
04-05 09:09:15.314 25811 25820 D BreventServer: received feelgood
04-05 09:09:20.983 25811 25811 D BreventServer: check and brevent
04-05 09:09:21.113 25811 25811 D BreventServer: check again in 293s
04-05 09:09:21.113 25811 25811 D BreventServer: check and brevent, took 129ms
04-05 09:09:21.152 25811 25811 D BreventServer: checking feelgood
04-05 09:09:21.155 25811 25820 D BreventServer: received feelgood
04-05 09:10:23.499 25811 25811 D BreventServer: check and brevent
04-05 09:10:23.820 25811 25811 D BreventServer: check again in 230s
04-05 09:10:23.820 25811 25811 D BreventServer: check and brevent, took 318ms
04-05 09:12:42.988 25811 25811 D BreventServer: check and brevent
04-05 09:12:43.188 25811 25811 D BreventServer: check again in 91s
04-05 09:12:43.188 25811 25811 D BreventServer: check and brevent, took 180ms
04-05 09:12:43.213 25811 25811 D BreventServer: checking feelgood
04-05 09:12:43.217 25811 25820 D BreventServer: received feelgood
04-05 09:12:48.077 25811 25811 I BreventServer: real home tid: 1824
04-05 09:12:51.082 25811 25811 D BreventServer: check and brevent
04-05 09:12:51.352 25811 25811 D BreventServer: check again in 83s
04-05 09:12:51.353 25811 25811 D BreventServer: check and brevent, took 268ms
04-05 09:13:50.706 25811 25811 D BreventServer: check and brevent
04-05 09:13:51.022 25811 25811 D BreventServer: check again in 23s
04-05 09:13:51.022 25811 25811 D BreventServer: check and brevent, took 313ms
04-05 09:14:11.773 25811 25811 D BreventServer: check and brevent
04-05 09:14:11.963 25811 25811 D BreventServer: check again in 2s
04-05 09:14:11.963 25811 25811 D BreventServer: check and brevent, took 189ms
04-05 09:14:12.022 25811 25811 D BreventServer: checking feelgood
04-05 09:14:12.024 25811 25820 D BreventServer: received feelgood
04-05 09:14:13.969 25811 25811 D BreventServer: check and brevent
04-05 09:14:14.243 25811 25811 D BreventServer: check again in 0s
04-05 09:14:14.243 25811 25811 D BreventServer: check and brevent, took 270ms
04-05 09:14:16.246 25811 25811 D BreventServer: check and brevent
04-05 09:14:16.599 25811 25811 D BreventServer: check again in 296s
04-05 09:14:16.599 25811 25811 D BreventServer: check and brevent, took 351ms
04-05 09:15:17.785 25811 25811 D BreventServer: check and brevent
04-05 09:15:18.135 25811 25811 D BreventServer: check again in 298s
04-05 09:15:18.135 25811 25811 D BreventServer: check and brevent, took 348ms
04-05 09:15:39.950 25811 25811 D BreventServer: check and brevent
04-05 09:15:40.214 25811 25811 D BreventServer: check again in 300s
04-05 09:15:40.214 25811 25811 D BreventServer: check and brevent, took 234ms
04-05 09:15:40.243 25811 25811 D BreventServer: checking feelgood
04-05 09:15:40.245 25811 25820 D BreventServer: received feelgood
04-05 09:16:51.697 25811 25811 D BreventServer: check and brevent
04-05 09:16:52.037 25811 25811 D BreventServer: check again in 298s
04-05 09:16:52.037 25811 25811 D BreventServer: check and brevent, took 339ms
04-05 09:19:39.912 25811 25811 D BreventServer: check and brevent
04-05 09:19:40.031 25811 25811 D BreventServer: Force stop org.zooper.zwpro(noRecent)
04-05 09:19:40.033 25811 25811 D BreventServer: check again in 274s
04-05 09:19:40.033 25811 25811 D BreventServer: check and brevent, took 120ms
04-05 09:19:40.059 25811 25811 D BreventServer: checking feelgood
04-05 09:19:40.073 25811 25820 D BreventServer: received feelgood
04-05 09:20:43.399 25811 25811 D BreventServer: check and brevent
04-05 09:20:43.725 25811 25811 D BreventServer: check again in 210s
04-05 09:20:43.725 25811 25811 D BreventServer: check and brevent, took 323ms
04-05 09:23:01.219 25811 25811 D BreventServer: check and brevent
04-05 09:23:01.477 25811 25811 D BreventServer: check again in 72s
04-05 09:23:01.477 25811 25811 D BreventServer: check and brevent, took 231ms
04-05 09:23:01.497 25811 25811 D BreventServer: checking feelgood
04-05 09:23:01.503 25811 25820 D BreventServer: received feelgood
04-05 09:23:23.519 25811 25811 I BreventServer: real home tid: 1824
04-05 09:23:26.522 25811 25811 D BreventServer: check and brevent
04-05 09:23:26.687 25811 25811 D BreventServer: check again in 47s
04-05 09:23:26.687 25811 25811 D BreventServer: check and brevent, took 161ms
04-05 09:23:35.900 25811 25811 D BreventServer: check and brevent
04-05 09:23:35.987 25811 25811 D BreventServer: check again in 38s
04-05 09:23:35.987 25811 25811 D BreventServer: check and brevent, took 87ms
04-05 09:23:36.003 25811 25811 D BreventServer: checking feelgood
04-05 09:23:36.003 25811 25820 D BreventServer: received feelgood
04-05 09:24:13.990 25811 25811 D BreventServer: check and brevent
04-05 09:24:14.139 25811 25811 D BreventServer: widgets: {com.oneplus.security, com.google.android.calendar, org.zooper.zwpro}
04-05 09:24:14.139 25811 25811 D BreventServer: running: {com.tencent.mm=39275, me.piebridge.brevent=40137, com.android.incallui=36082, com.google.android.packageinstaller=2744, com.android.settings=40136, com.iflytek.inputmethod.google=40175}
04-05 09:24:14.140 25811 25811 D BreventServer: recent: {me.piebridge.brevent=861, com.android.settings=861}
04-05 09:24:14.181 25811 25811 D BreventServer: inactive for com.tencent.mm: 900, timeout: 300
04-05 09:24:14.181 25811 25811 D BreventServer: inactive for me.piebridge.brevent: 38, timeout: 300
04-05 09:24:14.181 25811 25811 D BreventServer: check later(background) for me.piebridge.brevent: 262
04-05 09:24:14.269 25811 25811 D BreventServer: com.google.android.webview depended by {com.google.android.gms}
04-05 09:24:14.269 25811 25811 D BreventServer: com.google.android.gms depended by {net.oneplus.push}
04-05 09:24:14.270 25811 25811 D BreventServer: service: {}
04-05 09:24:14.270 25811 25811 D BreventServer: back: {}
04-05 09:24:14.270 25811 25811 D BreventServer: blocking: {com.tencent.mm}
04-05 09:24:14.270 25811 25811 D BreventServer: top: {me.piebridge.brevent}
04-05 09:24:14.270 25811 25811 D BreventServer: home: {com.android.systemui, net.oneplus.launcher}
04-05 09:24:14.270 25811 25811 D BreventServer: current: me.piebridge.brevent
04-05 09:24:14.270 25811 25811 D BreventServer: unsafe: {}
04-05 09:24:14.271 25811 25811 D BreventServer: final blocking: {com.tencent.mm}
04-05 09:24:14.271 25811 25811 D BreventServer: notifications: {}
04-05 09:24:14.271 25811 25811 D BreventServer: noRecent: {com.tencent.mm}
04-05 09:24:14.271 25811 25811 D BreventServer: foreground service: {}
04-05 09:24:14.272 25811 25811 D BreventServer: sticky notification: {}
04-05 09:24:14.292 25811 25811 D BreventServer: Force stop com.tencent.mm(noRecent)
04-05 09:24:14.297 25811 25811 D BreventServer: check again in 262s
04-05 09:24:14.297 25811 25811 D BreventServer: check and brevent, took 300ms
04-05 09:24:36.067 25811 25811 D BreventServer: pause activity, tid: 1466, packageName: me.piebridge.brevent
04-05 09:24:38.399 25811 25811 D BreventServer: check and brevent
04-05 09:24:38.556 25811 25811 D BreventServer: widgets: {com.oneplus.security, com.google.android.calendar, org.zooper.zwpro}
04-05 09:24:38.556 25811 25811 D BreventServer: running: {me.piebridge.brevent=40197, com.android.incallui=36081, com.google.android.packageinstaller=2743, com.android.settings=40136, com.iflytek.inputmethod.google=40199}
04-05 09:24:38.557 25811 25811 D BreventServer: recent: {me.piebridge.brevent=898, com.android.settings=837}
04-05 09:24:38.626 25811 25811 D BreventServer: inactive for me.piebridge.brevent: 3, timeout: 300
04-05 09:24:38.627 25811 25811 D BreventServer: check later(background) for me.piebridge.brevent: 297
04-05 09:24:38.719 25811 25811 D BreventServer: com.google.android.webview depended by {com.google.android.gms}
04-05 09:24:38.719 25811 25811 D BreventServer: com.google.android.gms depended by {net.oneplus.push}
04-05 09:24:38.719 25811 25811 D BreventServer: service: {}
04-05 09:24:38.719 25811 25811 D BreventServer: back: {}
04-05 09:24:38.719 25811 25811 D BreventServer: blocking: {}
04-05 09:24:38.719 25811 25811 D BreventServer: top: {me.piebridge.brevent}
04-05 09:24:38.719 25811 25811 D BreventServer: home: {com.android.systemui, net.oneplus.launcher}
04-05 09:24:38.719 25811 25811 D BreventServer: current: me.piebridge.brevent
04-05 09:24:38.719 25811 25811 D BreventServer: unsafe: {}
04-05 09:24:38.719 25811 25811 D BreventServer: final blocking: {}
04-05 09:24:38.719 25811 25811 D BreventServer: notifications: {}
04-05 09:24:38.719 25811 25811 D BreventServer: noRecent: {}
04-05 09:24:38.719 25811 25811 D BreventServer: foreground service: {}
04-05 09:24:38.719 25811 25811 D BreventServer: sticky notification: {}
04-05 09:24:38.719 25811 25811 D BreventServer: check again in 297s
04-05 09:24:38.719 25811 25811 D BreventServer: check and brevent, took 317ms
04-05 09:26:33.890 25811 25811 D BreventServer: check and brevent
04-05 09:26:33.995 25811 25811 D BreventServer: widgets: {com.oneplus.security, com.google.android.calendar, org.zooper.zwpro}
04-05 09:26:33.995 25811 25811 D BreventServer: running: {me.piebridge.brevent=40315, com.android.incallui=36082, com.google.android.packageinstaller=2744, com.android.settings=40137, com.iflytek.inputmethod.google=40315}
04-05 09:26:33.995 25811 25811 D BreventServer: recent: {me.piebridge.brevent=900, com.android.settings=722}
04-05 09:26:34.036 25811 25811 D BreventServer: inactive for me.piebridge.brevent: 0, timeout: 300
04-05 09:26:34.036 25811 25811 D BreventServer: check later(background) for me.piebridge.brevent: 300
04-05 09:26:34.108 25811 25811 D BreventServer: com.google.android.webview depended by {com.google.android.gms}
04-05 09:26:34.108 25811 25811 D BreventServer: com.google.android.gms depended by {net.oneplus.push}
04-05 09:26:34.108 25811 25811 D BreventServer: service: {}
04-05 09:26:34.108 25811 25811 D BreventServer: back: {}
04-05 09:26:34.108 25811 25811 D BreventServer: blocking: {}
04-05 09:26:34.108 25811 25811 D BreventServer: top: {me.piebridge.brevent}
04-05 09:26:34.108 25811 25811 D BreventServer: home: {com.android.systemui, net.oneplus.launcher}
04-05 09:26:34.108 25811 25811 D BreventServer: current: me.piebridge.brevent
04-05 09:26:34.108 25811 25811 D BreventServer: unsafe: {}
04-05 09:26:34.108 25811 25811 D BreventServer: final blocking: {}
04-05 09:26:34.108 25811 25811 D BreventServer: notifications: {}
04-05 09:26:34.108 25811 25811 D BreventServer: noRecent: {}
04-05 09:26:34.108 25811 25811 D BreventServer: foreground service: {}
04-05 09:26:34.108 25811 25811 D BreventServer: sticky notification: {}
04-05 09:26:34.108 25811 25811 D BreventServer: check again in 300s
04-05 09:26:34.108 25811 25811 D BreventServer: check and brevent, took 184ms
04-05 09:26:34.140 25811 25811 D BreventServer: checking feelgood
04-05 09:26:34.142 25811 25820 D BreventServer: received feelgood
04-05 09:26:34.144 25811 25811 D BreventServer: resume activity, packageName: me.piebridge.brevent, launcher: net.oneplus.launcher, paused: me.piebridge.brevent, pressed home: false

**Comment by liudongmiao** [comment]
1. 辅助应用是你自己加的，可能你自己都不记得了；也有可能是你的 ROM 默认给你加好的。
你可以去系统设置里去掉，或者换用别的应用。

当然，也可能你只有一个辅助应用，然后我就默认它为辅助应用。
接下来，我会把这个默认给去掉。电话必须要默认一个，但辅助应用可以不必默认。

2. 并不能黑域辅助应用，如果你更要处理，后果不可知。

**Comment by heiyuheiyu** [comment]
没有，上个0.9.5 还是正常的 因为我经常用uc 记得很清楚。 我就是升级了 黑域后 才发现它变为辅助应用了。

**Comment by heiyuheiyu** [comment]
刚才 我已经在设置里面 取消了 uc的 辅助应用  现在辅助应用为“无”。  可是 黑域里 仍然显示 uc为 “辅助应用” 无法选择 加入黑域列表

**Comment by liudongmiao** [comment]
只有两个的话，确实会这样。我晚上会处理它。
你再装个别的带辅助应用的，如绿色守护，Firefox等。

**Comment by liudongmiao** [comment]
你现在可以使用 0.9.6，不要使用最新测试版。0.9.6 应该没这个问题。

**Comment by heiyuheiyu** [comment]
ok 呵呵  不好意思  老是比较低级别的问题

**Comment by liudongmiao** [comment]
真的没有。非常感谢你测这个问题。

请发个邮件给我，我给你一枚特别贡献。

**Comment by WanderMax** [comment]
@liudongmiao debug日志必须用adb工具导出么？

**Comment by liudongmiao** [comment]
是的，如果你有 root，寻求其它工具。

**Comment by heiyuheiyu** [comment]
@liudongmiao 呵呵 不客气。作为开发者 你比较辛苦。 您邮箱是多少 ？不知道您邮箱。 我的是 frank933@126.com
**********************************************************************
另外说句题外话，希望您别介意。其实除了 酷安上 一些伸手党 非常不可理喻，只按自己需求来，要求这，要求那，不顾你作为开发者的思路 初衷。这种人你可以不加理会，更没必要生气，你按自己的思路 做你的开发就好了。某些有价值的，你可以选择性的回复。其余权当听不见。（有点像 黄章 在魅族论坛的做法,呵呵（头几年他也会被一些激进回复左右情绪） )  
其余更多的矛盾，我觉得  是因为 表达 双方不能领会所致。 您是那种做技术开发的，技术水平高，很多问题 你的表达方式都比较专业，或者你按照自己的思路表达了，或者 有些您压根认为 没必要细说，简单几个字 就表达的很明白了。 可是作为 用户 不太懂技术的，理解不了你话语的表达方式，他认为不明白，觉得你不负责，你开发的东西乱。矛盾 误解 就产生了。 呵呵 
像我这样 不太懂技术的。到现在 抓取日志 也不知道抓的对不对的 可是这种人。哈哈。
但是好在我 比较耐心，能描述的详细一些。
您更 耐心 愿意读完我的回复， 能从我不专业的表述中，发现问题。

所以我觉得 对待这类不太懂技术的人 在酷安上的回复，您更没必要生气， 有时间就讲讲，没时间就算了。 按你的思路  做开发就好，理解不了的 就算了。实在觉得自己 表达不好的 ，找人帮你翻译成大众化语言。 总之 千万别 赌气，没有用 更没那个必要。
一点 感受。 说的不对 别介意。 希望你越做越好！

**Comment by liudongmiao** [comment]
不要在公开场合透露你私人邮箱，建议修改答案。

**Comment by heiyuheiyu** [comment]
修改了  多谢提醒
