### ISSUE TITLE
QQ以不同方式打开后back后反应不一致

### ISSUE THREAD

**Issue by CVN-77** [liudongmiao/Brevent#376]
（以下QQ和UC均开启允许同步）
1.在启动器打开QQ后back，QQ被立即强行停止，触发优化非正常返回功能：

C:\ADB>adb -d logcat -d -b main -s BreventServer BreventLoader
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
04-05 10:45:09.495 11571 11571 D BreventServer: Can't setStopped for com.tencent
.android.qqdownloader(ignore)
04-05 10:45:09.499 11571 11571 D BreventServer: Can't setStopped for com.tencent
.android.qqdownloader(ignore)
04-05 10:45:14.853 11571 11571 D BreventServer: check and brevent
04-05 10:45:15.105 11571 11571 W BreventServer: com.tencent.mobileqq has foregro
und service, but without notification
04-05 10:45:15.182 11571 11571 D BreventServer: Force stop com.tencent.android.q
qdownloader(service)
04-05 10:45:15.222 11571 11571 D BreventServer: check and brevent, took 368ms
04-05 10:45:15.293 11571 11571 D BreventServer: checking feelgood
04-05 10:45:15.294 11571 11580 D BreventServer: received feelgood
04-05 10:46:04.194 11571 11571 D BreventServer: check and brevent
04-05 10:46:04.311 11571 11571 W BreventServer: com.tencent.mobileqq has foregro
und service, but without notification
04-05 10:46:04.313 11571 11571 D BreventServer: Can't setStopped for com.tencent
.mobileqq(ignore)
04-05 10:46:04.313 11571 11571 D BreventServer: check and brevent, took 118ms
04-05 10:46:04.349 11571 11571 D BreventServer: checking feelgood
04-05 10:46:04.349 11571 11580 D BreventServer: received feelgood

2.在黑域里的列表打开QQ后back，则跟home的反应差不多，进入计时然后待机，似乎并没有触发优化非正常返回功能：

C:\ADB>adb -d logcat -d -b main -s BreventServer BreventLoader
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
04-05 10:48:52.545 15144 15144 D BreventServer: check and brevent
04-05 10:48:52.803 15144 15144 D BreventServer: Force stop com.tencent.android.q
qdownloader(service)
04-05 10:48:52.811 15144 15144 D BreventServer: check and brevent, took 266ms
04-05 10:48:52.813 15144 15144 D BreventServer: Can't setStopped for com.tencent
.mobileqq(ignore)
04-05 10:49:09.871 15144 15144 D BreventServer: Can't setStopped for com.tencent
.mobileqq(ignore)
04-05 10:49:10.380 15144 15144 D BreventServer: Can't setStopped for com.tencent
.mobileqq(ignore)
04-05 10:49:14.737 15144 15144 D BreventServer: check and brevent
04-05 10:49:15.033 15144 15144 W BreventServer: com.tencent.mobileqq has foregro
und service, but without notification
04-05 10:49:15.126 15144 15144 D BreventServer: Force stop com.tencent.mobileqq(
mock sticky notification)
04-05 10:49:15.131 15144 15144 D BreventServer: check and brevent, took 393ms
04-05 10:49:20.317 15144 15144 D BreventServer: check and brevent
04-05 10:49:20.443 15144 15144 D BreventServer: check and brevent, took 125ms
04-05 10:49:20.462 15144 15144 D BreventServer: checking feelgood
04-05 10:49:20.462 15144 15153 D BreventServer: received feelgood

ps：以UC做参考，无论是在启动器或者黑域列表里打开UC然后退出，都是30s后强行停止（期间在正在运行列表里无计时），反应一致：

C:\ADB>adb -d logcat -d -b main -s BreventServer BreventLoader
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
04-05 10:58:06.410 23576 23576 D BreventServer: com.UCMobile: priority
04-05 10:58:07.657 23576 23576 D BreventServer: com.UCMobile: priority
04-05 10:58:08.960 23576 23576 D BreventServer: check and brevent
04-05 10:58:09.157 23576 23576 D BreventServer: ignore com.UCMobile, wait for th
e service check
04-05 10:58:09.157 23576 23576 D BreventServer: check and brevent, took 196ms
04-05 10:58:42.161 23576 23576 D BreventServer: check and brevent
04-05 10:58:42.494 23576 23576 D BreventServer: Force stop com.UCMobile(priority
 service)
04-05 10:58:42.498 23576 23576 D BreventServer: check and brevent, took 335ms
04-05 10:59:33.183 23576 23576 D BreventServer: check and brevent
04-05 10:59:33.286 23576 23576 D BreventServer: Can't setStopped for com.UCMobil
e(ignore)
04-05 10:59:33.286 23576 23576 D BreventServer: check and brevent, took 102ms
04-05 10:59:33.310 23576 23576 D BreventServer: checking feelgood
04-05 10:59:33.311 23576 23611 D BreventServer: received feelgood

C:\ADB>

**Comment by liudongmiao** [comment]
终于被发现了，哈哈。

这是非正常 Back 的第一个变种，总体上来说，它使用的是标准的 API。
链接见此：https://developer.android.google.cn/reference/android/app/Activity.html#moveTaskToBack(boolean)

另外两个变种，是直接以某种方式启动启动器，有一个还非常恶劣。

对于这第一个变种，一是比较友好，二是要真正识别，只能支持 7.0 与 7.1。
所以，权衡之后，我采取变通方法，只监控一件事。
当一个应用回到桌面时，是否按 Home 键。这样就简单很多。

但是，像你说的这种，就比较难以处理。
但考虑到绝大部分应用，都是主屏幕上打开，然后 Back。
所以总体来说影响比较小。整个过程，重点要防的是其它两类。

所以，为了兼容性，以及尽力处理绝大部分情况，偷懒处理了。

**Comment by liudongmiao** [comment]
另外，你机器上应该是不支持 FCM 的吧。因为我看到这个日志了

> 04-05 10:46:04.313 11571 11571 D BreventServer: Can't setStopped for com.tencent
.mobileqq(ignore)

**Comment by heiyuheiyu** [comment]
我的跟你的有点不一样  1.在启动器打开QQ后back，QQ被**立即进入待机** ，触发优化非正常返回功能。
2.在黑域里的列表打开QQ后back，和 home的反应差不多，进入计时，然后待机。 这个跟你一样。
（我用0.9.6， 没有开启它的允许同步）

**Comment by CVN-77** [comment]
原来是这样，有些明白了，看来是back后要回到桌面的才能立即按优化非正常返回处理，如果不是则按home的处理。

**Comment by CVN-77** [comment]
至于我的机器是否支持FCM我也没搞懂，以前微信试过待机后能推送，因为网不稳就不搞了，不过我这QQ的确是没FCM推送，让QQ待机后，总提示网络连接无效，然后就一直没接收信息。

**Comment by liudongmiao** [comment]
非正常返回的这种情况，难以处理。

A 应用 回到 B 应用，此时 A 应用，应该是要结束的。但是，其实是有反例的。

A 应用里，阅读通知或者从最近列表，跳到 B 应用。此时，A 应用放到后台，B 应用。

所以，直接不处理比较好。处理了，反而是负优化。因为这确实不是正常使用场景。

**Comment by liudongmiao** [comment]
@CVN-77 你机器不支持设置停止状态，所以很多待机可以有的优化，实现不了。
同时，一旦停止，也无法接收广播。

**Comment by CVN-77** [comment]
关于“不支持设置停止状态”，作者能详细解析一下吗？我目前也是有些疑惑，我这里安卓6.0，待机支持的，黑域模式里的“只强行停止”应该也是支持（酷安back后进程就没了），不过已待机的应用在黑屏很久后再打开，发现还是待机没有停止，还有已待机的应用亮屏下似乎也是很久都没停止（待机超时设置15分钟），这些是否属于不支持设置强行停止？不支持设置强行停止是否也就无法支持FCM？能单独待机或强行停止，但不能待机后停止，不知道是安卓系统版本还是EMUI的问题…

**Comment by liudongmiao** [comment]
> 04-05 10:49:10.380 15144 15144 D BreventServer: Can't setStopped for com.tencent
.mobileqq(ignore)

比如说，你找个支持 FCM 的应用，然后触发黑域强行停止它。结束以后，你去详情里看，那个”强行停止“还可不可以点。正常是可以点的。
