### ISSUE TITLE
酷安上 使用方法 是您写的吗？好像有个地方不对。

### ISSUE THREAD

**Issue by heiyuheiyu** [liudongmiao/Brevent#378]
[使用方法] 中
5. (电脑) 电脑命令行中执行黑域提示中的"adb -d shell sh /sdcard/Android/me.piebridge.brevent/brevent.sh"，不出意外，到此就成功了

Android 后面 少个 /data/  吧？ 我加上 data 才打开启动黑域的。 按您写的 打不开 提示找不到文件。
赶紧改了 要不然 很多 小白 又该乱叫了~~

**Comment by liudongmiao** [comment]
酷安上的版本不由我维护。早上已经 @ 小编修改，他没更我。

Play 上是正确的就成～
