### ISSUE TITLE
0.96版在lg g5上不能正常adb

### ISSUE THREAD

**Issue by ltkun** [liudongmiao/Brevent#380]
第一次可以正常adb 重启以后黑域失效 不能再次adb 显示
sh: /sdcard/Android/me.piebridge.brevent/brevent.sh: No such file or directory

第一次也是同华为p10p一样 缺右上角的加入黑域按钮

**Comment by ltkun** [comment]
好吧 等了几分钟竟然又可以了 但是重启难道会失效？

**Comment by liudongmiao** [comment]
使用 `/sdcard/Android/data/me.piebridge.brevent/brevent.sh`

酷安详情是错的，请以 Play 及界面提示为准。

**Comment by ltkun** [comment]
完成adb后 进入黑域 选择app后 右上角也没有显示加入黑域……
不会这么巧 我两个手机都不行吧

**Comment by ltkun** [comment]
没注意哈 可是不显示按钮这个bug 怎么搞……

**Comment by liudongmiao** [comment]
我不维护酷安，Brevent 帐号已经离走了。

**Comment by ltkun** [comment]
是进去黑域了 可是选中app以后 右上角没有加入黑域的按钮 
截图在这里
https://goo.gl/photos/k15UiQuFQrhR3i9w9

**Comment by liudongmiao** [comment]
你的图里有”加入黑域“的按钮啊。不就出现了两个么，一个不再黑域，一个加入黑域。
