### ISSUE TITLE
DELAY

### ISSUE THREAD

**Issue by XiaoyuJiao** [liudongmiao/Brevent#381]
04-05 14:54:11.691  5016  5016 D BreventServer: checking feelgood
04-05 14:54:11.700  5016  5025 D BreventServer: received feelgood
04-05 14:54:13.695  5016  5016 D BreventServer: checking feelgood
04-05 14:54:13.696  5016  5025 D BreventServer: received feelgood
04-05 14:54:16.324  5016  5016 D BreventServer: checking feelgood
04-05 14:54:16.325  5016  5025 D BreventServer: received feelgood
04-05 14:54:20.123  5016  5016 D BreventServer: checking feelgood
04-05 14:54:20.123  5016  5025 D BreventServer: received feelgood
04-05 14:54:33.504  5016  5016 D BreventServer: checking feelgood
04-05 14:54:33.506  5016  5025 D BreventServer: received feelgood
04-05 14:54:42.563  5016  5016 D BreventServer: checking feelgood
04-05 14:54:42.564  5016  5025 D BreventServer: received feelgood
04-05 14:54:47.732  5016  5016 D BreventServer: checking feelgood
04-05 14:54:47.733  5016  5025 D BreventServer: received feelgood
04-05 14:55:40.478  5016  5016 D BreventServer: check and brevent
04-05 14:55:40.764  5016  5016 D BreventServer: Force stop com.sankuai.meituan(noRecent)
04-05 14:55:40.780  5016  5016 D BreventServer: Force stop com.coolapk.market(noRecent)
04-05 14:55:40.786  5016  5016 D BreventServer: check and brevent, took 304ms
04-05 14:56:11.473  5016  5016 D BreventServer: checking feelgood
04-05 14:56:11.474  5016  5025 D BreventServer: received feelgood
04-05 14:56:22.927  5016  5016 D BreventServer: checking feelgood
04-05 14:56:22.928  5016  5025 D BreventServer: received feelgood
04-05 14:56:32.708  5016  5016 D BreventServer: checking feelgood
04-05 14:56:32.708  5016  5025 D BreventServer: received feelgood
04-05 14:56:38.458  5016  5016 D BreventServer: checking feelgood
04-05 14:56:38.460  5016  5025 D BreventServer: received feelgood
04-05 14:57:32.346  5016  5016 D BreventServer: checking feelgood
04-05 14:57:32.347  5016  5025 D BreventServer: received feelgood
04-05 14:57:39.413  5016  5016 D BreventServer: checking feelgood
04-05 14:57:39.415  5016  5025 D BreventServer: received feelgood
04-05 14:57:49.428  5016  5016 D BreventServer: checking feelgood
04-05 14:57:49.429  5016  5025 D BreventServer: received feelgood
04-05 14:58:11.809  5016  5016 D BreventServer: checking feelgood
04-05 14:58:11.810  5016  5025 D BreventServer: received feelgood
04-05 14:59:21.304  5016  5016 D BreventServer: checking feelgood
04-05 14:59:21.318  5016  5025 D BreventServer: received feelgood
04-05 14:59:23.292  5016  5016 D BreventServer: checking feelgood
04-05 14:59:23.293  5016  5025 D BreventServer: received feelgood
04-05 14:59:45.784  5016  5016 D BreventServer: checking feelgood
04-05 14:59:45.785  5016  5025 D BreventServer: received feelgood
04-05 15:00:40.801  5016  5016 D BreventServer: check and brevent
04-05 15:00:41.044  5016  5016 D BreventServer: Force stop com.coolapk.market(noRecent)
04-05 15:00:41.048  5016  5016 D BreventServer: check and brevent, took 244ms
04-05 15:01:45.452  5016  5016 D BreventServer: checking feelgood
04-05 15:01:45.457  5016  5025 D BreventServer: received feelgood
04-05 15:01:48.493  5016  5016 D BreventServer: checking feelgood
04-05 15:01:48.494  5016  5025 D BreventServer: received feelgood
EDIT:I opened coolapk and closed it from the nearest task list at about 14:58,but it was force stopped 2 minutes later.There was an obvious delay.So was other apps.Using gemini with lineageOS 20170328.

**Comment by liudongmiao** [comment]
It seems that you didn't install the latest version.
Please update to latest 0.9.6, or the latest snapshot: 0.9.6+X.

For stable: https://piebridge.me/br/
For next: https://piebridge.me/br/next/

I didn't offer support for old version.

**Comment by XiaoyuJiao** [comment]
Ok,I'll try.Thx.（中国人特地来看望柳大[手动滑稽])

2017年4月5日 下午3:35，"Liu DongMiao" <notifications@github.com>写道：

**Comment by XiaoyuJiao** [comment]
谢谢，解决了😀

2017年4月5日 下午4:11，"焦小宇" <xiaoyujiao3@gmail.com>写道：
