### ISSUE TITLE
机器:三星Note5未ROOT；描述:0.9.6版本12小时后adb失效，更新0.9.6-5-gc96eb46版本后还是12小时后失效

### ISSUE THREAD

**Issue by ROCKHEARTWINE** [liudongmiao/Brevent#385]
0.9.6版本失效后重新adb日志
F:\platform-tools-latest-windows\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoder
04-04 18:20:43.739 26081 26081 D BreventServer: check and brevent
04-04 18:20:44.029 26081 26081 D BreventServer: Force stop com.samsung.android.themestore(forceStop)
04-04 18:20:44.049 26081 26081 D BreventServer: Force stop com.sec.android.app.samsungapps(forceStop)
04-04 18:20:44.079 26081 26081 D BreventServer: Force stop com.samsung.android.spay(forceStop)
04-04 18:20:44.079 26081 26081 D BreventServer: check again in 3541s
04-04 18:20:44.079 26081 26081 D BreventServer: check and brevent, took 331ms

F:\platform-tools-latest-windows\platform-tools>

0.9.6-5-gc96eb46版本失效后重新adb日志
F:\platform-tools-latest-windows\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
04-05 22:40:33.731 19658 19658 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-05 22:40:34.271 19668 19668 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]
04-05 22:40:34.271 19668 19668 I BreventServer: Brevent Server 0.9.6-5-gc96eb46 started
04-05 22:40:34.281 19668 19668 I BreventServer: brevent user: 0, uid: 2000
04-05 22:40:34.281 19668 19668 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-05 22:40:34.421 19668 19668 I BreventServer: loading brevent list
04-05 22:40:34.421 19668 19668 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 33
04-05 22:40:34.421 19668 19668 I BreventServer: loading brevent conf
04-05 22:40:34.451 19668 19668 D BreventServer: check and brevent
04-05 22:40:34.571 19668 19668 I BreventServer: android process: android.process.acore, packages: [com.android.providers.userdictionary, com.android.providers.contacts]
04-05 22:40:34.581 19668 19668 I BreventServer: android process: android.process.media, packages: [com.android.providers.media, com.android.providers.downloads]
04-05 22:40:34.681 19668 19668 D BreventServer: Force stop com.supercell.boombeach.BD(forceStop)
04-05 22:40:34.691 19668 19668 D BreventServer: check and brevent, took 242ms
04-05 22:40:34.691 19668 19668 D BreventServer: check and brevent
04-05 22:40:34.911 19668 19668 D BreventServer: check and brevent, took 206ms
04-05 22:40:34.971 19668 19668 D BreventServer: sent first status
04-05 22:40:37.971 19668 19668 D BreventServer: check and brevent
04-05 22:40:38.301 19668 19668 D BreventServer: check again in 3600s
04-05 22:40:38.301 19668 19668 D BreventServer: check and brevent, took 328ms
04-05 22:42:11.711 19668 19668 D BreventServer: check and brevent
04-05 22:42:12.041 19668 19668 D BreventServer: check again in 3600s
04-05 22:42:12.041 19668 19668 D BreventServer: check and brevent, took 337ms

F:\platform-tools-latest-windows\platform-tools>

**Comment by liudongmiao** [comment]
失效后立即给日志。这些日志都看不到原因。

**Comment by ROCKHEARTWINE** [comment]
更新1.0后接近两天失效，失效后不adb能直接获得日志吗？

**Comment by liudongmiao** [comment]
可用，这个就是为了获取相关日志。

但我估计你更要 adb logcat -b crash

**Comment by ROCKHEARTWINE** [comment]
新版本失效了
F:\platform-tools-latest-windows\platform-tools>adb logcat -b crash
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
Unable to open log device 'crash'

F:\platform-tools-latest-windows\platform-tools>adb -d logcat -b main -d -s BreventLoader BreventServer

F:\platform-tools-latest-windows\platform-tools>adb devices
List of devices attached
0815f8196c311602        device


F:\platform-tools-latest-windows\platform-tools>adb -d logcat -b main -d -s BreventLoader BreventServer

F:\platform-tools-latest-windows\platform-tools>adb logcat -b crash
Unable to open log device 'crash'

F:\platform-tools-latest-windows\platform-tools>adb logcat -b crash
Unable to open log device 'crash'

F:\platform-tools-latest-windows\platform-tools>adb -d logcat -b main -d -s BreventLoader BreventServer

F:\platform-tools-latest-windows\platform-tools>adb logcat -b crash
Unable to open log device 'crash'

F:\platform-tools-latest-windows\platform-tools>
重新ADB就能查看日志，没有ADB就这样了
