### ISSUE TITLE
某些应该一后台就会立即强杀

### ISSUE THREAD

**Issue by HoiFung** [liudongmiao/Brevent#387]
用QQ，网易云音乐等应用，一后台就马上被杀掉了，这是我在用索尼官方Rom才这样，貌似用原生就没有这样的问题

**Comment by HoiFung** [comment]
打错字,是某些应用

**Comment by liudongmiao** [comment]
可能他们利用了 7.0 及以下前台服务没有通知的漏洞。
请不要黑域，或者为他们单独设置允许同步。

**Comment by HoiFung** [comment]
1.0新版在黑域里设置了允许同步还会这样，但是上一个版本网易云音乐一按后台不会强杀，开了允许同步。

**Comment by liudongmiao** [comment]
可能他们利用了 7.0 下的漏洞。

这块有特殊处理，但我也不记得了。

发现不能处理，就直接不要黑域了吧。

此外，一定不要关闭他们的通知。或者你直接关闭“检查通知”。

**Comment by liudongmiao** [comment]
不管什么原因，请参考商店详情底部日志获取方式，带上日志。
