### ISSUE TITLE
华为荣耀7提示grep: can't execute: Permission denied 版本1.0

### ISSUE THREAD

**Issue by Picking-github** [liudongmiao/Brevent#388]
错误提示如下，在比较早期版本要直接加载so的那会儿还好用，后来从某个版本改成运行脚本后就提示这个了。请问这个应该如何处理？

Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

c:\Program Files 2\platform-tools>adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
/sdcard/Android/data/me.piebridge.brevent/brevent.sh[5]: grep: can't execute: Permission denied
please install me.piebridge.brevent

c:\Program Files 2\platform-tools>

**Comment by liudongmiao** [comment]
你系统里居然连 grep 都没安装？

那你直接找找那个命令吧，和你系统相关。就是你之前用的那个 so 的路径。
这个脚本只是为了更好的去找这个指令。
