### ISSUE TITLE
使用带手势的悬浮窗与优化非正常返回功能有冲突

### ISSUE THREAD

**Issue by CVN-77** [liudongmiao/Brevent#389]
1.0版也试过了，悬浮窗支持返回back、回到主页home等手势操作，这些手势需相关辅助功能开启才能生效。黑域打开优化非正常返回。

1、如果在adb启动黑域服务前未开启悬浮窗辅助功能，那么黑域服务启动完后，只要开启悬浮窗的辅助功能开始使用悬浮窗，就会有如下表现：
打开某个软件如酷安后，如果没有立即使用悬浮窗自己的home，仍是点系统自带的home时，酷安能正常挂到后台计时待机，但是在酷安界面一旦用了悬浮窗的home回到主页，酷安就会立即待机。这之后要在酷安下连用两次系统自带的home，home后才是计时待机，而用悬浮窗的home，无论如何都是home立即待机。
把悬浮窗辅助功能关闭或者把优化非正常返回关闭，在酷安界面下home，酷安则恢复正常计时，到时间才待机。

2、另一种情况，在adb开启黑域服务前已打开悬浮窗辅助功能使用悬浮窗，那么开启黑域服务后，在酷安下第一次用悬浮窗的home是正常计时待机的，再回到酷安第二次用悬浮窗的home，酷安就立即待机了。
此后只有使用系统自带的home才能正常，有时在界面下第一次用系统home还是立即待机，则要返回界面第二次用系统home，则恢复计时待机（即连用两次）。或者将优化非正常返回关闭，那么不管怎么home都能正常计时待机。

总结：打开黑域的优化非正常返回功能下，使用带手势操作的悬浮窗的home，就会令黑域识别home出现问题，本来正常计时再处理变成如同back一般的立即处理，这时只有用系统自带的home才表现正常（不正常则连用两次）。如果关闭这个功能，则两种home都反应正常。这个功能可能依赖系统的home，也就是描述里“真正的主页”，不知可否再优化与悬浮窗的home兼容？

**Comment by liudongmiao** [comment]
说的主页，就是真正的主页。我个人还觉得，他们的原理，真是利用了非正常”返回“呢。

**Comment by CVN-77** [comment]
可能和QQ 微博那些非正常返回是不同的吧，它们还是得用到辅助功能才能实现手势操作。

不过我也试过使用一些悬浮窗操作home黑域也能正常处理的，就是按钮救星免root版和手机自带的悬浮按钮，他们的共同点都是悬浮窗不是直接手势操作，需要点一下展开面板，然后再点按按钮实现back、home等，区别就是按钮救星免root版需要开启辅助功能，系统自带的不用。

**Comment by liudongmiao** [comment]
你其它软件，再牛，能发出系统的 HOME 事件，也真是牛。
所以，只有 ROOT 或者系统层的应用能做到。

**Comment by CVN-77** [comment]
刚刚试了好几款模拟按键的悬浮窗类软件，都在未root下通过辅助功能实现。
发现凡是有通过悬浮图标的手势直接实现按键操作的，其模拟的home黑域应该都按back处理了（不管模拟的home是否在二级菜单）。
而其他一类悬浮窗软件没有手势直接操作，只能通过悬浮图标展开二级菜单，比如Zone悬浮球（酷安有），按钮救星免root版（这个小众），用其二级菜单的home，黑域都以系统的home处理。
<上边写的有个例外，就是fooview，这个悬浮软件比较特殊，也是直接手势操作，但它的home也能让黑域以系统的home正常处理。>

或许这些只能通过二级菜单来模拟home的（还有个例外的fooview）是真的牛…未root下通过辅助功能实现，能让黑域认为是系统的home…目前看来我要换个别的悬浮软件了。

**Comment by CVN-77** [comment]
搞这个反馈真多亏了UC能够自动记忆内容，由于黑域了UC，又试用好几款悬浮软件，一不小心用了手势操作的悬浮球的home，黑域就会强杀UC，还好回到UC能重新加载网页，回复框的内容也保留，要不重打一遍就惨了…

**Comment by ydj73** [comment]
你有没有试过LMT，开启辅助功能，貌似HOME正常。
