### ISSUE TITLE
能否增加一个定时清理功能

### ISSUE THREAD

**Issue by xcjiang** [liudongmiao/Brevent#39]
有时候一些耗电的软件忘了清理，结果一晚上手机就没电了。如果可以设置一个时间，比如凌晨1点，定时执行一次清理，这样会很方便。

**Comment by liudongmiao** [comment]
目前是离开多久之后，默认是半小时，理论上不会存在忘了清理就怎么怎么样。

此外，可以养成睡觉前，直接执行清理全部。。。
