### ISSUE TITLE
黑域1.0 当前台进程me.piebridge.brevent 被误杀后，重新手动启动后，设置-黑域方法自动变成"只强行停止，不侍机"

### ISSUE THREAD

**Issue by bigbighill** [liudongmiao/Brevent#390]
黑域1.0 当前台进程me.piebridge.brevent 被误杀后，设置-黑域方法不管被杀前是什么状态，重新手动启动后黑域后，自动变成"只强行停止，不侍机"。

小米5sp miui 8.2 android 6.0.1

**Comment by liudongmiao** [comment]
你小米支持待机才怪
