### ISSUE TITLE
FCM does not work for WhatsApp

### ISSUE THREAD

**Issue by ppterryhui** [liudongmiao/Brevent#391]
It does not work if WhatsApp is brevented by Standby method. However it works perfectly if it is brevented by force-stop method. I am on version 1.0

**Comment by liudongmiao** [comment]
Could you help to check the GCM message when WhatsApp in Standby?

In dial pad, type `*#*#GCM#*#*`

**Comment by ppterryhui** [comment]
I just found that I can receive WhatsApp even use the Standby brevented
mode. However , there is a delay. With comparing with brevented with
force-stop, which I can receive the WhatsApp instantly.

The second thing is force-stop mode works on Line messenger for receiving
FCM but not Standby mode

A. 22:45 Line with force-stop
B. 22:46 WhatsApp with force-stop
C. 22:49 WhatsApp with Standby

**Comment by liudongmiao** [comment]
Sorry, I don't think i can resolve this issue.

For me, some apps claim to support fcm, but actually not. 

And for myself, play console works ok. It can still receive mesaages in standby and force-stop state. For the first message, in force-stop state, for later mesaages, in standby state.

Don't brevent IM apps, otherwise you may miss important mesaages.

**Comment by ppterryhui** [comment]
Can I have a suggestion on brevented?

Understand that we can choose Standby or force-stop mode globally. It means
we can only choose one mode for all apps.

Is it possible to make the configuration individually? Like, I brevent app
A with Standby mode while brevent app B with force-stop mode.

**Comment by liudongmiao** [comment]
For single app, you can brevent it, then choose allow sync.
If you open it, and don't quit it using Back, it will never be force-stopped.

**Comment by liudongmiao** [comment]
You can brevent app, rhen click it, or long click to show context menu, you will see allow sync.
