### ISSUE TITLE
在Magisk的root下，似乎无法正常使用root开启黑域

### ISSUE THREAD

**Issue by Removable** [liudongmiao/Brevent#393]
具体不清楚是不是Magisk的root导致的，希望作者有空能看一下这个问题，放到低优先级解决也没问题

Nexus 6P，原生7.1.2，使用MagiskSU

**Comment by Removable** [comment]
谢谢

**Comment by BlackLotus152** [comment]
可以去酷市场下载aviraxp制作的magisk模块

**Comment by aviraxp** [comment]
没日志，说啥都白搭

**Comment by guoyonganceo** [comment]
Su调整为仅应用

**Comment by Removable** [comment]
@aviraxp 请问运行adb -d logcat -d -b main -s BreventServer BreventLoader之后，日志是输出在adb目录下的吗？

**Comment by Removable** [comment]
@guoyonganceo 似乎还是不行

**Comment by aviraxp** [comment]
。。。。你连电脑了，日志应该直接在命令行打印出来啊

**Comment by Removable** [comment]
@aviraxp 就是没看到命令行输出啊。。。

**Comment by aviraxp** [comment]
触发一遍之后 马上打印日志

**Comment by Removable** [comment]
@aviraxp 打出来了，麻烦看一下，谢谢
04-06 23:58:42.246  6589  6589 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-06 23:58:43.026  6626  6626 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]]
04-06 23:58:43.038  6626  6626 I BreventServer: Brevent Server 1.0 started
04-06 23:58:43.052  6626  6626 I BreventServer: brevent user: 0, uid: 0
04-06 23:58:43.053  6626  6626 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
04-06 23:58:43.367  6626  6626 I BreventServer: loading brevent list
04-06 23:58:43.371  6626  6626 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 75
04-06 23:58:43.372  6626  6626 D BreventServer: brevent: {com.amazon.mShop.android.shopping, #省略一堆# com.eg.android.AlipayGphone, org.nixgame.ruler}
04-06 23:58:43.372  6626  6626 D BreventServer: priority: {}
04-06 23:58:43.372  6626  6626 I BreventServer: loading brevent conf
04-06 23:58:43.379  6626  6626 D BreventServer: Can't dump widgets (ignore)
04-06 23:58:43.407  6626  6626 D BreventServer: notification_cancel_all, tag: 2752, event: 4
04-06 23:58:43.411  6626  6626 D BreventServer: notification_panel_revealed, tag: 27500, event: 6
04-06 23:58:43.412  6626  6626 D BreventServer: notification_panel_hidden, tag: 27501, event: 7
04-06 23:58:43.412  6626  6626 D BreventServer: am_new_intent, tag: 30003, event: 8
04-06 23:58:43.413  6626  6626 D BreventServer: am_resume_activity, tag: 30007, event: 2
04-06 23:58:43.414  6626  6626 D BreventServer: am_pause_activity, tag: 30013, event: 9
04-06 23:58:43.414  6626  6626 D BreventServer: am_proc_start, tag: 30014, event: 1
04-06 23:58:43.416  6626  6626 D BreventServer: am_switch_user, tag: 30041, event: 3
04-06 23:58:43.421  6626  6626 D BreventServer: screen_toggled, tag: 70000, event: 5
04-06 23:58:43.430  6626  6626 D BreventServer: check and brevent
04-06 23:58:43.433  6626  6626 D BreventServer: Can't dump notifications
04-06 23:58:43.439  6626  6626 D BreventServer: Can't dump widgets (ignore)
04-06 23:58:43.441  6626  6626 E BreventServer: Can't dump activities
04-06 23:58:43.441  6626  6626 E BreventServer: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
04-06 23:58:43.441  6626  6626 E BreventServer:         at android.os.BinderProxy.transactNative(Native Method)
04-06 23:58:43.441  6626  6626 E BreventServer:         at android.os.BinderProxy.transact(Binder.java:615)
04-06 23:58:43.441  6626  6626 E BreventServer:         at android.os.BinderProxy.dump(Binder.java:631)
04-06 23:58:43.441  6626  6626 E BreventServer:         at me.piebridge.brevent.server.d.d(HideApi.java:321)
04-06 23:58:43.441  6626  6626 E BreventServer:         at me.piebridge.brevent.server.BreventServer.o(BreventServer.java:1384)
04-06 23:58:43.441  6626  6626 E BreventServer:         at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:489)
04-06 23:58:43.441  6626  6626 E BreventServer:         at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1560)
04-06 23:58:43.441  6626  6626 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
04-06 23:58:43.441  6626  6626 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1582)
04-06 23:58:43.441  6626  6626 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-06 23:58:43.441  6626  6626 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
04-06 23:58:43.453  6589  6589 E BreventLoader: worker 6626 exited on signal 9
04-06 23:58:43.453  6589  6589 D BreventLoader: signal arrived, update: 0
04-06 23:58:43.454  6588  6588 D BreventLoader: worker 6589 exited with status 0

**Comment by liudongmiao** [comment]
从日志看，与 root 无关。

此外，root 为实验性功能，不提供任何支持。

**Comment by liudongmiao** [comment]
个人建议过程为:

1. adb 模式是否正常
2. root 模式是否正常
3. 开机自启模式是否正常
4. 你爱干啥就爱啥模式

总之，我目前不对 root 模式提供任何支持。
但是我会保证在模拟器，及自己的测试机 1 - 3 都正常。

**Comment by Removable** [comment]
目前是adb模式正常，root开启模式不正常，root自启不正常，magisk模块自启不正常
算了吧，root不行就不行吧，反正电脑是有的，就是怕出门在外什么的

Liu DongMiao <notifications@github.com>于2017年4月7日周五 10:10写道：

**Comment by liudongmiao** [comment]
如果  root 模式不正常，后续尝试就可以终止。
如果你实在要测试，就直接 adb 连上以后，切换到 root，然后观察日志。

当初，我就是被 @aviraxp 带上了要 root 的路上，一发不可收拾。
先是，解决他机器上 root 的问题，然后，解决他机器上 selinux 的问题。

如果你们有时间，可以继续测试。但我本人真的太累，不提供支持。
如果你是阻止运行时代就是捐赠用户，请再约时间调试。
电脑上装好 teamviewer，然后帐号密码发我邮箱。
如果不知道我邮箱，就去 Play 商店底部看，或 adb 进入以后点反馈都能看到。

**Comment by Removable** [comment]
算了算了，root模式不行也没事，（虽然我以前就捐赠过两次还是三次来着

Liu DongMiao <notifications@github.com>于2017年4月7日周五 11:22写道：

**Comment by liudongmiao** [comment]
有需要就约好时间调试，但我不保证能解决。
