### ISSUE TITLE
不支持7.1.2？

### ISSUE THREAD

**Issue by em020** [liudongmiao/Brevent#394]
今天设备推来了7.1.2更新，升级之后黑域不能用了，具体症状是，输入完adb命令后，仍然不能进入进程列表，在recent tasks里划掉黑域再进入也不行

设备是nexus 5x

**Comment by liudongmiao** [comment]
日志日志日志。

我用 7.1.2 几天。

**Comment by em020** [comment]
奇怪，刚才试了一下又正常了，谢谢回复，really great job!

To 其他人，Nexus 5X，7.1.2，非root，亲测可用。
