### ISSUE TITLE
请重启黑域服务，一直闪，就是进不到列表中

### ISSUE THREAD

**Issue by sloate** [liudongmiao/Brevent#397]
服务日志：

C:\Users\Sloate>adb -d logcat -d -b main -s BreventServer BreventLoader
04-07 14:16:53.155 17865 17865 D BreventServer: checking feelgood
04-07 14:16:53.159 17865 17997 D BreventServer: received feelgood
04-07 14:17:11.219 17865 17865 D BreventServer: checking feelgood
04-07 14:17:11.219 17865 17865 D BreventServer: check and brevent
04-07 14:17:11.220 17865 17997 D BreventServer: received feelgood
04-07 14:17:11.763 17865 17865 D BreventServer: widgets: {hanjie.app.pureweather
, small.word}
04-07 14:17:11.763 17865 17865 D BreventServer: running: {org.getlantern.lantern
=411, com.tencent.mm=758, me.piebridge.brevent=2345, com.shuame.mobile=2344, com
.coolapk.market=1790, com.android.settings=2298}
04-07 14:17:11.763 17865 17865 D BreventServer: recent: {org.getlantern.lantern=
1627, com.tencent.mm=1974, me.piebridge.brevent=3560, com.shuame.mobile=3560, co
m.coolapk.market=3006, com.android.settings=1336}
04-07 14:17:11.988 17865 17865 D BreventServer: com.google.android.webview depen
ded by {jyeoo.app.ystudy, fm.xiami.main, com.UCMobile, com.coolapk.market, com.a
utonavi.minimap, cn.buding.martin, com.eg.android.AlipayGphone}
04-07 14:17:11.988 17865 17865 D BreventServer: com.google.android.gms depended
by {com.teslacoilsw.launcher, com.android.vending, com.google.android.apps.maps}

04-07 14:17:11.988 17865 17865 D BreventServer: service: {}
04-07 14:17:11.988 17865 17865 D BreventServer: back(no action): {}
04-07 14:17:11.989 17865 17865 D BreventServer: blocking: {}
04-07 14:17:11.989 17865 17865 D BreventServer: top: {me.piebridge.brevent}
04-07 14:17:11.989 17865 17865 D BreventServer: home: {com.teslacoilsw.launcher,
 com.android.systemui}
04-07 14:17:11.989 17865 17865 D BreventServer: current: me.piebridge.brevent
04-07 14:17:11.989 17865 17865 D BreventServer: unsafe: {}
04-07 14:17:11.989 17865 17865 D BreventServer: final blocking: {}
04-07 14:17:11.990 17865 17865 D BreventServer: notifications: {com.tencent.qqmu
sic=[98], com.android.vending=[272], fm.xiami.main=[98], com.UCMobile=[16]}
04-07 14:17:11.990 17865 17865 D BreventServer: noRecent: {}
04-07 14:17:11.990 17865 17865 D BreventServer: foreground service: {}
04-07 14:17:11.990 17865 17865 D BreventServer: sticky notification: {}
04-07 14:17:11.990 17865 17865 D BreventServer: check and brevent, took 770ms
04-07 14:17:29.243 17865 17865 D BreventServer: checking feelgood
04-07 14:17:29.245 17865 17997 D BreventServer: received feelgood
04-07 14:17:47.249 17865 17865 D BreventServer: checking feelgood
04-07 14:17:47.262 17865 17997 D BreventServer: received feelgood
04-07 14:18:05.308 17865 17865 D BreventServer: checking feelgood
04-07 14:18:05.310 17865 17997 D BreventServer: received feelgood
04-07 14:18:23.299 17865 17865 D BreventServer: checking feelgood
04-07 14:18:23.303 17865 17997 D BreventServer: received feelgood
04-07 14:18:41.343 17865 17865 D BreventServer: checking feelgood
04-07 14:18:41.345 17865 17997 D BreventServer: received feelgood
04-07 14:18:59.372 17865 17865 D BreventServer: checking feelgood
04-07 14:18:59.385 17865 17997 D BreventServer: received feelgood
04-07 14:19:17.402 17865 17865 D BreventServer: checking feelgood
04-07 14:19:17.404 17865 17997 D BreventServer: received feelgood

C:\Users\Sloate>

**Comment by liudongmiao** [comment]
那就重启机器，然后重新执行

**Comment by sloate** [comment]
还是这样

**Comment by sloate** [comment]
崩溃日志：
04-07 14:05:03.744 22521 22521 F DEBUG   :     x28  0000000000000000  x29  00000
07fd2ba54b0  x30  000000557ce42d4c
04-07 14:05:03.744 22521 22521 F DEBUG   :     sp   0000007fd2ba5410  pc   00000
07c050f7504  pstate 0000000000000000
04-07 14:05:03.756 22521 22521 F DEBUG   :
04-07 14:05:03.756 22521 22521 F DEBUG   : backtrace:
04-07 14:05:03.756 22521 22521 F DEBUG   :     #00 pc 000000000001b504  /system/
lib64/libc.so (strncmp+232)
04-07 14:05:03.756 22521 22521 F DEBUG   :     #01 pc 0000000000020d48  /system/
bin/toybox
04-07 14:05:03.756 22521 22521 F DEBUG   :     #02 pc 000000000000c58c  /system/
bin/toybox
04-07 14:05:03.756 22521 22521 F DEBUG   :     #03 pc 000000000000c678  /system/
bin/toybox
04-07 14:05:03.756 22521 22521 F DEBUG   :     #04 pc 000000000000c5e4  /system/
bin/toybox
04-07 14:05:03.756 22521 22521 F DEBUG   :     #05 pc 0000000000020340  /system/
bin/toybox
04-07 14:05:03.756 22521 22521 F DEBUG   :     #06 pc 000000000001190c  /system/
bin/toybox
04-07 14:05:03.756 22521 22521 F DEBUG   :     #07 pc 00000000000114b8  /system/
bin/toybox
04-07 14:05:03.756 22521 22521 F DEBUG   :     #08 pc 00000000000119a4  /system/
bin/toybox
04-07 14:05:03.756 22521 22521 F DEBUG   :     #09 pc 000000000001a594  /system/
lib64/libc.so (__libc_init+88)
04-07 14:05:03.756 22521 22521 F DEBUG   :     #10 pc 000000000000b6f8  /system/
bin/toybox
04-07 14:06:54.946 23434 23434 F libc    : Fatal signal 11 (SIGSEGV), code 1, fa
ult addr 0x0 in tid 23434 (netstat)
04-07 14:06:55.008 23436 23436 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-07 14:06:55.008 23436 23436 F DEBUG   : Build fingerprint: 'google/angler/ang
ler:7.1.2/N2G47H/3783593:user/release-keys'
04-07 14:06:55.008 23436 23436 F DEBUG   : Revision: '0'
04-07 14:06:55.008 23436 23436 F DEBUG   : ABI: 'arm64'
04-07 14:06:55.008 23436 23436 F DEBUG   : pid: 23434, tid: 23434, name: netstat
  >>> netstat <<<
04-07 14:06:55.009 23436 23436 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAP
ERR), fault addr 0x0
04-07 14:06:55.010 23436 23436 F DEBUG   :     x0   0000000000000000  x1   00000
0557f1b4402  x2   0000000000000007  x3   0000000000000004
04-07 14:06:55.010 23436 23436 F DEBUG   :     x4   000000000000004b  x5   80808
08000000000  x6   0000007fe00bce87  x7   fefefeff33fefefe
04-07 14:06:55.010 23436 23436 F DEBUG   :     x8   000000557f1b4402  x9   00000
07e7660c708  x10  000000000000004b  x11  0101010101010101
04-07 14:06:55.010 23436 23436 F DEBUG   :     x12  0000007e7660c6e8  x13  00000
0000ccccccc  x14  000000008000002f  x15  0000007e76d6d268
04-07 14:06:55.010 23436 23436 F DEBUG   :     x16  000000557f1cd778  x17  00000
07e76ce241c  x18  0000000000000000  x19  ffffffffffffffff
04-07 14:06:55.010 23436 23436 F DEBUG   :     x20  0000007e7662a1f0  x21  00000
07e76636400  x22  000000557f1b0df5  x23  ffffffffffffffff
04-07 14:06:55.010 23436 23436 F DEBUG   :     x24  0000007e76632010  x25  00000
0557f1cf760  x26  000000557f1b4402  x27  000000557f1b440b
04-07 14:06:55.010 23436 23436 F DEBUG   :     x28  0000000000000000  x29  00000
07fe00bcf10  x30  000000557f198d4c
04-07 14:06:55.011 23436 23436 F DEBUG   :     sp   0000007fe00bce70  pc   00000
07e76ce2504  pstate 0000000000000000
04-07 14:06:55.016 23436 23436 F DEBUG   :
04-07 14:06:55.016 23436 23436 F DEBUG   : backtrace:
04-07 14:06:55.018 23436 23436 F DEBUG   :     #00 pc 000000000001b504  /system/
lib64/libc.so (strncmp+232)
04-07 14:06:55.018 23436 23436 F DEBUG   :     #01 pc 0000000000020d48  /system/
bin/toybox
04-07 14:06:55.018 23436 23436 F DEBUG   :     #02 pc 000000000000c58c  /system/
bin/toybox
04-07 14:06:55.018 23436 23436 F DEBUG   :     #03 pc 000000000000c678  /system/
bin/toybox
04-07 14:06:55.018 23436 23436 F DEBUG   :     #04 pc 000000000000c5e4  /system/
bin/toybox
04-07 14:06:55.019 23436 23436 F DEBUG   :     #05 pc 0000000000020340  /system/
bin/toybox
04-07 14:06:55.019 23436 23436 F DEBUG   :     #06 pc 000000000001190c  /system/
bin/toybox
04-07 14:06:55.019 23436 23436 F DEBUG   :     #07 pc 00000000000114b8  /system/
bin/toybox
04-07 14:06:55.019 23436 23436 F DEBUG   :     #08 pc 00000000000119a4  /system/
bin/toybox
04-07 14:06:55.019 23436 23436 F DEBUG   :     #09 pc 000000000001a594  /system/
lib64/libc.so (__libc_init+88)
04-07 14:06:55.019 23436 23436 F DEBUG   :     #10 pc 000000000000b6f8  /system/
bin/toybox
04-07 14:13:36.814 27097 27097 F libc    : Fatal signal 11 (SIGSEGV), code 1, fa
ult addr 0x0 in tid 27097 (netstat)
04-07 14:13:36.891 27101 27101 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-07 14:13:36.891 27101 27101 F DEBUG   : Build fingerprint: 'google/angler/ang
ler:7.1.2/N2G47H/3783593:user/release-keys'
04-07 14:13:36.891 27101 27101 F DEBUG   : Revision: '0'
04-07 14:13:36.891 27101 27101 F DEBUG   : ABI: 'arm64'
04-07 14:13:36.892 27101 27101 F DEBUG   : pid: 27097, tid: 27097, name: netstat
  >>> netstat <<<
04-07 14:13:36.892 27101 27101 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAP
ERR), fault addr 0x0
04-07 14:13:36.892 27101 27101 F DEBUG   :     x0   0000000000000000  x1   00000
05557826402  x2   0000000000000007  x3   0000000000000004
04-07 14:13:36.892 27101 27101 F DEBUG   :     x4   000000000000004b  x5   00000
00000000000  x6   0000007fe8bb7ea9  x7   fefefefefefefefe
04-07 14:13:36.892 27101 27101 F DEBUG   :     x8   0000005557826402  x9   00000
071df40c708  x10  000000000000004b  x11  0101010101010101
04-07 14:13:36.892 27101 27101 F DEBUG   :     x12  00000071df40c6e8  x13  00000
0000ccccccc  x14  000000008000002f  x15  00000071dfcb1268
04-07 14:13:36.892 27101 27101 F DEBUG   :     x16  000000555783f778  x17  00000
071dfc2641c  x18  0000000000000000  x19  ffffffffffffffff
04-07 14:13:36.892 27101 27101 F DEBUG   :     x20  00000071df42a1f0  x21  00000
071df436400  x22  0000005557822df5  x23  ffffffffffffffff
04-07 14:13:36.892 27101 27101 F DEBUG   :     x24  00000071df427780  x25  00000
05557841760  x26  0000005557826402  x27  000000555782640b
04-07 14:13:36.892 27101 27101 F DEBUG   :     x28  0000000000000000  x29  00000
07fe8bb7f30  x30  000000555780ad4c
04-07 14:13:36.892 27101 27101 F DEBUG   :     sp   0000007fe8bb7e90  pc   00000
071dfc26504  pstate 0000000000000000
04-07 14:13:36.897 27101 27101 F DEBUG   :
04-07 14:13:36.897 27101 27101 F DEBUG   : backtrace:
04-07 14:13:36.898 27101 27101 F DEBUG   :     #00 pc 000000000001b504  /system/
lib64/libc.so (strncmp+232)
04-07 14:13:36.898 27101 27101 F DEBUG   :     #01 pc 0000000000020d48  /system/
bin/toybox
04-07 14:13:36.898 27101 27101 F DEBUG   :     #02 pc 000000000000c58c  /system/
bin/toybox
04-07 14:13:36.898 27101 27101 F DEBUG   :     #03 pc 000000000000c678  /system/
bin/toybox
04-07 14:13:36.898 27101 27101 F DEBUG   :     #04 pc 000000000000c5e4  /system/
bin/toybox
04-07 14:13:36.898 27101 27101 F DEBUG   :     #05 pc 0000000000020340  /system/
bin/toybox
04-07 14:13:36.898 27101 27101 F DEBUG   :     #06 pc 000000000001190c  /system/
bin/toybox
04-07 14:13:36.898 27101 27101 F DEBUG   :     #07 pc 00000000000114b8  /system/
bin/toybox
04-07 14:13:36.898 27101 27101 F DEBUG   :     #08 pc 00000000000119a4  /system/
bin/toybox
04-07 14:13:36.898 27101 27101 F DEBUG   :     #09 pc 000000000001a594  /system/
lib64/libc.so (__libc_init+88)
04-07 14:13:36.898 27101 27101 F DEBUG   :     #10 pc 000000000000b6f8  /system/
bin/toybox
04-07 14:13:47.573 27121 27121 F libc    : Fatal signal 11 (SIGSEGV), code 1, fa
ult addr 0x0 in tid 27121 (netstat)
04-07 14:13:47.688 27124 27124 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-07 14:13:47.689 27124 27124 F DEBUG   : Build fingerprint: 'google/angler/ang
ler:7.1.2/N2G47H/3783593:user/release-keys'
04-07 14:13:47.689 27124 27124 F DEBUG   : Revision: '0'
04-07 14:13:47.689 27124 27124 F DEBUG   : ABI: 'arm64'
04-07 14:13:47.689 27124 27124 F DEBUG   : pid: 27121, tid: 27121, name: netstat
  >>> netstat <<<
04-07 14:13:47.689 27124 27124 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAP
ERR), fault addr 0x0
04-07 14:13:47.689 27124 27124 F DEBUG   :     x0   0000000000000000  x1   00000
05558105402  x2   0000000000000007  x3   0000000000000004
04-07 14:13:47.689 27124 27124 F DEBUG   :     x4   000000000000004b  x5   00000
00000000000  x6   0000007fe61e33f7  x7   fefefefefefefefe
04-07 14:13:47.689 27124 27124 F DEBUG   :     x8   0000005558105402  x9   00000
079bb20c708  x10  000000000000004b  x11  0101010101010101
04-07 14:13:47.689 27124 27124 F DEBUG   :     x12  00000079bb20c6e8  x13  00000
0000ccccccc  x14  000000008000002f  x15  00000079bb7c5268
04-07 14:13:47.689 27124 27124 F DEBUG   :     x16  000000555811e778  x17  00000
079bb73a41c  x18  0000000000000000  x19  ffffffffffffffff
04-07 14:13:47.689 27124 27124 F DEBUG   :     x20  00000079bb22a1f0  x21  00000
079bb236400  x22  0000005558101df5  x23  ffffffffffffffff
04-07 14:13:47.689 27124 27124 F DEBUG   :     x24  00000079bb232010  x25  00000
05558120760  x26  0000005558105402  x27  000000555810540b
04-07 14:13:47.689 27124 27124 F DEBUG   :     x28  0000000000000000  x29  00000
07fe61e3480  x30  00000055580e9d4c
04-07 14:13:47.689 27124 27124 F DEBUG   :     sp   0000007fe61e33e0  pc   00000
079bb73a504  pstate 0000000000000000
04-07 14:13:47.697 27124 27124 F DEBUG   :
04-07 14:13:47.697 27124 27124 F DEBUG   : backtrace:
04-07 14:13:47.697 27124 27124 F DEBUG   :     #00 pc 000000000001b504  /system/
lib64/libc.so (strncmp+232)
04-07 14:13:47.697 27124 27124 F DEBUG   :     #01 pc 0000000000020d48  /system/
bin/toybox
04-07 14:13:47.697 27124 27124 F DEBUG   :     #02 pc 000000000000c58c  /system/
bin/toybox
04-07 14:13:47.697 27124 27124 F DEBUG   :     #03 pc 000000000000c678  /system/
bin/toybox
04-07 14:13:47.697 27124 27124 F DEBUG   :     #04 pc 000000000000c5e4  /system/
bin/toybox
04-07 14:13:47.697 27124 27124 F DEBUG   :     #05 pc 0000000000020340  /system/
bin/toybox
04-07 14:13:47.697 27124 27124 F DEBUG   :     #06 pc 000000000001190c  /system/
bin/toybox
04-07 14:13:47.697 27124 27124 F DEBUG   :     #07 pc 00000000000114b8  /system/
bin/toybox
04-07 14:13:47.697 27124 27124 F DEBUG   :     #08 pc 00000000000119a4  /system/
bin/toybox
04-07 14:13:47.697 27124 27124 F DEBUG   :     #09 pc 000000000001a594  /system/
lib64/libc.so (__libc_init+88)
04-07 14:13:47.698 27124 27124 F DEBUG   :     #10 pc 000000000000b6f8  /system/
bin/toybox
04-07 14:15:20.808 27496 27496 F libc    : Fatal signal 11 (SIGSEGV), code 1, fa
ult addr 0x0 in tid 27496 (netstat)
04-07 14:15:20.874 27498 27498 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-07 14:15:20.875 27498 27498 F DEBUG   : Build fingerprint: 'google/angler/ang
ler:7.1.2/N2G47H/3783593:user/release-keys'
04-07 14:15:20.875 27498 27498 F DEBUG   : Revision: '0'
04-07 14:15:20.875 27498 27498 F DEBUG   : ABI: 'arm64'
04-07 14:15:20.875 27498 27498 F DEBUG   : pid: 27496, tid: 27496, name: netstat
  >>> netstat <<<
04-07 14:15:20.875 27498 27498 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAP
ERR), fault addr 0x0
04-07 14:15:20.875 27498 27498 F DEBUG   :     x0   0000000000000000  x1   00000
05555d81402  x2   0000000000000007  x3   0000000000000004
04-07 14:15:20.875 27498 27498 F DEBUG   :     x4   000000000000004b  x5   80808
00000000000  x6   0000007fdc566e19  x7   fefeff3134fefefe
04-07 14:15:20.875 27498 27498 F DEBUG   :     x8   0000005555d81402  x9   00000
07028a0c708  x10  000000000000004b  x11  0101010101010101
04-07 14:15:20.875 27498 27498 F DEBUG   :     x12  0000007028a0c6e8  x13  00000
0000ccccccc  x14  000000008000002f  x15  00000070291f9268
04-07 14:15:20.875 27498 27498 F DEBUG   :     x16  0000005555d9a778  x17  00000
0702916e41c  x18  0000000000000000  x19  ffffffffffffffff
04-07 14:15:20.875 27498 27498 F DEBUG   :     x20  0000007028a2a1f0  x21  00000
07028a36400  x22  0000005555d7ddf5  x23  000000000007f1b1
04-07 14:15:20.875 27498 27498 F DEBUG   :     x24  0000007028a27780  x25  00000
05555d9c760  x26  0000005555d81402  x27  0000005555d8140b
04-07 14:15:20.875 27498 27498 F DEBUG   :     x28  0000000000000000  x29  00000
07fdc566ea0  x30  0000005555d65d4c
04-07 14:15:20.875 27498 27498 F DEBUG   :     sp   0000007fdc566e00  pc   00000
0702916e504  pstate 0000000000000000
04-07 14:15:20.881 27498 27498 F DEBUG   :
04-07 14:15:20.881 27498 27498 F DEBUG   : backtrace:
04-07 14:15:20.881 27498 27498 F DEBUG   :     #00 pc 000000000001b504  /system/
lib64/libc.so (strncmp+232)
04-07 14:15:20.881 27498 27498 F DEBUG   :     #01 pc 0000000000020d48  /system/
bin/toybox
04-07 14:15:20.881 27498 27498 F DEBUG   :     #02 pc 000000000000c58c  /system/
bin/toybox
04-07 14:15:20.881 27498 27498 F DEBUG   :     #03 pc 000000000000c678  /system/
bin/toybox
04-07 14:15:20.881 27498 27498 F DEBUG   :     #04 pc 000000000000c5e4  /system/
bin/toybox
04-07 14:15:20.881 27498 27498 F DEBUG   :     #05 pc 0000000000020340  /system/
bin/toybox
04-07 14:15:20.881 27498 27498 F DEBUG   :     #06 pc 000000000001190c  /system/
bin/toybox
04-07 14:15:20.881 27498 27498 F DEBUG   :     #07 pc 00000000000114b8  /system/
bin/toybox
04-07 14:15:20.881 27498 27498 F DEBUG   :     #08 pc 00000000000119a4  /system/
bin/toybox
04-07 14:15:20.881 27498 27498 F DEBUG   :     #09 pc 000000000001a594  /system/
lib64/libc.so (__libc_init+88)
04-07 14:15:20.881 27498 27498 F DEBUG   :     #10 pc 000000000000b6f8  /system/
bin/toybox
04-07 14:16:29.417 28946 28946 F libc    : Fatal signal 11 (SIGSEGV), code 1, fa
ult addr 0x0 in tid 28946 (netstat)
04-07 14:16:29.481 28947 28947 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-07 14:16:29.481 28947 28947 F DEBUG   : Build fingerprint: 'google/angler/ang
ler:7.1.2/N2G47H/3783593:user/release-keys'
04-07 14:16:29.481 28947 28947 F DEBUG   : Revision: '0'
04-07 14:16:29.481 28947 28947 F DEBUG   : ABI: 'arm64'
04-07 14:16:29.482 28947 28947 F DEBUG   : pid: 28946, tid: 28946, name: netstat
  >>> netstat <<<
04-07 14:16:29.482 28947 28947 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAP
ERR), fault addr 0x0
04-07 14:16:29.482 28947 28947 F DEBUG   :     x0   0000000000000000  x1   00000
055935ec402  x2   0000000000000007  x3   0000000000000004
04-07 14:16:29.482 28947 28947 F DEBUG   :     x4   000000000000004b  x5   80808
08000000000  x6   0000007fcdea3f47  x7   fefefeff33fefefe
04-07 14:16:29.482 28947 28947 F DEBUG   :     x8   00000055935ec402  x9   00000
07426e0c708  x10  000000000000004b  x11  0101010101010101
04-07 14:16:29.482 28947 28947 F DEBUG   :     x12  0000007426e0c6e8  x13  00000
0000ccccccc  x14  000000008000002f  x15  0000007427325268
04-07 14:16:29.482 28947 28947 F DEBUG   :     x16  0000005593605778  x17  00000
0742729a41c  x18  0000000000000000  x19  ffffffffffffffff
04-07 14:16:29.482 28947 28947 F DEBUG   :     x20  0000007426e2a1f0  x21  00000
07426e36400  x22  00000055935e8df5  x23  ffffffffffffffff
04-07 14:16:29.482 28947 28947 F DEBUG   :     x24  0000007426e32010  x25  00000
05593607760  x26  00000055935ec402  x27  00000055935ec40b
04-07 14:16:29.482 28947 28947 F DEBUG   :     x28  0000000000000000  x29  00000
07fcdea3fd0  x30  00000055935d0d4c
04-07 14:16:29.482 28947 28947 F DEBUG   :     sp   0000007fcdea3f30  pc   00000
0742729a504  pstate 0000000000000000
04-07 14:16:29.488 28947 28947 F DEBUG   :
04-07 14:16:29.488 28947 28947 F DEBUG   : backtrace:
04-07 14:16:29.488 28947 28947 F DEBUG   :     #00 pc 000000000001b504  /system/
lib64/libc.so (strncmp+232)
04-07 14:16:29.488 28947 28947 F DEBUG   :     #01 pc 0000000000020d48  /system/
bin/toybox
04-07 14:16:29.488 28947 28947 F DEBUG   :     #02 pc 000000000000c58c  /system/
bin/toybox
04-07 14:16:29.488 28947 28947 F DEBUG   :     #03 pc 000000000000c678  /system/
bin/toybox
04-07 14:16:29.488 28947 28947 F DEBUG   :     #04 pc 000000000000c5e4  /system/
bin/toybox
04-07 14:16:29.488 28947 28947 F DEBUG   :     #05 pc 0000000000020340  /system/
bin/toybox
04-07 14:16:29.488 28947 28947 F DEBUG   :     #06 pc 000000000001190c  /system/
bin/toybox
04-07 14:16:29.488 28947 28947 F DEBUG   :     #07 pc 00000000000114b8  /system/
bin/toybox
04-07 14:16:29.488 28947 28947 F DEBUG   :     #08 pc 00000000000119a4  /system/
bin/toybox
04-07 14:16:29.488 28947 28947 F DEBUG   :     #09 pc 000000000001a594  /system/
lib64/libc.so (__libc_init+88)
04-07 14:16:29.488 28947 28947 F DEBUG   :     #10 pc 000000000000b6f8  /system/
bin/toybox

C:\Users\Sloate>

**Comment by liudongmiao** [comment]
这里日志和黑域都没有什么关系

**Comment by sloate** [comment]
麻烦问一下我应该怎么操作

**Comment by liudongmiao** [comment]
电脑上装 teamviewer，然后帐号密码发我邮箱。
（邮箱请见商店底部，或者黑域内反馈）

我估计晚上 19.30 后有空。

**Comment by sloate** [comment]
谢谢您了，我把手机恢复出厂设置就能用了，以后有问题再来请教^v^

**Comment by liudongmiao** [comment]
恢复出厂设置....你真是执着啊，不能用，也用不着恢复出厂设置啊。

莫非你就是传说中的玩机高手，而不真正使用手机？

**Comment by amdth** [comment]
@sloate 莫非你是传说中的玩机高手，而不真正使用手机？
