### ISSUE TITLE
黑域方法选择【待机，然后强行停止】，但是每次用了一段时间后，就变成【只强行停止，不侍机】

### ISSUE THREAD

**Issue by Vstory** [liudongmiao/Brevent#399]
D:\Software\ADB\platform-tools>adb -d logcat -d -b crash
04-07 18:11:18.636  6266  6266 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 6266 (toybox)
04-07 18:11:18.704   642   642 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-07 18:11:18.704   642   642 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/7.4.6:user/release-keys'
04-07 18:11:18.704   642   642 F DEBUG   : Revision: '0'
04-07 18:11:18.704   642   642 F DEBUG   : ABI: 'arm64'
04-07 18:11:18.705   642   642 F DEBUG   : pid: 6266, tid: 6266, name: toybox  >>> toybox <<<
04-07 18:11:18.705   642   642 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-07 18:11:18.714   642   642 F DEBUG   :     x0   0000000000000000  x1   0000000000000000  x2   ffffffffffffffff  x3   0000000000000074
04-07 18:11:18.714   642   642 F DEBUG   :     x4   0000000000000074  x5   0000000000000000  x6   0000808080808080  x7   0000000000000000
04-07 18:11:18.714   642   642 F DEBUG   :     x8   00000000f8b3f8f7  x9   fefefefefeff736d  x10  7f7f7f7f7f7f7f7f  x11  0101010101010101
04-07 18:11:18.715   642   642 F DEBUG   :     x12  0000000000000010  x13  0000000000000000  x14  00000055991323c0  x15  0000000000000f30
04-07 18:11:18.715   642   642 F DEBUG   :     x16  0000007f7ccf8d40  x17  0000007f7cc6a6a4  x18  00000055991323e0  x19  0000000000000001
04-07 18:11:18.715   642   642 F DEBUG   :     x20  0000005561a0db24  x21  0000000000000007  x22  0000000000000001  x23  0000000000000007
04-07 18:11:18.715   642   642 F DEBUG   :     x24  00000055991323d3  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
04-07 18:11:18.715   642   642 F DEBUG   :     x28  0000005561a2bd20  x29  0000007fce55a960  x30  0000007f7ccc1994
04-07 18:11:18.715   642   642 F DEBUG   :     sp   0000007fce55a960  pc   0000007f7cc6a6b4  pstate 0000000040000000
04-07 18:11:18.729   642   642 F DEBUG   :
04-07 18:11:18.729   642   642 F DEBUG   : backtrace:
04-07 18:11:18.729   642   642 F DEBUG   :     #00 pc 000000000001a6b4  /system/lib64/libc.so (strlen+16)
04-07 18:11:18.729   642   642 F DEBUG   :     #01 pc 0000000000071990  /system/lib64/libc.so (__strlen_chk+12)
04-07 18:11:18.729   642   642 F DEBUG   :     #02 pc 000000000000b454  /system/bin/toybox
04-07 18:11:18.729   642   642 F DEBUG   :     #03 pc 0000000000010104  /system/bin/toybox
04-07 18:11:18.729   642   642 F DEBUG   :     #04 pc 000000000000ed14  /system/bin/toybox
04-07 18:11:18.729   642   642 F DEBUG   :     #05 pc 000000000000e8d0  /system/bin/toybox
04-07 18:11:18.729   642   642 F DEBUG   :     #06 pc 000000000000ed14  /system/bin/toybox
04-07 18:11:18.729   642   642 F DEBUG   :     #07 pc 000000000000e8d0  /system/bin/toybox
04-07 18:11:18.729   642   642 F DEBUG   :     #08 pc 000000000000ed50  /system/bin/toybox (main+52)
04-07 18:11:18.729   642   642 F DEBUG   :     #09 pc 000000000001976c  /system/lib64/libc.so (__libc_init+100)
04-07 18:11:18.729   642   642 F DEBUG   :     #10 pc 000000000000a290  /system/bin/toybox
04-07 18:11:18.872   642   642 F DEBUG   :
04-07 18:11:18.872   642   642 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_06
04-07 18:11:20.034  6352  6352 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 6352 (toybox)
04-07 18:11:20.137   642   642 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-07 18:11:20.137   642   642 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/7.4.6:user/release-keys'
04-07 18:11:20.137   642   642 F DEBUG   : Revision: '0'
04-07 18:11:20.137   642   642 F DEBUG   : ABI: 'arm64'
04-07 18:11:20.137   642   642 F DEBUG   : pid: 6352, tid: 6352, name: toybox  >>> toybox <<<
04-07 18:11:20.137   642   642 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-07 18:11:20.139   642   642 F DEBUG   :     x0   0000000000000000  x1   0000000000000000  x2   ffffffffffffffff  x3   0000000000000074
04-07 18:11:20.139   642   642 F DEBUG   :     x4   0000000000000074  x5   0000000000000000  x6   0000808080808080  x7   0000000000000000
04-07 18:11:20.139   642   642 F DEBUG   :     x8   00000000e60b88f7  x9   fefefefefeff736d  x10  7f7f7f7f7f7f7f7f  x11  0101010101010101
04-07 18:11:20.139   642   642 F DEBUG   :     x12  0000000000000010  x13  0000000000000000  x14  000000558a24f3c0  x15  0000000000000f30
04-07 18:11:20.139   642   642 F DEBUG   :     x16  0000007fb4ea7d40  x17  0000007fb4e196a4  x18  000000558a24f3e0  x19  0000000000000001
04-07 18:11:20.139   642   642 F DEBUG   :     x20  000000556c2f7b24  x21  0000000000000007  x22  0000000000000001  x23  0000000000000007
04-07 18:11:20.139   642   642 F DEBUG   :     x24  000000558a24f3d3  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
04-07 18:11:20.139   642   642 F DEBUG   :     x28  000000556c315d20  x29  0000007ff8279a80  x30  0000007fb4e70994
04-07 18:11:20.139   642   642 F DEBUG   :     sp   0000007ff8279a80  pc   0000007fb4e196b4  pstate 0000000040000000
04-07 18:11:20.145   642   642 F DEBUG   :
04-07 18:11:20.145   642   642 F DEBUG   : backtrace:
04-07 18:11:20.145   642   642 F DEBUG   :     #00 pc 000000000001a6b4  /system/lib64/libc.so (strlen+16)
04-07 18:11:20.145   642   642 F DEBUG   :     #01 pc 0000000000071990  /system/lib64/libc.so (__strlen_chk+12)
04-07 18:11:20.145   642   642 F DEBUG   :     #02 pc 000000000000b454  /system/bin/toybox
04-07 18:11:20.145   642   642 F DEBUG   :     #03 pc 0000000000010104  /system/bin/toybox
04-07 18:11:20.145   642   642 F DEBUG   :     #04 pc 000000000000ed14  /system/bin/toybox
04-07 18:11:20.145   642   642 F DEBUG   :     #05 pc 000000000000e8d0  /system/bin/toybox
04-07 18:11:20.145   642   642 F DEBUG   :     #06 pc 000000000000ed14  /system/bin/toybox
04-07 18:11:20.145   642   642 F DEBUG   :     #07 pc 000000000000e8d0  /system/bin/toybox
04-07 18:11:20.145   642   642 F DEBUG   :     #08 pc 000000000000ed50  /system/bin/toybox (main+52)
04-07 18:11:20.145   642   642 F DEBUG   :     #09 pc 000000000001976c  /system/lib64/libc.so (__libc_init+100)
04-07 18:11:20.145   642   642 F DEBUG   :     #10 pc 000000000000a290  /system/bin/toybox
04-07 18:11:20.301   642   642 F DEBUG   :
04-07 18:11:20.301   642   642 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_07
04-07 18:11:32.515   663   663 F libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xf52649e8 in tid 663 (main)
04-07 18:11:32.620   641   641 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-07 18:11:32.621   641   641 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/7.4.6:user/release-keys'
04-07 18:11:32.621   641   641 F DEBUG   : Revision: '0'
04-07 18:11:32.621   641   641 F DEBUG   : ABI: 'arm'
04-07 18:11:32.621   641   641 F DEBUG   : pid: 663, tid: 663, name: main  >>> zygote <<<
04-07 18:11:32.621   641   641 F DEBUG   : signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xf52649e8
04-07 18:11:32.650   641   641 F DEBUG   :     r0 0000000b  r1 f7643c90  r2 f7643d10  r3 70795465
04-07 18:11:32.650   641   641 F DEBUG   :     r4 ab6bb9f0  r5 00000002  r6 00000000  r7 ab802878
04-07 18:11:32.650   641   641 F DEBUG   :     r8 ff833d74  r9 ff833dc0  sl 00000001  fp f15db7ec
04-07 18:11:32.650   641   641 F DEBUG   :     ip f73fe5dc  sp f7643c90  lr f73b6838  pc f52649e8  cpsr 00010030
04-07 18:11:32.656   641   641 F DEBUG   :
04-07 18:11:32.656   641   641 F DEBUG   : backtrace:
04-07 18:11:32.656   641   641 F DEBUG   :     #00 pc 003589e8  /system/lib/libart.so (_ZN3art10ThreadList20FindThreadByThreadIdEj+155)
04-07 18:11:32.656   641   641 F DEBUG   :     #01 pc 00016834  /system/lib/libc.so
04-07 18:11:32.656   641   641 F DEBUG   :     #02 pc 70795460  <unknown>
04-07 18:11:33.174   641   641 F DEBUG   :
04-07 18:11:33.174   641   641 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_08
04-07 18:11:36.937  6935  6935 F libc    : Fatal signal 13 (SIGPIPE), code 0 in tid 6935 (sh)
04-07 18:11:37.041   642   642 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-07 18:11:37.041   642   642 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/7.4.6:user/release-keys'
04-07 18:11:37.041   642   642 F DEBUG   : Revision: '0'
04-07 18:11:37.041   642   642 F DEBUG   : ABI: 'arm64'
04-07 18:11:37.041   642   642 F DEBUG   : pid: 6935, tid: 6935, name: sh  >>> sh <<<
04-07 18:11:37.041   642   642 F DEBUG   : signal 13 (SIGPIPE), code 0 (SI_USER), fault addr --------
04-07 18:11:37.043   642   642 F DEBUG   :     x0   ffffffffffffffe0  x1   00000055a4a027e8  x2   0000000000000007  x3   00000055a4a027ee
04-07 18:11:37.043   642   642 F DEBUG   :     x4   0000000000000000  x5   0000000000000001  x6   00000055a4a02868  x7   00000000000000e0
04-07 18:11:37.043   642   642 F DEBUG   :     x8   0000000000000040  x9   0000000000051450  x10  0000000010051450  x11  0000000000000080
04-07 18:11:37.043   642   642 F DEBUG   :     x12  00000055a4a02868  x13  000000558cddb000  x14  000000558cddb000  x15  000000000000000a
04-07 18:11:37.043   642   642 F DEBUG   :     x16  000000558ce17b50  x17  0000007f9d83fd2c  x18  00000000ffffffff  x19  0000000000000007
04-07 18:11:37.044   642   642 F DEBUG   :     x20  00000055a4a027e8  x21  0000000000000000  x22  0000000000000000  x23  0000000000000003
04-07 18:11:37.044   642   642 F DEBUG   :     x24  00000055a4a027ef  x25  0000000000000003  x26  0000000000000001  x27  0000000000000007
04-07 18:11:37.044   642   642 F DEBUG   :     x28  0000000000000007  x29  0000007fc27ab020  x30  000000558cddbb68
04-07 18:11:37.044   642   642 F DEBUG   :     sp   0000007fc27ab020  pc   0000007f9d83fd34  pstate 0000000020000000
04-07 18:11:37.051   642   642 F DEBUG   :
04-07 18:11:37.051   642   642 F DEBUG   : backtrace:
04-07 18:11:37.051   642   642 F DEBUG   :     #00 pc 000000000006ad34  /system/lib64/libc.so (write+8)
04-07 18:11:37.051   642   642 F DEBUG   :     #01 pc 0000000000019b64  /system/bin/sh
04-07 18:11:37.051   642   642 F DEBUG   :     #02 pc 000000000001522c  /system/bin/sh
04-07 18:11:37.051   642   642 F DEBUG   :     #03 pc 0000000000017ba4  /system/bin/sh
04-07 18:11:37.051   642   642 F DEBUG   :     #04 pc 0000000000016edc  /system/bin/sh
04-07 18:11:37.051   642   642 F DEBUG   :     #05 pc 000000000002a2d4  /system/bin/sh
04-07 18:11:37.051   642   642 F DEBUG   :     #06 pc 000000000000629c  /system/bin/sh (main+1848)
04-07 18:11:37.051   642   642 F DEBUG   :     #07 pc 000000000001976c  /system/lib64/libc.so (__libc_init+100)
04-07 18:11:37.051   642   642 F DEBUG   :     #08 pc 0000000000006860  /system/bin/sh
04-07 18:11:37.105   642   642 F DEBUG   :
04-07 18:11:37.105   642   642 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_09
04-07 18:30:44.520 30315 30589 E AndroidRuntime: FATAL EXCEPTION: IntentService[FlushLogsService]
04-07 18:30:44.520 30315 30589 E AndroidRuntime: Process: com.android.vending, PID: 30315
04-07 18:30:44.520 30315 30589 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
04-07 18:30:44.520 30315 30589 E AndroidRuntime:        at android.support.v4.b.ae.a(SourceFile:115)
04-07 18:30:44.520 30315 30589 E AndroidRuntime:        at com.google.android.finsky.receivers.FlushLogsReceiver$FlushLogsService.onHandleIntent(SourceFile:185)
04-07 18:30:44.520 30315 30589 E AndroidRuntime:        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
04-07 18:30:44.520 30315 30589 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-07 18:30:44.520 30315 30589 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-07 18:30:44.520 30315 30589 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by aviraxp** [comment]
你确认你的系统支持待机？

**Comment by Vstory** [comment]
设置黑域开机自启和允许Root运行后，每次开机都会造成彩云天气，无法正常开机自启。而且，我并未将彩云天气加入黑域名单。
在不启用黑域开机自启时，彩云天气可以正常开机自启。但是，我在授权管理里允许了它开机自启了。

**Comment by Vstory** [comment]
我正是因为不确定是否支持待机，才来提问的啊。

**Comment by aviraxp** [comment]
哦，小米啊，不用想了，支持才怪

**Comment by Vstory** [comment]
原来系统不支持的原因啊，😅
