### ISSUE TITLE
一加2 系统魔趣6.0.1

### ISSUE THREAD

**Issue by 1900han** [liudongmiao/Brevent#4]
service.jar 成功打出来了,并且也导入到对应的手机文件夹里,打开黑域APP还是提示请给ROM打黑域补丁,这是bug吗?

**Comment by liudongmiao** [comment]
1. 黑域请不要放到系统里，目前只支持 `/data/app` 下的几个固定目录
2. 必要时，请删除 `services.odex`

**Comment by liudongmiao** [comment]
没有进一步消息，关闭 issue .
