### ISSUE TITLE
部分app在退出后黑域无法使其停止

### ISSUE THREAD

**Issue by asdfsega** [liudongmiao/Brevent#400]
墨墨背单词，mx播放器，目前就碰到这两个。

其他app如果在总揽中移除卡片后，黑域会自动使其停止，但是这两个app不会，在绿色守护中还是能看到这两个app在运行。

**Comment by liudongmiao** [comment]
类似问题不知道讨论多少次。

自己搜搜。

参考向导第四屏。

也可以等着别人来回答。

**Comment by liudongmiao** [comment]
#316 自己看吧
