### ISSUE TITLE
微信与QQ没有正常返回，返回退出后大概30秒被强杀。

### ISSUE THREAD

**Issue by ydj73** [liudongmiao/Brevent#401]
F:\platform-tools> adb -d shell setprop log.tag.BreventServer DEBUG

F:\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
04-08 16:18:03.430  6905  6905 D BreventServer: pause activity, tid: 3312, packa
geName: me.piebridge.brevent
04-08 16:18:08.784  6905  6905 D BreventServer: new intent, tid: 2545, packageNa
me: com.htc.launcher, pressed home: true, flags: 10200000
04-08 16:18:08.790  6905  6905 D BreventServer: pause activity, tid: 2545, packa
geName: com.tencent.mm
04-08 16:18:08.826  6905  6905 D BreventServer: resume activity, packageName: co
m.htc.launcher, launcher: com.htc.launcher, paused: com.tencent.mm, pressed home
: true
04-08 16:18:11.829  6905  6905 D BreventServer: check and brevent
04-08 16:18:11.890  6905  6905 D BreventServer: widgets: {com.htc.launcher, sk.m
ildev84.agendareminder}
04-08 16:18:11.890  6905  6905 D BreventServer: running: {com.github.shadowsocks
=5673, com.tencent.mm=6981, me.piebridge.brevent=6976, com.tencent.mobileqq=6969
}
04-08 16:18:11.890  6905  6905 D BreventServer: recent: {com.github.shadowsocks=
20289, com.htc.launcher=7690, com.speedsoftware.rootexplorer=13589, com.keramida
s.TitaniumBackup=13139, com.android.browser=3600, mark.via.gp=21222, com.noname8
1.lmt=15529, com.android.vending=5567, net.dinglisch.android.taskerm=20193, com.
tencent.mm=21597, com.htc.securitycenter=6507, com.htc.contacts=6430, com.htc.se
nse.mms=13526, me.piebridge.brevent=21592, com.htc.htcpowermanager=1321, com.goo
gle.android.gm=14263, com.htc.calendar=7771, com.lerist.ghosts=5606, com.htc.cam
era2=6144, com.tencent.qqpimsecure=6669, com.tencent.mobileqq=21584, com.android
.settings=13110, sk.mildev84.agendareminder=7729, com.htc.filemanager=2199, com.
htcmarket=1634, com.baidu.netdisk=6265}
04-08 16:18:11.905  6905  6905 D BreventServer: inactive for com.tencent.mm: 3,
timeout: 1800
04-08 16:18:11.906  6905  6905 D BreventServer: check later(background) for com.
tencent.mm: 1797
04-08 16:18:11.906  6905  6905 D BreventServer: inactive for com.tencent.mobileq
q: 15

**Comment by ydj73** [comment]
nse.mms=13464, me.piebridge.brevent=21530, com.htc.htcpowermanager=1259, com.goo
gle.android.gm=14201, com.htc.calendar=7709, com.lerist.ghosts=5544, com.htc.cam
era2=6082, com.tencent.qqpimsecure=6607, com.tencent.mobileqq=21597, com.android
.settings=13048, sk.mildev84.agendareminder=7667, com.htc.filemanager=2137, com.
htcmarket=1572, com.baidu.netdisk=6203}
04-08 16:19:13.619  6905  6905 D BreventServer: inactive for com.tencent.mobileq
q: 3, timeout: 1800
04-08 16:19:13.619  6905  6905 D BreventServer: check later(background) for com.
tencent.mobileqq: 1797
04-08 16:19:13.676  6905  6905 D BreventServer: com.htc.launcher depended by {co
m.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
04-08 16:19:13.676  6905  6905 D BreventServer: com.prassein.sit.htc depended by
 {com.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
04-08 16:19:13.676  6905  6905 D BreventServer: com.htc.htcpowermanager depended
 by {com.android.settings}
04-08 16:19:13.676  6905  6905 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gm}
04-08 16:19:13.676  6905  6905 D BreventServer: com.google.android.gms depended
by {com.github.shadowsocks, com.google.android.gm, com.android.settings}
04-08 16:19:13.676  6905  6905 D BreventServer: com.htc.backupreset depended by
{com.android.settings}
04-08 16:19:13.676  6905  6905 D BreventServer: service: {}
04-08 16:19:13.676  6905  6905 D BreventServer: back: {com.tencent.mm, com.tence
nt.mobileqq}
04-08 16:19:13.676  6905  6905 D BreventServer: blocking: {com.tencent.mm, com.t
encent.mobileqq}
04-08 16:19:13.676  6905  6905 D BreventServer: top: {}
04-08 16:19:13.676  6905  6905 D BreventServer: home: {com.htc.launcher, com.and
roid.systemui}
04-08 16:19:13.676  6905  6905 D BreventServer: current: com.htc.launcher
04-08 16:19:13.676  6905  6905 D BreventServer: unsafe: {}
04-08 16:19:13.677  6905  6905 D BreventServer: final blocking: {com.tencent.mm,
 com.tencent.mobileqq}
04-08 16:19:13.677  6905  6905 D BreventServer: notifications: {com.github.shado
wsocks=[98], com.noname81.lmt=[98]}
04-08 16:19:13.677  6905  6905 D BreventServer: noRecent: {}
04-08 16:19:13.677  6905  6905 D BreventServer: foreground service: {}
04-08 16:19:13.677  6905  6905 D BreventServer: gcm: {com.tencent.mm, com.mobile
srepublic.appy}
04-08 16:19:13.677  6905  6905 D BreventServer: sticky notification: {}
04-08 16:19:13.679  6905  6905 D BreventServer: Force stop com.tencent.mm(priori
ty service)
04-08 16:19:13.692  6905  6905 D BreventServer: Force stop com.tencent.mobileqq(
priority service)
04-08 16:19:13.693  6905  6905 D BreventServer: check again in 1797s
04-08 16:19:13.693  6905  6905 D BreventServer: check and brevent, took 162ms
04-08 16:20:10.488  6905  6905 D BreventServer: pause activity, tid: 1394, packa
geName: com.htc.launcher
04-08 16:20:13.265  6905  6905 D BreventServer: check and brevent
04-08 16:20:13.324  6905  6905 D BreventServer: widgets: {com.htc.launcher, sk.m
ildev84.agendareminder}
04-08 16:20:13.324  6905  6905 D BreventServer: running: {com.github.shadowsocks
=5673, me.piebridge.brevent=6976}
04-08 16:20:13.324  6905  6905 D BreventServer: recent: {com.github.shadowsocks=
20167, com.htc.launcher=7568, com.speedsoftware.rootexplorer=13467, com.keramida
s.TitaniumBackup=13017, com.android.browser=3478, mark.via.gp=21100, com.noname8
1.lmt=15407, com.android.vending=5445, net.dinglisch.android.taskerm=20071, com.
tencent.mm=21529, com.htc.securitycenter=6385, com.htc.contacts=6308, com.htc.se
nse.mms=13404, me.piebridge.brevent=21470, com.htc.htcpowermanager=1199, com.goo
gle.android.gm=14141, com.htc.calendar=7649, com.lerist.ghosts=5484, com.htc.cam
era2=6022, com.tencent.qqpimsecure=6547, com.tencent.mobileqq=21537, com.android
.settings=12988, sk.mildev84.agendareminder=7607, com.htc.filemanager=2077, com.
htcmarket=1512, com.baidu.netdisk=6143}
04-08 16:20:13.391  6905  6905 D BreventServer: com.htc.launcher depended by {co
m.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
04-08 16:20:13.391  6905  6905 D BreventServer: com.prassein.sit.htc depended by
 {com.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
04-08 16:20:13.391  6905  6905 D BreventServer: com.htc.htcpowermanager depended
 by {com.android.settings}
04-08 16:20:13.391  6905  6905 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gm}
04-08 16:20:13.391  6905  6905 D BreventServer: com.google.android.gms depended
by {com.github.shadowsocks, com.google.android.gm, com.android.settings}
04-08 16:20:13.391  6905  6905 D BreventServer: com.htc.backupreset depended by
{com.android.settings}
04-08 16:20:13.391  6905  6905 D BreventServer: service: {}
04-08 16:20:13.391  6905  6905 D BreventServer: back: {com.tencent.mm, com.tence
nt.mobileqq}
04-08 16:20:13.391  6905  6905 D BreventServer: blocking: {com.tencent.mm, com.t
encent.mobileqq}
04-08 16:20:13.392  6905  6905 D BreventServer: top: {}
04-08 16:20:13.392  6905  6905 D BreventServer: home: {com.htc.launcher, com.and
roid.systemui}
04-08 16:20:13.392  6905  6905 D BreventServer: current: com.htc.launcher
04-08 16:20:13.392  6905  6905 D BreventServer: unsafe: {}
04-08 16:20:13.392  6905  6905 D BreventServer: final blocking: {com.tencent.mm,
 com.tencent.mobileqq}
04-08 16:20:13.392  6905  6905 D BreventServer: notifications: {com.github.shado
wsocks=[98], com.noname81.lmt=[98]}
04-08 16:20:13.392  6905  6905 D BreventServer: noRecent: {}
04-08 16:20:13.392  6905  6905 D BreventServer: foreground service: {}
04-08 16:20:13.392  6905  6905 D BreventServer: gcm: {com.tencent.mm, com.mobile
srepublic.appy}
04-08 16:20:13.393  6905  6905 D BreventServer: sticky notification: {}
04-08 16:20:13.399  6905  6905 D BreventServer: Force stop com.tencent.mm(priori
ty service)
04-08 16:20:13.404  6905  6905 D BreventServer: Force stop com.tencent.mobileqq(
priority service)
04-08 16:20:13.406  6905  6905 D BreventServer: check again in 3600s
04-08 16:20:13.406  6905  6905 D BreventServer: check and brevent, took 141ms

F:\platform-tools>adb -d shell setprop log.tag.BreventServer \"\"

F:\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
04-08 16:18:54.921  6905  6905 D BreventServer: pause activity, tid: 2656, packa
geName: com.htc.launcher
04-08 16:18:57.437  6905  6905 D BreventServer: pause activity, tid: 3977, packa
geName: com.tencent.mm
04-08 16:18:57.454  6905  6905 D BreventServer: resume activity, packageName: co
m.tencent.mm, launcher: com.htc.launcher, paused: com.tencent.mm, pressed home:
false
04-08 16:19:02.690  6905  6905 D BreventServer: pause activity, tid: 3973, packa
geName: com.tencent.mm
04-08 16:19:02.728  6905  6905 D BreventServer: resume activity, packageName: co
m.htc.launcher, launcher: com.htc.launcher, paused: com.tencent.mm, pressed home
: false
04-08 16:19:05.731  6905  6905 D BreventServer: check and brevent
04-08 16:19:05.799  6905  6905 D BreventServer: widgets: {com.htc.launcher, sk.m
ildev84.agendareminder}
04-08 16:19:05.799  6905  6905 D BreventServer: running: {com.github.shadowsocks
=5673, com.tencent.mm=7035, me.piebridge.brevent=6976, com.tencent.mobileqq=6969
}
04-08 16:19:05.799  6905  6905 D BreventServer: recent: {com.github.shadowsocks=
20235, com.htc.launcher=7636, com.speedsoftware.rootexplorer=13535, com.keramida
s.TitaniumBackup=13085, com.android.browser=3546, mark.via.gp=21168, com.noname8
1.lmt=15475, com.android.vending=5513, net.dinglisch.android.taskerm=20139, com.
tencent.mm=21597, com.htc.securitycenter=6453, com.htc.contacts=6376, com.htc.se
nse.mms=13472, me.piebridge.brevent=21538, com.htc.htcpowermanager=1267, com.goo
gle.android.gm=14209, com.htc.calendar=7717, com.lerist.ghosts=5552, com.htc.cam
era2=6090, com.tencent.qqpimsecure=6615, com.tencent.mobileqq=21530, com.android
.settings=13056, sk.mildev84.agendareminder=7675, com.htc.filemanager=2145, com.
htcmarket=1580, com.baidu.netdisk=6211}
04-08 16:19:05.815  6905  6905 D BreventServer: inactive for com.tencent.mm: 3,
timeout: 1800
04-08 16:19:05.815  6905  6905 D BreventServer: check later(background) for com.
tencent.mm: 1797
04-08 16:19:05.815  6905  6905 D BreventServer: inactive for com.tencent.mobileq
q: 69, timeout: 1800
04-08 16:19:05.815  6905  6905 D BreventServer: check later(background) for com.
tencent.mobileqq: 1731
04-08 16:19:05.873  6905  6905 D BreventServer: com.htc.launcher depended by {co
m.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
04-08 16:19:05.873  6905  6905 D BreventServer: com.prassein.sit.htc depended by
 {com.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
04-08 16:19:05.873  6905  6905 D BreventServer: com.htc.htcpowermanager depended
 by {com.android.settings}
04-08 16:19:05.873  6905  6905 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gm}
04-08 16:19:05.873  6905  6905 D BreventServer: com.google.android.gms depended
by {com.github.shadowsocks, com.google.android.gm, com.android.settings}
04-08 16:19:05.873  6905  6905 D BreventServer: com.htc.backupreset depended by
{com.android.settings}
04-08 16:19:05.874  6905  6905 D BreventServer: service: {}
04-08 16:19:05.874  6905  6905 D BreventServer: back: {com.tencent.mm}
04-08 16:19:05.874  6905  6905 D BreventServer: blocking: {com.tencent.mm}
04-08 16:19:05.874  6905  6905 D BreventServer: top: {}
04-08 16:19:05.874  6905  6905 D BreventServer: home: {com.htc.launcher, com.and
roid.systemui}
04-08 16:19:05.874  6905  6905 D BreventServer: current: com.htc.launcher
04-08 16:19:05.874  6905  6905 D BreventServer: unsafe: {}
04-08 16:19:05.874  6905  6905 D BreventServer: final blocking: {com.tencent.mm}

04-08 16:19:05.874  6905  6905 D BreventServer: notifications: {com.github.shado
wsocks=[98], com.noname81.lmt=[98]}
04-08 16:19:05.874  6905  6905 D BreventServer: noRecent: {}
04-08 16:19:05.874  6905  6905 D BreventServer: foreground service: {}
04-08 16:19:05.874  6905  6905 D BreventServer: gcm: {com.tencent.mm, com.mobile
srepublic.appy}
04-08 16:19:05.874  6905  6905 D BreventServer: sticky notification: {}
04-08 16:19:05.887  6905  6905 D BreventServer: Force stop com.tencent.mm(priori
ty service)
04-08 16:19:05.889  6905  6905 D BreventServer: check again in 1731s
04-08 16:19:05.889  6905  6905 D BreventServer: check and brevent, took 157ms
04-08 16:19:08.975  6905  6905 D BreventServer: pause activity, tid: 3972, packa
geName: com.htc.launcher
04-08 16:19:08.977  6905  6905 D BreventServer: new intent, tid: 3972, packageNa
me: com.tencent.mobileqq, pressed home: false, flags: 10600000
04-08 16:19:08.999  6905  6905 D BreventServer: resume activity, packageName: co
m.tencent.mobileqq, launcher: com.htc.launcher, paused: com.htc.launcher, presse
d home: false
04-08 16:19:10.486  6905  6905 D BreventServer: pause activity, tid: 2957, packa
geName: com.tencent.mobileqq
04-08 16:19:10.526  6905  6905 D BreventServer: resume activity, packageName: co
m.htc.launcher, launcher: com.htc.launcher, paused: com.tencent.mobileqq, presse
d home: false
04-08 16:19:13.530  6905  6905 D BreventServer: check and brevent
04-08 16:19:13.603  6905  6905 D BreventServer: widgets: {com.htc.launcher, sk.m
ildev84.agendareminder}
04-08 16:19:13.603  6905  6905 D BreventServer: running: {com.github.shadowsocks
=5672, me.piebridge.brevent=6975, com.tencent.mobileqq=7042}
04-08 16:19:13.603  6905  6905 D BreventServer: recent: {com.github.shadowsocks=
20227, com.htc.launcher=7628, com.speedsoftware.rootexplorer=13527, com.keramida
s.TitaniumBackup=13077, com.android.browser=3538, mark.via.gp=21160, com.noname8
1.lmt=15467, com.android.vending=5505, net.dinglisch.android.taskerm=20131, com.
tencent.mm=21589, com.htc.securitycenter=6445, com.htc.contacts=6368, com.htc.se
nse.mms=13464, me.piebridge.brevent=21530, com.htc.htcpowermanager=1259, com.goo
gle.android.gm=14201, com.htc.calendar=7709, com.lerist.ghosts=5544, com.htc.cam
era2=6082, com.tencent.qqpimsecure=6607, com.tencent.mobileqq=21597, com.android
.settings=13048, sk.mildev84.agendareminder=7667, com.htc.filemanager=2137, com.
htcmarket=1572, com.baidu.netdisk=6203}
04-08 16:19:13.619  6905  6905 D BreventServer: inactive for com.tencent.mobileq
q: 3, timeout: 1800
04-08 16:19:13.619  6905  6905 D BreventServer: check later(background) for com.
tencent.mobileqq: 1797
04-08 16:19:13.676  6905  6905 D BreventServer: com.htc.launcher depended by {co
m.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
04-08 16:19:13.676  6905  6905 D BreventServer: com.prassein.sit.htc depended by
 {com.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
04-08 16:19:13.676  6905  6905 D BreventServer: com.htc.htcpowermanager depended
 by {com.android.settings}
04-08 16:19:13.676  6905  6905 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gm}
04-08 16:19:13.676  6905  6905 D BreventServer: com.google.android.gms depended
by {com.github.shadowsocks, com.google.android.gm, com.android.settings}
04-08 16:19:13.676  6905  6905 D BreventServer: com.htc.backupreset depended by
{com.android.settings}
04-08 16:19:13.676  6905  6905 D BreventServer: service: {}
04-08 16:19:13.676  6905  6905 D BreventServer: back: {com.tencent.mm, com.tence
nt.mobileqq}
04-08 16:19:13.676  6905  6905 D BreventServer: blocking: {com.tencent.mm, com.t
encent.mobileqq}
04-08 16:19:13.676  6905  6905 D BreventServer: top: {}
04-08 16:19:13.676  6905  6905 D BreventServer: home: {com.htc.launcher, com.and
roid.systemui}
04-08 16:19:13.676  6905  6905 D BreventServer: current: com.htc.launcher
04-08 16:19:13.676  6905  6905 D BreventServer: unsafe: {}
04-08 16:19:13.677  6905  6905 D BreventServer: final blocking: {com.tencent.mm,
 com.tencent.mobileqq}
04-08 16:19:13.677  6905  6905 D BreventServer: notifications: {com.github.shado
wsocks=[98], com.noname81.lmt=[98]}
04-08 16:19:13.677  6905  6905 D BreventServer: noRecent: {}
04-08 16:19:13.677  6905  6905 D BreventServer: foreground service: {}
04-08 16:19:13.677  6905  6905 D BreventServer: gcm: {com.tencent.mm, com.mobile
srepublic.appy}
04-08 16:19:13.677  6905  6905 D BreventServer: sticky notification: {}
04-08 16:19:13.679  6905  6905 D BreventServer: Force stop com.tencent.mm(priori
ty service)
04-08 16:19:13.692  6905  6905 D BreventServer: Force stop com.tencent.mobileqq(
priority service)
04-08 16:19:13.693  6905  6905 D BreventServer: check again in 1797s
04-08 16:19:13.693  6905  6905 D BreventServer: check and brevent, took 162ms
04-08 16:20:10.488  6905  6905 D BreventServer: pause activity, tid: 1394, packa
geName: com.htc.launcher
04-08 16:20:13.265  6905  6905 D BreventServer: check and brevent
04-08 16:20:13.324  6905  6905 D BreventServer: widgets: {com.htc.launcher, sk.m
ildev84.agendareminder}
04-08 16:20:13.324  6905  6905 D BreventServer: running: {com.github.shadowsocks
=5673, me.piebridge.brevent=6976}
04-08 16:20:13.324  6905  6905 D BreventServer: recent: {com.github.shadowsocks=
20167, com.htc.launcher=7568, com.speedsoftware.rootexplorer=13467, com.keramida
s.TitaniumBackup=13017, com.android.browser=3478, mark.via.gp=21100, com.noname8
1.lmt=15407, com.android.vending=5445, net.dinglisch.android.taskerm=20071, com.
tencent.mm=21529, com.htc.securitycenter=6385, com.htc.contacts=6308, com.htc.se
nse.mms=13404, me.piebridge.brevent=21470, com.htc.htcpowermanager=1199, com.goo
gle.android.gm=14141, com.htc.calendar=7649, com.lerist.ghosts=5484, com.htc.cam
era2=6022, com.tencent.qqpimsecure=6547, com.tencent.mobileqq=21537, com.android
.settings=12988, sk.mildev84.agendareminder=7607, com.htc.filemanager=2077, com.
htcmarket=1512, com.baidu.netdisk=6143}
04-08 16:20:13.391  6905  6905 D BreventServer: com.htc.launcher depended by {co
m.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
04-08 16:20:13.391  6905  6905 D BreventServer: com.prassein.sit.htc depended by
 {com.htc.sense.easyaccessservice, com.htc.lockscreen, com.android.systemui}
04-08 16:20:13.391  6905  6905 D BreventServer: com.htc.htcpowermanager depended
 by {com.android.settings}
04-08 16:20:13.391  6905  6905 D BreventServer: com.google.android.webview depen
ded by {com.google.android.gm}
04-08 16:20:13.391  6905  6905 D BreventServer: com.google.android.gms depended
by {com.github.shadowsocks, com.google.android.gm, com.android.settings}
04-08 16:20:13.391  6905  6905 D BreventServer: com.htc.backupreset depended by
{com.android.settings}
04-08 16:20:13.391  6905  6905 D BreventServer: service: {}
04-08 16:20:13.391  6905  6905 D BreventServer: back: {com.tencent.mm, com.tence
nt.mobileqq}
04-08 16:20:13.391  6905  6905 D BreventServer: blocking: {com.tencent.mm, com.t
encent.mobileqq}
04-08 16:20:13.392  6905  6905 D BreventServer: top: {}
04-08 16:20:13.392  6905  6905 D BreventServer: home: {com.htc.launcher, com.and
roid.systemui}
04-08 16:20:13.392  6905  6905 D BreventServer: current: com.htc.launcher
04-08 16:20:13.392  6905  6905 D BreventServer: unsafe: {}
04-08 16:20:13.392  6905  6905 D BreventServer: final blocking: {com.tencent.mm,
 com.tencent.mobileqq}
04-08 16:20:13.392  6905  6905 D BreventServer: notifications: {com.github.shado
wsocks=[98], com.noname81.lmt=[98]}
04-08 16:20:13.392  6905  6905 D BreventServer: noRecent: {}
04-08 16:20:13.392  6905  6905 D BreventServer: foreground service: {}
04-08 16:20:13.392  6905  6905 D BreventServer: gcm: {com.tencent.mm, com.mobile
srepublic.appy}
04-08 16:20:13.393  6905  6905 D BreventServer: sticky notification: {}
04-08 16:20:13.399  6905  6905 D BreventServer: Force stop com.tencent.mm(priori
ty service)
04-08 16:20:13.404  6905  6905 D BreventServer: Force stop com.tencent.mobileqq(
priority service)
04-08 16:20:13.406  6905  6905 D BreventServer: check again in 3600s
04-08 16:20:13.406  6905  6905 D BreventServer: check and brevent, took 141ms
04-08 16:22:16.909  6905  6905 D BreventServer: resume activity, packageName: co
m.htc.launcher, launcher: com.htc.launcher, paused: com.htc.launcher, pressed ho
me: false

F:\platform-tools>

**Comment by ydj73** [comment]
刚才安装1.0.5测试版才发现黑方法只剩下只停止了，看来是系统的问题？

**Comment by liudongmiao** [comment]
你手机不支持待机，所以非正常返回的话，会直接杀掉。
建议不要黑域它们。

**Comment by ydj73** [comment]
嗯，明白了，国行的系统还真是奇葩。
