### ISSUE TITLE
黑域可以与原来的“阻止运行”同时工作吗？

### ISSUE THREAD

**Issue by dotAge** [liudongmiao/Brevent#402]
我想，如果一旦手机需要重启，身边又没有PC可以用ADB启动黑域服务，那手机里那些APP岂不是进入“山中无老虎”的无政府状态？

**Comment by ydj73** [comment]
新版1.0可以在ROOT开启模式下重启自启动，因此个人觉得没必要在用阻止运行。

**Comment by dotAge** [comment]
刚才我设置过ROOT自启后重新启动手机，再次运行黑域，发现又被要求设置ROOT自启，连续点了两三次这个对话框才消失得以进入应用程序列表，不会每次都要这么玩吧？

**Comment by liudongmiao** [comment]
目前不对 ROOT 模式提供任何支持。
能用则用，不能用则不能用。
