### ISSUE TITLE
黑域1.0 权限问题

### ISSUE THREAD

**Issue by Zndroid** [liudongmiao/Brevent#403]
大大您好，我安装完黑域后用adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh发现提示权限拒绝。随后我查看发现是没有执行权限，我用RE管理器修改发现提示“权限修改失败，部分文件系统不支持修改所有者/用户组”。然后我在adb下重新挂载后也不能改变权限，用黑域的root也不能开启。黑域不是对非root用户都能用吗？现在我root了都不能用，希望大大能把sh文件换个路径，或者能不能写入的时候开启所有权限？

**Comment by bigbighill** [comment]
把  brevent.sh 放在群/sysyem/bin 目录  权限 755，
可使用第三方软件 开机运行这个shell script

**Comment by liudongmiao** [comment]
如何你确定你敲的是  sh /path/to/brevent.sh 而不是 /path/to/brevent.sh，然后提示没有权限，把手机扔了。

如果你可以改系统文件，建议直接复制 /path/to/libbrevent.so 到 /data/local/tmp/brevent
然后运行 /data/local/tmp/brevent

这个 sh 脚本，就是做这么一件事而已。

**Comment by Zndroid** [comment]
我直接复制的总不会错吧？而且，我还到所在目录下去查看文件权限的了，也直接运行了这个脚本，但是什么用都没有。
![sh](https://cloud.githubusercontent.com/assets/17594156/24834383/cd7adfc6-1d15-11e7-8139-3aa507413217.png)
复制到 /data/local/tmp/brevent然后运行 /data/local/tmp/brevent这个也不行呀，这样的话就同名了，根本复制不过去。

**Comment by liudongmiao** [comment]
安装最新测试版，然后看界面提示。

如果还不行，电脑上装 teamviewer，帐号密码发至 br @ piebridge.me
