### ISSUE TITLE
正在获取进程状态，请稍后......

### ISSUE THREAD

**Issue by wxhzd1987** [liudongmiao/Brevent#405]
昨天突然这样了，换了几个版本，重启了多次，还是没用。不知道怎么回事。
下面是服务日志：
D:\angler-n4f26t>adb -d logcat -d -b main -s BreventServer BreventLoader
04-09 17:08:14.161 10999 10999 D BreventLoader: loader path: /data/app/me.piebri
dge.brevent-1/base.apk
04-09 17:08:14.579 11061 11061 I BreventServer: classloader: dalvik.system.PathC
lassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],na
tiveLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib
64]]]
04-09 17:08:14.580 11061 11061 I BreventServer: Brevent Server 1.0-5-g4c4132b st
arted
04-09 17:08:14.589 11061 11061 I BreventServer: brevent user: 0, uid: 2000
04-09 17:08:14.590 11061 11061 I BreventServer: brevent data directory: /data/us
er_de/0/com.android.shell
04-09 17:08:14.758 11061 11061 I BreventServer: loading brevent list
04-09 17:08:14.758 11061 11061 I BreventServer: loading brevent conf
04-09 17:08:14.799 11061 11061 D BreventServer: check and brevent
04-09 17:08:14.897 11061 11061 I BreventServer: android process: android.process
.media, packages: [com.android.providers.media, com.android.providers.downloads]

04-09 17:08:14.900 11061 11061 I BreventServer: android process: android.process
.acore, packages: [com.android.providers.blockednumber, com.android.providers.us
erdictionary, com.android.providers.contacts]
04-09 17:08:14.998 11061 11061 D BreventServer: check and brevent, took 199ms
04-09 17:08:30.036 11061 11061 D BreventServer: sent first status
04-09 17:08:47.899 11061 11061 D BreventServer: checking feelgood
04-09 17:08:47.899 11061 11061 D BreventServer: check and brevent
04-09 17:08:47.900 11061 11123 D BreventServer: received feelgood
04-09 17:08:48.104 11061 11061 D BreventServer: check and brevent, took 204ms
04-09 17:08:50.648 11061 11061 D BreventServer: check and brevent
04-09 17:08:50.832 11061 11061 D BreventServer: check again in 3600s
04-09 17:08:50.832 11061 11061 D BreventServer: check and brevent, took 183ms
04-09 17:09:20.291 11061 11061 D BreventServer: checking feelgood
04-09 17:09:20.291 11061 11061 D BreventServer: check and brevent
04-09 17:09:20.292 11061 11123 D BreventServer: received feelgood
04-09 17:09:20.486 11061 11061 D BreventServer: check again in 3600s
04-09 17:09:20.486 11061 11061 D BreventServer: check and brevent, took 194ms

**Comment by liudongmiao** [comment]
日志无异常

**Comment by lijunle** [comment]
感觉最近很不稳定，“请重启黑域服务”那个界面一直闪，有些时候闪出来列表，但是大部分时候不行。日志目测无异常：

```
05-03 01:23:52.590 11009 11009 D BreventServer: checking feelgood
05-03 01:23:52.591 11009 11025 D BreventServer: received feelgood
05-03 01:24:10.663 11009 11009 D BreventServer: checking feelgood
05-03 01:24:10.665 11009 11025 D BreventServer: received feelgood
05-03 01:24:17.732 11009 11009 D BreventServer: checking feelgood
05-03 01:24:17.737 11009 11025 D BreventServer: received feelgood
05-03 01:24:20.733 11009 11009 D BreventServer: check and brevent
05-03 01:24:20.923 11009 11009 D BreventServer: check again in 3600s
05-03 01:24:20.923 11009 11009 D BreventServer: check and brevent, took 187ms
05-03 01:25:02.062 11009 11009 D BreventServer: check and brevent
05-03 01:25:02.231 11009 11009 D BreventServer: check again in 3600s
05-03 01:25:02.231 11009 11009 D BreventServer: check and brevent, took 168ms
05-03 01:25:31.373 11009 11009 D BreventServer: check and brevent
05-03 01:25:31.584 11009 11009 D BreventServer: check again in 3600s
05-03 01:25:31.584 11009 11009 D BreventServer: check and brevent, took 210ms
05-03 01:25:46.637 11009 11009 D BreventServer: checking feelgood
05-03 01:25:46.640 11009 11025 D BreventServer: received feelgood
05-03 01:26:06.820 11009 11009 D BreventServer: check and brevent
05-03 01:26:07.029 11009 11009 D BreventServer: check again in 3600s
05-03 01:26:07.029 11009 11009 D BreventServer: check and brevent, took 198ms
05-03 01:26:22.088 11009 11009 D BreventServer: checking feelgood
05-03 01:26:22.089 11009 11025 D BreventServer: received feelgood
05-03 01:27:07.099 11009 11009 D BreventServer: check and brevent
05-03 01:27:07.296 11009 11009 D BreventServer: Force stop com.baidu.BaiduMap(noRecent)
05-03 01:27:07.303 11009 11009 D BreventServer: Force stop com.flightmanager.view(noRecent)
05-03 01:27:07.305 11009 11009 D BreventServer: check again in 3600s
05-03 01:27:07.305 11009 11009 D BreventServer: check and brevent, took 205ms
05-03 01:27:22.360 11009 11009 D BreventServer: checking feelgood
05-03 01:27:22.363 11009 11025 D BreventServer: received feelgood
05-03 01:29:07.385 11009 11009 D BreventServer: check and brevent
05-03 01:29:07.628 11009 11009 D BreventServer: check again in 3600s
05-03 01:29:07.628 11009 11009 D BreventServer: check and brevent, took 240ms
05-03 01:29:22.744 11009 11009 D BreventServer: checking feelgood
05-03 01:29:22.758 11009 11025 D BreventServer: received feelgood
```
