### ISSUE TITLE
checking............cannot listen port

### ISSUE THREAD

**Issue by xieyiyi** [liudongmiao/Brevent#406]
发生在 Nexus 6，Android 7.1.1，CM 14.1 ROM上
以下是 logcat 日志

$ adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-10 10:16:00.000' -d
04-10 10:16:02.459 12538 12538 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9c in tid 12538 (brevent_server)
04-10 10:16:02.522 12539 12539 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-10 10:16:02.523 12539 12539 F DEBUG   : CM Version: '14.1-20161225-NIGHTLY-shamu'
04-10 10:16:02.523 12539 12539 F DEBUG   : Build fingerprint: 'google/shamu/shamu:7.0/NBD91U/3408911:user/release-keys'
04-10 10:16:02.523 12539 12539 F DEBUG   : Revision: '0'
04-10 10:16:02.523 12539 12539 F DEBUG   : ABI: 'arm'
04-10 10:16:02.523 12539 12539 F DEBUG   : pid: 12538, tid: 12538, name: brevent_server
>>> brevent_server <<<
04-10 10:16:02.523 12539 12539 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x9c
04-10 10:16:02.527 12539 12539 F DEBUG   : Abort message: 'art/runtime/gc/heap.cc:426] Check failed: main_mem_map_2.get() != nullptr Failed anonymous mmap(0x0, 805306368, 0x3, 0x2, 6, 0): Out of memory. See process maps in the log.'
04-10 10:16:02.527 12539 12539 F DEBUG   :     r0 00000000  r1 7464e26f  r2 00000000  r3 00000080
04-10 10:16:02.527 12539 12539 F DEBUG   :     r4 a62abcc0  r5 bed0bed0  r6 00000000  r7 00000000
04-10 10:16:02.527 12539 12539 F DEBUG   :     r8 a6223800  r9 00000001  sl a62f0280  fp 00000000
04-10 10:16:02.527 12539 12539 F DEBUG   :     ip a63eff80  sp bed0be90  lr a63eadc9  pc a60ce334  cpsr 60010030
04-10 10:16:02.548 12539 12539 F DEBUG   :
04-10 10:16:02.548 12539 12539 F DEBUG   : backtrace:
04-10 10:16:02.548 12539 12539 F DEBUG   :     #00 pc 0033d334  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEb+199)
04-10 10:16:02.548 12539 12539 F DEBUG   :     #01 pc 003245f5  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+372)
04-10 10:16:02.548 12539 12539 F DEBUG   :     #02 pc 0031b351  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
04-10 10:16:02.548 12539 12539 F DEBUG   :     #03 pc 000b526b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1134)
04-10 10:16:02.549 12539 12539 F DEBUG   :     #04 pc 001824ab  /system/lib/libart.so (_ZN3art2gc4HeapC1EjjjjddjjRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS_14InstructionSetENS0_13CollectorTypeESC_NS0_5space20LargeObjectSpaceTypeEjjjbjjbbbbbbbbbby+10730)
04-10 10:16:02.549 12539 12539 F DEBUG   :     #05 pc 0031d391  /system/lib/libart.so (_ZN3art7Runtime4InitEONS_18RuntimeArgumentMapE+6552)
04-10 10:16:02.549 12539 12539 F DEBUG   :     #06 pc 0031f3fb  /system/lib/libart.so (_ZN3art7Runtime6CreateERKNSt3__16vectorINS1_4pairINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKvEENS7_ISC_EEEEb+66)
04-10 10:16:02.549 12539 12539 F DEBUG   :     #07 pc 0023d95b  /system/lib/libart.so (JNI_CreateJavaVM+386)
04-10 10:16:02.549 12539 12539 F DEBUG   :     #08 pc 000690bb  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime7startVmEPP7_JavaVMPP7_JNIEnvb+2246)
04-10 10:16:02.549 12539 12539 F DEBUG   :     #09 pc 00069491  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+272)
04-10 10:16:02.549 12539 12539 F DEBUG   :     #10 pc 00001945  /system/bin/app_process32

04-10 10:16:02.549 12539 12539 F DEBUG   :     #11 pc 00016ca1  /system/lib/libc.so (__libc_init+48)
04-10 10:16:02.549 12539 12539 F DEBUG   :     #12 pc 00001564  /system/bin/app_process32

--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-10 10:16:00.000' -d -s BreventLoader BreventServer
04-10 10:16:01.646 12526 12526 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-10 10:16:02.777 12526 12526 E BreventLoader: worker 12538 exited on signal 11
04-10 10:16:02.777 12526 12526 D BreventLoader: signal arrived, update: 0
04-10 10:16:02.781 12508 12508 D BreventLoader: worker 12526 exited with status 0
--- brevent end ---

**Comment by liudongmiao** [comment]
找你的 rom 吧，升级 rom 看看。

**Comment by xieyiyi** [comment]
rom不可升级，为 CM 的最后一个版本的 ROM
CM 的 ROM 应该是用户量最大的第三方 ROM 了，如果有问题，此系列的 ROM 上的黑域可能都会存在问题

**Comment by liudongmiao** [comment]
我目标从来不包括支持第三方 ROM，能用则用，不用则拉倒。

我的moto，无论原版ROM，还是 lineage 上用得也挺好。

**Comment by xieyiyi** [comment]
OK，反正是你开发的，支不支持随你高兴啦

**Comment by liudongmiao** [comment]
本来就是黑科技，还是第三方 ROM，我更不愿意支持了。
直接这个错误，还是一个第三方的，当然不会去认真支持了。
