### ISSUE TITLE
可以手机端启动黑域服务吗？

### ISSUE THREAD

**Issue by luck-apple** [liudongmiao/Brevent#407]
手机端可以直接启动服务吗？如果在外边，手机由于一些原因重启了（比如没电关机，飞机上等），重启后电脑不在身边就无法启动黑域，如果手机端可以启动服务就很方便了。我试过手机端使用终端模拟器app，进入目标文件件下执行sh brevent.sh，提示please install me.piebridge.brevent（手机Google pixel 7.1.2，黑域Google play版本1.0）

**Comment by liudongmiao** [comment]
认真阅读向导第二屏，了解必要的权限。

1. 没电关机，有了黑域还用不了一天，带充电宝吧...

2. 飞机可以偷偷飞行模式(自行控制风险)，以及一年几次飞机，真正商旅人士还用得着黑域....

**Comment by yorks** [comment]
的确没办法了。 adb 指令andorid7 已经从 /system/bin/adb 里面移除了。如果还在的话还是能搞的。
