### ISSUE TITLE
在omni上无法正确识别是否支持应用待机

### ISSUE THREAD

**Issue by vvb2060** [liudongmiao/Brevent#409]
Omni 版本：7.1.1-20170402-angler-WEEKLY
未安装gapps，开发者选项中未启用应用无法切换，均有电池优化。
黑域方法三个全部显示，调整为只待机模式从未看见过已待机应用。
需要附上什么信息吗？

**Comment by aviraxp** [comment]
omni 不装 gapps 也可以待机。那个 bool 也是 true。说实话，我不知道咋回事。。。

**Comment by liudongmiao** [comment]
自己找 ROM 去，我肯定直接读那个值啊。

有些 ROM 厂商，胡乱优化，怪我咯。

你难道还是我出个东西，来更精准检查是否支持待机？

**Comment by vvb2060** [comment]
已解决，自己手贱

**Comment by liudongmiao** [comment]
我想知道，到底出了啥事
