### ISSUE TITLE
请问新版黑域开源吗？

### ISSUE THREAD

**Issue by t123yh** [liudongmiao/Brevent#41]
希望了解一下 libbootstrap.so 的工作以及程序原理。

**Comment by liudongmiao** [comment]
等更新完 UI 之后，会开源。

主要工作机制，可以直接参考命令的 am 指令。
libbootstrap.so 只是加了一层监听依赖而已。

**Comment by t123yh** [comment]
另外将 PrivBrevent.apk 复制到 /system/priv-app/PrivBrevent/ 之后，重启还是需要用 adb 执行 libbootstrap.so。这是 bug 吗？

**Comment by liudongmiao** [comment]
我并不对这个模式提供任何实质性支持，主要是我并不使用。

理论上，放到 /system/priv-app/ 会有 PrivBrevent 声明的那些权限，然后，开机广播以后，就会启动。但是，这个模式由于权限问题并不支持休眠，所以并不建议使用。应该使用其它的方式执行 libbootstrap.so 里的内容。

**Comment by t123yh** [comment]
那可以添加使用 root 权限执行 libbootstrap.lib 吗？

**Comment by t123yh** [comment]
libbootstrap.so 竟然是脚本，能否问一下为什么要用 so 做扩展名？

**Comment by liudongmiao** [comment]
为了你找到它。要不然，你还得解压出来...

能直接看到的，就只有 apk 和 so 了，而 apk 是个 zip 包，没法执行，能下手的就只有 so 了。
难道我说，请解压 apk，得到一个 sh，然后执行这个 sh?
