### ISSUE TITLE
对应用第一次黑域

### ISSUE THREAD

**Issue by VanXNF** [liudongmiao/Brevent#411]
对应用第一次黑域时，不显示黑域符号(那个禁止的符号)，实际也没有黑域(点击并不出现允许同步选项)，但是当点击不再黑域按钮后再次黑域该应用，就正常了。HTC 7.0

**Comment by liudongmiao** [comment]
HTC 的机器上，没有相应事件，后端不知道是否安装了这个应用。

这个没法解决。之前努力的解决，但效果也并不好。

**Comment by VanXNF** [comment]
好的，不过问题也不大，多点击一下就好了。

2017年4月11日 10:15，"Liu DongMiao" <notifications@github.com>写道：
