### ISSUE TITLE
Can not listen port

### ISSUE THREAD

**Issue by kencin** [liudongmiao/Brevent#412]
checking....brevent_server started, pid: 2160
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-11 11:12:27.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-11 11:12:27.000' -d -s BreventLoader BreventServer
04-11 11:12:28.630  2146  2146 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-11 11:12:29.167  2160  2160 W BreventServer: Can't find Settings.Secure.QS_TILES
04-11 11:12:29.172  2160  2160 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]]
04-11 11:12:29.172  2160  2160 I BreventServer: Brevent Server 1.0 started
04-11 11:12:29.177  2160  2160 W BreventServer: Can't find Settings.Secure.QS_TILES
04-11 11:12:29.180  2160  2160 I BreventServer: brevent user: 0, uid: 0
04-11 11:12:29.181  2160  2160 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
04-11 11:12:30.367  2160  2160 I BreventServer: loading brevent list04-11 11:12:30.371  2160  2160 I BreventServer: loading brevent conf04-11 11:12:30.396  2160  2160 E BreventServer: Can't open file
04-11 11:12:30.396  2160  2160 E BreventServer: java.io.IOException: No such file or directory
04-11 11:12:30.396  2160  2160 E BreventServer:         at java.io.UnixFileSystem.createFileExclusively0(Native Method)
04-11 11:12:30.396  2160  2160 E BreventServer:         at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
04-11 11:12:30.396  2160  2160 E BreventServer:         at java.io.File.createNewFile(File.java:948)
04-11 11:12:30.396  2160  2160 E BreventServer:         at java.io.File.createTempFile(File.java:1862)
04-11 11:12:30.396  2160  2160 E BreventServer:         at me.piebridge.brevent.server.d.a(HideApi.java:339)
04-11 11:12:30.396  2160  2160 E BreventServer:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:209)
04-11 11:12:30.396  2160  2160 E BreventServer:         at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1524)
04-11 11:12:30.396  2160  2160 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
04-11 11:12:30.396  2160  2160 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1582)
04-11 11:12:30.396  2160  2160 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-11 11:12:30.396  2160  2160 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java)
04-11 11:12:30.398  2160  2160 E BreventServer: Can't open file
04-11 11:12:30.398  2160  2160 E BreventServer: java.io.IOException: No such file or directory
04-11 11:12:30.398  2160  2160 E BreventServer:         at java.io.UnixFileSystem.createFileExclusively0(Native Method)
04-11 11:12:30.398  2160  2160 E BreventServer:         at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
04-11 11:12:30.398  2160  2160 E BreventServer:         at java.io.File.createNewFile(File.java:948)
04-11 11:12:30.398  2160  2160 E BreventServer:         at java.io.File.createTempFile(File.java:1862)
04-11 11:12:30.398  2160  2160 E BreventServer:         at me.piebridge.brevent.server.d.d(HideApi.java:318)
04-11 11:12:30.398  2160  2160 E BreventServer:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:217)
04-11 11:12:30.398  2160  2160 E BreventServer:         at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1524)
04-11 11:12:30.398  2160  2160 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
04-11 11:12:30.398  2160  2160 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1582)
04-11 11:12:30.398  2160  2160 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-11 11:12:30.398  2160  2160 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java)
04-11 11:12:30.398  2160  2160 E BreventServer: Can't be run as root, please open Brevent
04-11 11:12:30.451  2146  2146 E BreventLoader: worker 2160 exited with status 1
04-11 11:12:30.451  2146  2146 D BreventLoader: signal arrived, update: 0
04-11 11:12:30.453  2124  2124 D BreventLoader: worker 2146 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> 04-11 11:12:30.398 2160 2160 E BreventServer: Can't be run as root, please open Brevent

**Comment by kencin** [comment]
这期我第一次打开brevent啊，没有授权过root
