### ISSUE TITLE
希望您可以考虑一下对多用户的支持

### ISSUE THREAD

**Issue by XiaoyuJiao** [liudongmiao/Brevent#413]
如题😂😂😂

**Comment by amdth** [comment]
有多少人会使用多用户呢？你又准备付多少钱来支持laoda呢？

**Comment by liudongmiao** [comment]
吃力不讨好，我也不使用的事情，暂时没有计划。

**Comment by XiaoyuJiao** [comment]
哦

2017年4月12日 下午1:06，"Liu DongMiao" <notifications@github.com>写道：

吃力不讨好，我也不使用的事情，暂时没有计划。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/liudongmiao/Brevent/issues/413#issuecomment-293475065>,
or mute the thread

**Comment by amdth** [comment]
你回复的挺快的

**Comment by XiaoyuJiao** [comment]
嗯嗯，明白了。😂😂😂

2017年4月12日 下午1:15，"amdth" <notifications@github.com>写道：

**Comment by amdth** [comment]
既然明摆了就支持一下laoda呗！

**Comment by XiaoyuJiao** [comment]
😂😂😂马上去支持

2017年4月12日 下午1:20，"amdth" <notifications@github.com>写道：

**Comment by XiaoyuJiao** [comment]
因为你的错别字，现在支持的钱数变为计划支持的一半😏

2017年4月12日 下午1:20，"amdth" <notifications@github.com>写道：

**Comment by amdth** [comment]
因为我的错别字而让laoda来买单，有点说不过去吧！（这一次没有了，是不是该变为原来的二倍了呢？）

**Comment by XiaoyuJiao** [comment]
🙄🙄😌😌

2017年4月12日 下午1:30，"amdth" <notifications@github.com>写道：
