### ISSUE TITLE
作者大神，黑域异常退出，请帮忙分析

### ISSUE THREAD

**Issue by hubeixulu** [liudongmiao/Brevent#414]
一加3T，7.1.1
更新1.0版本后，运行一段时间，在点击进黑域，就会提示重新ADB，具体运行多长时间退出的就不知道了，
1.崩溃日志从4月9号开始，需要更多日志的话，我在提供
04-09 15:57:56.428  4677  4677 F libc    : "/data/user/0/com.baidu.input/files/libprocmox_v1_4.so": error: only position independent executables (PIE) are supported.
04-09 15:57:56.428  4677  4677 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 4677 (libprocmox_v1_4)
04-09 15:57:56.521  4681  4681 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-09 15:57:56.521  4681  4681 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus3/OnePlus3T:7.1.1/NMF26F/03102130:user/release-keys'
04-09 15:57:56.521  4681  4681 F DEBUG   : Revision: '0'
04-09 15:57:56.521  4681  4681 F DEBUG   : ABI: 'arm'
04-09 15:57:56.521  4681  4681 F DEBUG   : pid: 4677, tid: 4677, name: libprocmox_v1_4  >>> /data/user/0/com.baidu.input/files/libprocmox_v1_4.so <<<
04-09 15:57:56.521  4681  4681 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-09 15:57:56.521  4681  4681 F DEBUG   :     r0 00000000  r1 00001245  r2 00000006  r3 00000008
04-09 15:57:56.521  4681  4681 F DEBUG   :     r4 edc8058c  r5 00000006  r6 edc80534  r7 0000010c
04-09 15:57:56.521  4681  4681 F DEBUG   :     r8 edc1b000  r9 ff87b0a4  sl 00000000  fp edc14010
04-09 15:57:56.521  4681  4681 F DEBUG   :     ip 00000000  sp ff879d98  lr edc602cf  pc edc60d5c  cpsr 20070010
04-09 15:57:56.525  4681  4681 F DEBUG   : 
04-09 15:57:56.525  4681  4681 F DEBUG   : backtrace:
04-09 15:57:56.525  4681  4681 F DEBUG   :     #00 pc 00045d5c  /system/bin/linker (__dl_tgkill+12)
04-09 15:57:56.525  4681  4681 F DEBUG   :     #01 pc 000452cb  /system/bin/linker (__dl_pthread_kill+34)
04-09 15:57:56.526  4681  4681 F DEBUG   :     #02 pc 0003d62f  /system/bin/linker (__dl_raise+10)
04-09 15:57:56.526  4681  4681 F DEBUG   :     #03 pc 0003c0db  /system/bin/linker (__dl___libc_android_abort+34)
04-09 15:57:56.526  4681  4681 F DEBUG   :     #04 pc 0003b038  /system/bin/linker (__dl_abort+4)
04-09 15:57:56.526  4681  4681 F DEBUG   :     #05 pc 0003d12b  /system/bin/linker (__dl___libc_fatal+22)
04-09 15:57:56.526  4681  4681 F DEBUG   :     #06 pc 000098d1  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+2416)
04-09 15:57:56.526  4681  4681 F DEBUG   :     #07 pc 00008ecb  /system/bin/linker (__dl___linker_init+358)
04-09 15:57:56.526  4681  4681 F DEBUG   :     #08 pc 000027e8  /system/bin/linker (_start+4)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-09 17:39:47.587 15730 15730 E AndroidRuntime: java.lang.reflect.InvocationTargetException
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1582)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:276)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unknown package: cn.rpg8.abyteofpython
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1688)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1637)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4501)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at me.piebridge.brevent.server.d.a(HideApi.java:262)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:837)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:824)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:775)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:693)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.handleMessage(BreventServer.java:388)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1564)
04-09 17:39:47.587 15730 15730 E AndroidRuntime: 	... 4 more
04-09 17:39:47.588 15730 15730 E AndroidRuntime: Error reporting crash
04-09 17:39:47.588 15730 15730 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-09 17:39:47.588 15730 15730 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
04-09 17:39:47.588 15730 15730 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:651)
04-09 17:39:47.588 15730 15730 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5396)
04-09 17:39:47.588 15730 15730 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:111)
04-09 17:39:47.588 15730 15730 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
04-09 17:39:47.588 15730 15730 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-11 13:17:00.936 17849 17849 E AndroidRuntime: java.lang.reflect.InvocationTargetException
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1582)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:276)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unknown package: com.azure.authenticator
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1688)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1637)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4501)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at me.piebridge.brevent.server.d.a(HideApi.java:262)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:837)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:824)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:775)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:693)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.handleMessage(BreventServer.java:388)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1564)
04-11 13:17:00.936 17849 17849 E AndroidRuntime: 	... 4 more
04-11 13:17:00.937 17849 17849 E AndroidRuntime: Error reporting crash
04-11 13:17:00.937 17849 17849 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-11 13:17:00.937 17849 17849 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
04-11 13:17:00.937 17849 17849 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:651)
04-11 13:17:00.937 17849 17849 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5396)
04-11 13:17:00.937 17849 17849 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:111)
04-11 13:17:00.937 17849 17849 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
04-11 13:17:00.937 17849 17849 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)

**Comment by liudongmiao** [comment]
下个版本起，将处理这个异常。

#418

**Comment by hubeixulu** [comment]
已经下载1.0.5在用了，目前还没出现这个问题
