### ISSUE TITLE
柳大。我用的1.05。不能截取崩溃日志。只有服务日志

### ISSUE THREAD

**Issue by wgj1061744779** [liudongmiao/Brevent#415]
D:\hellxz\hybudingyjzz_jb51>adb -d logcat -d -b main -s BreventServer BreventLoa
der
04-12 09:00:02.821 17951 17951 D BreventServer: check and brevent
04-12 09:00:02.905 17951 17951 D BreventServer: widgets: {com.sonymobile.xperiaw
eather, com.sonyericsson.advancedwidget.clock}
04-12 09:00:02.905 17951 17951 D BreventServer: running: {com.android.vending=59
094, com.tencent.mm=59042, me.piebridge.brevent=59149, com.musjoy.pocketvpn=5862
7, com.android.settings=58593, com.sonymobile.android.dialer=59149}
04-12 09:00:02.905 17951 17951 D BreventServer: recent: {com.android.vending=354
5, com.tencent.mm=3493, me.piebridge.brevent=3600, com.musjoy.pocketvpn=3078, co
m.coolapk.market=3317, com.android.settings=3044}
04-12 09:00:02.917 17951 17951 D BreventServer: inactive for com.android.vending
: 55, timeout: 60
04-12 09:00:02.917 17951 17951 D BreventServer: check later(background) for com.
android.vending: 5
04-12 09:00:02.917 17951 17951 D BreventServer: inactive for com.musjoy.pocketvp
n: 522, timeout: 60
04-12 09:00:02.951 17951 17951 D BreventServer: com.google.android.webview depen
ded by {com.android.vending, com.musjoy.pocketvpn, com.google.android.gms, com.x
iaomi.hm.health}
04-12 09:00:02.951 17951 17951 D BreventServer: com.google.android.gms depended
by {com.sonymobile.lifelog, com.sonyericsson.home, com.android.vending, com.musj
oy.pocketvpn}
04-12 09:00:02.951 17951 17951 D BreventServer: service: {}
04-12 09:00:02.951 17951 17951 D BreventServer: back: {}
04-12 09:00:02.951 17951 17951 D BreventServer: blocking: {com.musjoy.pocketvpn}

04-12 09:00:02.951 17951 17951 D BreventServer: top: {me.piebridge.brevent}
04-12 09:00:02.951 17951 17951 D BreventServer: home: {com.sonyericsson.home, co
m.android.systemui}
04-12 09:00:02.951 17951 17951 D BreventServer: current: null
04-12 09:00:02.951 17951 17951 D BreventServer: unsafe: {}
04-12 09:00:02.951 17951 17951 D BreventServer: final blocking: {com.musjoy.pock
etvpn}
04-12 09:00:02.951 17951 17951 D BreventServer: notifications: {com.sonymobile.l
ifelog=[114], com.musjoy.pocketvpn=[98]}
04-12 09:00:02.951 17951 17951 D BreventServer: noRecent: {}
04-12 09:00:02.951 17951 17951 D BreventServer: foreground service: {}
04-12 09:00:02.951 17951 17951 D BreventServer: gcm: {}
04-12 09:00:02.951 17951 17951 D BreventServer: sticky notification: {com.musjoy
.pocketvpn}
04-12 09:00:02.951 17951 17951 D BreventServer: check and brevent, took 129ms
04-12 09:00:02.974 17951 17951 D BreventServer: checking feelgood

**Comment by liudongmiao** [comment]
日志正常。

**Comment by wgj1061744779** [comment]
.cargoshipmanual17crane, com.sonymobile.entrance, com.tencent.qt.qtl, com.musjoy
.pocketvpn, com.UCMobile, com.sonyericsson.extras.liveware, com.tencent.mobileqq
, com.sonyericsson.xhs, com.sonymobile.android.contacts, com.snda.wifilocating,
com.zhihu.android, com.coolapk.market, com.sonyericsson.android.camera, com.sony
ericsson.music, com.sonyericsson.trackid, com.netease.gmdl, com.tencent.karaoke,
 com.xfplay.play, com.smile.gifmaker, cn.goapk.market, com.baidu.netdisk, com.su
percell.clashofclans.anzhi, com.taobao.taobao, com.netease.cloudmusic, tv.danmak
u.bili, com.handsgo.jiakao.android, com.eg.android.AlipayGphone, cn.wps.moffice_
eng}
04-12 17:28:47.952 16155 16155 D BreventServer: priority: {}
04-12 17:28:47.952 16155 16155 I BreventServer: loading brevent conf
04-12 17:28:47.987 16155 16155 D BreventServer: notification_cancel_all, tag: 27
52, event: 4
04-12 17:28:47.990 16155 16155 D BreventServer: notification_panel_revealed, tag
: 27500, event: 6
04-12 17:28:47.990 16155 16155 D BreventServer: notification_panel_hidden, tag:
27501, event: 7
04-12 17:28:47.991 16155 16155 D BreventServer: am_new_intent, tag: 30003, event
: 8
04-12 17:28:47.991 16155 16155 D BreventServer: am_resume_activity, tag: 30007,
event: 2
04-12 17:28:47.992 16155 16155 D BreventServer: am_pause_activity, tag: 30013, e
vent: 9
04-12 17:28:47.992 16155 16155 D BreventServer: am_proc_start, tag: 30014, event
: 1
04-12 17:28:47.994 16155 16155 D BreventServer: am_switch_user, tag: 30041, even
t: 3
04-12 17:28:47.998 16155 16155 D BreventServer: screen_toggled, tag: 70000, even
t: 5
04-12 17:28:48.018 16155 16155 D BreventServer: check and brevent
04-12 17:28:48.150 16155 16155 D BreventServer: widgets: {com.sonymobile.xperiaw
eather, com.sonyericsson.advancedwidget.clock}
04-12 17:28:48.150 16155 16155 D BreventServer: running: {com.tencent.mm=80447,
com.UCMobile=89627, com.android.settings=89627}
04-12 17:28:48.150 16155 16155 D BreventServer: recent: {com.UCMobile=3552, com.
android.settings=3552}
04-12 17:28:48.157 16155 16155 I BreventServer: android process: android.process
.media, packages: [com.android.providers.media, com.android.providers.downloads]

04-12 17:28:48.167 16155 16155 D BreventServer: inactive for com.sankuai.meituan
: 0, timeout: 60
04-12 17:28:48.167 16155 16155 D BreventServer: inactive for com.sonymobile.entr
ance: 0, timeout: 60
04-12 17:28:48.168 16155 16155 D BreventServer: inactive for com.UCMobile: 47, t
imeout: 60
04-12 17:28:48.168 16155 16155 D BreventServer: check later(background) for com.
UCMobile: 13
04-12 17:28:48.168 16155 16155 D BreventServer: inactive for com.tencent.mobileq
q: 0, timeout: 60
04-12 17:28:48.168 16155 16155 D BreventServer: inactive for com.snda.wifilocati
ng: 0, timeout: 60
04-12 17:28:48.168 16155 16155 D BreventServer: inactive for com.coolapk.market:
 0, timeout: 60
04-12 17:28:48.168 16155 16155 D BreventServer: inactive for com.xfplay.play: 0,
 timeout: 60
04-12 17:28:48.168 16155 16155 D BreventServer: inactive for com.baidu.netdisk:
0, timeout: 60
04-12 17:28:48.168 16155 16155 D BreventServer: inactive for com.taobao.taobao:
0, timeout: 60
04-12 17:28:48.169 16155 16155 D BreventServer: inactive for com.eg.android.Alip
ayGphone: 0, timeout: 60
04-12 17:28:48.260 16155 16155 D BreventServer: com.google.android.webview depen
ded by {com.UCMobile, com.taobao.taobao, com.xiaomi.hm.health, com.eg.android.Al
ipayGphone}
04-12 17:28:48.260 16155 16155 D BreventServer: com.google.android.gms depended
by {com.sonymobile.lifelog, com.sonyericsson.home}
04-12 17:28:48.261 16155 16155 D BreventServer: service: {}
04-12 17:28:48.261 16155 16155 D BreventServer: back: {}
04-12 17:28:48.261 16155 16155 D BreventServer: blocking: {com.sankuai.meituan,
com.sonymobile.entrance, com.tencent.mobileqq, com.snda.wifilocating, com.coolap
k.market, com.xfplay.play, com.baidu.netdisk, com.taobao.taobao, com.eg.android.
AlipayGphone}
04-12 17:28:48.261 16155 16155 D BreventServer: top: {com.android.settings}
04-12 17:28:48.261 16155 16155 D BreventServer: home: {com.sonyericsson.home, co
m.android.systemui}
04-12 17:28:48.261 16155 16155 D BreventServer: current: null
04-12 17:28:48.261 16155 16155 D BreventServer: unsafe: {}
04-12 17:28:48.261 16155 16155 D BreventServer: final blocking: {com.sankuai.mei
tuan, com.sonymobile.entrance, com.tencent.mobileqq, com.snda.wifilocating, com.
coolapk.market, com.xfplay.play, com.baidu.netdisk, com.taobao.taobao, com.eg.an
droid.AlipayGphone}
04-12 17:28:48.261 16155 16155 D BreventServer: notifications: {com.sonymobile.l
ifelog=[114], com.UCMobile=[2]}
04-12 17:28:48.261 16155 16155 D BreventServer: noRecent: {com.sankuai.meituan,
com.sonymobile.entrance, com.tencent.mobileqq, com.snda.wifilocating, com.coolap
k.market, com.xfplay.play, com.baidu.netdisk, com.taobao.taobao, com.eg.android.
AlipayGphone}
04-12 17:28:48.261 16155 16155 D BreventServer: foreground service: {}
04-12 17:28:48.261 16155 16155 D BreventServer: gcm: {}
04-12 17:28:48.261 16155 16155 D BreventServer: sticky notification: {com.UCMobi
le}
04-12 17:28:48.266 16155 16155 D BreventServer: Force stop com.sankuai.meituan(f
orceStop)
04-12 17:28:48.283 16155 16155 D BreventServer: Force stop com.sonymobile.entran
ce(forceStop)
04-12 17:28:48.290 16155 16155 D BreventServer: Force stop com.tencent.mobileqq(
forceStop)
04-12 17:28:48.297 16155 16155 D BreventServer: Force stop com.snda.wifilocating
(forceStop)
04-12 17:28:48.312 16155 16155 D BreventServer: Force stop com.coolapk.market(fo
rceStop)
04-12 17:28:48.320 16155 16155 D BreventServer: Force stop com.xfplay.play(force
Stop)
04-12 17:28:48.329 16155 16155 D BreventServer: Force stop com.baidu.netdisk(for
ceStop)
04-12 17:28:48.341 16155 16155 D BreventServer: Force stop com.taobao.taobao(for
ceStop)
04-12 17:28:48.348 16155 16155 D BreventServer: Force stop com.eg.android.Alipay
Gphone(forceStop)
04-12 17:28:48.349 16155 16155 D BreventServer: check and brevent, took 330ms
04-12 17:28:48.350 16155 16155 D BreventServer: check and brevent
04-12 17:28:48.464 16155 16155 D BreventServer: widgets: {com.sonymobile.xperiaw
eather, com.sonyericsson.advancedwidget.clock}
04-12 17:28:48.464 16155 16155 D BreventServer: running: {com.tencent.mm=80447,
com.UCMobile=89627, com.android.settings=89627}
04-12 17:28:48.464 16155 16155 D BreventServer: recent: {com.UCMobile=3552, com.
android.settings=3552}
04-12 17:28:48.474 16155 16155 D BreventServer: inactive for com.UCMobile: 47, t
imeout: 60
04-12 17:28:48.474 16155 16155 D BreventServer: check later(background) for com.
UCMobile: 13
04-12 17:28:48.517 16155 16155 D BreventServer: com.google.android.webview depen
ded by {com.UCMobile, com.xiaomi.hm.health}
04-12 17:28:48.517 16155 16155 D BreventServer: com.google.android.gms depended
by {com.sonymobile.lifelog, com.sonyericsson.home}
04-12 17:28:48.517 16155 16155 D BreventServer: service: {}
04-12 17:28:48.517 16155 16155 D BreventServer: back: {}
04-12 17:28:48.517 16155 16155 D BreventServer: blocking: {}
04-12 17:28:48.517 16155 16155 D BreventServer: top: {com.android.settings}
04-12 17:28:48.517 16155 16155 D BreventServer: home: {com.sonyericsson.home, co
m.android.systemui}
04-12 17:28:48.517 16155 16155 D BreventServer: current: null
04-12 17:28:48.517 16155 16155 D BreventServer: unsafe: {}
04-12 17:28:48.517 16155 16155 D BreventServer: final blocking: {}
04-12 17:28:48.517 16155 16155 D BreventServer: notifications: {com.sonymobile.l
ifelog=[114], com.UCMobile=[2]}
04-12 17:28:48.517 16155 16155 D BreventServer: noRecent: {}
04-12 17:28:48.517 16155 16155 D BreventServer: foreground service: {}
04-12 17:28:48.517 16155 16155 D BreventServer: sticky notification: {com.UCMobi
le}
04-12 17:28:48.517 16155 16155 D BreventServer: check and brevent, took 167ms
04-12 17:28:48.537 16155 16155 D BreventServer: sent first status
04-12 17:29:02.623 16258 16258 W BreventServer: Can't find Settings.Secure.QS_TI
LES
04-12 17:29:02.695 16155 16155 D BreventServer: check and brevent
04-12 17:29:02.814 16155 16155 D BreventServer: widgets: {com.sonymobile.xperiaw
eather, com.sonyericsson.advancedwidget.clock}
04-12 17:29:02.814 16155 16155 D BreventServer: running: {com.tencent.mm=80448,
me.piebridge.brevent=89689, com.UCMobile=89627, com.android.settings=89687}
04-12 17:29:02.814 16155 16155 D BreventServer: recent: {me.piebridge.brevent=36
00, com.UCMobile=3538}
04-12 17:29:02.828 16155 16155 D BreventServer: inactive for com.UCMobile: 62, t
imeout: 60
04-12 17:29:02.881 16155 16155 D BreventServer: com.google.android.webview depen
ded by {com.UCMobile, com.xiaomi.hm.health}
04-12 17:29:02.881 16155 16155 D BreventServer: com.google.android.gms depended
by {com.sonymobile.lifelog, com.sonyericsson.home}
04-12 17:29:02.881 16155 16155 D BreventServer: service: {}
04-12 17:29:02.881 16155 16155 D BreventServer: back: {}
04-12 17:29:02.881 16155 16155 D BreventServer: blocking: {com.UCMobile}
04-12 17:29:02.881 16155 16155 D BreventServer: top: {me.piebridge.brevent}
04-12 17:29:02.881 16155 16155 D BreventServer: home: {com.sonyericsson.home, co
m.android.systemui}
04-12 17:29:02.881 16155 16155 D BreventServer: current: null
04-12 17:29:02.881 16155 16155 D BreventServer: unsafe: {}
04-12 17:29:02.881 16155 16155 D BreventServer: final blocking: {com.UCMobile}
04-12 17:29:02.881 16155 16155 D BreventServer: notifications: {com.sonymobile.l
ifelog=[114], com.UCMobile=[2]}
04-12 17:29:02.881 16155 16155 D BreventServer: noRecent: {}
04-12 17:29:02.881 16155 16155 D BreventServer: foreground service: {}
04-12 17:29:02.881 16155 16155 D BreventServer: gcm: {}
04-12 17:29:02.881 16155 16155 D BreventServer: sticky notification: {com.UCMobi
le}
04-12 17:29:02.882 16155 16155 D BreventServer: check and brevent, took 186ms
04-12 17:29:02.905 16155 16155 D BreventServer: checking feelgood
04-12 17:29:44.938 16155 16155 E BreventServer: Don't receive answer from univer
se
04-12 17:31:20.587 16977 16977 W BreventServer: Can't find Settings.Secure.QS_TI
LES
04-12 17:31:20.592 16977 16977 I BreventServer: classloader: dalvik.system.PathC
lassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-2/base.apk"],na
tiveLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib
64]]]
04-12 17:31:20.593 16977 16977 I BreventServer: Brevent Server 1.0-5-g4c4132b st
arted
04-12 17:31:20.599 16977 16977 W BreventServer: Can't find Settings.Secure.QS_TI
LES
04-12 17:31:20.601 16977 16977 I BreventServer: brevent user: 0, uid: 2000
04-12 17:31:20.602 16977 16977 I BreventServer: brevent data directory: /data/us
er_de/0/com.android.shell
04-12 17:31:20.796 16977 16977 I BreventServer: loading brevent list
04-12 17:31:20.798 16977 16977 I BreventServer: load /data/user_de/0/com.android
.shell/me.piebridge.brevent.list, size: 41
04-12 17:31:20.798 16977 16977 D BreventServer: brevent: {com.google.android.you
tube, com.sonymobile.sketch, com.google.android.googlequicksearchbox, com.tencen
t.tmgp.sgame, com.tg.ambulancehelicopterheroes, com.sankuai.meituan, com.cmcm.li
ve, com.huang.lgplayer, com.android.vending, com.mobisystems.fileman, com.xunlei
.downloadprovider, com.sonymobile.backgrounddefocus, com.android.ccz.kkk, com.tg
.cargoshipmanual17crane, com.sonymobile.entrance, com.tencent.qt.qtl, com.musjoy
.pocketvpn, com.UCMobile, com.sonyericsson.extras.liveware, com.tencent.mobileqq
, com.sonyericsson.xhs, com.sonymobile.android.contacts, com.snda.wifilocating,
com.zhihu.android, com.coolapk.market, com.sonyericsson.android.camera, com.sony
ericsson.music, com.sonyericsson.trackid, com.netease.gmdl, com.tencent.karaoke,
 com.xfplay.play, com.smile.gifmaker, cn.goapk.market, com.baidu.netdisk, com.su
percell.clashofclans.anzhi, com.taobao.taobao, com.netease.cloudmusic, tv.danmak
u.bili, com.handsgo.jiakao.android, com.eg.android.AlipayGphone, cn.wps.moffice_
eng}
04-12 17:31:20.798 16977 16977 D BreventServer: priority: {}
04-12 17:31:20.798 16977 16977 I BreventServer: loading brevent conf
04-12 17:31:20.826 16977 16977 D BreventServer: notification_cancel_all, tag: 27
52, event: 4
04-12 17:31:20.829 16977 16977 D BreventServer: notification_panel_revealed, tag
: 27500, event: 6
04-12 17:31:20.829 16977 16977 D BreventServer: notification_panel_hidden, tag:
27501, event: 7
04-12 17:31:20.829 16977 16977 D BreventServer: am_new_intent, tag: 30003, event
: 8
04-12 17:31:20.830 16977 16977 D BreventServer: am_resume_activity, tag: 30007,
event: 2
04-12 17:31:20.831 16977 16977 D BreventServer: am_pause_activity, tag: 30013, e
vent: 9
04-12 17:31:20.831 16977 16977 D BreventServer: am_proc_start, tag: 30014, event
: 1
04-12 17:31:20.833 16977 16977 D BreventServer: am_switch_user, tag: 30041, even
t: 3
04-12 17:31:20.838 16977 16977 D BreventServer: screen_toggled, tag: 70000, even
t: 5
04-12 17:31:20.845 16977 16977 D BreventServer: check and brevent
04-12 17:31:20.958 16977 16977 D BreventServer: widgets: {com.sonymobile.xperiaw
eather, com.sonyericsson.advancedwidget.clock}
04-12 17:31:20.958 16977 16977 D BreventServer: running: {com.tencent.mm=80447,
me.piebridge.brevent=89785, com.UCMobile=89627, com.android.settings=89687}
04-12 17:31:20.958 16977 16977 D BreventServer: recent: {me.piebridge.brevent=35
58, com.UCMobile=3400}
04-12 17:31:20.966 16977 16977 I BreventServer: android process: android.process
.media, packages: [com.android.providers.media, com.android.providers.downloads]

04-12 17:31:20.972 16977 16977 D BreventServer: inactive for com.UCMobile: 200,
timeout: 60
04-12 17:31:20.972 16977 16977 D BreventServer: inactive for com.coolapk.market:
 0, timeout: 60
04-12 17:31:21.037 16977 16977 D BreventServer: com.google.android.webview depen
ded by {com.UCMobile, com.xiaomi.hm.health}
04-12 17:31:21.037 16977 16977 D BreventServer: com.google.android.gms depended
by {com.sonymobile.lifelog, com.sonyericsson.home}
04-12 17:31:21.037 16977 16977 D BreventServer: service: {}
04-12 17:31:21.037 16977 16977 D BreventServer: back: {}
04-12 17:31:21.037 16977 16977 D BreventServer: blocking: {com.UCMobile, com.coo
lapk.market}
04-12 17:31:21.037 16977 16977 D BreventServer: top: {me.piebridge.brevent}
04-12 17:31:21.037 16977 16977 D BreventServer: home: {com.sonyericsson.home, co
m.android.systemui}
04-12 17:31:21.037 16977 16977 D BreventServer: current: null
04-12 17:31:21.037 16977 16977 D BreventServer: unsafe: {}
04-12 17:31:21.037 16977 16977 D BreventServer: final blocking: {com.UCMobile, c
om.coolapk.market}
04-12 17:31:21.037 16977 16977 D BreventServer: notifications: {com.sonymobile.l
ifelog=[114], com.UCMobile=[2]}
04-12 17:31:21.037 16977 16977 D BreventServer: noRecent: {com.coolapk.market}
04-12 17:31:21.037 16977 16977 D BreventServer: foreground service: {}
04-12 17:31:21.037 16977 16977 D BreventServer: gcm: {}
04-12 17:31:21.037 16977 16977 D BreventServer: sticky notification: {com.UCMobi
le}
04-12 17:31:21.042 16977 16977 D BreventServer: Force stop com.coolapk.market(fo
rceStop)
04-12 17:31:21.043 16977 16977 D BreventServer: check and brevent, took 196ms
04-12 17:31:21.044 16977 16977 D BreventServer: check and brevent
04-12 17:31:21.143 16977 16977 D BreventServer: widgets: {com.sonymobile.xperiaw
eather, com.sonyericsson.advancedwidget.clock}
04-12 17:31:21.143 16977 16977 D BreventServer: running: {com.tencent.mm=80447,
me.piebridge.brevent=89785, com.UCMobile=89627, com.android.settings=89687}
04-12 17:31:21.143 16977 16977 D BreventServer: recent: {me.piebridge.brevent=35
57, com.UCMobile=3399}
04-12 17:31:21.154 16977 16977 D BreventServer: inactive for com.UCMobile: 200,
timeout: 60
04-12 17:31:21.200 16977 16977 D BreventServer: com.google.android.webview depen
ded by {com.UCMobile, com.xiaomi.hm.health}
04-12 17:31:21.200 16977 16977 D BreventServer: com.google.android.gms depended
by {com.sonymobile.lifelog, com.sonyericsson.home}
04-12 17:31:21.200 16977 16977 D BreventServer: service: {}
04-12 17:31:21.200 16977 16977 D BreventServer: back: {}
04-12 17:31:21.200 16977 16977 D BreventServer: blocking: {com.UCMobile}
04-12 17:31:21.200 16977 16977 D BreventServer: top: {me.piebridge.brevent}
04-12 17:31:21.200 16977 16977 D BreventServer: home: {com.sonyericsson.home, co
m.android.systemui}
04-12 17:31:21.200 16977 16977 D BreventServer: current: null
04-12 17:31:21.200 16977 16977 D BreventServer: unsafe: {}
04-12 17:31:21.200 16977 16977 D BreventServer: final blocking: {com.UCMobile}
04-12 17:31:21.200 16977 16977 D BreventServer: notifications: {com.sonymobile.l
ifelog=[114], com.UCMobile=[2]}
04-12 17:31:21.200 16977 16977 D BreventServer: noRecent: {}
04-12 17:31:21.200 16977 16977 D BreventServer: foreground service: {}
04-12 17:31:21.200 16977 16977 D BreventServer: gcm: {}
04-12 17:31:21.200 16977 16977 D BreventServer: sticky notification: {com.UCMobi
le}
04-12 17:31:21.200 16977 16977 D BreventServer: check and brevent, took 146ms
04-12 17:31:21.225 16977 16977 D BreventServer: sent first status

新截取的

**Comment by liudongmiao** [comment]
> 04-12 17:29:44.938 16155 16155 E BreventServer: Don't receive answer from universe

黑域依赖系统的日志。虽然现在收不到自己发的也没关系，但这个条件目前不会去掉。

请确定你的系统没有关闭事件日志。

**Comment by wgj1061744779** [comment]
柳大。可以用了！我的系统日志改成16M就可以用了
