### ISSUE TITLE
卸载后重新安装就很难打开

### ISSUE THREAD

**Issue by usc** [liudongmiao/Brevent#416]
play版本安装的，后发现有些问题，就卸载了（能够使用），重新安装后，使用adb很难再成功使用了，好像看日志是正常的

log
04-12 09:31:45.307 12140 12140 D BreventServer: sent first status
04-12 09:32:03.370 12140 12140 D BreventServer: checking feelgood
04-12 09:32:03.372 12140 12149 D BreventServer: received feelgood
04-12 09:32:21.303 12140 12140 D BreventServer: checking feelgood
04-12 09:32:21.304 12140 12149 D BreventServer: received feelgood
04-12 09:32:21.987 12129 12129 E BreventLoader: worker 12140 exited on signal 15
04-12 09:32:21.987 12129 12129 D BreventLoader: signal arrived, update: 0
04-12 09:32:22.471 12961 12961 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-12 09:32:22.910 12981 12981 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]]
04-12 09:32:22.910 12981 12981 I BreventServer: Brevent Server 1.0 started
04-12 09:32:22.921 12981 12981 I BreventServer: brevent user: 0, uid: 2000
04-12 09:32:22.922 12981 12981 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
04-12 09:32:23.111 12981 12981 I BreventServer: loading brevent list
04-12 09:32:23.111 12981 12981 I BreventServer: loading brevent conf
04-12 09:32:23.172 12981 12981 D BreventServer: check and brevent
04-12 09:32:23.229 12981 12981 I BreventServer: android process: android.process.media, packages: [com.android.providers.media, com.android.providers.downloads]
04-12 09:32:23.237 12981 12981 I BreventServer: android process: android.process.acore, packages: [com.android.providers.blockednumber, com.android.providers.userdictionary, com.android.providers.contacts]
04-12 09:32:23.349 12981 12981 D BreventServer: check and brevent, took 176ms
04-12 09:32:38.408 12981 12981 D BreventServer: sent first status
04-12 09:32:54.527 12981 12981 D BreventServer: checking feelgood
04-12 09:32:54.529 12981 13013 D BreventServer: received feelgood

**Comment by liudongmiao** [comment]
日志正常。
