### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by Lv-devil7** [liudongmiao/Brevent#417]
索尼z5p，安卓6.0
1.刚下载安装后有允许fcm消息的选项，一段时间之后这个选项就消失了，并且直到现在还没有出现？
2.优化back键功能，似乎偶尔可以触发偶尔不行？表现为有时候打开app，back后黑域里计时消失，一段时间后stopped，有时候却仍然计时，并且不会被stopped
3.允许同步后仍然无法接收微信，QQ，微博，Google allo等的推送消息？请问一下允许同步功能会在app被stopped后允许哪些行为？

**Comment by liudongmiao** [comment]
1. 说明你机器不支持。下个版本起，将提前这个检查。

2. 即使优化，有些放到后台的也是会显示时间。非正常 Back 以后，这些应用还是会显示时间的，没有办法处理。但是会提前黑域它。

3. 你说了，你机器不支持 1 ，所以不支持 FCM。正常的话，黑域强行停止以后，打开应用详情，还可以看到可以继续”强行停止“。此外，可以参照商店详情的描述。

**Comment by Lv-devil7** [comment]
那么如果我希望接受推送消息的话，现在的办法就是1.不加入黑域，或者2.加入黑域后在最近的任务里一直不把他划去让他始终处于running或者standby状态对吗？

另外还有一个就是我设置了standby上限1h，可是昨天晚上两个app一直到我早上醒来看他还是处于standby，大概有7 8个小时吧，请问这个是因为我开了允许同步的原因吗？

**Comment by CVN-77** [comment]
建议在相关选项写明不支持，向导也可加些说明，此类问题（比如小米没有待机等）可能会少一些。

**Comment by liudongmiao** [comment]
是否能收到 FCM 取决于以下几点：
1. 设备是否安装了 GMS
2. 应用是否接入 FCM，并且通过 GMS 注册
3. 应用当前是否处于非停止状态

但是，如果你不强行停止它，你又无法准确判断，它是自己获取的消息，还是 FCM 推送的。

加上国内，访问 FCM 困难，不要纠结了。
不过真的不用这么纠结，放弃吧。

允许同步有其它的处理策略，具体看商店详情的描述。

**Comment by Lv-devil7** [comment]
感谢聚聚的耐心回答:)

**Comment by ydj73** [comment]
哈哈，终于看到一个和我一样纠结的人。

**Comment by Lv-devil7** [comment]
大佬刚才我又发现好像有一个应用触发了fcm…是个游戏所以我很确定退出的时候是肯定直接最近任务里划去的，然后刚才又推送了每天的消息…我开了这个游戏的允许同步…不过已经stopped了应该不会是允许同步的原因。这是否可以说明我机器支持fcm呢…

**Comment by ydj73** [comment]
一个简单判断的方法，拨号界面，*#*#426#*#*，如果能进入谷歌服务的界面，则可能支持，否则，则可能是支持的。2017年4月12日 16:34，Lv-devil7 <notifications@github.com>写道：大佬刚才我又发现好像有一个应用触发了fcm…是个游戏所以我很确定退出的时候是肯定直接最近任务里划去的，然后刚才又推送了每天的消息…我开了这个游戏的允许同步…不过已经stopped了应该不会是允许同步的原因。这是否可以说明我机器支持fcm呢…

**Comment by ydj73** [comment]
笔误，要没反应，则肯定是支持。2017年4月12日 16:34，Lv-devil7 <notifications@github.com>写道：大佬刚才我又发现好像有一个应用触发了fcm…是个游戏所以我很确定退出的时候是肯定直接最近任务里划去的，然后刚才又推送了每天的消息…我开了这个游戏的允许同步…不过已经stopped了应该不会是允许同步的原因。这是否可以说明我机器支持fcm呢…

**Comment by ydj73** [comment]
晕，老漏一个不字2017年4月12日 16:34，Lv-devil7 <notifications@github.com>写道：大佬刚才我又发现好像有一个应用触发了fcm…是个游戏所以我很确定退出的时候是肯定直接最近任务里划去的，然后刚才又推送了每天的消息…我开了这个游戏的允许同步…不过已经stopped了应该不会是允许同步的原因。这是否可以说明我机器支持fcm呢…
