### ISSUE TITLE
请教柳大一个问题

### ISSUE THREAD

**Issue by LornBin** [liudongmiao/Brevent#420]
柳大，我目前的是测试版（1.0+14）。系统是lineage14.1，自己刷的gapp  pico包，play里面搜索不到黑域。黑域底部也只是显示支付宝，没有play。高级功能全是灰色的（本想来几刀可是没法就支付宝了一点，也不想用play捐，给你3刀实际得到2刀）。改了配置文件，可以自启，但是灰色显示的还是关闭没有开启。
之前用酷安里的应用安Google时，play里有显示。

**Comment by liudongmiao** [comment]
连上 VPN，打开 Play 商店，放后台看看。

对于安装了 Play 商店的朋友，我限制比较严一点，必须要通过 Play 商店捐赠才能开启实验性功能。
目前实验性功能有以下几个：
1. 优化 VPN，因为这个意义不大，绝大部分都可以通过“允许同步”+通知来完成
2. 允许 ROOT 运行以及开机自启，这个只是为了解决自启问题，没有它，也可以点击 7 次 Back 来完成

至于，有能力安装 Play 商店（或者自己就是海淘）的人，肯定有办法搞定 Play 商店购买问题。
如果这样的人搞不定 Play 商店购买问题，还要使用不太重要的“实验性”功能，不是我的目标用户。

**Comment by bigbighill** [comment]
我是play高店捐赠的经常在设置里显示没有捐赠，必须运行play 商店后才显示已捐赠。

**Comment by liudongmiao** [comment]
那说明，你还有其它同类软件（或者系统自带）阻止 Play 商店被唤醒。
