### ISSUE TITLE
这个命令不知什么意思

### ISSUE THREAD

**Issue by JunC1212** [liudongmiao/Brevent#422]
C:\Users\lovej\Downloads\platform-tools-latest-windows>adb -d logcat -d -b main -s BreventServer BreventLoader
Unable to open log device 'main'

没办法看日志

**Comment by liudongmiao** [comment]
你系统上，没有 main 这个日志，这是不正常的。去开发者选项里看看，没有禁用日志。

黑域高度依赖日志，没有日志的话，没法运行。

**Comment by JunC1212** [comment]
开发者选项里看哪个开关
