### ISSUE TITLE
更新1.0.1后出现的问题，貌似外置卡读写和网络管理出问题了

### ISSUE THREAD

**Issue by ydj73** [liudongmiao/Brevent#425]
具体表现：
1、GOOGLE音乐我已经用钛备份冻结，但提示停止运行。
2、钛备份我的正版验证key在外置卡，打开钛备份时意外的出现提示正在验证授权，但是更新之前重来没有过。
3、网易云音乐经常出现卡顿，貌似没有网络连接一样，HTC主题程序与服务器通讯出现同样问题，重启后正常……，因为其他程序访问网络正常，我只是怀疑。
3、我是菜鸟，无法判断这是系统问题还是其他问题。附上崩溃日志：
hread$H.handleMessage(ActivityThread.java)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at android.os.Handler.di
spatchMessage(Handler.java)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at android.os.Looper.loo
p(Looper.java)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at android.app.ActivityT
hread.main(ActivityThread.java)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at java.lang.reflect.Met
hod.invoke(Native Method)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.android.internal.
os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.android.internal.
os.ZygoteInit.main(ZygoteInit.java)
04-15 11:23:55.744 12055 12055 E AndroidRuntime: Caused by: java.lang.IllegalArg
umentException: There is no GcmTaskService component registered within this pack
age. Have you extended GcmTaskService correctly?
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.gm
s.common.internal.zzab.zzb(Unknown Source)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.gm
s.gcm.GcmNetworkManager.zzjn(Unknown Source)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.gm
s.gcm.GcmNetworkManager.zza(Unknown Source)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.gm
s.gcm.GcmNetworkManager.cancelTaskUnchecked(Unknown Source)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.gm
s.gcm.GcmNetworkManager.cancelTask(Unknown Source)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.mu
sic.sync.google.tasks.PeriodicSyncTask$Scheduler.disable(PeriodicSyncTask.java:1
04)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.mu
sic.sync.google.MusicPeriodicUpdater.disablePeriodicSync(MusicPeriodicUpdater.ja
va:171)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.mu
sic.preferences.MusicPreferences.setUseGmsNetworkManagerPeriodicSync(MusicPrefer
ences.java:2195)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.mu
sic.plugins.SyncPlugin.onApplicationCreated(SyncPlugin.java:36)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.mu
sic.plugins.framework.ApplicationLifecyclePluginRegistry.onCreate(ApplicationLif
ecyclePluginRegistry.java:37)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at com.google.android.mu
sic.MusicApplication.onCreate(MusicApplication.java:137)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        at android.app.Instrumen
tation.callApplicationOnCreate(Instrumentation.java)
04-15 11:23:55.744 12055 12055 E AndroidRuntime:        ... 9 more
04-15 11:24:14.465 12472 12472 F libc    : CANNOT LINK EXECUTABLE "/system/bin/d
ex2oat": "/system/lib64/libcutils.so" is 64-bit instead of 32-bit
04-15 11:24:14.465 12472 12472 F libc    : Fatal signal 6 (SIGABRT), code -6 in
tid 12472 (dex2oat)
04-15 11:24:14.469 12473 12473 F libc    : CANNOT LINK EXECUTABLE "/system/bin/d
ex2oat": "/system/lib64/libcutils.so" is 64-bit instead of 32-bit
04-15 11:24:14.470 12473 12473 F libc    : Fatal signal 6 (SIGABRT), code -6 in
tid 12473 (dex2oat)
04-15 11:24:14.524 12474 12474 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-15 11:24:14.524 12474 12474 F DEBUG   : Build fingerprint: 'htc/hiaeuhl_00401
/htc_hiaeuhl:7.0/NRD90M/853511.3:user/release-keys'
04-15 11:24:14.524 12474 12474 F DEBUG   : Revision: '0'
04-15 11:24:14.524 12474 12474 F DEBUG   : ABI: 'arm'
04-15 11:24:14.524 12474 12474 F DEBUG   : pid: 12472, tid: 12472, name: dex2oat
  >>> /system/bin/dex2oat <<<
04-15 11:24:14.524 12474 12474 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL
), fault addr --------
04-15 11:24:14.524 12474 12474 F DEBUG   :     r0 00000000  r1 000030b8  r2 0000
0006  r3 00000008
04-15 11:24:14.524 12474 12474 F DEBUG   :     r4 f0d6a58c  r5 00000006  r6 f0d6
a534  r7 0000010c
04-15 11:24:14.524 12474 12474 F DEBUG   :     r8 ff8df738  r9 00000000  sl 0000
0008  fp f0cf8010
04-15 11:24:14.524 12474 12474 F DEBUG   :     ip 00000002  sp ff8df6d0  lr f0d4
a53f  pc f0d4aff8  cpsr 200f0010
04-15 11:24:14.528 12474 12474 F DEBUG   :
04-15 11:24:14.528 12474 12474 F DEBUG   : backtrace:
04-15 11:24:14.528 12474 12474 F DEBUG   :     #00 pc 00045ff8  /system/bin/link
er (__dl_tgkill+12)
04-15 11:24:14.528 12474 12474 F DEBUG   :     #01 pc 0004553b  /system/bin/link
er (__dl_pthread_kill+34)
04-15 11:24:14.528 12474 12474 F DEBUG   :     #02 pc 0003d89f  /system/bin/link
er (__dl_raise+10)
04-15 11:24:14.528 12474 12474 F DEBUG   :     #03 pc 0003c32b  /system/bin/link
er (__dl___libc_android_abort+34)
04-15 11:24:14.528 12474 12474 F DEBUG   :     #04 pc 0003b294  /system/bin/link
er (__dl_abort+4)
04-15 11:24:14.528 12474 12474 F DEBUG   :     #05 pc 0003d37b  /system/bin/link
er (__dl___libc_fatal+22)
04-15 11:24:14.528 12474 12474 F DEBUG   :     #06 pc 000092c1  /system/bin/link
er (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+1912)
04-15 11:24:14.528 12474 12474 F DEBUG   :     #07 pc 00008ab3  /system/bin/link
er (__dl___linker_init+358)
04-15 11:24:14.528 12474 12474 F DEBUG   :     #08 pc 000027d0  /system/bin/link
er (_start+4)
04-15 11:24:14.592 12475 12475 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-15 11:24:14.592 12475 12475 F DEBUG   : Build fingerprint: 'htc/hiaeuhl_00401
/htc_hiaeuhl:7.0/NRD90M/853511.3:user/release-keys'
04-15 11:24:14.592 12475 12475 F DEBUG   : Revision: '0'
04-15 11:24:14.592 12475 12475 F DEBUG   : ABI: 'arm'
04-15 11:24:14.592 12475 12475 F DEBUG   : pid: 12473, tid: 12473, name: dex2oat
  >>> /system/bin/dex2oat <<<
04-15 11:24:14.592 12475 12475 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL
), fault addr --------
04-15 11:24:14.592 12475 12475 F DEBUG   :     r0 00000000  r1 000030b9  r2 0000
0006  r3 00000008
04-15 11:24:14.592 12475 12475 F DEBUG   :     r4 e99d758c  r5 00000006  r6 e99d
7534  r7 0000010c
04-15 11:24:14.592 12475 12475 F DEBUG   :     r8 ffebb1a8  r9 00000000  sl 0000
0008  fp e9965010
04-15 11:24:14.592 12475 12475 F DEBUG   :     ip 00000002  sp ffebb140  lr e99b
753f  pc e99b7ff8  cpsr 200f0010
04-15 11:24:14.596 12475 12475 F DEBUG   :
04-15 11:24:14.596 12475 12475 F DEBUG   : backtrace:
04-15 11:24:14.596 12475 12475 F DEBUG   :     #00 pc 00045ff8  /system/bin/link
er (__dl_tgkill+12)
04-15 11:24:14.597 12475 12475 F DEBUG   :     #01 pc 0004553b  /system/bin/link
er (__dl_pthread_kill+34)
04-15 11:24:14.597 12475 12475 F DEBUG   :     #02 pc 0003d89f  /system/bin/link
er (__dl_raise+10)
04-15 11:24:14.597 12475 12475 F DEBUG   :     #03 pc 0003c32b  /system/bin/link
er (__dl___libc_android_abort+34)
04-15 11:24:14.597 12475 12475 F DEBUG   :     #04 pc 0003b294  /system/bin/link
er (__dl_abort+4)
04-15 11:24:14.597 12475 12475 F DEBUG   :     #05 pc 0003d37b  /system/bin/link
er (__dl___libc_fatal+22)
04-15 11:24:14.597 12475 12475 F DEBUG   :     #06 pc 000092c1  /system/bin/link
er (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+1912)
04-15 11:24:14.597 12475 12475 F DEBUG   :     #07 pc 00008ab3  /system/bin/link
er (__dl___linker_init+358)
04-15 11:24:14.597 12475 12475 F DEBUG   :     #08 pc 000027d0  /system/bin/link
er (_start+4)
04-15 11:24:24.911 12750 12750 F libc    : CANNOT LINK EXECUTABLE "/system/bin/d
ex2oat": "/system/lib64/libcutils.so" is 64-bit instead of 32-bit
04-15 11:24:24.911 12750 12750 F libc    : Fatal signal 6 (SIGABRT), code -6 in
tid 12750 (dex2oat)
04-15 11:24:24.967 12751 12751 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-15 11:24:24.967 12751 12751 F DEBUG   : Build fingerprint: 'htc/hiaeuhl_00401
/htc_hiaeuhl:7.0/NRD90M/853511.3:user/release-keys'
04-15 11:24:24.967 12751 12751 F DEBUG   : Revision: '0'
04-15 11:24:24.967 12751 12751 F DEBUG   : ABI: 'arm'
04-15 11:24:24.967 12751 12751 F DEBUG   : pid: 12750, tid: 12750, name: dex2oat
  >>> /system/bin/dex2oat <<<
04-15 11:24:24.967 12751 12751 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL
), fault addr --------
04-15 11:24:24.967 12751 12751 F DEBUG   :     r0 00000000  r1 000031ce  r2 0000
0006  r3 00000008
04-15 11:24:24.967 12751 12751 F DEBUG   :     r4 e850958c  r5 00000006  r6 e850
9534  r7 0000010c
04-15 11:24:24.967 12751 12751 F DEBUG   :     r8 ffbdf4c8  r9 00000000  sl 0000
0008  fp e8497010
04-15 11:24:24.967 12751 12751 F DEBUG   :     ip 00000002  sp ffbdf460  lr e84e
953f  pc e84e9ff8  cpsr 200f0010
04-15 11:24:24.971 12751 12751 F DEBUG   :
04-15 11:24:24.971 12751 12751 F DEBUG   : backtrace:
04-15 11:24:24.971 12751 12751 F DEBUG   :     #00 pc 00045ff8  /system/bin/link
er (__dl_tgkill+12)
04-15 11:24:24.971 12751 12751 F DEBUG   :     #01 pc 0004553b  /system/bin/link
er (__dl_pthread_kill+34)
04-15 11:24:24.971 12751 12751 F DEBUG   :     #02 pc 0003d89f  /system/bin/link
er (__dl_raise+10)
04-15 11:24:24.971 12751 12751 F DEBUG   :     #03 pc 0003c32b  /system/bin/link
er (__dl___libc_android_abort+34)
04-15 11:24:24.971 12751 12751 F DEBUG   :     #04 pc 0003b294  /system/bin/link
er (__dl_abort+4)
04-15 11:24:24.971 12751 12751 F DEBUG   :     #05 pc 0003d37b  /system/bin/link
er (__dl___libc_fatal+22)
04-15 11:24:24.971 12751 12751 F DEBUG   :     #06 pc 000092c1  /system/bin/link
er (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+1912)
04-15 11:24:24.971 12751 12751 F DEBUG   :     #07 pc 00008ab3  /system/bin/link
er (__dl___linker_init+358)
04-15 11:24:24.971 12751 12751 F DEBUG   :     #08 pc 000027d0  /system/bin/link
er (_start+4)
04-15 11:26:45.651 13174 13174 F libc    : CANNOT LINK EXECUTABLE "/system/bin/d
ex2oat": "/system/lib64/libcutils.so" is 64-bit instead of 32-bit
04-15 11:26:45.651 13174 13174 F libc    : Fatal signal 6 (SIGABRT), code -6 in
tid 13174 (dex2oat)
04-15 11:26:45.651 13173 13173 F libc    : CANNOT LINK EXECUTABLE "/system/bin/d
ex2oat": "/system/lib64/libcutils.so" is 64-bit instead of 32-bit
04-15 11:26:45.651 13173 13173 F libc    : Fatal signal 6 (SIGABRT), code -6 in
tid 13173 (dex2oat)
04-15 11:26:45.706 13175 13175 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-15 11:26:45.707 13175 13175 F DEBUG   : Build fingerprint: 'htc/hiaeuhl_00401
/htc_hiaeuhl:7.0/NRD90M/853511.3:user/release-keys'
04-15 11:26:45.707 13175 13175 F DEBUG   : Revision: '0'
04-15 11:26:45.707 13175 13175 F DEBUG   : ABI: 'arm'
04-15 11:26:45.707 13175 13175 F DEBUG   : pid: 13174, tid: 13174, name: dex2oat
  >>> /system/bin/dex2oat <<<
04-15 11:26:45.707 13175 13175 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL
), fault addr --------
04-15 11:26:45.707 13175 13175 F DEBUG   :     r0 00000000  r1 00003376  r2 0000
0006  r3 00000008
04-15 11:26:45.707 13175 13175 F DEBUG   :     r4 e973e58c  r5 00000006  r6 e973
e534  r7 0000010c
04-15 11:26:45.707 13175 13175 F DEBUG   :     r8 ff856368  r9 00000000  sl 0000
0008  fp e96cc010
04-15 11:26:45.707 13175 13175 F DEBUG   :     ip 00000002  sp ff856300  lr e971
e53f  pc e971eff8  cpsr 200f0010
04-15 11:26:45.710 13175 13175 F DEBUG   :
04-15 11:26:45.710 13175 13175 F DEBUG   : backtrace:
04-15 11:26:45.710 13175 13175 F DEBUG   :     #00 pc 00045ff8  /system/bin/link
er (__dl_tgkill+12)
04-15 11:26:45.710 13175 13175 F DEBUG   :     #01 pc 0004553b  /system/bin/link
er (__dl_pthread_kill+34)
04-15 11:26:45.710 13175 13175 F DEBUG   :     #02 pc 0003d89f  /system/bin/link
er (__dl_raise+10)
04-15 11:26:45.711 13175 13175 F DEBUG   :     #03 pc 0003c32b  /system/bin/link
er (__dl___libc_android_abort+34)
04-15 11:26:45.711 13175 13175 F DEBUG   :     #04 pc 0003b294  /system/bin/link
er (__dl_abort+4)
04-15 11:26:45.711 13175 13175 F DEBUG   :     #05 pc 0003d37b  /system/bin/link
er (__dl___libc_fatal+22)
04-15 11:26:45.711 13175 13175 F DEBUG   :     #06 pc 000092c1  /system/bin/link
er (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+1912)
04-15 11:26:45.711 13175 13175 F DEBUG   :     #07 pc 00008ab3  /system/bin/link
er (__dl___linker_init+358)
04-15 11:26:45.711 13175 13175 F DEBUG   :     #08 pc 000027d0  /system/bin/link
er (_start+4)
04-15 11:26:45.778 13177 13177 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-15 11:26:45.778 13177 13177 F DEBUG   : Build fingerprint: 'htc/hiaeuhl_00401
/htc_hiaeuhl:7.0/NRD90M/853511.3:user/release-keys'
04-15 11:26:45.778 13177 13177 F DEBUG   : Revision: '0'
04-15 11:26:45.778 13177 13177 F DEBUG   : ABI: 'arm'
04-15 11:26:45.779 13177 13177 F DEBUG   : pid: 13173, tid: 13173, name: dex2oat
  >>> /system/bin/dex2oat <<<
04-15 11:26:45.779 13177 13177 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL
), fault addr --------
04-15 11:26:45.779 13177 13177 F DEBUG   :     r0 00000000  r1 00003375  r2 0000
0006  r3 00000008
04-15 11:26:45.779 13177 13177 F DEBUG   :     r4 ecb0858c  r5 00000006  r6 ecb0
8534  r7 0000010c
04-15 11:26:45.779 13177 13177 F DEBUG   :     r8 ffbff578  r9 00000000  sl 0000
0008  fp eca96010
04-15 11:26:45.779 13177 13177 F DEBUG   :     ip 00000002  sp ffbff510  lr ecae
853f  pc ecae8ff8  cpsr 200f0010
04-15 11:26:45.783 13177 13177 F DEBUG   :
04-15 11:26:45.783 13177 13177 F DEBUG   : backtrace:
04-15 11:26:45.783 13177 13177 F DEBUG   :     #00 pc 00045ff8  /system/bin/link
er (__dl_tgkill+12)
04-15 11:26:45.783 13177 13177 F DEBUG   :     #01 pc 0004553b  /system/bin/link
er (__dl_pthread_kill+34)
04-15 11:26:45.783 13177 13177 F DEBUG   :     #02 pc 0003d89f  /system/bin/link
er (__dl_raise+10)
04-15 11:26:45.783 13177 13177 F DEBUG   :     #03 pc 0003c32b  /system/bin/link
er (__dl___libc_android_abort+34)
04-15 11:26:45.783 13177 13177 F DEBUG   :     #04 pc 0003b294  /system/bin/link
er (__dl_abort+4)
04-15 11:26:45.783 13177 13177 F DEBUG   :     #05 pc 0003d37b  /system/bin/link
er (__dl___libc_fatal+22)
04-15 11:26:45.783 13177 13177 F DEBUG   :     #06 pc 000092c1  /system/bin/link
er (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+1912)
04-15 11:26:45.783 13177 13177 F DEBUG   :     #07 pc 00008ab3  /system/bin/link
er (__dl___linker_init+358)
04-15 11:26:45.784 13177 13177 F DEBUG   :     #08 pc 000027d0  /system/bin/link
er (_start+4)
04-15 11:28:12.584 14790 14790 F libc    : CANNOT LINK EXECUTABLE "/system/bin/d
ex2oat": "/system/lib64/libcutils.so" is 64-bit instead of 32-bit
04-15 11:28:12.584 14790 14790 F libc    : Fatal signal 6 (SIGABRT), code -6 in
tid 14790 (dex2oat)
04-15 11:28:12.640 14791 14791 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-15 11:28:12.640 14791 14791 F DEBUG   : Build fingerprint: 'htc/hiaeuhl_00401
/htc_hiaeuhl:7.0/NRD90M/853511.3:user/release-keys'
04-15 11:28:12.640 14791 14791 F DEBUG   : Revision: '0'
04-15 11:28:12.640 14791 14791 F DEBUG   : ABI: 'arm'
04-15 11:28:12.640 14791 14791 F DEBUG   : pid: 14790, tid: 14790, name: dex2oat
  >>> /system/bin/dex2oat <<<
04-15 11:28:12.640 14791 14791 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL
), fault addr --------
04-15 11:28:12.640 14791 14791 F DEBUG   :     r0 00000000  r1 000039c6  r2 0000
0006  r3 00000008
04-15 11:28:12.640 14791 14791 F DEBUG   :     r4 f401458c  r5 00000006  r6 f401
4534  r7 0000010c
04-15 11:28:12.640 14791 14791 F DEBUG   :     r8 ff9e73b8  r9 00000000  sl 0000
0008  fp f3fa2010
04-15 11:28:12.640 14791 14791 F DEBUG   :     ip 00000002  sp ff9e7350  lr f3ff
453f  pc f3ff4ff8  cpsr 200f0010
04-15 11:28:12.644 14791 14791 F DEBUG   :
04-15 11:28:12.644 14791 14791 F DEBUG   : backtrace:
04-15 11:28:12.644 14791 14791 F DEBUG   :     #00 pc 00045ff8  /system/bin/link
er (__dl_tgkill+12)
04-15 11:28:12.644 14791 14791 F DEBUG   :     #01 pc 0004553b  /system/bin/link
er (__dl_pthread_kill+34)
04-15 11:28:12.644 14791 14791 F DEBUG   :     #02 pc 0003d89f  /system/bin/link
er (__dl_raise+10)
04-15 11:28:12.644 14791 14791 F DEBUG   :     #03 pc 0003c32b  /system/bin/link
er (__dl___libc_android_abort+34)
04-15 11:28:12.644 14791 14791 F DEBUG   :     #04 pc 0003b294  /system/bin/link
er (__dl_abort+4)
04-15 11:28:12.644 14791 14791 F DEBUG   :     #05 pc 0003d37b  /system/bin/link
er (__dl___libc_fatal+22)
04-15 11:28:12.644 14791 14791 F DEBUG   :     #06 pc 000092c1  /system/bin/link
er (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+1912)
04-15 11:28:12.644 14791 14791 F DEBUG   :     #07 pc 00008ab3  /system/bin/link
er (__dl___linker_init+358)
04-15 11:28:12.644 14791 14791 F DEBUG   :     #08 pc 000027d0  /system/bin/link
er (_start+4)

**Comment by liudongmiao** [comment]
日志中，没有任何与黑域相关的内容。

**Comment by ydj73** [comment]
好的，那能否判断问题成因？2017年4月15日 15:58，Liu DongMiao <notifications@github.com>写道：日志中，没有任何与黑域相关的内容。

**Comment by liudongmiao** [comment]
都说了没日志了....

**Comment by ydj73** [comment]
好的，我再看看会不会重现，再看看日志。2017年4月15日 18:35，Liu DongMiao <notifications@github.com>写道：都说了没日志了....
