### ISSUE TITLE
首次打开fc。。另外貌似我这里魅族必须开机等sim卡加载好才能正常开始黑域。。下面是fc时候日志(这次更新才出现fc的，以前使用没问题，可是开始黑域慢

### ISSUE THREAD

**Issue by naloder** [liudongmiao/Brevent#426]
> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: FATAL EXCEPTION: Brevent

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: Process: me.piebridge.brevent, PID: 25803

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: java.lang.NumberFormatException: Invalid int: ""

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at java.lang.Integer.invalidInt(Integer.java:138)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:358)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:334)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at me.piebridge.brevent.protocol.BreventConfiguration.a(BreventConfiguration.java:163)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at me.piebridge.brevent.protocol.BreventConfiguration.<init>(BreventConfiguration.java:70)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.k(BreventActivity.java:619)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:836)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:753)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at me.piebridge.brevent.ui.a.handleMessage(AppsActivityHandler.java:77)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:194)

> 04-15 12:36:15.794 25803 25904 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by naloder** [comment]
这次更新以后出现的，以前使用没问题

**Comment by naloder** [comment]
刚刚清除黑域数据重新打开可以了。。原因是啥。

**Comment by liudongmiao** [comment]
你有手动修改配置文件么？这是因为某个配置文件被修改了。
