### ISSUE TITLE
huawei 无法启动服务

### ISSUE THREAD

**Issue by CreeperLin** [liudongmiao/Brevent#427]
--- crash start ---
>>> logcat -b crash -t '04-15 16:20:14.000' -d

Note: log switch off, only log_main and log_events will have logs!
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-15 16:20:14.000' -d -s BreventLoader BreventServer

Note: log switch off, only log_main and log_events will have logs!
I/BreventServer( 7321): Brevent Server 1.0.2 started
I/BreventServer( 7321): brevent user: 0, uid: 0
E/BreventLoader( 7307): worker 7321 exited on signal 9
I/BreventServer( 7375): Brevent Server 1.0.2 started
I/BreventServer( 7375): brevent user: 0, uid: 0
E/BreventLoader( 7361): worker 7375 exited on signal 9
I/BreventServer( 7491): Brevent Server 1.0.2 started
I/BreventServer( 7491): brevent user: 0, uid: 0
E/BreventLoader( 7477): worker 7491 exited on signal 9
I/BreventServer( 8177): Brevent Server 1.0.2 started
W/BreventServer( 8177): Can't getCurrentUser
I/BreventServer( 8177): brevent user: 0, uid: 2000
E/BreventLoader( 8163): worker 8177 exited on signal 9
I/BreventServer( 8291): Brevent Server 1.0.2 started
I/BreventServer( 8291): brevent user: 0, uid: 0
E/BreventLoader( 8277): worker 8291 exited on signal 9
--- brevent end ---

**Comment by liudongmiao** [comment]
电脑上装个 teamviewer，帐号密码发到我邮箱：br@piebridge.me
