### ISSUE TITLE
建议界面可以快速定位应用

### ISSUE THREAD

**Issue by CVN-77** [liudongmiao/Brevent#428]
应用多的时候，在列表里找某个特定应用要滑很久，建议加入搜索或者右侧做个滑块，以快速定位应用，这应该也是符合安卓应用设计规范的。

**Comment by liudongmiao** [comment]
暂时没有任何计划，没有任何动力继续开发。
真心累了。

其实目前按运行+名称排序，还好。
实在不济，启动器里手动打开，就排到前面去了。

**Comment by CVN-77** [comment]
…还是有很大完善空间的，不过这段时间作者应该确实是累，酷安实在是太杂乱了…

没事的，你歇会吧，望你再出发。
