### ISSUE TITLE
新版0.4不能用

### ISSUE THREAD

**Issue by wudimenghuan** [liudongmiao/Brevent#43]
adb shell里运行时候说不能运行在non-shell
放在PrivBrevent/PrivBrevent.apk，开机后没有这个应用

一加3
自己改的脚本，不用root浏览器了
https://github.com/wudimenghuan/BreventBat

**Comment by liudongmiao** [comment]
目前只允许使用 shell 

如果你 root 了，你有好多种办法让一个进程启动。不在讨论范围之内。
