### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by z747414964** [liudongmiao/Brevent#431]
sdcard/Android/data/me.piebridge.brevent/brevent.sh           <
checking...brevent_server started, pid: 12656
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-16 23:00:16.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-16 23:00:16.000' -d -s BreventLoader BreventServer
04-16 23:00:17.109 12645 12645 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-16 23:00:17.663 12656 12656 I BreventServer: Brevent Server 1.0.3 started
04-16 23:00:17.670 12656 12656 I BreventServer: brevent user: 0, uid: 0
04-16 23:00:17.671 12656 12656 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
04-16 23:00:18.512 12656 12656 I BreventServer: loading brevent list
04-16 23:00:18.512 12656 12656 I BreventServer: loading brevent conf
04-16 23:00:18.575 12656 12656 E BreventServer: Can't be run as root, please open Brevent
04-16 23:00:18.602 12645 12645 E BreventLoader: worker 12656 exited with status 1
04-16 23:00:18.602 12645 12645 D BreventLoader: signal arrived, update: 0
04-16 23:00:18.603 12634 12634 D BreventLoader: worker 12645 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> 04-16 23:00:18.575 12656 12656 E BreventServer: Can't be run as root, please open Brevent
