### ISSUE TITLE
回酷安吧，柳大

### ISSUE THREAD

**Issue by LornBin** [liudongmiao/Brevent#433]
希望柳大能回酷安，领回开发者账号。您不用像以前那样，挨个挨个回复问题，更不要理那些喷子。平常的刷酷安，和冯老师一样，不去理那些人就好，黑域评论区没有你显得不那么热闹了。当然期待柳大说的放手不管版，不知道有没有可能哪天不用电脑adb。

**Comment by liudongmiao** [comment]
参照向导 - 权限，没有 root 的话，不可能。

**Comment by CVN-77** [comment]
作者机智的回答后一个问题，避开了前一个问题😁

**Comment by heiyuheiyu** [comment]
楼上你太搞笑了 哈哈
