### ISSUE TITLE
权限不足问题

### ISSUE THREAD

**Issue by qq714476521** [liudongmiao/Brevent#434]
![qq 20170418011712](https://cloud.githubusercontent.com/assets/27697364/25096897/d5cce4d8-23d4-11e7-9f1c-6f3d7e157d27.jpg)
提示权限不足

**Comment by liudongmiao** [comment]
你先这样吧，下个版本我加进兼容性：

1. adb -d shell chmod 0775 /data/local/tmp/brevent
2. adb -d shell /data/local/tmp/brevent

**Comment by liudongmiao** [comment]
测试版应该能解决你的问题：https://piebridge.me/br/next/
