### ISSUE TITLE
Optimize VPN should work with shadowsocks?

### ISSUE THREAD

**Issue by djunhao** [liudongmiao/Brevent#435]
I have checked "optimize VPN ", but when I swipe shadowsocks from the recent applications, shadowsocks quit immediately.
How to setup shadowsocks or brevent to keep shadowsocks and brevent working together?

**Comment by liudongmiao** [comment]
please make sure that shadowsocks connected. 

on my phone, and other guys' test, if vpn is connected, it won't be force-stopped by brevent. please attach log, you can learn from the play store's detail page.

**Comment by djunhao** [comment]
I comfirm that shadowsocks has connected, and I have tested for five times at least, but shadowsocks quit as soon as it has been swiped from the recent apps.
And as I remember, shadowsocks works properly if I swiped it from the recent apps lists before brevent-1.0.3.
After all, I will attach the log tomorrow.

**Comment by djunhao** [comment]
I have just install brevent-1.0.3+5, and it works with shadowsocks as I wanted.
Thanks for your work very much!

**Comment by djunhao** [comment]
./adb -d logcat -d -b main -s BreventServer BreventLoader
04-19 00:00:16.700 29642 29642 D BreventServer: com.microsoft.skydrive: priority
04-19 00:00:28.080 29642 29642 D BreventServer: check and brevent
04-19 00:00:28.390 29642 29642 D BreventServer: ignore com.microsoft.skydrive, wait for the service check
04-19 00:00:28.440 29642 29642 D BreventServer: Force stop com.facebook.katana(service)
04-19 00:00:28.470 29642 29642 D BreventServer: check again in 3600s
04-19 00:00:28.470 29642 29642 D BreventServer: check and brevent, took 391ms
04-19 00:00:49.730 29642 29642 D BreventServer: check and brevent
04-19 00:00:49.870 29642 29642 D BreventServer: Force stop tv.peel.app(noRecent)
04-19 00:00:49.900 29642 29642 D BreventServer: Force stop com.android.vending(priority service)
04-19 00:00:49.940 29642 29642 D BreventServer: Force stop com.microsoft.skydrive(priority service)
04-19 00:00:49.940 29642 29642 D BreventServer: check again in 3600s
04-19 00:00:49.940 29642 29642 D BreventServer: check and brevent, took 215ms
04-19 00:01:12.150 29642 29642 D BreventServer: check and brevent
04-19 00:01:12.240 29642 29642 D BreventServer: check again in 3600s
04-19 00:01:12.240 29642 29642 D BreventServer: check and brevent, took 91ms
04-19 00:05:40.450 29642 29642 I BreventServer: version changed from 1.0.3 to 1.0.3-5-gf812335, live 22:07:44
04-19 00:05:40.490 29621 29621 D BreventLoader: worker 29642 exited with status 0
04-19 00:05:40.490 29621 29621 D BreventLoader: signal arrived, update: 1
04-19 00:05:41.390 29621 29621 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-19 00:05:42.260 14882 14882 I BreventServer: Brevent Server 1.0.3-5-gf812335 started
04-19 00:05:42.280 14882 14882 I BreventServer: brevent user: 0, uid: 2000
04-19 00:05:42.280 14882 14882 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-19 00:05:42.590 14882 14882 I BreventServer: loading brevent list
04-19 00:05:42.590 14882 14882 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 30
04-19 00:05:42.590 14882 14882 I BreventServer: loading brevent conf
04-19 00:05:42.620 14882 14882 D BreventServer: check and brevent
04-19 00:05:42.700 14882 14882 I BreventServer: android process: android.process.media, packages: [com.android.providers.media, com.android.providers.downloads]
04-19 00:05:42.700 14882 14882 I BreventServer: android process: android.process.acore, packages: [com.android.providers.userdictionary, com.android.providers.contacts]
04-19 00:05:42.790 14882 14882 D BreventServer: Force stop com.microsoft.office.excel(noRecent)
04-19 00:05:42.820 14882 14882 D BreventServer: Force stop com.android.vending(priority service)
04-19 00:05:42.830 14882 14882 D BreventServer: Can't setStopped for com.android.vending(ignore)
04-19 00:05:42.850 14882 14882 D BreventServer: Force stop com.google.android.apps.docs(noRecent)
04-19 00:05:42.870 14882 14882 D BreventServer: Force stop com.microsoft.office.word(noRecent)
04-19 00:05:42.890 14882 14882 D BreventServer: Force stop com.microsoft.office.powerpoint(noRecent)
04-19 00:05:42.940 14882 14882 D BreventServer: Force stop com.sec.android.app.sbrowser(noRecent)
04-19 00:05:42.970 14882 14882 D BreventServer: Force stop com.facebook.katana(noRecent)
04-19 00:05:42.980 14882 14882 D BreventServer: check again in 3600s
04-19 00:05:42.980 14882 14882 D BreventServer: check and brevent, took 354ms
04-19 00:05:42.980 14882 14882 D BreventServer: Can't setStopped for me.piebridge.brevent(ignore)
04-19 00:05:42.980 14882 14882 D BreventServer: Can't setStopped for me.piebridge.brevent(ignore)
04-19 00:05:51.080 14882 14882 D BreventServer: sent first status
04-19 00:05:51.080 14882 14882 D BreventServer: com.microsoft.skydrive: priority
04-19 00:05:51.080 14882 14882 D BreventServer: com.microsoft.skydrive: priority
04-19 00:05:53.360 14882 14882 D BreventServer: checking feelgood
04-19 00:05:53.360 14882 14962 D BreventServer: received feelgood
04-19 00:05:55.510 14882 14882 D BreventServer: check and brevent
04-19 00:05:55.790 14882 14882 D BreventServer: Force stop com.sec.android.app.samsungapps(noRecent)
04-19 00:05:55.890 14882 14882 D BreventServer: Force stop tv.peel.app(noRecent)
04-19 00:05:55.890 14882 14882 D BreventServer: ignore com.microsoft.skydrive, wait for the service check
04-19 00:05:55.970 14882 14882 D BreventServer: Force stop com.instagram.android(noRecent)
04-19 00:05:56.010 14882 14882 D BreventServer: Force stop com.microsoft.office.onenote(noRecent)
04-19 00:05:56.070 14882 14882 D BreventServer: Force stop com.sec.android.app.music(service)
04-19 00:05:56.100 14882 14882 D BreventServer: Force stop com.google.android.apps.plus(service)
04-19 00:05:56.140 14882 14882 D BreventServer: Force stop com.facebook.katana(service)
04-19 00:05:56.160 14882 14882 D BreventServer: Force stop com.samsung.voiceserviceplatform(noRecent)
04-19 00:05:56.190 14882 14882 D BreventServer: Force stop com.google.android.apps.magazines(noRecent)
04-19 00:05:56.210 14882 14882 D BreventServer: check again in 3600s
04-19 00:05:56.210 14882 14882 D BreventServer: check and brevent, took 702ms
04-19 00:06:24.110 14882 14882 D BreventServer: check and brevent
04-19 00:06:24.330 14882 14882 D BreventServer: Force stop tv.peel.app(noRecent)
04-19 00:06:24.350 14882 14882 D BreventServer: Force stop com.android.vending(priority service)
04-19 00:06:24.390 14882 14882 D BreventServer: Force stop com.microsoft.skydrive(priority service)
04-19 00:06:24.400 14882 14882 D BreventServer: check again in 3600s
04-19 00:06:24.400 14882 14882 D BreventServer: check and brevent, took 291ms
04-19 00:06:42.590 14882 14882 D BreventServer: check and brevent
04-19 00:06:42.710 14882 14882 D BreventServer: Force stop com.samsung.galaxylife(noRecent)
04-19 00:06:42.710 14882 14882 D BreventServer: check again in 3600s
04-19 00:06:42.710 14882 14882 D BreventServer: check and brevent, took 120ms
04-19 00:06:53.580 14882 14882 D BreventServer: com.android.vending: priority
04-19 00:07:19.640 14882 14882 D BreventServer: check and brevent
04-19 00:07:19.750 14882 14882 D BreventServer: ignore com.android.vending, wait for the service check
04-19 00:07:19.760 14882 14882 D BreventServer: check again in 3600s
04-19 00:07:19.760 14882 14882 D BreventServer: check and brevent, took 115ms
04-19 00:07:26.590 14882 14882 D BreventServer: check and brevent
04-19 00:07:27.050 14882 14882 D BreventServer: Force stop com.android.vending(priority service)
04-19 00:07:27.060 14882 14882 D BreventServer: check again in 3600s
04-19 00:07:27.060 14882 14882 D BreventServer: check and brevent, took 469ms
04-19 00:07:51.020 14882 14882 D BreventServer: checking feelgood
04-19 00:07:51.020 14882 14962 D BreventServer: received feelgood
04-19 00:08:09.270 14882 14882 D BreventServer: check and brevent
04-19 00:08:09.560 14882 14882 D BreventServer: check again in 3600s
04-19 00:08:09.560 14882 14882 D BreventServer: check and brevent, took 287ms
04-19 00:08:24.120 14882 14882 D BreventServer: Can't setStopped for com.android.vending(ignore)
04-19 00:08:24.120 14882 14882 D BreventServer: Can't setStopped for com.android.vending(ignore)
04-19 00:08:25.340 14882 14882 D BreventServer: check and brevent
04-19 00:08:25.450 14882 14882 D BreventServer: check again in 1799s
04-19 00:08:25.450 14882 14882 D BreventServer: check and brevent, took 112ms
04-19 00:08:39.210 14882 14882 D BreventServer: Can't setStopped for com.facebook.katana(ignore)
04-19 00:08:39.210 14882 14882 D BreventServer: Can't setStopped for com.facebook.katana(ignore)
04-19 00:08:39.300 14882 14882 D BreventServer: check and brevent
04-19 00:08:39.400 14882 14882 D BreventServer: check again in 1800s
04-19 00:08:39.400 14882 14882 D BreventServer: check and brevent, took 101ms
04-19 00:08:40.490 14882 14882 D BreventServer: Can't setStopped for com.facebook.katana(ignore)
04-19 00:08:54.160 14882 14882 D BreventServer: Can't setStopped for com.facebook.katana(ignore)
04-19 00:08:56.850 14882 14882 D BreventServer: Can't setStopped for com.facebook.katana(ignore)
04-19 00:09:01.200 14882 14882 D BreventServer: check and brevent
04-19 00:09:01.390 14882 14882 D BreventServer: check again in 3597s
04-19 00:09:01.390 14882 14882 D BreventServer: check and brevent, took 188ms
04-19 00:09:02.550 14882 14882 D BreventServer: checking feelgood
04-19 00:09:02.550 14882 14962 D BreventServer: received feelgood
04-19 00:09:39.520 14882 14882 D BreventServer: checking feelgood
04-19 00:09:39.520 14882 14962 D BreventServer: received feelgood
04-19 00:10:31.270 14882 14882 D BreventServer: check and brevent
04-19 00:10:31.680 14882 14882 D BreventServer: Force stop com.android.vending(priority service)
04-19 00:10:31.700 14882 14882 D BreventServer: check again in 3507s
04-19 00:10:31.700 14882 14882 D BreventServer: check and brevent, took 438ms
04-19 00:11:11.630 14882 14882 D BreventServer: checking feelgood
04-19 00:11:11.630 14882 14962 D BreventServer: received feelgood
04-19 00:11:19.890 14882 14882 D BreventServer: check and brevent
04-19 00:11:20.320 14882 14882 D BreventServer: Force stop com.sec.android.app.sbrowser(noRecent)
04-19 00:11:20.340 14882 14882 D BreventServer: check again in 3458s
04-19 00:11:20.340 14882 14882 D BreventServer: check and brevent, took 442ms
04-19 00:11:25.320 14882 14882 D BreventServer: check and brevent
04-19 00:11:25.740 14882 14882 D BreventServer: check again in 3453s
04-19 00:11:25.740 14882 14882 D BreventServer: check and brevent, took 415ms
04-19 00:12:36.270 14882 14882 D BreventServer: check and brevent
04-19 00:12:36.640 14882 14882 D BreventServer: Force stop com.microsoft.skydrive(priority service)
04-19 00:12:36.660 14882 14882 D BreventServer: Force stop com.google.android.apps.plus(noRecent)
04-19 00:12:36.670 14882 14882 D BreventServer: check again in 3382s
04-19 00:12:36.670 14882 14882 D BreventServer: check and brevent, took 394ms
04-19 00:13:02.710 14882 14882 D BreventServer: check and brevent
04-19 00:13:03.320 14882 14882 D BreventServer: Force stop com.skype.raider(noRecent)
04-19 00:13:03.360 14882 14882 D BreventServer: Force stop com.sec.android.app.samsungapps(noRecent)
04-19 00:13:03.420 14882 14882 D BreventServer: Force stop tv.peel.app(noRecent)
04-19 00:13:03.460 14882 14882 D BreventServer: Force stop com.android.vending(priority service)
04-19 00:13:03.490 14882 14882 D BreventServer: Force stop com.microsoft.skydrive(priority service)
04-19 00:13:03.520 14882 14882 D BreventServer: Force stop com.instagram.android(noRecent)
04-19 00:13:03.560 14882 14882 D BreventServer: Force stop com.google.android.apps.plus(noRecent)
04-19 00:13:03.620 14882 14882 D BreventServer: Force stop com.samsung.galaxylife(noRecent)
04-19 00:13:03.650 14882 14882 D BreventServer: check again in 3356s
04-19 00:13:03.650 14882 14882 D BreventServer: check and brevent, took 933ms
04-19 00:13:24.110 14882 14882 D BreventServer: check and brevent
04-19 00:13:24.440 14882 14882 D BreventServer: Force stop com.skype.raider(noRecent)
04-19 00:13:24.480 14882 14882 D BreventServer: Force stop com.sec.android.app.samsungapps(noRecent)
04-19 00:13:24.540 14882 14882 D BreventServer: Force stop tv.peel.app(noRecent)
04-19 00:13:24.570 14882 14882 D BreventServer: Force stop com.microsoft.skydrive(priority service)
04-19 00:13:24.640 14882 14882 D BreventServer: Force stop com.instagram.android(noRecent)
04-19 00:13:24.680 14882 14882 D BreventServer: Force stop com.google.android.apps.plus(noRecent)
04-19 00:13:24.710 14882 14882 D BreventServer: Force stop com.facebook.katana(noRecent)
04-19 00:13:24.720 14882 14882 D BreventServer: check again in 3600s
04-19 00:13:24.720 14882 14882 D BreventServer: check and brevent, took 605ms
04-19 00:13:53.240 14882 14882 D BreventServer: check and brevent
04-19 00:13:53.560 14882 14882 D BreventServer: Force stop com.skype.raider(noRecent)
04-19 00:13:53.610 14882 14882 D BreventServer: Force stop tv.peel.app(noRecent)
04-19 00:13:53.650 14882 14882 D BreventServer: Force stop com.android.vending(priority service)
04-19 00:13:53.680 14882 14882 D BreventServer: Force stop com.samsung.galaxylife(noRecent)
04-19 00:13:53.690 14882 14882 D BreventServer: check again in 3600s
04-19 00:13:53.690 14882 14882 D BreventServer: check and brevent, took 436ms

**Comment by djunhao** [comment]
Why brevent would brevent itself?

**Comment by liudongmiao** [comment]
Brevent app is only a manager UI. The real working server is started by adb. So brevent Brevent is OK.

**Comment by djunhao** [comment]
In sometimes, closing all apps  from the recent apps list by clicking "close all" button, shadowsocks would keep "alive" and could not be brevented.

**Comment by liudongmiao** [comment]
Just wait for the next check, normally, very quick.

And there are always debug log, please read play store details to learn how to debug Brevent Server.

**Comment by djunhao** [comment]
OK, thanks for your work.

**Comment by djunhao** [comment]
I have installed brevent-1.0.9 and recently brevent-1.1, it seems ok!
