### ISSUE TITLE
flyme6黑域方法只有强行停止不待机选项

### ISSUE THREAD

**Issue by AceMONKEY519** [liudongmiao/Brevent#437]
魅蓝note5的flyme6,不知道从哪个黑域版本开始就出现这种情况了，，，一直无解

**Comment by AceMONKEY519** [comment]
还有就是，明明黑域已经放各种白名单了，可还是会出现重新开启root模式情况一直无法解决，，，就差把自带的管理软件删掉了

**Comment by liudongmiao** [comment]
魅族就不支持待机呗，绝大多数国产机器都不支持。

root 实验性功能，不提供技术支持。

**Comment by hhuimie** [comment]
@liudongmiao 大佬, 小米6刚到, 也是只有强行停止, 这个没办法解决吗? 绿守也一样? 非常感谢!
