### ISSUE TITLE
建议：每项设置增加详细说明，向导就不用了吧，改成帮助

### ISSUE THREAD

**Issue by hubeixulu** [liudongmiao/Brevent#442]
说一下我的个人建议，我从生活中观察使用手机软件的人，他们大部分是不看向导的，大部分会跳过向导，直接打开用，所以我看到你在酷安回复别人的一些低级问题的时候都会说请看向导。
建议1，把设置描述的详细一点，比如高级功能里面有个检查通知，里面的描述是“只有当您的机器解锁或者查看通知卡顿时，才需要关闭检查通知”其实看到这个不知道这个选项是干嘛用的，我看了你写的文档以后才知道的，所以描述可以详细一点。
建议2，把向导取消了，设置成帮助，帮助直接链接到你写的那个文档，文档写的非常好，免得老是有人问一些低级问题，还要你去回答他们去看向导，
这是一些个人建议，作者忙的话可以不必在乎

**Comment by liudongmiao** [comment]
怎样都会有人不看。

**Comment by MisterGlasses** [comment]
文档在哪

**Comment by liudongmiao** [comment]
https://piebridge.me/br/br.pdf
