### ISSUE TITLE
微信捐赠了 怎么开启捐赠功能  

### ISSUE THREAD

**Issue by jiaobo169** [liudongmiao/Brevent#445]
如题 联系方式Q28043511

**Comment by ydj73** [comment]
如果你没有装GooglePlay，功能上没有任何限制呀

**Comment by jiaobo169** [comment]
我装了play……

**Comment by liudongmiao** [comment]
能使用微信捐赠的，就不是 play 版，请继续使用非 play 版，也就是不要从 Play 商店安装。
如果直接从 Play 商店安装，需要重新捐赠，并且只会见到 Play 捐赠。

**Comment by jiaobo169** [comment]
恩 明白 已捐赠支持
