### ISSUE TITLE
建议加回原来的启动方式

### ISSUE THREAD

**Issue by vvb2060** [liudongmiao/Brevent#447]
还是有很多人用脚本启动遇到各种问题，脚本启动是为了方便，还有各种一键xx，但不应该造成一些用户就无法启动了。
我认为还是应该以某种形式提示用户直接运行libbrevent.so的方法。

**Comment by liudongmiao** [comment]
以前的方式，从来就没有去掉。
自己找到那个文件，然后执行不就好了？

这么说吧，以前提示那个 libbrevent.so 的位置，现在只是加装了一层，解决好多兼容性问题。
如果这种兼容性问题不能工作，那么，也应该是汇报 bug，继续加强。

**Comment by wudimenghuan** [comment]
请问，如何在ROOT的系统上执行这个文件？用各种浏览器都不能执行，用终端模拟器也不能运行

**Comment by Vstory** [comment]
用MT管理器（授予Root权限）找到这个文件 libbrevent.so ，长按选择脚本执行。应该也是可以的。

**Comment by liudongmiao** [comment]
认真阅读向导-权限，里面有提到具体方法。

简单点说，点击 7 次 Back，你就可以看到“以 ROOT 运行”了。
