### ISSUE TITLE
Win10创意者更新后adb启动问题

### ISSUE THREAD

**Issue by Vstory** [liudongmiao/Brevent#448]
按住Shift后右击platform-tools，打开的是Powershell，执行"adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
"这个命令会出错。建议更新下应用的adb介绍。
需要在adb前面加上".\"，才能正常启用。".\adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
“

**Comment by liudongmiao** [comment]
ADB 文档更新了吧，使用 .\adb.exe 代替 adb

不同操作系统有不同的方式，这个只有一次，也没法提示不同的版本。
毕竟不能知道用户到底使用的是 windows，还是 linux，还是 mac。
所以，就直接放在 向导 - ADB 里说了。
