### ISSUE TITLE
一加3t  安卓6.0.1 在未重启情况下 黑域失效 需要重新adb 授权 附奔溃日志

### ISSUE THREAD

**Issue by fj11101** [liudongmiao/Brevent#449]
04-16 17:37:38.037 14459 10032 F google-breakpad: M F5CC1000 00000000 00018000 8
4D7CD1460DF65ED624726ACBE0620E30 libprotobuf-cpp-lite.so
04-16 17:37:38.037 14459 10032 F google-breakpad: M F5CDC000 00000000 00007000 8
CF8ACFCDCB530109040A73CA64A02CD0 libstagefright_avc_common.so
04-16 17:37:38.037 14459 10032 F google-breakpad: M F5CE5000 00000000 00003000 C
3A7B4A6639479AC87DD0CC1061B020F0 libstagefright_enc_common.so
04-16 17:37:38.037 14459 10032 F google-breakpad: M F5CEB000 00000000 00004000 A
7E4D65ED8D861106287EB251B788D100 libpowermanager.so
04-16 17:37:38.037 14459 10032 F google-breakpad: M F5CF2000 00000000 0001D000 E
DC5A24B6DC9323E53157DE97A49701E0 libvorbisidec.so
04-16 17:37:38.037 14459 10032 F google-breakpad: M F5D11000 00000000 00005000 B
5B07FA9E7D09ABA858F3491306A22590 libstagefright_yuv.so
04-16 17:37:38.037 14459 10032 F google-breakpad: M F5D17000 00000000 0002F000 7
89416A233E156A95609B266FA91CB5D0 libstagefright_omx.so
04-16 17:37:38.037 14459 10032 F google-breakpad: M F5D4B000 00000000 00039000 E
E0E40D79DA8BAAA520B76C5040050AF0 libopus.so
04-16 17:37:38.037 14459 10032 F google-breakpad: M F5D87000 00000000 00007000 1
6D38127C1F119A39634424977DE9E080 libmediautils.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5D8F000 00000000 00018000 7
2EEF399B953F693B3D55D950E1A2FD00 libdrmframework.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5DAB000 00000000 0001E000 E
444AC8F4BF452307A6AC5A34DC1241D0 libRScpp.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5DCC000 00000000 0003E000 0
E67C901FF91F00CC187D970B553ABC90 libRS.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5E0F000 00000000 00007000 0
3F48E6CFD7808049BFF4B0015F641A60 libspeexresampler.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5E18000 00000000 00009000 8
8F6BF6454DEDCE3BEA563717B36DD850 libnbaio.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5E23000 00000000 00012000 6
CCAEBBF139CD705A2AAA8D35DC64CB50 libpcre.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5E37000 00000000 00005000 C
E71D63295305D034C3F704CA3DE87790 libwpa_client.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5E3E000 00000000 0000B000 E
5FDA782D7C8D01879DA3D071ABCA44D0 libqsap_sdk.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5E4C000 00000000 0006E000 1
D02A0B9903CCBF3F25F29CD9B0953C60 libGLES_trace.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5EBD000 00000000 00036000 2
D9D5AC7AE3012A3E3DB2F655AB876530 libqc-opt.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5EF5000 00000000 00061000 F
EC86D04D9B378AEF299B370A18DE5070 libft2.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5F59000 00000000 00025000 C
083D518402A3BF6B21404B60EEEB6F20 libpng.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5F81000 00000000 00003000 B
304A9D0DB749632FFF6F05962C2F2690 libsync.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5F86000 00000000 00005000 8
DAA0BC5C2B1780F2EF40F9D65DAF4E00 libstdc++.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5F8D000 00000000 00010000 C
50A492992AE32BEF8B68EA11C4ADE680 libunwind.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5FE5000 00000000 00009000 2
3CD986D3F0D658DD978972000E2424F0 libbase.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5FF0000 00000000 00005000 6
472F814CADBF9C7A7748BCE19646B730 libeffects.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5FF7000 00000000 00003000 9
0FCF1D280A0B3FFCF9F0FB707DBBB350 libstagefright_http_support.so
04-16 17:37:38.038 14459 10032 F google-breakpad: M F5FFD000 00000000 00018000 2
D7D6A10D1D267E5B47F728E5EFC78F50 libstagefright_foundation.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6011000 00000000 00160000 2
CF91E0810AAF693F1E23FD628586A320 libstagefright.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F617F000 00000000 00004000 D
E797F713F503F5F826C2F2A0C08C2620 libregionalization.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6184000 00000000 00069000 5
A0724CA09E3DBD71F36372385156F370 libhwui.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F61F2000 00000000 00004000 D
1A71C4BF386A4C5E892901902721BD60 liboem_jni.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F61F8000 00000000 00007000 3
A81929A479B9663B896D71DDC5729DF0 libassert_tip_service.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6201000 00000000 00003000 D
5960FFF952C60F242FE34AB1AF0A15F0 libradio_metadata.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6206000 00000000 00004000 8
0C852880EB0DD94FAB748835F2EFF460 libnativebridge.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F620C000 00000000 00004000 E
00F25A7873FE8850EA0F778DA8A5A030 libprocessgroup.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6212000 00000000 0000E000 9
BACB2BCF94F0493DECD682613EAEE0B0 libminikin.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6222000 00000000 0000B000 8
0340A956810D04172FCB301BE70ECE20 libsoundtrigger.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6230000 00000000 0000B000 4
3567217A8EC89767687031D9125EB100 libradio.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6240000 00000000 00004000 A
9BE9CF6A5C6A0A91B9D0232AA5215620 libnetd_client.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6246000 00000000 0000D000 0
ED5B046E948D797167D8085399E312C0 libimg_utils.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6250000 00000000 00404000 9
BA20C14DC9664B5A5571C750CC516E70 libpdfium.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6663000 00000000 00007000 C
0AC95D46FBF7444910EE40F363B5B5F0 libaudioutils.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F666C000 00000000 0001A000 3
DC71D3BACBEC2697E1AB303711890A20 libz.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F6688000 00000000 00049000 A
79C2B7B4CBACD2644EBD222168DB4A30 libharfbuzz_ng.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F66D4000 00000000 00005000 4
72ACAB0BF45985CF656C61865F1F00C0 libusbhost.so
04-16 17:37:38.039 14459 10032 F google-breakpad: M F66DC000 00000000 00035000 9
5E916A0B085B76B427471A72DAA3DCE0 libjpeg.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F66FC000 00000000 000AA000 7
B71A199545D2FA02B4826BE938910300 libmedia.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F67BD000 00000000 0016C000 C
23844FE6C3B62EC7274369DA9FD6F960 libicui18n.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F692F000 00000000 00116000 1
A8E73D37A19F8B34811CD3D583A59BD0 libicuuc.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6A55000 00000000 00023000 4
E4CCAA8214BBA81BB3C8BBEA1B944270 libssl.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6A7B000 00000000 00090000 A
977D139AB994E7BF00762F32C9AC3B80 libcrypto.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6B18000 00000000 00052000 5
B62F9FC91FAF68B84F07FF357FA28CF0 libsonivox.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6B72000 00000000 0000F000 E
8011F69A51C616E2A4B17D44941A8CA0 libselinux.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6B83000 00000000 00008000 5
A270EDA69C9AE9922D990E1EFC3EA230 libhardware_legacy.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6B8F000 00000000 00003000 F
E9D4FCCF6E405AE1EA4D0C664332B3B0 libhardware.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6B94000 00000000 00004000 A
B6DBEAF1F9940CABBF3BA72CB340A320 libETC1.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6B9A000 00000000 0000D000 1
6054B4E1D38983A53C2E7B23628AA3F0 libGLESv2.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6BA9000 00000000 00008000 3
3715298D16B68CF67C2C04EC1E197930 libGLESv1_CM.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6BAB000 00000000 00064000 C
67249DD6288CAE4A8487F477E2B26FF0 libEGL.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6C1D000 00000000 00064000 F
14EE878CF7E7307E00743CF67E831350 libsqlite.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6C73000 00000000 0026C000 F
4F2D2D869E753ED5DEFDFC9A68ACB9F0 libskia.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6F01000 00000000 00008000 C
9B114DDA962B0D482D64D865DF427090 libcamera_metadata.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6F08000 00000000 00028000 3
8530E9F3426353C4643D7DDC8F00D2E0 libcamera_client.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6F38000 00000000 0003D000 4
21EC2470ADC1E8AC2B219F00BC673480 libinputflinger.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6F77000 00000000 0001C000 A
50D0552B435C547E78F6C3D74E340750 libinput.so
04-16 17:37:38.040 14459 10032 F google-breakpad: M F6F8F000 00000000 00056000 C
77DCF3B358374C2CB277097B6114BBF0 libgui.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F6FF2000 00000000 0000D000 2
4B24CA70877AADE6E262FD1A23356B70 libui.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F7002000 00000000 00007000 D
3E9989C47B8C2A00077AD0BE7BECAD30 libnetutils.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F700B000 00000000 00007000 D
116DC62B287BA8FD588EB9C0C1198A80 libnativehelper.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F7014000 00000000 00014000 E
7D03CC141B38BEB239DE5A62573844F0 libexpat.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F702B000 00000000 00027000 9
3F7486181300406ADD6C858EF4807170 libandroidfw.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F7055000 00000000 00003000 7
C2202F403B4FF18F6B999EACA13FD220 libmemtrack.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F705A000 00000000 00009000 6
93EC95DDE80DCD50DCB757834769FDD0 libbacktrace.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F7065000 00000000 0001F000 C
41244E02F2B1A9348A13ADF1001A8C20 libm.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F7087000 00000000 00072000 5
ADB232B821C3F60FEAC0B5ED76C7B500 libc.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F7108000 00000000 0008B000 7
F0D6F45453412BB9689ACFD2F635F510 libc++.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F7198000 00000000 00029000 A
C367DA17973983B33EBA1C079D4A2310 libwilhelm.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F71B7000 00000000 000E1000 C
E81AD04FAE8DE43E901992C8C42A8E90 libandroid_runtime.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F72A4000 00000000 0002A000 3
D278F7E71C0C60A781F67959A96BE8C0 libbinder.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F72D6000 00000000 00008000 B
A84D9C59146E7F3C93BA7C3F1059BA10 liblog.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F72E0000 00000000 00018000 2
31C3721132B6819F0BF5BD86FA2A2D10 libutils.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F72FB000 00000000 0000F000 6
EDEAE992F528F411B2007634D96A9210 libcutils.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F730D000 00000000 00004000 6
000958350BC531E0B3B24D53C87906B0 libNimsWrap.so
04-16 17:37:38.041 14459 10032 F google-breakpad: M F7344000 00000000 0001C000 7
BCF97A1A3ACCCB9E6D43355ABDD48BE0 linker
04-16 17:37:38.041 14459 10032 F google-breakpad: -----END BREAKPAD MICRODUMP---
--
04-19 23:58:00.418 20967 24222 F libc    : Fatal signal 11 (SIGSEGV), code 1, fa
ult addr 0x6390 in tid 24222 (Thread-16839)
04-19 23:58:00.493   752   752 F DEBUG   : *** *** *** *** *** *** *** *** *** *
** *** *** *** *** *** ***
04-19 23:58:00.494   752   752 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus3/
OnePlus3T:6.0.1/MXB48T/213713:user/release-keys'
04-19 23:58:00.495   752   752 F DEBUG   : Revision: '0'
04-19 23:58:00.495   752   752 F DEBUG   : ABI: 'arm64'
04-19 23:58:00.496   752   752 F DEBUG   : pid: 20967, tid: 24222, name: Thread-
16839  >>> com.magnetic.king <<<
04-19 23:58:00.496   752   752 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAP
ERR), fault addr 0x6390
04-19 23:58:00.528   752   752 F DEBUG   :     x0   0000000000000000  x1   00000
07f8ec9f000  x2   0000000058f78908  x3   0000000000000000
04-19 23:58:00.529   752   752 F DEBUG   :     x4   0000007fa85a72d0  x5   00000
00000000006  x6   0000007fa85a6000  x7   0000000000000000
04-19 23:58:00.529   752   752 F DEBUG   :     x8   00000000086f21b2  x9   00000
000086f21b2  x10  0000000058f78908  x11  00000000000654a9
04-19 23:58:00.529   752   752 F DEBUG   :     x12  0000000000000018  x13  00000
003e8000000  x14  0000000000000000  x15  0018bab78d425058
04-19 23:58:00.529   752   752 F DEBUG   :     x16  0000007f8cd35b70  x17  00000
07fa80cdaa4  x18  0000000000000000  x19  0000007f88a35000
04-19 23:58:00.529   752   752 F DEBUG   :     x20  0000000000000000  x21  00000
0000000001c  x22  0000000000000000  x23  0000000000000000
04-19 23:58:00.529   752   752 F DEBUG   :     x24  0000000000000005  x25  00000
00000000000  x26  0000007f8e2d7cb0  x27  0000007f8e2d8d3c
04-19 23:58:00.529   752   752 F DEBUG   :     x28  0000007f8b72dd50  x29  00000
07f8e2d6ad0  x30  0000007f8cd13820
04-19 23:58:00.529   752   752 F DEBUG   :     sp   0000007f8e2d6ad0  pc   00000
07f8cd13834  pstate 0000000060000000
04-19 23:58:00.537   752   752 F DEBUG   :
04-19 23:58:00.537   752   752 F DEBUG   : backtrace:
04-19 23:58:00.538   752   752 F DEBUG   :     #00 pc 000000000001e834  /data/ap
p/com.magnetic.king-2/lib/arm64/libvplayer.so
04-19 23:58:00.538   752   752 F DEBUG   :     #01 pc 000000000001e81c  /data/ap
p/com.magnetic.king-2/lib/arm64/libvplayer.so
04-19 23:58:00.859   752   752 F DEBUG   :
04-19 23:58:00.859   752   752 F DEBUG   : Tombstone written to: /data/tombstone
s/tombstone_03
04-23 22:00:57.263 10701 10701 E AndroidRuntime: FATAL EXCEPTION: main
04-23 22:00:57.263 10701 10701 E AndroidRuntime: Process: com.oneplus.security,
PID: 10701
04-23 22:00:57.263 10701 10701 E AndroidRuntime: java.lang.IllegalStateException
: Fragment DataUsagePrefFragment{79a472b} not attached to Activity
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at android.support.v4.ap
p.Fragment.getResources(Fragment.java:639)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at android.support.v4.ap
p.Fragment.getString(Fragment.java:661)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at com.oneplus.security.
network.view.DataUsagePrefFragment.getDataInvalidValueHintString(DataUsagePrefFr
agment.java:360)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at com.oneplus.security.
network.view.DataUsagePrefFragment.access$200(DataUsagePrefFragment.java:38)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at com.oneplus.security.
network.view.DataUsagePrefFragment$6.run(DataUsagePrefFragment.java:292)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at android.os.Handler.ha
ndleCallback(Handler.java:739)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at android.os.Handler.di
spatchMessage(Handler.java:95)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at android.os.Looper.loo
p(Looper.java:148)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at android.app.ActivityT
hread.main(ActivityThread.java:5507)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at java.lang.reflect.Met
hod.invoke(Native Method)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at com.android.internal.
os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-23 22:00:57.263 10701 10701 E AndroidRuntime:        at com.android.internal.
os.ZygoteInit.main(ZygoteInit.java:616)
04-25 11:02:01.307  5736  5736 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM P
ROCESS: main
04-25 11:02:01.307  5736  5736 E AndroidRuntime: java.lang.reflect.InvocationTar
getException
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at java.lang.reflect.Met
hod.invoke(Native Method)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at me.piebridge.brevent.
server.BreventServer.main(BreventServer.java:1647)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit.nativeFinishInit(Native Method)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit.main(RuntimeInit.java:265)
04-25 11:02:01.307  5736  5736 E AndroidRuntime: Caused by: java.lang.NumberForm
atException: Invalid int: "2564671175"
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at java.lang.Integer.inv
alidInt(Integer.java:138)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at java.lang.Integer.par
se(Integer.java:413)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at java.lang.Integer.par
seInt(Integer.java:367)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at java.lang.Integer.par
seInt(Integer.java:334)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at me.piebridge.brevent.
server.d.a(HideApi.java:584)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at me.piebridge.brevent.
server.d.c(HideApi.java:543)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at me.piebridge.brevent.
server.d.d(HideApi.java:330)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at me.piebridge.brevent.
server.BreventServer.r(BreventServer.java:1432)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at me.piebridge.brevent.
server.BreventServer.g(BreventServer.java:493)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at me.piebridge.brevent.
server.BreventServer.handleMessage(BreventServer.java:392)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at android.os.Handler.di
spatchMessage(Handler.java:102)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at android.os.Looper.loo
p(Looper.java:148)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        at me.piebridge.brevent.
server.BreventServer.a(BreventServer.java:1620)
04-25 11:02:01.307  5736  5736 E AndroidRuntime:        ... 4 more
04-25 11:02:01.308  5736  5736 E AndroidRuntime: Error reporting crash
04-25 11:02:01.308  5736  5736 E AndroidRuntime: java.lang.RuntimeException: Bad
 file descriptor
04-25 11:02:01.308  5736  5736 E AndroidRuntime:        at android.os.BinderProx
y.transactNative(Native Method)
04-25 11:02:01.308  5736  5736 E AndroidRuntime:        at android.os.BinderProx
y.transact(Binder.java:536)
04-25 11:02:01.308  5736  5736 E AndroidRuntime:        at android.app.ActivityM
anagerProxy.handleApplicationCrash(ActivityManagerNative.java:4646)
04-25 11:02:01.308  5736  5736 E AndroidRuntime:        at com.android.internal.
os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
04-25 11:02:01.308  5736  5736 E AndroidRuntime:        at java.lang.ThreadGroup
.uncaughtException(ThreadGroup.java:693)
04-25 11:02:01.308  5736  5736 E AndroidRuntime:        at java.lang.ThreadGroup
.uncaughtException(ThreadGroup.java:690)

C:\Users\Administrator\Desktop\platform-tools-latest-windows\platform-tools>^V

**Comment by liudongmiao** [comment]
> 04-25 11:02:01.307 5736 5736 E AndroidRuntime: Caused by: java.lang.NumberForm
atException: Invalid int: "2564671175"

稳定重现么？

**Comment by liudongmiao** [comment]
你确定是最新稳定版 1.1 么？

**Comment by fj11101** [comment]
问题是偶然出现一次，版本不是最新版本。
现在更新1.1问题未出现。

**Comment by liudongmiao** [comment]
还记得版本么？没有版本号的话，我都不知道出问题的地方。
