### ISSUE TITLE
桌面小控件问题

### ISSUE THREAD

**Issue by houfukude** [liudongmiao/Brevent#45]
如果阻止了Google keep
keep桌面小控件点击启动keep会闪退
貌似google日历也有类似情况

**Comment by liudongmiao** [comment]
最新版优化了这个，目前我测试时并未出现。

**Comment by liudongmiao** [comment]
请使用最新 beta 版测试：piebridge.me/br/

如果还有这个问题，请重开这个问题，谢谢。
