### ISSUE TITLE
重启后黑域失效，需要重新adb

### ISSUE THREAD

**Issue by THLIVSQAZ** [liudongmiao/Brevent#450]
如题，重启后开启黑域，要求adb启动，目前在使用root，root模式重启后需要启动黑域才会自动su启动服务，安卓原生6.0.1，未安装任何优化软件，黑域版本1.1

**Comment by liudongmiao** [comment]
root 模式实验性，能用就用，不能用就不用。我不提供任何支持。

**Comment by THLIVSQAZ** [comment]
那adb脚本重启失效有解决办法吗？

**Comment by liudongmiao** [comment]
你都不给日志，我能知道问题才怪。我只能说，我半个多月，升级无数次，还没有出现要重新 adb 情况。

**Comment by liudongmiao** [comment]
你说重启失效啊，那么高权限，不失效才不正常。这是系统限制。

**Comment by THLIVSQAZ** [comment]
了解了，谢谢，支持开发者
