### ISSUE TITLE
三星S8+ 开启adb不成功

### ISSUE THREAD

**Issue by Princezhu** [liudongmiao/Brevent#452]
三星S8+，部署adb的时候，最后一步，总是显示“no devices found”，详情见图，不知道是不是驱动的原因？还是哪里出错了？求高人带领
![_20170426131204](https://cloud.githubusercontent.com/assets/28036058/25417876/65fb5522-2a82-11e7-8002-f30b4393d59e.png)

**Comment by liudongmiao** [comment]
你都找不到设备啊...安装了手机驱动了么？

另外， S8 哪里买的，国内有现货了么？

**Comment by Princezhu** [comment]
国行要5.25上市。我在韩国，预购的，用了一个周了，算是首批用户吧
我也觉得可能是驱动的原因，但是现在官方也没给驱动，只是手机插电脑上可以读取。。。

**Comment by liudongmiao** [comment]
这里找找吧：https://developer.android.google.cn/studio/run/oem-usb.html

还有一个办法，找台 mac 或者 linux... mac 和 linux 下都不需要驱动。

**Comment by Princezhu** [comment]
我之前是在win7上试的，出现问题那个画面
刚刚我又用我个人的pc，win10上试的，出现了下边这个画面。。。
![123](https://cloud.githubusercontent.com/assets/28036058/25421598/98c56dec-2a98-11e7-8d2d-ea66b947660c.png)
另外，我给你看一下，S8+的 开发者选项 的截图，里边没有 adb调试，会不会是这个原因？
![screenshot_smartselect_2017-04-26-15-55-35](https://cloud.githubusercontent.com/assets/28036058/25421702/01f09c9c-2a99-11e7-9676-714e983b2dda.png)

**Comment by chanssl** [comment]
unauthorized，是否未授权（adb devices 会弹出是否信任该设备的授权）？
如果是的话，撤回USB除错授权后再操作看看

**Comment by Princezhu** [comment]
@chanssl 我的手机上就没出来过这样的提示。。。手机连上电脑上以后就再没出来过什么提示
难道手机上除了安装黑域这个app以外，还要安装别的app？

**Comment by Princezhu** [comment]
@chanssl 谢谢建议，我先在手机上 撤回了USB除错 以后，最终还是用我的MAC成功启动的黑域，谢谢热心帮忙

**Comment by Princezhu** [comment]
@liudongmiao 柳大好，最终我还是用我的MAC，成功开启了黑域，win不知道有什么问题，可能还是驱动的原因吧。。。

**Comment by Princezhu** [comment]
@liudongmiao 柳大好，我在学着使用 黑域 ，有几点疑问，特来咨询   1 黑域是不是自动工作的？即便我不进行任何设置，它也是有自己的处理规则的对吗？  2 我的设置界面，如下图，没有找到“允许同步” “允许FCM推送” 的选项，是新版本把这两个功能去掉了吗？还是，捐赠之后才能出现这样的选项？    以上两点疑问，望能得到柳大的解疑
![screenshot_smartselect_2017-04-27-12-08-31](https://cloud.githubusercontent.com/assets/28036058/25466323/f008dbde-2b42-11e7-80df-56b546a841d8.png)

**Comment by liudongmiao** [comment]
使用方面，阅读这个文档吧：https://piebridge.me/br/br.pdf

允许同步，需要你单独为每个应用设置。

1.0.1 起，移除选项“允许 FCM 推送”，默认启用（需要单独开启“允许同步”）。

**Comment by Princezhu** [comment]
@liudongmiao 谢柳大，pdf文档非常有用

**Comment by liudongmiao** [comment]
有空的话，我会更新截图为最新的版本。目前没什么空。

**Comment by Princezhu** [comment]
我是在coolapk上下载的你的app，对比的截图也是coolapk上的

**Comment by liudongmiao** [comment]
酷安上我早就不更新了...

**Comment by Princezhu** [comment]
@liudongmiao 那现在官方的发布平台是哪个呢？除了那个网址

**Comment by liudongmiao** [comment]
play 商店

**Comment by liudongmiao** [comment]
此外，还有应用宝。

**Comment by Princezhu** [comment]
了解了，谢柳大

**Comment by liudongmiao** [comment]
到现在为止，我在以下商店上架，文件内容完全一致。

- Play 商店
- 应用宝
- 魅族商店
- 锤子商店，自 1.1.1 起才同步更新
- 个人网站：https://piebridge.me/br/

目前没有任何计划新增这个商店名单，没有任何计划发布到酷安。

**Comment by Princezhu** [comment]
再问下，play版的必须得在play上支付，才能使用高级功能吧？
那我在https://piebridge.me/br/这个网站上下载安装以后使用高级功能是可以的吧？
那如果我用play更新新的版本，那以后还能用高级功能嘛？

**Comment by liudongmiao** [comment]
只有 Play 版的实验性功能才强制捐赠。其它任何地方安装的，都可以自由使用实验性功能。
实验性功能，基本包括一些不稳定或者没有必要，或者我自己也不用的功能，并不是高级功能。

通过 Play 更新后，会自动变成  Play 版。

**Comment by Princezhu** [comment]
好的，明白了，谢谢柳大
