### ISSUE TITLE
黑域方法

### ISSUE THREAD

**Issue by Steve0k** [liudongmiao/Brevent#453]
可否将黑域方法更改为只从最近列表划掉后才进行黑域，未划掉则不处理。或者从软件中如何设置可以达到比效果？

**Comment by Steve0k** [comment]
或者从软件中如何设置可以达到此效果？

**Comment by liudongmiao** [comment]
后台应用超时设为 11.5 天，以及不要使用 Back 键退出应用。

如果你过了 11.5 天，还记得这个应用，再找我我可以把这个调大 10 倍。

我个人建议，你不要使用黑域。

其实，最近列表只会展示最近的应用，大约 6 个小时。你想得太多了。
