### ISSUE TITLE
黑域版本与使用

### ISSUE THREAD

**Issue by JoeLeeWu** [liudongmiao/Brevent#455]
在上网找到黑域3.1.4版本和1.1版本，请问有什么区别吗？另外我机子是安卓5.0，能使用黑域吗？

**Comment by liudongmiao** [comment]
直接看包名吧，我本人仅维护 me.piebridge.brevent，其它的黑域，本人不作任何评价。

**Comment by JoeLeeWu** [comment]
只支持安卓7.0与7.1？

**Comment by naloder** [comment]
现在支持5.0-7.1
