### ISSUE TITLE
华为荣耀Magic，0.87之后的所有版本都无法启动黑域

### ISSUE THREAD

**Issue by vinsonkwong** [liudongmiao/Brevent#456]
柳大，请帮忙看看是否那里出了问题。
机型：华为荣耀Magic
版本：1.2.530.2
安卓版本：6.0
情况描述：只有0.87版本可以使用，之后的所有版本，包括现在play上的最新版本，都无法启动黑域
日志如下

![Uploading TIM截图20170427151910.png…]()

**Comment by liudongmiao** [comment]
日志，日志，日志。

**Comment by vinsonkwong** [comment]
柳大，不知道为什么就是上传不了日志，我在支付宝里传给你了，不好意思

**Comment by liudongmiao** [comment]
不在这里传日志的，都是耍流氓。

**Comment by vinsonkwong** [comment]
柳大，不是我不想传，是上传n次都提示错误呀(>﹏<)
发自网易邮箱大师
在2017年04月27日 17:27，Liu DongMiao 写道： 不在这里传日志的，都是耍流氓。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/liudongmiao/Brevent","title":"liudongmiao/Brevent","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/liudongmiao/Brevent"}},"updates":{"snippets":[{"icon":"PERSON","message":"@liudongmiao in #456: 不在这里传日志的，都是耍流氓。"}],"action":{"name":"View Issue","url":"https://github.com/liudongmiao/Brevent/issues/456#issuecomment-297662717"}}}

**Comment by vinsonkwong** [comment]
这样可以吗？发自网易邮箱大师
            在2017年04月27日 17:45，vinsonkwong 写道： 
柳大，不是我不想传，是上传n次都提示错误呀(>﹏<)
发自网易邮箱大师
在2017年04月27日 17:27，Liu DongMiao 写道： 不在这里传日志的，都是耍流氓。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/liudongmiao/Brevent","title":"liudongmiao/Brevent","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/liudongmiao/Brevent"}},"updates":{"snippets":[{"icon":"PERSON","message":"@liudongmiao in #456: 不在这里传日志的，都是耍流氓。"}],"action":{"name":"View Issue","url":"https://github.com/liudongmiao/Brevent/issues/456#issuecomment-297662717"}}}

**Comment by vinsonkwong** [comment]
柳大，有其他的途径可以传日志给你吗？我全局代理了还是上传不了

**Comment by liudongmiao** [comment]
我看了那个图片，日志里没啥有用的信息。你问问别人吧。

**Comment by vinsonkwong** [comment]
好吧，无论如何，还是得感谢柳大。那我还是用回我的nexus吧
