### ISSUE TITLE
报bug

### ISSUE THREAD

**Issue by ads2016** [liudongmiao/Brevent#459]
Android6.01 
checking.....brevent_server started, pid: 9910
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-29 21:19:55.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-29 21:19:55.000' -d -s BreventLoader BreventServer
04-29 21:19:56.702  9896  9896 D BreventLoader: loader path: /data/app/me.piebridge.brevent-2/base.apk
04-29 21:19:57.942  9910  9910 I BreventServer: Brevent Server xy(1.1) started
04-29 21:19:57.962  9910  9910 I BreventServer: brevent user: 0, uid: 2000
04-29 21:19:57.962  9910  9910 I BreventServer: brevent data directory: /data/user/0/com.android.shell
04-29 21:19:58.242  9910  9910 I BreventServer: loading brevent list
04-29 21:19:58.252  9910  9910 I BreventServer: loading brevent conf
04-29 21:19:58.442  9910  9910 D BreventServer: check and brevent
04-29 21:19:58.702  9896  9896 E BreventLoader: worker 9910 exited on signal 9
04-29 21:19:58.702  9896  9896 D BreventLoader: signal arrived, update: 0
04-29 21:19:58.702  9880  9880 D BreventLoader: worker 9896 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
禁用 selinux 看看

**Comment by ads2016** [comment]
但是没有root怎么办

**Comment by liudongmiao** [comment]
来更多日志，或者约个时间，我登录你电脑看看。
