### ISSUE TITLE
apkpure即便从应用切换器中划掉仍然会在通州栏上继续下载app

### ISSUE THREAD

**Issue by shywu** [liudongmiao/Brevent#46]
如题。版本0.5pre2。以前版本没有这个问题。
谢谢！

**Comment by liudongmiao** [comment]
过会再检查。目前不是即时的，如果发现一直这样，比如一分钟之后还这样，请报告。

目前已经发布 pre4，优化了这块的处理。

**Comment by liudongmiao** [comment]
请使用最新 beta 版测试：piebridge.me/br/

如果还有这个问题，请重开，谢谢。
