### ISSUE TITLE
root模式失败

### ISSUE THREAD

**Issue by vvb2060** [liudongmiao/Brevent#460]
Android 7.1.2 magiskSU Nexus 6p原生 应用内root开启失败

手动运行脚本输出
Error dumping service info: (Unknown error -2147483646) package
please install me.piebridge.brevent

直接运行so文件输出
checking...brevent_server started, pid: 16841
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '04-30 10:18:52.000' -d
04-30 10:18:53.575 16841 16841 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-30 10:18:53.575 16841 16841 E AndroidRuntime: java.lang.reflect.InvocationTargetException
04-30 10:18:53.575 16841 16841 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 10:18:53.575 16841 16841 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1717)
04-30 10:18:53.575 16841 16841 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-30 10:18:53.575 16841 16841 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
04-30 10:18:53.575 16841 16841 E AndroidRuntime: Caused by: me.piebridge.brevent.server.d$a: Can't dump activities
04-30 10:18:53.575 16841 16841 E AndroidRuntime: 	at me.piebridge.brevent.server.d.d(HideApi.java:334)
04-30 10:18:53.575 16841 16841 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.u(BreventServer.java:1486)
04-30 10:18:53.575 16841 16841 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:479)
04-30 10:18:53.575 16841 16841 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1669)
04-30 10:18:53.575 16841 16841 E AndroidRuntime: 	... 4 more
04-30 10:18:53.576 16841 16841 E AndroidRuntime: Error reporting crash
04-30 10:18:53.576 16841 16841 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-30 10:18:53.576 16841 16841 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
04-30 10:18:53.576 16841 16841 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
04-30 10:18:53.576 16841 16841 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5133)
04-30 10:18:53.576 16841 16841 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
04-30 10:18:53.576 16841 16841 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
04-30 10:18:53.576 16841 16841 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-30 10:18:52.000' -d -s BreventLoader BreventServer
04-30 10:18:52.813 16822 16822 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-30 10:18:53.266 16841 16841 I BreventServer: Brevent Server xy(1.1-1-ged587ca) started
04-30 10:18:53.274 16841 16841 I BreventServer: brevent user: 0, uid: 0
04-30 10:18:53.276 16841 16841 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
04-30 10:18:53.494 16841 16841 I BreventServer: loading brevent list
04-30 10:18:53.498 16841 16841 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 140
04-30 10:18:53.498 16841 16841 I BreventServer: loading brevent conf
04-30 10:18:53.510 16841 16841 D BreventServer: Can't dump widgets (ignore)
04-30 10:18:53.559 16841 16841 D BreventServer: check and brevent
04-30 10:18:53.561 16841 16841 D BreventServer: Can't dump notifications
04-30 10:18:53.571 16841 16841 D BreventServer: Can't dump widgets (ignore)
04-30 10:18:53.575 16841 16841 E BreventServer: Can't dump activities
04-30 10:18:53.575 16841 16841 E BreventServer: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
04-30 10:18:53.575 16841 16841 E BreventServer: 	at android.os.BinderProxy.transactNative(Native Method)
04-30 10:18:53.575 16841 16841 E BreventServer: 	at android.os.BinderProxy.transact(Binder.java:615)
04-30 10:18:53.575 16841 16841 E BreventServer: 	at android.os.BinderProxy.dump(Binder.java:631)
04-30 10:18:53.575 16841 16841 E BreventServer: 	at me.piebridge.brevent.server.d.d(HideApi.java:328)
04-30 10:18:53.575 16841 16841 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.u(BreventServer.java:1486)
04-30 10:18:53.575 16841 16841 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:479)
04-30 10:18:53.575 16841 16841 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1669)
04-30 10:18:53.575 16841 16841 E BreventServer: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 10:18:53.575 16841 16841 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1717)
04-30 10:18:53.575 16841 16841 E BreventServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-30 10:18:53.575 16841 16841 E BreventServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
04-30 10:18:53.590 16822 16822 E BreventLoader: worker 16841 exited on signal 9
04-30 10:18:53.590 16822 16822 D BreventLoader: signal arrived, update: 0
04-30 10:18:53.592 16821 16821 D BreventLoader: worker 16822 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by xiaoyaoyuxin** [comment]
同样遇到这个问题。

**Comment by liudongmiao** [comment]
> android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died

禁用 selinux 看看

**Comment by vvb2060** [comment]
禁用后的确能开启。
问题是以前用的好好的，SELinux也开着，今天就备份应用恢复出厂来翻新了下，发现出问题了，很奇怪。
另外，用SuperSU正常，准备换了

**Comment by vvb2060** [comment]
目前状况是设置为Permissive来启动服务，后恢复Enforcing黑域可以正常运行。能否考虑改变一下应用内root启动方式？

**Comment by vvb2060** [comment]
摸索出了很奇怪的规律，magisk坑额。
在service.d里放脚本setenforce 0，开机后手动setenforce 1，可以正常root启动。
什么都不放，开机后无法启动服务，setenforce 0后正常，再setenforce 1后服务不关闭
