### ISSUE TITLE
微信不进入standby

### ISSUE THREAD

**Issue by dfliaoyue** [liudongmiao/Brevent#462]
开启微信推送支持后，经常出现不进入standby模式的情况，似乎对出现在使用流量的情况。

**Comment by dfliaoyue** [comment]
补充：有时能正常standby，有时很长时间都不行。期间没有微信通知。
另外有个小问题，这种情况下微信弹出的无网络的系统通知有办法屏蔽吗

**Comment by liudongmiao** [comment]
如果你不是特别强迫，或者根本不 care 微信是否能及时收到消息，否则不要黑域微信。

这些问题，你但凡早期关注过酷安，关注过 github，都会从中找到答案。

针对特定 APP 的问题，没有任何意义。就我而言，不排除操作系统限制，黑域处理微信没有任何问题。

**Comment by liudongmiao** [comment]
1. 后台应用超时后，才会待机
2. 充电时，不会待机
3. 待机后，收到通知，系统会解除待机状态

4. 微信是非正常 Back，所以，目前的识别非正常 Back 是实验性功能，仅支持识别回到桌面时的 非正常 Back。这个也会导致不能待机。

5. 微信无网络通知，是正常的。待机后就会没有网络，但是它还是可以运行的。如果你设置了允许同步，还能被其它类型通知唤醒。

**Comment by kcschan** [comment]
确实可以观察到以下的情况：
步骤：
1，确定GCM通信良好
2，离开微信，返回启动器
3，用am set-inactive把微信置于app-standby状态
4，给微信发送消息，可以看到heads up通知，同时可以在GCM里看到推送

5，通过黑域让微信处于app-standby后(未force-stop)，再给微信发送消息，不会出现heads up通知，且同时可以看到GCM收到了该推送

6，无论如何，通过GCM传递的信息不会触发force-stop下的微信显示通知，这是预期会发生的事情。
