### ISSUE TITLE
1.2 功能点

### ISSUE THREAD

**Issue by liudongmiao** [liudongmiao/Brevent#463]
- [ ] 实验性功能：~多用户~工作模式支持
- [ ] 高级功能：主动低电耗
- [ ] 日志功能
  成功启动黑域后，自己给自己日志权限。
  分为几部分：反馈时主动获取日志，实时查看黑域过程日志，三是针对应用的唤醒与黑域日志。

**Comment by liaobin** [comment]
支持doze好评

**Comment by xiangcl** [comment]
什么时候发布？

**Comment by MisterGlasses** [comment]
doze??

**Comment by CVN-77** [comment]
“高级功能：主动低电耗”这个赞，息屏更省电

**Comment by liudongmiao** [comment]
@CVN-77 这个功能亮屏也可以，但我还没想好怎样开放。

**Comment by MisterGlasses** [comment]
很期待呢 不过我这破手机进入doze后 微信收不到消息（加了白名单跟忽略电池优化）

**Comment by ydj73** [comment]
期待呀，

**Comment by darkwolf99** [comment]
最好不要亮屏也doze，一些rom在亮屏状态下显示的时钟会停止，虽然系统内部时钟并没停止

**Comment by xiangcl** [comment]
各位有没有用锤子手机的，我想知道锤子手机安装google套件后FCM是否完美？会不会像三星一样一小时才连接一次。

**Comment by Soylent-Green-Yummy** [comment]
很期待工作模式，现在把国产毒瘤都放在里面了，用island和绿色守护来控制冻结。但是控制逻辑太简单，也不支持FCM唤醒，没有黑域好用。

**Comment by Zero3K** [comment]
So, there will be a function similar to what Greenify does which will be added to Brevent soon?

**Comment by mmemi** [comment]
后台应用超时希望能加2小时和3小时选项？

**Comment by liudongmiao** [comment]
- com.smartisanos.appstore
- com.meizu.mstore
