### ISSUE TITLE
Google 日曆新增行程時崩潰

### ISSUE THREAD

**Issue by kimlu235711** [liudongmiao/Brevent#464]
附上Log
C:\Users\Shanyu>adb -d logcat -d -b main -s BreventServer BreventLoader
05-02 21:39:08.844  7697  7697 D BreventServer: check and brevent
05-02 21:39:08.935  7697  7697 D BreventServer: widgets: {com.google.android.calendar, com.htc.widget.weatherclock}
05-02 21:39:08.935  7697  7697 D BreventServer: running: {}
05-02 21:39:08.935  7697  7697 D BreventServer: recent: {com.google.android.calendar=1755}
05-02 21:39:08.945  7697  7697 D BreventServer: inactive for com.android.vending: 0, timeout: 300
05-02 21:39:08.945  7697  7697 D BreventServer: inactive for com.htc.bidhandler: 0, timeout: 300
05-02 21:39:08.945  7697  7697 D BreventServer: inactive for com.android.printspooler: 0, timeout: 300
05-02 21:39:08.945  7697  7697 D BreventServer: inactive for com.facebook.orca: 0, timeout: 300
05-02 21:39:08.982  7697  7697 D BreventServer: com.htc.htcpowermanager depended by {com.android.settings}
05-02 21:39:08.982  7697  7697 D BreventServer: com.android.chrome depended by {com.google.android.googlequicksearchbox, com.google.android.gms, com.facebook.orca}
05-02 21:39:08.982  7697  7697 D BreventServer: com.google.android.gms depended by {com.android.vending, com.android.settings}
05-02 21:39:08.982  7697  7697 D BreventServer: service: {com.android.vending, com.htc.bidhandler}
05-02 21:39:08.982  7697  7697 D BreventServer: back: {com.google.android.calendar}
05-02 21:39:08.982  7697  7697 D BreventServer: blocking: {com.android.vending, com.htc.bidhandler, com.android.printspooler, com.google.android.calendar, com.facebook.orca}
05-02 21:39:08.983  7697  7697 D BreventServer: top: {}
05-02 21:39:08.983  7697  7697 D BreventServer: home: {com.asus.launcher, com.android.systemui}
05-02 21:39:08.983  7697  7697 D BreventServer: current: com.asus.launcher
05-02 21:39:08.983  7697  7697 D BreventServer: unsafe: {}
05-02 21:39:08.983  7697  7697 D BreventServer: final blocking: {com.android.vending, com.htc.bidhandler, com.android.printspooler, com.google.android.calendar, com.facebook.orca}
05-02 21:39:08.984  7697  7697 D BreventServer: notifications: {com.facebook.orca=[1, 1, 354]}
05-02 21:39:08.984  7697  7697 D BreventServer: noRecent: {com.android.vending, com.htc.bidhandler, com.android.printspooler, com.facebook.orca}
05-02 21:39:08.984  7697  7697 D BreventServer: foreground service: {com.facebook.orca}
05-02 21:39:08.984  7697  7697 D BreventServer: gcm: {org.telegram.messenger, com.htc.cs.pns, jp.naver.line.android, org.cwb, com.android.vending, com.google.android.apps.classroom, com.google.android.apps.docs, com.google.android.gsf, com.esri.arcgis.android.idt.EPA.HL, com.google.android.apps.photos, com.facebook.katana, com.facebook.orca}
05-02 21:39:08.984  7697  7697 D BreventServer: sticky notification: {com.facebook.orca}
05-02 21:39:08.988  7697  7697 D BreventServer: Force stop com.android.vending(priority service)
05-02 21:39:08.998  7697  7697 D BreventServer: Force stop com.htc.bidhandler(priority service)
05-02 21:39:08.999  7697  7697 D BreventServer: ignore com.android.printspooler, wait for the service check
05-02 21:39:09.060  7697  7697 D BreventServer: check again in 3600s
05-02 21:39:09.061  7697  7697 D BreventServer: check and brevent, took 215ms
05-02 21:39:12.314  7697  7697 D BreventServer: check and brevent
05-02 21:39:12.395  7697  7697 D BreventServer: widgets: {com.google.android.calendar, com.htc.widget.weatherclock}
05-02 21:39:12.395  7697  7697 D BreventServer: running: {}
05-02 21:39:12.395  7697  7697 D BreventServer: recent: {com.google.android.calendar=1751}
05-02 21:39:12.403  7697  7697 D BreventServer: inactive for com.android.printspooler: 0, timeout: 300
05-02 21:39:12.403  7697  7697 D BreventServer: inactive for com.facebook.orca: 0, timeout: 300
05-02 21:39:12.438  7697  7697 D BreventServer: com.htc.htcpowermanager depended by {com.android.settings}
05-02 21:39:12.439  7697  7697 D BreventServer: com.android.chrome depended by {com.google.android.googlequicksearchbox, com.google.android.gms, com.facebook.orca}
05-02 21:39:12.439  7697  7697 D BreventServer: com.google.android.gms depended by {com.android.settings}
05-02 21:39:12.439  7697  7697 D BreventServer: service: {com.android.printspooler}
05-02 21:39:12.439  7697  7697 D BreventServer: back: {com.google.android.calendar}
05-02 21:39:12.439  7697  7697 D BreventServer: blocking: {com.android.printspooler, com.google.android.calendar, com.facebook.orca}
05-02 21:39:12.440  7697  7697 D BreventServer: top: {}
05-02 21:39:12.440  7697  7697 D BreventServer: home: {com.asus.launcher, com.android.systemui}
05-02 21:39:12.440  7697  7697 D BreventServer: current: com.asus.launcher
05-02 21:39:12.440  7697  7697 D BreventServer: unsafe: {}
05-02 21:39:12.440  7697  7697 D BreventServer: final blocking: {com.android.printspooler, com.google.android.calendar, com.facebook.orca}
05-02 21:39:12.440  7697  7697 D BreventServer: notifications: {com.facebook.orca=[1, 1, 354]}
05-02 21:39:12.440  7697  7697 D BreventServer: noRecent: {com.android.printspooler, com.facebook.orca}
05-02 21:39:12.440  7697  7697 D BreventServer: foreground service: {com.facebook.orca}
05-02 21:39:12.440  7697  7697 D BreventServer: gcm: {org.telegram.messenger, com.htc.cs.pns, jp.naver.line.android, org.cwb, com.android.vending, com.google.android.apps.classroom, com.google.android.apps.docs, com.google.android.gsf, com.esri.arcgis.android.idt.EPA.HL, com.google.android.apps.photos, com.facebook.katana, com.facebook.orca}
05-02 21:39:12.441  7697  7697 D BreventServer: sticky notification: {com.facebook.orca}
05-02 21:39:12.445  7697  7697 D BreventServer: Force stop com.android.printspooler(priority service)
05-02 21:39:12.476  7697  7697 D BreventServer: check again in 3600s
05-02 21:39:12.476  7697  7697 D BreventServer: check and brevent, took 160ms
05-02 21:39:20.727  7697  7697 D BreventServer: pause activity, tid: 2907, packageName: com.asus.launcher
05-02 21:39:21.001  7697  7697 D BreventServer: pause activity, tid: 2913, packageName: com.google.android.calendar
05-02 21:40:01.726  7697  7697 D BreventServer: com.htc.Weather: priority
05-02 21:40:20.756  7697  7697 D BreventServer: check and brevent
05-02 21:40:20.865  7697  7697 D BreventServer: widgets: {com.google.android.calendar, com.htc.widget.weatherclock}
05-02 21:40:20.865  7697  7697 D BreventServer: running: {com.google.android.calendar=2130}
05-02 21:40:20.865  7697  7697 D BreventServer: recent: {com.google.android.calendar=1741}
05-02 21:40:20.894  7697  7697 D BreventServer: inactive for com.android.providers.calendar: 0, timeout: 300
05-02 21:40:20.894  7697  7697 D BreventServer: inactive for com.google.android.gsf: 0, timeout: 300
05-02 21:40:20.894  7697  7697 D BreventServer: inactive for com.google.android.calendar: 59, timeout: 300
05-02 21:40:20.894  7697  7697 D BreventServer: inactive for com.facebook.katana: 0, timeout: 300
05-02 21:40:20.894  7697  7697 D BreventServer: inactive for com.facebook.orca: 0, timeout: 300
05-02 21:40:20.894  7697  7697 D BreventServer: inactive for com.htc.Weather: 0, timeout: 300
05-02 21:40:20.946  7697  7697 D BreventServer: com.htc.htcpowermanager depended by {com.android.settings}
05-02 21:40:20.946  7697  7697 D BreventServer: com.android.chrome depended by {com.google.android.googlequicksearchbox, com.google.android.gms, com.facebook.orca}
05-02 21:40:20.946  7697  7697 D BreventServer: com.google.android.gms depended by {com.google.android.calendar, com.android.settings}
05-02 21:40:20.946  7697  7697 D BreventServer: service: {}
05-02 21:40:20.946  7697  7697 D BreventServer: back: {}
05-02 21:40:20.946  7697  7697 D BreventServer: blocking: {com.android.providers.calendar, com.google.android.gsf, com.facebook.katana, com.facebook.orca, com.htc.Weather}
05-02 21:40:20.948  7697  7697 D BreventServer: top: {com.google.android.calendar}
05-02 21:40:20.948  7697  7697 D BreventServer: home: {com.asus.launcher, com.android.systemui}
05-02 21:40:20.948  7697  7697 D BreventServer: current: com.google.android.calendar
05-02 21:40:20.948  7697  7697 D BreventServer: unsafe: {}
05-02 21:40:20.948  7697  7697 D BreventServer: final blocking: {com.android.providers.calendar, com.google.android.gsf, com.facebook.katana, com.facebook.orca, com.htc.Weather}
05-02 21:40:20.948  7697  7697 D BreventServer: notifications: {com.facebook.orca=[354]}
05-02 21:40:20.948  7697  7697 D BreventServer: noRecent: {com.android.providers.calendar, com.google.android.gsf, com.facebook.katana, com.facebook.orca, com.htc.Weather}
05-02 21:40:20.948  7697  7697 D BreventServer: foreground service: {com.facebook.orca}
05-02 21:40:20.948  7697  7697 D BreventServer: gcm: {org.telegram.messenger, com.htc.cs.pns, jp.naver.line.android, org.cwb, com.android.vending, com.google.android.apps.classroom, com.google.android.apps.docs, com.google.android.gsf, com.esri.arcgis.android.idt.EPA.HL, com.google.android.apps.photos, com.facebook.katana, com.facebook.orca}
05-02 21:40:20.948  7697  7697 D BreventServer: sticky notification: {com.facebook.orca}
05-02 21:40:20.967  7697  7697 D BreventServer: Force stop com.android.providers.calendar(noRecent)
05-02 21:40:21.025  7697  7697 D BreventServer: Force stop com.google.android.gsf(priority service)
05-02 21:40:21.031  7697  7697 D BreventServer: Force stop com.facebook.katana(priority service)
05-02 21:40:21.033  7697  7697 D BreventServer: ignore com.htc.Weather, wait for the service check
05-02 21:40:21.051  7697  7697 D BreventServer: check again in 241s
05-02 21:40:21.051  7697  7697 D BreventServer: check and brevent, took 291ms
05-02 21:40:21.058  7697  7697 D BreventServer: resume activity, tid: 2186, packageName: com.asus.launcher, launcher: com.asus.launcher
05-02 21:40:21.058  7697  7697 D BreventServer: abnormal back: com.google.android.calendar
05-02 21:40:24.062  7697  7697 D BreventServer: check and brevent
05-02 21:40:24.148  7697  7697 D BreventServer: widgets: {com.google.android.calendar, com.htc.widget.weatherclock}
05-02 21:40:24.149  7697  7697 D BreventServer: running: {}
05-02 21:40:24.149  7697  7697 D BreventServer: recent: {com.google.android.calendar=1737}
05-02 21:40:24.159  7697  7697 D BreventServer: inactive for com.facebook.orca: 0, timeout: 300
05-02 21:40:24.159  7697  7697 D BreventServer: inactive for com.htc.Weather: 0, timeout: 300
05-02 21:40:24.207  7697  7697 D BreventServer: com.htc.htcpowermanager depended by {com.android.settings}
05-02 21:40:24.207  7697  7697 D BreventServer: com.android.chrome depended by {com.google.android.googlequicksearchbox, com.google.android.gms, com.facebook.orca}
05-02 21:40:24.207  7697  7697 D BreventServer: com.google.android.gms depended by {com.android.settings}
05-02 21:40:24.208  7697  7697 D BreventServer: service: {}
05-02 21:40:24.208  7697  7697 D BreventServer: back: {com.google.android.calendar}
05-02 21:40:24.208  7697  7697 D BreventServer: blocking: {com.google.android.calendar, com.facebook.orca, com.htc.Weather}
05-02 21:40:24.209  7697  7697 D BreventServer: top: {}
05-02 21:40:24.209  7697  7697 D BreventServer: home: {com.asus.launcher, com.android.systemui}
05-02 21:40:24.209  7697  7697 D BreventServer: current: com.asus.launcher
05-02 21:40:24.209  7697  7697 D BreventServer: unsafe: {}
05-02 21:40:24.209  7697  7697 D BreventServer: final blocking: {com.google.android.calendar, com.facebook.orca, com.htc.Weather}
05-02 21:40:24.209  7697  7697 D BreventServer: notifications: {com.facebook.orca=[354]}
05-02 21:40:24.209  7697  7697 D BreventServer: noRecent: {com.facebook.orca, com.htc.Weather}
05-02 21:40:24.209  7697  7697 D BreventServer: foreground service: {com.facebook.orca}
05-02 21:40:24.209  7697  7697 D BreventServer: gcm: {org.telegram.messenger, com.htc.cs.pns, jp.naver.line.android, org.cwb, com.android.vending, com.google.android.apps.classroom, com.google.android.apps.docs, com.google.android.gsf, com.esri.arcgis.android.idt.EPA.HL, com.google.android.apps.photos, com.facebook.katana, com.facebook.orca}
05-02 21:40:24.210  7697  7697 D BreventServer: sticky notification: {com.facebook.orca}
05-02 21:40:24.212  7697  7697 D BreventServer: ignore com.htc.Weather, wait for the service check
05-02 21:40:24.232  7697  7697 D BreventServer: check again in 3600s
05-02 21:40:24.232  7697  7697 D BreventServer: check and brevent, took 167ms
05-02 21:40:32.453  7697  7697 D BreventServer: com.htc.mobiledata: priority
05-02 21:40:34.744  7697  7697 D BreventServer: check and brevent
05-02 21:40:34.830  7697  7697 D BreventServer: widgets: {com.google.android.calendar, com.htc.widget.weatherclock}
05-02 21:40:34.830  7697  7697 D BreventServer: running: {}
05-02 21:40:34.830  7697  7697 D BreventServer: recent: {com.google.android.calendar=1727}
05-02 21:40:34.853  7697  7697 D BreventServer: inactive for com.facebook.orca: 0, timeout: 300
05-02 21:40:34.853  7697  7697 D BreventServer: inactive for com.htc.mobiledata: 0, timeout: 300
05-02 21:40:34.853  7697  7697 D BreventServer: inactive for com.htc.Weather: 0, timeout: 300
05-02 21:40:34.916  7697  7697 D BreventServer: com.htc.htcpowermanager depended by {com.android.settings}
05-02 21:40:34.916  7697  7697 D BreventServer: com.android.chrome depended by {com.google.android.googlequicksearchbox, com.google.android.gms, com.facebook.orca}
05-02 21:40:34.916  7697  7697 D BreventServer: com.google.android.gms depended by {com.android.settings}
05-02 21:40:34.916  7697  7697 D BreventServer: service: {com.htc.Weather}
05-02 21:40:34.916  7697  7697 D BreventServer: back: {com.google.android.calendar}
05-02 21:40:34.916  7697  7697 D BreventServer: blocking: {com.google.android.calendar, com.facebook.orca, com.htc.mobiledata, com.htc.Weather}
05-02 21:40:34.918  7697  7697 D BreventServer: top: {}
05-02 21:40:34.918  7697  7697 D BreventServer: home: {com.asus.launcher, com.android.systemui}
05-02 21:40:34.918  7697  7697 D BreventServer: current: com.asus.launcher
05-02 21:40:34.918  7697  7697 D BreventServer: unsafe: {}
05-02 21:40:34.918  7697  7697 D BreventServer: final blocking: {com.google.android.calendar, com.facebook.orca, com.htc.mobiledata, com.htc.Weather}
05-02 21:40:34.918  7697  7697 D BreventServer: notifications: {com.facebook.orca=[354]}
05-02 21:40:34.918  7697  7697 D BreventServer: noRecent: {com.facebook.orca, com.htc.mobiledata, com.htc.Weather}
05-02 21:40:34.918  7697  7697 D BreventServer: foreground service: {com.facebook.orca}
05-02 21:40:34.918  7697  7697 D BreventServer: gcm: {org.telegram.messenger, com.htc.cs.pns, jp.naver.line.android, org.cwb, com.android.vending, com.google.android.apps.classroom, com.google.android.apps.docs, com.google.android.gsf, com.esri.arcgis.android.idt.EPA.HL, com.google.android.apps.photos, com.facebook.katana, com.facebook.orca}
05-02 21:40:34.918  7697  7697 D BreventServer: sticky notification: {com.facebook.orca}
05-02 21:40:34.920  7697  7697 D BreventServer: ignore com.htc.mobiledata, wait for the service check
05-02 21:40:34.924  7697  7697 D BreventServer: Force stop com.htc.Weather(priority service)
05-02 21:40:34.944  7697  7697 D BreventServer: check again in 3600s
05-02 21:40:34.944  7697  7697 D BreventServer: check and brevent, took 198ms

**Comment by kimlu235711** [comment]
C:\Users\Shanyu>adb -d logcat -d -b crash
05-02 21:06:20.562  7085  7085 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 7085 (main)
05-02 21:06:20.626  7379  7379 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-02 21:06:20.626  7379  7379 F DEBUG   : Build fingerprint: 'htc/pmeuhl_00709/htc_pmeuhl:7.0/NRD90M/857212.7:user/release-keys'
05-02 21:06:20.626  7379  7379 F DEBUG   : Revision: '0'
05-02 21:06:20.626  7379  7379 F DEBUG   : ABI: 'arm'
05-02 21:06:20.626  7379  7379 F DEBUG   : pid: 7085, tid: 7085, name: main  >>> /system/bin/dex2oat <<<
05-02 21:06:20.626  7379  7379 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-02 21:06:20.628  7379  7379 F DEBUG   : Abort message: 'art/compiler/image_writer.cc:440] Check failed: dex_file_oat_index_map_.find(dex_file) != dex_file_oat_index_map_.end() Dex cache should have been pruned /system/framework/com.google.android.maps.jar; possibly in class path'
05-02 21:06:20.628  7379  7379 F DEBUG   :     r0 00000000  r1 00001bad  r2 00000006  r3 00000008
05-02 21:06:20.628  7379  7379 F DEBUG   :     r4 f75b258c  r5 00000006  r6 f75b2534  r7 0000010c
05-02 21:06:20.628  7379  7379 F DEBUG   :     r8 f74f2f00  r9 00000017  sl 00000012  fp f6802498
05-02 21:06:20.628  7379  7379 F DEBUG   :     ip 00000002  sp fff95760  lr f7182fe7  pc f7185868  cpsr 200f0010
05-02 21:06:20.635  7379  7379 F DEBUG   :
05-02 21:06:20.635  7379  7379 F DEBUG   : backtrace:
05-02 21:06:20.637  7379  7379 F DEBUG   :     #00 pc 0004a868  /system/lib/libc.so (tgkill+12)
05-02 21:06:20.637  7379  7379 F DEBUG   :     #01 pc 00047fe3  /system/lib/libc.so (pthread_kill+34)
05-02 21:06:20.637  7379  7379 F DEBUG   :     #02 pc 0001d7f9  /system/lib/libc.so (raise+10)
05-02 21:06:20.637  7379  7379 F DEBUG   :     #03 pc 000192f1  /system/lib/libc.so (__libc_android_abort+34)
05-02 21:06:20.637  7379  7379 F DEBUG   :     #04 pc 00017358  /system/lib/libc.so (abort+4)
05-02 21:06:20.637  7379  7379 F DEBUG   :     #05 pc 0031be75  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+252)
05-02 21:06:20.637  7379  7379 F DEBUG   :     #06 pc 000b4d79  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+864)
05-02 21:06:20.637  7379  7379 F DEBUG   :     #07 pc 00179399  /system/lib/libart-compiler.so (_ZN3art11ImageWriter25PrepareDexCacheArraySlotsEv+960)
05-02 21:06:20.637  7379  7379 F DEBUG   :     #08 pc 0017624b  /system/lib/libart-compiler.so (_ZN3art11ImageWriter25CalculateNewObjectOffsetsEv+642)
05-02 21:06:20.638  7379  7379 F DEBUG   :     #09 pc 00175995  /system/lib/libart-compiler.so (_ZN3art11ImageWriter24PrepareImageAddressSpaceEv+908)
05-02 21:06:20.638  7379  7379 F DEBUG   :     #10 pc 000188ad  /system/bin/dex2oat
05-02 21:06:20.638  7379  7379 F DEBUG   :     #11 pc 00008a99  /system/bin/dex2oat (main+736)
05-02 21:06:20.638  7379  7379 F DEBUG   :     #12 pc 00016da1  /system/lib/libc.so (__libc_init+48)
05-02 21:06:20.638  7379  7379 F DEBUG   :     #13 pc 000086e0  /system/bin/dex2oat

**Comment by vvb2060** [comment]
不要黑域【日历存储】，老问题了。
