### ISSUE TITLE
黑域在没有重启的情况下需要重新执行adb命令

### ISSUE THREAD

**Issue by amdth** [liudongmiao/Brevent#465]
手机型号 sony xperia x 
手机版本号7.0
黑域版本号1.1

崩溃日志
adb -d logcat -d -b crash
05-02 23:53:24.458 13394 13394 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
05-02 23:53:24.458 13394 13394 E AndroidRuntime: java.lang.reflect.InvocationTargetException
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1717)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unknown package: com.microsoft.launcher
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1694)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1640)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4542)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at me.piebridge.brevent.server.d.a(HideApi.java:262)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:915)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:905)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:856)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:638)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.handleMessage(BreventServer.java:403)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1674)
05-02 23:53:24.458 13394 13394 E AndroidRuntime: 	... 4 more
05-02 23:53:24.462 13394 13394 E AndroidRuntime: Error reporting crash
05-02 23:53:24.462 13394 13394 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
05-02 23:53:24.462 13394 13394 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
05-02 23:53:24.462 13394 13394 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
05-02 23:53:24.462 13394 13394 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5140)
05-02 23:53:24.462 13394 13394 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
05-02 23:53:24.462 13394 13394 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
05-02 23:53:24.462 13394 13394 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
黑域服务日志
$ adb -d logcat -d -b main -s BreventServer BreventLoader
05-03 06:41:14.300 26315 26315 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
05-03 06:41:14.815 26332 26332 W BreventServer: Can't find Settings.Secure.QS_TILES
05-03 06:41:14.871 26332 26332 I BreventServer: Brevent Server xy(1.1) started
05-03 06:41:14.878 26332 26332 W BreventServer: Can't find Settings.Secure.QS_TILES
05-03 06:41:14.881 26332 26332 I BreventServer: brevent user: 0, uid: 2000
05-03 06:41:14.884 26332 26332 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
05-03 06:41:14.997 26332 26332 I BreventServer: loading brevent list
05-03 06:41:14.999 26332 26332 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 20
05-03 06:41:15.000 26332 26332 I BreventServer: loading brevent conf
05-03 06:41:15.079 26332 26332 D BreventServer: check and brevent
05-03 06:41:15.259 26332 26332 I BreventServer: android process: android.process.media, packages: [com.android.providers.media, com.android.providers.downloads]
05-03 06:41:15.264 26332 26332 I BreventServer: android process: android.process.acore, packages: [com.android.providers.blockednumber, com.android.providers.userdictionary, com.android.providers.contacts]
05-03 06:41:15.370 26332 26332 D BreventServer: check again in 2619s
05-03 06:41:15.370 26332 26332 D BreventServer: check and brevent, took 290ms
05-03 06:41:15.436 26332 26332 D BreventServer: sent first status
ccde-MacBook-Pro:~ c.c$

**Comment by djunhao** [comment]
我的是三星S6，无法抓取main日志，也经常出现黑域非重启异常退出的状况。

**Comment by amdth** [comment]
没有日志就没办法了

2017-05-03 9:16 GMT+08:00 djunhao <notifications@github.com>:

**Comment by liudongmiao** [comment]
这个确实是一个 bug，我捕获了 IllegalArgumentException，但是实际抛出的可能是 RemoteException

我将本地测试好了以后，再给测试版

**Comment by djunhao** [comment]
我说错了，无法抓取的是crash的日志。
