### ISSUE TITLE
求助  crash

### ISSUE THREAD

**Issue by TorresKwan** [liudongmiao/Brevent#467]
求助  crash

![sshot-22](https://cloud.githubusercontent.com/assets/28332774/25648034/0e81e270-2ffa-11e7-8be5-cd38fc73e930.jpg)
![sshot-21](https://cloud.githubusercontent.com/assets/28332774/25648035/0eb531f2-2ffa-11e7-9061-540bc268062c.jpg)
![sshot-20](https://cloud.githubusercontent.com/assets/28332774/25648036/0ee7606e-2ffa-11e7-9e09-33c0531a3fef.jpg)

**Comment by liudongmiao** [comment]
这里没有 crash 日志。请使用这个看下能不能提取 crash 信息：

```
adb logcat -s AndroidRuntime:E
```
