### ISSUE TITLE
支付宝闪退

### ISSUE THREAD

**Issue by fox1226** [liudongmiao/Brevent#47]
Sony Z5 dual 7.0.1 未解锁未root 

阻止支付宝后 在其他应用中用到支付宝付款的时候支付宝付款框弹出后会造成当前应用闪退 再次进入应用即可顺利付款 

烦请测试 
谢谢

**Comment by liudongmiao** [comment]
请获取最新 beta 版测试：piebridge.me/br/ 目前无法重现。

**Comment by liudongmiao** [comment]
请使用最新 beta 版测试：piebridge.me/br/

如果还有这个问题，请重开这个问题，谢谢。
