### ISSUE TITLE
黑域只能用几个小时

### ISSUE THREAD

**Issue by orcasland** [liudongmiao/Brevent#470]
你好，首先感谢你为中国安卓用户开发的这款软件，这是不得不使用大量国内垃圾软件的安卓用户的一大福音!
但在使用中发现如下问题，软件刚安装好时工作正常，可是过了几个小时，再按退出键不再自动关闭程序，在最近使用菜单中划掉也无效，打开“黑域”,黑域的菜单显示没在运行，可实际正在运行。
重启以后，重新adb命令恢复正常。我的手机是moto x pure美版原生安卓。谢谢！

**Comment by vvb2060** [comment]
实际正在运行是看什么信息得出的？
开debug模式黑域的日志又是怎么？
如果不给日志就不知道黑域为什么不处理。

**Comment by orcasland** [comment]
你好，我重启一次，然后重新输入adb命令，然后一切正常了，已经1天了一切正常，不知道是不是残存的缓存之类问题。谢谢2017年5月5日 下午6:43，vvb2060 <notifications@github.com>写道：实际正在运行是看什么信息得出的？
开debug模式黑域的日志又是怎么？
如果不给日志就不知道黑域为什么不处理。
