### ISSUE TITLE
用不了，一直提示重启黑域服务

### ISSUE THREAD

**Issue by lethe-fan** [liudongmiao/Brevent#474]
C:\Users\fanya\Downloads\Compressed\platform-tools>adb -d logcat -d -b crash
05-08 20:11:03.410 18425 18425 F libc    : "/data/user/0/com.wandoujia.eyepetizer/lib/libuuid.so": error: only position independent executables (PIE) are supported.
05-08 20:11:03.410 18425 18425 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 18425 (libuuid.so)
05-08 20:11:03.465 18428 18428 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-08 20:11:03.465 18428 18428 F DEBUG   : LineageOS Version: '14.1-20170501-NIGHTLY-bacon'
05-08 20:11:03.465 18428 18428 F DEBUG   : Build fingerprint: 'oneplus/bacon/A0001:6.0.1/MHC19Q/ZNH2KAS1KN:user/release-keys'
05-08 20:11:03.466 18428 18428 F DEBUG   : Revision: '0'
05-08 20:11:03.466 18428 18428 F DEBUG   : ABI: 'arm'
05-08 20:11:03.466 18428 18428 F DEBUG   : pid: 18425, tid: 18425, name: libuuid.so  >>> /data/user/0/com.wandoujia.eyepetizer/lib/libuuid.so <<<
05-08 20:11:03.466 18428 18428 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-08 20:11:03.466 18428 18428 F DEBUG   :     r0 00000000  r1 000047f9  r2 00000006  r3 00000008
05-08 20:11:03.466 18428 18428 F DEBUG   :     r4 b6f9058c  r5 00000006  r6 b6f90534  r7 0000010c
05-08 20:11:03.466 18428 18428 F DEBUG   :     r8 b6f2a000  r9 bed19904  sl bed19f0c  fp bed19f0c
05-08 20:11:03.466 18428 18428 F DEBUG   :     ip 00000000  sp bed185d8  lr b6f7029f  pc b6f70cbc  cpsr 60070010
05-08 20:11:03.484 18428 18428 F DEBUG   :
05-08 20:11:03.484 18428 18428 F DEBUG   : backtrace:
05-08 20:11:03.484 18428 18428 F DEBUG   :     #00 pc 00046cbc  /system/bin/linker (__dl_tgkill+12)
05-08 20:11:03.484 18428 18428 F DEBUG   :     #01 pc 0004629b  /system/bin/linker (__dl_pthread_kill+34)
05-08 20:11:03.484 18428 18428 F DEBUG   :     #02 pc 0003e59f  /system/bin/linker (__dl_raise+10)
05-08 20:11:03.484 18428 18428 F DEBUG   :     #03 pc 0003d05b  /system/bin/linker (__dl___libc_android_abort+34)
05-08 20:11:03.484 18428 18428 F DEBUG   :     #04 pc 0003bf54  /system/bin/linker (__dl_abort+4)
05-08 20:11:03.484 18428 18428 F DEBUG   :     #05 pc 0003e0a3  /system/bin/linker (__dl___libc_fatal+22)
05-08 20:11:03.484 18428 18428 F DEBUG   :     #06 pc 00009de5  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+3496)
05-08 20:11:03.484 18428 18428 F DEBUG   :     #07 pc 00008fa7  /system/bin/linker (__dl___linker_init+358)
05-08 20:11:03.485 18428 18428 F DEBUG   :     #08 pc 000027c0  /system/bin/linker (_start+4)

**Comment by liudongmiao** [comment]
那就按提示的来。

这里没有任何与黑域相关的日志。
