### ISSUE TITLE
[一加3T][H2OS 3.0 第2版 Android 7.0] v1.1.1 非Root模式下 BreventServer自动退出

### ISSUE THREAD

**Issue by kakashir** [liudongmiao/Brevent#476]
基本上adb启动后10分钟内就会退出，每次最后一条log都是 “E BreventServer: Don't receive answer from universe” ，请看下。

log如下：
05-09 16:08:14.206  7362  7362 D BreventServer: com.android.webview depended by {com.android.vending}
05-09 16:08:14.206  7362  7362 D BreventServer: com.google.android.gms depended by {com.android.vending}
05-09 16:08:14.206  7362  7362 D BreventServer: service: {}
05-09 16:08:14.206  7362  7362 D BreventServer: back(no action): {}
05-09 16:08:14.206  7362  7362 D BreventServer: blocking: {com.netease.cloudmusic}
05-09 16:08:14.206  7362  7362 D BreventServer: top: {com.android.vending}
05-09 16:08:14.206  7362  7362 D BreventServer: home: {net.oneplus.launcher}
05-09 16:08:14.206  7362  7362 D BreventServer: current: null
05-09 16:08:14.206  7362  7362 D BreventServer: unsafe: {}
05-09 16:08:14.206  7362  7362 D BreventServer: final blocking: {com.netease.cloudmusic}
05-09 16:08:14.206  7362  7362 D BreventServer: notifications: {com.android.mms=[1]}
05-09 16:08:14.206  7362  7362 D BreventServer: noRecent: {com.netease.cloudmusic}
05-09 16:08:14.206  7362  7362 D BreventServer: foreground service: {}
05-09 16:08:14.207  7362  7362 D BreventServer: gcm: {}
05-09 16:08:14.207  7362  7362 D BreventServer: sticky notification: {}
05-09 16:08:14.210  7362  7362 D BreventServer: check again in 55s
05-09 16:08:14.211  7362  7362 D BreventServer: check and brevent, took 334ms
05-09 16:09:09.266  7362  7362 D BreventServer: check and brevent
05-09 16:09:09.374  7362  7362 D BreventServer: widgets: {com.oneplus.calendar, com.netease.cloudmusic}
05-09 16:09:09.374  7362  7362 D BreventServer: running: {com.android.vending=1231, me.piebridge.brevent=1063, com.android.dialer=234}
05-09 16:09:09.374  7362  7362 D BreventServer: recent: {net.oneplus.weather=6261, com.douban.frodo=1418, com.android.vending=7140, com.tencent.mm=5369, me.piebridge.brevent=6972, com.android.mms=1689, com.android.chrome=2562, com.android.dialer=6143, com.android.settings=6798}
05-09 16:09:09.524  7362  7362 D BreventServer: inactive for com.android.vending: 59, timeout: 60
05-09 16:09:09.525  7362  7362 D BreventServer: inactive for com.netease.cloudmusic: 0, timeout: 60
05-09 16:09:09.631  7362  7362 D BreventServer: com.android.webview depended by {com.android.vending}
05-09 16:09:09.631  7362  7362 D BreventServer: com.google.android.gms depended by {com.android.vending}
05-09 16:09:09.631  7362  7362 D BreventServer: service: {}
05-09 16:09:09.631  7362  7362 D BreventServer: back(no action): {}
05-09 16:09:09.631  7362  7362 D BreventServer: blocking: {com.netease.cloudmusic}
05-09 16:09:09.632  7362  7362 D BreventServer: top: {com.android.vending}
05-09 16:09:09.632  7362  7362 D BreventServer: home: {net.oneplus.launcher}
05-09 16:09:09.632  7362  7362 D BreventServer: current: null
05-09 16:09:09.632  7362  7362 D BreventServer: unsafe: {}
05-09 16:09:09.632  7362  7362 D BreventServer: final blocking: {com.netease.cloudmusic}
05-09 16:09:09.632  7362  7362 D BreventServer: notifications: {com.android.mms=[1]}
05-09 16:09:09.632  7362  7362 D BreventServer: noRecent: {com.netease.cloudmusic}
05-09 16:09:09.632  7362  7362 D BreventServer: foreground service: {}
05-09 16:09:09.632  7362  7362 D BreventServer: gcm: {}
05-09 16:09:09.632  7362  7362 D BreventServer: sticky notification: {}
05-09 16:09:09.638  7362  7362 D BreventServer: check again in 1s
05-09 16:09:09.638  7362  7362 D BreventServer: check and brevent, took 370ms
05-09 16:09:11.641  7362  7362 D BreventServer: check and brevent
05-09 16:09:11.716  7362  7362 D BreventServer: widgets: {com.oneplus.calendar, com.netease.cloudmusic}
05-09 16:09:11.717  7362  7362 D BreventServer: running: {com.android.vending=1230, me.piebridge.brevent=1063, com.android.dialer=234}
05-09 16:09:11.717  7362  7362 D BreventServer: recent: {net.oneplus.weather=6259, com.douban.frodo=1416, com.android.vending=7138, com.tencent.mm=5367, me.piebridge.brevent=6970, com.android.mms=1687, com.android.chrome=2560, com.android.dialer=6141, com.android.settings=6796}
05-09 16:09:11.810  7362  7362 D BreventServer: inactive for com.android.vending: 62, timeout: 60
05-09 16:09:11.811  7362  7362 D BreventServer: inactive for com.netease.cloudmusic: 0, timeout: 60
05-09 16:09:11.886  7362  7362 D BreventServer: com.android.webview depended by {com.android.vending}
05-09 16:09:11.887  7362  7362 D BreventServer: com.google.android.gms depended by {com.android.vending}
05-09 16:09:11.887  7362  7362 D BreventServer: service: {}
05-09 16:09:11.887  7362  7362 D BreventServer: back(no action): {}
05-09 16:09:11.887  7362  7362 D BreventServer: blocking: {com.android.vending, com.netease.cloudmusic}
05-09 16:09:11.887  7362  7362 D BreventServer: top: {com.android.vending}
05-09 16:09:11.887  7362  7362 D BreventServer: home: {net.oneplus.launcher}
05-09 16:09:11.887  7362  7362 D BreventServer: current: null
05-09 16:09:11.887  7362  7362 D BreventServer: unsafe: {}
05-09 16:09:11.887  7362  7362 D BreventServer: final blocking: {com.netease.cloudmusic}
05-09 16:09:11.887  7362  7362 D BreventServer: notifications: {com.android.mms=[1]}
05-09 16:09:11.887  7362  7362 D BreventServer: noRecent: {com.netease.cloudmusic}
05-09 16:09:11.887  7362  7362 D BreventServer: foreground service: {}
05-09 16:09:11.887  7362  7362 D BreventServer: gcm: {}
05-09 16:09:11.887  7362  7362 D BreventServer: sticky notification: {}
05-09 16:09:11.893  7362  7362 D BreventServer: check again in 3600s
05-09 16:09:11.894  7362  7362 D BreventServer: check and brevent, took 250ms
05-09 16:09:39.342  7362  7362 D BreventServer: checking feelgood
05-09 16:09:44.538  7362  7362 D BreventServer: checking feelgood
05-09 16:10:26.581  7362  7362 E BreventServer: Don't receive answer from universe

**Comment by kakashir** [comment]
搜索了一下，这个问题看起来是和log level有关，把log level调整为info后就没有这个问题了，过去是slient。这样的话正好搭车问一下，搭配黑域建议的log level为多少比较合适？谢谢。

**Comment by liudongmiao** [comment]
黑域依赖事件日志，事件日志的级别基本都是 INFO。

**Comment by liudongmiao** [comment]
此外，没有特殊必要的话，建议关闭黑域调试日志。

你可以从商店详情中找到开启与关闭方法。

**Comment by kakashir** [comment]
OK, 非常感谢。
