### ISSUE TITLE
联想p8平板，命令行运行通过但是不能进入黑域

### ISSUE THREAD

**Issue by takato555** [liudongmiao/Brevent#479]
之前进入过一次，后来可能是因为插入了sd卡并且格式化为内置存储空间（可能，我猜），命令行输入以后一切正常，只是打开黑域软件点击进入黑域会提示“正在获取进程状态”，然后过了一会会提示重启黑域，再次输入命令行一样的提示。

黑域服务日志：
05-11 08:48:45.460 10792 10792 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
05-11 08:48:45.991 10808 10808 I BreventServer: Brevent Server 1.1.1 started
05-11 08:48:46.000 10808 10808 I BreventServer: brevent user: 0, uid: 2000
05-11 08:48:46.001 10808 10808 I BreventServer: brevent data directory: /data/user/0/com.android.shell
05-11 08:48:46.032 10808 10808 I BreventServer: android providers: {com.android.providers.calendar, com.android.providers.media, com.android.providers.downloads, com.android.providers.downloads.ui, com.android.providers.userdictionary, com.android.providers.contacts}
05-11 08:48:46.033 10808 10808 I BreventServer: loading brevent list
05-11 08:48:46.033 10808 10808 I BreventServer: loading brevent conf
05-11 08:48:46.237 10808 10808 D BreventServer: check and brevent
05-11 08:48:46.340 10808 10808 D BreventServer: check again in 3600s
05-11 08:48:46.340 10808 10808 D BreventServer: check and brevent, took 103ms
05-11 08:48:46.342 10808 10808 D BreventServer: Can't setStopped for me.piebridge.brevent(ignore)
05-11 08:48:46.343 10808 10808 D BreventServer: Can't setStopped for me.piebridge.brevent(ignore)
05-11 08:49:01.387 10808 10808 D BreventServer: sent first status

**Comment by liudongmiao** [comment]
这个日志正常，等提示“重启黑域”时，再贴日志。

**Comment by tgr989** [comment]
+1
