### ISSUE TITLE
在酷安里点链接，返回酷安被干掉了。

### ISSUE THREAD

**Issue by cv0cv0** [liudongmiao/Brevent#48]
被强行停止了。

**Comment by liudongmiao** [comment]
请使用最新 beta 版测试，然后看看能不能重现。

目前无法重现。

**Comment by cv0cv0** [comment]
我遇到过几次，但是无法具体重现。已装beta版，再留意一下。

**Comment by liudongmiao** [comment]
请使用最新 beta 版测试：piebridge.me/br/

如果还有这个问题，请重开这个问题，谢谢。
