### ISSUE TITLE
印象笔记  每次进入 黑域  计时都会重新开始

### ISSUE THREAD

**Issue by ebnbin** [liudongmiao/Brevent#480]
印象笔记（com.evernote），Google play 版本，正常返回键退出后，每次进入 黑域，都会显示在 正在运行 列表，显示 1个服务进程，并且，计时器每次都会从 00:00 重新开始计算，麻烦帮忙看一下

**Comment by naloder** [comment]
缺少日志_(:з」∠)_

**Comment by liudongmiao** [comment]
非正常 Back 所致。

强行停止这些时间异常的应用，然后强行停止启动器，然后就会恢复正常。

目前没有好的办法避免。
