### ISSUE TITLE
添加忽略应用状态的选项

### ISSUE THREAD

**Issue by AntSYau** [liudongmiao/Brevent#483]
有些进程会滥用进程（比如优酷，我不知道它赖在后台到底想干嘛），希望能添加一个设置选项能够忽略应用状态强行brevent

**Comment by liudongmiao** [comment]
自己划掉，如果划不掉，还显示时间，就自己手动强行停止，或者等超时后处理。
但有些应用，时间会自动刷新，你直接先手动强行停止它吧。

**Comment by AntSYau** [comment]
好吧，，
我把这种app都卸载掉了，这样更省心（逃
