### ISSUE TITLE
更新v1.1.3后进入死循环

### ISSUE THREAD

**Issue by 86shaku** [liudongmiao/Brevent#484]
日志：
05-13 10:26:35.167  6882  6882 D BreventServer: check and brevent
05-13 10:26:35.892  6882  6882 D BreventServer: check again in 3600s
05-13 10:26:35.893  6882  6882 D BreventServer: check and brevent, took 725ms
05-13 10:27:36.578  6882  6882 D BreventServer: check and brevent
05-13 10:27:37.412  6882  6882 D BreventServer: check again in 3600s
05-13 10:27:37.412  6882  6882 D BreventServer: check and brevent, took 831ms
05-13 10:28:04.997  6882  6882 D BreventServer: check and brevent
05-13 10:28:05.687  6882  6882 D BreventServer: check again in 3600s
05-13 10:28:05.687  6882  6882 D BreventServer: check and brevent, took 689ms
05-13 10:28:29.503  6882  6882 D BreventServer: check and brevent
05-13 10:28:30.115  6882  6882 D BreventServer: check again in 3600s
05-13 10:28:30.116  6882  6882 D BreventServer: check and brevent, took 612ms
05-13 10:28:50.679  6882  6882 D BreventServer: check and brevent
05-13 10:28:51.347  6882  6882 D BreventServer: check again in 3600s
05-13 10:28:51.348  6882  6882 D BreventServer: check and brevent, took 667ms
05-13 10:29:06.678  6882  6882 D BreventServer: checking feelgood
05-13 10:29:06.679  6882  6892 D BreventServer: received feelgood
05-13 10:29:24.824  6882  6882 D BreventServer: checking feelgood
05-13 10:29:24.826  6882  6892 D BreventServer: received feelgood
05-13 10:30:10.031  6882  6882 D BreventServer: checking feelgood
05-13 10:30:10.033  6882  6892 D BreventServer: received feelgood
05-13 10:30:25.169  6882  6882 D BreventServer: checking feelgood
05-13 10:30:25.169  6882  6892 D BreventServer: received feelgood
05-13 10:30:43.153  6882  6882 D BreventServer: checking feelgood
05-13 10:30:43.154  6882  6892 D BreventServer: received feelgood
05-13 10:31:08.699  6882  6882 D BreventServer: checking feelgood
05-13 10:31:08.700  6882  6882 D BreventServer: check and brevent
05-13 10:31:08.716  6882  6892 D BreventServer: received feelgood
05-13 10:31:09.444  6882  6882 D BreventServer: check again in 3600s
05-13 10:31:09.445  6882  6882 D BreventServer: check and brevent, took 744ms
05-13 10:31:12.427  6871  6871 E BreventLoader: worker 6882 exited on signal 15
05-13 10:31:12.427  6871  6871 D BreventLoader: signal arrived, update: 0
05-13 10:31:13.577  8263  8263 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
05-13 10:31:14.438  8277  8277 I BreventServer: Brevent Server 1.1.3 started
05-13 10:31:14.481  8277  8277 I BreventServer: brevent user: 0, uid: 2000
05-13 10:31:14.483  8277  8277 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
05-13 10:31:14.599  8277  8277 I BreventServer: android providers: {com.android.providers.calendar, com.android.providers.media, com.android.providers.downloads, com.android.providers.downloads.ui, com.android.providers.partnerbookmarks, com.android.providers.blockednumber, com.android.providers.userdictionary, com.android.providers.contacts}
05-13 10:31:14.834  8277  8277 I BreventServer: loading brevent list
05-13 10:31:14.845  8277  8277 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 3
05-13 10:31:14.856  8277  8277 D BreventServer: Force stop com.niksoftware.snapseed(load brevent)
05-13 10:31:14.878  8277  8277 D BreventServer: Force stop luo.gpsspeed_pro(load brevent)
05-13 10:31:14.894  8277  8277 D BreventServer: Force stop com.tencent.mm(load brevent)
05-13 10:31:14.895  8277  8277 I BreventServer: loading brevent conf
05-13 10:31:15.279  8277  8277 D BreventServer: check and brevent
05-13 10:31:16.110  8277  8277 D BreventServer: check again in 3600s
05-13 10:31:16.110  8277  8277 D BreventServer: check and brevent, took 830ms
05-13 10:31:31.212  8277  8277 D BreventServer: sent first status
05-13 10:31:31.486  8263  8263 E BreventLoader: worker 8277 exited on signal 15
05-13 10:31:31.486  8263  8263 D BreventLoader: signal arrived, update: 0
05-13 10:31:32.500  8360  8360 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
05-13 10:31:33.429  8374  8374 I BreventServer: Brevent Server 1.1.3 started
05-13 10:31:33.445  8374  8374 I BreventServer: brevent user: 0, uid: 2000
05-13 10:31:33.449  8374  8374 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
05-13 10:31:33.506  8374  8374 I BreventServer: android providers: {com.android.providers.calendar, com.android.providers.media, com.android.providers.downloads, com.android.providers.downloads.ui, com.android.providers.partnerbookmarks, com.android.providers.blockednumber, com.android.providers.userdictionary, com.android.providers.contacts}
05-13 10:31:33.691  8374  8374 I BreventServer: loading brevent list
05-13 10:31:33.719  8374  8374 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 3
05-13 10:31:33.741  8374  8374 D BreventServer: Force stop com.niksoftware.snapseed(load brevent)
05-13 10:31:33.762  8374  8374 D BreventServer: Force stop luo.gpsspeed_pro(load brevent)
05-13 10:31:33.777  8374  8374 D BreventServer: Force stop com.tencent.mm(load brevent)
05-13 10:31:33.778  8374  8374 I BreventServer: loading brevent conf
05-13 10:31:34.163  8374  8374 D BreventServer: check and brevent
05-13 10:31:35.027  8374  8374 D BreventServer: check again in 3600s
05-13 10:31:35.031  8374  8374 D BreventServer: check and brevent, took 867ms
05-13 10:31:50.124  8374  8374 D BreventServer: sent first status
05-13 10:32:05.972  8374  8374 D BreventServer: checking feelgood
05-13 10:32:05.982  8374  8374 D BreventServer: check and brevent
05-13 10:32:05.986  8374  8390 D BreventServer: received feelgood
05-13 10:32:06.692  8374  8374 D BreventServer: check again in 3600s
05-13 10:32:06.692  8374  8374 D BreventServer: check and brevent, took 708ms
05-13 10:32:21.782  8374  8374 D BreventServer: checking feelgood
05-13 10:32:21.785  8374  8390 D BreventServer: received feelgood
05-13 10:32:39.146  8374  8374 D BreventServer: checking feelgood
05-13 10:32:39.147  8374  8390 D BreventServer: received feelgood
05-13 10:32:57.151  8374  8374 D BreventServer: checking feelgood
05-13 10:32:57.152  8374  8390 D BreventServer: received feelgood
05-13 10:32:59.154  8374  8374 D BreventServer: check and brevent
05-13 10:32:59.897  8374  8374 D BreventServer: check again in 3600s
05-13 10:32:59.898  8374  8374 D BreventServer: check and brevent, took 738ms

retrieving processes status约十秒之后不能正常进入APP列表，
而是显示首次使用时候提示输入adb的界面。
重复输入adb命令行也没有任何效果。

原生7.1.1

**Comment by liudongmiao** [comment]
>  05-13 10:31:31.486 8263 8263 E BreventLoader: worker 8277 exited on signal 15
需要更多日志。

你找下全部的日志吧。15 表示这个进程，被其它程序杀了。

**Comment by 86shaku** [comment]
E:\platform-tools>adb -d logcat -d -b main -s BreventServer BreventLoader
05-14 09:57:32.500  7337  7337 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
05-14 09:57:33.468  7350  7350 I BreventServer: Brevent Server 1.1.3 started
05-14 09:57:33.484  7350  7350 I BreventServer: brevent user: 0, uid: 2000
05-14 09:57:33.486  7350  7350 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
05-14 09:57:33.560  7350  7350 I BreventServer: android providers: {com.android.providers.calendar, com.android.providers.media, com.android.providers.downloads, com.android.providers.downloads.ui, com.android.providers.partnerbookmarks, com.android.providers.blockednumber, com.android.providers.userdictionary, com.android.providers.contacts}
05-14 09:57:33.711  7350  7350 I BreventServer: loading brevent list
05-14 09:57:33.712  7350  7350 I BreventServer: loading brevent conf
05-14 09:57:34.047  7350  7350 D BreventServer: check and brevent
05-14 09:57:35.206  7350  7350 D BreventServer: check again in 3600s
05-14 09:57:35.206  7350  7350 D BreventServer: check and brevent, took 1158ms
05-14 09:57:50.309  7350  7350 D BreventServer: sent first status
05-14 09:58:05.884  7350  7350 D BreventServer: checking feelgood
05-14 09:58:05.886  7350  7359 D BreventServer: received feelgood
05-14 09:58:23.864  7350  7350 D BreventServer: checking feelgood
05-14 09:58:23.868  7350  7359 D BreventServer: received feelgood
05-14 09:58:41.863  7350  7350 D BreventServer: checking feelgood
05-14 09:58:41.880  7350  7359 D BreventServer: received feelgood
05-14 09:58:59.934  7350  7350 D BreventServer: checking feelgood
05-14 09:58:59.935  7350  7359 D BreventServer: received feelgood
05-14 09:59:17.930  7350  7350 D BreventServer: checking feelgood
05-14 09:59:17.933  7350  7359 D BreventServer: received feelgood
05-14 09:59:35.972  7350  7350 D BreventServer: checking feelgood
05-14 09:59:35.974  7350  7359 D BreventServer: received feelgood
05-14 09:59:53.984  7350  7350 D BreventServer: checking feelgood
05-14 09:59:53.985  7350  7359 D BreventServer: received feelgood
05-14 10:00:12.018  7350  7350 D BreventServer: checking feelgood
05-14 10:00:12.020  7350  7359 D BreventServer: received feelgood
05-14 10:00:30.085  7350  7350 D BreventServer: checking feelgood
05-14 10:00:30.085  7350  7359 D BreventServer: received feelgood
05-14 10:00:48.095  7350  7350 D BreventServer: checking feelgood
05-14 10:00:48.096  7350  7359 D BreventServer: received feelgood
05-14 10:01:06.132  7350  7350 D BreventServer: checking feelgood
05-14 10:01:06.133  7350  7359 D BreventServer: received feelgood
05-14 10:01:24.185  7350  7350 D BreventServer: checking feelgood
05-14 10:01:24.186  7350  7359 D BreventServer: received feelgood

E:\platform-tools>

现在的情况是重启后重新输入adb命令也无法正常进入app列表 ，一直留在提示输入界面不停闪烁。

**Comment by liudongmiao** [comment]
应该是其它应用，阻挡了黑域接收广播。

这个日志，本身没什么问题。

**Comment by 86shaku** [comment]
尝试一天没能解决，Google play已付款，只好等下次更新在尝试了。

**Comment by liudongmiao** [comment]
重启；卸载重新安装；以及不要和其它类似软件共用。

都可以尝试。

已经捐赠的，都可以发邮件要求退款。
