### ISSUE TITLE
[bug] cannot make sure this is bug ? processes don't brevent 

### ISSUE THREAD

**Issue by sosmygirl** [liudongmiao/Brevent#485]
5-1313:06:57.  6567  6567 D BreventServer: check later for com.tencent.qqlive: 2018
05-13 13:06:57.139  6567  6567 D BreventServer: check later for com.netease.cloudmusic: 1797
05-13 13:06:57.140  6567  6567 D BreventServer: check again in 1797s
05-13 13:06:57.140  6567  6567 D BreventServer: check and brevent, took 178ms
05-13 13:08:54.986  6567  6567 D BreventServer: resume activity, tid: 3441, packageName: net.oneplus.launcher, launcher: net.oneplus.launcher
05-13 13:08:56.617  6567  6567 D BreventServer: pause activity, tid: 2415, packageName: net.oneplus.launcher
05-13 13:08:56.662  6567  6567 D BreventServer: check and brevent
05-13 13:08:56.697  6567  6567 D BreventServer: widgets: {com.google.android.googlequicksearchbox, com.oneplus.security}
05-13 13:08:56.697  6567  6567 D BreventServer: running: {com.android.contacts=2984, me.piebridge.brevent=3269, com.android.incallui=2101, moe.haruue.wadb=851, com.android.settings=3008, com.netease.cloudmusic=1347}
05-13 13:08:56.697  6567  6567 D BreventServer: recent: {me.piebridge.brevent=3600, com.tencent.qqlive=1899, com.android.dialer=3315, moe.haruue.wadb=1181, com.android.settings=3338, com.netease.cloudmusic=1678}
05-13 13:08:56.723  6567  6567 D BreventServer: inactive for com.tencent.qqlive: 0, timeout: 1800
05-13 13:08:56.723  6567  6567 D BreventServer: inactive for com.netease.cloudmusic: 1922, timeout: 1800
05-13 13:08:56.761  6567  6567 D BreventServer: com.android.chrome depended by {com.google.android.googlequicksearchbox}
05-13 13:08:56.761  6567  6567 D BreventServer: com.google.android.gms depended by {com.android.vending, com.google.android.gm, net.oneplus.push}
05-13 13:08:56.761  6567  6567 D BreventServer: service: {}
05-13 13:08:56.761  6567  6567 D BreventServer: back: {}
05-13 13:08:56.761  6567  6567 D BreventServer: blocking: {com.tencent.qqlive, com.netease.cloudmusic}
05-13 13:08:56.761  6567  6567 D BreventServer: top: {me.piebridge.brevent}
05-13 13:08:56.761  6567  6567 D BreventServer: home: {com.android.systemui, net.oneplus.launcher}
05-13 13:08:56.761  6567  6567 D BreventServer: current: net.oneplus.launcher
05-13 13:08:56.761  6567  6567 D BreventServer: unsafe: {}
05-13 13:08:56.761  6567  6567 D BreventServer: final blocking: {com.tencent.qqlive, com.netease.cloudmusic}
05-13 13:08:56.761  6567  6567 D BreventServer: notifications: {}
05-13 13:08:56.761  6567  6567 D BreventServer: noRecent: {}
05-13 13:08:56.761  6567  6567 D BreventServer: foreground service: {}
05-13 13:08:56.761  6567  6567 D BreventServer: gcm: {com.weico.international}
05-13 13:08:56.761  6567  6567 D BreventServer: sticky notification: {}
05-13 13:08:56.762  6567  6567 D BreventServer: check later for com.tencent.qqlive: 1899
05-13 13:08:56.763  6567  6567 D BreventServer: check later for com.netease.cloudmusic: 1678
05-13 13:08:56.764  6567  6567 D BreventServer: check again in 1678s
05-13 13:08:56.764  6567  6567 D BreventServer: check and brevent, took 101ms
05-13 13:08:56.790  6567  6567 D BreventServer: checking feelgood
05-13 13:08:56.792  6567  6577 D BreventServer: received feelgood
05-13 13:09:27.630  6567  6567 D BreventServer: pause activity, tid: 3242, packageName: me.piebridge.brevent
05-13 13:09:27.661  6567  6567 D BreventServer: resume activity, tid: 1932, packageName: com.android.settings, launcher: net.oneplus.launcher
05-13 13:09:31.131  6567  6567 D BreventServer: check and brevent
05-13 13:09:31.213  6567  6567 D BreventServer: widgets: {com.google.android.googlequicksearchbox, com.oneplus.security}
05-13 13:09:31.213  6567  6567 D BreventServer: running: {com.android.contacts=2984, me.piebridge.brevent=3300, com.android.incallui=2100, moe.haruue.wadb=850, com.android.settings=3300, com.netease.cloudmusic=1346}
05-13 13:09:31.213  6567  6567 D BreventServer: recent: {me.piebridge.brevent=3596, com.tencent.qqlive=1864, com.android.dialer=3280, moe.haruue.wadb=1146, com.android.settings=3596, com.netease.cloudmusic=1643}
05-13 13:09:31.253  6567  6567 D BreventServer: inactive for com.tencent.qqlive: 0, timeout: 1800
05-13 13:09:31.253  6567  6567 D BreventServer: inactive for com.netease.cloudmusic: 1957, timeout: 1800
05-13 13:09:31.282  6567  6567 D BreventServer: com.android.chrome depended by {com.google.android.googlequicksearchbox}
05-13 13:09:31.282  6567  6567 D BreventServer: com.google.android.gms depended by {com.android.vending, com.google.android.gm, net.oneplus.push}
05-13 13:09:31.282  6567  6567 D BreventServer: service: {}
05-13 13:09:31.282  6567  6567 D BreventServer: back: {}
05-13 13:09:31.282  6567  6567 D BreventServer: blocking: {com.tencent.qqlive, com.netease.cloudmusic}
05-13 13:09:31.282  6567  6567 D BreventServer: top: {com.android.settings}
05-13 13:09:31.282  6567  6567 D BreventServer: home: {com.android.systemui, net.oneplus.launcher}
05-13 13:09:31.282  6567  6567 D BreventServer: current: com.android.settings
05-13 13:09:31.282  6567  6567 D BreventServer: unsafe: {}
05-13 13:09:31.282  6567  6567 D BreventServer: final blocking: {com.tencent.qqlive, com.netease.cloudmusic}
05-13 13:09:31.282  6567  6567 D BreventServer: notifications: {}
05-13 13:09:31.282  6567  6567 D BreventServer: noRecent: {}
05-13 13:09:31.282  6567  6567 D BreventServer: foreground service: {}
05-13 13:09:31.282  6567  6567 D BreventServer: gcm: {com.weico.international}
05-13 13:09:31.282  6567  6567 D BreventServer: sticky notification: {}
05-13 13:09:31.284  6567  6567 D BreventServer: check later for com.tencent.qqlive: 1864
05-13 13:09:31.285  6567  6567 D BreventServer: check later for com.netease.cloudmusic: 1643
05-13 13:09:31.287  6567  6567 D BreventServer: check again in 1643s
05-13 13:09:31.287  6567  6567 D BreventServer: check and brevent, took 152ms

> [processingScreenshot](https://www.dropbox.com/s/f4pfdp5vy1hj33l/EA484E437E4D1925E31FE1B373686155.png?dl=0)

> [BreventScreenshot](https://www.dropbox.com/s/z43oyxa2el08rli/E84644A6C1D0819E8FBD89B07F2024D9.png?dl=0)

**Comment by liudongmiao** [comment]
It's ok, and design like this.

If you opened an app, I think you may continued to use it later. 
So, default Brevent method is Standby, then Force-Stop.

Standby is running, however, no network activity.
When standby timeout, it will be force-stopped.

You can clear it from Recent Tasks, it will be force-stopped immediatly.
