### ISSUE TITLE
可否增加一个功能

### ISSUE THREAD

**Issue by linchen123** [liudongmiao/Brevent#487]
可否自定义某个应用的后台超时时间，和待机的超时时间

**Comment by liudongmiao** [comment]
没什么意义，设置麻烦，收益小。

你可以通过允许同步+主动从最近列表划掉完成绝大多数类似需求。

**Comment by linchen123** [comment]
谢谢，三星s8 QQ 和微信 开启同步只要一挂掉后台进程就彻底结束了不能收到信息推送 长年挂着影梭 谷歌的fcm    也没有问题啊

**Comment by liudongmiao** [comment]
开启同步，同时放入后台（如 按 Home）。

如果界面上有时间，还被强行停止了进程，不是黑域处理的。

至于其它的支持 FCM 的应用，只要开了允许同步，即使没有进程，也支持接收消息的，如 Play Console；而如果有同步类，即使没有进程，系统也会不定期唤醒，保证能接收消息的，如 QQ 邮箱。

我本地的话，使用 Play Console 接收 Play 商店中的评论，使用 QQ 邮箱接收发到 @piebridge.me 的反馈。偶尔有些延时外，没有丢过消息。

微信非标准 FCM，要收到  FCM 消息并通知比较困难，相比收益，个人建议对其电池未优化，且不要黑域，如果真的要黑域，开允许同步（比如当你从后台划掉它，表明真的想退出）。

**Comment by linchen123** [comment]
👌👌👌
