### ISSUE TITLE
一次性adb

### ISSUE THREAD

**Issue by vievenvua** [liudongmiao/Brevent#488]
看了【黑域】应用简介，说设备没重启一次就要adb一次，感觉这样挺麻烦的。今天看到了另一个应用【冰箱】，也可以免root用adb的这种方法，不过他的adb可以一次性，永久的。希望【黑域】也可以一次性adb。 。。。这样就可以给老妈的手机在不root的前提下，管好毒瘤了

**Comment by liudongmiao** [comment]
1. 他使用的是设备管理员。
设备管理员，要求你删除手机上所有帐号，并且，还是无法完成黑域所要的权限。

2. 黑域所使用的技术，无法通过已知的任何方式一次性授权。
同时，一次性授权也极不安全，试想，你不小心点了同意，被恶意软件利用，然后，你再也无法拖身，重启都没用。

3. 如果其它软件可以，用它就可以，没必要使用黑域。

4. 对于父母，少装软件才是王道。

**Comment by vievenvua** [comment]
大佬，是我想的简单了，确实安全也是最重要的。不过这样的话，我想问另外一个问题，其他那些一次性adb代替root的软件，会不会有安全性问题？

2017年5月14日 下午6:11，"Liu DongMiao" <notifications@github.com>写道：

**Comment by liudongmiao** [comment]
基本不会。因为重要的权限，无法被一次授予。
但是，一定要注意，像能保留的设备管理员，其它的重要权限，也不一定安全。
请谨慎选择。

对我而言，无法通过重启或者卸载解除限制的第三方应用，都是不安全的。
之前我也提到，相比黑域拥有的管理其它应用的权限，我更在意卸载之后，是否有其它副作用。

**Comment by vievenvua** [comment]
谢谢大佬指教。

在 2017年5月15日 上午10:11，Liu DongMiao <notifications@github.com>写道：
