### ISSUE TITLE
只有正在运行和没有运行，没有休眠。

### ISSUE THREAD

**Issue by cv0cv0** [liudongmiao/Brevent#49]
具体有没有生效没有试。

**Comment by liudongmiao** [comment]
是的，这是一个问题。我想，要休眠，必须是已经打开过。但识别打开过的应用，还有些问题。

这是为了让第三方唤醒的应用，不进入休眠，直接强行停止。

**Comment by liudongmiao** [comment]
我再测试下，明天给新包。但是奇怪的是，调系统接口返回的数据比系统界面看到的多，明天再看看怎么修正。

**Comment by liudongmiao** [comment]
已经发布 beta 版，请前住下载。

**Comment by liudongmiao** [comment]
请使用最新 beta 版测试：piebridge.me/br/

如果还有这个问题，请重开这个问题，谢谢。
