### ISSUE TITLE
黑域1.1.3 play版 设备同时登录两个Google账号时，一个捐赠过一个未捐赠，黑域无法使用捐赠功能

### ISSUE THREAD

**Issue by VanXNF** [liudongmiao/Brevent#490]
同时登录两个Google账号时，一个捐赠过一个未捐赠，黑域无法使用捐赠功能。
捐赠过的账号作为主要备份账号，未捐赠的是辅助账号，只同步了gmail. 删除了未捐赠账号后清空了Google所有数据和黑域数据，重装了黑域后依然无法识别捐赠，无法启用捐赠功能。

**Comment by liudongmiao** [comment]
我无法给出回复，因为确实是调用 Play 商店的 API。
你可以这样尝试下：请打开 Play 商店，切换到捐赠过的账号，按 Home 放到后台，然后进入黑域看看。

如果还不行，请从其它商店重新安装黑域，文件是完全一样的。如以下商店：
- 应用宝
- 酷安
- 魅族商店
- http://br.piebridge.me

**Comment by VanXNF** [comment]
下载了酷安的解决了 谢啦
