### ISSUE TITLE
FATAL EXCEPTION IN SYSTEM PROCESS: main

### ISSUE THREAD

**Issue by yuwenvss** [liudongmiao/Brevent#493]
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '05-16 11:12:57.000' -d
05-16 11:12:57.873 29819 29819 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
05-16 11:12:57.873 29819 29819 E AndroidRuntime: java.lang.reflect.InvocationTargetException
05-16 11:12:57.873 29819 29819 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-16 11:12:57.873 29819 29819 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1805)
05-16 11:12:57.873 29819 29819 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-16 11:12:57.873 29819 29819 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
05-16 11:12:57.873 29819 29819 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo android.content.pm.PackageInfo.applicationInfo' on a null object reference
05-16 11:12:57.873 29819 29819 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.f(BreventServer.java:1668)
05-16 11:12:57.873 29819 29819 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:217)
05-16 11:12:57.873 29819 29819 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1692)
05-16 11:12:57.873 29819 29819 E AndroidRuntime:        ... 4 more
05-16 11:12:57.877 29819 29819 E AndroidRuntime: Error reporting crash
05-16 11:12:57.877 29819 29819 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
05-16 11:12:57.877 29819 29819 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
05-16 11:12:57.877 29819 29819 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:608)
05-16 11:12:57.877 29819 29819 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4577)
05-16 11:12:57.877 29819 29819 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
05-16 11:12:57.877 29819 29819 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
05-16 11:12:57.877 29819 29819 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '05-16 11:12:57.000' -d -s BreventLoader BreventServer
05-16 11:12:57.535 29809 29809 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
05-16 11:12:57.866 29819 29819 I BreventServer: Brevent Server 1.1.3 started
05-16 11:12:57.871 29819 29819 I BreventServer: brevent user: 0, uid: 2000
05-16 11:12:57.886 29809 29809 E BreventLoader: worker 29819 exited on signal 9
05-16 11:12:57.886 29809 29809 D BreventLoader: signal arrived, update: 0
05-16 11:12:57.887 29797 29797 D BreventLoader: worker 29809 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
先试最新的 1.1.6，然后再看问题是否存的。

**Comment by liudongmiao** [comment]
please try the latest 1.1.6.
