### ISSUE TITLE
brevent-server 文件夹好像没有上传？

### ISSUE THREAD

**Issue by rockman1949** [liudongmiao/Brevent#494]
如题

**Comment by liudongmiao** [comment]
这个不开源。但是不影响你自己编译。

为了便于自己处理，现在，brevent-server 中的内容，单独编译成了 classes2.dex。

不开源的原因有两点：

1. 不想公开技术细节，原理实际上相当简单
2. 不开源，也不会影响大家信任。而且，我想，绝大多数人，都不会去改这里面的代码。

目前的这种方式，并不影响整个项目的自己编译。
如果你对于 brevent-server 这部分感兴趣，可以给项目 pr 一些功能后，表示对项目理解，我可以单独开放。

比如搜索，比如日志。
