### ISSUE TITLE
缺少其余两个黑域方法

### ISSUE THREAD

**Issue by guoyonganceo** [liudongmiao/Brevent#495]
我用的是1.1.6版本，Rom是LinageOS-20170331
如图所示：
![Screenshot_20170517-120009.png](https://ooo.0o0.ooo/2017/05/17/591bcbbbb88d9.png)

**Comment by liudongmiao** [comment]
你的系统就是不支持而已。要你的系统支持的话，请安装 GMS。

**Comment by guoyonganceo** [comment]
哦，原来是这样子。现在就去装个GMS
