### ISSUE TITLE
Permission denied的问题

### ISSUE THREAD

**Issue by sensendeni** [liudongmiao/Brevent#496]
之前是可以用的，1.1.1，今天重启后就提示Permission denied。更新到1.1.6还是不行，求解答
截图如下：
![_20170517125007](https://cloud.githubusercontent.com/assets/9124620/26139054/68a1edac-3b00-11e7-909f-57727912f13e.png)

**Comment by sensendeni** [comment]
![_20170517125853](https://cloud.githubusercontent.com/assets/9124620/26139079/a498b34a-3b00-11e7-8a85-f630115e24d2.jpg)

**Comment by liudongmiao** [comment]
你使用的可能是一个被改动的 brevent.sh，请使用这个命令，会打出这个指令的调试信息。

```
adb -d shell sh -x /sdcard/Android/data/me.piebridge.brevent/brevent.sh
```

**Comment by sensendeni** [comment]
@liudongmiao  截图如下
![_20170517141758](https://cloud.githubusercontent.com/assets/9124620/26140890/bfc6ead2-3b0b-11e7-9014-3ae4cdb6f231.png)

**Comment by sensendeni** [comment]
刚刚不死心又试了一次，这次没有Permission denied的问题了，好奇怪

**Comment by liudongmiao** [comment]
能电脑上安装个 teamviewer，然后把 id 与 密码发到这个邮箱么？

br@piebridge.me

**Comment by sensendeni** [comment]
@liudongmiao 已发送

**Comment by sensendeni** [comment]
@liudongmiao 非常感谢！

**Comment by liudongmiao** [comment]
兼容性问题，下个版本修复。
