### ISSUE TITLE
更新1.1.3以后酷安更新应用会被干掉

### ISSUE THREAD

**Issue by hubeixulu** [liudongmiao/Brevent#497]
1.1.3之前酷安虽然加入到黑域列表了，但是能正常更新应用，更新1.1.3以后，酷安更新应用会直接被干掉
05-17 16:45:46.680 11024 11024 D BreventServer: check and brevent
05-17 16:45:46.807 11024 11024 D BreventServer: check again in 59s
05-17 16:45:46.807 11024 11024 D BreventServer: check and brevent, took 125ms
05-17 16:45:53.695 11024 11024 D BreventServer: com.coolapk.market: priority
05-17 16:45:55.044 11024 11024 D BreventServer: check and brevent
05-17 16:45:55.200 11024 11024 D BreventServer: Force stop com.coolapk.market(previous running)
05-17 16:45:55.203 11024 11024 D BreventServer: check again in 3600s
05-17 16:45:55.203 11024 11024 D BreventServer: check and brevent, took 158ms
05-17 16:45:55.692 11024 11024 D BreventServer: checking feelgood
05-17 16:45:55.693 11024 11033 D BreventServer: received feelgood
05-17 16:46:22.648 11024 11024 D BreventServer: checking feelgood
05-17 16:46:22.649 11024 11033 D BreventServer: received feelgood
05-17 16:46:26.702 11024 11024 D BreventServer: check and brevent
05-17 16:46:26.888 11024 11024 D BreventServer: Force stop com.coolapk.market(service)
05-17 16:46:26.893 11024 11024 D BreventServer: check again in 3600s
05-17 16:46:26.893 11024 11024 D BreventServer: check and brevent, took 190ms
05-17 16:46:31.529 11024 11024 D BreventServer: check and brevent
05-17 16:46:31.689 11024 11024 D BreventServer: check again in 3600s
05-17 16:46:31.689 11024 11024 D BreventServer: check and brevent, took 160ms
05-17 16:46:36.529 11024 11024 D BreventServer: checking feelgood
05-17 16:46:36.531 11024 11033 D BreventServer: received feelgood
05-17 16:46:45.420 11024 11024 D BreventServer: checking feelgood
05-17 16:46:45.421 11024 11033 D BreventServer: received feelgood
05-17 16:46:58.194 11024 11024 D BreventServer: check and brevent
05-17 16:46:58.396 11024 11024 D BreventServer: check again in 3600s
05-17 16:46:58.397 11024 11024 D BreventServer: check and brevent, took 200ms
05-17 16:47:30.487 11024 11024 D BreventServer: checking feelgood
05-17 16:47:30.489 11024 11033 D BreventServer: received feelgood
05-17 16:48:14.050 11024 11024 D BreventServer: check and brevent
05-17 16:48:14.410 11024 11024 D BreventServer: check again in 3600s
05-17 16:48:14.410 11024 11024 D BreventServer: check and brevent, took 356ms

**Comment by liudongmiao** [comment]
1. 检查是否开启了检查通知，并且对它 允许同步

2. 当你要允许它更新应用时，不要退出应用（如按 Back，你可以按 Home 放后台），否则，是期望行为
