### ISSUE TITLE
Auto start Brevent Server

### ISSUE THREAD

**Issue by Zero3K** [liudongmiao/Brevent#498]
It would be nice if it could auto start itself on the Android Device instead of having to start it via adb every time it is restarted.

**Comment by liudongmiao** [comment]
If it's rooted, there is way. Please read Guide more carefully.

If it's not rooted, it's impossible. And try to think about this, if it's possible, and malicious apps use this techlogy (Just via a adb command), if you no way to escape but do a factory reset.

For myself, I only reboot my phone after OTA upgrade.

**Comment by liudongmiao** [comment]
And from #499 , it seems you use an old Android version.

You can consider other apps, like greenify with Xposed module, or Prevent Running (Xposed module).

**Comment by Zero3K** [comment]
I cannot root the Acer Iconia One 8.

**Comment by Zero3K** [comment]
I am trying to use https://play.google.com/store/apps/details?id=os.tools.scriptmanager&hl=en to run the script for loading the service at startup but it told me to please install Brevent even though it is already installed.

**Comment by Zero3K** [comment]
Is it not possible to run the script directly on the Android Device via that program?

**Comment by liudongmiao** [comment]
Normal apps has no permissions required by Brevent. The permissions cannot be granted once.
However, `adb shell` has the permissins, and `root` has the permissions too.

**Comment by Zero3K** [comment]
Are there any commands that can be used to grant the permissions like how Greenify has commands for its permissions?

**Comment by Zero3K** [comment]
Oh, how about making a program that runs on the PC which runs the command when it notices that an Android device with Brevent installed being plugged in via USB?

**Comment by liudongmiao** [comment]
Actually, Greenify has no such permissions too.

Brevent requires two permissions:
1. App Standby. Greenify only offers this function for ROOT mode.

2. Force Stop. Greenify can offer this function by click-emulation for non-ROOT mode. But I don't think it's ok for daily usage, so it only apply when screen is turn off.

You can make your own version. However, I don't offer any suport. A simple `bat` may like this.

```
adb wait-for-device
adb shell /data/local/tmp/brevent
```

for `/data/local/tmp/brevent`, please copy from APK (unzip the apk, you'll find libbrevent.so).

And, I don't think it's too difficult for you to run `adb -d shell sh /sdcard/Android/...`. Brevent don't requires you to execute this when it's upgraded.

**Comment by Zero3K** [comment]
Well, I still have to run the batch file. I just want a way to have it ran automatically when the device is plugged in. Maybe someone else can make it for me and everyone else.

**Comment by liudongmiao** [comment]
If you reboot phone very frequently, then Brevent is not suitable for you.

**Comment by Zero3K** [comment]
Oh, ok. I just read that its better to keep it on anyways.
