### ISSUE TITLE
Error when starting Brevent Server

### ISSUE THREAD

**Issue by Zero3K** [liudongmiao/Brevent#499]
When I run the command to start it, I get the following error:

WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6ffffffe arg 0xd28

I am running Brevent on an Acer Iconia One 8 that is running Android 5.1. Also, here is a link to some information about the error and how to fix it:

http://stackoverflow.com/questions/33206409/unused-dt-entry-type-0x1d-arg

**Comment by liudongmiao** [comment]
It's a warning, you can just ignore it.

**Comment by liudongmiao** [comment]
I didn't fix this warning, it's very simple:

Adnrodi 5.X warning this entry, Android 6.0+ requires this entry.

I don't think it's ok to patch serveral binary just to omit this warning.
