### ISSUE TITLE
Nexus 5x 进行到打补丁patch.py 这一步找不到 services/com/android/server/IntentResolver.smali

### ISSUE THREAD

**Issue by stormb0rn** [liudongmiao/Brevent#5]
Nexus 5x 进行到打补丁patch.py 这一步找不到 services/com/android/server/IntentResolver.smali
![image](https://cloud.githubusercontent.com/assets/4110314/19972972/b870a470-a21e-11e6-98c4-1a789fa92104.png)
![image](https://cloud.githubusercontent.com/assets/4110314/19972988/cc2a2e8c-a21e-11e6-9140-81b90d408306.png)

**Comment by liudongmiao** [comment]
那肯定是缺失这几个文件。看你的样子，已经打过老式的补丁？请恢复系统，然后重新处理。
