### ISSUE TITLE
How much RAM does it use total?

### ISSUE THREAD

**Issue by Zero3K** [liudongmiao/Brevent#501]
I am curious in knowing since I cannot see the program and its service in the Running List of the Apps page that is accessible via the Settings App.

**Comment by liudongmiao** [comment]
It's very little, you can ignore it.

You can use `ps` command to get cpu / ram for theses processes:
- `brevent_daemon`, it's a daemon keep `brevent_server` upgradeable
- `brevent_server`, real brevent server

And for the battery usage, you can click brevent, then click Brevent Server Info, it's actually Shell. to get it's battery usage. Very little.
