### ISSUE TITLE
Android O尚无法启动服务？

### ISSUE THREAD

**Issue by GabrielCheungX** [liudongmiao/Brevent#503]
电脑端使用 adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh 报错，请问是否还不支持Android O?

**Comment by liudongmiao** [comment]
报错也要贴出日志啊。

我在模拟器上试了刚出的 dp2，没问题；之前真机上的 dp1，也没问题。

**Comment by GabrielCheungX** [comment]
不好意思 我这边网不太好 刚才没传成功附件，重新试了下是可以启动服务的
