### ISSUE TITLE
1.1.8无法使用

### ISSUE THREAD

**Issue by chinen95** [liudongmiao/Brevent#509]
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '05-19 02:00:23.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '05-19 02:00:23.000' -d -s BreventLoader BreventServer
05-19 02:00:25.542  8568  8568 E BreventLoader: worker 8574 exited with status 255
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

然后上个版本的11.5天有时会失效变成1分钟

**Comment by liudongmiao** [comment]
日志内容太少，特别是没有有用的日志信息。

**Comment by chinen95** [comment]
play的评论中 升了1.1.8不能用的不止我一个

**Comment by liudongmiao** [comment]
那就先使用 1.1.6 吧，1.1.6 到 1.1.8 没有实质改进。

**Comment by chinen95** [comment]
在哪可以下到play版的历史版本

**Comment by liudongmiao** [comment]
你可以保留这个地址：https://piebridge.me/br/

历史版本在 archive 下：https://piebridge.me/br/archive/
测试版在 next 下。

稍后我会修复它。明明我在虚拟机里测试通过的，但是确实用不了。

此外，自 1.1.7 起，采用 Google Play App Signing 技术，play 版与普通版 apk 包内容不再完全一样。
但是，代码完全一样，只是被 Google Play App Signing 加了一小点东西。
本来只是想测试一下，但一旦加入，无法退出。英文不好啊。

**Comment by liudongmiao** [comment]
稍后的意思是，晚上下班后....

**Comment by liudongmiao** [comment]
我继续在虚拟机里测试，没有问题。

抱歉，我自己不 root 。

**Comment by tgr989** [comment]
我的没root，也不能用。1.1.6没问题

**Comment by chm512512** [comment]
root的我一直正常😳

**Comment by liudongmiao** [comment]
@tgr989 你得带日志，最好单开一个问题..没日志，我什么都不知道。

**Comment by chinen95** [comment]
我测试了几个设备 都是7.x 错误完全一样

**Comment by chinen95** [comment]
通过电脑端的adb工具执行可用 本机不管su执行 su shell执行都报错 su切换登陆出来的shell(/dev/pts/2)和adb工具登录的shell(/dev/pts/3)不知有什么区别

**Comment by liudongmiao** [comment]
你这个日志太简单。

先看最新测试版。如果不行，就约时间，电脑上安装 teamviewer，我登录上去调试。
