### ISSUE TITLE
打开视频或音频链接跳转至第三方应用进行播放，后台应用停止运行，导致第三方应用闪退

### ISSUE THREAD

**Issue by sosmygirl** [liudongmiao/Brevent#51]
比如微博中的bilibili视频链接，通过bilibili客户端打开，播放几十秒就退出到桌面了。查看黑域，微博已停止运行。
前者应用停止运行导致打开链接的应用也无法继续加载该链接。
在文件管理软件中也会出现这种问题

黑域版本：05pre06

**Comment by liudongmiao** [comment]
请使用最新的 beta2 以上看下，下载地址：https://piebridge.me/br/

**Comment by sosmygirl** [comment]
ok，我试一下

**Comment by sosmygirl** [comment]
完美解决，现在不会停止运行了，作者v5
