### ISSUE TITLE
Does this log look like it contains any fixable errors?

### ISSUE THREAD

**Issue by Zero3K** [liudongmiao/Brevent#510]
C:\Program Files\gnirehtet>adb -d logcat -d -b main -s BreventServer BreventLoad
er
E/BreventLoader(24571): worker 24585 exited on signal 15
D/BreventLoader(24571): signal arrived, update: 0
D/BreventLoader(24725): loader path: /data/app/me.piebridge.brevent-2/base.apk
I/BreventServer(24739): Brevent Server 1.1.8 started
I/BreventServer(24739): brevent user: 0, uid: 2000
I/BreventServer(24739): brevent data directory: /data/data/com.android.shell
I/BreventServer(24739): android providers: {com.android.providers.calendar, com.
android.providers.media, com.android.providers.downloads, com.android.providers.
applications, com.android.providers.downloads.ui, com.android.providers.partnerb
ookmarks, com.android.providers.userdictionary, com.android.providers.contacts}
I/BreventServer(24739): loading brevent list
I/BreventServer(24739): load /data/data/com.android.shell/me.piebridge.brevent.l
ist, size: 65
D/BreventServer(24739): Force stop com.ubisoft.raymanadventures(load brevent)
D/BreventServer(24739): Force stop com.mediatek.fwk.plugin(load brevent)
D/BreventServer(24739): Force stop com.android.wallpapercropper(load brevent)
D/BreventServer(24739): Force stop com.acer.android.acernidus(load brevent)
D/BreventServer(24739): Force stop com.android.documentsui(load brevent)
D/BreventServer(24739): Force stop com.android.galaxy4(load brevent)
D/BreventServer(24739): Force stop com.android.externalstorage(load brevent)
D/BreventServer(24739): Force stop com.acer.deskclock(load brevent)
D/BreventServer(24739): Force stop com.acer.android.home(load brevent)
D/BreventServer(24739): Force stop com.acer.android.oobe(load brevent)
D/BreventServer(24739): Force stop org.ais.archidroid(load brevent)
D/BreventServer(24739): Force stop com.bandainamcoent.jojodr(load brevent)
D/BreventServer(24739): Force stop com.myzone.myzoneble(load brevent)
D/BreventServer(24739): Force stop com.android.browser.provider(load brevent)
D/BreventServer(24739): Force stop com.nintendo.zara(load brevent)
D/BreventServer(24739): Force stop com.bandainamcoent.torays(load brevent)
D/BreventServer(24739): Force stop com.google.android.configupdater(load brevent
)
D/BreventServer(24739): Force stop com.square_enix.android_googleplay.subarashik
ikonosekai_solo(load brevent)
D/BreventServer(24739): Force stop com.android.pacprocessor(load brevent)
D/BreventServer(24739): Force stop com.snkplaymore.android010(load brevent)
D/BreventServer(24739): Force stop com.eolwral.osmonitor(load brevent)
D/BreventServer(24739): Force stop com.netmarble.mherosgb(load brevent)
D/BreventServer(24739): Force stop me.piebridge.brevent(load brevent)
D/BreventServer(24739): Force stop com.android.backupconfirm(load brevent)
D/BreventServer(24739): Force stop com.instagram.android(load brevent)
D/BreventServer(24739): Force stop com.greenlogger.widget.bluetooth(load brevent
)
D/BreventServer(24739): Force stop klye.plugin.en(load brevent)
D/BreventServer(24739): Force stop com.mediatek.floatmenu(load brevent)
D/BreventServer(24739): Force stop com.acer.byocoobe(load brevent)
D/BreventServer(24739): Force stop com.appiator.defaultappmanager(load brevent)
D/BreventServer(24739): Force stop com.android.sharedstoragebackup(load brevent)

D/BreventServer(24739): Force stop com.mxtech.videoplayer.ad(load brevent)
D/BreventServer(24739): Force stop com.acer.android.carecenter(load brevent)
D/BreventServer(24739): Force stop com.square_enix.android_googleplay.valkyriejp
(load brevent)
D/BreventServer(24739): Force stop com.google.android.apps.maps(load brevent)
D/BreventServer(24739): Force stop com.klab.bleach(load brevent)
D/BreventServer(24739): Force stop jp.takmurata.twitwick2(load brevent)
D/BreventServer(24739): Force stop jaineel.videoconvertor(load brevent)
D/BreventServer(24739): Force stop com.android.gallery3d(load brevent)
D/BreventServer(24739): Force stop com.dev47apps.droidcamx(load brevent)
D/BreventServer(24739): Force stop com.netflix.mediaclient(load brevent)
D/BreventServer(24739): Force stop com.android.managedprovisioning(load brevent)

D/BreventServer(24739): Force stop com.andysi.freevideochatonline(load brevent)
D/BreventServer(24739): Force stop com.actgames.bbrr.sgp(load brevent)
D/BreventServer(24739): Force stop com.android.wallpaper.livepicker(load brevent
)
D/BreventServer(24739): Force stop org.blackmart.market(load brevent)
D/BreventServer(24739): Force stop com.square_enix.android_googleplay.DFFOperaOm
niaj(load brevent)
D/BreventServer(24739): Force stop org.mozilla.firefox(load brevent)
D/BreventServer(24739): Force stop com.sonyericsson.trackid(load brevent)
D/BreventServer(24739): Force stop air.com.chat.live173(load brevent)
D/BreventServer(24739): Force stop com.android.calculator2(load brevent)
D/BreventServer(24739): Force stop com.square_enix.android_googleplay.StarOceanj
(load brevent)
D/BreventServer(24739): Force stop com.greenlogger.widget.wifi(load brevent)
D/BreventServer(24739): Force stop com.acer.quicklauncher(load brevent)
D/BreventServer(24739): Force stop com.android.wallpaper(load brevent)
D/BreventServer(24739): Force stop com.android.vpndialogs(load brevent)
D/BreventServer(24739): Force stop com.alensw.PicFolder(load brevent)
D/BreventServer(24739): Force stop com.ratcash.wifiperf(load brevent)
D/BreventServer(24739): Force stop com.mediatek.filemanager(load brevent)
D/BreventServer(24739): Force stop com.almalence.opencam_plus(load brevent)
D/BreventServer(24739): Force stop com.android.freehand.capture(load brevent)
D/BreventServer(24739): Force stop com.google.android.androidforwork(load breven
t)
D/BreventServer(24739): Force stop com.android.captiveportallogin(load brevent)
D/BreventServer(24739): Force stop com.mediatek.dataprotection(load brevent)
D/BreventServer(24739): brevent: {com.ubisoft.raymanadventures, com.mediatek.fwk
.plugin, com.android.wallpapercropper, com.acer.android.acernidus, com.android.d
ocumentsui, com.android.galaxy4, com.android.externalstorage, com.acer.deskclock
, com.acer.android.home, com.acer.android.oobe, org.ais.archidroid, com.bandaina
mcoent.jojodr, com.myzone.myzoneble, com.android.browser.provider, com.nintendo.
zara, com.bandainamcoent.torays, com.google.android.configupdater, com.square_en
ix.android_googleplay.subarashikikonosekai_solo, com.android.pacprocessor, com.s
nkplaymore.android010, com.eolwral.osmonitor, com.netmarble.mherosgb, me.piebrid
ge.brevent, com.android.backupconfirm, com.instagram.android, com.greenlogger.wi
dget.bluetooth, klye.plugin.en, com.mediatek.floatmenu, com.acer.byocoobe, com.a
ppiator.defaultappmanager, com.lonelycatgames.PM, com.android.sharedstoragebacku
p, com.mxtech.videoplayer.ad, com.acer.android.carecenter, com.square_enix.andro
id_googleplay.valkyriejp, com.google.android.apps.maps, com.klab.bleach, jp.takm
urata.twitwick2, jaineel.videoconvertor, com.android.gallery3d, com.dev47apps.dr
oidcamx, com.netflix.mediaclient, com.android.managedprovisioning, com.andysi.fr
eevideochatonline, com.actgames.bbrr.sgp, com.android.wallpaper.livepicker, org.
blackmart.market, com.square_enix.android_googleplay.DFFOperaOmniaj, org.mozilla
.firefox, com.sonyericsson.trackid, air.com.chat.live173, com.android.calculator
2, com.square_enix.android_googleplay.StarOceanj, com.greenlogger.widget.wifi, c
om.acer.quicklauncher, com.android.wallpaper, com.android.vpndialogs, com.alensw
.PicFolder, com.ratcash.wifiperf, com.mediatek.filemanager, com.almalence.openca
m_plus, com.android.freehand.capture, com.google.android.androidforwork, com.and
roid.captiveportallogin, com.mediatek.dataprotection}
D/BreventServer(24739): priority: {}
I/BreventServer(24739): loading brevent conf
D/BreventServer(24739): notification_cancel_all, tag: 2752, event: 4
D/BreventServer(24739): notification_panel_revealed, tag: 27500, event: 6
D/BreventServer(24739): notification_panel_hidden, tag: 27501, event: 7
D/BreventServer(24739): am_new_intent, tag: 30003, event: 8
D/BreventServer(24739): am_resume_activity, tag: 30007, event: 2
D/BreventServer(24739): am_pause_activity, tag: 30013, event: 9
D/BreventServer(24739): am_proc_start, tag: 30014, event: 1
D/BreventServer(24739): am_switch_user, tag: 30041, event: 3
D/BreventServer(24739): screen_toggled, tag: 70000, event: 5
D/BreventServer(24739): received feelgood
D/BreventServer(24739): check and brevent
D/BreventServer(24739): received feelgood
D/BreventServer(24739): received feelgood
W/BreventServer(24739): Can't parse stack:   Stack #0(isFloating:false):
W/BreventServer(24739): Can't parse stack:   Stack #1(isFloating:false):
D/BreventServer(24739): widgets: {}
D/BreventServer(24739): running: {ginlemon.flowerfree=63429, com.skype.raider=64
053, com.android.vending=61810, com.realvnc.viewer.android=64053, co.uk.syslynx.
wifiwebloginapp=64053, com.foxnews.android=63428, com.lonelycatgames.PM=58646, c
om.abtnprojects.ambatana=64053, com.duapps.recorder=53430, com.android.settings=
64053, com.android.systemui=58545}
D/BreventServer(24739): recent: {com.android.vending=1356, me.piebridge.brevent=
1487, com.foxnews.android=2974, com.android.settings=1440}
D/BreventServer(24739): inactive for com.lonelycatgames.PM: 5407, timeout: 1800
D/BreventServer(24739): com.google.android.webview depended by {com.android.vend
ing, com.foxnews.android, com.lonelycatgames.PM, com.google.android.gms}
D/BreventServer(24739): com.google.android.gms depended by {ginlemon.flowerfree,
 com.google.android.youtube, com.android.vending, com.foxnews.android}
D/BreventServer(24739): service: {}
D/BreventServer(24739): back(no action): {}
D/BreventServer(24739): blocking: {com.lonelycatgames.PM}
D/BreventServer(24739): top: {ginlemon.flowerfree, com.android.vending}
D/BreventServer(24739): home: {}
D/BreventServer(24739): current: null
D/BreventServer(24739): next: null
D/BreventServer(24739): unsafe: {}
D/BreventServer(24739): final blocking: {com.lonelycatgames.PM}
D/BreventServer(24739): notifications: {com.android.providers.media=[268435554],
 com.joeperkins.nws=[98], com.oasisfeng.bytesinsight=[0], com.digibites.accubatt
ery=[98], com.jamworks.noheadsup=[98], com.lonelycatgames.PM=[98], com.klma.rece
ntbar=[2], com.duapps.recorder=[2], net.loadinghome.smartunlock=[98], com.applay
.overlay=[114], com.synetics.stay.alive=[98], net.mybesttools.bkeepawake=[16]}
D/BreventServer(24739): noRecent: {com.lonelycatgames.PM}
D/BreventServer(24739): foreground service: {com.lonelycatgames.PM}
D/BreventServer(24739): gcm: {}
D/BreventServer(24739): sticky notification: {com.lonelycatgames.PM}
D/BreventServer(24739): check again in 3600s
D/BreventServer(24739): check and brevent, took 182ms
D/BreventServer(24739): Can't setStopped for me.piebridge.brevent(ignore)
D/BreventServer(24739): Can't setStopped for me.piebridge.brevent(ignore)
W/BreventServer(24739): Can't parse stack:   Stack #0(isFloating:false):
W/BreventServer(24739): Can't parse stack:   Stack #1(isFloating:false):
D/BreventServer(24739): sent first status
D/BreventServer(24739): pause activity, tid: 671, packageName: ginlemon.flowerfr
ee
D/BreventServer(24739): resume activity, tid: 1514, packageName: ginlemon.flower
free, launcher: ginlemon.flowerfree
D/BreventServer(24739): pause activity, tid: 712, packageName: ginlemon.flowerfr
ee
D/BreventServer(24739): Can't setStopped for me.piebridge.brevent(ignore)
D/BreventServer(24739): Can't setStopped for me.piebridge.brevent(ignore)
D/BreventServer(24739): pause activity, tid: 1728, packageName: me.piebridge.bre
vent
D/BreventServer(24739): pause activity, tid: 775, packageName: me.piebridge.brev
ent
D/BreventServer(24739): resume activity, tid: 1278, packageName: ginlemon.flower
free, launcher: ginlemon.flowerfree
D/BreventServer(24739): pause activity, tid: 935, packageName: ginlemon.flowerfr
ee
D/BreventServer(24739): resume activity, tid: 687, packageName: com.android.vend
ing, launcher: ginlemon.flowerfree
D/BreventServer(24739): pause activity, tid: 1513, packageName: com.android.vend
ing
D/BreventServer(24739): pause activity, tid: 1523, packageName: com.android.vend
ing
D/BreventServer(24739): pause activity, tid: 1728, packageName: com.android.vend
ing
D/BreventServer(24739): resume activity, tid: 28139, packageName: com.android.ve
nding, launcher: ginlemon.flowerfree
D/BreventServer(24739): pause activity, tid: 1523, packageName: com.android.vend
ing
D/BreventServer(24739): resume activity, tid: 712, packageName: com.android.vend
ing, launcher: ginlemon.flowerfree
D/BreventServer(24739): pause activity, tid: 775, packageName: com.android.vendi
ng
D/BreventServer(24739): resume activity, tid: 712, packageName: ginlemon.flowerf
ree, launcher: ginlemon.flowerfree
D/BreventServer(24739): pause activity, tid: 1513, packageName: ginlemon.flowerf
ree
D/BreventServer(24739): Can't setStopped for me.piebridge.brevent(ignore)
D/BreventServer(24739): Can't setStopped for me.piebridge.brevent(ignore)
D/BreventServer(24739): resume activity, tid: 712, packageName: ginlemon.flowerf
ree, launcher: ginlemon.flowerfree
D/BreventServer(24739): pause activity, tid: 1251, packageName: ginlemon.flowerf
ree
D/BreventServer(24739): Can't setStopped for me.piebridge.brevent(ignore)
D/BreventServer(24739): Can't setStopped for me.piebridge.brevent(ignore)
D/BreventServer(24739): pause activity, tid: 686, packageName: me.piebridge.brev
ent
D/BreventServer(24739): pause activity, tid: 1407, packageName: me.piebridge.bre
vent
D/BreventServer(24739): pause activity, tid: 1407, packageName: com.android.sett
ings
D/BreventServer(24739): resume activity, tid: 1514, packageName: me.piebridge.br
event, launcher: ginlemon.flowerfree
D/BreventServer(24739): Can't setStopped for me.piebridge.brevent(ignore)
D/BreventServer(24739): pause activity, tid: 28139, packageName: me.piebridge.br
event
D/BreventServer(24739): resume activity, tid: 1535, packageName: me.piebridge.br
event, launcher: ginlemon.flowerfree
D/BreventServer(24739): Can't setStopped for me.piebridge.brevent(ignore)
D/BreventServer(24739): pause activity, tid: 687, packageName: me.piebridge.brev
ent
D/BreventServer(24739): resume activity, tid: 1304, packageName: ginlemon.flower
free, launcher: ginlemon.flowerfree
D/BreventServer(24739): abnormal back: me.piebridge.brevent
D/BreventServer(24739): pause activity, tid: 671, packageName: ginlemon.flowerfr
ee
D/BreventServer(24739): resume activity, tid: 671, packageName: ginlemon.flowerf
ree, launcher: ginlemon.flowerfree
D/BreventServer(24739): pause activity, tid: 671, packageName: ginlemon.flowerfr
ee
D/BreventServer(24739): resume activity, tid: 671, packageName: ginlemon.flowerf
ree, launcher: ginlemon.flowerfree
D/BreventServer(24739): pause activity, tid: 1513, packageName: ginlemon.flowerf
ree
D/BreventServer(24739): pause activity, tid: 1523, packageName: com.foxnews.andr
oid
D/BreventServer(24739): pause activity, tid: 935, packageName: com.foxnews.andro
id
D/BreventServer(24739): resume activity, tid: 712, packageName: ginlemon.flowerf
ree, launcher: ginlemon.flowerfree
D/BreventServer(24739): check and brevent
W/BreventServer(24739): Can't parse stack:   Stack #0(isFloating:false):
W/BreventServer(24739): Can't parse stack:   Stack #1(isFloating:false):
D/BreventServer(24739): widgets: {}
D/BreventServer(24739): running: {ginlemon.flowerfree=63428, com.skype.raider=64
056, com.android.vending=61809, com.realvnc.viewer.android=64056, co.uk.syslynx.
wifiwebloginapp=64056, com.foxnews.android=63428, com.lonelycatgames.PM=58645, c
om.abtnprojects.ambatana=64056, com.duapps.recorder=53430, com.android.settings=
64056, com.android.systemui=58545}
D/BreventServer(24739): recent: {com.android.vending=1353, me.piebridge.brevent=
1484, com.foxnews.android=2971, com.android.settings=1437}
D/BreventServer(24739): inactive for com.lonelycatgames.PM: 5411, timeout: 1800
D/BreventServer(24739): com.google.android.webview depended by {com.android.vend
ing, com.foxnews.android, com.lonelycatgames.PM, com.google.android.gms}
D/BreventServer(24739): com.google.android.gms depended by {ginlemon.flowerfree,
 com.google.android.youtube, com.android.vending, com.foxnews.android}
D/BreventServer(24739): service: {}
D/BreventServer(24739): back(no action): {me.piebridge.brevent}
D/BreventServer(24739): blocking: {com.lonelycatgames.PM}
D/BreventServer(24739): top: {ginlemon.flowerfree, com.android.vending}
D/BreventServer(24739): home: {}
D/BreventServer(24739): current: ginlemon.flowerfree
D/BreventServer(24739): next: com.android.settings
D/BreventServer(24739): unsafe: {}
D/BreventServer(24739): final blocking: {com.lonelycatgames.PM}
D/BreventServer(24739): notifications: {com.android.providers.media=[268435554],
 com.joeperkins.nws=[98], com.oasisfeng.bytesinsight=[0], com.digibites.accubatt
ery=[98], com.jamworks.noheadsup=[98], com.lonelycatgames.PM=[98], com.klma.rece
ntbar=[2], com.duapps.recorder=[2], net.loadinghome.smartunlock=[98], com.applay
.overlay=[114], com.synetics.stay.alive=[98], net.mybesttools.bkeepawake=[16]}
D/BreventServer(24739): noRecent: {com.lonelycatgames.PM}
D/BreventServer(24739): foreground service: {com.lonelycatgames.PM}
D/BreventServer(24739): gcm: {}
D/BreventServer(24739): sticky notification: {com.lonelycatgames.PM}
D/BreventServer(24739): check again in 3600s
D/BreventServer(24739): check and brevent, took 181ms

**Comment by liudongmiao** [comment]
```
 E/BreventLoader(24571): worker 24585 exited on signal 15

W/BreventServer(24739): Can't parse stack: Stack #0(isFloating:false):
W/BreventServer(24739): Can't parse stack: Stack #1(isFloating:false):
```

A error, can be ignored if Brevent works.

Some warning, you can ignore it.
