### ISSUE TITLE
魅族pro5 flyme6.7.5.9（android 5.1）有两个警告

### ISSUE THREAD

**Issue by tgr989** [liudongmiao/Brevent#512]
用起来没问题，但是强迫症了，反馈一下
adb -d shell sh /sdcard/Android/data/me.piebridge.brevent/brevent.sh
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6ffffffe arg 0xd28
WARNING: linker: /data/local/tmp/brevent: unused DT entry: type 0x6fffffff arg 0x1
checking...brevent_server started, pid: 
checking for stable...........ok

if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

**Comment by liudongmiao** [comment]
呃，在别的 issue 里提到过，不过是英文的。

主要吧，如果去掉了这些 unused DT entry，高版本就无法运行了。
虽然可以对低版本单独提供二进制文件，但 apk 包会变大，衡量之后，决定就这样。
