### ISSUE TITLE
1.18,啊哈，我来报bug了

### ISSUE THREAD

**Issue by chm512512** [liudongmiao/Brevent#514]
05-19 16:07:04.255 20200 20200 D BreventServer: checking feelgood
05-19 16:07:04.287 20200 20271 D BreventServer: received feelgood
05-19 16:07:05.696 20200 20200 D BreventServer: check and brevent
05-19 16:07:05.849 20200 20200 D BreventServer: widgets: {}
05-19 16:07:05.849 20200 20200 D BreventServer: running: {me.piebridge.brevent=142271}
05-19 16:07:05.849 20200 20200 D BreventServer: recent: {me.piebridge.brevent=3599}
05-19 16:07:05.857 20200 20200 D BreventServer: inactive for com.android.musicfx: 0, timeout: 3600
05-19 16:07:05.858 20200 20200 D BreventServer: inactive for com.android.smspush: 0, timeout: 3600
05-19 16:07:05.858 20200 20200 D BreventServer: inactive for com.netease.cloudmusic: 0, timeout: 3600
05-19 16:07:05.909 20200 20200 D BreventServer: service: {}
05-19 16:07:05.909 20200 20200 D BreventServer: back(no action): {com.coolapk.market}
05-19 16:07:05.909 20200 20200 D BreventServer: blocking: {com.android.musicfx, com.android.smspush, com.netease.cloudmu
sic}
05-19 16:07:05.911 20200 20200 D BreventServer: top: {me.piebridge.brevent}
05-19 16:07:05.911 20200 20200 D BreventServer: home: {com.android.launcher3, com.android.systemui}
05-19 16:07:05.911 20200 20200 D BreventServer: current: me.piebridge.brevent
05-19 16:07:05.911 20200 20200 D BreventServer: next: me.piebridge.brevent
05-19 16:07:05.911 20200 20200 D BreventServer: unsafe: {}
05-19 16:07:05.911 20200 20200 D BreventServer: final blocking: {com.android.musicfx, com.android.smspush, com.netease.c
loudmusic}
05-19 16:07:05.911 20200 20200 D BreventServer: notifications: {}
05-19 16:07:05.911 20200 20200 D BreventServer: noRecent: {com.android.musicfx, com.android.smspush, com.netease.cloudmu
sic}
05-19 16:07:05.911 20200 20200 D BreventServer: foreground service: {}
05-19 16:07:05.911 20200 20200 D BreventServer: gcm: {com.tencent.mm}
05-19 16:07:05.912 20200 20200 D BreventServer: sticky notification: {}
05-19 16:07:05.912 20200 20200 D BreventServer: full power list: {com.android.providers.downloads, com.google.android.gm
s, com.android.deskclock}
05-19 16:07:05.915 20200 20200 D BreventServer: check again in 3600s
05-19 16:07:05.915 20200 20200 D BreventServer: check and brevent, took 217ms
05-19 16:07:06.955 20200 20200 D BreventServer: pause activity, tid: 2719, packageName: me.piebridge.brevent
05-19 16:07:07.068 20200 20200 D BreventServer: com.android.vending: widgets or system
05-19 16:07:09.361 20200 20200 D BreventServer: pause activity, tid: 2466, packageName: me.piebridge.brevent
05-19 16:07:09.365 20200 20200 D BreventServer: resume activity, tid: 26330, packageName: me.piebridge.brevent, launcher
: com.android.launcher3
05-19 16:07:09.432 20200 20200 D BreventServer: checking feelgood
05-19 16:07:09.443 20200 20271 D BreventServer: received feelgood
05-19 16:07:09.568 20200 20200 D BreventServer: pause activity, tid: 30878, packageName: me.piebridge.brevent
05-19 16:07:09.594 20200 20200 D BreventServer: resume activity, tid: 3437, packageName: com.android.launcher3, launcher
: com.android.launcher3
05-19 16:07:11.450 20200 20200 D BreventServer: pause activity, tid: 3389, packageName: com.android.launcher3
05-19 16:07:11.516 20200 20200 D BreventServer: checking feelgood
05-19 16:07:11.517 20200 20271 D BreventServer: received feelgood
05-19 16:07:12.595 20200 20200 D BreventServer: check and brevent
05-19 16:07:12.701 20200 20200 D BreventServer: widgets: {}
05-19 16:07:12.702 20200 20200 D BreventServer: running: {me.piebridge.brevent=142278}
05-19 16:07:12.702 20200 20200 D BreventServer: recent: {me.piebridge.brevent=3599}
05-19 16:07:12.710 20200 20200 D BreventServer: inactive for com.android.vending: 0, timeout: 3600
05-19 16:07:12.710 20200 20200 D BreventServer: inactive for com.android.musicfx: 0, timeout: 3600
05-19 16:07:12.710 20200 20200 D BreventServer: inactive for com.android.smspush: 0, timeout: 3600
05-19 16:07:12.710 20200 20200 D BreventServer: inactive for com.netease.cloudmusic: 0, timeout: 3600
05-19 16:07:12.758 20200 20200 D BreventServer: com.google.android.gms depended by {com.android.vending}
05-19 16:07:12.758 20200 20200 D BreventServer: service: {}
05-19 16:07:12.758 20200 20200 D BreventServer: back(no action): {com.coolapk.market}
05-19 16:07:12.758 20200 20200 D BreventServer: blocking: {com.android.vending, com.android.musicfx, com.android.smspush
, com.netease.cloudmusic}
05-19 16:07:12.762 20200 20200 D BreventServer: top: {me.piebridge.brevent}
05-19 16:07:12.762 20200 20200 D BreventServer: home: {com.android.launcher3, com.android.systemui}
05-19 16:07:12.762 20200 20200 D BreventServer: current: com.android.launcher3
05-19 16:07:12.762 20200 20200 D BreventServer: next: me.piebridge.brevent
05-19 16:07:12.762 20200 20200 D BreventServer: unsafe: {}
05-19 16:07:12.762 20200 20200 D BreventServer: final blocking: {com.android.vending, com.android.musicfx, com.android.s
mspush, com.netease.cloudmusic}
05-19 16:07:12.763 20200 20200 D BreventServer: notifications: {}
05-19 16:07:12.763 20200 20200 D BreventServer: noRecent: {com.android.vending, com.android.musicfx, com.android.smspush
, com.netease.cloudmusic}
05-19 16:07:12.763 20200 20200 D BreventServer: foreground service: {}
05-19 16:07:12.763 20200 20200 D BreventServer: gcm: {com.tencent.mm}
05-19 16:07:12.763 20200 20200 D BreventServer: sticky notification: {}
05-19 16:07:12.764 20200 20200 D BreventServer: full power list: {com.android.providers.downloads, com.google.android.gm
s, com.android.deskclock}
05-19 16:07:12.764 20200 20200 D BreventServer: ignore com.android.vending, wait for the service check
05-19 16:07:12.768 20200 20200 D BreventServer: check again in 3600s
05-19 16:07:12.768 20200 20200 D BreventServer: check and brevent, took 172ms
05-19 16:07:40.096 20200 20200 D BreventServer: check and brevent
05-19 16:07:40.210 20200 20200 D BreventServer: widgets: {}
05-19 16:07:40.210 20200 20200 D BreventServer: running: {me.piebridge.brevent=142279}
05-19 16:07:40.210 20200 20200 D BreventServer: recent: {me.piebridge.brevent=3571}
05-19 16:07:40.220 20200 20200 D BreventServer: inactive for com.android.vending: 0, timeout: 3600
05-19 16:07:40.220 20200 20200 D BreventServer: inactive for com.android.musicfx: 0, timeout: 3600
05-19 16:07:40.220 20200 20200 D BreventServer: inactive for com.android.smspush: 0, timeout: 3600
05-19 16:07:40.220 20200 20200 D BreventServer: inactive for com.netease.cloudmusic: 0, timeout: 3600
05-19 16:07:40.260 20200 20200 D BreventServer: com.google.android.gms depended by {com.android.vending}
05-19 16:07:40.260 20200 20200 D BreventServer: service: {com.android.vending}
05-19 16:07:40.260 20200 20200 D BreventServer: back(no action): {com.coolapk.market}
05-19 16:07:40.260 20200 20200 D BreventServer: blocking: {com.android.vending, com.android.musicfx, com.android.smspush
, com.netease.cloudmusic}
05-19 16:07:40.263 20200 20200 D BreventServer: top: {me.piebridge.brevent}
05-19 16:07:40.263 20200 20200 D BreventServer: home: {com.android.launcher3, com.android.systemui}
05-19 16:07:40.263 20200 20200 D BreventServer: current: com.android.launcher3
05-19 16:07:40.263 20200 20200 D BreventServer: next: me.piebridge.brevent
05-19 16:07:40.263 20200 20200 D BreventServer: unsafe: {}
05-19 16:07:40.263 20200 20200 D BreventServer: final blocking: {com.android.vending, com.android.musicfx, com.android.s
mspush, com.netease.cloudmusic}
05-19 16:07:40.263 20200 20200 D BreventServer: notifications: {}
05-19 16:07:40.263 20200 20200 D BreventServer: noRecent: {com.android.vending, com.android.musicfx, com.android.smspush
, com.netease.cloudmusic}
05-19 16:07:40.263 20200 20200 D BreventServer: foreground service: {}
05-19 16:07:40.263 20200 20200 D BreventServer: gcm: {com.tencent.mm}
05-19 16:07:40.263 20200 20200 D BreventServer: sticky notification: {}
05-19 16:07:40.264 20200 20200 D BreventServer: full power list: {com.android.providers.downloads, com.google.android.gm
s, com.android.deskclock}
05-19 16:07:40.278 20200 20200 D BreventServer: Force stop com.android.vending(service)
05-19 16:07:40.281 20200 20200 D BreventServer: check again in 3600s
05-19 16:07:40.281 20200 20200 D BreventServer: check and brevent, took 183ms

**Comment by liudongmiao** [comment]
根据这份日志，你采取的是只待机不强行停止策略？

最终处理的结果中，至少有网易云音乐，但没有强行停止它。

我需要想想，我是怎么设计的来着，待机模式下，按 Back 退出以后或者从最近列表划掉以后，怎么处理。

**Comment by chm512512** [comment]
嗯，专门留一个网易云做测试的。其他某些APP也会这样。这个是只待机不停止，我试过待机加停止也一样。划掉的APP应该不论那个策略都应该直接停止才比较好呗？！

**Comment by liudongmiao** [comment]
因为很难分辨划掉没有后台，与返回键退出没有后台的区别。

我晚上再去确认下，现在是不是有办法区分了。
确实没有对于这个点进行测试。

**Comment by liudongmiao** [comment]
在我这边，待机加停止，肯定是会被杀掉的。

**Comment by liudongmiao** [comment]
这个功能，我已经忘了最初设计是啥样子了。
好像是强迫症要求，任何时候都待机，包括从最近列表划掉。
所以，如果你想变更设定，在酷安认真问问吧。

就你的需求，我建议使用 待机强行停止，对部分应用使用“允许同步”。
这样，你打开它们时，它们不会被强行停止，直到你划掉它们。
