### ISSUE TITLE
关于黑域的问题

### ISSUE THREAD

**Issue by LLForever** [liudongmiao/Brevent#515]
是这样的，黑域自己把各类系统软件给黑了，看日志好像黑了但是黑域软件上没显示，所以说这怎么解决，有没有办法重置一下黑域的列表？
日志如下
05-19 20:44:06.027 32022 32022 D BreventServer: Force stop com.quark.browser(load brevent)05-19 20:44:06.031 32022 32022 D BreventServer: Force stop com.android.providers.telephony(load brevent)05-19 20:44:06.038 32022 32022 D BreventServer: Force stop org.cyanogenmod.snap(load brevent)05-19 20:44:06.041 32022 32022 D BreventServer: Force stop com.cyanogenmod.pocketmode(load brevent)05-19 20:44:06.046 32022 32022 D BreventServer: Force stop com.qti.service.colorservice(load brevent)05-19 20:44:06.055 32022 32022 D BreventServer: Force stop com.quicinc.cne.CNEService(load brevent)05-19 20:44:06.058 32022 32022 D BreventServer: Force stop com.sinovatech.unicom.ui(load brevent)05-19 20:44:06.066 32022 32022 D BreventServer: Force stop org.lineageos.customtiles(load brevent)05-19 20:44:06.070 32022 32022 D BreventServer: Force stop com.android.mms.service(load brevent)05-19 20:44:06.079 32022 32022 D BreventServer: Force stop com.microsoft.office.excel(load brevent)05-19 20:44:06.081 32022 32022 D BreventServer: Force stop me.ele(load brevent)05-19 20:44:06.084 32022 32022 D BreventServer: Force stop com.cyanogenmod.setupwizard(load brevent)05-19 20:44:06.095 32022 32022 D BreventServer: Force stop com.tencent.mm(load brevent)05-19 20:44:06.099 32022 32022 D BreventServer: Force stop org.codeaurora.bluetooth(load brevent)05-19 20:44:06.102 32022 32022 D BreventServer: Force stop com.qti.qualcomm.datastatusnotification(load brevent)05-19 20:44:06.115 32022 32022 D BreventServer: Force stop android(load brevent)05-19 20:44:06.118 32022 32022 D BreventServer: Force stop cyanogenmod.platform(load brevent)05-19 20:44:06.127 32022 32022 D BreventServer: Force stop com.tencent.token(load brevent)05-19 20:44:06.130 32022 32022 D BreventServer: Force stop com.android.nfc(load brevent)05-19 20:44:06.132 32022 32022 D BreventServer: Force stop com.android.stk(load brevent)05-19 20:44:06.143 32022 32022 D BreventServer: Force stop org.codeaurora.ims(load brevent)05-19 20:44:06.148 32022 32022 D BreventServer: Force stop com.google.android.gm(load brevent)05-19 20:44:06.152 32022 32022 D BreventServer: Force stop com.cyanogenmod.settings.device(load brevent)05-19 20:44:06.154 32022 32022 D BreventServer: Force stop com.qualcomm.qcrilmsgtunnel(load brevent)05-19 20:44:06.162 32022 32022 D BreventServer: Force stop com.android.providers.settings(load brevent)05-19 20:44:06.167 32022 32022 D BreventServer: Force stop com.android.inputdevices(load brevent)05-19 20:44:06.172 32022 32022 D BreventServer: Force stop com.tencent.tim(load brevent)05-19 20:44:06.177 32022 32022 D BreventServer: Force stop com.qti.dpmserviceapp(load brevent)05-19 20:44:06.182 32022 32022 D BreventServer: Force stop com.google.android.apps.plus(load brevent)05-19 20:44:06.184 32022 32022 D BreventServer: Force stop com.microsoft.office.word(load brevent)05-19 20:44:06.195 32022 32022 D BreventServer: Force stop com.microsoft.office.powerpoint(load brevent)05-19 20:44:06.197 32022 32022 D BreventServer: Force stop com.google.android.contacts(load brevent)05-19 20:44:06.204 32022 32022 D BreventServer: Force stop com.ktls.fileinfo(load brevent)05-19 20:44:06.208 32022 32022 D BreventServer: Force stop com.android.server.telecom(load brevent)05-19 20:44:06.214 32022 32022 D BreventServer: Force stop org.cyanogenmod.cmparts(load brevent)05-19 20:44:06.222 32022 32022 D BreventServer: Force stop com.youdao.dict(load brevent)05-19 20:44:06.229 32022 32022 D BreventServer: Force stop com.android.keychain(load brevent)05-19 20:44:06.235 32022 32022 D BreventServer: Force stop org.cyanogenmod.cmsettings(load brevent)05-19 20:44:06.245 32022 32022 D BreventServer: Force stop com.baidu.tieba(load brevent)05-19 20:44:06.249 32022 32022 D BreventServer: Force stop com.dsi.ant.server(load brevent)05-19 20:44:06.257 32022 32022 D BreventServer: Force stop com.google.android.calendar(load brevent)05-19 20:44:06.263 32022 32022 D BreventServer: Force stop com.zhihu.android(load brevent)05-19 20:44:06.267 32022 32022 D BreventServer: Force stop com.coolapk.market(load brevent)05-19 20:44:06.274 32022 32022 D BreventServer: Force stop com.cyanogenmod.settings.doze(load brevent)05-19 20:44:06.278 32022 32022 D BreventServer: Force stop com.android.settings(load brevent)05-19 20:44:06.285 32022 32022 D BreventServer: Force stop com.qualcomm.qti.ims(load brevent)05-19 20:44:06.297 32022 32022 D BreventServer: Force stop com.jingdong.app.mall(load brevent)05-19 20:44:06.306 32022 32022 D BreventServer: Force stop com.cyanogenmod.eleven(load brevent)05-19 20:44:06.309 32022 32022 D BreventServer: Force stop com.xtuone.android.syllabus(load brevent)05-19 20:44:06.315 32022 32022 D BreventServer: Force stop com.android.calculator2(load brevent)05-19 20:44:06.321 32022 32022 D BreventServer: Force stop com.autonavi.minimap(load brevent)05-19 20:44:06.324 32022 32022 D BreventServer: Force stop com.qualcomm.location(load brevent)05-19 20:44:06.331 32022 32022 D BreventServer: Force stop com.qualcomm.qti.tetherservice(load brevent)05-19 20:44:06.336 32022 32022 D BreventServer: Force stop com.google.android.apps.wallpaper(load brevent)05-19 20:44:06.340 32022 32022 D BreventServer: Force stop com.android.phone(load brevent)05-19 20:44:06.348 32022 32022 D BreventServer: Force stop com.android.shell(load brevent)05-19 20:44:06.352 32022 32022 D BreventServer: Force stop com.android.wallpaperbackup(load brevent)05-19 20:44:06.358 32022 32022 D BreventServer: Force stop com.android.location.fused(load brevent)05-19 20:44:06.361 32022 32022 D BreventServer: Force stop com.qualcomm.fastdormancy(load brevent)05-19 20:44:06.363 32022 32022 D BreventServer: Force stop com.taobao.taobao(load brevent)05-19 20:44:06.366 32022 32022 D BreventServer: Force stop com.android.bluetooth(load brevent)05-19 20:44:06.369 32022 32022 D BreventServer: Force stop com.qualcomm.timeservice(load brevent)05-19 20:44:06.376 32022 32022 D BreventServer: Force stop com.android.development(load brevent)05-19 20:44:06.388 32022 32022 D BreventServer: Force stop org.cyanogenmod.weatherservice(load brevent)05-19 20:44:06.391 32022 32022 D BreventServer: Force stop com.netease.cloudmusic(load brevent)05-19 20:44:06.397 32022 32022 D BreventServer: Force stop tv.danmaku.bili(load brevent)05-19 20:44:06.405 32022 32022 D BreventServer: Force stop com.eg.android.AlipayGphone(load brevent)05-19 20:44:06.413 32022 32022 D BreventServer: Force stop cn.dict.android.pro(load brevent)05-19 20:44:06.413 32022 32022 I BreventServer: loading brevent conf05-19 20:44:07.421 32022 32022 D BreventServer: check and brevent05-19 20:44:07.591 32022 32022 D BreventServer: Force stop com.android.vending(noRecent)05-19 20:44:07.602 32022 32022 D BreventServer: Force stop com.google.android.apps.photos(noRecent)05-19 20:44:07.604 32022 32022 D BreventServer: check again in 3600s05-19 20:44:07.604 32022 32022 D BreventServer: check and brevent, took 182ms05-19 20:44:07.605 32022 32022 D BreventServer: check and brevent05-19 20:44:07.737 32022 32022 D BreventServer: Force stop com.android.vending(previous running)05-19 20:44:07.745 32022 32022 D BreventServer: Force stop com.google.android.apps.photos(previous running)05-19 20:44:07.748 32022 32022 D BreventServer: check again in 3600s05-19 20:44:07.748 32022 32022 D BreventServer: check and brevent, took 142ms05-19 20:44:07.776 32022 32022 D BreventServer: sent first status05-19 20:44:18.230 32022 32022 D BreventServer: check and brevent05-19 20:44:18.458 32022 32022 D BreventServer: Force stop com.android.vending(service)05-19 20:44:18.460 32022 32022 D BreventServer: check again in 3600s05-19 20:44:18.460 32022 32022 D BreventServer: check and brevent, took 227ms05-19 20:44:36.874 32022 32022 D BreventServer: check and brevent05-19 20:44:37.028 32022 32022 D BreventServer: Force stop com.android.vending(previous running)05-19 20:44:37.030 32022 32022 D BreventServer: check again in 3600s05-19 20:44:37.030 32022 32022 D BreventServer: check and brevent, took 154ms05-19 20:44:37.066 32022 32022 D BreventServer: checking feelgood05-19 20:44:37.067 32022 32031 D BreventServer: received feelgood

**Comment by LLForever** [comment]
PS   版本号1.1.8

**Comment by liudongmiao** [comment]
这确实是一个问题。

请看下这个版本是否还存在这个问题：https://piebridge.me/br/next/

**Comment by liudongmiao** [comment]
请确认 1.1.9 是否修复。

如果已经有，请发送邮件至我邮箱（黑域内反馈），我好给你特别优惠。

**Comment by LLForever** [comment]
我已经在测试中  将尽快给出结婚

**Comment by LLForever** [comment]
抱歉   是结果   手误

**Comment by LLForever** [comment]
根据目前的日志中，并未发现有关闭安卓内部架构和软件的情况，感谢作者！！！
