### ISSUE TITLE
SELinux日志

### ISSUE THREAD

**Issue by vvb2060** [liudongmiao/Brevent#516]
<36>[10566.345929] type=1400 audit(1495200716.240:314): avc: denied { use } for pid=15065 comm="main" path="/data/user_de/0/com.android.shell/dumpsys1277643552appwidget" dev="mmcblk0p44" ino=1688478 scontext=u:r:system_server:s0 tcontext=u:r:su:s0 tclass=fd permissive=0
<36>[10566.348797] type=1400 audit(1495200716.243:315): avc: denied { use } for pid=15065 comm="main" path="/data/user_de/0/com.android.shell/dumpsys744470481activity" dev="mmcblk0p44" ino=1688501 scontext=u:r:system_server:s0 tcontext=u:r:su:s0 tclass=fd permissive=0
nexus 6p 7.1.2原生系统 magisksu

**Comment by liudongmiao** [comment]
https://piebridge.me/br/next/ 然后给新的日志

**Comment by liudongmiao** [comment]
这个做了一个 fallback，之前的话，家目录使用 /data/user_de/0/com.android.shell/ 这也是 shell 的家目录。

现在的话，如果这个目录不可写，改为写 /sdcard/brevent，如果这个目录也不可写，就直接退出。

**Comment by vvb2060** [comment]
<36>[12753.078027] type=1400 audit(1495202902.973:334): avc: denied { use } for pid=21750 comm="main" path="/data/user_de/0/com.android.shell/dumpsys424951354appwidget" dev="mmcblk0p44" ino=1688529 scontext=u:r:system_server:s0 tcontext=u:r:su:s0 tclass=fd permissive=0
<36>[12753.080320] type=1400 audit(1495202902.977:335): avc: denied { use } for pid=21750 comm="main" path="/data/user_de/0/com.android.shell/dumpsys1498664387activity" dev="mmcblk0p44" ino=1688530 scontext=u:r:system_server:s0 tcontext=u:r:su:s0 tclass=fd permissive=0
1.1.8-1.g5cf 完全一样的日志。（话说 /sdcard/brevent不申请权限能写吗？

**Comment by liudongmiao** [comment]
接着看这个版本吧：https://piebridge.me/br/next/

**Comment by liudongmiao** [comment]
先等等

**Comment by liudongmiao** [comment]
好了，去测试吧。

**Comment by vvb2060** [comment]
angler:/ $ su
angler:/ # cat /proc/kmsg | grep denied
<36>[  315.348642] type=1400 audit(1495259154.985:43): avc: denied { use }
for pid=12228 comm="main" path="pipe:[101038]" dev="pipefs" ino=101038
scontext=u:r:system_server:s0 tcontext=u:r:su:s0 tclass=fd permissive=0
<36>[  315.384854] type=1400 audit(1495259155.021:45): avc: denied { use }
for pid=12228 comm="main" path="pipe:[102942]" dev="pipefs" ino=102942
scontext=u:r:system_server:s0 tcontext=u:r:su:s0 tclass=fd permissive=0

Liu DongMiao <notifications@github.com>于2017年5月20日周六 下午12:37写道：

**Comment by liudongmiao** [comment]
那就没办法了…

文件不行，pipe 也不让…

你要继续测试的话，得提供 teamviewer 账号与密码。不和你挤牙膏，慢慢测试了。

**Comment by liudongmiao** [comment]
系统上 dumpsys 也无法使用，等 dumpsys 可以正常使用的时候，再重开吧。

**Comment by vvb2060** [comment]
用1.1.8-1版输入 sepolicy-inject --live "allow system_server su fd use"可以用root开启

Liu DongMiao <notifications@github.com>于2017年5月20日周六 下午6:08写道：

**Comment by liudongmiao** [comment]
等什么时候  dumpsys 可用了，再说吧。

否则，不可能正常工作的，即使开启了也不会正常工作。
