### ISSUE TITLE
QQ接收消息无振动提示

### ISSUE THREAD

**Issue by mmemi** [liudongmiao/Brevent#517]
QQ收消息应该是收到了但开了振动提示没反应，时间一长QQ通知栏图标消失，后台可能也被终止了！微信时间长了后也是基本假死状态！对了，都没有黑域它们。
05-20 00:53:39.041   329   329 D BreventServer: check and brevent
05-20 00:53:39.091   329   329 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, cn.etouch.ecalendar, com.Kingdee.Express, com.samsung.android.snote, com.baidu.searchbox_samsung}
05-20 00:53:39.091   329   329 D BreventServer: running: {com.tencent.mm=90947, com.tencent.mobileqq=90399}
05-20 00:53:39.091   329   329 D BreventServer: recent: {com.tencent.mm=3590, me.piebridge.brevent=2963, com.tencent.mobileqq=3042}
05-20 00:53:39.251   329   329 D BreventServer: service: {}
05-20 00:53:39.251   329   329 D BreventServer: back: {}
05-20 00:53:39.251   329   329 D BreventServer: blocking: {}
05-20 00:53:39.251   329   329 D BreventServer: top: {com.tencent.mm}
05-20 00:53:39.251   329   329 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-20 00:53:39.251   329   329 D BreventServer: current: com.tencent.mm
05-20 00:53:39.251   329   329 D BreventServer: next: com.tencent.mobileqq
05-20 00:53:39.251   329   329 D BreventServer: unsafe: {}
05-20 00:53:39.251   329   329 D BreventServer: final blocking: {}
05-20 00:53:39.251   329   329 D BreventServer: notifications: {}
05-20 00:53:39.251   329   329 D BreventServer: noRecent: {}
05-20 00:53:39.251   329   329 D BreventServer: foreground service: {}
05-20 00:53:39.251   329   329 D BreventServer: sticky notification: {}
05-20 00:53:39.251   329   329 D BreventServer: check again in 3600s
05-20 00:53:39.251   329   329 D BreventServer: check and brevent, took 204ms
05-20 00:54:12.871   329   329 D BreventServer: resume activity, tid: 4678, packageName: com.tencent.mm, launcher: com.sec.android.app.launcher
05-20 00:54:19.491   329   329 D BreventServer: check and brevent
05-20 00:54:19.511   329   329 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, cn.etouch.ecalendar, com.Kingdee.Express, com.samsung.android.snote, com.baidu.searchbox_samsung}
05-20 00:54:19.511   329   329 D BreventServer: running: {com.tencent.mm=90994, com.tencent.mobileqq=90400}
05-20 00:54:19.511   329   329 D BreventServer: recent: {com.tencent.mm=3597, me.piebridge.brevent=2923, com.tencent.mobileqq=3002}
05-20 00:54:19.561   329   329 D BreventServer: service: {}
05-20 00:54:19.561   329   329 D BreventServer: back: {}
05-20 00:54:19.561   329   329 D BreventServer: blocking: {}
05-20 00:54:19.561   329   329 D BreventServer: top: {com.tencent.mm}
05-20 00:54:19.561   329   329 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-20 00:54:19.561   329   329 D BreventServer: current: com.tencent.mm
05-20 00:54:19.561   329   329 D BreventServer: next: com.tencent.mobileqq
05-20 00:54:19.561   329   329 D BreventServer: unsafe: {}
05-20 00:54:19.561   329   329 D BreventServer: final blocking: {}
05-20 00:54:19.561   329   329 D BreventServer: notifications: {}
05-20 00:54:19.561   329   329 D BreventServer: noRecent: {}
05-20 00:54:19.561   329   329 D BreventServer: foreground service: {}
05-20 00:54:19.561   329   329 D BreventServer: sticky notification: {}
05-20 00:54:19.561   329   329 D BreventServer: check again in 3600s
05-20 00:54:19.561   329   329 D BreventServer: check and brevent, took 75ms
05-20 00:54:19.751   329   329 D BreventServer: pause activity, tid: 5135, packageName: com.tencent.mm
05-20 00:54:19.771   329   329 D BreventServer: resume activity, tid: 4778, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher
05-20 00:54:21.251   329   329 D BreventServer: pause activity, tid: 5058, packageName: com.sec.android.app.launcher
05-20 00:54:21.261   329   329 D BreventServer: resume activity, tid: 5136, packageName: com.tencent.mobileqq, launcher: com.sec.android.app.launcher
05-20 00:54:22.771   329   329 D BreventServer: check and brevent
05-20 00:54:22.811   329   329 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, cn.etouch.ecalendar, com.Kingdee.Express, com.samsung.android.snote, com.baidu.searchbox_samsung}
05-20 00:54:22.811   329   329 D BreventServer: running: {com.tencent.mm=90997, com.tencent.mobileqq=90999}
05-20 00:54:22.811   329   329 D BreventServer: recent: {com.tencent.mm=3597, me.piebridge.brevent=2920, com.tencent.mobileqq=3599}
05-20 00:54:22.971   329   329 D BreventServer: service: {}
05-20 00:54:22.971   329   329 D BreventServer: back: {}
05-20 00:54:22.971   329   329 D BreventServer: blocking: {}
05-20 00:54:22.971   329   329 D BreventServer: top: {com.tencent.mobileqq}
05-20 00:54:22.971   329   329 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-20 00:54:22.971   329   329 D BreventServer: current: com.tencent.mobileqq
05-20 00:54:22.971   329   329 D BreventServer: next: com.tencent.mobileqq
05-20 00:54:22.971   329   329 D BreventServer: unsafe: {}
05-20 00:54:22.971   329   329 D BreventServer: final blocking: {}
05-20 00:54:22.971   329   329 D BreventServer: notifications: {}
05-20 00:54:22.971   329   329 D BreventServer: noRecent: {}
05-20 00:54:22.971   329   329 D BreventServer: foreground service: {}
05-20 00:54:22.971   329   329 D BreventServer: sticky notification: {}
05-20 00:54:22.971   329   329 D BreventServer: check again in 3600s
05-20 00:54:22.971   329   329 D BreventServer: check and brevent, took 196ms
05-20 00:54:24.001   329   329 D BreventServer: pause activity, tid: 10149, packageName: com.tencent.mobileqq
05-20 00:54:24.021   329   329 D BreventServer: resume activity, tid: 10008, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher
05-20 00:54:25.281   329   329 D BreventServer: pause activity, tid: 5058, packageName: com.sec.android.app.launcher
05-20 00:54:25.291   329   329 D BreventServer: resume activity, tid: 4683, packageName: com.tencent.mobileqq, launcher: com.sec.android.app.launcher
05-20 00:54:26.181   329   329 D BreventServer: pause activity, tid: 4778, packageName: com.tencent.mobileqq
05-20 00:54:27.021   329   329 D BreventServer: check and brevent
05-20 00:54:27.101   329   329 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, cn.etouch.ecalendar, com.Kingdee.Express, com.samsung.android.snote, com.baidu.searchbox_samsung}
05-20 00:54:27.101   329   329 D BreventServer: running: {com.tencent.mm=90997, com.tencent.mobileqq=91004}
05-20 00:54:27.101   329   329 D BreventServer: recent: {com.tencent.mm=3592, me.piebridge.brevent=2915, com.tencent.mobileqq=3599}
05-20 00:54:27.161   329   329 D BreventServer: service: {}
05-20 00:54:27.161   329   329 D BreventServer: back: {}
05-20 00:54:27.161   329   329 D BreventServer: blocking: {}
05-20 00:54:27.161   329   329 D BreventServer: top: {com.tencent.mobileqq}
05-20 00:54:27.161   329   329 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-20 00:54:27.161   329   329 D BreventServer: current: com.tencent.mobileqq
05-20 00:54:27.161   329   329 D BreventServer: next: com.tencent.mobileqq
05-20 00:54:27.161   329   329 D BreventServer: unsafe: {}
05-20 00:54:27.161   329   329 D BreventServer: final blocking: {}
05-20 00:54:27.161   329   329 D BreventServer: notifications: {}
05-20 00:54:27.161   329   329 D BreventServer: noRecent: {}
05-20 00:54:27.161   329   329 D BreventServer: foreground service: {}
05-20 00:54:27.161   329   329 D BreventServer: sticky notification: {}
05-20 00:54:27.161   329   329 D BreventServer: check again in 3600s
05-20 00:54:27.161   329   329 D BreventServer: check and brevent, took 132ms
05-20 00:54:27.981   329   329 D BreventServer: pause activity, tid: 5135, packageName: com.tencent.mobileqq
05-20 00:54:28.061   329   329 D BreventServer: resume activity, tid: 5136, packageName: com.tencent.mobileqq, launcher: com.sec.android.app.launcher
05-20 00:54:29.191   329   329 D BreventServer: pause activity, tid: 4777, packageName: com.tencent.mobileqq
05-20 00:54:29.851   329   329 D BreventServer: pause activity, tid: 10149, packageName: com.tencent.mobileqq
05-20 00:54:29.861   329   329 D BreventServer: resume activity, tid: 10146, packageName: com.tencent.mobileqq, launcher: com.sec.android.app.launcher
05-20 00:54:31.491   329   329 D BreventServer: pause activity, tid: 3679, packageName: com.tencent.mobileqq
05-20 00:54:31.501   329   329 D BreventServer: resume activity, tid: 5135, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher
05-20 00:54:32.541   329   329 D BreventServer: pause activity, tid: 10153, packageName: com.sec.android.app.launcher
05-20 00:54:32.551   329   329 D BreventServer: resume activity, tid: 4678, packageName: com.tencent.mobileqq, launcher: com.sec.android.app.launcher
05-20 00:54:34.051   329   329 D BreventServer: pause activity, tid: 10153, packageName: com.tencent.mobileqq
05-20 00:54:34.501   329   329 D BreventServer: check and brevent
05-20 00:54:34.521   329   329 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, cn.etouch.ecalendar, com.Kingdee.Express, com.samsung.android.snote, com.baidu.searchbox_samsung}
05-20 00:54:34.521   329   329 D BreventServer: running: {com.tencent.mm=90998, com.tencent.mobileqq=91012}
05-20 00:54:34.521   329   329 D BreventServer: recent: {com.tencent.mm=3585, me.piebridge.brevent=2908, com.tencent.mobileqq=3600}
05-20 00:54:34.551   329   329 D BreventServer: service: {}
05-20 00:54:34.551   329   329 D BreventServer: back: {}
05-20 00:54:34.551   329   329 D BreventServer: blocking: {}
05-20 00:54:34.551   329   329 D BreventServer: top: {com.tencent.mobileqq}
05-20 00:54:34.551   329   329 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-20 00:54:34.551   329   329 D BreventServer: current: com.tencent.mobileqq
05-20 00:54:34.551   329   329 D BreventServer: next: com.tencent.mobileqq
05-20 00:54:34.551   329   329 D BreventServer: unsafe: {}
05-20 00:54:34.551   329   329 D BreventServer: final blocking: {}
05-20 00:54:34.551   329   329 D BreventServer: notifications: {}
05-20 00:54:34.551   329   329 D BreventServer: noRecent: {}
05-20 00:54:34.551   329   329 D BreventServer: foreground service: {}
05-20 00:54:34.551   329   329 D BreventServer: sticky notification: {}
05-20 00:54:34.551   329   329 D BreventServer: check again in 3600s
05-20 00:54:34.551   329   329 D BreventServer: check and brevent, took 48ms
05-20 00:54:34.751   329   329 D BreventServer: pause activity, tid: 10149, packageName: com.tencent.mobileqq
05-20 00:54:37.621   329   329 D BreventServer: pause activity, tid: 10008, packageName: com.tencent.mobileqq
05-20 00:54:37.631   329   329 D BreventServer: resume activity, tid: 4683, packageName: com.tencent.mobileqq, launcher: com.sec.android.app.launcher
05-20 00:54:37.851   329   329 D BreventServer: pause activity, tid: 5058, packageName: com.tencent.mobileqq
05-20 00:54:37.861   329   329 D BreventServer: resume activity, tid: 5135, packageName: com.tencent.mobileqq, launcher: com.sec.android.app.launcher
05-20 00:54:38.831   329   329 D BreventServer: pause activity, tid: 4973, packageName: com.tencent.mobileqq
05-20 00:54:38.861   329   329 D BreventServer: resume activity, tid: 10153, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher
05-20 00:54:40.271   329   329 D BreventServer: pause activity, tid: 4973, packageName: com.sec.android.app.launcher
05-20 00:54:40.291   329   329 D BreventServer: resume activity, tid: 5135, packageName: com.tencent.mobileqq, launcher: com.sec.android.app.launcher
05-20 00:54:41.861   329   329 D BreventServer: check and brevent
05-20 00:54:41.931   329   329 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, cn.etouch.ecalendar, com.Kingdee.Express, com.samsung.android.snote, com.baidu.searchbox_samsung}
05-20 00:54:41.931   329   329 D BreventServer: running: {com.tencent.mm=90997, com.tencent.mobileqq=91018}
05-20 00:54:41.931   329   329 D BreventServer: recent: {com.tencent.mm=3578, me.piebridge.brevent=2901, com.tencent.mobileqq=3600}
05-20 00:54:42.011   329   329 D BreventServer: service: {}
05-20 00:54:42.011   329   329 D BreventServer: back: {}
05-20 00:54:42.011   329   329 D BreventServer: blocking: {}
05-20 00:54:42.011   329   329 D BreventServer: top: {com.tencent.mobileqq}
05-20 00:54:42.011   329   329 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-20 00:54:42.011   329   329 D BreventServer: current: com.tencent.mobileqq
05-20 00:54:42.011   329   329 D BreventServer: next: com.tencent.mobileqq
05-20 00:54:42.011   329   329 D BreventServer: unsafe: {}
05-20 00:54:42.011   329   329 D BreventServer: final blocking: {}
05-20 00:54:42.011   329   329 D BreventServer: notifications: {}
05-20 00:54:42.011   329   329 D BreventServer: noRecent: {}
05-20 00:54:42.011   329   329 D BreventServer: foreground service: {}
05-20 00:54:42.011   329   329 D BreventServer: sticky notification: {}
05-20 00:54:42.011   329   329 D BreventServer: check again in 3600s
05-20 00:54:42.011   329   329 D BreventServer: check and brevent, took 157ms
05-20 00:54:42.011   329   329 D BreventServer: pause activity, tid: 4777, packageName: com.tencent.mobileqq
05-20 00:54:42.011   329   329 D BreventServer: resume activity, tid: 10153, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher
05-20 00:54:45.021   329   329 D BreventServer: check and brevent
05-20 00:54:45.031   329   329 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, cn.etouch.ecalendar, com.Kingdee.Express, com.samsung.android.snote, com.baidu.searchbox_samsung}
05-20 00:54:45.031   329   329 D BreventServer: running: {com.tencent.mm=90997, com.tencent.mobileqq=91019}
05-20 00:54:45.031   329   329 D BreventServer: recent: {com.tencent.mm=3574, me.piebridge.brevent=2897, com.tencent.mobileqq=3596}
05-20 00:54:45.071   329   329 D BreventServer: service: {}
05-20 00:54:45.071   329   329 D BreventServer: back: {}
05-20 00:54:45.071   329   329 D BreventServer: blocking: {}
05-20 00:54:45.071   329   329 D BreventServer: top: {}
05-20 00:54:45.071   329   329 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-20 00:54:45.071   329   329 D BreventServer: current: com.sec.android.app.launcher
05-20 00:54:45.071   329   329 D BreventServer: next: com.tencent.mobileqq
05-20 00:54:45.071   329   329 D BreventServer: unsafe: {}
05-20 00:54:45.071   329   329 D BreventServer: final blocking: {}
05-20 00:54:45.071   329   329 D BreventServer: notifications: {}
05-20 00:54:45.071   329   329 D BreventServer: noRecent: {}
05-20 00:54:45.071   329   329 D BreventServer: foreground service: {}
05-20 00:54:45.071   329   329 D BreventServer: sticky notification: {}
05-20 00:54:45.071   329   329 D BreventServer: check again in 3600s
05-20 00:54:45.071   329   329 D BreventServer: check and brevent, took 54ms
05-20 00:54:45.081   329   329 D BreventServer: pause activity, tid: 4586, packageName: com.sec.android.app.launcher
05-20 00:54:47.491   329   329 D BreventServer: check and brevent
05-20 00:54:47.541   329   329 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, cn.etouch.ecalendar, com.Kingdee.Express, com.samsung.android.snote, com.baidu.searchbox_samsung}
05-20 00:54:47.541   329   329 D BreventServer: running: {com.tencent.mm=90998, com.tencent.mobileqq=91020}
05-20 00:54:47.541   329   329 D BreventServer: recent: {com.tencent.mm=3572, me.piebridge.brevent=2895, com.tencent.mobileqq=3594}
05-20 00:54:47.721   329   329 D BreventServer: service: {}
05-20 00:54:47.721   329   329 D BreventServer: back: {}
05-20 00:54:47.721   329   329 D BreventServer: blocking: {}
05-20 00:54:47.721   329   329 D BreventServer: top: {}
05-20 00:54:47.721   329   329 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-20 00:54:47.721   329   329 D BreventServer: current: com.sec.android.app.launcher
05-20 00:54:47.721   329   329 D BreventServer: next: com.tencent.mobileqq
05-20 00:54:47.721   329   329 D BreventServer: unsafe: {}
05-20 00:54:47.721   329   329 D BreventServer: final blocking: {}
05-20 00:54:47.721   329   329 D BreventServer: notifications: {}
05-20 00:54:47.721   329   329 D BreventServer: noRecent: {}
05-20 00:54:47.721   329   329 D BreventServer: foreground service: {}
05-20 00:54:47.721   329   329 D BreventServer: sticky notification: {}
05-20 00:54:47.721   329   329 D BreventServer: check again in 3600s
05-20 00:54:47.721   329   329 D BreventServer: check and brevent, took 229ms
05-20 00:54:54.981   329   329 D BreventServer: resume activity, tid: 10149, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher
05-20 00:54:56.881   329   329 D BreventServer: pause activity, tid: 3680, packageName: com.sec.android.app.launcher
05-20 00:54:57.171   329   329 D BreventServer: checking feelgood
05-20 00:54:57.171   329   341 D BreventServer: received feelgood
05-20 00:54:58.221   329   329 D BreventServer: check and brevent
05-20 00:54:58.241   329   329 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, cn.etouch.ecalendar, com.Kingdee.Express, com.samsung.android.snote, com.baidu.searchbox_samsung}
05-20 00:54:58.241   329   329 D BreventServer: running: {com.tencent.mm=90998, me.piebridge.brevent=91035, com.tencent.mobileqq=91020}
05-20 00:54:58.241   329   329 D BreventServer: recent: {com.tencent.mm=3561, me.piebridge.brevent=3598, com.tencent.mobileqq=3583}
05-20 00:54:58.341   329   329 D BreventServer: service: {}
05-20 00:54:58.341   329   329 D BreventServer: back: {}
05-20 00:54:58.341   329   329 D BreventServer: blocking: {}
05-20 00:54:58.341   329   329 D BreventServer: top: {me.piebridge.brevent}
05-20 00:54:58.341   329   329 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-20 00:54:58.341   329   329 D BreventServer: current: com.sec.android.app.launcher
05-20 00:54:58.341   329   329 D BreventServer: next: com.tencent.mobileqq
05-20 00:54:58.341   329   329 D BreventServer: unsafe: {}
05-20 00:54:58.341   329   329 D BreventServer: final blocking: {}
05-20 00:54:58.341   329   329 D BreventServer: notifications: {}
05-20 00:54:58.341   329   329 D BreventServer: noRecent: {}
05-20 00:54:58.341   329   329 D BreventServer: foreground service: {}
05-20 00:54:58.341   329   329 D BreventServer: sticky notification: {}
05-20 00:54:58.341   329   329 D BreventServer: check again in 3600s
05-20 00:54:58.341   329   329 D BreventServer: check and brevent, took 119ms
05-20 00:54:59.221   329   329 D BreventServer: pause activity, tid: 9938, packageName: me.piebridge.brevent
05-20 00:54:59.221   329   329 D BreventServer: resume activity, tid: 10153, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher
05-20 00:55:01.031   329   329 D BreventServer: pause activity, tid: 4586, packageName: com.sec.android.app.launcher
05-20 00:55:03.491   329   329 D BreventServer: check and brevent
05-20 00:55:03.521   329   329 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, cn.etouch.ecalendar, com.Kingdee.Express, com.samsung.android.snote, com.baidu.searchbox_samsung}
05-20 00:55:03.521   329   329 D BreventServer: running: {com.tencent.mm=90998, com.tencent.mobileqq=91020}
05-20 00:55:03.521   329   329 D BreventServer: recent: {com.tencent.mm=3556, me.piebridge.brevent=3596, com.tencent.mobileqq=3578}
05-20 00:55:03.591   329   329 D BreventServer: service: {}
05-20 00:55:03.591   329   329 D BreventServer: back: {}
05-20 00:55:03.591   329   329 D BreventServer: blocking: {}
05-20 00:55:03.591   329   329 D BreventServer: top: {}
05-20 00:55:03.591   329   329 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-20 00:55:03.591   329   329 D BreventServer: current: com.sec.android.app.launcher
05-20 00:55:03.591   329   329 D BreventServer: next: com.tencent.mobileqq
05-20 00:55:03.591   329   329 D BreventServer: unsafe: {}
05-20 00:55:03.591   329   329 D BreventServer: final blocking: {}
05-20 00:55:03.591   329   329 D BreventServer: notifications: {}
05-20 00:55:03.591   329   329 D BreventServer: noRecent: {}
05-20 00:55:03.591   329   329 D BreventServer: foreground service: {}
05-20 00:55:03.591   329   329 D BreventServer: sticky notification: {}
05-20 00:55:03.591   329   329 D BreventServer: check again in 3600s
05-20 00:55:03.591   329   329 D BreventServer: check and brevent, took 96ms

**Comment by mmemi** [comment]
br-v1.1.8+2.apk显示正在获取进程，电脑命令后也无法进入

**Comment by liudongmiao** [comment]
黑域从不干扰别的应用组件，不对此负责。

任何时候，你都可以不黑域它。

**Comment by mmemi** [comment]
装这软件后QQ微信根本没黑域，接收信息始终会延迟五分钟左右或者只能打开软件界面后才收信息，肯定哪里有问题！很想用这神器，无耐只能卸载！希望能早日找到原因修复！

**Comment by liudongmiao** [comment]
这真的与黑域无关。你可以这样以接收信息：

1. 对 QQ / 微信 电池未优化
2. 对 QQ / 微信 允许后台数据
