### ISSUE TITLE
Website for it

### ISSUE THREAD

**Issue by Zero3K** [liudongmiao/Brevent#518]
One should be made so more people can learn of it and how to use it properly, etc.

**Comment by liudongmiao** [comment]
https://piebridge.me/br/

And there is a chinese guide in pdf: https://piebridge.me/br/br.pdf
I have no plan to write it in english.

**Comment by Zero3K** [comment]
It could still be made nicer looking. That or add a README that explains how to use it and includes screenshots of it.
