### ISSUE TITLE
cannot listen port，6.0 没有 getRecentTasks(III)Landroid/content/pm/ParceledListSlice

### ISSUE THREAD

**Issue by idongyou** [liudongmiao/Brevent#52]
checking.............

cannot listen port, please report bug

--- crash start ---

01-02 07:17:35.266   630   630 F libc    : page record for 0xf758802c was not found (block_size=16)

02-17 12:19:36.564  8649  8664 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11

02-17 12:19:36.564  8649  8664 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

02-17 12:19:36.564  8649  8664 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)

02-17 12:19:36.564  8649  8664 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

02-17 12:19:36.564  8649  8664 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException

02-17 12:19:36.564  8649  8664 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

02-17 12:19:36.564  8649  8664 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)

02-17 12:19:36.564  8649  8664 E AndroidRuntime: 	... 1 more

02-17 12:19:36.564  8649  8664 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method getRecentTasks(III)Landroid/content/pm/ParceledListSlice; in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)

02-17 12:19:36.564  8649  8664 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:316)

02-17 12:19:36.564  8649  8664 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:221)

02-17 12:19:36.564  8649  8664 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:133)

02-17 12:19:36.564  8649  8664 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:808)

02-17 12:19:36.564  8649  8664 E AndroidRuntime: 	... 3 more

02-17 12:19:36.572  8649  8664 E AndroidRuntime: Error reporting crash

02-17 12:19:36.572  8649  8664 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor

02-17 12:19:36.572  8649  8664 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)

02-17 12:19:36.572  8649  8664 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)

02-17 12:19:36.572  8649  8664 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4429)

02-17 12:19:36.572  8649  8664 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:145)

02-17 12:19:36.572  8649  8664 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)

02-17 12:19:36.572  8649  8664 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

02-17 12:20:25.593  8759  8774 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11

02-17 12:20:25.593  8759  8774 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

02-17 12:20:25.593  8759  8774 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)

02-17 12:20:25.593  8759  8774 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

02-17 12:20:25.593  8759  8774 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException

02-17 12:20:25.593  8759  8774 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

02-17 12:20:25.593  8759  8774 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)

02-17 12:20:25.593  8759  8774 E AndroidRuntime: 	... 1 more

02-17 12:20:25.593  8759  8774 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method getRecentTasks(III)Landroid/content/pm/ParceledListSlice; in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)

02-17 12:20:25.593  8759  8774 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:316)

02-17 12:20:25.593  8759  8774 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:221)

02-17 12:20:25.593  8759  8774 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:133)

02-17 12:20:25.593  8759  8774 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:808)

02-17 12:20:25.593  8759  8774 E AndroidRuntime: 	... 3 more

02-17 12:20:25.598  8759  8774 E AndroidRuntime: Error reporting crash

02-17 12:20:25.598  8759  8774 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor

02-17 12:20:25.598  8759  8774 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)

02-17 12:20:25.598  8759  8774 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)

02-17 12:20:25.598  8759  8774 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4429)

02-17 12:20:25.598  8759  8774 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:145)

02-17 12:20:25.598  8759  8774 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)

02-17 12:20:25.598  8759  8774 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

02-17 12:22:53.782  8924  8939 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11

02-17 12:22:53.782  8924  8939 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

02-17 12:22:53.782  8924  8939 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)

02-17 12:22:53.782  8924  8939 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

02-17 12:22:53.782  8924  8939 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException

02-17 12:22:53.782  8924  8939 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

02-17 12:22:53.782  8924  8939 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)

02-17 12:22:53.782  8924  8939 E AndroidRuntime: 	... 1 more

02-17 12:22:53.782  8924  8939 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method getRecentTasks(III)Landroid/content/pm/ParceledListSlice; in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)

02-17 12:22:53.782  8924  8939 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:316)

02-17 12:22:53.782  8924  8939 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:221)

02-17 12:22:53.782  8924  8939 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:133)

02-17 12:22:53.782  8924  8939 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:808)

02-17 12:22:53.782  8924  8939 E AndroidRuntime: 	... 3 more

02-17 12:22:53.786  8924  8939 E AndroidRuntime: Error reporting crash

02-17 12:22:53.786  8924  8939 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor

02-17 12:22:53.786  8924  8939 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)

02-17 12:22:53.786  8924  8939 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)

02-17 12:22:53.786  8924  8939 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4429)

02-17 12:22:53.786  8924  8939 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:145)

02-17 12:22:53.786  8924  8939 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)

02-17 12:22:53.786  8924  8939 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

--- crash end ---

--- brevent start ---

02-17 12:19:36.310  8649  8649 D BreventLoader: lib: /data/user/0/com.android.shell/lib, loader: /data/user/0/com.android.shell/lib/libloader.so

02-17 12:19:36.383  8649  8664 D BreventServer: Brevent Server 0.5-beta2 started

02-17 12:19:36.398  8649  8664 D BreventServer: brevent data directory: /data/user/0/com.android.shell

02-17 12:19:36.563  8649  8664 D BreventLoader: Can't run brevent server

02-17 12:19:36.563  8649  8664 D BreventLoader: java.lang.reflect.InvocationTargetException

02-17 12:19:36.563  8649  8664 D BreventLoader: 	at java.lang.reflect.Method.invoke(Native Method)

02-17 12:19:36.563  8649  8664 D BreventLoader: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)

02-17 12:19:36.563  8649  8664 D BreventLoader: 	at java.lang.Thread.run(Thread.java:818)

02-17 12:19:36.563  8649  8664 D BreventLoader: Caused by: java.lang.NoSuchMethodError: No interface method getRecentTasks(III)Landroid/content/pm/ParceledListSlice; in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)

02-17 12:19:36.563  8649  8664 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:316)

02-17 12:19:36.563  8649  8664 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:221)

02-17 12:19:36.563  8649  8664 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:133)

02-17 12:19:36.563  8649  8664 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:808)

02-17 12:19:36.563  8649  8664 D BreventLoader: 	... 3 more

02-17 12:19:36.564  8649  8649 D BreventLoader: Brevent Server quit in 30 seconds, quit

02-17 12:19:36.564  8649  8649 D BreventLoader: Can't remove /data/user/0/com.android.shell/lib

02-17 12:20:25.251  8759  8759 D BreventLoader: lib: /data/user/0/com.android.shell/lib, loader: /data/user/0/com.android.shell/lib/libloader.so

02-17 12:20:25.340  8759  8774 D BreventServer: Brevent Server 0.5-beta2 started

02-17 12:20:25.350  8759  8774 D BreventServer: brevent data directory: /data/user/0/com.android.shell

02-17 12:20:25.592  8759  8774 D BreventLoader: Can't run brevent server

02-17 12:20:25.592  8759  8774 D BreventLoader: java.lang.reflect.InvocationTargetException

02-17 12:20:25.592  8759  8774 D BreventLoader: 	at java.lang.reflect.Method.invoke(Native Method)

02-17 12:20:25.592  8759  8774 D BreventLoader: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)

02-17 12:20:25.592  8759  8774 D BreventLoader: 	at java.lang.Thread.run(Thread.java:818)

02-17 12:20:25.592  8759  8774 D BreventLoader: Caused by: java.lang.NoSuchMethodError: No interface method getRecentTasks(III)Landroid/content/pm/ParceledListSlice; in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)

02-17 12:20:25.592  8759  8774 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:316)

02-17 12:20:25.592  8759  8774 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:221)

02-17 12:20:25.592  8759  8774 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:133)

02-17 12:20:25.592  8759  8774 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:808)

02-17 12:20:25.592  8759  8774 D BreventLoader: 	... 3 more

02-17 12:20:25.593  8759  8759 D BreventLoader: Brevent Server quit in 30 seconds, quit

02-17 12:20:25.593  8759  8759 D BreventLoader: Can't remove /data/user/0/com.android.shell/lib

02-17 12:22:53.509  8924  8924 D BreventLoader: lib: /data/user/0/com.android.shell/lib, loader: /data/user/0/com.android.shell/lib/libloader.so

02-17 12:22:53.579  8924  8939 D BreventServer: Brevent Server 0.5-beta2 started

02-17 12:22:53.588  8924  8939 D BreventServer: brevent data directory: /data/user/0/com.android.shell

02-17 12:22:53.782  8924  8939 D BreventLoader: Can't run brevent server

02-17 12:22:53.782  8924  8939 D BreventLoader: java.lang.reflect.InvocationTargetException

02-17 12:22:53.782  8924  8939 D BreventLoader: 	at java.lang.reflect.Method.invoke(Native Method)

02-17 12:22:53.782  8924  8939 D BreventLoader: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)

02-17 12:22:53.782  8924  8939 D BreventLoader: 	at java.lang.Thread.run(Thread.java:818)

02-17 12:22:53.782  8924  8939 D BreventLoader: Caused by: java.lang.NoSuchMethodError: No interface method getRecentTasks(III)Landroid/content/pm/ParceledListSlice; in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)

02-17 12:22:53.782  8924  8939 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:316)

02-17 12:22:53.782  8924  8939 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:221)

02-17 12:22:53.782  8924  8939 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:133)

02-17 12:22:53.782  8924  8939 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:808)

02-17 12:22:53.782  8924  8939 D BreventLoader: 	... 3 more

02-17 12:22:53.783  8924  8924 D BreventLoader: Brevent Server quit in 30 seconds, quit

02-17 12:22:53.783  8924  8924 D BreventLoader: Can't remove /data/user/0/com.android.shell/lib

--- brevent end ---

**Comment by liudongmiao** [comment]
> AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method getRecentTasks(III)Landroid/content/pm/ParceledListSlice; in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)

没有这个 API ...

**Comment by liudongmiao** [comment]
好吧，这个 API 7.0 才有，你是 6.0 的系统。

**Comment by liudongmiao** [comment]
https://piebridge.me/br/ 请看下 0.5-beta6 这个版本，谢谢。

**Comment by liudongmiao** [comment]
应该已经修复，如果没有，请重开。
