### ISSUE TITLE
在更新后root自启无效

### ISSUE THREAD

**Issue by CaesarW** [liudongmiao/Brevent#520]
**App Version: 2.1.0**

**OS Version: 25**

**Model: Xiaomi-4C MI Cancro**

 在更新黑域后root自启功能失效，需手动点开完成黑域启动。

ROM: Resurrection Remix 5.8.3
Android 7.1.2

**Comment by liudongmiao** [comment]
不带日志的实验性功能反馈，都是在挑战我的极限。。。
