### ISSUE TITLE
Google Pixel手機 最新8.0 beta 系統用不了1.18

### ISSUE THREAD

**Issue by windyyw** [liudongmiao/Brevent#521]
Adb 命令有效，但不超過若干分鐘又失效。

**Comment by liudongmiao** [comment]
据反应，开通之后，不要关 usb 调试～

**Comment by windyyw** [comment]
我沒關

**Comment by windyyw** [comment]
是按home 回到桌面，再回來，就要重新執行 adb 了

**Comment by windyyw** [comment]
https://goo.gl/photos/tCk13osrHCPzVqgYA
https://goo.gl/photos/FMvz1GEqTP44PhdD6
设置哪里不对？

**Comment by windyyw** [comment]
Crash report:

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\r>adb -d logcat -d -b crash
05-20 12:25:47.812  2917  2917 E AndroidRuntime: FATAL EXCEPTION: main
05-20 12:25:47.812  2917  2917 E AndroidRuntime: Process: com.ezonwatch.android4
g2:MainService, PID: 2917
05-20 12:25:47.812  2917  2917 E AndroidRuntime: java.lang.RuntimeException: Una
ble to instantiate service com.ezon.www.ancslib.NotificationService: java.lang.C
lassNotFoundException: Didn't find class "com.ezon.www.ancslib.NotificationServi
ce" on path: DexPathList[[zip file "/data/app/com.ezonwatch.android4g2-1/base.ap
k"],nativeLibraryDirectories=[/data/app/com.ezonwatch.android4g2-1/lib/arm, /sys
tem/fake-libs, /data/app/com.ezonwatch.android4g2-1/base.apk!/lib/armeabi-v7a, /
system/lib, /vendor/lib]]
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at android.app.ActivityT
hread.handleCreateService(ActivityThread.java:3389)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at android.app.ActivityT
hread.-wrap4(Unknown Source:0)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at android.app.ActivityT
hread$H.handleMessage(ActivityThread.java:1681)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at android.os.Handler.di
spatchMessage(Handler.java:105)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at android.os.Looper.loo
p(Looper.java:164)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at android.app.ActivityT
hread.main(ActivityThread.java:6535)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at java.lang.reflect.Met
hod.invoke(Native Method)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at com.android.internal.
os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at com.android.internal.
os.ZygoteInit.main(ZygoteInit.java:767)
05-20 12:25:47.812  2917  2917 E AndroidRuntime: Caused by: java.lang.ClassNotFo
undException: Didn't find class "com.ezon.www.ancslib.NotificationService" on pa
th: DexPathList[[zip file "/data/app/com.ezonwatch.android4g2-1/base.apk"],nativ
eLibraryDirectories=[/data/app/com.ezonwatch.android4g2-1/lib/arm, /system/fake-
libs, /data/app/com.ezonwatch.android4g2-1/base.apk!/lib/armeabi-v7a, /system/li
b, /vendor/lib]]
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at dalvik.system.BaseDex
ClassLoader.findClass(BaseDexClassLoader.java:93)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at java.lang.ClassLoader
.loadClass(ClassLoader.java:379)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at java.lang.ClassLoader
.loadClass(ClassLoader.java:312)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        at android.app.ActivityT
hread.handleCreateService(ActivityThread.java:3386)
05-20 12:25:47.812  2917  2917 E AndroidRuntime:        ... 8 more
05-20 12:25:52.382  3481  3481 E AndroidRuntime: FATAL EXCEPTION: main
05-20 12:25:52.382  3481  3481 E AndroidRuntime: Process: com.ezonwatch.android4
g2:MainService, PID: 3481
05-20 12:25:52.382  3481  3481 E AndroidRuntime: java.lang.RuntimeException: Una
ble to instantiate service com.ezon.www.ancslib.NotificationService: java.lang.C
lassNotFoundException: Didn't find class "com.ezon.www.ancslib.NotificationServi
ce" on path: DexPathList[[zip file "/data/app/com.ezonwatch.android4g2-1/base.ap
k"],nativeLibraryDirectories=[/data/app/com.ezonwatch.android4g2-1/lib/arm, /sys
tem/fake-libs, /data/app/com.ezonwatch.android4g2-1/base.apk!/lib/armeabi-v7a, /
system/lib, /vendor/lib]]
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at android.app.ActivityT
hread.handleCreateService(ActivityThread.java:3389)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at android.app.ActivityT
hread.-wrap4(Unknown Source:0)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at android.app.ActivityT
hread$H.handleMessage(ActivityThread.java:1681)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at android.os.Handler.di
spatchMessage(Handler.java:105)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at android.os.Looper.loo
p(Looper.java:164)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at android.app.ActivityT
hread.main(ActivityThread.java:6535)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at java.lang.reflect.Met
hod.invoke(Native Method)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at com.android.internal.
os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at com.android.internal.
os.ZygoteInit.main(ZygoteInit.java:767)
05-20 12:25:52.382  3481  3481 E AndroidRuntime: Caused by: java.lang.ClassNotFo
undException: Didn't find class "com.ezon.www.ancslib.NotificationService" on pa
th: DexPathList[[zip file "/data/app/com.ezonwatch.android4g2-1/base.apk"],nativ
eLibraryDirectories=[/data/app/com.ezonwatch.android4g2-1/lib/arm, /system/fake-
libs, /data/app/com.ezonwatch.android4g2-1/base.apk!/lib/armeabi-v7a, /system/li
b, /vendor/lib]]
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at dalvik.system.BaseDex
ClassLoader.findClass(BaseDexClassLoader.java:93)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at java.lang.ClassLoader
.loadClass(ClassLoader.java:379)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at java.lang.ClassLoader
.loadClass(ClassLoader.java:312)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        at android.app.ActivityT
hread.handleCreateService(ActivityThread.java:3386)
05-20 12:25:52.382  3481  3481 E AndroidRuntime:        ... 8 more
05-20 12:35:42.112 19055 19055 E AndroidRuntime: FATAL EXCEPTION: main
05-20 12:35:42.112 19055 19055 E AndroidRuntime: Process: me.piebridge.brevent,
PID: 19055
05-20 12:35:42.112 19055 19055 E AndroidRuntime: java.lang.NullPointerException:
 Attempt to invoke virtual method 'me.piebridge.brevent.ui.e me.piebridge.breven
t.ui.m.f(int)' on a null object reference
05-20 12:35:42.112 19055 19055 E AndroidRuntime:        at me.piebridge.brevent.
ui.BreventActivity.q(BreventActivity.java:703)
05-20 12:35:42.112 19055 19055 E AndroidRuntime:        at me.piebridge.brevent.
ui.BreventActivity.a(BreventActivity.java:795)
05-20 12:35:42.112 19055 19055 E AndroidRuntime:        at me.piebridge.brevent.
ui.b.handleMessage(AppsActivityUIHandler.java:58)
05-20 12:35:42.112 19055 19055 E AndroidRuntime:        at android.os.Handler.di
spatchMessage(Handler.java:105)
05-20 12:35:42.112 19055 19055 E AndroidRuntime:        at android.os.Looper.loo
p(Looper.java:164)
05-20 12:35:42.112 19055 19055 E AndroidRuntime:        at android.app.ActivityT
hread.main(ActivityThread.java:6535)
05-20 12:35:42.112 19055 19055 E AndroidRuntime:        at java.lang.reflect.Met
hod.invoke(Native Method)
05-20 12:35:42.112 19055 19055 E AndroidRuntime:        at com.android.internal.
os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-20 12:35:42.112 19055 19055 E AndroidRuntime:        at com.android.internal.
os.ZygoteInit.main(ZygoteInit.java:767)
05-20 12:39:26.619  6605  6605 E AndroidRuntime: FATAL EXCEPTION: main
05-20 12:39:26.619  6605  6605 E AndroidRuntime: Process: com.economist.hummingb
ird, PID: 6605
05-20 12:39:26.619  6605  6605 E AndroidRuntime: android.app.RemoteServiceExcept
ion: Attempt to read from field 'android.content.Intent com.android.server.am.Ta
skRecord.intent' on a null object reference
05-20 12:39:26.619  6605  6605 E AndroidRuntime:        at android.app.ActivityT
hread$H.handleMessage(ActivityThread.java:1773)
05-20 12:39:26.619  6605  6605 E AndroidRuntime:        at android.os.Handler.di
spatchMessage(Handler.java:105)
05-20 12:39:26.619  6605  6605 E AndroidRuntime:        at android.os.Looper.loo
p(Looper.java:164)
05-20 12:39:26.619  6605  6605 E AndroidRuntime:        at android.app.ActivityT
hread.main(ActivityThread.java:6535)
05-20 12:39:26.619  6605  6605 E AndroidRuntime:        at java.lang.reflect.Met
hod.invoke(Native Method)
05-20 12:39:26.619  6605  6605 E AndroidRuntime:        at com.android.internal.
os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-20 12:39:26.619  6605  6605 E AndroidRuntime:        at com.android.internal.
os.ZygoteInit.main(ZygoteInit.java:767)

C:\Users\r>

**Comment by windyyw** [comment]
日志：
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\r>adb -d logcat -d -b main -s BreventServer BreventLoader
05-20 13:16:38.302 28384 28384 D BreventServer: check and brevent
05-20 13:16:39.093 28384 28384 D BreventServer: Force stop com.ihad.ptt(previous
 running)
05-20 13:16:39.109 28384 28384 D BreventServer: Force stop com.zhihu.android(pre
vious running)
05-20 13:16:39.113 28384 28384 D BreventServer: check again in 687s
05-20 13:16:39.113 28384 28384 D BreventServer: check and brevent, took 807ms
05-20 13:17:22.506 28384 28384 D BreventServer: check and brevent
05-20 13:17:23.235 28384 28384 D BreventServer: check again in 643s
05-20 13:17:23.235 28384 28384 D BreventServer: check and brevent, took 728ms
05-20 13:18:23.321 28384 28384 D BreventServer: check and brevent
05-20 13:18:24.046 28384 28384 D BreventServer: check again in 583s
05-20 13:18:24.046 28384 28384 D BreventServer: check and brevent, took 724ms
05-20 13:20:33.886 28384 28384 D BreventServer: check and brevent
05-20 13:20:34.546 28384 28384 D BreventServer: check again in 452s
05-20 13:20:34.546 28384 28384 D BreventServer: check and brevent, took 659ms
05-20 13:21:11.690 28384 28384 D BreventServer: pause activity, tid: 2818, packa
geName: com.coolapk.market
05-20 13:21:13.349 28384 28384 D BreventServer: pause activity, tid: 1549, packa
geName: com.tencent.qqpimsecure
05-20 13:21:13.401 28384 28384 D BreventServer: resume activity, tid: 1193, pack
ageName: com.coolapk.market, launcher: com.google.android.apps.nexuslauncher
05-20 13:21:14.552 28384 28384 D BreventServer: check and brevent
05-20 13:21:15.198 28384 28384 D BreventServer: widgets: {com.google.android.app
s.nexuslauncher}
05-20 13:21:15.198 28384 28384 D BreventServer: running: {imoblife.memorybooster
.lite=650, com.oasisfeng.greenify=2375, imoblife.startupmanager.full=568, com.an
droid.vending=3709, me.piebridge.brevent=3346, com.google.android.dialer=481, cn
.opda.a.phonoalbumshoushou=3709, com.android.chrome=3282, com.economist.hummingb
ird=3709, com.google.android.apps.photos=3228, com.coolapk.market=3708, com.andr
oid.settings=3373, zhs.betalee.ccCallBlocker=521, com.android.systemui=3478}
05-20 13:21:15.198 28384 28384 D BreventServer: recent: {imoblife.memorybooster.
lite=541, com.oasisfeng.greenify=2265, imoblife.startupmanager.full=458, com.and
roid.vending=3005, me.piebridge.brevent=3236, com.ihad.ptt=2230, com.google.andr
oid.dialer=371, cn.opda.a.phonoalbumshoushou=405, com.android.chrome=3172, com.g
oogle.android.gms=2934, com.economist.hummingbird=1159, com.google.android.apps.
photos=3118, com.coolapk.market=3598, com.android.settings=975, com.google.andro
id.inputmethod.pinyin=3063, zhs.betalee.ccCallBlocker=411}
05-20 13:21:15.208 28384 28384 D BreventServer: inactive for imoblife.startupman
ager.full: 3141, timeout: 900
05-20 13:21:15.209 28384 28384 D BreventServer: inactive for com.android.vending
: 0, timeout: 900
05-20 13:21:15.209 28384 28384 D BreventServer: inactive for cn.opda.a.phonoalbu
mshoushou: 0, timeout: 900
05-20 13:21:15.209 28384 28384 D BreventServer: inactive for com.google.android.
apps.photos: 481, timeout: 900
05-20 13:21:15.209 28384 28384 D BreventServer: inactive for com.coolapk.market:
 1, timeout: 900
05-20 13:21:15.209 28384 28384 D BreventServer: inactive for zhs.betalee.ccCallB
locker: 3188, timeout: 900
05-20 13:21:15.235 28384 28384 D BreventServer: com.android.chrome depended by {
imoblife.memorybooster.lite, com.google.android.gms}
05-20 13:21:15.235 28384 28384 D BreventServer: com.google.android.gms depended
by {imoblife.memorybooster.lite, com.google.android.music}
05-20 13:21:15.235 28384 28384 D BreventServer: com.android.providers.userdictio
nary depended by {com.android.providers.blockednumber, com.android.providers.con
tacts}
05-20 13:21:15.235 28384 28384 D BreventServer: service: {}
05-20 13:21:15.235 28384 28384 D BreventServer: back(no action): {}
05-20 13:21:15.235 28384 28384 D BreventServer: blocking: {imoblife.startupmanag
er.full, zhs.betalee.ccCallBlocker}
05-20 13:21:15.235 28384 28384 D BreventServer: top: {com.coolapk.market, com.an
droid.systemui}
05-20 13:21:15.235 28384 28384 D BreventServer: home: {com.google.android.apps.n
exuslauncher}
05-20 13:21:15.235 28384 28384 D BreventServer: current: com.coolapk.market
05-20 13:21:15.235 28384 28384 D BreventServer: next: null
05-20 13:21:15.235 28384 28384 D BreventServer: unsafe: {}
05-20 13:21:15.236 28384 28384 D BreventServer: final blocking: {imoblife.startu
pmanager.full, zhs.betalee.ccCallBlocker}
05-20 13:21:15.236 28384 28384 D BreventServer: notifications: {com.github.shado
wsocks=[98], android=[258], com.google.android.music=[98], com.tencent.qqpimsecu
re=[2, 98], cn.opda.a.phonoalbumshoushou=[98], com.android.systemui=[16]}
05-20 13:21:15.236 28384 28384 D BreventServer: noRecent: {}
05-20 13:21:15.236 28384 28384 D BreventServer: foreground service: {cn.opda.a.p
honoalbumshoushou}
05-20 13:21:15.236 28384 28384 D BreventServer: gcm: {}
05-20 13:21:15.236 28384 28384 D BreventServer: sticky notification: {cn.opda.a.
phonoalbumshoushou}
05-20 13:21:15.237 28384 28384 D BreventServer: full power list: {com.github.sha
dowsocks, im.xingzhe, com.oasisfeng.greenify, com.google.android.apps.enterprise
.dmagent, com.android.providers.downloads, com.qualcomm.qti.telephonyservice, co
m.qti.qualcomm.datastatusnotification, com.psyone.brainmusic, com.qualcomm.qti.r
adioconfiginterface, com.ihad.ptt, com.ezonwatch.android4g2, com.android.cellbro
adcastreceiver, com.google.android.gms, com.google.android.ims, com.google.SSRes
tartDetector, com.qualcomm.qti.ims, com.google.android.tetheringentitlement, com
.android.omadm.service, com.michael.diguet.gps4cam, com.android.shell, com.ants3
60.yicamera, com.qualcomm.atfwd, com.qualcomm.embms}
05-20 13:21:15.239 28384 28384 D BreventServer: check later for imoblife.startup
manager.full: 458
05-20 13:21:15.240 28384 28384 D BreventServer: check later for zhs.betalee.ccCa
llBlocker: 411
05-20 13:21:15.241 28384 28384 D BreventServer: check again in 411s
05-20 13:21:15.241 28384 28384 D BreventServer: check and brevent, took 683ms
05-20 13:23:14.677 28384 28384 D BreventServer: pause activity, tid: 947, packag
eName: com.coolapk.market
05-20 13:23:17.149 28384 28384 D BreventServer: check and brevent
05-20 13:23:17.841 28384 28384 D BreventServer: widgets: {com.google.android.app
s.nexuslauncher}
05-20 13:23:17.841 28384 28384 D BreventServer: running: {imoblife.memorybooster
.lite=650, com.oasisfeng.greenify=2374, imoblife.startupmanager.full=567, com.an
droid.vending=3831, me.piebridge.brevent=3345, com.google.android.dialer=480, cn
.opda.a.phonoalbumshoushou=3831, com.android.chrome=3281, com.economist.hummingb
ird=3831, com.google.android.apps.photos=3227, com.coolapk.market=3828, com.andr
oid.settings=3372, zhs.betalee.ccCallBlocker=520, com.android.systemui=3477}
05-20 13:23:17.841 28384 28384 D BreventServer: recent: {imoblife.memorybooster.
lite=419, com.oasisfeng.greenify=2143, imoblife.startupmanager.full=336, com.and
roid.vending=2883, me.piebridge.brevent=3114, com.ihad.ptt=2108, com.google.andr
oid.dialer=249, cn.opda.a.phonoalbumshoushou=283, com.android.chrome=3050, com.g
oogle.android.gms=2812, com.economist.hummingbird=1037, com.google.android.apps.
photos=2996, com.coolapk.market=3597, com.android.settings=853, com.google.andro
id.inputmethod.pinyin=2941, zhs.betalee.ccCallBlocker=289}
05-20 13:23:17.863 28384 28384 D BreventServer: inactive for imoblife.startupman
ager.full: 3264, timeout: 900
05-20 13:23:17.863 28384 28384 D BreventServer: inactive for com.android.vending
: 0, timeout: 900
05-20 13:23:17.864 28384 28384 D BreventServer: inactive for cn.opda.a.phonoalbu
mshoushou: 0, timeout: 900
05-20 13:23:17.864 28384 28384 D BreventServer: inactive for com.google.android.
apps.photos: 604, timeout: 900
05-20 13:23:17.864 28384 28384 D BreventServer: inactive for com.coolapk.market:
 3, timeout: 900
05-20 13:23:17.864 28384 28384 D BreventServer: inactive for zhs.betalee.ccCallB
locker: 3311, timeout: 900
05-20 13:23:17.915 28384 28384 D BreventServer: com.android.chrome depended by {
imoblife.memorybooster.lite, com.google.android.gms}
05-20 13:23:17.915 28384 28384 D BreventServer: com.google.android.gms depended
by {imoblife.memorybooster.lite, com.google.android.music}
05-20 13:23:17.915 28384 28384 D BreventServer: com.android.providers.userdictio
nary depended by {com.android.providers.blockednumber, com.android.providers.con
tacts}
05-20 13:23:17.916 28384 28384 D BreventServer: service: {}
05-20 13:23:17.916 28384 28384 D BreventServer: back(no action): {}
05-20 13:23:17.916 28384 28384 D BreventServer: blocking: {imoblife.startupmanag
er.full, zhs.betalee.ccCallBlocker}
05-20 13:23:17.916 28384 28384 D BreventServer: top: {com.coolapk.market, com.an
droid.systemui}
05-20 13:23:17.916 28384 28384 D BreventServer: home: {com.google.android.apps.n
exuslauncher}
05-20 13:23:17.916 28384 28384 D BreventServer: current: com.coolapk.market
05-20 13:23:17.916 28384 28384 D BreventServer: next: null
05-20 13:23:17.916 28384 28384 D BreventServer: unsafe: {}
05-20 13:23:17.916 28384 28384 D BreventServer: final blocking: {imoblife.startu
pmanager.full, zhs.betalee.ccCallBlocker}
05-20 13:23:17.916 28384 28384 D BreventServer: notifications: {com.github.shado
wsocks=[98], com.google.android.music=[98], com.tencent.qqpimsecure=[2, 98], cn.
opda.a.phonoalbumshoushou=[98], com.android.systemui=[16]}
05-20 13:23:17.916 28384 28384 D BreventServer: noRecent: {}
05-20 13:23:17.916 28384 28384 D BreventServer: foreground service: {cn.opda.a.p
honoalbumshoushou}
05-20 13:23:17.916 28384 28384 D BreventServer: gcm: {}
05-20 13:23:17.916 28384 28384 D BreventServer: sticky notification: {cn.opda.a.
phonoalbumshoushou}
05-20 13:23:17.918 28384 28384 D BreventServer: full power list: {com.github.sha
dowsocks, im.xingzhe, com.oasisfeng.greenify, com.google.android.apps.enterprise
.dmagent, com.android.providers.downloads, com.qualcomm.qti.telephonyservice, co
m.qti.qualcomm.datastatusnotification, com.psyone.brainmusic, com.qualcomm.qti.r
adioconfiginterface, com.ihad.ptt, com.ezonwatch.android4g2, com.android.cellbro
adcastreceiver, com.google.android.gms, com.google.android.ims, com.google.SSRes
tartDetector, com.qualcomm.qti.ims, com.google.android.tetheringentitlement, com
.android.omadm.service, com.michael.diguet.gps4cam, com.android.shell, com.ants3
60.yicamera, com.qualcomm.atfwd, com.qualcomm.embms}
05-20 13:23:17.920 28384 28384 D BreventServer: check later for imoblife.startup
manager.full: 336
05-20 13:23:17.921 28384 28384 D BreventServer: check later for zhs.betalee.ccCa
llBlocker: 289
05-20 13:23:17.922 28384 28384 D BreventServer: check again in 289s
05-20 13:23:17.922 28384 28384 D BreventServer: check and brevent, took 769ms
05-20 13:25:24.154 28384 28384 D BreventServer: pause activity, tid: 2574, packa
geName: com.coolapk.market
05-20 13:25:25.656 28384 28384 D BreventServer: pause activity, tid: 2770, packa
geName: com.tencent.qqpimsecure
05-20 13:25:25.698 28384 28384 D BreventServer: resume activity, tid: 910, packa
geName: com.coolapk.market, launcher: com.google.android.apps.nexuslauncher
05-20 13:25:26.344 28384 28384 D BreventServer: pause activity, tid: 1187, packa
geName: com.coolapk.market
05-20 13:25:26.348 28384 28384 D BreventServer: resume activity, tid: 1187, pack
ageName: com.google.android.apps.nexuslauncher, launcher: com.google.android.app
s.nexuslauncher
05-20 13:25:28.334 28384 28384 D BreventServer: pause activity, tid: 13414, pack
ageName: com.google.android.apps.nexuslauncher
05-20 13:25:28.404 28384 28384 D BreventServer: pause activity, tid: 1601, packa
geName: com.android.chrome
05-20 13:25:28.421 28384 28384 D BreventServer: resume activity, tid: 13418, pac
kageName: com.android.chrome, launcher: com.google.android.apps.nexuslauncher
05-20 13:25:29.350 28384 28384 D BreventServer: check and brevent
05-20 13:25:30.056 28384 28384 D BreventServer: widgets: {com.google.android.app
s.nexuslauncher}
05-20 13:25:30.056 28384 28384 D BreventServer: running: {imoblife.memorybooster
.lite=651, com.oasisfeng.greenify=2375, imoblife.startupmanager.full=568, com.an
droid.vending=3964, me.piebridge.brevent=3346, com.google.android.dialer=481, cn
.opda.a.phonoalbumshoushou=3964, com.android.chrome=3963, com.economist.hummingb
ird=3964, com.google.android.apps.photos=3228, com.coolapk.market=3961, com.andr
oid.settings=3373, zhs.betalee.ccCallBlocker=521, com.android.systemui=3478}
05-20 13:25:30.056 28384 28384 D BreventServer: recent: {imoblife.memorybooster.
lite=286, com.oasisfeng.greenify=2010, imoblife.startupmanager.full=203, com.and
roid.vending=2750, me.piebridge.brevent=2981, com.ihad.ptt=1975, com.google.andr
oid.dialer=116, cn.opda.a.phonoalbumshoushou=150, com.android.chrome=3598, com.g
oogle.android.gms=2679, com.economist.hummingbird=904, com.google.android.apps.p
hotos=2863, com.coolapk.market=3596, com.android.settings=720, com.google.androi
d.inputmethod.pinyin=2808, zhs.betalee.ccCallBlocker=156}
05-20 13:25:30.075 28384 28384 D BreventServer: inactive for imoblife.startupman
ager.full: 3396, timeout: 900
05-20 13:25:30.075 28384 28384 D BreventServer: inactive for com.android.vending
: 0, timeout: 900
05-20 13:25:30.076 28384 28384 D BreventServer: inactive for cn.opda.a.phonoalbu
mshoushou: 0, timeout: 900
05-20 13:25:30.076 28384 28384 D BreventServer: inactive for com.google.android.
apps.photos: 736, timeout: 900
05-20 13:25:30.076 28384 28384 D BreventServer: inactive for com.coolapk.market:
 3, timeout: 900
05-20 13:25:30.076 28384 28384 D BreventServer: inactive for zhs.betalee.ccCallB
locker: 3443, timeout: 900
05-20 13:25:30.113 28384 28384 D BreventServer: com.android.chrome depended by {
imoblife.memorybooster.lite, com.google.android.gms}
05-20 13:25:30.113 28384 28384 D BreventServer: com.google.android.gms depended
by {imoblife.memorybooster.lite, com.google.android.music}
05-20 13:25:30.113 28384 28384 D BreventServer: com.android.providers.userdictio
nary depended by {com.android.providers.blockednumber, com.android.providers.con
tacts}
05-20 13:25:30.114 28384 28384 D BreventServer: service: {}
05-20 13:25:30.114 28384 28384 D BreventServer: back(no action): {}
05-20 13:25:30.114 28384 28384 D BreventServer: blocking: {imoblife.startupmanag
er.full, zhs.betalee.ccCallBlocker}
05-20 13:25:30.114 28384 28384 D BreventServer: top: {com.android.chrome, com.an
droid.systemui}
05-20 13:25:30.114 28384 28384 D BreventServer: home: {com.google.android.apps.n
exuslauncher}
05-20 13:25:30.114 28384 28384 D BreventServer: current: com.android.chrome
05-20 13:25:30.114 28384 28384 D BreventServer: next: null
05-20 13:25:30.114 28384 28384 D BreventServer: unsafe: {}
05-20 13:25:30.114 28384 28384 D BreventServer: final blocking: {imoblife.startu
pmanager.full, zhs.betalee.ccCallBlocker}
05-20 13:25:30.114 28384 28384 D BreventServer: notifications: {com.github.shado
wsocks=[98], android=[258], com.google.android.music=[98], com.tencent.qqpimsecu
re=[2, 98], cn.opda.a.phonoalbumshoushou=[98], com.android.systemui=[16]}
05-20 13:25:30.114 28384 28384 D BreventServer: noRecent: {}
05-20 13:25:30.114 28384 28384 D BreventServer: foreground service: {cn.opda.a.p
honoalbumshoushou}
05-20 13:25:30.114 28384 28384 D BreventServer: gcm: {}
05-20 13:25:30.114 28384 28384 D BreventServer: sticky notification: {cn.opda.a.
phonoalbumshoushou}
05-20 13:25:30.120 28384 28384 D BreventServer: full power list: {com.github.sha
dowsocks, im.xingzhe, com.oasisfeng.greenify, com.google.android.apps.enterprise
.dmagent, com.android.providers.downloads, com.qualcomm.qti.telephonyservice, co
m.qti.qualcomm.datastatusnotification, com.psyone.brainmusic, com.qualcomm.qti.r
adioconfiginterface, com.ihad.ptt, com.ezonwatch.android4g2, com.android.cellbro
adcastreceiver, com.google.android.gms, com.google.android.ims, com.google.SSRes
tartDetector, com.qualcomm.qti.ims, com.google.android.tetheringentitlement, com
.android.omadm.service, com.michael.diguet.gps4cam, com.android.shell, com.ants3
60.yicamera, com.qualcomm.atfwd, com.qualcomm.embms}
05-20 13:25:30.125 28384 28384 D BreventServer: check later for imoblife.startup
manager.full: 203
05-20 13:25:30.128 28384 28384 D BreventServer: check later for zhs.betalee.ccCa
llBlocker: 156
05-20 13:25:30.128 28384 28384 D BreventServer: check again in 156s
05-20 13:25:30.128 28384 28384 D BreventServer: check and brevent, took 778ms
05-20 13:26:11.251 28384 28384 D BreventServer: pause activity, tid: 1601, packa
geName: com.android.chrome
05-20 13:26:11.273 28384 28384 D BreventServer: resume activity, tid: 2770, pack
ageName: com.android.systemui, launcher: com.google.android.apps.nexuslauncher
05-20 13:26:12.131 28384 28384 D BreventServer: pause activity, tid: 2770, packa
geName: com.android.systemui
05-20 13:26:12.152 28384 28384 D BreventServer: resume activity, tid: 2770, pack
ageName: com.coolapk.market, launcher: com.google.android.apps.nexuslauncher

C:\Users\r>

**Comment by liudongmiao** [comment]
看最新测试版吧：https://piebridge.me/br/next/

**Comment by windyyw** [comment]
貌似找到原因了，插上USB 有这个：
https://goo.gl/photos/PatphPmFtKz1Wukx9
拔掉USB 线就没有了，这时马上失效。

**Comment by windyyw** [comment]
https://goo.gl/photos/sq4HuZUvn3VGut4YA
还是没用。要一直插USB 线与pc 相连才行。
我的手机版本：
https://goo.gl/photos/WZ7zbgpKTs58r8Ku9
https://goo.gl/photos/SzsFfyGFeTheGGP7A

**Comment by liudongmiao** [comment]
你可以执行 adb tcpip 5555
然后使用 网络的方式 连接，然后拔掉线看看

但是，抱歉，我不对这种兼容性提供任何支持。
如果拔线就失效，我也没有任何办法。

你可以升级  adb 至最新版本看看。

**Comment by windyyw** [comment]
不行(adb升级)，问题是O 系统是昨天才升级后出现的，之前7.1.x用了几个月也一直正常啊。问题持续时间不到24小时，之前我正常使用都好几个月了。什么都没变，除了系统，你也用Pixel ，你没这个问题？升级到最新系统O，默认出厂的牛轧糖不算，那个正常使用。

**Comment by windyyw** [comment]
https://goo.gl/photos/vc4Ds6Ma91bppgDA7
请 问最后一行Adb 命令是否需要变化？

**Comment by liudongmiao** [comment]
把 -d 去掉吧。之前加这个，严格表明是设备。现在通过网络调试，把这个去掉就好。

**Comment by mengyyy** [comment]
Nexus5 X Android O 正常

**Comment by windyyw** [comment]
好了。不選之前一直用的RNDIS(USB ethernet)與pc 的連接方式, 直接默認的charging 即可。

**Comment by liudongmiao** [comment]
请确认下，启动之后，可以关闭开发者选项。

**Comment by windyyw** [comment]
确认了，可以正常关闭和重新打开开发者模式。

**Comment by windyyw** [comment]
關閉後要重新打開debugging ,重新連接pc 和 adb 命令，但拔了線也依舊有效。
