### ISSUE TITLE
1.1.6和1.1.8版本的bug

### ISSUE THREAD

**Issue by W0835791** [liudongmiao/Brevent#522]
设置如下：
brevent方法为force stop only， 延迟1min执行，root模式，一加3t氧最新系统安卓7.1
退回到1.1.4版本则问题消失。

问题描述：
场景1：打开一个app（国产某毒瘤），然后返回键退出，应用不会被杀，即使过了延迟执行时间也不会被杀还能推送通知，普遍现象，所有app都如此。brevent页面看到此应用没有被计时，只有一个时钟图标，再重复打开brevent也是如此永远不会被杀。但如果再打开另一个毒瘤app，之前的app会被杀掉。但新打开的app又不会被杀和前app一样，始终会留一个后台。
场景2： 打开app然后用（home键）返回桌面再打开brevent，应用后面显示计时，但也是一直不会被杀掉。此时再打开另一个app，就和场景一描述一致，之前的app被杀但新app将始终保留后台。

log 如下（淘宝始终在后台无法被杀）：

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Wang>adb -d logcat -d -b main -s BreventServer BreventLoader
05-20 08:25:17.970  1859  1859 D BreventServer: checking feelgood
05-20 08:25:17.971  1859  1871 D BreventServer: received feelgood
05-20 08:25:20.806  1859  1859 D BreventServer: check and brevent
05-20 08:25:20.938  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(service)
05-20 08:25:20.949  1859  1859 D BreventServer: check again in 56s
05-20 08:25:20.949  1859  1859 D BreventServer: check and brevent, took 142ms
05-20 08:25:22.824  1859  1859 D BreventServer: checking feelgood
05-20 08:25:22.824  1859  1871 D BreventServer: received feelgood
05-20 08:25:24.002  1859  1859 D BreventServer: check and brevent
05-20 08:25:24.057  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(previous running)
05-20 08:25:24.058  1859  1859 D BreventServer: check again in 53s
05-20 08:25:24.058  1859  1859 D BreventServer: check and brevent, took 56ms
05-20 08:26:09.040  1859  1859 D BreventServer: check and brevent
05-20 08:26:09.111  1859  1859 D BreventServer: check again in 57s
05-20 08:26:09.111  1859  1859 D BreventServer: check and brevent, took 71ms
05-20 08:27:06.111  1859  1859 D BreventServer: check and brevent
05-20 08:27:06.200  1859  1859 D BreventServer: check again in 0s
05-20 08:27:06.200  1859  1859 D BreventServer: check and brevent, took 89ms
05-20 08:27:11.109  1859  1859 D BreventServer: check and brevent
05-20 08:27:11.194  1859  1859 D BreventServer: check again in 3600s
05-20 08:27:11.194  1859  1859 D BreventServer: check and brevent, took 85ms
05-20 08:28:12.567  1859  1859 D BreventServer: checking feelgood
05-20 08:28:12.568  1859  1871 D BreventServer: received feelgood
05-20 08:28:14.541  1859  1859 D BreventServer: check and brevent
05-20 08:28:14.628  1859  1859 D BreventServer: check again in 3600s
05-20 08:28:14.628  1859  1859 D BreventServer: check and brevent, took 86ms
05-20 08:28:19.957  1859  1859 D BreventServer: check and brevent
05-20 08:28:21.696  1859  1859 D BreventServer: check again in 3600s
05-20 08:28:21.696  1859  1859 D BreventServer: check and brevent, took 1732ms
05-20 08:29:46.237  1859  1859 D BreventServer: checking feelgood
05-20 08:29:46.238  1859  1871 D BreventServer: received feelgood
05-20 08:29:51.296  1859  1859 D BreventServer: check and brevent
05-20 08:29:51.454  1859  1859 D BreventServer: check again in 3600s
05-20 08:29:51.454  1859  1859 D BreventServer: check and brevent, took 158ms
05-20 08:30:39.339  1859  1859 D BreventServer: checking feelgood
05-20 08:30:39.339  1859  1871 D BreventServer: received feelgood
05-20 08:30:41.085  1859  1859 D BreventServer: check and brevent
05-20 08:30:41.255  1859  1859 D BreventServer: check again in 3600s
05-20 08:30:41.255  1859  1859 D BreventServer: check and brevent, took 169ms
05-20 08:30:44.261  1859  1859 D BreventServer: check and brevent
05-20 08:30:44.415  1859  1859 D BreventServer: Force stop com.sohu.sohuvideo(forceStop)
05-20 08:30:44.422  1859  1859 D BreventServer: check again in 59s
05-20 08:30:44.422  1859  1859 D BreventServer: check and brevent, took 158ms
05-20 08:30:51.576  1859  1859 D BreventServer: checking feelgood
05-20 08:30:51.576  1859  1871 D BreventServer: received feelgood
05-20 08:30:56.019  1859  1859 D BreventServer: check and brevent
05-20 08:30:56.118  1859  1859 D BreventServer: Force stop com.sohu.sohuvideo(previous running)
05-20 08:30:56.119  1859  1859 D BreventServer: check again in 55s
05-20 08:30:56.119  1859  1859 D BreventServer: check and brevent, took 99ms
05-20 08:31:51.170  1859  1859 D BreventServer: check and brevent
05-20 08:31:51.252  1859  1859 D BreventServer: check again in 0s
05-20 08:31:51.252  1859  1859 D BreventServer: check and brevent, took 82ms
05-20 08:31:56.709  1859  1859 D BreventServer: check and brevent
05-20 08:31:56.794  1859  1859 D BreventServer: check again in 3600s
05-20 08:31:56.794  1859  1859 D BreventServer: check and brevent, took 84ms
05-20 08:33:13.450  1859  1859 D BreventServer: checking feelgood
05-20 08:33:13.451  1859  1871 D BreventServer: received feelgood
05-20 08:33:15.455  1859  1859 D BreventServer: checking feelgood
05-20 08:33:15.460  1859  1871 D BreventServer: received feelgood
05-20 08:33:18.185  1859  1859 D BreventServer: checking feelgood
05-20 08:33:18.186  1859  1871 D BreventServer: received feelgood
05-20 08:33:19.522  1859  1859 D BreventServer: check and brevent
05-20 08:33:19.601  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(forceStop)
05-20 08:33:19.606  1859  1859 D BreventServer: Force stop com.baidu.netdisk(service)
05-20 08:33:19.609  1859  1859 D BreventServer: check again in 3600s
05-20 08:33:19.609  1859  1859 D BreventServer: check and brevent, took 87ms
05-20 08:33:23.204  1859  1859 D BreventServer: checking feelgood
05-20 08:33:23.204  1859  1871 D BreventServer: received feelgood
05-20 08:33:24.752  1859  1859 D BreventServer: check and brevent
05-20 08:33:24.928  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(previous running)
05-20 08:33:24.941  1859  1859 D BreventServer: Force stop com.baidu.netdisk(previous running)
05-20 08:33:24.948  1859  1859 D BreventServer: check again in 3600s
05-20 08:33:24.948  1859  1859 D BreventServer: check and brevent, took 195ms
05-20 08:33:40.623  1859  1859 D BreventServer: check and brevent
05-20 08:33:40.690  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(forceStop)
05-20 08:33:40.698  1859  1859 D BreventServer: Force stop com.baidu.netdisk(forceStop)
05-20 08:33:40.700  1859  1859 D BreventServer: check again in 3600s
05-20 08:33:40.700  1859  1859 D BreventServer: check and brevent, took 77ms
05-20 08:33:48.889  1859  1859 D BreventServer: check and brevent
05-20 08:33:48.981  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(forceStop)
05-20 08:33:48.987  1859  1859 D BreventServer: Force stop com.baidu.netdisk(service)
05-20 08:33:48.989  1859  1859 D BreventServer: check again in 3600s
05-20 08:33:48.989  1859  1859 D BreventServer: check and brevent, took 99ms
05-20 08:34:46.803  1859  1859 D BreventServer: check and brevent
05-20 08:34:48.132  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(previous running)
05-20 08:34:48.150  1859  1859 D BreventServer: Force stop com.baidu.netdisk(previous running)
05-20 08:34:48.157  1859  1859 D BreventServer: check again in 3600s
05-20 08:34:48.157  1859  1859 D BreventServer: check and brevent, took 1329ms
05-20 08:35:13.676  1859  1859 D BreventServer: checking feelgood
05-20 08:35:13.676  1859  1871 D BreventServer: received feelgood
05-20 08:35:15.487  1859  1859 D BreventServer: check and brevent
05-20 08:35:15.553  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(forceStop)
05-20 08:35:15.556  1859  1859 D BreventServer: Force stop com.baidu.netdisk(service)
05-20 08:35:15.557  1859  1859 D BreventServer: check again in 3600s
05-20 08:35:15.557  1859  1859 D BreventServer: check and brevent, took 70ms
05-20 08:35:19.486  1859  1859 D BreventServer: check and brevent
05-20 08:35:19.567  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(previous running)
05-20 08:35:19.569  1859  1859 D BreventServer: Force stop com.baidu.netdisk(previous running)
05-20 08:35:19.571  1859  1859 D BreventServer: check again in 3600s
05-20 08:35:19.571  1859  1859 D BreventServer: check and brevent, took 85ms
05-20 08:35:40.330  1859  1859 D BreventServer: checking feelgood
05-20 08:35:40.332  1859  1871 D BreventServer: received feelgood
05-20 08:35:47.065  1859  1859 D BreventServer: check and brevent
05-20 08:35:47.143  1859  1859 D BreventServer: check again in 3600s
05-20 08:35:47.143  1859  1859 D BreventServer: check and brevent, took 77ms
05-20 08:36:46.203  1859  1859 D BreventServer: check and brevent
05-20 08:36:46.778  1859  1859 D BreventServer: check again in 3600s
05-20 08:36:46.778  1859  1859 D BreventServer: check and brevent, took 546ms
05-20 08:37:01.253  1859  1859 D BreventServer: check and brevent
05-20 08:37:01.374  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(forceStop)
05-20 08:37:01.381  1859  1859 D BreventServer: Force stop com.baidu.netdisk(forceStop)
05-20 08:37:01.381  1859  1859 D BreventServer: check again in 3600s
05-20 08:37:01.381  1859  1859 D BreventServer: check and brevent, took 127ms
05-20 08:37:03.283  1859  1859 D BreventServer: checking feelgood
05-20 08:37:03.284  1859  1871 D BreventServer: received feelgood
05-20 08:37:07.425  1859  1859 D BreventServer: check and brevent
05-20 08:37:07.513  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(previous running)
05-20 08:37:07.515  1859  1859 D BreventServer: Force stop com.baidu.netdisk(previous running)
05-20 08:37:07.515  1859  1859 D BreventServer: check again in 3600s
05-20 08:37:07.515  1859  1859 D BreventServer: check and brevent, took 89ms
05-20 08:38:06.560  1859  1859 D BreventServer: check and brevent
05-20 08:38:07.776  1859  1859 D BreventServer: check again in 3600s
05-20 08:38:07.776  1859  1859 D BreventServer: check and brevent, took 1127ms
05-20 08:38:56.801  1859  1859 D BreventServer: checking feelgood
05-20 08:38:56.802  1859  1871 D BreventServer: received feelgood
05-20 08:38:57.802  1859  1859 D BreventServer: check and brevent
05-20 08:38:58.096  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(forceStop)
05-20 08:38:58.102  1859  1859 D BreventServer: Force stop com.baidu.netdisk(forceStop)
05-20 08:38:58.103  1859  1859 D BreventServer: check again in 3600s
05-20 08:38:58.103  1859  1859 D BreventServer: check and brevent, took 300ms
05-20 08:39:01.771  1859  1859 D BreventServer: checking feelgood
05-20 08:39:01.772  1859  1871 D BreventServer: received feelgood
05-20 08:39:02.966  1859  1859 D BreventServer: check and brevent
05-20 08:39:03.040  1859  1859 D BreventServer: Force stop com.ss.android.essay.joke(previous running)
05-20 08:39:03.044  1859  1859 D BreventServer: Force stop com.baidu.netdisk(previous running)
05-20 08:39:03.046  1859  1859 D BreventServer: check again in 3600s
05-20 08:39:03.046  1859  1859 D BreventServer: check and brevent, took 80ms
05-20 08:39:11.319  1859  1859 D BreventServer: checking feelgood
05-20 08:39:11.320  1859  1871 D BreventServer: received feelgood
05-20 08:39:59.015  1859  1859 D BreventServer: check and brevent
05-20 08:39:59.095  1859  1859 D BreventServer: check again in 3600s
05-20 08:39:59.095  1859  1859 D BreventServer: check and brevent, took 80ms
05-20 08:40:15.783  1859  1859 D BreventServer: check and brevent
05-20 08:40:15.920  1859  1859 D BreventServer: Force stop com.baidu.appsearch(forceStop)
05-20 08:40:15.921  1859  1859 D BreventServer: check again in 57s
05-20 08:40:15.921  1859  1859 D BreventServer: check and brevent, took 138ms
05-20 08:40:16.285  1859  1859 D BreventServer: checking feelgood
05-20 08:40:16.285  1859  1871 D BreventServer: received feelgood
05-20 08:40:22.876  1859  1859 D BreventServer: check and brevent
05-20 08:40:22.961  1859  1859 D BreventServer: Force stop com.baidu.appsearch(previous running)
05-20 08:40:22.971  1859  1859 D BreventServer: check again in 60s
05-20 08:40:22.971  1859  1859 D BreventServer: check and brevent, took 95ms
05-20 08:40:23.942  1859  1859 D BreventServer: abnormal back: com.taobao.taobao
05-20 08:40:26.603  1859  1859 D BreventServer: checking feelgood
05-20 08:40:26.603  1859  1871 D BreventServer: received feelgood
05-20 08:40:26.943  1859  1859 D BreventServer: check and brevent
05-20 08:40:27.011  1859  1859 D BreventServer: check again in 57s
05-20 08:40:27.011  1859  1859 D BreventServer: check and brevent, took 66ms
05-20 08:40:28.940  1859  1859 D BreventServer: checking feelgood
05-20 08:40:28.943  1859  1871 D BreventServer: received feelgood
05-20 08:41:16.473  1859  1859 D BreventServer: check and brevent
05-20 08:41:17.445  1859  1859 D BreventServer: check again in 7s
05-20 08:41:17.446  1859  1859 D BreventServer: check and brevent, took 946ms
05-20 08:41:24.458  1859  1859 D BreventServer: check and brevent
05-20 08:41:25.060  1859  1859 D BreventServer: check again in 0s
05-20 08:41:25.060  1859  1859 D BreventServer: check and brevent, took 583ms
05-20 08:41:27.067  1859  1859 D BreventServer: check and brevent
05-20 08:41:28.064  1859  1859 D BreventServer: check again in 3600s
05-20 08:41:28.064  1859  1859 D BreventServer: check and brevent, took 953ms
05-20 08:43:19.231  1859  1859 D BreventServer: checking feelgood
05-20 08:43:19.231  1859  1871 D BreventServer: received feelgood
05-20 08:43:21.055  1859  1859 D BreventServer: check and brevent
05-20 08:43:21.166  1859  1859 D BreventServer: check again in 3600s
05-20 08:43:21.166  1859  1859 D BreventServer: check and brevent, took 111ms

C:\Users\Wang>

**Comment by W0835791** [comment]
自顶一个，两个设备都是如此，希望能得到解决

**Comment by liudongmiao** [comment]
确实是个问题。自 1.1.5 解决另外一个问题时引入。

你看下这个版本是否修复：
https://piebridge.me/br/next/ 

如果已经修复，请发送邮件至我邮箱，我好给你特别贡献优惠。

**Comment by W0835791** [comment]
此版本解决了！，多谢！

**Comment by liudongmiao** [comment]
请发送邮件至我邮箱，我好给你特别贡献优惠。
