### ISSUE TITLE
可否通过授权网络adb方式使用黑域

### ISSUE THREAD

**Issue by chenfei0928** [liudongmiao/Brevent#523]
如果我在pc上通过 `adb tcpip 5555` 打开手机的网络adb调试，那么是否可以让黑域自己通过shell调用来网络adb调起自己的后台脚本启动

**Comment by chenfei0928** [comment]
就像 app ops 那样的工作方式

**Comment by vvb2060** [comment]
网络adb调试重启后自动关闭

**Comment by chenfei0928** [comment]
为同时使用 app ops 和黑域
如果可以通过网络adb的话我就可以同时启动两个程序的后台了
而且黑域的命令很长，通常是通过qq传给pc后复制进去cmd
adb tcpip 5555 这段很短并且容易记忆

**Comment by liudongmiao** [comment]
网络调试很危险…我不会支持。
但明显你可以用 remote adb 来启动。

黑域真正的指令，是 sh /sdcard/Android/...
并且，详细介绍里都提供了，你自己可以随时复制。

现在也统一了，不会变。你随时可以保留为脚本。
如果你明白路径意义，也没有那么长，其实很好记。

我从不提供对用户来说危险的操作。
