### ISSUE TITLE
发现黑域无法正常显示app的后台运行状态

### ISSUE THREAD

**Issue by yyikj14** [liudongmiao/Brevent#524]
现象：
黑域中“没有运行”列表中显示有摩拜单车、网易有道词典、51talk无忧英语。
但是，点击这三者中任意一个》应用信息》会看到“强制停止”按钮可以点，说明该app在后台运行
由于我每次用完app都是从最近列表中X掉，所以这一现象也说明，黑域并没有有效阻断某些应用对于这三个app的唤醒

手机是国行三星s7，android 7.0，没有root
黑域1.1.8普通模式

**Comment by liudongmiao** [comment]
可以强行停止，不代表在运行。
同时，不能强行停止，也不代表没有运行。
你可以开发者选项中查看正在运行的服务来验证。

升级 1.1.10，然后重新执行 ADB 吧。

**Comment by liudongmiao** [comment]
你可以开发者选项中查看正在运行的服务及缓存，以及系统自带的 ps 命令，dumpsys activity processes
 等来验证。

**Comment by yyikj14** [comment]
谢谢回复！

那app显示可以强行停止，代表它处在一种什么状态呢？
我用taskman也发现了，在“进程”和“服务”中都没有的app，却可能可以“强行停止”。
你说的“系统自带的 ps 命令，dumpsys activity processes”我都不知道如何运行。抱歉，对于安卓的知识几乎没有，问题估计很弱，谢谢解答！

**Comment by liudongmiao** [comment]
非“停止状态”。
