### ISSUE TITLE
发现黑域无法阻止ofo对于高德地图后台的唤醒

### ISSUE THREAD

**Issue by yyikj14** [liudongmiao/Brevent#525]
现象：
刚刚检查过高德地图后台没有运行（在设置》应用程序》高德地图中看到“强制停止”按钮为灰色，处于不可以按的状态）
然后启动ofo，然后再次检查高德地图，发现后台已经运行（即“强制停止”按钮为可以按的状态）

下面是日志：
05-21 14:57:45.862 24891 24891 D BreventServer: pause activity, tid: 3910, packageName: com.android.settings
05-21 14:57:45.910 24891 24891 D BreventServer: resume activity, tid: 13203, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:57:46.658 24891 24891 D BreventServer: pause activity, tid: 2843, packageName: org.wen.taskman
05-21 14:57:48.048 24891 24891 D BreventServer: pause activity, tid: 3444, packageName: com.android.settings
05-21 14:57:48.090 24891 24891 D BreventServer: resume activity, tid: 13202, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:57:49.222 24891 24891 D BreventServer: pause activity, tid: 3472, packageName: org.wen.taskman
05-21 14:57:50.585 24891 24891 D BreventServer: pause activity, tid: 4101, packageName: com.android.settings
05-21 14:57:50.631 24891 24891 D BreventServer: resume activity, tid: 13202, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:57:51.432 24891 24891 D BreventServer: pause activity, tid: 16863, packageName: org.wen.taskman
05-21 14:57:52.893 24891 24891 D BreventServer: pause activity, tid: 3880, packageName: com.android.settings
05-21 14:57:52.926 24891 24891 D BreventServer: resume activity, tid: 3851, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:57:53.771 24891 24891 D BreventServer: pause activity, tid: 15435, packageName: org.wen.taskman
05-21 14:57:55.172 24891 24891 D BreventServer: pause activity, tid: 3906, packageName: com.android.settings
05-21 14:57:55.205 24891 24891 D BreventServer: resume activity, tid: 3851, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:57:56.767 24891 24891 D BreventServer: pause activity, tid: 32711, packageName: org.wen.taskman
05-21 14:57:58.138 24891 24891 D BreventServer: pause activity, tid: 16863, packageName: com.android.settings
05-21 14:57:58.175 24891 24891 D BreventServer: resume activity, tid: 4101, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:57:59.012 24891 24891 D BreventServer: pause activity, tid: 15435, packageName: org.wen.taskman
05-21 14:58:00.355 24891 24891 D BreventServer: pause activity, tid: 13203, packageName: com.android.settings
05-21 14:58:00.387 24891 24891 D BreventServer: resume activity, tid: 3897, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:01.227 24891 24891 D BreventServer: pause activity, tid: 4222, packageName: org.wen.taskman
05-21 14:58:02.472 24891 24891 D BreventServer: pause activity, tid: 3900, packageName: com.android.settings
05-21 14:58:02.549 24891 24891 D BreventServer: resume activity, tid: 4101, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:03.476 24891 24891 D BreventServer: pause activity, tid: 3910, packageName: org.wen.taskman
05-21 14:58:05.013 24891 24891 D BreventServer: pause activity, tid: 4101, packageName: com.android.settings
05-21 14:58:05.089 24891 24891 D BreventServer: resume activity, tid: 3908, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:07.023 24891 24891 D BreventServer: pause activity, tid: 13204, packageName: org.wen.taskman
05-21 14:58:08.405 24891 24891 D BreventServer: pause activity, tid: 13203, packageName: com.android.settings
05-21 14:58:08.461 24891 24891 D BreventServer: resume activity, tid: 2843, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:09.579 24891 24891 D BreventServer: pause activity, tid: 16863, packageName: org.wen.taskman
05-21 14:58:10.494 24891 24891 D BreventServer: check and brevent
05-21 14:58:10.618 24891 24891 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, com.sec.android.daemonapp, com.baidu.searchbox_samsung}
05-21 14:58:10.618 24891 24891 D BreventServer: running: {com.oasisfeng.greenify=361737, com.tencent.mm=373882, com.android.settings=373947, org.wen.taskman=373946}
05-21 14:58:10.618 24891 24891 D BreventServer: recent: {com.tencent.mm=3535, com.android.settings=3543, org.wen.taskman=3599}
05-21 14:58:10.675 24891 24891 D BreventServer: inactive for org.wen.taskman: 1, timeout: 1800
05-21 14:58:10.789 24891 24891 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify}
05-21 14:58:10.789 24891 24891 D BreventServer: service: {}
05-21 14:58:10.789 24891 24891 D BreventServer: back(no action): {}
05-21 14:58:10.789 24891 24891 D BreventServer: blocking: {}
05-21 14:58:10.789 24891 24891 D BreventServer: top: {com.android.settings}
05-21 14:58:10.789 24891 24891 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-21 14:58:10.789 24891 24891 D BreventServer: current: org.wen.taskman
05-21 14:58:10.789 24891 24891 D BreventServer: next: com.android.settings
05-21 14:58:10.789 24891 24891 D BreventServer: unsafe: {}
05-21 14:58:10.789 24891 24891 D BreventServer: final blocking: {}
05-21 14:58:10.789 24891 24891 D BreventServer: notifications: {}
05-21 14:58:10.789 24891 24891 D BreventServer: noRecent: {}
05-21 14:58:10.789 24891 24891 D BreventServer: foreground service: {}
05-21 14:58:10.789 24891 24891 D BreventServer: sticky notification: {}
05-21 14:58:10.793 24891 24891 D BreventServer: Force stop io.dushu.fandengreader(previous running)
05-21 14:58:10.794 24891 24891 D BreventServer: check again in 1799s
05-21 14:58:10.794 24891 24891 D BreventServer: check and brevent, took 299ms
05-21 14:58:10.994 24891 24891 D BreventServer: pause activity, tid: 13203, packageName: com.android.settings
05-21 14:58:11.036 24891 24891 D BreventServer: resume activity, tid: 3910, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:12.453 24891 24891 D BreventServer: pause activity, tid: 3905, packageName: org.wen.taskman
05-21 14:58:13.916 24891 24891 D BreventServer: pause activity, tid: 3948, packageName: com.android.settings
05-21 14:58:13.970 24891 24891 D BreventServer: resume activity, tid: 3905, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:16.006 24891 24891 D BreventServer: pause activity, tid: 15436, packageName: org.wen.taskman
05-21 14:58:17.457 24891 24891 D BreventServer: pause activity, tid: 3901, packageName: com.android.settings
05-21 14:58:17.512 24891 24891 D BreventServer: resume activity, tid: 3904, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:19.164 24891 24891 D BreventServer: pause activity, tid: 3901, packageName: org.wen.taskman
05-21 14:58:20.516 24891 24891 D BreventServer: pause activity, tid: 3908, packageName: com.android.settings
05-21 14:58:20.575 24891 24891 D BreventServer: resume activity, tid: 3910, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:22.142 24891 24891 D BreventServer: pause activity, tid: 3900, packageName: org.wen.taskman
05-21 14:58:23.633 24891 24891 D BreventServer: pause activity, tid: 16863, packageName: com.android.settings
05-21 14:58:23.685 24891 24891 D BreventServer: resume activity, tid: 2842, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:25.547 24891 24891 D BreventServer: pause activity, tid: 3910, packageName: org.wen.taskman
05-21 14:58:26.927 24891 24891 D BreventServer: pause activity, tid: 3910, packageName: com.android.settings
05-21 14:58:26.974 24891 24891 D BreventServer: resume activity, tid: 17402, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:29.393 24891 24891 D BreventServer: pause activity, tid: 3741, packageName: org.wen.taskman
05-21 14:58:30.757 24891 24891 D BreventServer: pause activity, tid: 3472, packageName: com.android.settings
05-21 14:58:30.822 24891 24891 D BreventServer: resume activity, tid: 3898, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:32.270 24891 24891 D BreventServer: pause activity, tid: 3904, packageName: org.wen.taskman
05-21 14:58:33.751 24891 24891 D BreventServer: pause activity, tid: 13203, packageName: com.android.settings
05-21 14:58:33.815 24891 24891 D BreventServer: resume activity, tid: 3459, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:34.726 24891 24891 D BreventServer: pause activity, tid: 17400, packageName: org.wen.taskman
05-21 14:58:36.116 24891 24891 D BreventServer: pause activity, tid: 3901, packageName: com.android.settings
05-21 14:58:36.166 24891 24891 D BreventServer: resume activity, tid: 3898, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:38.266 24891 24891 D BreventServer: pause activity, tid: 17402, packageName: org.wen.taskman
05-21 14:58:39.757 24891 24891 D BreventServer: pause activity, tid: 2843, packageName: com.android.settings
05-21 14:58:39.823 24891 24891 D BreventServer: resume activity, tid: 3459, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:40.887 24891 24891 D BreventServer: pause activity, tid: 3908, packageName: org.wen.taskman
05-21 14:58:42.116 24891 24891 D BreventServer: pause activity, tid: 3904, packageName: com.android.settings
05-21 14:58:42.344 24891 24891 D BreventServer: resume activity, tid: 3895, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:43.435 24891 24891 D BreventServer: pause activity, tid: 17400, packageName: org.wen.taskman
05-21 14:58:45.625 24891 24891 D BreventServer: pause activity, tid: 4222, packageName: com.android.settings
05-21 14:58:46.130 24891 24891 D BreventServer: resume activity, tid: 3472, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:49.168 24891 24891 D BreventServer: pause activity, tid: 13204, packageName: org.wen.taskman
05-21 14:58:51.115 24891 24891 D BreventServer: pause activity, tid: 16862, packageName: com.android.settings
05-21 14:58:51.699 24891 24891 D BreventServer: resume activity, tid: 2846, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:52.878 24891 24891 D BreventServer: pause activity, tid: 3906, packageName: org.wen.taskman
05-21 14:58:54.353 24891 24891 D BreventServer: pause activity, tid: 3905, packageName: com.android.settings
05-21 14:58:54.385 24891 24891 D BreventServer: resume activity, tid: 2843, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:56.551 24891 24891 D BreventServer: pause activity, tid: 16862, packageName: org.wen.taskman
05-21 14:58:57.917 24891 24891 D BreventServer: pause activity, tid: 3444, packageName: com.android.settings
05-21 14:58:57.970 24891 24891 D BreventServer: resume activity, tid: 4101, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:58:58.948 24891 24891 D BreventServer: pause activity, tid: 3906, packageName: org.wen.taskman
05-21 14:59:00.525 24891 24891 D BreventServer: pause activity, tid: 3444, packageName: com.android.settings
05-21 14:59:00.576 24891 24891 D BreventServer: resume activity, tid: 3851, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:59:01.555 24891 24891 D BreventServer: pause activity, tid: 17402, packageName: org.wen.taskman
05-21 14:59:01.594 24891 24891 D BreventServer: resume activity, tid: 17402, packageName: com.android.systemui, launcher: com.sec.android.app.launcher
05-21 14:59:03.158 24891 24891 D BreventServer: pause activity, tid: 3898, packageName: com.android.systemui
05-21 14:59:03.235 24891 24891 D BreventServer: resume activity, tid: 16863, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher
05-21 14:59:06.238 24891 24891 D BreventServer: check and brevent
05-21 14:59:06.414 24891 24891 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, com.sec.android.daemonapp, com.baidu.searchbox_samsung}
05-21 14:59:06.414 24891 24891 D BreventServer: running: {com.oasisfeng.greenify=361737, com.tencent.mm=373883}
05-21 14:59:06.414 24891 24891 D BreventServer: recent: {com.tencent.mm=3479}
05-21 14:59:06.602 24891 24891 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify}
05-21 14:59:06.602 24891 24891 D BreventServer: service: {}
05-21 14:59:06.603 24891 24891 D BreventServer: back(no action): {}
05-21 14:59:06.603 24891 24891 D BreventServer: blocking: {}
05-21 14:59:06.603 24891 24891 D BreventServer: top: {}
05-21 14:59:06.603 24891 24891 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-21 14:59:06.603 24891 24891 D BreventServer: current: com.sec.android.app.launcher
05-21 14:59:06.603 24891 24891 D BreventServer: next: com.android.settings
05-21 14:59:06.603 24891 24891 D BreventServer: unsafe: {}
05-21 14:59:06.603 24891 24891 D BreventServer: final blocking: {}
05-21 14:59:06.603 24891 24891 D BreventServer: notifications: {}
05-21 14:59:06.603 24891 24891 D BreventServer: noRecent: {}
05-21 14:59:06.603 24891 24891 D BreventServer: foreground service: {}
05-21 14:59:06.603 24891 24891 D BreventServer: sticky notification: {}
05-21 14:59:06.614 24891 24891 D BreventServer: Force stop org.wen.taskman(previous running)
05-21 14:59:06.618 24891 24891 D BreventServer: check again in 3600s
05-21 14:59:06.618 24891 24891 D BreventServer: check and brevent, took 377ms
05-21 14:59:08.476 24891 24891 D BreventServer: pause activity, tid: 4222, packageName: com.sec.android.app.launcher
05-21 14:59:09.527 24891 24891 D BreventServer: pause activity, tid: 3906, packageName: so.ofo.labofo
05-21 14:59:19.004 24891 24891 D BreventServer: pause activity, tid: 3909, packageName: so.ofo.labofo
05-21 14:59:19.052 24891 24891 D BreventServer: resume activity, tid: 3909, packageName: com.android.systemui, launcher: com.sec.android.app.launcher
05-21 14:59:20.515 24891 24891 D BreventServer: pause activity, tid: 3895, packageName: com.android.systemui
05-21 14:59:20.561 24891 24891 D BreventServer: resume activity, tid: 3897, packageName: com.tencent.mm, launcher: com.sec.android.app.launcher
05-21 14:59:23.870 24891 24891 D BreventServer: pause activity, tid: 2847, packageName: com.tencent.mm
05-21 14:59:23.970 24891 24891 D BreventServer: resume activity, tid: 15435, packageName: com.sec.android.app.launcher, launcher: com.sec.android.app.launcher
05-21 14:59:25.591 24891 24891 D BreventServer: pause activity, tid: 3901, packageName: com.sec.android.app.launcher
05-21 14:59:26.972 24891 24891 D BreventServer: check and brevent
05-21 14:59:27.089 24891 24891 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, com.sec.android.daemonapp, com.baidu.searchbox_samsung}
05-21 14:59:27.089 24891 24891 D BreventServer: running: {com.oasisfeng.greenify=361737, com.tencent.mm=374021, org.wen.taskman=374023}
05-21 14:59:27.089 24891 24891 D BreventServer: recent: {com.tencent.mm=3596, org.wen.taskman=3598}
05-21 14:59:27.132 24891 24891 D BreventServer: inactive for org.wen.taskman: 1, timeout: 1800
05-21 14:59:27.204 24891 24891 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify}
05-21 14:59:27.204 24891 24891 D BreventServer: service: {}
05-21 14:59:27.204 24891 24891 D BreventServer: back(no action): {}
05-21 14:59:27.204 24891 24891 D BreventServer: blocking: {}
05-21 14:59:27.204 24891 24891 D BreventServer: top: {org.wen.taskman}
05-21 14:59:27.204 24891 24891 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-21 14:59:27.204 24891 24891 D BreventServer: current: org.wen.taskman
05-21 14:59:27.204 24891 24891 D BreventServer: next: org.wen.taskman
05-21 14:59:27.204 24891 24891 D BreventServer: unsafe: {}
05-21 14:59:27.204 24891 24891 D BreventServer: final blocking: {}
05-21 14:59:27.204 24891 24891 D BreventServer: notifications: {}
05-21 14:59:27.204 24891 24891 D BreventServer: noRecent: {}
05-21 14:59:27.204 24891 24891 D BreventServer: foreground service: {}
05-21 14:59:27.204 24891 24891 D BreventServer: sticky notification: {}
05-21 14:59:27.205 24891 24891 D BreventServer: check again in 1799s
05-21 14:59:27.205 24891 24891 D BreventServer: check and brevent, took 231ms
05-21 14:59:28.061 24891 24891 D BreventServer: pause activity, tid: 3948, packageName: org.wen.taskman
05-21 14:59:32.160 24891 24891 D BreventServer: pause activity, tid: 17402, packageName: com.android.settings
05-21 14:59:32.188 24891 24891 D BreventServer: resume activity, tid: 17402, packageName: com.android.systemui, launcher: com.sec.android.app.launcher
05-21 14:59:34.389 24891 24891 D BreventServer: pause activity, tid: 15435, packageName: com.android.systemui
05-21 14:59:34.420 24891 24891 D BreventServer: resume activity, tid: 3895, packageName: org.wen.taskman, launcher: com.sec.android.app.launcher
05-21 14:59:35.490 24891 24891 D BreventServer: pause activity, tid: 2857, packageName: org.wen.taskman
05-21 14:59:37.798 24891 24891 D BreventServer: check and brevent
05-21 14:59:37.918 24891 24891 D BreventServer: widgets: {com.sec.android.widgetapp.samsungapps, com.sec.android.daemonapp, com.baidu.searchbox_samsung}
05-21 14:59:37.918 24891 24891 D BreventServer: running: {com.oasisfeng.greenify=361737, com.tencent.mm=374021, org.wen.taskman=374033}
05-21 14:59:37.918 24891 24891 D BreventServer: recent: {com.tencent.mm=3586, org.wen.taskman=3598}
05-21 14:59:37.972 24891 24891 D BreventServer: inactive for org.wen.taskman: 2, timeout: 1800
05-21 14:59:38.040 24891 24891 D BreventServer: com.google.android.gms depended by {com.oasisfeng.greenify}
05-21 14:59:38.040 24891 24891 D BreventServer: service: {}
05-21 14:59:38.040 24891 24891 D BreventServer: back(no action): {}
05-21 14:59:38.040 24891 24891 D BreventServer: blocking: {}
05-21 14:59:38.040 24891 24891 D BreventServer: top: {org.wen.taskman}
05-21 14:59:38.040 24891 24891 D BreventServer: home: {com.sec.android.app.launcher, com.android.systemui}
05-21 14:59:38.040 24891 24891 D BreventServer: current: org.wen.taskman
05-21 14:59:38.040 24891 24891 D BreventServer: next: com.android.settings
05-21 14:59:38.040 24891 24891 D BreventServer: unsafe: {}
05-21 14:59:38.040 24891 24891 D BreventServer: final blocking: {}
05-21 14:59:38.040 24891 24891 D BreventServer: notifications: {}
05-21 14:59:38.040 24891 24891 D BreventServer: noRecent: {}
05-21 14:59:38.040 24891 24891 D BreventServer: foreground service: {}
05-21 14:59:38.040 24891 24891 D BreventServer: sticky notification: {}
05-21 14:59:38.040 24891 24891 D BreventServer: check again in 1798s
05-21 14:59:38.040 24891 24891 D BreventServer: check and brevent, took 239ms

**Comment by liudongmiao** [comment]
黑域并不会完全阻断唤醒，如果真要通过 bind 服务，也是可以唤醒的，要不然你系统就该出错了。
这个事前阻断，并没有任何实际意义，能用与不断唤醒之间并没有实际区别。

讲真的，A 唤醒支付宝可以，B 唤醒微信分享可以，都是通过相同技术手段，C 就不能唤醒 X 弹个通知？
你要体验和“事前阻断”类似的体验，可以开启“立即黑域”。但是，如果你某个应用打不开，不要怪我。

**Comment by yyikj14** [comment]
谢谢回复！

但是看得不是太明白，再问一下。“事前阻断”是什么意思？看你的意思，是不是说，如果实现了事前阻断，我就无法做到用B唤醒微信分享这样的事？

看样子，启动ofo，唤醒高德地图后台，是正常的结果。黑域不会事前阻断，那么黑域会对这个后台做后续的处理吗？这个高德后台是否适用黑域中“离开后台应用30分钟后”“后台应用超时”的处理？我看此时黑域的“没有运行”列表中有高德地图，所以是不是黑域认为它没有后台在运行？

抱歉问题有点多，不过确实不太明白，请回答一下，非常感谢！

**Comment by liudongmiao** [comment]
如果唤醒之后，没有打开界面，会不久后（正常的话，3 秒）就会强行停止它们。
但有时，应用 3 秒内可以弹个通知。立即黑域的话，不会延迟 3 秒，而是立即。

**Comment by yyikj14** [comment]
谢谢回复！

我搜了一下安卓程序状态：“程序”又可以分为三部分：有UI界面，用户可以交互的Activity、没有UI界面但会在后台运行的Services和接收别人通知的一个机制Receiver。

我理解，前两者应该就是通常说的进程和服务，而第三种就是既非前两种，又能够“强行停止”的状态。

刚才我看了一下，本主贴中提到的，刚刚下午3点左右被ofo唤醒的高德地图（即处于上述receiver状态），在现在4点半的时候，还是处于那种状态。那么看来，黑域并不会处理这种处于receiver状态的程序后台。

是这样子吧？

**Comment by aviraxp** [comment]
完全不是这样子。。。。

一句话，你可以认为强行停止按钮是否可以按下，和程序是否运行，没有任何关系。

**Comment by yyikj14** [comment]
越说我越糊涂了。。。

可能是因为我不懂安卓，对一些的术语含义的猜测有误，跟你们的理解不一样。但我觉得，一个应用的强行停止可用，总是应该说明它以某种形态在后台“运行”着，占用着资源，消耗着电量。

你们的意思是不是，留着一堆应用以强行停止可用的状态存在，对于资源消耗、电量消耗的影响可以忽略，压根不用管它们？还是说是基于某种妥协（比如为了支持在应用中唤醒微信进行分享这种情况），必须要留下这些东西在后台？谢谢啦！

关于“强行停止”，我看了以下这些资料：
http://droidyue.com/blog/2014/07/14/look-inside-android-package-stop-state-since-honeycomb-mr1/index.html
http://www.cnblogs.com/bravestarrhu/archive/2012/05/02/2479461.html
http://www.pingwest.com/kill-process-in-a-smart-way/
可能理解的不对，但是一个应用有不同的“运行”形式，这个理解应该不错，实在不懂你说“强行停止”可用跟程序“运行与否没有任何关系”。可否详细解释一二？多谢！

**Comment by liudongmiao** [comment]
可以强行停止，不代表实际在运行；没有运行，哪有什么资源之说？
Android 这样设计，主要是因为引入了停止状态。
关于停止状态：https://developer.android.google.cn/about/versions/android-3.1.html#launchcontrols

一句话，相信黑域即可。

再说一遍，可以强行停止，不代表在运行；不能强行停止，也不代表没有运行。
黑域使用相当多的底层 API 来表示程序状态，你可以使用以下方式验证：
- ps
- 开发者选项中“正在运行的服务”
- dumpsys activity processes

这些，在前一个 issue 中提到过，不要选择性忽视。
如果你还有疑问，我建议，相信黑域即可；如果不相信，卸载即可。

关于唤醒，从技术的角度，唤醒 A 支付，唤醒 B 分享，唤醒 C 通知，这些可以完全没有差别。
黑域借助“停止状态”，可以阻断广播类唤醒，这也是某守普通版的功能。
对于无法分辨善恶的服务类唤醒，黑域采取最终是否打开界面来判断，事后杀，过程中，可能会出现通知之类，但都将不久后被杀。

关于黑域：http://www.jianshu.com/p/aa3395d04b6d

此事到此为止。
