### ISSUE TITLE
Permanent Notification

### ISSUE THREAD

**Issue by Zero3K** [liudongmiao/Brevent#527]
It would be nice if it had one so the user could see when it closes a program, etc.

**Comment by Zero3K** [comment]
So, any thoughts regarding my suggestion?

**Comment by liudongmiao** [comment]
It doesn't make sense.

Brevent only force-stop apps when:

1. You don't use app, Back / HOME then timeout, swiping from recent list

2. Other app are awaken by other app or system.

Just trust. And I don't want to bother users.
However, if you want to know, just see the log.
It's the features in next version.
