### ISSUE TITLE
Box with loading circle when loading it after updating 

### ISSUE THREAD

**Issue by Zero3K** [liudongmiao/Brevent#528]
When loading it after updating by downloading the new version off of its server and installing it, a box with a loading circle is shown. There should be some text added to it that states that it is updating its server or have the updating of it occur when installing the client side of it.

**Comment by Zero3K** [comment]
So, any thoughts regarding my suggestion?

**Comment by liudongmiao** [comment]
It doesn't make sense. 

Brevent UI don't know the Brevent Server when it's upgrading.
And when Brevent UI knows, it will just works.
