### ISSUE TITLE
软件识别为框架应用

### ISSUE THREAD

**Issue by mzfqy** [liudongmiao/Brevent#53]
一加3氧OS和小米5miui8测试

**Comment by liudongmiao** [comment]
https://piebridge.me/br/ 看下 0.5-beta5 这个版本，谢谢。

**Comment by mzfqy** [comment]
没修复

**Comment by liudongmiao** [comment]
https://piebridge.me/br/ 那接着看下 0.5-beta6 这个版本，谢谢。

**Comment by mzfqy** [comment]
b6有了

**Comment by liudongmiao** [comment]
请去设置里，开启框架应用，给个截图看看。另外，你使用的是哪个 ROM ？

这样对不好，也就是说，所有程序都可能是框架应用，非常危险。

**Comment by liudongmiao** [comment]
去 https://piebridge.me/br/ 这里下载那个带 dirty 的版本，看下有没有框架应用。

**Comment by liudongmiao** [comment]
请下载最新的测试版看看：http://piebridge.me/br/
