### ISSUE TITLE
“立即黑域”的bug

### ISSUE THREAD

**Issue by liyufan** [liudongmiao/Brevent#530]
打开了“立即黑域”后，打开被黑域的app时，若之前app未运行，会在打开瞬间或一秒到两秒后（还在启动画面时）被黑域强行停止。
以下为日志：
1.打开酷安app，此前酷安app没有运行，然后酷安启动时被强行停止（类似于闪退时的情形，白屏启动画面，然后app突然退出）
05-21 22:26:05.912  8706  8706 D BreventServer: check and brevent
05-21 22:26:06.553  8706  8706 D BreventServer: check again in 3600s
05-21 22:26:06.553  8706  8706 D BreventServer: check and brevent, took 619ms
05-21 22:26:29.457  8706  8706 D BreventServer: Force stop com.coolapk.market(brevent request)
2.打开bilibili，同上：
05-21 22:21:12.374  8706  8706 D BreventServer: check and brevent
05-21 22:21:13.028  8706  8706 D BreventServer: check again in 3600s
05-21 22:21:13.028  8706  8706 D BreventServer: check and brevent, took 652ms
05-21 22:21:29.975  8706  8706 D BreventServer: Force stop tv.danmaku.bili(brevent request)

app被黑域停止后再次进入，则正常。
若从最近任务列表划掉刚才被启动的app，再次打开，则再次出现打开时被黑域强行停止的问题。

经测试，一些被黑域的app如酷安、斗鱼、饿了么、bilibili在打开了“立即黑域”后，会出现这种情况。
而QQ，微信，高德地图，支付宝，10086等，即使被黑域并且打开了“立即黑域”后，不会出现以上情况。

实测，将“立即黑域”关上后，打开app时，若此前这个app没有运行，不会被黑域强行停止。

**Comment by liudongmiao** [comment]
立即黑域就是这么设计的。所以，有风险嘛。

后面优化了下，但还是无法避免所有情况。

你可以下载测试最新测试版：https://piebridge.me/br/next/

**Comment by liyufan** [comment]
@liudongmiao 已经更新至最新测试版，还是有问题。
录了个视频，看下：
https://eyun.baidu.com/s/3dEWdJVF

**Comment by liudongmiao** [comment]
这是已知问题，遇到这种问题，按 Home 放后台，再打开。

**Comment by liudongmiao** [comment]
目前在最新测试版中修复，如果还有，请去新的项目地址。
