### ISSUE TITLE
Some apps aren't showing up in the list

### ISSUE THREAD

**Issue by Zero3K** [liudongmiao/Brevent#531]
One example of such app is called "Cellular Data".

**Comment by Zero3K** [comment]
In other words, please see about having it be able to brevent the same apps that Greenify is able to automatically hibernate.

**Comment by liudongmiao** [comment]
Brevent show this app:

1. user aps.
2. system apps (if you want to see all, turn on show all apps)
3. framework apps (you need to turn on show framework apps, and show all apps)

Brevent never show apps:

- uid less than 10000, which is part of system, like radio, system or so.

It doesn't make any sense for you to brevent.
If it works, it may brick your device; and if it doesn't work, users just bb, why it doesn't brevent this apps.

**Comment by liudongmiao** [comment]
for your "Cellular Data", I think, it should be radio..., you can check it yourself.
You just don't want to use your phone?

**Comment by Zero3K** [comment]
Its not a phone, its a tablet.

**Comment by Zero3K** [comment]
So, why is Greenify able to hibernate more system apps then?

**Comment by liudongmiao** [comment]
I won't check it's emulator, or tablet, or phone. 
And I won't show apps which uid greater than 1000.

Every app has it's degisn, I think brevent it's ok.
And if you don't think so, just fork your version, and build yourself.

it's hard limit in Brevent:
https://github.com/liudongmiao/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/ui/AppsItemAdapter.java#L388

**Comment by liudongmiao** [comment]
And even you remove these codes, you can only show it in Brevent's UI.
Brevent server refuses to brevent it. (I won't release source code for brevent server)

It's better to no-brick your device, than users' crazy idea.

**Comment by Zero3K** [comment]
Oh, ok. I understand.
