### ISSUE TITLE
最新版晚上待机疯狂掉电 

### ISSUE THREAD

**Issue by zhwang321** [liudongmiao/Brevent#532]
1.1.10版本之前或者可能是1，1.08版本之前一晚待机都是最多掉2.3格点 最近频繁更新之后到最新版  连续几晚掉30左右的电量

这个日志也不知道对不对 

[rizhi.txt](https://github.com/liudongmiao/Brevent/files/1017513/rizhi.txt)

**Comment by zhwang321** [comment]
不方便下载的我粘贴一下
PS E:\Nexus5x\adb> adb -d logcat -d -b main -s BreventServer BreventLoader
05-22 08:22:15.861  8482  8482 D BreventServer: abnormal back: com.tencent.qt.qtl
05-22 08:22:18.861  8482  8482 D BreventServer: check and brevent
05-22 08:22:19.009  8482  8482 D BreventServer: check again in 297s
05-22 08:22:19.009  8482  8482 D BreventServer: check and brevent, took 147ms
05-22 08:27:16.031  8482  8482 D BreventServer: check and brevent
05-22 08:27:16.203  8482  8482 D BreventServer: check again in 0s
05-22 08:27:16.203  8482  8482 D BreventServer: check and brevent, took 170ms
05-22 08:27:18.206  8482  8482 D BreventServer: check and brevent
05-22 08:27:18.594  8482  8482 D BreventServer: check again in 146s
05-22 08:27:18.594  8482  8482 D BreventServer: check and brevent, took 385ms
05-22 08:29:44.617  8482  8482 D BreventServer: check and brevent
05-22 08:29:44.883  8482  8482 D BreventServer: check again in 277s
05-22 08:29:44.883  8482  8482 D BreventServer: check and brevent, took 263ms
05-22 08:31:35.523  8482  8482 D BreventServer: check and brevent
05-22 08:31:35.870  8482  8482 D BreventServer: check again in 166s
05-22 08:31:35.870  8482  8482 D BreventServer: check and brevent, took 344ms
05-22 08:34:21.874  8482  8482 D BreventServer: check and brevent
05-22 08:34:22.080  8482  8482 D BreventServer: check again in 174s
05-22 08:34:22.080  8482  8482 D BreventServer: check and brevent, took 203ms
05-22 08:36:58.571  8482  8482 D BreventServer: abnormal back: com.baidu.xxtieba
05-22 08:37:02.463  8482  8482 D BreventServer: check and brevent
05-22 08:37:02.842  8482  8482 D BreventServer: check again in 13s
05-22 08:37:02.842  8482  8482 D BreventServer: check and brevent, took 376ms
05-22 08:37:19.161  8482  8482 D BreventServer: check and brevent
05-22 08:37:29.323  8482  8482 D BreventServer: Force stop com.tencent.qt.qtl(noRecent)
05-22 08:37:29.329  8482  8482 D BreventServer: check again in 280s
05-22 08:37:29.329  8482  8482 D BreventServer: check and brevent, took 10166ms
05-22 08:42:44.474  8482  8482 D BreventServer: check and brevent
05-22 08:42:44.832  8482  8482 D BreventServer: Force stop com.tencent.qt.qtl(previous running)
05-22 08:42:44.839  8482  8482 D BreventServer: check again in 554s
05-22 08:42:44.840  8482  8482 D BreventServer: check and brevent, took 361ms
05-22 08:43:20.943  8482  8482 D BreventServer: checking feelgood
05-22 08:43:20.943  8482  8496 D BreventServer: received feelgood
05-22 08:45:05.254  8482  8482 D BreventServer: check and brevent
05-22 08:45:05.563  8482  8482 D BreventServer: check again in 413s
05-22 08:45:05.563  8482  8482 D BreventServer: check and brevent, took 305ms
05-22 08:46:03.942  8482  8482 D BreventServer: check and brevent
05-22 08:46:04.313  8482  8482 D BreventServer: check again in 354s
05-22 08:46:04.313  8482  8482 D BreventServer: check and brevent, took 368ms
PS E:\Nexus5x\adb> adb -d logcat -d -b crash
05-21 21:10:57.352   537   537 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9c in tid 537 (zygote)
05-21 21:10:57.418  1292  1292 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-21 21:10:57.418  1292  1292 F DEBUG   : LineageOS Version: '14.1-20170519-UNOFFICIAL-z2_plus'
05-21 21:10:57.418  1292  1292 F DEBUG   : Build fingerprint: 'ZUK/z2_plus/z2_plus:6.0.1/MMB29M/1.9.077_160617:user/release-keys'
05-21 21:10:57.418  1292  1292 F DEBUG   : Revision: '0'
05-21 21:10:57.418  1292  1292 F DEBUG   : ABI: 'arm'
05-21 21:10:57.418  1292  1292 F DEBUG   : pid: 537, tid: 537, name: zygote  >>> zygote <<<
05-21 21:10:57.418  1292  1292 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x9c
05-21 21:10:57.420  1292  1292 F DEBUG   : Abort message: 'art/runtime/gc/heap.cc:426] Check failed: main_mem_map_2.get() != nullptr Failed anonymous mmap(0x0, 1073741824, 0x3, 0x2, 5, 0): Out of memory. See process maps in the log.'
05-21 21:10:57.420  1292  1292 F DEBUG   :     r0 00000000  r1 df08359b  r2 00000000  r3 00000080
05-21 21:10:57.420  1292  1292 F DEBUG   :     r4 ea9aac60  r5 ffa2a390  r6 00000000  r7 00000000
05-21 21:10:57.420  1292  1292 F DEBUG   :     r8 ea92a800  r9 00000001  sl ea9f7280  fp 00000000
05-21 21:10:57.420  1292  1292 F DEBUG   :     ip eabe5f80  sp ffa2a350  lr eabe0cd9  pc ea7cee14  cpsr 60010030
05-21 21:10:57.432  1292  1292 F DEBUG   :
05-21 21:10:57.432  1292  1292 F DEBUG   : backtrace:
05-21 21:10:57.432  1292  1292 F DEBUG   :     #00 pc 0033ce14  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEb+199)
05-21 21:10:57.432  1292  1292 F DEBUG   :     #01 pc 00324175  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+372)
05-21 21:10:57.432  1292  1292 F DEBUG   :     #02 pc 0031ae9d  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
05-21 21:10:57.432  1292  1292 F DEBUG   :     #03 pc 000b5285  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1132)
05-21 21:10:57.432  1292  1292 F DEBUG   :     #04 pc 00181a61  /system/lib/libart.so (_ZN3art2gc4HeapC1EjjjjddjjRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS_14InstructionSetENS0_13CollectorTypeESC_NS0_5space20LargeObjectSpaceTypeEjjjbjjbbbbbbbbbby+10736)
05-21 21:10:57.432  1292  1292 F DEBUG   :     #05 pc 0031cedd  /system/lib/libart.so (_ZN3art7Runtime4InitEONS_18RuntimeArgumentMapE+6556)
05-21 21:10:57.433  1292  1292 F DEBUG   :     #06 pc 0031ef4b  /system/lib/libart.so (_ZN3art7Runtime6CreateERKNSt3__16vectorINS1_4pairINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKvEENS7_ISC_EEEEb+66)
05-21 21:10:57.433  1292  1292 F DEBUG   :     #07 pc 0023cec5  /system/lib/libart.so (JNI_CreateJavaVM+388)
05-21 21:10:57.433  1292  1292 F DEBUG   :     #08 pc 0006826f  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime7startVmEPP7_JavaVMPP7_JNIEnvb+2250)
05-21 21:10:57.433  1292  1292 F DEBUG   :     #09 pc 00068645  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+272)
05-21 21:10:57.433  1292  1292 F DEBUG   :     #10 pc 00001947  /system/bin/app_process32
05-21 21:10:57.433  1292  1292 F DEBUG   :     #11 pc 00016c8d  /system/lib/libc.so (__libc_init+48)
05-21 21:10:57.433  1292  1292 F DEBUG   :     #12 pc 00001564  /system/bin/app_process32
05-21 21:10:58.101  1342  1342 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9c in tid 1342 (zygote)
05-21 21:10:58.167  1423  1423 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-21 21:10:58.167  1423  1423 F DEBUG   : LineageOS Version: '14.1-20170519-UNOFFICIAL-z2_plus'
05-21 21:10:58.167  1423  1423 F DEBUG   : Build fingerprint: 'ZUK/z2_plus/z2_plus:6.0.1/MMB29M/1.9.077_160617:user/release-keys'
05-21 21:10:58.167  1423  1423 F DEBUG   : Revision: '0'
05-21 21:10:58.167  1423  1423 F DEBUG   : ABI: 'arm'
05-21 21:10:58.167  1423  1423 F DEBUG   : pid: 1342, tid: 1342, name: zygote  >>> zygote <<<
05-21 21:10:58.167  1423  1423 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x9c
05-21 21:10:58.169  1423  1423 F DEBUG   : Abort message: 'art/runtime/gc/heap.cc:426] Check failed: main_mem_map_2.get() != nullptr Failed anonymous mmap(0x0, 1073741824, 0x3, 0x2, 5, 0): Out of memory. See process maps in the log.'
05-21 21:10:58.169  1423  1423 F DEBUG   :     r0 00000000  r1 0f00a327  r2 00000000  r3 00000080
05-21 21:10:58.169  1423  1423 F DEBUG   :     r4 e9caac60  r5 ffebd5e0  r6 00000000  r7 00000000
05-21 21:10:58.169  1423  1423 F DEBUG   :     r8 e9c2a800  r9 00000001  sl e9cf7280  fp 00000000
05-21 21:10:58.169  1423  1423 F DEBUG   :     ip eb8a5f80  sp ffebd5a0  lr eb8a0cd9  pc e9acee14  cpsr 60010030
05-21 21:10:58.175  1423  1423 F DEBUG   :
05-21 21:10:58.175  1423  1423 F DEBUG   : backtrace:
05-21 21:10:58.175  1423  1423 F DEBUG   :     #00 pc 0033ce14  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEb+199)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #01 pc 00324175  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+372)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #02 pc 0031ae9d  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #03 pc 000b5285  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1132)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #04 pc 00181a61  /system/lib/libart.so (_ZN3art2gc4HeapC1EjjjjddjjRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS_14InstructionSetENS0_13CollectorTypeESC_NS0_5space20LargeObjectSpaceTypeEjjjbjjbbbbbbbbbby+10736)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #05 pc 0031cedd  /system/lib/libart.so (_ZN3art7Runtime4InitEONS_18RuntimeArgumentMapE+6556)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #06 pc 0031ef4b  /system/lib/libart.so (_ZN3art7Runtime6CreateERKNSt3__16vectorINS1_4pairINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKvEENS7_ISC_EEEEb+66)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #07 pc 0023cec5  /system/lib/libart.so (JNI_CreateJavaVM+388)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #08 pc 0006826f  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime7startVmEPP7_JavaVMPP7_JNIEnvb+2250)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #09 pc 00068645  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+272)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #10 pc 00001947  /system/bin/app_process32
05-21 21:10:58.175  1423  1423 F DEBUG   :     #11 pc 00016c8d  /system/lib/libc.so (__libc_init+48)
05-21 21:10:58.175  1423  1423 F DEBUG   :     #12 pc 00001564  /system/bin/app_process32
05-21 22:20:10.211 10064 10064 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-21 22:20:10.211 10064 10064 F DEBUG   : LineageOS Version: '14.1-20170519-UNOFFICIAL-z2_plus'
05-21 22:20:10.211 10064 10064 F DEBUG   : Build fingerprint: 'ZUK/z2_plus/z2_plus:6.0.1/MMB29M/1.9.077_160617:user/release-keys'
05-21 22:20:10.211 10064 10064 F DEBUG   : Revision: '0'
05-21 22:20:10.211 10064 10064 F DEBUG   : ABI: 'arm'
05-21 22:20:10.211 10064 10064 F DEBUG   : pid: 10063, tid: 10063, name: libprocmox_v1_4  >>> /data/user/0/com.baidu.xxtieba/files/libprocmox_v1_4.so <<<
05-21 22:20:10.211 10064 10064 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-21 22:20:10.211 10064 10064 F DEBUG   :     r0 00000000  r1 0000274f  r2 00000006  r3 00000008
05-21 22:20:10.211 10064 10064 F DEBUG   :     r4 f77ce58c  r5 00000006  r6 f77ce534  r7 0000010c
05-21 22:20:10.211 10064 10064 F DEBUG   :     r8 f7769000  r9 ffcb9024  sl 00000000  fp 00000000
05-21 22:20:10.211 10064 10064 F DEBUG   :     ip 00000000  sp ffcb7cf8  lr f77aed4f  pc f77af768  cpsr 20070010
05-21 22:20:10.217 10064 10064 F DEBUG   :
05-21 22:20:10.217 10064 10064 F DEBUG   : backtrace:
05-21 22:20:10.217 10064 10064 F DEBUG   :     #00 pc 00046768  /system/bin/linker (__dl_tgkill+12)
05-21 22:20:10.217 10064 10064 F DEBUG   :     #01 pc 00045d4b  /system/bin/linker (__dl_pthread_kill+34)
05-21 22:20:10.217 10064 10064 F DEBUG   :     #02 pc 0003e0ef  /system/bin/linker (__dl_raise+10)
05-21 22:20:10.217 10064 10064 F DEBUG   :     #03 pc 0003cbab  /system/bin/linker (__dl___libc_android_abort+34)
05-21 22:20:10.217 10064 10064 F DEBUG   :     #04 pc 0003bb14  /system/bin/linker (__dl_abort+4)
05-21 22:20:10.217 10064 10064 F DEBUG   :     #05 pc 0003dbeb  /system/bin/linker (__dl___libc_fatal+22)
05-21 22:20:10.217 10064 10064 F DEBUG   :     #06 pc 00009d9f  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+3494)
05-21 22:20:10.217 10064 10064 F DEBUG   :     #07 pc 00008f63  /system/bin/linker (__dl___linker_init+358)
05-21 22:20:10.217 10064 10064 F DEBUG   :     #08 pc 000027c0  /system/bin/linker (_start+4)
05-21 22:44:26.741 11002 11002 E AndroidRuntime: FATAL EXCEPTION: main
05-21 22:44:26.741 11002 11002 E AndroidRuntime: Process: com.sina.weibo, PID: 11002
05-21 22:44:26.741 11002 11002 E AndroidRuntime: java.lang.RuntimeException: Unable to stop service com.sina.weibo.weiyou.refactor.service.DMService@2ac7aef: java.lang.IllegalArgumentException: Receiver not registered: com.sina.weibo.weiyou.refactor.service.c.a$2@f15e893
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at android.app.ActivityThread.handleStopService(ActivityThread.java:3398)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at android.app.ActivityThread.-wrap27(ActivityThread.java)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-21 22:44:26.741 11002 11002 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.sina.weibo.weiyou.refactor.service.c.a$2@f15e893
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1007)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1330)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:608)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at com.sina.weibo.weiyou.refactor.service.c.a.b(ConnectionPool.java:54)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at com.sina.weibo.weiyou.refactor.service.DMService.onDestroy(DMService.java:211)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        at android.app.ActivityThread.handleStopService(ActivityThread.java:3381)
05-21 22:44:26.741 11002 11002 E AndroidRuntime:        ... 8 more
05-22 08:22:18.064 20522 20522 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-22 08:22:18.065 20522 20522 F DEBUG   : LineageOS Version: '14.1-20170519-UNOFFICIAL-z2_plus'
05-22 08:22:18.065 20522 20522 F DEBUG   : Build fingerprint: 'ZUK/z2_plus/z2_plus:6.0.1/MMB29M/1.9.077_160617:user/release-keys'
05-22 08:22:18.065 20522 20522 F DEBUG   : Revision: '0'
05-22 08:22:18.065 20522 20522 F DEBUG   : ABI: 'arm'
05-22 08:22:18.065 20522 20522 F DEBUG   : pid: 20520, tid: 20520, name: libprocmox_v1_4  >>> /data/user/0/com.baidu.xxtieba/files/libprocmox_v1_4.so <<<
05-22 08:22:18.065 20522 20522 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-22 08:22:18.065 20522 20522 F DEBUG   :     r0 00000000  r1 00005028  r2 00000006  r3 00000008
05-22 08:22:18.065 20522 20522 F DEBUG   :     r4 f296858c  r5 00000006  r6 f2968534  r7 0000010c
05-22 08:22:18.065 20522 20522 F DEBUG   :     r8 f2903000  r9 ffe51e74  sl 00000000  fp 00000000
05-22 08:22:18.065 20522 20522 F DEBUG   :     ip 00000000  sp ffe50b48  lr f2948d4f  pc f2949768  cpsr 20070010
05-22 08:22:18.070 20522 20522 F DEBUG   :
05-22 08:22:18.070 20522 20522 F DEBUG   : backtrace:
05-22 08:22:18.070 20522 20522 F DEBUG   :     #00 pc 00046768  /system/bin/linker (__dl_tgkill+12)
05-22 08:22:18.070 20522 20522 F DEBUG   :     #01 pc 00045d4b  /system/bin/linker (__dl_pthread_kill+34)
05-22 08:22:18.070 20522 20522 F DEBUG   :     #02 pc 0003e0ef  /system/bin/linker (__dl_raise+10)
05-22 08:22:18.070 20522 20522 F DEBUG   :     #03 pc 0003cbab  /system/bin/linker (__dl___libc_android_abort+34)
05-22 08:22:18.070 20522 20522 F DEBUG   :     #04 pc 0003bb14  /system/bin/linker (__dl_abort+4)
05-22 08:22:18.070 20522 20522 F DEBUG   :     #05 pc 0003dbeb  /system/bin/linker (__dl___libc_fatal+22)
05-22 08:22:18.070 20522 20522 F DEBUG   :     #06 pc 00009d9f  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+3494)
05-22 08:22:18.070 20522 20522 F DEBUG   :     #07 pc 00008f63  /system/bin/linker (__dl___linker_init+358)
05-22 08:22:18.070 20522 20522 F DEBUG   :     #08 pc 000027c0  /system/bin/linker (_start+4)

**Comment by liudongmiao** [comment]
打开 黑域，连按 8 次 Home，看是否有提示。

没有提示的话，重新执行启动指令。

**Comment by zhwang321** [comment]
有的

**Comment by liudongmiao** [comment]
那你就需要看晚上的日志，有没有疯狂强行停止某个应用之类。
这和你使用习惯有关，如果你黑域了某个要不断启动的系统应用，不断启与杀，只会更加耗电。

但是，你的日志，没有相关内容。需要更多日志。
对我而已，并没有你说的这些问题。

**Comment by zhwang321** [comment]
使用黑域到现在从未黑域过任何一个系统应用 而且系统应用都不会开启那个选项的 晚上的日志怎么查看 我不是很懂这个日志..

**Comment by liudongmiao** [comment]
那就没有办法了....

**Comment by zhwang321** [comment]
这.. 那我退回之前的版本在等你发布新版还是保持现状呢  还有之前的版本我不知道在哪下载 （酷安的算了）

**Comment by liudongmiao** [comment]
https://piebridge.me/br/

这里有最新版，所有历史版本，最新测试版本。

**Comment by zhwang321** [comment]
好的 那我退回一个试试吧
