### ISSUE TITLE
印象笔记卡欢迎页面, ssr卡白屏

### ISSUE THREAD

**Issue by LSvKing** [liudongmiao/Brevent#536]
印象笔记卡欢迎页面, ssr卡白屏 系统是 锤子的7.1.1  用的adb模式 这两个软件执行shell后 无法打开 重启shell失效后软件就好了，在执行一次命令 还是进不去

**Comment by liudongmiao** [comment]
电脑上装 teamviewer，把 id 和 密码发我邮箱，我上去看看 (br@piebridge.me)

**Comment by liudongmiao** [comment]
已经解决，错误黑域谷歌家族软件所致。
