### ISSUE TITLE
dumpsys activity activities 解析异常

### ISSUE THREAD

**Issue by dudukee** [liudongmiao/Brevent#54]
C:\Users\lenovo>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstr
ap.so

checking...remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.and
roid.shell/lib
reset_reason_init
..........
cannot listen port, please report bug
--- crash start ---
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
```
02-17 15:20:48.724 12325 12325 D BreventLoader: lib: /data/user/0/com.android.sh
ell/lib, loader: /data/user/0/com.android.shell/lib/libloader.so
02-17 15:20:48.774 12325 12340 D BreventServer: Brevent Server 0.5 started
02-17 15:20:48.784 12325 12340 D BreventServer: brevent user: 0, uid: 2000
02-17 15:20:48.784 12325 12340 D BreventServer: brevent data directory: /data/us
er/0/com.android.shell
02-17 15:20:48.974 12325 12340 D BreventServer: loaded brevent list
02-17 15:20:48.974 12325 12340 D BreventServer: loaded brevent conf
02-17 15:20:49.004 12325 12340 D BreventLoader: Can't run brevent server
02-17 15:20:49.004 12325 12340 D BreventLoader: java.lang.reflect.InvocationTarg
etException
02-17 15:20:49.004 12325 12340 D BreventLoader:         at java.lang.reflect.Met
hod.invoke(Native Method)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at me.piebridge.brevent.
loader.Brevent.run(Brevent.java:57)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at java.lang.Thread.run(
Thread.java:818)
02-17 15:20:49.004 12325 12340 D BreventLoader: Caused by: java.lang.NumberForma
tException: Invalid int: ""
02-17 15:20:49.004 12325 12340 D BreventLoader:         at java.lang.Integer.inv
alidInt(Integer.java:138)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at java.lang.Integer.par
seInt(Integer.java:358)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at java.lang.Integer.par
seInt(Integer.java:334)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at ku.g(HideApi.java:395
)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at ku.d(HideApi.java:362
)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at ku.a(HideApi.java:275
)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.k(BreventServer.java:696)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.a(BreventServer.java:684)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.<init>(BreventServer.java:133)
02-17 15:20:49.004 12325 12340 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.main(BreventServer.java:820)
02-17 15:20:49.004 12325 12340 D BreventLoader:         ... 3 more
02-17 15:20:49.004 12325 12325 D BreventLoader: Brevent Server quit in 30 second
s, quit
02-17 15:20:49.004 12325 12325 D BreventLoader: Can't remove /data/user/0/com.an
droid.shell/lib
02-17 15:22:14.624 13230 13230 D BreventLoader: lib: /data/user/0/com.android.sh
ell/lib, loader: /data/user/0/com.android.shell/lib/libloader.so
02-17 15:22:14.664 13230 13245 D BreventServer: Brevent Server 0.5 started
02-17 15:22:14.674 13230 13245 D BreventServer: brevent user: 0, uid: 2000
02-17 15:22:14.674 13230 13245 D BreventServer: brevent data directory: /data/us
er/0/com.android.shell
02-17 15:22:14.834 13230 13245 D BreventServer: loaded brevent list
02-17 15:22:14.834 13230 13245 D BreventServer: loaded brevent conf
02-17 15:22:14.884 13230 13245 D BreventLoader: Can't run brevent server
02-17 15:22:14.884 13230 13245 D BreventLoader: java.lang.reflect.InvocationTarg
etException
02-17 15:22:14.884 13230 13245 D BreventLoader:         at java.lang.reflect.Met
hod.invoke(Native Method)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at me.piebridge.brevent.
loader.Brevent.run(Brevent.java:57)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at java.lang.Thread.run(
Thread.java:818)
02-17 15:22:14.884 13230 13245 D BreventLoader: Caused by: java.lang.NumberForma
tException: Invalid int: ""
02-17 15:22:14.884 13230 13245 D BreventLoader:         at java.lang.Integer.inv
alidInt(Integer.java:138)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at java.lang.Integer.par
seInt(Integer.java:358)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at java.lang.Integer.par
seInt(Integer.java:334)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at ku.g(HideApi.java:395
)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at ku.d(HideApi.java:362
)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at ku.a(HideApi.java:275
)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.k(BreventServer.java:696)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.a(BreventServer.java:684)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.<init>(BreventServer.java:133)
02-17 15:22:14.884 13230 13245 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.main(BreventServer.java:820)
02-17 15:22:14.884 13230 13245 D BreventLoader:         ... 3 more
02-17 15:22:14.884 13230 13230 D BreventLoader: Brevent Server quit in 30 second
s, quit
02-17 15:22:14.884 13230 13230 D BreventLoader: Can't remove /data/user/0/com.an
droid.shell/lib
```
--- brevent end ---

**Comment by dudukee** [comment]
S7 Active 6.0.1

**Comment by liudongmiao** [comment]
请帮忙提供一份 dumpsys activity activities 的输出，谢谢。

电脑指令：
```
adb -d shell dumpsys activity activities
```

**Comment by dudukee** [comment]
C:\Users\lenovo>adb -d shell dumpsys activity activities
ACTIVITY MANAGER ACTIVITIES (dumpsys activity activities)
Display #0 (activities from top to bottom):
  Stack #2:
    Task id #130
    * TaskRecord{2fbca80 #130 A=me.piebridge.brevent U=0 sz=1}
      userId=0 effectiveUid=u0a201 mCallingUid=u0a77 mCallingPackage=com.sec.and
roid.app.launcher
      affinity=me.piebridge.brevent
      intent={act=android.intent.action.MAIN cat=[android.intent.category.LAUNCH
ER] flg=0x10200000 cmp=me.piebridge.brevent/.ui.BreventActivity VirtualScreenPar
am=Params{mDisplayId=-1, null, mFlags=0x00000000)} bnds=[23,2048][371,2480]}
      realActivity=me.piebridge.brevent/.ui.BreventActivity
      autoRemoveRecents=false isPersistable=true numFullscreen=1 taskType=0 mTas
kToReturnTo=1
      rootWasReset=true mNeverRelinquishIdentity=true mReuseTask=false mLockTask
Auth=LOCK_TASK_AUTH_PINNABLE
      Activities=[ActivityRecord{9f7aeb7 u0 me.piebridge.brevent/.ui.BreventActi
vity t130}]
      askedCompatMode=false inRecents=true isAvailable=true
      lastThumbnail=android.graphics.Bitmap@be868b9 lastThumbnailFile=/data/syst
em/recent_images/130_task_thumbnail.png
      stackId=2
      hasBeenVisible=true mResizeable=false firstActiveTime=1487318632573 lastAc
tiveTime=1487318716060 lastActiveElapsedTime=8919477 (inactive for 11s)
      multiWindowStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x0000
0000, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, spe
cificTaskId=-1}
      bHidden=false
      isSecretMode=false
      * Hist #0: ActivityRecord{9f7aeb7 u0 me.piebridge.brevent/.ui.BreventActiv
ity t130}
          packageName=me.piebridge.brevent processName=me.piebridge.brevent
          launchedFromUid=10077 launchedFromPackage=com.sec.android.app.launcher
 userId=0
          app=ProcessRecord{94c85cb 15487:me.piebridge.brevent/u0a201}
          Intent { act=android.intent.action.MAIN cat=[android.intent.category.L
AUNCHER] flg=0x10200000 cmp=me.piebridge.brevent/.ui.BreventActivity VirtualScre
enParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} bnds=[23,2048][371,2480]
 (has extras) }
          frontOfTask=true task=TaskRecord{2fbca80 #130 A=me.piebridge.brevent U
=0 sz=1}
          taskAffinity=me.piebridge.brevent
          realActivity=me.piebridge.brevent/.ui.BreventActivity
          baseDir=/data/app/me.piebridge.brevent-1/base.apk
          dataDir=/data/user/0/me.piebridge.brevent
          stateNotNeeded=false componentSpecified=true mActivityType=0
          compat={640dpi} labelRes=0x7f08001d icon=0x7f030000 theme=0x7f0a0112
          config={0 1.0 themeSeq = 0 showBtnBg = 0 ?mcc?mnc zh_CN ldltr sw360dp
w360dp h616dp 640dpi nrml long port finger -keyb/v/h -nav/h mkbd/h s.4}
          stackConfigOverride={0 1.0 themeSeq = 0 showBtnBg = -1 ?mcc?mnc ?local
e ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?orien ?uimode ?night ?touch
?keyb/?/? ?nav/? mkbd/?}
          taskDescription: iconFilename=null label="null" color=ff212121
          launchFailed=false launchCount=0 lastLaunchTime=-1m35s207ms
          haveState=false icicle=null
          state=RESUMED stopped=false delayedResume=false finishing=false
          keysPaused=false inHistory=true visible=true sleeping=false idle=true
          fullscreen=true noDisplay=false immersive=false launchMode=0
          frozenBeforeDestroy=false forceNewConfig=false
          mActivityType=APPLICATION_ACTIVITY_TYPE
          waitingVisible=false nowVisible=true lastVisibleTime=-1m34s793ms
          multiWindowStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x
00000000, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0,
 specificTaskId=-1}
          bMultiInstance=false
          mIsLastShownWhenLocked=false
          virtualScreenAttrs=VirtualScreenAttrs{mDisplayId=0, mBaseDisplayId=0,
mBaseActivity=false}

    Running activities (most recent first):
      TaskRecord{2fbca80 #130 A=me.piebridge.brevent U=0 sz=1}
        Run #0: ActivityRecord{9f7aeb7 u0 me.piebridge.brevent/.ui.BreventActivi
ty t130}

    mResumedActivity: ActivityRecord{9f7aeb7 u0 me.piebridge.brevent/.ui.Brevent
Activity t130}
    mLastPausedActivity: ActivityRecord{9f7aeb7 u0 me.piebridge.brevent/.ui.Brev
entActivity t130}

  Stack #0:
    Task id #116
    * TaskRecord{eb4eb37 #116 A=com.sec.android.app.launcher U=0 sz=1}
      userId=0 effectiveUid=u0a77 mCallingUid=u0a74 mCallingPackage=com.android.
systemui
      affinity=com.sec.android.app.launcher
      intent={act=android.intent.action.MAIN cat=[android.intent.category.HOME]
flg=0x10800000 cmp=com.sec.android.app.launcher/com.android.launcher2.Launcher V
irtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)}}
      origActivity=com.sec.android.app.launcher/.activities.LauncherActivity
      realActivity=com.sec.android.app.launcher/com.android.launcher2.Launcher
      autoRemoveRecents=false isPersistable=false numFullscreen=1 taskType=1 mTa
skToReturnTo=1
      rootWasReset=false mNeverRelinquishIdentity=true mReuseTask=false mLockTas
kAuth=LOCK_TASK_AUTH_PINNABLE
      Activities=[ActivityRecord{2a2a94a u0 com.sec.android.app.launcher/.activi
ties.LauncherActivity t116}]
      askedCompatMode=false inRecents=true isAvailable=true
      lastThumbnail=null lastThumbnailFile=/data/system/recent_images/116_task_t
humbnail.png
      stackId=0
      hasBeenVisible=true mResizeable=false firstActiveTime=1487309896667 lastAc
tiveTime=1487318632573 lastActiveElapsedTime=8835990 (inactive for 95s)
      multiWindowStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x0000
0000, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, spe
cificTaskId=-1, or=1}
      bHidden=false
      isSecretMode=false
      * Hist #0: ActivityRecord{2a2a94a u0 com.sec.android.app.launcher/.activit
ies.LauncherActivity t116}
          packageName=com.sec.android.app.launcher processName=com.sec.android.a
pp.launcher
          launchedFromUid=0 launchedFromPackage=null userId=0
          app=ProcessRecord{17a3131 4658:com.sec.android.app.launcher/u0a77}
          Intent { act=android.intent.action.MAIN cat=[android.intent.category.H
OME] flg=0x10800000 cmp=com.sec.android.app.launcher/.activities.LauncherActivit
y VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} }
          frontOfTask=true task=TaskRecord{eb4eb37 #116 A=com.sec.android.app.la
uncher U=0 sz=1}
          taskAffinity=com.sec.android.app.launcher
          realActivity=com.sec.android.app.launcher/com.android.launcher2.Launch
er
          baseDir=/system/priv-app/TouchWizHome_2016/TouchWizHome_2016.apk
          dataDir=/data/user/0/com.sec.android.app.launcher
          stateNotNeeded=true componentSpecified=false mActivityType=1
          compat={640dpi} labelRes=0x7f070002 icon=0x7f02006d theme=0x7f0d0010
          config={0 1.0 themeSeq = 0 showBtnBg = 0 ?mcc?mnc zh_CN ldltr sw360dp
w360dp h616dp 640dpi nrml long port finger -keyb/v/h -nav/h mkbd/h s.4}
          stackConfigOverride={0 1.0 themeSeq = 0 showBtnBg = -1 ?mcc?mnc ?local
e ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?orien ?uimode ?night ?touch
?keyb/?/? ?nav/? mkbd/?}
          taskDescription: iconFilename=null label="null" color=ff51b0d3
          launchFailed=false launchCount=0 lastLaunchTime=-1h40m11s455ms
          haveState=true icicle=Bundle[mParcelledData.dataSize=16748]
          state=STOPPED stopped=true delayedResume=false finishing=false
          keysPaused=false inHistory=true visible=false sleeping=false idle=true

          fullscreen=true noDisplay=false immersive=false launchMode=2
          frozenBeforeDestroy=false forceNewConfig=false
          mActivityType=HOME_ACTIVITY_TYPE
          waitingVisible=false nowVisible=false lastVisibleTime=-1m37s626ms
          multiWindowStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x
00000000, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0,
 specificTaskId=-1, or=1}
          bMultiInstance=false
          mIsLastShownWhenLocked=false
          virtualScreenAttrs=VirtualScreenAttrs{mDisplayId=0, mBaseDisplayId=0,
mBaseActivity=false}

    Task id #125
    * TaskRecord{98c0fc6 #125 A=com.android.systemui U=0 sz=1}
      userId=0 effectiveUid=u0a74 mCallingUid=u0a74 mCallingPackage=com.android.
systemui
      affinity=com.android.systemui
      intent={flg=0x10800000 cmp=com.android.systemui/.recents.SeparatedRecentsA
ctivity VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} bnds=
[84,1673][1357,2946]}
      realActivity=com.android.systemui/.recents.SeparatedRecentsActivity
      autoRemoveRecents=false isPersistable=false numFullscreen=1 taskType=2 mTa
skToReturnTo=0
      rootWasReset=false mNeverRelinquishIdentity=true mReuseTask=false mLockTas
kAuth=LOCK_TASK_AUTH_PINNABLE
      Activities=[ActivityRecord{4ffc917 u0 com.android.systemui/.recents.Separa
tedRecentsActivity t125}]
      askedCompatMode=false inRecents=true isAvailable=true
      lastThumbnail=null lastThumbnailFile=/data/system/recent_images/125_task_t
humbnail.png
      stackId=0
      hasBeenVisible=true mResizeable=false firstActiveTime=1487316096805 lastAc
tiveTime=1487318629883 lastActiveElapsedTime=8833300 (inactive for 97s)
      multiWindowStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x0100
0002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, spe
cificTaskId=-1, or=3}
      bHidden=false
      isSecretMode=false
      * Hist #0: ActivityRecord{4ffc917 u0 com.android.systemui/.recents.Separat
edRecentsActivity t125}
          packageName=com.android.systemui processName=com.android.systemui.rece
nts
          launchedFromUid=10074 launchedFromPackage=com.android.systemui userId=
0
          app=ProcessRecord{9ff8612 4352:com.android.systemui.recents/u0a74}
          Intent { flg=0x10800000 cmp=com.android.systemui/.recents.SeparatedRec
entsActivity VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)}
bnds=[84,1673][1357,2946] }
          frontOfTask=true task=TaskRecord{98c0fc6 #125 A=com.android.systemui U
=0 sz=1}
          taskAffinity=com.android.systemui
          realActivity=com.android.systemui/.recents.SeparatedRecentsActivity
          baseDir=/system/priv-app/SystemUI/SystemUI.apk
          dataDir=/data/user/0/com.android.systemui
          stateNotNeeded=true componentSpecified=false mActivityType=2
          compat={640dpi} labelRes=0x7f0d0259 icon=0x7f020251 theme=0x7f100015
          config={0 1.0 themeSeq = 0 showBtnBg = 0 ?mcc?mnc zh_CN ldltr sw360dp
w360dp h616dp 640dpi nrml long port finger -keyb/v/h -nav/h mkbd/h s.4}
          stackConfigOverride={0 1.0 themeSeq = 0 showBtnBg = -1 ?mcc?mnc ?local
e ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?orien ?uimode ?night ?touch
?keyb/?/? ?nav/? mkbd/?}
          taskDescription: iconFilename=null label="null" color=fff5f5f5
          launchFailed=false launchCount=0 lastLaunchTime=-27m1s733ms
          haveState=true icicle=Bundle[mParcelledData.dataSize=1488]
          state=STOPPED stopped=true delayedResume=false finishing=false
          keysPaused=false inHistory=true visible=false sleeping=false idle=true

          fullscreen=true noDisplay=false immersive=false launchMode=3
          frozenBeforeDestroy=false forceNewConfig=false
          mActivityType=RECENTS_ACTIVITY_TYPE
          waitingVisible=false nowVisible=false lastVisibleTime=-1m38s418ms
          multiWindowStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x
01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0,
 specificTaskId=-1, or=3}
          bMultiInstance=false
          mIsLastShownWhenLocked=false
          virtualScreenAttrs=VirtualScreenAttrs{mDisplayId=0, mBaseDisplayId=0,
mBaseActivity=false}

    Running activities (most recent first):
      TaskRecord{eb4eb37 #116 A=com.sec.android.app.launcher U=0 sz=1}
        Run #1: ActivityRecord{2a2a94a u0 com.sec.android.app.launcher/.activiti
es.LauncherActivity t116}
      TaskRecord{98c0fc6 #125 A=com.android.systemui U=0 sz=1}
        Run #0: ActivityRecord{4ffc917 u0 com.android.systemui/.recents.Separate
dRecentsActivity t125}

    mLastPausedActivity: ActivityRecord{2a2a94a u0 com.sec.android.app.launcher/
.activities.LauncherActivity t116}
Display #1 (activities from top to bottom):

  mFocusedActivity: ActivityRecord{9f7aeb7 u0 me.piebridge.brevent/.ui.BreventAc
tivity t130}
  mPersistDownloadablePkgs:
    com.android.systemui
  mFocusedStack=ActivityStack{66303d3 stackId=2, 3 tasks} mLastFocusedStack=Acti
vityStack{66303d3 stackId=2, 3 tasks}
  mSleepTimeout=false
  mCurTaskId=130
  mUserStackInFront={}
  mActivityContainers={0=ActivtyContainer{0}A zone=0, 1=ActivtyContainer{1}A zon
e=0, 2=ActivtyContainer{2}A zone=0}
  mLockTaskModeState=NONE mLockTaskPackages (userId:packages)=
    0:[]
 mLockTaskModeTasks[]
  mCurrentUser=0

GlobalTaskHistory
  ActivityDisplay #1 (1440x2560)
  ActivityDisplay #0 (1440x2560)
    TASK id #130        u0      (Stack #2)      me.piebridge.brevent
    TASK id #116        u0      (Stack #0)      com.sec.android.app.launcher
    TASK id #125        u0      (Stack #0)      com.android.systemui

MultiWindow setting
  current

  history
    u0 history[0] - mobile_keyboard : true reason : prev

**Comment by liudongmiao** [comment]
请下载最新的测试版看看：http://piebridge.me/br/

**Comment by dudukee** [comment]
最新测试版br-v0.5-2-g5465cca.apk 解决了 , 多谢莴苣 .
