### ISSUE TITLE
Root 的机器安装了magisk之后不能用shell启动了

### ISSUE THREAD

**Issue by woodytian** [liudongmiao/Brevent#540]
我机器一直root，以前用boot shell 这软件执行sh命令可以运行，但是最近把supersu换成了magisk，然后就不能用了，已经给了root权限。
log如：
   WARNING: run as root is experimental!!!
checking for server...fail
please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-30 21:03:16.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-30 21:03:16.000' -d -s BreventLoader BreventServer
07-30 21:03:17.391 20541 20541 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-30 21:03:18.233 20562 20562 D BreventServer: get service: package
07-30 21:03:18.234 20562 20562 D BreventServer: args: [10]
07-30 21:03:18.234 20562 20562 I BreventServer: signal: 10
07-30 21:03:18.243 20562 20562 I BreventServer: starting Brevent Server 2.0.7a
07-30 21:03:18.254 20562 20562 D BreventServer: get service: package
07-30 21:03:18.255 20562 20562 I BreventServer: brevent user: 0, uid: 0
07-30 21:03:18.256 20562 20562 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-30 21:03:18.281 20562 20562 I BreventServer: loading brevent list
07-30 21:03:18.286 20562 20562 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 44
07-30 21:03:18.294 20562 20562 I BreventServer: loading brevent conf
07-30 21:03:18.297 20562 20562 D BreventServer: get service: appwidget
07-30 21:03:18.298 20562 20562 E BreventServer: Cannot dump appwidget(brevent dumpsys dead)
07-30 21:03:18.321 20541 20541 E BreventLoader: worker 20562 exited with status 1
07-30 21:03:18.321 20541 20541 D BreventLoader: signal arrived, update: 0
07-30 21:03:18.322 20537 20537 D BreventLoader: worker 20541 exited with status 0
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> please report bug to https://github.com/brevent/Brevent/issues with log below
