### ISSUE TITLE
正式版没有已经休眠。

### ISSUE THREAD

**Issue by cv0cv0** [liudongmiao/Brevent#55]
只有正在运行和没有运行，问过别人别人是有的。

**Comment by liudongmiao** [comment]
休眠需要你使用过应用，并且当前没有在使用。

一个典型场景：打开酷安，使用 BACK 退出，回到桌面，或者黑屏就会使它处于休眠状态。如果按 HOME 退出，过一段时间。如果从最近列表划掉，直接强行停止。
