### ISSUE TITLE
6.0 没有 android/app/ActivityManager$RecentTaskInfo realActivity

### ISSUE THREAD

**Issue by idongyou** [liudongmiao/Brevent#56]
checking.............

cannot listen port, please report bug

--- crash start ---

02-17 15:41:19.087   634   634 F libc    : page record for 0xf73f002c was not found (block_size=16)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-10

02-17 15:43:33.941  8361  8375 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	... 1 more

02-17 15:43:33.941  8361  8375 E AndroidRuntime: Caused by: java.lang.NoSuchFieldError: No instance field realActivity of type Landroid/content/ComponentName; in class Landroid/app/ActivityManager$RecentTaskInfo; or its superclasses (declaration of 'android.app.ActivityManager$RecentTaskInfo' appears in /system/framework/framework.jar)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	at ku.a(HideApi.java:460)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:329)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:227)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:820)

02-17 15:43:33.941  8361  8375 E AndroidRuntime: 	... 3 more

02-17 15:43:33.953  8361  8375 E AndroidRuntime: Error reporting crash

02-17 15:43:33.953  8361  8375 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor

02-17 15:43:33.953  8361  8375 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)

02-17 15:43:33.953  8361  8375 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)

02-17 15:43:33.953  8361  8375 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4429)

02-17 15:43:33.953  8361  8375 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:145)

02-17 15:43:33.953  8361  8375 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)

02-17 15:43:33.953  8361  8375 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

--- crash end ---

--- brevent start ---

02-17 15:43:33.581  8361  8361 D BreventLoader: lib: /data/user/0/com.android.shell/lib, loader: /data/user/0/com.android.shell/lib/libloader.so

02-17 15:43:33.665  8361  8375 D BreventServer: Brevent Server 0.5 started

02-17 15:43:33.677  8361  8375 D BreventServer: brevent user: 0, uid: 2000

02-17 15:43:33.679  8361  8375 D BreventServer: brevent data directory: /data/user/0/com.android.shell

02-17 15:43:33.757  8361  8375 D BreventServer: loaded brevent list

02-17 15:43:33.789  8361  8375 D BreventServer: loaded brevent conf

02-17 15:43:33.930  8361  8375 D BreventServer: checking

02-17 15:43:33.941  8361  8375 D BreventLoader: Can't run brevent server

02-17 15:43:33.941  8361  8375 D BreventLoader: java.lang.reflect.InvocationTargetException

02-17 15:43:33.941  8361  8375 D BreventLoader: 	at java.lang.reflect.Method.invoke(Native Method)

02-17 15:43:33.941  8361  8375 D BreventLoader: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)

02-17 15:43:33.941  8361  8375 D BreventLoader: 	at java.lang.Thread.run(Thread.java:818)

02-17 15:43:33.941  8361  8375 D BreventLoader: Caused by: java.lang.NoSuchFieldError: No instance field realActivity of type Landroid/content/ComponentName; in class Landroid/app/ActivityManager$RecentTaskInfo; or its superclasses (declaration of 'android.app.ActivityManager$RecentTaskInfo' appears in /system/framework/framework.jar)

02-17 15:43:33.941  8361  8375 D BreventLoader: 	at ku.a(HideApi.java:460)

02-17 15:43:33.941  8361  8375 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:329)

02-17 15:43:33.941  8361  8375 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:227)

02-17 15:43:33.941  8361  8375 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)

02-17 15:43:33.941  8361  8375 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:820)

02-17 15:43:33.941  8361  8375 D BreventLoader: 	... 3 more

02-17 15:43:33.941  8361  8361 D BreventLoader: Brevent Server quit in 30 seconds, quit

02-17 15:43:33.941  8361  8361 D BreventLoader: Can't remove /data/user/0/com.android.shell/lib

--- brevent end ---

**Comment by liudongmiao** [comment]
> No instance field realActivity of type Landroid/content/ComponentName; in class Landroid/app/ActivityManager$RecentTaskInfo

**Comment by liudongmiao** [comment]
请下载最新的测试版看看：http://piebridge.me/br/

**Comment by liudongmiao** [comment]
理论上，已经修复。
