### ISSUE TITLE
没有 getRecentTasks(III)Landroid/content/pm/ParceledListSlice 及 realActivity

### ISSUE THREAD

**Issue by sgxnew** [liudongmiao/Brevent#57]
--- crash start ---
02-17 13:28:01.129 10512 10512 E AndroidRuntime: FATAL EXCEPTION: main
02-17 13:28:01.129 10512 10512 E AndroidRuntime: Process: com.mediatek.selfregister, PID: 10512
02-17 13:28:01.129 10512 10512 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.mediatek.selfregister.RegisterService@b298aec with Intent { act=android.intent.action.SIM_STATE_CHANGED f
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3185)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.app.ActivityThread.access$2200(ActivityThread.java:180)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1573)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5710)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
02-17 13:28:01.129 10512 10512 E AndroidRuntime: Caused by: java.lang.SecurityException: Neither user 10088 nor current process has android.permission.ACCESS_COARSE_LOCATION.
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1599)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1552)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:614)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.telephony.TelephonyManager.listen(TelephonyManager.java:2914)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.telephony.TelephonyManager.listen(<Xposed>)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at com.mediatek.selfregister.utils.PlatformManager.registerPhoneListener(PlatformManager.java:429)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at com.mediatek.selfregister.RegisterService.registerPhoneListeners(RegisterService.java:306)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at com.mediatek.selfregister.RegisterService.onStartCommand(RegisterService.java:196)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3168)
02-17 13:28:01.129 10512 10512 E AndroidRuntime:        ... 9 more
02-17 13:28:13.399 11283 11457 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 11457 (MM_Thread_Pool_)
02-17 13:30:13.146 10219 13087 E AndroidRuntime: FATAL EXCEPTION: Thread-344
02-17 13:30:13.146 10219 13087 E AndroidRuntime: Process: com.mediatek.deviceregister, PID: 10219
02-17 13:30:13.146 10219 13087 E AndroidRuntime: java.lang.SecurityException: getSubscriberId: Neither user 10044 nor current process has android.permission.READ_PHONE_STATE.
02-17 13:30:13.146 10219 13087 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1599)
02-17 13:30:13.146 10219 13087 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1552)
02-17 13:30:13.146 10219 13087 E AndroidRuntime:        at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getSubscriberIdForSubscriber(IPhoneSubInfo.java:809)
02-17 13:30:13.146 10219 13087 E AndroidRuntime:        at android.telephony.TelephonyManager.getSubscriberId(TelephonyManager.java:2176)
02-17 13:30:13.146 10219 13087 E AndroidRuntime:        at com.mediatek.deviceregister.utils.PlatformManager.getImsiInfo(PlatformManager.java:431)
02-17 13:30:13.146 10219 13087 E AndroidRuntime:        at com.mediatek.deviceregister.utils.PlatformManager.getImsiFromSim(PlatformManager.java:406)
02-17 13:30:13.146 10219 13087 E AndroidRuntime:        at com.mediatek.deviceregister.RegisterService.needRegister(RegisterService.java:189)
02-17 13:30:13.146 10219 13087 E AndroidRuntime:        at com.mediatek.deviceregister.RegisterService.access$000(RegisterService.java:23)
02-17 13:30:13.146 10219 13087 E AndroidRuntime:        at com.mediatek.deviceregister.RegisterService$1.run(RegisterService.java:133)
02-17 13:34:12.821 14079 14092 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 13:34:12.821 14079 14092 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 13:34:12.821 14079 14092 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 13:34:12.821 14079 14092 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 13:34:12.821 14079 14092 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 13:34:12.821 14079 14092 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 13:34:12.821 14079 14092 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 13:34:12.821 14079 14092 E AndroidRuntime:        ... 1 more
02-17 13:34:12.821 14079 14092 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method getRecentTasks(III)Landroid/content/pm/ParceledListSlice; in class Landroid/app/IActivityManager; or
02-17 13:34:12.821 14079 14092 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:316)
02-17 13:34:12.821 14079 14092 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:221)
02-17 13:34:12.821 14079 14092 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:133)
02-17 13:34:12.821 14079 14092 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:808)
02-17 13:34:12.821 14079 14092 E AndroidRuntime:        ... 3 more
02-17 13:34:12.825 14079 14092 E AndroidRuntime: Error reporting crash
02-17 13:34:12.825 14079 14092 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 13:34:12.825 14079 14092 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 13:34:12.825 14079 14092 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:511)
02-17 13:34:12.825 14079 14092 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4603)
02-17 13:34:12.825 14079 14092 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:164)
02-17 13:34:12.825 14079 14092 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 13:34:12.825 14079 14092 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-17 15:23:11.997 25485 25498 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 15:23:11.997 25485 25498 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 15:23:11.997 25485 25498 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        ... 1 more
02-17 15:23:11.997 25485 25498 E AndroidRuntime: Caused by: java.lang.NoSuchFieldError: No instance field realActivity of type Landroid/content/ComponentName; in class Landroid/app/ActivityManager$RecentTaskInf
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        at ku.a(HideApi.java:460)
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:329)
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:227)
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:820)
02-17 15:23:11.997 25485 25498 E AndroidRuntime:        ... 3 more
02-17 15:23:12.004 25485 25498 E AndroidRuntime: Error reporting crash
02-17 15:23:12.004 25485 25498 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 15:23:12.004 25485 25498 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 15:23:12.004 25485 25498 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:511)
02-17 15:23:12.004 25485 25498 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4603)
02-17 15:23:12.004 25485 25498 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:164)
02-17 15:23:12.004 25485 25498 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 15:23:12.004 25485 25498 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-17 15:25:09.751 26380 26393 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 15:25:09.751 26380 26393 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 15:25:09.751 26380 26393 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        ... 1 more
02-17 15:25:09.751 26380 26393 E AndroidRuntime: Caused by: java.lang.NoSuchFieldError: No instance field realActivity of type Landroid/content/ComponentName; in class Landroid/app/ActivityManager$RecentTaskInf
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        at ku.a(HideApi.java:460)
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:329)
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:227)
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:820)
02-17 15:25:09.751 26380 26393 E AndroidRuntime:        ... 3 more
02-17 15:25:09.759 26380 26393 E AndroidRuntime: Error reporting crash
02-17 15:25:09.759 26380 26393 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 15:25:09.759 26380 26393 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 15:25:09.759 26380 26393 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:511)
02-17 15:25:09.759 26380 26393 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4603)
02-17 15:25:09.759 26380 26393 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:164)
02-17 15:25:09.759 26380 26393 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 15:25:09.759 26380 26393 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-17 15:26:12.469 26747 26762 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 15:26:12.469 26747 26762 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 15:26:12.469 26747 26762 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        ... 1 more
02-17 15:26:12.469 26747 26762 E AndroidRuntime: Caused by: java.lang.NoSuchFieldError: No instance field realActivity of type Landroid/content/ComponentName; in class Landroid/app/ActivityManager$RecentTaskInf
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        at ku.a(HideApi.java:460)
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:329)
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:227)
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:820)
02-17 15:26:12.469 26747 26762 E AndroidRuntime:        ... 3 more
02-17 15:26:12.470 26747 26762 E AndroidRuntime: Error reporting crash
02-17 15:26:12.470 26747 26762 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 15:26:12.470 26747 26762 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 15:26:12.470 26747 26762 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:511)
02-17 15:26:12.470 26747 26762 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4603)
02-17 15:26:12.470 26747 26762 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:164)
02-17 15:26:12.470 26747 26762 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 15:26:12.470 26747 26762 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
--- brevent end ---

**Comment by liudongmiao** [comment]
> No interface method getRecentTasks(III)Landroid/content/pm/ParceledListSlice; in class Landroid/app/IActivityManager

**Comment by liudongmiao** [comment]
与 #56 一样，应该已经修复，请下载。
