### ISSUE TITLE
Nexus 5 原生6.0系统  仍提示未打补丁

### ISSUE THREAD

**Issue by mengyyy** [liudongmiao/Brevent#6]
F:\hammerhead\Brevent>adb pull /system/framework
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
/system/framework/: 93 files pulled. 0... 3.2 MB/s (105793766 bytes in 31.860s)

F:\hammerhead\Brevent>java -Xms1g -jar baksmali-2.2b4.jar x -d F:\hammerhead\Bre
vent\framework\arm F:\hammerhead\Brevent\framework\oat\arm\services.odex -o serv
ices

F:\hammerhead\Brevent>java -Xms1g -jar baksmali-2.2b4.jar d F:\hammerhead\Breven
t\pr-v3.1.1.apk -o apk

F:\hammerhead\Brevent>python patch.py -a apk -s services
成功为 IntentResolver 打了 2 处补丁
成功为 ActivityStack 打了 3 处补丁
成功为 ActivityStackSupervisor 打了 1 处补丁
成功为 ActivityManagerService 打了 9 处补丁
正在复制 PreventRunning
正在复制 PreventRunningHook
正在复制 PreventRunningUtils

F:\hammerhead\Brevent>java -Xms1g -jar smali-2.2b4.jar a -o classes.dex services
F:\hammerhead\Brevent>"C:\Program Files\Java\jdk1.8.0_111\bin\jar.exe"  -cvf ser
vices.jar classes.dex
已添加清单
正在添加: classes.dex(输入 = 5409196) (输出 = 2424700)(压缩了 55%)

**Comment by aviraxp** [comment]
删除services.odex

**Comment by mengyyy** [comment]
删除了/framework/oat/arm/services.odex   问题 依旧

**Comment by liudongmiao** [comment]
1. 删除 **手机** 里 /system/framework 下所有的 services.odex 
2. 安装黑域到 `/data/app` (`adb shell pm path me.piebridge.prevent`)，目前只支持特定的几个目录
    - /data/app/me.piebridge.prevent-1/base.apk
    - /data/app/me.piebridge.prevent-2/base.apk
    - /data/app/me.piebridge.prevent-3/base.apk
    - 以及其它老式的位置

**Comment by zinian** [comment]
可能需要重启一至两次。。。。清理  /date/dalvik-cache
