### ISSUE TITLE
cannot listen port

### ISSUE THREAD

**Issue by idongyou** [liudongmiao/Brevent#60]
checking.............

cannot listen port, please report bug

--- crash start ---

01-02 13:17:44.203   577   577 F libc    : page record for 0xf71ee02c was not found (block_size=16)

--- crash end ---

--- brevent start ---

02-17 18:19:01.727  8261  8261 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so

02-17 18:19:01.808  8261  8276 D BreventServer: Brevent Server 0.5-2-g5465cca started

02-17 18:19:01.816  8261  8276 D BreventServer: brevent user: 0, uid: 2000

02-17 18:19:01.817  8261  8276 D BreventServer: brevent data directory: /data/user/0/com.android.shell

02-17 18:19:01.928  8261  8276 D BreventServer: loaded brevent list

02-17 18:19:01.931  8261  8276 D BreventServer: loaded brevent conf

02-17 18:19:02.074  8261  8276 D BreventServer: checking

02-17 18:19:02.277  8261  8276 I BreventServer: power_screen_state, tag: 2728, event: 7

02-17 18:19:02.278  8261  8276 I BreventServer: notification_cancel_all, tag: 2752, event: 6

02-17 18:19:02.281  8261  8276 I BreventServer: am_new_intent, tag: 30003, event: 2

02-17 18:19:02.283  8261  8276 I BreventServer: am_pause_activity, tag: 30013, event: 3

02-17 18:19:02.284  8261  8276 I BreventServer: am_proc_start, tag: 30014, event: 4

02-17 18:19:02.285  8261  8276 I BreventServer: am_switch_user, tag: 30041, event: 5

02-17 18:19:02.285  8261  8276 I BreventServer: am_focused_activity, tag: 30043, event: 1

02-17 18:19:46.618  8547  8547 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so

02-17 18:19:46.684  8547  8562 D BreventServer: Brevent Server 0.5-2-g5465cca started

02-17 18:19:46.694  8547  8562 D BreventServer: brevent user: 0, uid: 2000

02-17 18:19:46.696  8547  8562 D BreventServer: brevent data directory: /data/user/0/com.android.shell

02-17 18:19:46.758  8547  8562 D BreventServer: loaded brevent list

02-17 18:19:46.761  8547  8562 D BreventServer: loaded brevent conf

02-17 18:19:46.926  8547  8562 D BreventServer: checking

02-17 18:19:47.121  8547  8562 I BreventServer: power_screen_state, tag: 2728, event: 7

02-17 18:19:47.122  8547  8562 I BreventServer: notification_cancel_all, tag: 2752, event: 6

02-17 18:19:47.125  8547  8562 I BreventServer: am_new_intent, tag: 30003, event: 2

02-17 18:19:47.126  8547  8562 I BreventServer: am_pause_activity, tag: 30013, event: 3

02-17 18:19:47.126  8547  8562 I BreventServer: am_proc_start, tag: 30014, event: 4

02-17 18:19:47.127  8547  8562 I BreventServer: am_switch_user, tag: 30041, event: 5

02-17 18:19:47.128  8547  8562 I BreventServer: am_focused_activity, tag: 30043, event: 1

--- brevent end ---

**Comment by liudongmiao** [comment]
if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

请重新获取一份日志，这份日志数据不够。
