### ISSUE TITLE
 成功进入应用内，如果在应用内多操作几个app进行黑域，app提示重新adb

### ISSUE THREAD

**Issue by rookiedong521** [liudongmiao/Brevent#61]
成功进入应用内，如果在应用内多操作几个app进行黑域，app提示重新adb，试了好多次，一直会出现这个问题。机型小米5s，miui8

**Comment by liudongmiao** [comment]
if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer
