### ISSUE TITLE
用着好好的，突然就要重新adb - 无权限 setPackageStoppedState

### ISSUE THREAD

**Issue by 849506054** [liudongmiao/Brevent#62]
基本上待机几分钟，打开黑域看一下就提示要adb

**Comment by 849506054** [comment]
重新打了几次，然后就又不行了.......好气。再次尝试，再次失败

shell@OnePlus3:/ $ /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
/data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
checking.............
cannot listen port, please report bug
--- crash start ---
02-17 21:52:07.967  5091  5104 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 21:52:07.967  5091  5104 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 21:52:07.967  5091  5104 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        ... 1 more
02-17 21:52:07.967  5091  5104 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: attempt to change stopped state from pid=5091, uid=2000, package uid=10083
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4151)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at ku.a(HideApi.java:157)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:600)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:303)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.handleMessage(BreventServer.java:209)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:833)
02-17 21:52:07.967  5091  5104 E AndroidRuntime:        ... 3 more
02-17 21:52:07.968  5091  5104 E AndroidRuntime: Error reporting crash
02-17 21:52:07.968  5091  5104 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 21:52:07.968  5091  5104 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 21:52:07.968  5091  5104 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:536)
02-17 21:52:07.968  5091  5104 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4646)
02-17 21:52:07.968  5091  5104 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
02-17 21:52:07.968  5091  5104 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 21:52:07.968  5091  5104 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-17 21:54:14.807  5368  5381 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 21:54:14.807  5368  5381 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 21:54:14.807  5368  5381 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        ... 1 more
02-17 21:54:14.807  5368  5381 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: attempt to change stopped state from pid=5368, uid=2000, package uid=10083
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4151)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at ku.a(HideApi.java:157)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:600)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:303)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.handleMessage(BreventServer.java:209)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:833)
02-17 21:54:14.807  5368  5381 E AndroidRuntime:        ... 3 more
02-17 21:54:14.808  5368  5381 E AndroidRuntime: Error reporting crash
02-17 21:54:14.808  5368  5381 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 21:54:14.808  5368  5381 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 21:54:14.808  5368  5381 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:536)
02-17 21:54:14.808  5368  5381 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4646)
02-17 21:54:14.808  5368  5381 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
02-17 21:54:14.808  5368  5381 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 21:54:14.808  5368  5381 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-17 22:00:29.221  5618  5631 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 22:00:29.221  5618  5631 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 22:00:29.221  5618  5631 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        ... 1 more
02-17 22:00:29.221  5618  5631 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: attempt to change stopped state from pid=5618, uid=2000, package uid=10002
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4151)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at ku.a(HideApi.java:157)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:600)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:303)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.handleMessage(BreventServer.java:209)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:833)
02-17 22:00:29.221  5618  5631 E AndroidRuntime:        ... 3 more
02-17 22:06:29.856  7039  7052 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 22:06:29.856  7039  7052 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 22:06:29.856  7039  7052 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        ... 1 more
02-17 22:06:29.856  7039  7052 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: attempt to change stopped state from pid=7039, uid=2000, package uid=10002
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4151)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at ku.a(HideApi.java:157)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:600)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:255)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.handleMessage(BreventServer.java:209)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:833)
02-17 22:06:29.856  7039  7052 E AndroidRuntime:        ... 3 more
02-17 22:13:16.041  9257  9270 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 22:13:16.041  9257  9270 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 22:13:16.041  9257  9270 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        ... 1 more
02-17 22:13:16.041  9257  9270 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: attempt to change stopped state from pid=9257, uid=2000, package uid=10002
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4151)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at ku.a(HideApi.java:157)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:600)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:303)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:822)
02-17 22:13:16.041  9257  9270 E AndroidRuntime:        ... 3 more
02-17 22:13:16.045  9257  9270 E AndroidRuntime: Error reporting crash
02-17 22:13:16.045  9257  9270 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 22:13:16.045  9257  9270 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 22:13:16.045  9257  9270 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:536)
02-17 22:13:16.045  9257  9270 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4646)
02-17 22:13:16.045  9257  9270 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
02-17 22:13:16.045  9257  9270 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 22:13:16.045  9257  9270 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-17 22:13:50.525  9492  9505 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 22:13:50.525  9492  9505 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 22:13:50.525  9492  9505 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        ... 1 more
02-17 22:13:50.525  9492  9505 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: attempt to change stopped state from pid=9492, uid=2000, package uid=10111
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4151)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at ku.a(HideApi.java:157)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:600)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:303)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:822)
02-17 22:13:50.525  9492  9505 E AndroidRuntime:        ... 3 more
02-17 22:13:50.529  9492  9505 E AndroidRuntime: Error reporting crash
02-17 22:13:50.529  9492  9505 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 22:13:50.529  9492  9505 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 22:13:50.529  9492  9505 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:536)
02-17 22:13:50.529  9492  9505 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4646)
02-17 22:13:50.529  9492  9505 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
02-17 22:13:50.529  9492  9505 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 22:13:50.529  9492  9505 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-17 22:17:29.564  9990 10003 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 22:17:29.564  9990 10003 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 22:17:29.564  9990 10003 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        ... 1 more
02-17 22:17:29.564  9990 10003 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: attempt to change stopped state from pid=9990, uid=2000, package uid=10002
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4151)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at ku.a(HideApi.java:157)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:600)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:303)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:822)
02-17 22:17:29.564  9990 10003 E AndroidRuntime:        ... 3 more
02-17 22:17:29.568  9990 10003 E AndroidRuntime: Error reporting crash
02-17 22:17:29.568  9990 10003 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 22:17:29.568  9990 10003 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 22:17:29.568  9990 10003 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:536)
02-17 22:17:29.568  9990 10003 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4646)
02-17 22:17:29.568  9990 10003 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
02-17 22:17:29.568  9990 10003 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 22:17:29.568  9990 10003 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
02-17 22:13:15.767  9257  9257 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-17 22:13:15.802  9257  9270 D BreventServer: Brevent Server 0.5-2-g5465cca started
02-17 22:13:15.811  9257  9270 D BreventServer: brevent user: 0, uid: 2000
02-17 22:13:15.812  9257  9270 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-17 22:13:15.883  9257  9270 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 3
02-17 22:13:15.883  9257  9270 D BreventServer: loaded brevent list
02-17 22:13:15.886  9257  9270 D BreventServer: loaded brevent conf
02-17 22:13:15.933  9257  9270 D BreventServer: checking
02-17 22:13:16.040  9257  9270 D BreventLoader: Can't run brevent server
02-17 22:13:16.040  9257  9270 D BreventLoader: java.lang.reflect.InvocationTargetException
02-17 22:13:16.040  9257  9270 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-17 22:13:16.040  9257  9270 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 22:13:16.040  9257  9270 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-17 22:13:16.040  9257  9270 D BreventLoader: Caused by: java.lang.SecurityException: Permission Denial: attempt to change stopped state from pid=9257, uid=2000, package uid=10002
02-17 22:13:16.040  9257  9270 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1620)
02-17 22:13:16.040  9257  9270 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1573)
02-17 22:13:16.040  9257  9270 D BreventLoader:         at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4151)
02-17 22:13:16.040  9257  9270 D BreventLoader:         at ku.a(HideApi.java:157)
02-17 22:13:16.040  9257  9270 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:600)
02-17 22:13:16.040  9257  9270 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:303)
02-17 22:13:16.040  9257  9270 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 22:13:16.040  9257  9270 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:822)
02-17 22:13:16.040  9257  9270 D BreventLoader:         ... 3 more
02-17 22:13:16.041  9257  9257 D BreventLoader: Brevent Server quit in 30 seconds, quit
02-17 22:13:16.042  9257  9257 D BreventLoader: Can't remove /data/user/0/com.android.shell/brevent
02-17 22:13:49.904  9492  9492 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-17 22:13:49.941  9492  9505 D BreventServer: Brevent Server 0.5-2-g5465cca started
02-17 22:13:49.950  9492  9505 D BreventServer: brevent user: 0, uid: 2000
02-17 22:13:49.952  9492  9505 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-17 22:13:50.014  9492  9505 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 3
02-17 22:13:50.014  9492  9505 D BreventServer: loaded brevent list
02-17 22:13:50.015  9492  9505 D BreventServer: loaded brevent conf
02-17 22:13:50.246  9492  9505 D BreventServer: checking
02-17 22:13:50.524  9492  9505 D BreventLoader: Can't run brevent server
02-17 22:13:50.524  9492  9505 D BreventLoader: java.lang.reflect.InvocationTargetException
02-17 22:13:50.524  9492  9505 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-17 22:13:50.524  9492  9505 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 22:13:50.524  9492  9505 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-17 22:13:50.524  9492  9505 D BreventLoader: Caused by: java.lang.SecurityException: Permission Denial: attempt to change stopped state from pid=9492, uid=2000, package uid=10111
02-17 22:13:50.524  9492  9505 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1620)
02-17 22:13:50.524  9492  9505 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1573)
02-17 22:13:50.524  9492  9505 D BreventLoader:         at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4151)
02-17 22:13:50.524  9492  9505 D BreventLoader:         at ku.a(HideApi.java:157)
02-17 22:13:50.524  9492  9505 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:600)
02-17 22:13:50.524  9492  9505 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:303)
02-17 22:13:50.524  9492  9505 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 22:13:50.524  9492  9505 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:822)
02-17 22:13:50.524  9492  9505 D BreventLoader:         ... 3 more
02-17 22:13:50.525  9492  9492 D BreventLoader: Brevent Server quit in 30 seconds, quit
02-17 22:13:50.525  9492  9492 D BreventLoader: Can't remove /data/user/0/com.android.shell/brevent
02-17 22:17:29.016  9990  9990 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-17 22:17:29.056  9990 10003 D BreventServer: Brevent Server 0.5-2-g5465cca started
02-17 22:17:29.065  9990 10003 D BreventServer: brevent user: 0, uid: 2000
02-17 22:17:29.068  9990 10003 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-17 22:17:29.133  9990 10003 I BreventServer: load /data/user/0/com.android.shell/me.piebridge.brevent.list, size: 3
02-17 22:17:29.134  9990 10003 D BreventServer: loaded brevent list
02-17 22:17:29.135  9990 10003 D BreventServer: loaded brevent conf
02-17 22:17:29.305  9990 10003 D BreventServer: checking
02-17 22:17:29.564  9990 10003 D BreventLoader: Can't run brevent server
02-17 22:17:29.564  9990 10003 D BreventLoader: java.lang.reflect.InvocationTargetException
02-17 22:17:29.564  9990 10003 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-17 22:17:29.564  9990 10003 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 22:17:29.564  9990 10003 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-17 22:17:29.564  9990 10003 D BreventLoader: Caused by: java.lang.SecurityException: Permission Denial: attempt to change stopped state from pid=9990, uid=2000, package uid=10002
02-17 22:17:29.564  9990 10003 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1620)
02-17 22:17:29.564  9990 10003 D BreventLoader:         at android.os.Parcel.readException(Parcel.java:1573)
02-17 22:17:29.564  9990 10003 D BreventLoader:         at android.content.pm.IPackageManager$Stub$Proxy.setPackageStoppedState(IPackageManager.java:4151)
02-17 22:17:29.564  9990 10003 D BreventLoader:         at ku.a(HideApi.java:157)
02-17 22:17:29.564  9990 10003 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:600)
02-17 22:17:29.564  9990 10003 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:303)
02-17 22:17:29.564  9990 10003 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 22:17:29.564  9990 10003 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:822)
02-17 22:17:29.564  9990 10003 D BreventLoader:         ... 3 more
02-17 22:17:29.564  9990  9990 D BreventLoader: Brevent Server quit in 30 seconds, quit
02-17 22:17:29.565  9990  9990 D BreventLoader: Can't remove /data/user/0/com.android.shell/brevent
--- brevent end ---

**Comment by 849506054** [comment]
重启之后可以执行adb可以打开，然后，重复上述情况

**Comment by liudongmiao** [comment]
你的shell居然没有权限setPackageStoppedState……

**Comment by liudongmiao** [comment]
下个版本忽视这个异常

**Comment by 849506054** [comment]
测试下了0.6.1版，貌似正常了。
继续观望，看看是否正常处理
