### ISSUE TITLE
cannot listen port,

### ISSUE THREAD

**Issue by jeromeyycp** [liudongmiao/Brevent#63]
cannot listen port, please report bug
--- crash start ---
02-17 06:57:53.072   972   989 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-17 06:57:53.072   972   989 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 06:57:53.072   972   989 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 06:57:53.072   972   989 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 06:57:53.072   972   989 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 06:57:53.072   972   989 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 06:57:53.072   972   989 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 06:57:53.072   972   989 E AndroidRuntime:        ... 1 more
02-17 06:57:53.072   972   989 E AndroidRuntime: Caused by: java.lang.NoSuchFieldError: No instance field realActivity of type Landroid/content/ComponentName; in class Landroid/app/ActivityManager$RecentTaskInfo; or its superclasses (declaration of 'android.app.ActivityManager$RecentTaskInfo' appears in /system/framework/framework.jar)
02-17 06:57:53.072   972   989 E AndroidRuntime:        at ku.a(HideApi.java:460)
02-17 06:57:53.072   972   989 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:329)
02-17 06:57:53.072   972   989 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:227)
02-17 06:57:53.072   972   989 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 06:57:53.072   972   989 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:820)
02-17 06:57:53.072   972   989 E AndroidRuntime:        ... 3 more
02-17 06:57:53.075   972   989 E AndroidRuntime: Error reporting crash
02-17 06:57:53.075   972   989 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 06:57:53.075   972   989 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 06:57:53.075   972   989 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
02-17 06:57:53.075   972   989 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4505)
02-17 06:57:53.075   972   989 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
02-17 06:57:53.075   972   989 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 06:57:53.075   972   989 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-17 06:57:56.329 31289 31289 E AndroidRuntime: FATAL EXCEPTION: main
02-17 06:57:56.329 31289 31289 E AndroidRuntime: Process: me.piebridge.brevent, PID: 31289
02-17 06:57:56.329 31289 31289 E AndroidRuntime: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1413)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1431)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.app.BackStackRecord.commit(BackStackRecord.java:663)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.app.DialogFragment.dismissInternal(DialogFragment.java:301)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.app.DialogFragment.dismiss(DialogFragment.java:267)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at me.piebridge.brevent.ui.BreventActivity.i(BreventActivity.java:220)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at me.piebridge.brevent.ui.BreventActivity.d(BreventActivity.java:214)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at lg.a(AppsInfoTask.java:64)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at lg.onPostExecute(AppsInfoTask.java:18)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:651)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.os.AsyncTask.access$500(AsyncTask.java:180)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5459)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
02-17 06:57:56.329 31289 31289 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
02-17 06:58:49.720  2139  2155 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-10
02-17 06:58:49.720  2139  2155 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 06:58:49.720  2139  2155 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        ... 1 more
02-17 06:58:49.720  2139  2155 E AndroidRuntime: Caused by: java.lang.NoSuchFieldError: No instance field realActivity of type Landroid/content/ComponentName; in class Landroid/app/ActivityManager$RecentTaskInfo; or its superclasses (declaration of 'android.app.ActivityManager$RecentTaskInfo' appears in /system/framework/framework.jar)
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        at ku.a(HideApi.java:460)
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:329)
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:227)
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:820)
02-17 06:58:49.720  2139  2155 E AndroidRuntime:        ... 3 more
02-17 06:58:49.727  2139  2155 E AndroidRuntime: Error reporting crash
02-17 06:58:49.727  2139  2155 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 06:58:49.727  2139  2155 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 06:58:49.727  2139  2155 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
02-17 06:58:49.727  2139  2155 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4505)
02-17 06:58:49.727  2139  2155 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
02-17 06:58:49.727  2139  2155 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 06:58:49.727  2139  2155 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-17 07:07:28.500  3782  3794 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-10
02-17 07:07:28.500  3782  3794 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-17 07:07:28.500  3782  3794 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        ... 1 more
02-17 07:07:28.500  3782  3794 E AndroidRuntime: Caused by: java.lang.NoSuchFieldError: No instance field realActivity of type Landroid/content/ComponentName; in class Landroid/app/ActivityManager$RecentTaskInfo; or its superclasses (declaration of 'android.app.ActivityManager$RecentTaskInfo' appears in /system/framework/framework.jar)
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        at ku.a(HideApi.java:460)
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:329)
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:227)
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:820)
02-17 07:07:28.500  3782  3794 E AndroidRuntime:        ... 3 more
02-17 07:07:28.502  3782  3794 E AndroidRuntime: Error reporting crash
02-17 07:07:28.502  3782  3794 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 07:07:28.502  3782  3794 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-17 07:07:28.502  3782  3794 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
02-17 07:07:28.502  3782  3794 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4505)
02-17 07:07:28.502  3782  3794 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
02-17 07:07:28.502  3782  3794 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-17 07:07:28.502  3782  3794 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
02-17 07:07:28.269  3782  3782 D BreventLoader: lib: /data/user/0/com.android.shell/lib, loader: /data/user/0/com.android.shell/lib/libloader.so
02-17 07:07:28.313  3782  3794 D BreventServer: Brevent Server 0.5 started
02-17 07:07:28.320  3782  3794 D BreventServer: brevent user: 0, uid: 2000
02-17 07:07:28.321  3782  3794 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-17 07:07:28.399  3782  3794 D BreventServer: loaded brevent list
02-17 07:07:28.399  3782  3794 D BreventServer: loaded brevent conf
02-17 07:07:28.475  3782  3794 D BreventServer: checking
02-17 07:07:28.499  3782  3794 D BreventLoader: Can't run brevent server
02-17 07:07:28.499  3782  3794 D BreventLoader: java.lang.reflect.InvocationTargetException
02-17 07:07:28.499  3782  3794 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-17 07:07:28.499  3782  3794 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 07:07:28.499  3782  3794 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-17 07:07:28.499  3782  3794 D BreventLoader: Caused by: java.lang.NoSuchFieldError: No instance field realActivity of type Landroid/content/ComponentName; in class Landroid/app/ActivityManager$RecentTaskInfo; or its superclasses (declaration of 'android.app.ActivityManager$RecentTaskInfo' appears in /system/framework/framework.jar)
02-17 07:07:28.499  3782  3794 D BreventLoader:         at ku.a(HideApi.java:460)
02-17 07:07:28.499  3782  3794 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:329)
02-17 07:07:28.499  3782  3794 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.c(BreventServer.java:227)
02-17 07:07:28.499  3782  3794 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:135)
02-17 07:07:28.499  3782  3794 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:820)
02-17 07:07:28.499  3782  3794 D BreventLoader:         ... 3 more
02-17 07:07:28.501  3782  3782 D BreventLoader: Brevent Server quit in 30 seconds, quit
02-17 07:07:28.501  3782  3782 D BreventLoader: Can't remove /data/user/0/com.android.shell/lib

**Comment by liudongmiao** [comment]
请使用 0.5-2

**Comment by liudongmiao** [comment]
同 #56 应该已经修复
