### ISSUE TITLE
索尼xz系统6.0.1无法使用

### ISSUE THREAD

**Issue by zouyezaici** [liudongmiao/Brevent#65]
[通过cmd执行第一步没问题 第二部执行之后出现checking   之后显示-----brevent  end------

**Comment by liudongmiao** [comment]
需要更多日志，特别是 crash 中间的日志，brevent 中间的日志。

**Comment by liudongmiao** [comment]
if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer
