### ISSUE TITLE
按back需要重新adb

### ISSUE THREAD

**Issue by wocala** [liudongmiao/Brevent#66]
新问题。。。
adb结束显示checking....successfully，可以正常使用。但按back后再重新进入就提示please start brevent service。试了好几次了，不知道为啥。
android6.0.1，未root。测试版br-v0.5-2-g5465cca.apk

**Comment by wocala** [comment]
尝试了酷安污点证人的建议，成功了。
![image](https://cloud.githubusercontent.com/assets/10202658/23090455/a43b07b6-f5d9-11e6-9e2c-884523c22cf8.png)

**Comment by wocala** [comment]
呃，收回我刚说的话，又需要重新授权了。。。。

**Comment by liudongmiao** [comment]
if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer
