### ISSUE TITLE
每次打开黑域都要求手动再次输入adb命令开启黑域

### ISSUE THREAD

**Issue by jackplus** [liudongmiao/Brevent#67]
是否可以能够授权一次就直接可用？

**Comment by jackplus** [comment]
而且没有办法把app添加到黑域，点击按钮无任何反应…
Android7.1 Nexus6P

**Comment by liudongmiao** [comment]
肯定是这样设计的。请提供日志。

if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer
