### ISSUE TITLE
意见 - 多任务划掉时处理 - 答复：有

### ISSUE THREAD

**Issue by aliuselly** [liudongmiao/Brevent#70]
希望有以前的从最近任务里划掉进程就立刻或者几秒后就被杀掉

**Comment by liudongmiao** [comment]
现在也有啊，你划掉试试..?

不过现在处理起来，不是划掉这个瞬间，而是你划掉以后，回到桌面，或者打开其他应用。

https://github.com/liudongmiao/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/server/BreventServer.java#L96

这里定义了，处理事件的时间。另外，真的请阅读下那四屏说明。
