### ISSUE TITLE
软件闪退 - 新装应用无法打开，0.6.1 中修复

### ISSUE THREAD

**Issue by idongyou** [liudongmiao/Brevent#71]
02-18 20:37:03.837   681   681 F libc    : page record for 0xf75ae02c was not found (block_size=16)
02-18 20:38:46.961  9603  9603 E AndroidRuntime: FATAL EXCEPTION: main
02-18 20:38:46.961  9603  9603 E AndroidRuntime: Process: me.piebridge.brevent, PID: 9603
02-18 20:38:46.961  9603  9603 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {me.piebridge.brevent/me.piebridge.brevent.ui.BreventActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.os.Handler.getLooper()' on a null object reference
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3838)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3856)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at android.app.ActivityThread.access$1500(ActivityThread.java:153)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5441)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
02-18 20:38:46.961  9603  9603 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.os.Handler.getLooper()' on a null object reference
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at me.piebridge.brevent.ui.BreventActivity.onDestroy(BreventActivity.java:255)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at android.app.Activity.performDestroy(Activity.java:6474)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3825)
02-18 20:38:46.961  9603  9603 E AndroidRuntime:        ... 10 more

**Comment by liudongmiao** [comment]
0.6 应该修复了。

**Comment by liudongmiao** [comment]
囧，才发就出问题，请稍等下 0.6.1
