### ISSUE TITLE
可正常使用App无法阻止 - 没有网络权限

### ISSUE THREAD

**Issue by CrazyMan1226** [liudongmiao/Brevent#72]
C:\Users\a>adb -d shell
7[r[999;999H[6n8heroltexx:/ #
/*/libbootstrap.so; if ls $file >/dev/null 2>&1; then $file; break; fi; done  <
please run with 'su shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so'
ata/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so                        <
checking.............
cannot listen port, please report bug
--- crash start ---
02-18 20:46:25.798 11421 11433 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-1
02-18 20:46:25.798 11421 11433 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
02-18 20:46:25.798 11421 11433 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        ... 1 more
02-18 20:46:25.798 11421 11433 E AndroidRuntime: Caused by: java.net.SocketException: Permission denied
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        at java.net.ServerSocket.bind(ServerSocket.java:377)
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:829)
02-18 20:46:25.798 11421 11433 E AndroidRuntime:        ... 3 more
02-18 20:46:25.800 11421 11433 E AndroidRuntime: Error reporting crash
02-18 20:46:25.800 11421 11433 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-18 20:46:25.800 11421 11433 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-18 20:46:25.800 11421 11433 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
02-18 20:46:25.800 11421 11433 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5163)
02-18 20:46:25.800 11421 11433 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
02-18 20:46:25.800 11421 11433 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-18 20:46:25.800 11421 11433 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
02-18 20:46:25.332 11421 11421 D BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
02-18 20:46:25.334 11421 11433 D BreventServer: Brevent Server 0.5-2-g5465cca started
02-18 20:46:25.339 11421 11433 D BreventServer: brevent user: 0, uid: 2000
02-18 20:46:25.341 11421 11433 D BreventServer: brevent data directory: /data/user_de/0/com.android.shell
02-18 20:46:25.403 11421 11433 D BreventServer: loaded brevent list
02-18 20:46:25.403 11421 11433 D BreventServer: loaded brevent conf
02-18 20:46:25.551 11421 11433 D BreventServer: checking
02-18 20:46:25.774 11421 11433 I BreventServer: power_screen_state, tag: 2728, event: 7
02-18 20:46:25.777 11421 11433 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-18 20:46:25.783 11421 11433 I BreventServer: am_new_intent, tag: 30003, event: 2
02-18 20:46:25.785 11421 11433 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-18 20:46:25.785 11421 11433 I BreventServer: am_proc_start, tag: 30014, event: 4
02-18 20:46:25.786 11421 11433 I BreventServer: am_switch_user, tag: 30041, event: 5
02-18 20:46:25.787 11421 11433 I BreventServer: am_focused_activity, tag: 30043, event: 1
02-18 20:46:25.798 11421 11433 D BreventLoader: Can't run brevent server
02-18 20:46:25.798 11421 11433 D BreventLoader: java.lang.reflect.InvocationTargetException
02-18 20:46:25.798 11421 11433 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-18 20:46:25.798 11421 11433 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-18 20:46:25.798 11421 11433 D BreventLoader:         at java.lang.Thread.run(Thread.java:761)
02-18 20:46:25.798 11421 11433 D BreventLoader: Caused by: java.net.SocketException: Permission denied
02-18 20:46:25.798 11421 11433 D BreventLoader:         at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-18 20:46:25.798 11421 11433 D BreventLoader:         at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-18 20:46:25.798 11421 11433 D BreventLoader:         at java.net.ServerSocket.bind(ServerSocket.java:377)
02-18 20:46:25.798 11421 11433 D BreventLoader:         at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-18 20:46:25.798 11421 11433 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:829)
02-18 20:46:25.798 11421 11433 D BreventLoader:         ... 3 more
02-18 20:46:25.799 11421 11421 D BreventLoader: Brevent Server quit in 30 seconds, quit
02-18 20:46:25.799 11421 11421 D BreventLoader: Can't remove /data/user_de/0/com.android.shell/brevent
--- brevent end ---

**Comment by liudongmiao** [comment]
没有网络权限，同 #50

**Comment by liudongmiao** [comment]
什么 ROM ?

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
