### ISSUE TITLE
一加一omni ROM7.1.1。 0.6.1 没有网络权限

### ISSUE THREAD

**Issue by wangyou** [liudongmiao/Brevent#73]
A0001:/ $ su
A0001:/ # adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/libbootsata/app/me.piebridge.brevent-1/lib/arm/libbootstrap.s                   o     <
* daemon not running. starting it now on port 5038 *
* daemon started successfully *
error: no devices found
1|A0001:/ # su
A0001:/ # for x in 1 2 3; do file=/data/app/me.piebridge.brevent-$x/lib/ do file=/data/app/me.piebridge.brevent-$x/lib/*/libb                   bridge.brevent-$x/lib/*/libbootstrap.so; if ls $file                    ibbootstrap.so; if ls $file >/dev/null 2>&1; then $fi                   le; break; fi; done
please run with 'su shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so'
A0001:/ # su ahell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
Unknown id: ahell
1|A0001:/ # su
A0001:/ # su shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
checking.............
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
02-18 22:13:55.902 15491 15607 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-1
02-18 22:13:55.902 15491 15607 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
02-18 22:13:55.902 15491 15607 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        ... 1 more
02-18 22:13:55.902 15491 15607 E AndroidRuntime: Caused by: java.net.SocketException: Permission denied
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        at java.net.ServerSocket.bind(ServerSocket.java:377)
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:838)
02-18 22:13:55.902 15491 15607 E AndroidRuntime:        ... 3 more
02-18 22:13:55.905 15491 15607 E AndroidRuntime: Error reporting crash
02-18 22:13:55.905 15491 15607 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-18 22:13:55.905 15491 15607 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-18 22:13:55.905 15491 15607 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
02-18 22:13:55.905 15491 15607 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5133)
02-18 22:13:55.905 15491 15607 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
02-18 22:13:55.905 15491 15607 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-18 22:13:55.905 15491 15607 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
02-18 22:14:05.165 15801 15801 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 15801 (netstat)
02-18 22:14:05.185 15801 15801 F libc    : failed to resend signal during crash: Operation not permitted
--- crash end ---
--- brevent start ---
02-18 22:13:55.558 15491 15491 D BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
02-18 22:13:55.562 15491 15607 D BreventServer: Brevent Server 0.6.1 started
02-18 22:13:55.573 15491 15607 D BreventServer: brevent user: 0, uid: 2000
02-18 22:13:55.574 15491 15607 D BreventServer: brevent data directory: /data/user_de/0/com.android.shell
02-18 22:13:55.620 15491 15607 D BreventServer: loaded brevent list
02-18 22:13:55.621 15491 15607 D BreventServer: loaded brevent conf
02-18 22:13:55.706 15491 15607 D BreventServer: checking
02-18 22:13:55.868 15491 15607 I BreventServer: power_screen_state, tag: 2728, event: 7
02-18 22:13:55.870 15491 15607 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-18 22:13:55.876 15491 15607 I BreventServer: am_new_intent, tag: 30003, event: 2
02-18 22:13:55.878 15491 15607 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-18 22:13:55.878 15491 15607 I BreventServer: am_proc_start, tag: 30014, event: 4
02-18 22:13:55.882 15491 15607 I BreventServer: am_switch_user, tag: 30041, event: 5
02-18 22:13:55.882 15491 15607 I BreventServer: am_focused_activity, tag: 30043, event: 1
02-18 22:13:55.902 15491 15607 D BreventLoader: Can't run brevent server02-18 22:13:55.902 15491 15607 D BreventLoader: java.lang.reflect.InvocationTargetException
02-18 22:13:55.902 15491 15607 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-18 22:13:55.902 15491 15607 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-18 22:13:55.902 15491 15607 D BreventLoader:         at java.lang.Thread.run(Thread.java:761)
02-18 22:13:55.902 15491 15607 D BreventLoader: Caused by: java.net.SocketException: Permission denied
02-18 22:13:55.902 15491 15607 D BreventLoader:         at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-18 22:13:55.902 15491 15607 D BreventLoader:         at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-18 22:13:55.902 15491 15607 D BreventLoader:         at java.net.ServerSocket.bind(ServerSocket.java:377)
02-18 22:13:55.902 15491 15607 D BreventLoader:         at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-18 22:13:55.902 15491 15607 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:838)
02-18 22:13:55.902 15491 15607 D BreventLoader:         ... 3 more
02-18 22:13:55.904 15491 15491 D BreventLoader: Brevent Server quit in 30 seconds, quit
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
3|A0001:/ #

**Comment by liudongmiao** [comment]
运行并不需要su，你可以直接运行看看。

没有网络权限这事，我不想处理。

**Comment by wangyou** [comment]
这是直接运行的结果…前面的没有复制上……
/data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so             <
* daemon not running. starting it now on port 5038 *
error: cannot open '/data/local/tmp/adb.10157.log': Permission denied
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so        <
/sbin/su: invalid option -- d

Usage: su [options] [--] [-] [LOGIN] [--] [args...]

Options:
  --daemon                      start the su daemon agent
  -c, --command COMMAND         pass COMMAND to the invoked shell
  --context context             Change SELinux context
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -u                            display the multiuser mode and exit
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk
2|A0001:/ $ su
A0001:/ # adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/libbootsata/app/me.piebridge.brevent-1/lib/arm/libbootstrap.s                   o     <
* daemon not running. starting it now on port 5038 *
* daemon started successfully *
error: no devices found
1|A0001:/ #
![screenshot_20170220-072200](https://cloud.githubusercontent.com/assets/3582935/23107795/5c08f340-f6c9-11e6-832b-d28adadab738.png)

**Comment by liudongmiao** [comment]
duplicate #50, #72

**Comment by liudongmiao** [comment]
建议使用电脑连接，然后看看。目前我不知道是什么问题。理论上，shell 应该有网络权限。

**Comment by wangyou** [comment]
这是刚才运行的…最前面的是没有su
后面是su下运行的
/data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so             <
error: no devices found
1|A0001:/ $ su
A0001:/ # adb -d shell /data/app/me.piebridge.brevent-2/lib/arm/libbootsata/app/me.piebridge.brevent-2/lib/arm/libbootstrap.s                   o     <
error: no devices found
1|A0001:/ #

**Comment by wangyou** [comment]
刚才换了一个终端重试了一下
![screenshot_20170220-133615](https://cloud.githubusercontent.com/assets/3582935/23113228/5eccabca-f6fc-11e6-9e6f-4c4e45126122.png)

**Comment by liudongmiao** [comment]
1. 不要执行 su

2. 当你在手机里以后，执行的命令去掉 adb -d shell，只保留那个后面的文件路径。

**Comment by wangyou** [comment]
/data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so  cannot be run as u0_a75
这是什么情况？

**Comment by wangyou** [comment]
我cd 到/data/app/me.piebridge.brevent-2/lib/arm下
执行./libbootstrap.so还是显示
cannot be run as u0_a75
这是什么情况？

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
