### ISSUE TITLE
Pixel 7.1.1 上无法正常工作 - 依赖 adb 版本？

### ISSUE THREAD

**Issue by 7nights** [liudongmiao/Brevent#74]
adb 输入之后显示 checking....successfully , 能正常载入 App 列表, 但是无法执行任何操作, 选择一些应用然后点 brevent 没有任何反应……每次退出应用重新打开都要重新执行一次 adb 才能看到 app 列表……

**Comment by liudongmiao** [comment]
if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

我自己就是pixel最新版，你说不能用，肯定是使用不当。没有日志，我啥也处理不了。

**Comment by 7nights** [comment]
@liudongmiao 不好意思额当时只是想反应下问题，刚重尝试了一次抓了下日志：

![brevent1](https://cloud.githubusercontent.com/assets/3193621/23098973/92088b32-f696-11e6-9fc4-bb43e53af096.png)

![brevent2](https://cloud.githubusercontent.com/assets/3193621/23098972/9204768c-f696-11e6-98dc-54589a82ece8.png)

**然后，使用方式&步骤：**

1. 随便选择3个应用，然后点右上角的那个 "禁止" 按钮。
![brevent3](https://cloud.githubusercontent.com/assets/3193621/23098985/ec896a72-f696-11e6-9f87-06db6118f9f2.png)

2. 点击之后这3个应用被 uncheck 了，除此之外没有任何反应。
![brevent4](https://cloud.githubusercontent.com/assets/3193621/23098991/10b12b42-f697-11e6-9c9c-bdd3a491dd86.png)

3. 另外顺带问一下，back键返回之后就又变成了开始打开的界面，让运行 adb 命令才能展示 list 是正常的吗？

然后，对 adb(Android Debug Bridge version 1.0.31) 的版本不会有要求吧？

**Comment by lancelotly** [comment]
@7nights 感觉对 adb 的确有要求…第一次使用从这里 （http://adbshell.com/downloads）下载的 1.0.32 版本和你一样情况复现。之后从 https://developer.android.com/studio/releases/platform-tools.html#download 下载最新 1.0.36 版本后正常黑幕~ 💯

**Comment by lancelotly** [comment]
@liudongmiao 为什么会依赖 adb 版本呀？好像酷安那边也有好多用 adb 旧版本不行的，或者应用简介里写一下支持的 adb 版本呢

**Comment by liudongmiao** [comment]
我认真看了下。

在 1.0.32 里，执行完命令，直接退出了，然后会把 brevent_server 给杀掉。解决办法，分两次进行。

在 1.0.36 里，一次执行完命令，不会退出。所以这种是可以的。

**Comment by lancelotly** [comment]
原来如此～

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
