### ISSUE TITLE
[Feature request]希望在[Brevent timeout]中增加增加[立即]的选项

### ISSUE THREAD

**Issue by moonheart** [liudongmiao/Brevent#75]
希望在[Brevent timeout]中增加增加[立即]的选项，目前可选的是Never和五分钟到1小时，可以增加一个 不超时，[立即处理]的选项吗

**Comment by moonheart** [comment]
目前变通的处理方法是 关屏再开屏，可以使所有阻止的应用处于Standby状态

**Comment by liudongmiao** [comment]
呃，确实存在误会。

这个超时，指后台应用超时，不是指处理的时间。

处理的时候，从 3 秒到 60 秒不等，取决于操作。比如你正停留在某个应用上，60 秒后处理；比如你回到桌面，3 秒后处理；如果被服务唤醒，30 秒后处理；黑屏，立即处理。

这样是为了黑域服务本身不对系统造成过大的影响。虽然不能切断唤醒，但是更要减少由于被杀，某些应用不能使用。

我会在下个版本中更新下描述。

**Comment by moonheart** [comment]
谢谢回复。

我分别尝试了返回键，home键，停留某应用，以及关屏操作，确实是如您所说，是我理解有误。

可以麻烦说明下[Brevent timeout]这个选项设置的时间是在什么地方使用的吗？

**Comment by moonheart** [comment]
在0.7版本已经看到新的描述，感谢
