### ISSUE TITLE
将酷安加入黑域处理后，编写回复用时比较长的情况下，发送异常

### ISSUE THREAD

**Issue by 849506054** [liudongmiao/Brevent#76]
将酷安加入到黑域休眠名单之后，如果我写回复时写的比较久，那么写完之后点发送会发送不出去
重新切一下酷安的后台才能够发送
一下是个人测试的一个小结：
场景1：使用wifi网络，酷安黑域处理。结果：复现问题，回复发送异常
场景2：使用4g网络，酷安黑域处理。结果：复现问题，回复发送异常
场景3：使用4g网络，移除酷安黑域处理。结果：未复现问题，回复正常发送
场景4：使用wifi网络，移除酷安黑域处理。结果：未复现问题，回复正常发送

系统是6.0，氧os

**Comment by 849506054** [comment]
貌似我用via提交这个问题的时候，和同样复现了这个问题！

**Comment by 849506054** [comment]
多次测试后，确实是黑域的原因

**Comment by 849506054** [comment]
应该不仅仅局限于酷安，浏览器好像也受到影响

**Comment by liudongmiao** [comment]
确实是个问题。
https://github.com/liudongmiao/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/server/BreventServer.java#L255
不知道这里，我为啥直接 block 了，应该上面那样，使用 blocking.add ...

这样吧，先把黑域应用时机设大点。

**Comment by 849506054** [comment]
也就是说，当使用输入法码字时。
黑域认为已经离开之前的应用了，所以开始进行处理导致的吗😂
这样的话，扩大应用时机并不能彻底解决啊😅

**Comment by 849506054** [comment]
判断一下，打开输入法应用之后，不对离开之前的应用进行处理？不知是否可行？
应该不难判断吧，黑域本身是强制用户不对输入法处理的

**Comment by liudongmiao** [comment]
上面说了，把那句话改下就好。黑域不会处理在前台（包括多个桌面），以及前台back会返回的所有应用

**Comment by 849506054** [comment]
ok的，那这个关闭了吧。留前面那个就成
