### ISSUE TITLE
对于音乐播放器处理逻辑上有问题

### ISSUE THREAD

**Issue by 849506054** [liudongmiao/Brevent#77]
后台播放几首之后会自动休眠掉，即使是在开屏状态下

**Comment by liudongmiao** [comment]
所有前台服务，必须要有活动…也就是说，home切吧…还想过判断前台服务，问题是就没有退出机制了，只能你自己离开。

**Comment by 849506054** [comment]
这个我是home切到后台的，莫非是网易云的问题?因为我发现播放本地音乐的话是正常的，如果是网络歌单或者是私人fm就会出现上述情况

**Comment by liudongmiao** [comment]
现在是那个bug嘛…等我晚上回去发个更新

**Comment by 849506054** [comment]
好吧，谢谢~

**Comment by liudongmiao** [comment]
此外，休眠之后，不能听网络音乐的的，因为不能访问网络，但本地音乐还可以，这是安卓设计。此外，一旦从最近列表划掉，就会结束。

**Comment by 849506054** [comment]
嗯，应该是这个原因了。
