### ISSUE TITLE
切换应用后休眠了前一个应用，是否太激进？

### ISSUE THREAD

**Issue by 849506054** [liudongmiao/Brevent#79]
跟之前提到的码字问题类似吧，此种做法是不是太过激进了？
如下场景，正用着浏览器看网页，此时有qq消息于是回去回复消息
再切回浏览器时，浏览器已经被休眠，点击网页链接无法正常打开，需要刷新一次...极度影响体验

也许说这类应用不加入黑域处理，但是这种场景在实际使用上还是非常多的，不能加入处理的应用会越来越多，那么黑域也没有存在的意义了

个人建议是，除非是手动back或者是home了否则不处理
甚至是在home之后，不关闭屏幕都不处理

**Comment by 849506054** [comment]
这方面我觉得绿色做的非常好，所有的休眠应用时机都是在关闭屏幕一段时间后再进行处理

所以在用新版黑域之前，我都是使用补丁版（强行停止）+绿色守护（休眠）的方式控制

需要即时停止的back，需要在关屏后休眠的home

新版黑域休眠机制相比前代，确实太激进了，至少前代在切换任务时不会停止掉上一个应用

**Comment by liudongmiao** [comment]
前面说了，是bug，写错了…

**Comment by 849506054** [comment]
那好的，期待更新
