### ISSUE TITLE
黑域按钮没有反应

### ISSUE THREAD

**Issue by AkazaDorian** [liudongmiao/Brevent#81]
每次开启应用都提示需要输入命令，输入之后进入主界面选择黑域也没有任何效果

**Comment by lancelotly** [comment]
@AkazaDorian 从 https://developer.android.com/studio/releases/platform-tools.html#download 下载 adb最新 1.0.36 版本试试看~ https://github.com/liudongmiao/Brevent/issues/74

**Comment by jackplus** [comment]
@AkazaDorian 从 https://developer.android.com/studio/releases/platform-tools.html#download 下载 adb最新 1.0.36 版本试试看~ #74

果然管用！

**Comment by AkazaDorian** [comment]
@AkazaDorian 从 https://developer.android.com/studio/releases/platform-tools.html#download 下载 adb最新 1.0.36 版本试试看~ #74 

管用，谢谢！
