### ISSUE TITLE
三星note5 6.0.1黑域无效

### ISSUE THREAD

**Issue by 940842546** [liudongmiao/Brevent#82]
adb success的 黑域界面也提示已黑域的 但是不管是按返回键还是关屏 重新打开黑域界面加载出的时间还是继续走 打开应用就是之前的状态 没有被停止或者休眠 应该是三星有限制

**Comment by 940842546** [comment]
后台切换页面关软件能关掉😂😂😂但是不确定是三星的智能管理器干的还是黑域干的

**Comment by liudongmiao** [comment]
这个时间是指离开后台应用的时候，在你重新进入就会改变。如果你使用 BACK 退出，则不会有(某些非正常BACK除外)。休眠不取决于这个时间，取决于下次处理时机(参考工作模式)和黑域后台应用时机。

**Comment by 940842546** [comment]
qq贴吧微信back退出还是有这个时间 常用软件里只有酷安back会没有时间 但是酷安还是在正在运行里1 服务, 1 缓存, 共 2 个进程 然后右侧是那个禁止的符号

**Comment by 940842546** [comment]
如下图
![Uploading Screenshot_20170220-135903.png…]()

**Comment by 940842546** [comment]
图片好像插不进 直接上链接http://www.cjlu.net.cn:3000/download?file=1cjmjug5bvcgnwmi

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
