### ISSUE TITLE
app无法持续显示软件信息

### ISSUE THREAD

**Issue by Vtrust** [liudongmiao/Brevent#85]
在小米5 lineage os 2月14版本 上app无法持续显示软件状态 感觉就是刚刚打开的时候显示正确之后就一直不改变了

**Comment by liudongmiao** [comment]
if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
