### ISSUE TITLE
源码能编译自用吗？

### ISSUE THREAD

**Issue by chenguangtu** [liudongmiao/Brevent#86]

**Comment by aviraxp** [comment]
WTFPL，所以。。

**Comment by liudongmiao** [comment]
可以。代码是 WTFPL，但是有几点要注意下：

1. 修改之后，不建议继续使用黑域的名义发布。
2. logo 不是 WTFPL，是商业授权。

就代码层面来说，是 WTFPL；就打包的应用来说，更多层面属于 BSD 或类似。

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。

**Comment by liudongmiao** [comment]
@chenguangtu 需要注意下，0.9 版本以后，brevent-server 单独出去，并且你编译时没有任何提示，只是最终无法运行。

https://github.com/liudongmiao/Brevent/commit/f70169786fc26bd3f6341c548f09129e368ef0db

**Comment by chenguangtu** [comment]
明白，谢谢
