### ISSUE TITLE
Translation for Traditional Chinese

### ISSUE THREAD

**Issue by a7811925** [liudongmiao/Brevent#88]
Hello, the black domain of this program is very easy to use, do not know if the next time to join the traditional Chinese?

**Comment by liudongmiao** [comment]
Please help to translate.

**Comment by a7811925** [comment]
Can you give me a simplified Chinese template so that I can help translate it into traditional Chinese?

**Comment by aviraxp** [comment]
https://github.com/liudongmiao/Brevent/blob/master/brevent/src/main/res/values/strings.xml
https://github.com/liudongmiao/Brevent/blob/master/donation/src/main/res/values/strings.xml

**Comment by a7811925** [comment]
[chinese TW.zip](https://github.com/liudongmiao/Brevent/files/787068/chinese.TW.zip)

已完成，感謝您

**Comment by liudongmiao** [comment]
@a7811925 能帮忙直接 fork，然后提交 pull request 么?

这样，方便后续继续维护。

此外，请暂时添加一个新的翻译项，表明翻译者身份。

```xml
<string name="translator">...</string>
```

**Comment by a7811925** [comment]
@liudongmiao 前面是什麼意思?

**Comment by liudongmiao** [comment]
呃，fork 就是，到主页：https://github.com/liudongmiao/Brevent 点击 fork 。

这样的话，相当于你有了 Brevent 这个项目，可以改，改完之后，推给我就好。

此外，我发现了极少翻译有问题，比如 process 这个，以及绝大部分好像和简体中文并没有太多差别，除去几个专有名字外。

**Comment by a7811925** [comment]
@liudongmiao 是的，和簡體中文沒太大差別，有些用語不同，但台灣不使用簡體中文，所以希望可以增加繁體中文

**Comment by a7811925** [comment]
@liudongmiao https://github.com/a7811925/Brevent/pull/1 是不是像這樣?
抱歉我不太會用這網頁

**Comment by liudongmiao** [comment]
0.8.6 已经开始试验性支持。
