### ISSUE TITLE
如果services.jar 里有多个 classes.dex classes2.dex .....

### ISSUE THREAD

**Issue by zinian** [liudongmiao/Brevent#9]
最后打过补丁的 services.jar  因为没有classes2.dex  ，会不能开机。
这个教程里 说明下手动添加吧

**Comment by zinian** [comment]
Android 4.4 或者非 odex 优化版本 (services.jar 在 1M 以上)
命令行> jar -cvf services.jar classes.dex
单独改成     jar -```uvf``` services.jar classes.dex
可以避免这个情况

**Comment by liudongmiao** [comment]
能提交 pr 么？

说实话，这个问题更复杂，有的还带其它的文件。

**Comment by zinian** [comment]
不是，jar  -uvf  参数是在原 services.jar 添加新增或者替换指定的 classes.dex 文件，  
       -cvf  参数是创建新 services.jar 并添加指定文件 classes.dex
pr 提交了，你看下。。。
