### ISSUE TITLE
按back键只能休眠 不能实现强杀

### ISSUE THREAD

**Issue by amdth** [liudongmiao/Brevent#91]
黑域版本 0.5-0.7
手机 Xperia X
安卓系统 7.0
应用 QQ国际版
不知道其他应用是否如此

**Comment by liudongmiao** [comment]
黑域只强杀你不使用的应用，目前只有两种情况：

- 应用被恶意唤醒
- 应用被你从最近列表划掉

其它任何时机，都执行休眠操作。目前没有考虑放开可选。
对于 6.0 及以上系统，休眠是安全的操作，可放心使用。
如果你非要纠结于这点，请使用其它类似软件，或者等，当然，可能永远等不到。

**Comment by amdth** [comment]
非常感谢回复
这封邮件使我明白了黑域的作用方式。我本以为是软件bug呢。建议老大写一些简单的使用说明以及某些操作所产生的效果，如此一来就会少了很多小白整天提问

2017年2月20日 上午9:55 於 "Liu DongMiao" <notifications@github.com> 寫道：

**Comment by wudimenghuan** [comment]
这个休眠做的非常不错，使得大内存的手机可以充分发挥内存的缓存作用。

**Comment by liudongmiao** [comment]
其实吧，在第四屏，说了的。可能都没认真看。。。
