### ISSUE TITLE
只有在开发者选项中开启了“在设备上永久存储日志记录器数据”，才能休眠 - 特定 ROM 无事件日志

### ISSUE THREAD

**Issue by ynuance** [liudongmiao/Brevent#93]
已经试验了几次，确认开启这个选项后，才会显示已休眠分类。不开启就不能休眠。

**Comment by liudongmiao** [comment]
我的机器并没有这个选项，不过有可能相关。

请这样测试一下，在开关这个选项时，先执行 `adb logcat -b events -c`(清空事件日志) 然后执行 `adb logcat -b events -d`(打印事件日志) ，看有没有数据。

黑域使用事件日志来决定什么时候处理，如果没有事件，基本上就是不处理(只在更新黑域清单时处理一下)。

**Comment by ynuance** [comment]
我之前（昨天还是前天）试验过在关闭这个选项的情况下，用你之前提供的adb命令无法获取日志，输入命令没反应。开启之后才会输出日志。
现在不方便测试你刚刚提供的这两个命令。
现在看来确实是开启这个选项黑域才能工作。
我用的rom是AICP 12（N7.1.1）。不知道是不是AICP独有的选项，可能Lineage OS或是Ressurection Remix或是魔趣也有这个选项。

**Comment by RedL0tus** [comment]
我看了下，至少 LineageOS 14.1 是沒有這個選項的。

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
