### ISSUE TITLE
Nexus 6P 7.1.1 黒域好像不起作用

### ISSUE THREAD

**Issue by panlivictory** [liudongmiao/Brevent#94]
在里面点选要阻止的进程，好像后面也不出符号

**Comment by liudongmiao** [comment]
看下这个 #74 

使用最新版本的 adb 看下。

windows: http://dl.google.com/android/repository/platform-tools_r25.0.3-windows.zip
mac: http://dl.google.com/android/repository/platform-tools_r25.0.3-macosx.zip
linux: http://dl.google.com/android/repository/platform-tools_r25.0.3-linux.zip

我自己也是 7.1.1，没有啥问题的。

**Comment by panlivictory** [comment]
谢谢作者，按你的方法可以了

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
