### ISSUE TITLE
adb安装报以下错误 - adb 给的是 su shell

### ISSUE THREAD

**Issue by usc** [liudongmiao/Brevent#95]
hi
我用adb安装后，报下面的错误
`please` run with 'su shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so'`
请帮忙看看

手机小米4，Android 7.1.1，黑域从gp下载

![screenshot_20170220-130035](https://cloud.githubusercontent.com/assets/1018826/23112627/a57dbddc-f76c-11e6-825a-c9bba7cf4e29.png)

**Comment by liudongmiao** [comment]
你的系统给了 su 的权限，目前不建议使用 root 运行，这样也很不安全。

建议去系统相关设置，是否可以关闭 su shell，有可能是安装了supersu 或之类软件导致。

**Comment by usc** [comment]
嗯，已经解决（`adb unroot` ），多谢。
建议: so脚本中 name=`id -un` 判断root或者shell是否有必要？如果去掉是否就可以在类似终端模拟器中运行了（还未尝试）

**Comment by chm512512** [comment]
把supersu 删了 ？

**Comment by liudongmiao** [comment]
因为root用户肯定没有权限，所以必须用shell…下个版本我还是加上限制吧，必须id与context都与正常的shell一样才给运行。

**Comment by chm512512** [comment]
已经搞定了…问题我也顺手关闭了…

**Comment by p2112797797** [comment]
@chm512512  也是这种情况 最后你是怎么处理的
@usc

**Comment by liudongmiao** [comment]
@p2112797797 `adb usb` 或者  `adb unroot` 看下。

**Comment by chm512512** [comment]
stop adbd && setprop service.adb.root 0 && start adbd &

这个会退出root，以后再用黑域命令就行了。
本人Nitrogen-OS

@p2112797797
adb版本我自己的我记得是36 所以应该不存在作者说的版本问题，不过我不确定adb是否完整。不过我是在官网下的。

**Comment by chm512512** [comment]
stop adbd && setprop service.adb.root 0 && start adbd &

这个会退出root，以后再用黑域命令就行了。
本人Nitrogen-OS

@p2112797797
因为我之前弄了某些东西所以找了很多adb，
adb版本我自己的我记得是36 所以应该不存在作者说的版本问题，不过我不确定adb是否完整。不过我是在官网下的。

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
