### ISSUE TITLE
本来用的好好的没重启，装完QQ后打开黑域突然提示“请启动服务”且执行命令成功仍然无效

### ISSUE THREAD

**Issue by zglzone** [liudongmiao/Brevent#96]
没有重启，没有升级，黑域app添加到各种白名单中，手机是3T氢OS3.0正式版未root未解锁
而且现在再连到电脑上执行命令虽然显示成功，但是app还是没检测到
![1](https://cloud.githubusercontent.com/assets/6051672/23112887/eed5bc8a-f76e-11e6-954c-10ce758f2f9e.png)

**Comment by liudongmiao** [comment]
给下 crash 日志： `logcat -b crash -d`，直接文件就好，不要截图。

此外，你是怎么启动的？感觉就是就程序不断启动进入，并且没有退出。

**Comment by liudongmiao** [comment]
此外，请使用最新的 adb，版本应该是 1.0.36

`adb version` 可以获取。可以从这里下载：

[adb-win]: http://dl.google.com/android/repository/platform-tools_r25.0.3-windows.zip
[adb-mac]: http://dl.google.com/android/repository/platform-tools_r25.0.3-macosx.zip
[adb-linux]: http://dl.google.com/android/repository/platform-tools_r25.0.3-linux.zip

**Comment by zglzone** [comment]
果然是，我刚看其他的问题里面说可以尝试一下这个，我就更新下试了没有问题了，感觉这个好坑
