### ISSUE TITLE
教程 - 什么是后台应用 与 黑域什么时候工作

### ISSUE THREAD

**Issue by shywu** [liudongmiao/Brevent#97]
从0.6版升级到0.7版，升级完后打开黑域并不会看到简介或者升级日志。如果能在主菜单里加上简介或者教程之类的最好了。不太明白新增的“黑域工作模式”控制的东西和“黑域后台应用时间”控制的东西差异在哪里。多谢！

**Comment by liudongmiao** [comment]
那几屏，又没有更新。你要看到的话，清空数据就看到了，酷安或者 Play 商店里，截图里都有。

一个是针对所有应用的检查模式，一个是后台应用。前者针对什么时候开启检查，后面那个是，当你离开一个应用以后，比如 HOME，可以允许不受限制多久才处理。

举个例子。

你打开酷安，然后 HOME 或者其它方式切到后台，就会显示时间了。这个能开心的运行多久，是黑域后台应用时间控制的。如果你 BACK 切出了，直接是没有显示的，因为你已经退出，不存在后台。

好，上面那个以后，什么时间点触发，以及还存在一些被恶意唤醒的程序，什么时候处理，这些是工作模式的定义。像绿色守护，可能是要息屏，而黑域则不同，处理随时存在，在你切换应用时，回到主界面时，被恶意唤醒时，都会叫黑域开始工作。默认的话，延迟一点点，免得黑域服务耗电过多。你也可以直接让黑域在切换应用，回到主界面，被恶意唤醒时马上执行清理操作。

你可以帮忙整下。

**Comment by shywu** [comment]
谢谢耐心回答，自以为这下明白多了。看了酷安的截图才发现一个问题。第5张图显示“正在运行 3”和“已经休眠 4”，但是我的黑域界面里面从来没看到过“已经休眠”的清单，只有“正在运行”和“没有运行”。我的“黑域后台应用时间“设置是5分钟。在“正在运行”里面会有这种情况：
Outlook 1个服务进程 25分钟 (我知道我没有主动退出Outlook，但是超过5分钟没有把它切回前台是不是应该变成“已经休眠”呢？我所有应用里面只有输入法和微信没有加入黑域清单)
cnBeta 1个缓存进程 1小时40分钟 (这个忘了有没有主动Back退出过，但是肯定有超过5分钟没有使用了。黑域里面两个关于Back的设置都是打开的状态)

确实感觉黑域里面的介绍文字对于普通用户来说不是特别好懂，感觉像是高手切磋的时候说的话。回头我会看看能不能提出一点修改建议。多谢！

**Comment by 940842546** [comment]
我这也是只有正在运行和没有运行 然后超时之后应用还在后台 我是按back退的应用

**Comment by amdth** [comment]
按照我的理解：上面两位的问题是没有休眠，应该是第三方ROM的问题，可能你们的ROM不支持休眠吧

**Comment by shywu** [comment]
之前我以为变成“缓存进程”就表示休眠了。看来不是这样。Lineage OS 7.1，不知道怎样检查系统是否有休眠功能。

**Comment by amdth** [comment]
我在红米1S上也刷过Lineage OS 7.1 同样没有休眠 我也不知道怎样检查，不过你可以看看酷安评论区试试其它的第三方系统

2017年2月21日 下午1:37 於 "shywu" <notifications@github.com> 寫道：

**Comment by 940842546** [comment]
我不是第三方rom，三星官方的rom

**Comment by amdth** [comment]
你可以看看酷安评论区，里面也有三星的使用者

2017年2月21日 下午2:06 於 "940842546" <notifications@github.com> 寫道：

我不是第三方rom，三星官方的rom

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/liudongmiao/Brevent/issues/97#issuecomment-281253651>,
or mute the thread

**Comment by amdth** [comment]
三星的ROM和第三方又有什么区别呢？

2017年2月21日 下午2:16 於 "k c.c" <zuiyufack@gmail.com> 寫道：

你可以看看酷安评论区，里面也有三星的使用者

2017年2月21日 下午2:06 於 "940842546" <notifications@github.com> 寫道：

我不是第三方rom，三星官方的rom

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/liudongmiao/Brevent/issues/97#issuecomment-281253651>,
or mute the thread
