### ISSUE TITLE
对影俊这个app无法加入到黒域

### ISSUE THREAD

**Issue by panlivictory** [liudongmiao/Brevent#99]
包名为com.github.shadowsocks，从play市场下载的

**Comment by liudongmiao** [comment]
对于 vpn 类，由于绝大部分时候，使用时都不会打开软件，而是直接点击某个快捷方式使用，而这种没有主动打开的应用，基本都会被强行停止。为了体验，所有 vpn 类软件，只要添加了账号，都不能被加入。

后期可能会识别哪些是正在运行的 vpn，对于这类不处理。但目前来说，只能不允许加入。你可以直接去设置里，把它从vpn里去掉，就可以继续添加。
